import Mathlib.Algebra.Homology.ShortComplex.ShortExact
import Mathlib.CategoryTheory.Abelian.Basic
import Mathlib.CategoryTheory.Adjunction.Limits
import Mathlib.GroupTheory.FreeAbelianGroup

/-!
# The Grothendieck group of an abelian category

Let `C` be an abelian category. Its *Grothendieck group* `K₀(C)` is the abelian group generated
by symbols `[X]`, one for each object `X` of `C`, subject to the relations `[X₂] = [X₁] + [X₃]`
for every short exact sequence `0 ⟶ X₁ ⟶ X₂ ⟶ X₃ ⟶ 0` (A. Grothendieck; see
C. A. Weibel, *The K-book*, Chapter II, §6). Since every isomorphism `X ≅ Y` fits into a short
exact sequence `0 ⟶ 0 ⟶ X ⟶ Y ⟶ 0`, the class `[X]` depends only on the isomorphism class of `X`,
so this is the usual free abelian group on isomorphism classes modulo the short exact sequence
relations, without any smallness hypothesis: `DG.AbelianK0 C` lives in the universe of the
objects of `C`. Short exact sequences are Mathlib's `CategoryTheory.ShortComplex.ShortExact`.

The Grothendieck group of a pretriangulated category is `DG.K0` (`DG/K0/Triangulated.lean`);
the Euler characteristic of a bounded complex and the comparison with `DG.K0` of the derived
category are in `DG/K0/Euler.lean`.

## Main definitions

* `DG.AbelianK0 C`: the Grothendieck group, the quotient of `FreeAbelianGroup C` by the subgroup
  `DG.AbelianK0.relations C` generated by `of X₂ - of X₁ - of X₃` for the short exact sequences
  `0 ⟶ X₁ ⟶ X₂ ⟶ X₃ ⟶ 0`.
* `DG.AbelianK0.mk X`: the class `[X]` of an object.
* `DG.AbelianK0.lift`: the universal property, producing a homomorphism `AbelianK0 C →+ G` from
  a function `C → G` which is additive on short exact sequences; `DG.AbelianK0.addMonoidHom_ext`
  is the corresponding extensionality lemma and `DG.AbelianK0.induction_on` the induction
  principle.
* `DG.AbelianK0.map F`: the homomorphism `AbelianK0 C →+ AbelianK0 D` induced by an exact functor
  `F : C ⥤ D` (one preserving finite limits and finite colimits), with `DG.AbelianK0.map_id` and
  `DG.AbelianK0.map_comp`.
* `DG.AbelianK0.mapEquiv e`: the isomorphism `AbelianK0 C ≃+ AbelianK0 D` induced by an
  equivalence `e : C ≌ D`.

## Main results

* `DG.AbelianK0.mk_X₂`: `[S.X₂] = [S.X₁] + [S.X₃]` for a short exact sequence `S`.
* `DG.AbelianK0.mk_zero`, `DG.AbelianK0.mk_eq_zero_of_isZero`: the class of a zero object is `0`.
* `DG.AbelianK0.mk_eq_of_iso`: isomorphic objects have the same class.
* `DG.AbelianK0.mk_biprod`: `[X ⊞ Y] = [X] + [Y]`.
* `DG.AbelianK0.mk_eq_mk_kernel_add_mk_coimage`, `DG.AbelianK0.mk_eq_mk_coimage_add_mk_cokernel`:
  for `f : X ⟶ Y`, `[X] = [ker f] + [coim f]` and `[Y] = [coim f] + [coker f]`.
* `DG.AbelianK0.mk_X₂_eq_mk_homology_add`: for any short complex `S : X₁ ⟶ X₂ ⟶ X₃`,
  `[X₂] = [H(S)] + [coim S.f] + [coim S.g]`. This is the degreewise identity behind the
  Euler characteristic formula `χ(K) = Σ (-1)ⁿ [Hⁿ(K)]`.
-/

namespace DG

open CategoryTheory Category Limits ZeroObject

universe v u

variable (C : Type u) [Category.{v} C] [Abelian C]

namespace AbelianK0

/-- The subgroup of the free abelian group on the objects of `C` generated by the elements
`of S.X₂ - of S.X₁ - of S.X₃`, for `S` running through the short exact sequences of `C`.
The Grothendieck group `DG.AbelianK0 C` is the quotient by this subgroup. -/
def relations : AddSubgroup (FreeAbelianGroup C) :=
  AddSubgroup.closure {x | ∃ S : ShortComplex C, S.ShortExact ∧
    x = FreeAbelianGroup.of S.X₂ - FreeAbelianGroup.of S.X₁ - FreeAbelianGroup.of S.X₃}

end AbelianK0

/-- The Grothendieck group `K₀(C)` of an abelian category `C`: the free abelian group on the
objects of `C` modulo the relations `[X₂] = [X₁] + [X₃]` for every short exact sequence
`0 ⟶ X₁ ⟶ X₂ ⟶ X₃ ⟶ 0` (Grothendieck; Weibel, *The K-book*, II.6). The class of an object `X`
is `DG.AbelianK0.mk X`. -/
def AbelianK0 : Type u := FreeAbelianGroup C ⧸ AbelianK0.relations C

namespace AbelianK0

instance : AddCommGroup (AbelianK0 C) := QuotientAddGroup.Quotient.addCommGroup _

/-- The quotient map from the free abelian group on the objects of `C` to `K₀(C)`. -/
def mkHom : FreeAbelianGroup C →+ AbelianK0 C := QuotientAddGroup.mk' _

variable {C}

/-- The class `[X] ∈ K₀(C)` of an object `X` of `C`. -/
def mk (X : C) : AbelianK0 C := mkHom C (FreeAbelianGroup.of X)

theorem mkHom_of (X : C) : mkHom C (FreeAbelianGroup.of X) = mk X := rfl

theorem mkHom_surjective : Function.Surjective (mkHom C) := QuotientAddGroup.mk'_surjective _

theorem relation_mem {S : ShortComplex C} (hS : S.ShortExact) :
    FreeAbelianGroup.of S.X₂ - FreeAbelianGroup.of S.X₁ - FreeAbelianGroup.of S.X₃ ∈
      relations C :=
  AddSubgroup.subset_closure ⟨S, hS, rfl⟩

/-- The defining relation of `K₀(C)`: `[S.X₂] = [S.X₁] + [S.X₃]` for a short exact sequence
`S`. -/
theorem mk_X₂ {S : ShortComplex C} (hS : S.ShortExact) : mk S.X₂ = mk S.X₁ + mk S.X₃ := by
  have h := (QuotientAddGroup.eq_zero_iff _).2 (relation_mem hS)
  change mkHom C _ = 0 at h
  rwa [map_sub, map_sub, sub_sub, sub_eq_zero] at h

/-- Induction principle for `K₀(C)`: every element is obtained from the classes of objects by
sums and negatives. -/
theorem induction_on {p : AbelianK0 C → Prop} (x : AbelianK0 C) (zero : p 0)
    (mk : ∀ X : C, p (mk X)) (neg : ∀ x, p x → p (-x)) (add : ∀ x y, p x → p y → p (x + y)) :
    p x := by
  obtain ⟨y, rfl⟩ := mkHom_surjective x
  induction y using FreeAbelianGroup.induction_on with
  | C0 => simpa using zero
  | C1 X => exact mk X
  | Cn y hy => rw [map_neg]; exact neg _ hy
  | Cp y z hy hz => rw [map_add]; exact add _ _ hy hz

section lift

variable {G : Type*} [AddCommGroup G]

/-- Two homomorphisms out of `K₀(C)` which agree on the classes of objects are equal. -/
@[ext]
theorem addMonoidHom_ext ⦃f g : AbelianK0 C →+ G⦄ (h : ∀ X : C, f (mk X) = g (mk X)) :
    f = g := by
  apply QuotientAddGroup.addMonoidHom_ext
  exact FreeAbelianGroup.lift.ext _ _ h

/-- The universal property of `K₀(C)`: a function `f : C → G` to an abelian group which satisfies
`f S.X₂ = f S.X₁ + f S.X₃` for every short exact sequence `S` induces a homomorphism
`AbelianK0 C →+ G` sending `[X]` to `f X`. -/
def lift (f : C → G) (hf : ∀ S : ShortComplex C, S.ShortExact → f S.X₂ = f S.X₁ + f S.X₃) :
    AbelianK0 C →+ G :=
  QuotientAddGroup.lift _ (FreeAbelianGroup.lift f) (by
    refine (AddSubgroup.closure_le _).2 ?_
    rintro x ⟨S, hS, rfl⟩
    simp only [SetLike.mem_coe, AddMonoidHom.mem_ker, map_sub, FreeAbelianGroup.lift.of, hf S hS]
    abel)

@[simp]
theorem lift_mk (f : C → G) (hf) (X : C) : lift f hf (mk X) = f X :=
  (QuotientAddGroup.lift_mk' (relations C) _ (FreeAbelianGroup.of X)).trans
    (FreeAbelianGroup.lift.of f X)

theorem lift_unique (f : C → G) (hf) (g : AbelianK0 C →+ G) (hg : ∀ X, g (mk X) = f X) :
    g = lift f hf := by
  ext X
  simp [hg]

end lift

/-! ### Basic relations -/

theorem mk_X₁ {S : ShortComplex C} (hS : S.ShortExact) : mk S.X₁ = mk S.X₂ - mk S.X₃ := by
  rw [mk_X₂ hS, add_sub_cancel_right]

theorem mk_X₃ {S : ShortComplex C} (hS : S.ShortExact) : mk S.X₃ = mk S.X₂ - mk S.X₁ := by
  rw [mk_X₂ hS, add_sub_cancel_left]

/-- The short exact sequence relation, for a short exact sequence given by its two morphisms. -/
theorem mk_eq_add_of_shortExact {X₁ X₂ X₃ : C} (f : X₁ ⟶ X₂) (g : X₂ ⟶ X₃) (w : f ≫ g = 0)
    (h : (ShortComplex.mk f g w).ShortExact) : mk X₂ = mk X₁ + mk X₃ :=
  mk_X₂ h

/-- The class of the zero object is `0`. -/
@[simp]
theorem mk_zero : mk (0 : C) = 0 := by
  have h := mk_X₂ ((ShortComplex.Splitting.ofIsZeroOfIsIso
    (ShortComplex.mk (0 : (0 : C) ⟶ 0) (𝟙 0) (by simp)) (isZero_zero C)
    (by dsimp; infer_instance)).shortExact)
  exact right_eq_add.1 h

/-- Isomorphic objects have the same class in `K₀(C)`, by the short exact sequence
`0 ⟶ 0 ⟶ X ⟶ Y ⟶ 0`. -/
theorem mk_eq_of_iso {X Y : C} (e : X ≅ Y) : mk X = mk Y := by
  have h := mk_X₂ ((ShortComplex.Splitting.ofIsZeroOfIsIso
    (ShortComplex.mk (0 : (0 : C) ⟶ X) e.hom (by simp)) (isZero_zero C)
    (by dsimp; infer_instance)).shortExact)
  dsimp at h
  rw [h, mk_zero, zero_add]

theorem mk_eq_zero_of_isZero {X : C} (hX : IsZero X) : mk X = 0 := by
  rw [mk_eq_of_iso hX.isoZero, mk_zero]

/-! ### Biproducts -/

/-- `[X ⊞ Y] = [X] + [Y]`, from the split short exact sequence `0 ⟶ X ⟶ X ⊞ Y ⟶ Y ⟶ 0`. -/
theorem mk_biprod (X Y : C) : mk (X ⊞ Y) = mk X + mk Y :=
  mk_X₂ (ShortComplex.Splitting.ofHasBinaryBiproduct X Y).shortExact

theorem mk_prod (X Y : C) : mk (X ⨯ Y) = mk X + mk Y :=
  (mk_eq_of_iso (biprod.isoProd X Y).symm).trans (mk_biprod X Y)

theorem mk_coprod (X Y : C) : mk (X ⨿ Y) = mk X + mk Y :=
  (mk_eq_of_iso (biprod.isoCoprod X Y).symm).trans (mk_biprod X Y)

/-! ### Kernels, images and homology -/

/-- `[X] = [ker f] + [coim f]` for `f : X ⟶ Y`, from the short exact sequence
`0 ⟶ ker f ⟶ X ⟶ coim f ⟶ 0`. -/
theorem mk_eq_mk_kernel_add_mk_coimage {X Y : C} (f : X ⟶ Y) :
    mk X = mk (kernel f) + mk (Abelian.coimage f) :=
  mk_X₂ (S := ShortComplex.mk (kernel.ι f) (Abelian.coimage.π f) (by simp))
    (ShortComplex.ShortExact.mk' (ShortComplex.exact_of_g_is_cokernel _
      (cokernelIsCokernel (kernel.ι f))) (by dsimp; infer_instance) (by dsimp; infer_instance))

/-- `[Y] = [im f] + [coker f]` for `f : X ⟶ Y`, from the short exact sequence
`0 ⟶ im f ⟶ Y ⟶ coker f ⟶ 0`. -/
theorem mk_eq_mk_image_add_mk_cokernel {X Y : C} (f : X ⟶ Y) :
    mk Y = mk (Abelian.image f) + mk (cokernel f) :=
  mk_X₂ (S := ShortComplex.mk (Abelian.image.ι f) (cokernel.π f) (by simp))
    (ShortComplex.ShortExact.mk' (ShortComplex.exact_of_f_is_kernel _
      (kernelIsKernel (cokernel.π f))) (by dsimp; infer_instance) (by dsimp; infer_instance))

/-- `[Y] = [coim f] + [coker f]` for `f : X ⟶ Y`, using `coim f ≅ im f`. -/
theorem mk_eq_mk_coimage_add_mk_cokernel {X Y : C} (f : X ⟶ Y) :
    mk Y = mk (Abelian.coimage f) + mk (cokernel f) := by
  rw [mk_eq_mk_image_add_mk_cokernel f, mk_eq_of_iso (Abelian.coimageIsoImage f)]

theorem mk_coimage_eq_zero_of_isZero_source {X Y : C} (f : X ⟶ Y) (hX : IsZero X) :
    mk (Abelian.coimage f) = 0 :=
  mk_eq_zero_of_isZero (IsZero.of_epi (Abelian.coimage.π f) hX)

theorem mk_coimage_eq_zero_of_isZero_target {X Y : C} (f : X ⟶ Y) (hY : IsZero Y) :
    mk (Abelian.coimage f) = 0 := by
  rw [mk_eq_of_iso (Abelian.coimageIsoImage f)]
  exact mk_eq_zero_of_isZero (IsZero.of_mono (Abelian.image.ι f) hY)

/-- For a short complex `S : X₁ ⟶ X₂ ⟶ X₃` in an abelian category,
`[X₂] = [H(S)] + [coim S.f] + [coim S.g]`. It combines the short exact sequences
`0 ⟶ Z ⟶ X₂ ⟶ coim S.g ⟶ 0` and `0 ⟶ B ⟶ Z ⟶ H(S) ⟶ 0`, where `Z = S.cycles` is the kernel of
`S.g` and `B ≅ coim S.f` is the image of `S.f`. -/
theorem mk_X₂_eq_mk_homology_add (S : ShortComplex C) :
    mk S.X₂ = mk S.homology + mk (Abelian.coimage S.f) + mk (Abelian.coimage S.g) := by
  have e₁ : S.homology ≅ cokernel S.toCycles :=
    IsColimit.coconePointUniqueUpToIso S.homologyIsCokernel (colimit.isColimit _)
  have e₂ : kernel S.f ≅ kernel S.toCycles :=
    kernelIsoOfEq S.toCycles_i.symm ≪≫ kernelCompMono S.toCycles S.iCycles
  have h₁ := mk_eq_mk_kernel_add_mk_coimage S.g
  have h₂ := mk_eq_mk_coimage_add_mk_cokernel S.toCycles
  have h₃ := mk_eq_mk_kernel_add_mk_coimage S.toCycles
  have h₄ := mk_eq_mk_kernel_add_mk_coimage S.f
  rw [mk_eq_of_iso S.cyclesIsoKernel.symm] at h₁
  rw [← mk_eq_of_iso e₁] at h₂
  rw [mk_eq_of_iso e₂] at h₄
  have h₅ : mk (Abelian.coimage S.toCycles) = mk (Abelian.coimage S.f) :=
    add_left_cancel (h₃.symm.trans h₄)
  rw [h₁, h₂, h₅]
  abel

/-! ### Functoriality -/

section map

attribute [local instance] comp_preservesFiniteLimits comp_preservesFiniteColimits

variable {D : Type*} [Category D] [Abelian D] {E : Type*} [Category E] [Abelian E]

/-- An exact functor `F : C ⥤ D` between abelian categories (one preserving zero morphisms,
finite limits and finite colimits) induces a homomorphism `K₀(C) →+ K₀(D)`, `[X] ↦ [F X]`. -/
def map (F : C ⥤ D) [F.PreservesZeroMorphisms] [PreservesFiniteLimits F]
    [PreservesFiniteColimits F] : AbelianK0 C →+ AbelianK0 D :=
  lift (fun X => mk (F.obj X)) (fun _ hS => mk_X₂ (hS.map_of_exact F))

@[simp]
theorem map_mk (F : C ⥤ D) [F.PreservesZeroMorphisms] [PreservesFiniteLimits F]
    [PreservesFiniteColimits F] (X : C) : map F (mk X) = mk (F.obj X) :=
  lift_mk _ _ X

@[simp]
theorem map_id : map (𝟭 C) = AddMonoidHom.id (AbelianK0 C) := by
  ext X
  simp

theorem map_comp (F : C ⥤ D) (G : D ⥤ E) [F.PreservesZeroMorphisms] [PreservesFiniteLimits F]
    [PreservesFiniteColimits F] [G.PreservesZeroMorphisms] [PreservesFiniteLimits G]
    [PreservesFiniteColimits G] : map (F ⋙ G) = (map G).comp (map F) := by
  ext X
  simp

/-- Naturally isomorphic exact functors induce the same map on `K₀`. -/
theorem map_eq_of_iso {F₁ F₂ : C ⥤ D} (e : F₁ ≅ F₂) [F₁.PreservesZeroMorphisms]
    [PreservesFiniteLimits F₁] [PreservesFiniteColimits F₁] [F₂.PreservesZeroMorphisms]
    [PreservesFiniteLimits F₂] [PreservesFiniteColimits F₂] : map F₁ = map F₂ := by
  ext X
  simp only [map_mk]
  exact mk_eq_of_iso (e.app X)

/-- An equivalence of abelian categories induces an isomorphism `K₀(C) ≃+ K₀(D)`. -/
def mapEquiv (e : C ≌ D) : AbelianK0 C ≃+ AbelianK0 D where
  toFun := map e.functor
  invFun := map e.inverse
  left_inv x := by
    rw [← AddMonoidHom.comp_apply, ← map_comp, map_eq_of_iso e.unitIso.symm, map_id,
      AddMonoidHom.id_apply]
  right_inv x := by
    rw [← AddMonoidHom.comp_apply, ← map_comp, map_eq_of_iso e.counitIso, map_id,
      AddMonoidHom.id_apply]
  map_add' := map_add _

@[simp]
theorem mapEquiv_apply (e : C ≌ D) (x : AbelianK0 C) : mapEquiv e x = map e.functor x :=
  rfl

@[simp]
theorem mapEquiv_symm_apply (e : C ≌ D) (y : AbelianK0 D) :
    (mapEquiv e).symm y = map e.inverse y :=
  rfl

theorem mapEquiv_mk (e : C ≌ D) (X : C) : mapEquiv e (mk X) = mk (e.functor.obj X) :=
  map_mk _ X

end map

end AbelianK0

end DG
