import DG.Compact.Thick
import DG.K0.Triangulated
import Mathlib.CategoryTheory.Adjunction.Additive

/-!
# Compact objects under functors, and `K₀` of the compact objects

Let `T` be a pretriangulated category with coproducts. Its compact objects form a thick
triangulated subcategory `T^c` (`DG.compactSubcategory`, a Mathlib `ObjectProperty` whose full
subcategory is pretriangulated), and `K₀(T^c)` is the Grothendieck group of compact objects.
This file collects the functoriality of `T^c` and `K₀(T^c)`.

## Main results

* `DG.IsCompact.map_of_adjunction`: a left adjoint `F ⊣ G` (with `F` additive) whose right
  adjoint preserves coproducts preserves compact objects, since
  `Hom(F X, ∐ Y) ≅ Hom(X, G (∐ Y)) ≅ Hom(X, ∐ G Y)`. In particular equivalences preserve and
  reflect compactness (`DG.isCompact_functor_obj_iff`).
* `DG.compactRestriction F hF : T^c ⥤ T'^c`, the restriction of a functor preserving compact
  objects; it commutes with shifts and is triangulated when `F` is.
* `DG.K0.mapCompact F hF : K₀(T^c) →+ K₀(T'^c)`, with `DG.K0.mapCompact_mk`,
  `DG.K0.mapCompact_comp`, `DG.K0.mapCompact_eq_of_iso`; `DG.K0.compactMapEquiv e` for a
  triangulated equivalence `e : T ≌ T'`.
* `DG.K0.mk_fullSubcategory_obj₂`: the triangle relation in `K₀` of a triangulated
  subcategory for a distinguished triangle of the ambient category.
* `DG.K0.exists_mk_eq`: every element of `K₀(T)` is the class of a single object.
* `DG.K0.mk_mem_closure_of_forall`: the classes of the objects of the triangulated subcategory
  generated by a family `S` lie in the subgroup generated by the classes of `S`. (Classes of
  direct summands need not: for the ring `k × k` in degree `0` the class of `k × 0` is not a
  multiple of `[k × k]`.)
-/

universe w w' w'' v v' v'' u u' u''

namespace DG

open CategoryTheory Limits Pretriangulated ZeroObject

set_option backward.isDefEq.respectTransparency false

/-! ### Compact objects and adjunctions -/

section Adjunction

variable {C : Type u} [Category.{v} C] [Preadditive C] {D : Type u'} [Category.{v'} D]
  [Preadditive D]

/-- A left adjoint whose right adjoint preserves coproducts preserves compact objects:
`Hom(F X, ∐ Y) ≅ Hom(X, G (∐ Y)) ≅ Hom(X, ∐ G Y)`. -/
theorem IsCompact.map_of_adjunction {F : C ⥤ D} {G : D ⥤ C} (adj : F ⊣ G) [F.Additive]
    [∀ ι : Type w, PreservesColimitsOfShape (Discrete ι) G] {X : C} (hX : IsCompact.{w} X) :
    IsCompact.{w} (F.obj X) := by
  intro ι _ Y _
  have hc := isColimitCofanMkObjOfIsColimit G _ _ (coproductIsCoproduct Y)
  have : HasCoproduct fun i => G.obj (Y i) := ⟨⟨_, hc⟩⟩
  let E := hc.coconePointUniqueUpToIso (colimit.isColimit _)
  have hE : ∀ i, Sigma.ι (fun i => G.obj (Y i)) i ≫ E.inv = G.map (Sigma.ι Y i) := fun i => by
    rw [Iso.comp_inv_eq]
    exact (hc.comp_coconePointUniqueUpToIso_hom (colimit.isColimit _) ⟨i⟩).symm
  let e : (DirectSum ι fun i => (F.obj X ⟶ Y i)) ≃+ DirectSum ι fun i => (X ⟶ G.obj (Y i)) :=
    DFinsupp.mapRange.addEquiv fun i => adj.homAddEquiv X (Y i)
  have key : ∀ a, coproductComparison (F.obj X) Y a = (adj.homAddEquiv X (∐ Y)).symm
      (coproductComparison X (fun i => G.obj (Y i)) (e a) ≫ E.inv) := by
    intro a
    induction a using DirectSum.induction_on with
    | zero => simp
    | of i f =>
      have he : e (DirectSum.of _ i f) = DirectSum.of _ i (adj.homEquiv X (Y i) f) := by
        change DFinsupp.mapRange (fun i => adj.homAddEquiv X (Y i)) (fun i => map_zero _)
          (DFinsupp.single i f) = DFinsupp.single i _
        rw [DFinsupp.mapRange_single]
        rfl
      rw [he, coproductComparison_of, coproductComparison_of, Category.assoc, hE,
        ← adj.homEquiv_naturality_right, Adjunction.homAddEquiv_symm_apply,
        Equiv.symm_apply_apply]
    | add a b ha hb => rw [map_add, ha, hb, map_add, map_add, Preadditive.add_comp, map_add]
  have hE' : Function.Bijective fun a : X ⟶ ∐ fun i => G.obj (Y i) => a ≫ E.inv :=
    Function.bijective_iff_has_inverse.mpr ⟨fun a => a ≫ E.hom, fun a => by simp, fun a => by simp⟩
  have hk : ⇑(coproductComparison (F.obj X) Y) = (adj.homAddEquiv X (∐ Y)).symm ∘
      (fun a => a ≫ E.inv) ∘ coproductComparison X (fun i => G.obj (Y i)) ∘ e := funext key
  rw [hk]
  exact (adj.homAddEquiv X (∐ Y)).symm.bijective.comp (hE'.comp ((hX ι _).comp e.bijective))

/-- The functor of an equivalence of preadditive categories preserves compact objects. -/
theorem IsCompact.map_of_equivalence (e : C ≌ D) [e.functor.Additive] {X : C}
    (hX : IsCompact.{w} X) : IsCompact.{w} (e.functor.obj X) :=
  hX.map_of_adjunction e.toAdjunction

/-- An object is compact iff its image under an equivalence of preadditive categories is. -/
theorem isCompact_functor_obj_iff (e : C ≌ D) [e.functor.Additive] (X : C) :
    IsCompact.{w} (e.functor.obj X) ↔ IsCompact.{w} X := by
  refine ⟨fun h => ?_, fun h => h.map_of_equivalence e⟩
  have : e.symm.functor.Additive := e.toAdjunction.right_adjoint_additive
  exact ((h.map_of_equivalence e.symm).of_iso (e.unitIso.app X))

end Adjunction

/-! ### Restriction to compact objects -/

section Restriction

variable {T : Type u} [Category.{v} T] [HasZeroObject T] [HasShift T ℤ] [Preadditive T]
  [∀ n : ℤ, (shiftFunctor T n).Additive] [Pretriangulated T]
  {T' : Type u'} [Category.{v'} T'] [HasZeroObject T'] [HasShift T' ℤ] [Preadditive T']
  [∀ n : ℤ, (shiftFunctor T' n).Additive] [Pretriangulated T']

namespace K0

variable {P : ObjectProperty T}

/-- Objects of a full subcategory which are isomorphic in the ambient category have the same
class. -/
theorem mk_eq_of_iso_obj [P.IsTriangulated] {X Y : P.FullSubcategory} (e : X.obj ≅ Y.obj) :
    mk X = mk Y :=
  mk_eq_of_iso (ObjectProperty.isoMk P e)

/-- The triangle relation in `K₀` of a triangulated subcategory, for a distinguished triangle of
the ambient category whose three objects lie in the subcategory. -/
theorem mk_fullSubcategory_obj₂ [P.IsTriangulated] (R : Triangle T) (hR : R ∈ distTriang T)
    (h₁ : P R.obj₁) (h₂ : P R.obj₂) (h₃ : P R.obj₃) :
    mk (⟨R.obj₂, h₂⟩ : P.FullSubcategory) = mk ⟨R.obj₁, h₁⟩ + mk ⟨R.obj₃, h₃⟩ := by
  obtain ⟨Z, g, h, hT⟩ := distinguished_cocone_triangle
    (ObjectProperty.homMk R.mor₁ : (⟨R.obj₁, h₁⟩ : P.FullSubcategory) ⟶ ⟨R.obj₂, h₂⟩)
  rw [mk_eq_add_of_distTriang _ g h hT]
  congr 1
  exact mk_eq_of_iso_obj (Triangle.π₃.mapIso (isoTriangleOfIso₁₂ _ R (P.ι.map_distinguished _ hT)
    hR (Iso.refl _) (Iso.refl _) (by simp)))

/-- Every element of `K₀(C)` is the class of an object: `[X] - [Y] = [X ⊞ Y⟦1⟧]`. -/
theorem exists_mk_eq (x : K0 T) : ∃ X : T, mk X = x := by
  induction x using induction_on with
  | zero => exact ⟨0, mk_zero⟩
  | mk X => exact ⟨X, rfl⟩
  | neg x hx =>
    obtain ⟨X, rfl⟩ := hx
    exact ⟨X⟦(1 : ℤ)⟧, mk_shift_one X⟩
  | add x y hx hy =>
    obtain ⟨X, rfl⟩ := hx
    obtain ⟨Y, rfl⟩ := hy
    exact ⟨X ⊞ Y, mk_biprod X Y⟩


/-- The objects whose class lies in a given subgroup `G` of `K₀(T)`. -/
def mkMem (G : AddSubgroup (K0 T)) : ObjectProperty T := fun X => mk X ∈ G

instance (G : AddSubgroup (K0 T)) : (mkMem G).IsClosedUnderIsomorphisms where
  of_iso e h := by
    change mk _ ∈ G
    rwa [← mk_eq_of_iso e]

/-- The objects whose class lies in a subgroup of `K₀(T)` form a triangulated subcategory. -/
instance (G : AddSubgroup (K0 T)) : (mkMem G).IsTriangulated where
  toContainsZero := ⟨⟨0, isZero_zero T, by
    change mk _ ∈ G
    rw [mk_zero]
    exact zero_mem G⟩⟩
  toIsStableUnderShift := ⟨fun n => ⟨fun X (hX : mk X ∈ G) => by
    change mk _ ∈ G
    rw [mk_shift, Units.smul_def]
    exact G.zsmul_mem hX _⟩⟩
  toIsTriangulatedClosed₂ := .mk' fun R hR (h₁ : mk _ ∈ G) (h₃ : mk _ ∈ G) => by
    change mk _ ∈ G
    rw [mk_obj₂ R hR]
    exact add_mem h₁ h₃

/-- If `X` lies in every triangulated subcategory (closed under isomorphisms) containing the
objects of `S`, i.e. in the triangulated subcategory generated by `S`, then its class lies in the
subgroup of `K₀(T)` generated by the classes of the objects of `S`. -/
theorem mk_mem_closure_of_forall (S : ObjectProperty T) {X : T}
    (hX : ∀ P : ObjectProperty T, P.IsTriangulated → P.IsClosedUnderIsomorphisms → S ≤ P → P X) :
    mk X ∈ AddSubgroup.closure {x | ∃ Y, S Y ∧ mk Y = x} :=
  hX (mkMem _) inferInstance inferInstance fun Y hY => AddSubgroup.subset_closure ⟨Y, hY, rfl⟩

end K0

/-! ### Functors between categories of compact objects -/

section CompactRestriction

variable [HasCoproducts.{w} T] [HasCoproducts.{w'} T']

/-- The restriction of a functor `F : T ⥤ T'` which preserves compact objects to the categories
of compact objects `T^c ⥤ T'^c`. -/
noncomputable abbrev compactRestriction (F : T ⥤ T')
    (hF : ∀ X : T, IsCompact.{w} X → IsCompact.{w'} (F.obj X)) :
    (compactSubcategory.{w} T).FullSubcategory ⥤ (compactSubcategory.{w'} T').FullSubcategory :=
  (compactSubcategory.{w'} T').lift ((compactSubcategory.{w} T).ι ⋙ F)
    fun X => hF X.obj X.property

namespace K0

variable (F : T ⥤ T') [F.CommShift ℤ] [F.IsTriangulated]
  (hF : ∀ X : T, IsCompact.{w} X → IsCompact.{w'} (F.obj X))

/-- The homomorphism `K₀(T^c) →+ K₀(T'^c)` induced by a triangulated functor which preserves
compact objects. -/
noncomputable def mapCompact :
    K0 (compactSubcategory.{w} T).FullSubcategory →+
      K0 (compactSubcategory.{w'} T').FullSubcategory :=
  map (compactRestriction F hF)

@[simp]
theorem mapCompact_mk (X : (compactSubcategory.{w} T).FullSubcategory) :
    mapCompact F hF (mk X) = mk (⟨F.obj X.obj, hF _ X.property⟩ :
      (compactSubcategory.{w'} T').FullSubcategory) :=
  map_mk _ X

theorem mapCompact_eq_of_iso {F₁ F₂ : T ⥤ T'} (e : F₁ ≅ F₂) [F₁.CommShift ℤ] [F₁.IsTriangulated]
    [F₂.CommShift ℤ] [F₂.IsTriangulated]
    (h₁ : ∀ X : T, IsCompact.{w} X → IsCompact.{w'} (F₁.obj X))
    (h₂ : ∀ X : T, IsCompact.{w} X → IsCompact.{w'} (F₂.obj X)) :
    mapCompact F₁ h₁ = mapCompact F₂ h₂ := by
  ext X
  simp only [mapCompact_mk]
  exact mk_eq_of_iso_obj (e.app X.obj)

@[simp]
theorem mapCompact_id :
    mapCompact (𝟭 T) (fun _ h => h) =
      AddMonoidHom.id (K0 (compactSubcategory.{w} T).FullSubcategory) := by
  ext X
  simp only [mapCompact_mk, AddMonoidHom.id_apply]
  rfl

theorem mapCompact_comp {T'' : Type u''} [Category.{v''} T''] [HasZeroObject T''] [HasShift T'' ℤ]
    [Preadditive T''] [∀ n : ℤ, (shiftFunctor T'' n).Additive] [Pretriangulated T'']
    [HasCoproducts.{w''} T''] (G : T' ⥤ T'') [G.CommShift ℤ] [G.IsTriangulated]
    (hG : ∀ X : T', IsCompact.{w'} X → IsCompact.{w''} (G.obj X)) :
    mapCompact (F ⋙ G) (fun X h => hG _ (hF X h)) = (mapCompact G hG).comp (mapCompact F hF) := by
  ext X
  simp only [mapCompact_mk, AddMonoidHom.comp_apply]
  rfl

end K0

end CompactRestriction

section CompactEquivalence

variable [HasCoproducts.{w} T] [HasCoproducts.{w} T']

namespace K0

/-- An equivalence of pretriangulated categories with coproducts restricts to an equivalence of
the categories of compact objects, and so induces an isomorphism `K₀(T^c) ≃+ K₀(T'^c)`. -/
noncomputable def compactMapEquiv (e : T ≌ T') [e.functor.CommShift ℤ] [e.inverse.CommShift ℤ]
    [e.functor.IsTriangulated] [e.inverse.IsTriangulated] :
    K0 (compactSubcategory.{w} T).FullSubcategory ≃+
      K0 (compactSubcategory.{w} T').FullSubcategory :=
  haveI : e.symm.functor.Additive := inferInstanceAs e.inverse.Additive
  { toFun := mapCompact e.functor fun _ h => h.map_of_equivalence e
    invFun := mapCompact e.inverse fun _ h => h.map_of_equivalence e.symm
    left_inv x := by
      induction x using induction_on with
      | zero => rw [map_zero, map_zero]
      | mk X =>
        simp only [mapCompact_mk]
        exact mk_eq_of_iso_obj (e.unitIso.app X.obj).symm
      | neg x hx => rw [map_neg, map_neg, hx]
      | add x y hx hy => rw [map_add, map_add, hx, hy]
    right_inv y := by
      induction y using induction_on with
      | zero => rw [map_zero, map_zero]
      | mk X =>
        simp only [mapCompact_mk]
        exact mk_eq_of_iso_obj (e.counitIso.app X.obj)
      | neg x hx => rw [map_neg, map_neg, hx]
      | add x y hx hy => rw [map_add, map_add, hx, hy]
    map_add' := map_add _ }

@[simp]
theorem compactMapEquiv_mk (e : T ≌ T') [e.functor.CommShift ℤ] [e.inverse.CommShift ℤ]
    [e.functor.IsTriangulated] [e.inverse.IsTriangulated]
    (X : (compactSubcategory.{w} T).FullSubcategory) :
    compactMapEquiv e (mk X) = mk (⟨e.functor.obj X.obj, X.property.map_of_equivalence e⟩ :
      (compactSubcategory.{w} T').FullSubcategory) :=
  mapCompact_mk _ _ X

end K0

end CompactEquivalence

end Restriction

end DG
