import DG.Category.Derived.Perfect

/-!
# The Grothendieck group of a dg category

For a dg category `C`, `K₀(C) := K₀(D^c(C))` (`DG.DGCategory.K0 C`) is the Grothendieck group of
the perfect derived category `D^c(C)` of compact objects of `D(C)` (roadmap D.5).

## Main definitions and results

* `DG.DGCategory.K0 C`, the class `DG.DGCategory.K0.representable X = [C(X, -)]`.
* `DG.DGCategory.K0.exists_mk_eq`: every element of `K₀(C)` is the class of a perfect module.
* `DG.DGCategory.K0.mk_mem_closure_representable`: the classes of the objects of the triangulated
  subcategory generated by the representables lie in the subgroup generated by the
  `[C(X, -)]`. Every perfect module is a direct summand of such an object
  (`DG.CatModule.DerivedCategory.thickClosure_representable_eq_isCompact`), but `K₀(C)` need not
  be generated by the representables: for the ring `k × k` in degree `0` (one object) the class
  of the summand `k × 0` of the representable is not a multiple of `[k × k]`.
* `DG.DGCategory.K0.map F : K₀(C) →+ K₀(D)` for a dg functor `F : C ⥤ D`, induced by derived
  induction `LF_! : D^c(C) ⥤ D^c(D)`, with `DG.DGCategory.K0.map_representable`:
  `K₀(F) [C(X, -)] = [D(F X, -)]`.
* `DG.DGCategory.K0.mapEquivOfIsQuasiEquivalence`: a quasi-equivalence induces an isomorphism
  `K₀(C) ≃+ K₀(D)` (Keller's theorem, `DG.CatModule.DerivedCategory.kellerEquivalence`).

## Universes

`K0.{w', w} C` refers to dg modules with values in `Type w` and a derived category with morphisms
in `Type w'`. The representable classes need `w` of the form `max v w`. Functoriality along
`F : C ⥤ D` (with `C : Type u₁`, `[Category.{v₁} C]`, `D : Type u₂`, `[Category.{v₂} D]`) uses dg
modules in `Type (max u₁ v₁ v₂ w)` on both sides and a model of `D(C)` with morphisms in that
universe, as for derived induction.
-/

open CategoryTheory Limits Pretriangulated

universe w' w₂ w v v₁ v₂ u u₁ u₂

set_option backward.isDefEq.respectTransparency false

namespace DG

open CatModule

namespace DGCategory

variable (C : Type u) [Category.{v} C] [Preadditive C] [∀ X Y : C, DGAddCommGroup (X ⟶ Y)]
  [DGCategory C]

/-- The Grothendieck group `K₀(C) := K₀(D^c(C))` of a dg category `C`: the Grothendieck group of
the perfect derived category, for dg modules with values in `Type w`. -/
abbrev K0 [CatModule.HasDerivedCategory.{w', w} C] : Type _ :=
  DG.K0 (PerfectDerivedCategory.{w', w} C)

namespace K0

variable {C}

/-- The class `[C(X, -)] ∈ K₀(C)` of the representable module at `X`. -/
noncomputable def representable [CatModule.HasDerivedCategory.{w', max v w} C] (X : C) :
    K0.{w', max v w} C :=
  DG.K0.mk (PerfectDerivedCategory.representable.{w', w} X)

/-- Every element of `K₀(C)` is the class of a perfect module. -/
theorem exists_mk_eq [CatModule.HasDerivedCategory.{w', w} C] (x : K0.{w', w} C) :
    ∃ X : PerfectDerivedCategory.{w', w} C, DG.K0.mk X = x :=
  DG.K0.exists_mk_eq x

/-- The classes of the objects of the triangulated subcategory of `D^c(C)` generated by the
representable modules lie in the subgroup generated by the classes of the representables.
(Direct summands of such objects, which are also perfect, need not: see `DG.K0.Compact`.) -/
theorem mk_mem_closure_representable [CatModule.HasDerivedCategory.{w', max v w} C]
    {X : PerfectDerivedCategory.{w', max v w} C}
    (hX : ∀ P : ObjectProperty (PerfectDerivedCategory.{w', max v w} C), P.IsTriangulated →
      P.IsClosedUnderIsomorphisms → (∀ Y : C, P (PerfectDerivedCategory.representable.{w', w} Y)) →
      P X) :
    DG.K0.mk X ∈ AddSubgroup.closure (Set.range (representable.{w', w} (C := C))) := by
  have h := DG.K0.mk_mem_closure_of_forall
    (fun Y => ∃ Z : C, PerfectDerivedCategory.representable.{w', w} Z = Y)
    (X := X) fun P h₁ h₂ hP => hX P h₁ h₂ fun Y => hP _ ⟨Y, rfl⟩
  convert h using 2
  ext x
  constructor
  · rintro ⟨Z, rfl⟩
    exact ⟨_, ⟨Z, rfl⟩, rfl⟩
  · rintro ⟨_, ⟨Z, rfl⟩, rfl⟩
    exact ⟨Z, rfl⟩

section Functoriality

variable {C : Type u₁} [Category.{v₁} C] [Preadditive C] [∀ X Y : C, DGAddCommGroup (X ⟶ Y)]
  [DGCategory C] {D : Type u₂} [Category.{v₂} D] [Preadditive D]
  [∀ X Y : D, DGAddCommGroup (X ⟶ Y)] [DGCategory D] (F : C ⥤ D) [F.Additive] [F.IsDGFunctor]
  [CatModule.HasDerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C]
  [CatModule.HasDerivedCategory.{w₂, max u₁ v₁ v₂ w} D]

/-- The homomorphism `K₀(F) : K₀(C) →+ K₀(D)` induced by a dg functor `F : C ⥤ D`, via derived
induction `LF_! : D^c(C) ⥤ D^c(D)`. -/
noncomputable def map :
    K0.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C →+ K0.{w₂, max u₁ v₁ v₂ w} D :=
  DG.K0.map (DerivedCategory.perfectInduction.{w₂, w} F)

theorem map_mk (X : PerfectDerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C) :
    map.{w₂, w} F (DG.K0.mk X) = DG.K0.mk ((DerivedCategory.perfectInduction.{w₂, w} F).obj X) :=
  DG.K0.map_mk _ X

/-- `K₀(F)` sends the class of the representable `C(X, -)` to that of `D(F X, -)`. -/
theorem map_representable (X : C) :
    map.{w₂, w} F (representable.{max u₁ v₁ v₂ w, max u₁ v₂ w} X) =
      representable.{w₂, max u₁ v₁ v₂ w} (F.obj X) := by
  rw [representable, map_mk]
  exact DG.K0.mk_eq_of_iso_obj (DerivedCategory.inductionRepresentableIso F X)

/-- **Invariance of `K₀` under quasi-equivalences**: a quasi-equivalence of dg categories
`F : C ⥤ D` induces an isomorphism `K₀(C) ≃+ K₀(D)`, since by Keller's theorem
(`DG.CatModule.DerivedCategory.kellerEquivalence`) derived induction is a triangulated
equivalence `D(C) ≌ D(D)`, which restricts to the compact objects. -/
noncomputable def mapEquivOfIsQuasiEquivalence (hF : IsQuasiEquivalence F) :
    K0.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C ≃+ K0.{w₂, max u₁ v₁ v₂ w} D :=
  letI : (DerivedCategory.kellerEquivalence.{w, w₂} hF).functor.CommShift ℤ :=
    inferInstanceAs ((DerivedCategory.induction.{max u₁ v₁ v₂ w, w₂, w} F).CommShift ℤ)
  haveI : (DerivedCategory.kellerEquivalence.{w, w₂} hF).functor.IsTriangulated :=
    inferInstanceAs (DerivedCategory.induction.{max u₁ v₁ v₂ w, w₂, w} F).IsTriangulated
  DG.K0.compactMapEquiv (DerivedCategory.kellerEquivalence.{w, w₂} hF)

@[simp]
theorem mapEquivOfIsQuasiEquivalence_apply (hF : IsQuasiEquivalence F)
    (x : K0.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C) :
    mapEquivOfIsQuasiEquivalence.{w₂, w} F hF x = map.{w₂, w} F x :=
  rfl

end Functoriality

end K0

end DGCategory

end DG
