import DG.Homotopy.Comparison
import DG.K0.DGRing
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas

/-!
# `K₀` of a field

Let `k` be a field, regarded as a dg ring concentrated in degree `0` (the scoped instances of
`DG.DegreeZero`). This file shows `K₀(k) ≅ ℤ`, generated by `[k]` (roadmap 5.6).

The isomorphism is the Euler characteristic `χ(X) = ∑ₙ (-1)ⁿ dim Hⁿ(X)`. We develop it for a dg
algebra `A` over a field `R`:

* `DG.DerivedCategory.homologyFunctorShiftIso`: `Hⁿ(X⟦a⟧) ≅ Hᵃ⁺ⁿ(X)`, naturally in `X`, for the
  cohomology functors `D(A) ⥤ ModuleCat R` of any dg `R`-algebra (induced by Mathlib's shift
  sequence of the homology functors on the homotopy category of cochain complexes);
* `DG.DerivedCategory.finrankHomology`, `DG.DerivedCategory.HasFiniteCohomology`,
  `DG.DerivedCategory.eulerChar`;
* `DG.DerivedCategory.eulerChar_obj₂`: additivity of `χ` on distinguished triangles, from the
  long exact cohomology sequence (exactness at the three vertices, read off from the rotated
  triangles, and the rank–nullity theorem; `DG.DerivedCategory.alternating_finsum_of_exact`);
* `DG.DerivedCategory.isThick_hasFiniteCohomology`: objects with finite cohomology form a thick
  subcategory.

For a field `k` in degree `0`:

* `DG.DerivedCategory.finrankHomology_Q_self`, `DG.DerivedCategory.eulerChar_Q_self`:
  `Hⁿ(k) = k` for `n = 0` and `0` otherwise, so `χ(k) = 1`;
* `DG.DerivedCategory.isCompact_iff_hasFiniteCohomology`: an object of `D(k)` is compact iff its
  total cohomology is finite-dimensional. One direction is
  `DG.DerivedCategory.hasFiniteCohomology_of_isCompact` (compact objects form the thick closure
  of `k`), the other `DG.DerivedCategory.isCompact_of_hasFiniteCohomology` (by induction on the
  total dimension, splitting off a cell `k⟦-n⟧ ⟶ X` which is injective on cohomology,
  `DG.DerivedCategory.cocycleHom`);
* `DG.DGRing.K0.eulerChar k : K₀(k) →+ ℤ`, `DG.DGRing.K0.mem_zmultiples_self` (every class is a
  multiple of `[k]`, from the ordered cell towers of Schnürer's theorem,
  `DG.IsPositive.hasOrderedCellTower_of_isCompact`, whose cells are the `k⟦n⟧`), and
  **`DG.DGRing.K0.equivIntOfField k : K₀(k) ≃+ ℤ`**, `[k] ↦ 1`.

## Universes

The statements about `K₀(k)` use a model of `D(k)` with morphisms in the universe `u` of `k`
(`[DG.HasDerivedCategory.{u, u} k]`), as needed to identify the compact objects with the thick
closure of `k`.
-/

open CategoryTheory Limits Pretriangulated

universe w w' v u

set_option backward.isDefEq.respectTransparency false

namespace DG

namespace DerivedCategory

section Shift

variable (R : Type w) {A : Type u} [CommRing R] [Ring A] [DGAddCommGroup A] [Algebra R A]
  [DGRing A] [DGAlgebra R A] [HasDerivedCategory.{w', v} A]

/-- The cohomology functors of `D(A)` commute with the shifts: `Hⁿ(X⟦a⟧) ≅ Hⁿ⁺ᵃ(X)`, naturally
in `X`. It is induced by the corresponding isomorphism for cochain complexes (Mathlib's
`HomotopyCategory.homologyFunctor` shift sequence), through the forgetful functor. -/
noncomputable def homologyFunctorShiftIso (a n n' : ℤ) (h : a + n = n') :
    shiftFunctor (DerivedCategory A) a ⋙ homologyFunctor R n ≅ homologyFunctor R n' :=
  ((Functor.whiskeringLeft _ _ _).obj (Qh (A := A))).preimageIso
    ((Functor.associator _ _ _).symm ≪≫
      Functor.isoWhiskerRight ((Qh.commShiftIso a).symm) _ ≪≫ Functor.associator _ _ _ ≪≫
      Functor.isoWhiskerLeft _ (homologyFunctorFactorsh R n) ≪≫
      (Functor.associator _ _ _).symm ≪≫
      Functor.isoWhiskerRight ((HomotopyCategory.forget R A).commShiftIso a) _ ≪≫
      Functor.associator _ _ _ ≪≫
      Functor.isoWhiskerLeft _
        ((_root_.HomotopyCategory.homologyFunctor (ModuleCat.{v} R) (ComplexShape.up ℤ)
          0).shiftIso a n n' h) ≪≫
      (homologyFunctorFactorsh R n').symm)

end Shift

/-! ### Dimensions of cohomology over a field -/

section Dimension

/-- The rank of a linear map is unchanged by composing with isomorphisms. -/
theorem _root_.ModuleCat.finrank_range_iso_comp_comp {K : Type w} [Field K]
    {X X' Y Y' : ModuleCat.{v} K} (e₁ : X' ≅ X) (g : X ⟶ Y) (e₂ : Y ≅ Y') :
    Module.finrank K (LinearMap.range (e₁.hom ≫ g ≫ e₂.hom).hom) =
      Module.finrank K (LinearMap.range g.hom) := by
  have h : (e₁.hom ≫ g ≫ e₂.hom).hom =
      (e₂.toLinearEquiv : Y →ₗ[K] Y').comp (g.hom.comp (e₁.toLinearEquiv : X' →ₗ[K] X)) := rfl
  rw [h, LinearMap.range_comp, LinearEquiv.range_comp, LinearEquiv.finrank_map_eq]

/-- For an exact sequence `U → V → W` of vector spaces with `V` finite-dimensional,
`dim V = rank f + rank g`. -/
theorem _root_.ModuleCat.finrank_eq_add_of_exact {K : Type w} [Field K]
    {U V W : ModuleCat.{v} K} (f : U ⟶ V) (g : V ⟶ W)
    (h : LinearMap.range f.hom = LinearMap.ker g.hom) [FiniteDimensional K V] :
    Module.finrank K V =
      Module.finrank K (LinearMap.range f.hom) + Module.finrank K (LinearMap.range g.hom) := by
  rw [← LinearMap.finrank_range_add_finrank_ker g.hom, h, add_comm]


/-- The middle term of an exact sequence of vector spaces with finite-dimensional outer terms is
finite-dimensional. -/
theorem _root_.ModuleCat.finiteDimensional_of_exact {K : Type w} [Field K]
    {U V W : ModuleCat.{v} K} (f : U ⟶ V) (g : V ⟶ W)
    (h : LinearMap.range f.hom = LinearMap.ker g.hom) [FiniteDimensional K U]
    [FiniteDimensional K W] : FiniteDimensional K V := by
  have h1 : ((⊤ : Submodule K V).map g.hom).FG := IsNoetherian.noetherian _
  have h2 : ((⊤ : Submodule K V) ⊓ LinearMap.ker g.hom).FG := by
    rw [top_inf_eq, ← h, LinearMap.range_eq_map]
    exact (Module.Finite.fg_top).map _
  exact ⟨Submodule.fg_of_fg_map_of_fg_inf_ker g.hom h1 h2⟩

variable (R : Type w) {A : Type u} [Field R] [Ring A] [DGAddCommGroup A] [Algebra R A]
  [DGRing A] [DGAlgebra R A] [HasDerivedCategory.{w', v} A]

/-- The dimension of the `n`-th cohomology `Hⁿ(X)` of an object of `D(A)`, for a dg algebra `A`
over a field `R`. -/
noncomputable def finrankHomology (n : ℤ) (X : DerivedCategory A) : ℕ :=
  Module.finrank R ((homologyFunctor R n).obj X)

/-- The rank of the map `Hⁿ(f)` induced by a morphism of `D(A)`. -/
noncomputable def rankHomology (n : ℤ) {X Y : DerivedCategory A} (f : X ⟶ Y) : ℕ :=
  Module.finrank R (LinearMap.range ((homologyFunctor R n).map f).hom)

theorem finrankHomology_eq_of_iso (n : ℤ) {X Y : DerivedCategory A} (e : X ≅ Y) :
    finrankHomology R n X = finrankHomology R n Y :=
  ((homologyFunctor R n).mapIso e).toLinearEquiv.finrank_eq

theorem finrankHomology_shift (a n : ℤ) (X : DerivedCategory A) :
    finrankHomology R n (X⟦a⟧) = finrankHomology R (a + n) X :=
  ((homologyFunctorShiftIso R a n (a + n) rfl).app X).toLinearEquiv.finrank_eq

theorem rankHomology_shift (a n : ℤ) {X Y : DerivedCategory A} (f : X ⟶ Y) :
    rankHomology R n (f⟦a⟧') = rankHomology R (a + n) f := by
  let σ := homologyFunctorShiftIso (A := A) R a n (a + n) rfl
  have h : (homologyFunctor R n).map (f⟦a⟧') =
      σ.hom.app X ≫ (homologyFunctor R (a + n)).map f ≫ σ.inv.app Y := by
    rw [← Category.assoc, ← σ.hom.naturality f, Category.assoc, Iso.hom_inv_id_app,
      Category.comp_id]
    rfl
  rw [rankHomology, h]
  exact ModuleCat.finrank_range_iso_comp_comp (σ.app X) _ (σ.app Y).symm

theorem rankHomology_neg (n : ℤ) {X Y : DerivedCategory A} (f : X ⟶ Y) :
    rankHomology R n (-f) = rankHomology R n f := by
  rw [rankHomology, rankHomology, Functor.map_neg, ModuleCat.hom_neg, LinearMap.range_neg]

theorem rankHomology_le_left (n : ℤ) {X Y : DerivedCategory A} (f : X ⟶ Y)
    [FiniteDimensional R ((homologyFunctor R n).obj X)] :
    rankHomology R n f ≤ finrankHomology R n X :=
  LinearMap.finrank_range_le _

theorem rankHomology_le_right (n : ℤ) {X Y : DerivedCategory A} (f : X ⟶ Y)
    [FiniteDimensional R ((homologyFunctor R n).obj Y)] :
    rankHomology R n f ≤ finrankHomology R n Y :=
  Submodule.finrank_le _

/-- Exactness of the cohomology of a distinguished triangle at its second object. -/
theorem range_eq_ker_of_distTriang (n : ℤ) (T : Triangle (DerivedCategory A))
    (hT : T ∈ distTriang _) :
    LinearMap.range ((homologyFunctor R n).map T.mor₁).hom =
      LinearMap.ker ((homologyFunctor R n).map T.mor₂).hom :=
  ((homologyFunctor R n).map_distinguished_exact T hT).moduleCat_range_eq_ker

/-- An object of `D(A)` has *finite cohomology* if each `Hⁿ(X)` is finite-dimensional and only
finitely many of them are nonzero. -/
def HasFiniteCohomology (X : DerivedCategory A) : Prop :=
  (∀ n, FiniteDimensional R ((homologyFunctor R n).obj X)) ∧
    (Function.support fun n => finrankHomology R n X).Finite

/-- The Euler characteristic `χ(X) = ∑ₙ (-1)ⁿ dim Hⁿ(X)` of an object of `D(A)` (meaningful for
objects with finite cohomology). -/
noncomputable def eulerChar (X : DerivedCategory A) : ℤ :=
  ∑ᶠ n : ℤ, (n.negOnePow : ℤ) * (finrankHomology R n X : ℤ)

/-- The alternating sum identity behind the additivity of the Euler characteristic: for the
dimensions `x, y, z` of the terms and the ranks `a, b, c` of the maps of a long exact sequence
`⋯ → Xⁿ → Yⁿ → Zⁿ → Xⁿ⁺¹ → ⋯`, `∑ (-1)ⁿ yₙ = ∑ (-1)ⁿ xₙ + ∑ (-1)ⁿ zₙ`. -/
theorem alternating_finsum_of_exact (x y z a b c : ℤ → ℕ) (ha : (Function.support a).Finite)
    (hb : (Function.support b).Finite) (hc : (Function.support c).Finite)
    (hy : ∀ n, y n = a n + b n) (hz : ∀ n, z n = b n + c n)
    (hx : ∀ n, x (n + 1) = c n + a (n + 1)) :
    ∑ᶠ n, (n.negOnePow : ℤ) * y n =
      ∑ᶠ n, (n.negOnePow : ℤ) * x n + ∑ᶠ n, (n.negOnePow : ℤ) * z n := by
  have hx' : ∀ n, x n = c (n - 1) + a n := fun n => by
    have := hx (n - 1)
    rwa [sub_add_cancel] at this
  have fin : ∀ f : ℤ → ℕ, (Function.support f).Finite →
      Function.HasFiniteSupport fun n : ℤ => (n.negOnePow : ℤ) * f n := fun f hf =>
    hf.subset fun n hn h => hn (by simp [h])
  have hc' : (Function.support fun n => c (n - 1)).Finite := by
    have : (Function.support fun n => c (n - 1)) = (fun m => m + 1) '' Function.support c := by
      ext n
      simp only [Function.mem_support, Set.mem_image]
      exact ⟨fun h => ⟨n - 1, h, sub_add_cancel n 1⟩, fun ⟨m, hm, e⟩ => by
        rw [← e, add_sub_cancel_right]; exact hm⟩
    rw [this]
    exact hc.image _
  simp only [hy, hz, hx', Nat.cast_add, mul_add]
  rw [finsum_add_distrib (fin _ ha) (fin _ hb), finsum_add_distrib (fin _ hc') (fin _ ha),
    finsum_add_distrib (fin _ hb) (fin _ hc)]
  have key : ∑ᶠ n : ℤ, (n.negOnePow : ℤ) * (c (n - 1) : ℤ) =
      -∑ᶠ n : ℤ, (n.negOnePow : ℤ) * (c n : ℤ) := by
    rw [← finsum_comp_equiv (Equiv.addRight (1 : ℤ)), ← finsum_neg_distrib]
    refine finsum_congr fun n => ?_
    simp [Int.negOnePow_succ]
  rw [key]
  ring

section Triangle

variable {R} (T : Triangle (DerivedCategory A)) (hT : T ∈ distTriang _)
include hT

theorem finiteDimensional_obj₂ (n : ℤ) [FiniteDimensional R ((homologyFunctor R n).obj T.obj₁)]
    [FiniteDimensional R ((homologyFunctor R n).obj T.obj₃)] :
    FiniteDimensional R ((homologyFunctor R n).obj T.obj₂) :=
  ModuleCat.finiteDimensional_of_exact _ _ (range_eq_ker_of_distTriang R n T hT)

variable (h₁ : ∀ n, FiniteDimensional R ((homologyFunctor R n).obj T.obj₁))
  (h₃ : ∀ n, FiniteDimensional R ((homologyFunctor R n).obj T.obj₃))
include h₁ h₃

theorem finrankHomology_obj₂ (n : ℤ) :
    finrankHomology R n T.obj₂ = rankHomology R n T.mor₁ + rankHomology R n T.mor₂ := by
  have := h₁ n
  have := h₃ n
  have := finiteDimensional_obj₂ (R := R) T hT n
  exact ModuleCat.finrank_eq_add_of_exact _ _ (range_eq_ker_of_distTriang R n T hT)

omit h₁ in
theorem finrankHomology_obj₃ (n : ℤ) :
    finrankHomology R n T.obj₃ = rankHomology R n T.mor₂ + rankHomology R n T.mor₃ := by
  have := h₃ n
  exact ModuleCat.finrank_eq_add_of_exact _ _
    (range_eq_ker_of_distTriang R n T.rotate (rot_of_distTriang _ hT))

omit h₃ in
theorem finrankHomology_obj₁ (n : ℤ) :
    finrankHomology R (n + 1) T.obj₁ = rankHomology R n T.mor₃ + rankHomology R (n + 1) T.mor₁ := by
  have e := (homologyFunctorShiftIso (A := A) R 1 n (1 + n) rfl).app T.obj₁
  have := h₁ (1 + n)
  have : FiniteDimensional R ((homologyFunctor R n).obj T.rotate.rotate.obj₂) :=
    LinearEquiv.finiteDimensional e.toLinearEquiv.symm
  have h := ModuleCat.finrank_eq_add_of_exact _ _
    (range_eq_ker_of_distTriang R n T.rotate.rotate (rot_of_distTriang _ (rot_of_distTriang _ hT)))
  change finrankHomology R n (T.obj₁⟦(1 : ℤ)⟧) = rankHomology R n T.mor₃ +
    rankHomology R n (-T.mor₁⟦(1 : ℤ)⟧') at h
  rw [rankHomology_neg, rankHomology_shift, finrankHomology_shift, add_comm 1 n] at h
  exact h

end Triangle

theorem hasFiniteCohomology_obj₂ (T : Triangle (DerivedCategory A)) (hT : T ∈ distTriang _)
    (h₁ : HasFiniteCohomology R T.obj₁) (h₃ : HasFiniteCohomology R T.obj₃) :
    HasFiniteCohomology R T.obj₂ := by
  have := h₁.1
  have := h₃.1
  refine ⟨fun n => finiteDimensional_obj₂ T hT n, (h₁.2.union h₃.2).subset fun n hn => ?_⟩
  by_contra hn'
  simp only [Set.mem_union, Function.mem_support, not_or, not_not] at hn'
  apply hn
  change finrankHomology R n T.obj₂ = 0
  rw [finrankHomology_obj₂ T hT h₁.1 h₃.1]
  have ha := rankHomology_le_left R n T.mor₁
  have hb := rankHomology_le_right R n T.mor₂
  omega

/-- **Additivity of the Euler characteristic** on distinguished triangles of objects with finite
cohomology. -/
theorem eulerChar_obj₂ (T : Triangle (DerivedCategory A)) (hT : T ∈ distTriang _)
    (h₁ : HasFiniteCohomology R T.obj₁) (h₃ : HasFiniteCohomology R T.obj₃) :
    eulerChar R T.obj₂ = eulerChar R T.obj₁ + eulerChar R T.obj₃ := by
  have := h₁.1
  have := h₃.1
  refine alternating_finsum_of_exact _ _ _ (fun n => rankHomology R n T.mor₁)
    (fun n => rankHomology R n T.mor₂) (fun n => rankHomology R n T.mor₃)
    (h₁.2.subset fun n hn h => hn ?_) (h₃.2.subset fun n hn h => hn ?_)
    (h₃.2.subset fun n hn h => hn ?_) (finrankHomology_obj₂ T hT h₁.1 h₃.1)
    (finrankHomology_obj₃ T hT h₃.1) (finrankHomology_obj₁ T hT h₁.1)
  · have := rankHomology_le_left R n T.mor₁
    change finrankHomology R n T.obj₁ = 0 at h
    change rankHomology R n T.mor₁ = 0
    omega
  · have := rankHomology_le_right R n T.mor₂
    change finrankHomology R n T.obj₃ = 0 at h
    change rankHomology R n T.mor₂ = 0
    omega
  · have := rankHomology_le_left R n T.mor₃
    change finrankHomology R n T.obj₃ = 0 at h
    change rankHomology R n T.mor₃ = 0
    omega

theorem hasFiniteCohomology_of_isZero {X : DerivedCategory A} (hX : IsZero X) :
    HasFiniteCohomology R X := by
  have h : ∀ n, Subsingleton ((homologyFunctor R n).obj X) := fun n =>
    (ModuleCat.isZero_iff_subsingleton).mp ((homologyFunctor R n).map_isZero hX)
  refine ⟨fun n => inferInstance, ?_⟩
  convert Set.finite_empty
  ext n
  simp [finrankHomology, Module.finrank_zero_of_subsingleton]

theorem hasFiniteCohomology_of_iso {X Y : DerivedCategory A} (e : X ≅ Y)
    (hY : HasFiniteCohomology R Y) : HasFiniteCohomology R X := by
  refine ⟨fun n => ?_, ?_⟩
  · have := hY.1 n
    exact LinearEquiv.finiteDimensional ((homologyFunctor R n).mapIso e).toLinearEquiv.symm
  · convert hY.2 using 1
    ext n
    simp [Function.mem_support, finrankHomology_eq_of_iso R n e]

theorem hasFiniteCohomology_shift {X : DerivedCategory A} (hX : HasFiniteCohomology R X)
    (a : ℤ) : HasFiniteCohomology R (X⟦a⟧) := by
  refine ⟨fun n => ?_, ?_⟩
  · have := hX.1 (a + n)
    exact LinearEquiv.finiteDimensional
      ((homologyFunctorShiftIso (A := A) R a n (a + n) rfl).app X).toLinearEquiv.symm
  · refine ((hX.2.image fun n => n - a)).subset fun n hn => ⟨a + n, ?_, by ring⟩
    simpa [Function.mem_support, finrankHomology_shift] using hn

theorem hasFiniteCohomology_of_retract {X Y : DerivedCategory A} (r : Retract X Y)
    (hY : HasFiniteCohomology R Y) : HasFiniteCohomology R X := by
  have hinj : ∀ n, Function.Injective ((homologyFunctor R n).map r.i).hom := fun n =>
    Function.LeftInverse.injective (g := ((homologyFunctor R n).map r.r).hom) fun x => by
      change ((homologyFunctor R n).map r.i ≫ (homologyFunctor R n).map r.r).hom x = x
      rw [← Functor.map_comp, r.retract, CategoryTheory.Functor.map_id]
      rfl
  have hfd : ∀ n, FiniteDimensional R ((homologyFunctor R n).obj X) := fun n => by
    have := hY.1 n
    exact FiniteDimensional.of_injective _ (hinj n)
  refine ⟨hfd, hY.2.subset fun n hn h => hn ?_⟩
  have := hY.1 n
  change Module.finrank R _ = 0
  have := LinearMap.finrank_le_finrank_of_injective (hinj n)
  change finrankHomology R n Y = 0 at h
  unfold finrankHomology at h
  omega

/-- The objects with finite cohomology form a thick subcategory of `D(A)`. -/
theorem isThick_hasFiniteCohomology : IsThick (HasFiniteCohomology R (A := A)) where
  zero := hasFiniteCohomology_of_isZero R (isZero_zero _)
  shift _ a h := hasFiniteCohomology_shift R h a
  ext₂ T hT h₁ h₃ := hasFiniteCohomology_obj₂ R T hT h₁ h₃
  retract r h := hasFiniteCohomology_of_retract R r h

end Dimension

end DerivedCategory

/-! ### A field in degree `0` -/

section Field

open DegreeZero DGModuleCat.Algebra

variable (k : Type u) [Field k]

/-- The cohomology of a field `k` in degree `0`, as a dg module over itself: `H⁰(k) ≅ k`. -/
noncomputable def cohomologySelfZeroEquiv :
    k ≃ₗ[k] cohomology (DGModuleCat.of k k) 0 :=
  LinearEquiv.ofBijective
    { toFun := fun r => cohomology.mkOf (M := k) (n := 0) (mem_grading_iff.mpr (Or.inl rfl))
        (d_apply r)
      map_add' := fun r s => cohomology.mkOf_add _ _ _ _
      map_smul' := fun c r => rfl }
    ⟨(injective_iff_map_eq_zero _).mpr fun r h => by
      obtain ⟨m, -, hm⟩ := (cohomology.mkOf_eq_zero_iff (M := k) (n := 0)
        (mem_grading_iff.mpr (Or.inl rfl)) (d_apply r)).mp h
      rw [← hm]
      exact d_apply m,
    fun x => by
      induction x using cohomology.induction_on with
      | h z => exact ⟨(z : k), rfl⟩⟩

theorem subsingleton_cohomology_self {n : ℤ} (hn : n ≠ 0) :
    Subsingleton (cohomology (DGModuleCat.of k k) n) := by
  refine ⟨fun x y => ?_⟩
  induction x using cohomology.induction_on with
  | h z =>
  induction y using cohomology.induction_on with
  | h w =>
  congr 1
  refine Subtype.ext ?_
  have hz := (mem_grading_iff (R := k)).mp z.2.1
  have hw := (mem_grading_iff (R := k)).mp w.2.1
  rw [hz.resolve_left hn, hw.resolve_left hn]

namespace DerivedCategory

variable {k} [HasDerivedCategory.{w', u} k]

/-- `Hⁿ(Q k) ≅ Hⁿ(k)`, as `k`-vector spaces. -/
noncomputable def homologyQSelfEquiv (n : ℤ) :
    (homologyFunctor k n).obj (Q.obj (DGModuleCat.of k k)) ≃ₗ[k]
      cohomology (DGModuleCat.of k k) n :=
  ((homologyFunctorFactors k n).app (DGModuleCat.of k k)).toLinearEquiv

theorem finrankHomology_Q_self (n : ℤ) :
    finrankHomology k n (Q.obj (DGModuleCat.of k k)) = if n = 0 then 1 else 0 := by
  rw [finrankHomology, (homologyQSelfEquiv n).finrank_eq]
  split_ifs with hn
  · subst hn
    rw [← (cohomologySelfZeroEquiv k).finrank_eq, Module.finrank_self]
  · have := subsingleton_cohomology_self k hn
    exact Module.finrank_zero_of_subsingleton

theorem hasFiniteCohomology_Q_self : HasFiniteCohomology k (Q.obj (DGModuleCat.of k k)) := by
  refine ⟨fun n => ?_, (Set.finite_singleton (0 : ℤ)).subset fun n hn => ?_⟩
  · by_cases hn : n = 0
    · subst hn
      exact LinearEquiv.finiteDimensional
        ((cohomologySelfZeroEquiv k).trans (homologyQSelfEquiv 0).symm)
    · have := subsingleton_cohomology_self k hn
      have : Subsingleton ((homologyFunctor k n).obj (Q.obj (DGModuleCat.of k k))) :=
        (homologyQSelfEquiv n).toEquiv.subsingleton
      infer_instance
  · by_contra h
    apply hn
    change finrankHomology k n _ = 0
    simp [finrankHomology_Q_self, show n ≠ 0 from h]

theorem eulerChar_Q_self : eulerChar k (Q.obj (DGModuleCat.of k k)) = 1 := by
  rw [eulerChar, finsum_eq_single _ 0 fun n hn => by simp [finrankHomology_Q_self, hn]]
  simp [finrankHomology_Q_self]

omit [HasDerivedCategory.{w', u} k] in
/-- Compact objects of `D(k)` have finite-dimensional total cohomology. -/
theorem hasFiniteCohomology_of_isCompact [HasDerivedCategory.{u, u} k]
    {X : DerivedCategory.{u, u} k} (hX : IsCompact.{u} X) : HasFiniteCohomology k X := by
  rw [← thickClosure_self_eq_isCompact] at hX
  exact thickClosure_le (isThick_hasFiniteCohomology k)
    (by rintro _ ⟨-, rfl⟩; exact hasFiniteCohomology_Q_self) X hX

end DerivedCategory

end Field


/-! ### The Grothendieck group of a field -/

namespace DGRing.K0

section LeftCorner

variable {A : Type u} [Ring A] [DGAddCommGroup A] [DGRing A] [HasDerivedCategory.{w', u} A]

/-- For the idempotent `e = 1`, `[A e] = [A]`. -/
theorem leftCorner_eq_self_of_val_eq_one (e : DGIdempotent A) (he : e.val = 1) :
    leftCorner e = self A :=
  DG.K0.mk_eq_of_iso_obj (DerivedCategory.Q.mapIso
    { hom := DGModuleCat.ofHom e.leftCornerInclusion
      inv := DGModuleCat.ofHom e.leftCornerProjection
      hom_inv_id := DGModuleCat.hom_ext_apply fun x => Subtype.ext x.2
      inv_hom_id := DGModuleCat.hom_ext_apply fun x => by
        change x * e.val = x
        rw [he, mul_one] })

end LeftCorner

section Field

open DegreeZero

variable (k : Type u) [Field k] [HasDerivedCategory.{u, u} k]

/-- The Euler characteristic `χ : K₀(k) →+ ℤ`, `[X] ↦ ∑ₙ (-1)ⁿ dim Hⁿ(X)`, of a field `k` in
degree `0`. -/
noncomputable def eulerChar : K0 k →+ ℤ :=
  DG.K0.lift (fun X => DerivedCategory.eulerChar k X.obj) fun T hT =>
    DerivedCategory.eulerChar_obj₂ k _ hT
      (DerivedCategory.hasFiniteCohomology_of_isCompact T.obj₁.property)
      (DerivedCategory.hasFiniteCohomology_of_isCompact T.obj₃.property)

@[simp]
theorem eulerChar_mk (X : PerfectDerivedCategory k) :
    eulerChar k (DG.K0.mk X) = DerivedCategory.eulerChar k X.obj :=
  DG.K0.lift_mk _ _ X

theorem eulerChar_self : eulerChar k (self k) = 1 :=
  (eulerChar_mk k _).trans DerivedCategory.eulerChar_Q_self

/-- Every element of `K₀(k)` is a multiple of `[k]`: every compact object of `D(k)` has a
cell tower with cells `k⟦n⟧` (Schnürer's theorem for the positive dg ring `k`). -/
theorem mem_zmultiples_self (x : K0 k) : x ∈ AddSubgroup.zmultiples (self k) := by
  obtain ⟨X, rfl⟩ := DG.K0.exists_mk_eq x
  have hk : IsPositive k := IsPositive.degreeZero k
  obtain ⟨l, -, hl⟩ := hk.hasOrderedCellTower_of_isCompact X.property
  have hcell : ∀ (i : SimpleIdempotent k) (n : ℤ),
      IsCompact.{u} (DerivedCategory.cell k i.1 n : DerivedCategory.{u, u} k) :=
    fun i n => DerivedCategory.isCompact_cell i.1 n
  have h := CellTower.mk_eq_sum hcell hl
  have hX : DG.K0.mk X = DG.K0.mk (⟨X.obj, hl.isCompact hcell⟩ : PerfectDerivedCategory k) := rfl
  rw [hX, h]
  refine AddSubgroup.list_sum_mem _ fun y hy => ?_
  obtain ⟨c, -, rfl⟩ := List.mem_map.mp hy
  rw [mk_cell, leftCorner_eq_self_of_val_eq_one]
  · exact AddSubgroup.zsmul_mem _ (AddSubgroup.mem_zmultiples _) _
  · exact (IsIdempotentElem.iff_eq_zero_or_one.mp c.1.1.mul_self).resolve_left c.1.2.val_ne_zero

theorem eq_eulerChar_smul_self (x : K0 k) : x = eulerChar k x • self k := by
  obtain ⟨m, rfl⟩ := AddSubgroup.mem_zmultiples_iff.mp (mem_zmultiples_self k x)
  rw [map_zsmul, eulerChar_self, smul_eq_mul, mul_one]

/-- **`K₀` of a field** (roadmap 5.6): for a field `k` in degree `0`, the Euler characteristic
is an isomorphism `K₀(k) ≃+ ℤ` sending `[k]` to `1`. -/
noncomputable def equivIntOfField : K0 k ≃+ ℤ where
  toFun := eulerChar k
  invFun n := n • self k
  left_inv x := (eq_eulerChar_smul_self k x).symm
  right_inv n := by
    rw [map_zsmul, eulerChar_self, smul_eq_mul, mul_one]
  map_add' := map_add _

@[simp]
theorem equivIntOfField_self : equivIntOfField k (self k) = 1 :=
  eulerChar_self k

@[simp]
theorem equivIntOfField_symm_apply (n : ℤ) : (equivIntOfField k).symm n = n • self k :=
  rfl

end Field

end DGRing.K0

end DG

namespace DG

namespace DerivedCategory

section Zero

variable {R : Type w} {A : Type u} [Field R] [Ring A] [DGAddCommGroup A] [Algebra R A]
  [DGRing A] [DGAlgebra R A] [HasDerivedCategory.{w', v} A]

/-- An object of `D(A)` whose cohomology vanishes is zero. -/
theorem isZero_of_hasFiniteCohomology {X : DerivedCategory A} (hX : HasFiniteCohomology R X)
    (h : ∀ n, finrankHomology R n X = 0) : IsZero X := by
  obtain ⟨M, ⟨e⟩⟩ := exists_iso_Q_obj X
  refine IsZero.of_iso ?_ e
  rw [isZero_Q_obj_iff]
  intro n
  have := hX.1 n
  have hs : Subsingleton ((homologyFunctor R n).obj X) :=
    Module.finrank_zero_iff.mp (h n)
  have e' := ((homologyFunctor R n).mapIso e ≪≫ (homologyFunctorFactors R n).app M).toLinearEquiv
  exact e'.symm.toEquiv.subsingleton

variable (R) in
/-- The total dimension `∑ₙ dim Hⁿ(X)` of the cohomology of an object of `D(A)`. -/
noncomputable def totalFinrank (X : DerivedCategory A) : ℕ :=
  ∑ᶠ n, finrankHomology R n X

end Zero

section Field

open DegreeZero

variable {k : Type u} [Field k]

/-- The morphism of dg modules `k⟦-n⟧ → M`, `x ↦ x • m`, attached to a cocycle `m ∈ Mⁿ` of a dg
module over a field `k` in degree `0`. -/
def cocycleHom (M : DGModuleCat.{u} k) {n : ℤ} {m : M} (hm : m ∈ grading n) (hdm : d m = 0) :
    DGModuleCat.of k (Shift (-n) k) ⟶ M :=
  DGModuleCat.ofHom
    { toFun := fun x => Shift.unmk (-n) x • m
      map_add' := fun x y => by rw [map_add, add_smul]
      map_smul' := fun a x => by
        rw [Shift.unmk_smul (mem_grading_iff.mpr (Or.inl rfl)), mul_zero, koszulSign_zero,
          one_smul, smul_eq_mul, mul_smul]
        rfl
      map_mem' := fun {j x} hx => by
        have hx' := (mem_grading_iff (R := k)).mp (Shift.unmk_mem_grading hx)
        rcases hx' with hj | hx0
        · have : (Shift.unmk (-n) x : k) • m ∈ grading (0 + n) :=
            smul_mem_grading (mem_grading_iff.mpr (Or.inl rfl)) hm
          rwa [zero_add, show n = j by omega] at this
        · simp only [hx0, zero_smul]
          exact zero_mem _
      map_d' := fun x => by
        rw [Shift.unmk_d, d_apply, smul_zero, zero_smul,
          d_smul (mem_grading_iff.mpr (Or.inl rfl)), d_apply, zero_smul, hdm, smul_zero,
          smul_zero, add_zero] }

theorem cocycleHom_apply_mk (M : DGModuleCat.{u} k) {n : ℤ} {m : M} (hm : m ∈ grading n)
    (hdm : d m = 0) : (cocycleHom M hm hdm).hom (Shift.mk (-n) (1 : k)) = m :=
  one_smul k m

theorem mk_one_mem_grading (n : ℤ) : Shift.mk (-n) (1 : k) ∈ grading n := by
  have := Shift.mk_mem_grading (n := -n) (m := (1 : k)) ((mem_grading_iff (R := k)).mpr
    (Or.inl rfl))
  rwa [zero_sub, neg_neg] at this

theorem d_mk_one (n : ℤ) : d (Shift.mk (-n) (1 : k)) = 0 := by
  rw [Shift.d_mk, d_apply, smul_zero, map_zero]

variable [HasDerivedCategory.{w', u} k]

theorem finrankHomology_Q_shift_self (a j : ℤ) :
    finrankHomology k j (Q.obj (DGModuleCat.of k (Shift a k))) = if a + j = 0 then 1 else 0 := by
  refine (finrankHomology_eq_of_iso k j (X := Q.obj (DGModuleCat.of k (Shift a k)))
    ((Q.commShiftIso a).app (DGModuleCat.of k k))).trans ?_
  change finrankHomology k j ((Q.obj (DGModuleCat.of k k))⟦a⟧) = _
  rw [finrankHomology_shift, finrankHomology_Q_self]

theorem hasFiniteCohomology_Q_shift_self (a : ℤ) :
    HasFiniteCohomology k (Q.obj (DGModuleCat.of k (Shift a k))) :=
  hasFiniteCohomology_of_iso k ((Q.commShiftIso a).app (DGModuleCat.of k k))
    (hasFiniteCohomology_shift k hasFiniteCohomology_Q_self a)

theorem isCompact_Q_shift_self (a : ℤ) :
    IsCompact.{u} (Q.obj (DGModuleCat.of k (Shift a k))) :=
  (isCompact_Q_self.shift a).of_iso ((Q.commShiftIso a).app (DGModuleCat.of k k))

/-- The morphism `Q (cocycleHom z)` is nonzero on `Hⁿ` when the cocycle `z` is not a
coboundary. -/
theorem homologyFunctor_map_cocycleHom_ne_zero (M : DGModuleCat.{u} k) {n : ℤ}
    (z : cocycles M n) (hz : cohomology.mk M n z ≠ 0) :
    (homologyFunctor k n).map (Q.map (cocycleHom M z.2.1 z.2.2)) ≠ 0 := by
  intro h
  have nat := (homologyFunctorFactors k n).hom.naturality (cocycleHom M z.2.1 z.2.2)
  change (homologyFunctor k n).map (Q.map (cocycleHom M z.2.1 z.2.2)) ≫ _ = _ ≫ _ at nat
  rw [h, zero_comp] at nat
  have h2 := congrArg (fun f => f.hom (((homologyFunctorFactors k n).app
    (DGModuleCat.of k (Shift (-n) k))).inv
      (cohomology.mkOf (M := Shift (-n) k) (mk_one_mem_grading n) (d_mk_one n)))) nat
  simp only [ModuleCat.hom_zero, LinearMap.zero_apply, ModuleCat.hom_comp,
    LinearMap.comp_apply] at h2
  have h3 : ((homologyFunctorFactors k n).hom.app (DGModuleCat.of k (Shift (-n) k))).hom
      (((homologyFunctorFactors k n).app (DGModuleCat.of k (Shift (-n) k))).inv.hom
        (cohomology.mkOf (M := Shift (-n) k) (mk_one_mem_grading n) (d_mk_one n))) =
      cohomology.mkOf (M := Shift (-n) k) (mk_one_mem_grading n) (d_mk_one n) := by
    change (((homologyFunctorFactors k n).app (DGModuleCat.of k (Shift (-n) k))).inv ≫
      ((homologyFunctorFactors k n).app (DGModuleCat.of k (Shift (-n) k))).hom).hom _ = _
    rw [Iso.inv_hom_id]
    rfl
  erw [h3] at h2
  change 0 = cohomology.map (cocycleHom M z.2.1 z.2.2).hom n
    (cohomology.mkOf (M := Shift (-n) k) (mk_one_mem_grading n) (d_mk_one n)) at h2
  rw [cohomology.map_mkOf] at h2
  apply hz
  rw [← h2.symm]
  exact congrArg (cohomology.mk M n) (Subtype.ext (cocycleHom_apply_mk M z.2.1 z.2.2).symm)

theorem rankHomology_Q_cocycleHom (M : DGModuleCat.{u} k) {n : ℤ} (z : cocycles M n)
    (hz : cohomology.mk M n z ≠ 0) (j : ℤ) :
    rankHomology k j (Q.map (cocycleHom M z.2.1 z.2.2)) = if -n + j = 0 then 1 else 0 := by
  have := (hasFiniteCohomology_Q_shift_self (k := k) (-n)).1 j
  have hle := rankHomology_le_left k j (Q.map (cocycleHom M z.2.1 z.2.2))
  rw [finrankHomology_Q_shift_self] at hle
  split_ifs with hj
  · simp only [hj, ↓reduceIte] at hle
    have hjn : j = n := by omega
    subst hjn
    refine le_antisymm hle (Nat.one_le_iff_ne_zero.mpr fun h0 => ?_)
    apply homologyFunctor_map_cocycleHom_ne_zero M z hz
    rw [rankHomology, Submodule.finrank_eq_zero, LinearMap.range_eq_bot] at h0
    exact ModuleCat.hom_ext h0
  · simp only [hj, ↓reduceIte] at hle
    omega

/-- **Finite cohomology implies compactness** over a field: an object of `D(k)` whose total
cohomology is finite-dimensional is compact. By induction on the total dimension: a nonzero
cohomology class of degree `n` gives a morphism `k⟦-n⟧ ⟶ X` injective on cohomology, whose cone
has total dimension one less. -/
theorem isCompact_of_hasFiniteCohomology {X : DerivedCategory.{w', u} k}
    (hX : HasFiniteCohomology k X) : IsCompact.{u} X := by
  suffices h : ∀ (N : ℕ) (X : DerivedCategory.{w', u} k), HasFiniteCohomology k X →
      totalFinrank k X = N → IsCompact.{u} X from h _ X hX rfl
  intro N
  induction N with
  | zero =>
    intro X hX hN
    refine IsCompact.of_isZero (isZero_of_hasFiniteCohomology hX fun n => ?_)
    have := single_le_finsum n hX.2 fun _ => Nat.zero_le _
    change _ ≤ totalFinrank k X at this
    omega
  | succ N ih =>
    intro X hX hN
    obtain ⟨M, ⟨e⟩⟩ := exists_iso_Q_obj X
    have hM : HasFiniteCohomology k (Q.obj M) := hasFiniteCohomology_of_iso k e.symm hX
    -- a nonzero cohomology class
    obtain ⟨n, hn⟩ : ∃ n, finrankHomology k n (Q.obj M) ≠ 0 := by
      by_contra hcon
      push Not at hcon
      have : totalFinrank k X = 0 := by
        rw [totalFinrank]
        exact finsum_eq_zero_of_forall_eq_zero fun n => by
          rw [finrankHomology_eq_of_iso k n e]; exact hcon n
      omega
    have hnt : Nontrivial (cohomology M n) := by
      have := hM.1 n
      have e' := ((homologyFunctorFactors k n).app M).toLinearEquiv
      have : Nontrivial ((Q ⋙ homologyFunctor k n).obj M) :=
        Module.nontrivial_of_finrank_pos (R := k)
          (Nat.pos_of_ne_zero hn : 0 < Module.finrank k ((Q ⋙ homologyFunctor k n).obj M))
      exact (e'.symm.toEquiv.nontrivial : Nontrivial (cohomology M n))
    obtain ⟨x, hx⟩ := exists_ne (0 : cohomology M n)
    obtain ⟨z, rfl⟩ := cohomology.mk_surjective M n x
    -- the triangle `k⟦-n⟧ → M → C`
    obtain ⟨C, v, w, hT⟩ := distinguished_cocone_triangle (Q.map (cocycleHom M z.2.1 z.2.2))
    set T := Triangle.mk (Q.map (cocycleHom M z.2.1 z.2.2)) v w
    have h₁ : HasFiniteCohomology k T.obj₁ := hasFiniteCohomology_Q_shift_self (-n)
    have hC : HasFiniteCohomology k C :=
      hasFiniteCohomology_obj₂ k T.rotate (rot_of_distTriang _ hT) hM
        (hasFiniteCohomology_shift k h₁ 1)
    have ha := rankHomology_Q_cocycleHom M z hx
    -- dimensions
    have key : ∀ j, finrankHomology k j C + (if -n + j = 0 then 1 else 0) =
        finrankHomology k j (Q.obj M) := by
      intro j
      have hy := finrankHomology_obj₂ T hT h₁.1 hC.1 j
      have hz := finrankHomology_obj₃ T hT hC.1 j
      have hx := finrankHomology_obj₁ T hT h₁.1 j
      have hx1 : finrankHomology k (j + 1) T.obj₁ = if -n + (j + 1) = 0 then 1 else 0 :=
        finrankHomology_Q_shift_self (-n) (j + 1)
      have ha1 := ha (j + 1)
      have haj := ha j
      change finrankHomology k j (Q.obj M) = _ at hy
      change finrankHomology k j C = _ at hz
      change rankHomology k j (Q.map (cocycleHom M z.2.1 z.2.2)) = _ at haj
      change rankHomology k (j + 1) (Q.map (cocycleHom M z.2.1 z.2.2)) = _ at ha1
      change finrankHomology k (j + 1) _ = rankHomology k j T.mor₃ +
        rankHomology k (j + 1) (Q.map (cocycleHom M z.2.1 z.2.2)) at hx
      rw [hx1, ha1] at hx
      rw [show T.mor₁ = Q.map (cocycleHom M z.2.1 z.2.2) from rfl, haj] at hy
      split_ifs at hy ⊢ with h <;> omega
    have hsupp : (Function.support fun j : ℤ => if -n + j = 0 then 1 else 0).Finite :=
      (Set.finite_singleton n).subset fun j hj => by
        simp only [Function.mem_support, ne_eq, ite_eq_right_iff, one_ne_zero, imp_false,
          not_not] at hj
        simp only [Set.mem_singleton_iff]
        omega
    have htot : totalFinrank k C + 1 = totalFinrank k (Q.obj M) := by
      rw [totalFinrank, totalFinrank, ← finsum_congr key, finsum_add_distrib hC.2 hsupp,
        finsum_eq_single _ n fun j hj => ite_eq_right_iff.mpr fun h => absurd (by omega) hj]
      simp
    have hMX : totalFinrank k (Q.obj M) = totalFinrank k X := by
      rw [totalFinrank, totalFinrank]
      exact finsum_congr fun j => finrankHomology_eq_of_iso k j e.symm
    have hCN : totalFinrank k C = N := by omega
    exact (IsCompact.ext₂ T hT (isCompact_Q_shift_self (-n)) (ih C hC hCN)).of_iso e

omit [HasDerivedCategory.{w', u} k] in
/-- **Compact objects of `D(k)`** (roadmap 5.6): for a field `k` in degree `0`, an object of
`D(k)` is compact iff its total cohomology `⊕ₙ Hⁿ(X)` is finite-dimensional. -/
theorem isCompact_iff_hasFiniteCohomology [HasDerivedCategory.{u, u} k]
    {X : DerivedCategory.{u, u} k} : IsCompact.{u} X ↔ HasFiniteCohomology k X :=
  ⟨hasFiniteCohomology_of_isCompact, isCompact_of_hasFiniteCohomology⟩

end Field

end DerivedCategory

end DG
