import DG.K0.Triangulated
import DG.Compact.Thick
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.Algebra.BigOperators.Finprod

/-!
# Grothendieck groups generated by an orthonormal family over a field

Let `C` be a pretriangulated category, `K` a field and `G` an object of `C` with a ring
homomorphism `ρ : K →+* End G`. Then every group `Hom(G, Y)` is a `K`-vector space, with
`c • f = ρ c ≫ f` (`DG.HomK ρ Y`), and postcomposition is `K`-linear. For a distinguished
triangle `X → Y → Z → X⟦1⟧` the long exact sequence of the functor `Hom(G, -)` gives the
additivity of the Euler characteristic `χ_G(Y) = ∑ₙ (-1)ⁿ dim_K Hom(G, Y⟦n⟧)` on objects with
finite-dimensional total `Hom(G, -⟦*⟧)` (`DG.HomK.eulerChar_obj₂`).

Given a finite family `G j` (`j ∈ J`) which is *orthonormal* (`Hom(G j, G j'⟦n⟧) = 0` unless
`j = j'` and `n = 0`, and `End(G j) = K`) and *generates* a triangulated subcategory `𝒮` in which
all objects have finite total `Hom(G j, -⟦*⟧)` (every nonzero object of `𝒮` receives a nonzero
map from some `G j⟦-n⟧`), the Grothendieck group of `𝒮` is free on the classes `[G j]`:
`DG.IsOrthonormalGenerating.K0Equiv : K₀(𝒮) ≃+ (J → ℤ)`, `[X] ↦ (χ_{G j}(X))_j`. The proof that the
classes `[G j]` generate is by induction on the total dimension: a nonzero map `G j → X⟦n⟧`
completes to a distinguished triangle whose third vertex has total dimension one less.

## Main definitions and results

* `DG.HomK ρ Y`, with its `K`-module structure, and `DG.HomK.postcomp ρ f`.
* `DG.HomK.IsFin ρ Y`, `DG.HomK.eulerChar ρ Y`, `DG.HomK.isFin_obj₂`, `DG.HomK.eulerChar_obj₂`,
  `DG.HomK.eulerChar_shift`, `DG.HomK.isThick_isFin`.
* `DG.IsOrthonormalGenerating`, `DG.IsOrthonormalGenerating.K0Equiv`,
  `DG.IsOrthonormalGenerating.K0Equiv_mk_G`.
-/

open CategoryTheory Category Limits Pretriangulated

universe v u

namespace DG

variable {C : Type u} [Category.{v} C] [Preadditive C] {K : Type*} [Field K] {G : C}

/-! ### `Hom(G, -)` as a vector space -/

variable (ρ : K →+* End G)

/-- The group `Hom(G, Y)`, as a `K`-vector space through `ρ : K →+* End G`: `c • f = ρ c ≫ f`. -/
@[nolint unusedArguments]
def HomK (_ : K →+* End G) (Y : C) : Type v := G ⟶ Y

namespace HomK

instance (Y : C) : AddCommGroup (HomK ρ Y) := inferInstanceAs (AddCommGroup (G ⟶ Y))

instance (Y : C) : Module K (HomK ρ Y) where
  smul c f := (ρ c ≫ f : G ⟶ Y)
  one_smul f := show ρ 1 ≫ f = f by rw [map_one]; exact id_comp f
  mul_smul a b f := show ρ (a * b) ≫ f = ρ a ≫ ρ b ≫ f by
    rw [mul_comm, map_mul]; exact assoc (ρ a) (ρ b) f
  smul_zero c := Limits.comp_zero
  smul_add c f g := Preadditive.comp_add _ _ _ _ _ _
  add_smul a b f := show ρ (a + b) ≫ f = ρ a ≫ f + ρ b ≫ f by
    rw [map_add]; exact Preadditive.add_comp _ _ _ _ _ _
  zero_smul f := show ρ 0 ≫ f = 0 by rw [map_zero]; exact Limits.zero_comp

variable {ρ}

theorem smul_def {Y : C} (c : K) (f : HomK ρ Y) : c • f = (ρ c ≫ (f : G ⟶ Y) : G ⟶ Y) := rfl

variable (ρ)

/-- Postcomposition with `g : Y ⟶ Z`, a `K`-linear map `Hom(G, Y) → Hom(G, Z)`. -/
def postcomp {Y Z : C} (g : Y ⟶ Z) : HomK ρ Y →ₗ[K] HomK ρ Z where
  toFun f := (f : G ⟶ Y) ≫ g
  map_add' _ _ := Preadditive.add_comp _ _ _ _ _ _
  map_smul' _ _ := assoc _ _ _

@[simp]
theorem postcomp_apply {Y Z : C} (g : Y ⟶ Z) (f : G ⟶ Y) : postcomp ρ g f = f ≫ g := rfl

theorem postcomp_comp {X Y Z : C} (f : X ⟶ Y) (g : Y ⟶ Z) :
    postcomp ρ (f ≫ g) = (postcomp ρ g).comp (postcomp ρ f) :=
  LinearMap.ext fun _ => (assoc _ _ _).symm

/-- An isomorphism `Y ≅ Z` induces a linear equivalence `Hom(G, Y) ≃ Hom(G, Z)`. -/
def linearEquivOfIso {Y Z : C} (e : Y ≅ Z) : HomK ρ Y ≃ₗ[K] HomK ρ Z :=
  { postcomp ρ e.hom with
    invFun := postcomp ρ e.inv
    left_inv := fun (f : G ⟶ Y) => show (f ≫ e.hom) ≫ e.inv = f by simp
    right_inv := fun (f : G ⟶ Z) => show (f ≫ e.inv) ≫ e.hom = f by simp }

/-- The dimension of `Hom(G, Y)`. -/
noncomputable def finrankHom (Y : C) : ℕ := Module.finrank K (HomK ρ Y)

/-- The rank of postcomposition `Hom(G, Y) → Hom(G, Z)` with `g : Y ⟶ Z`. -/
noncomputable def rankHom {Y Z : C} (g : Y ⟶ Z) : ℕ :=
  Module.finrank K (LinearMap.range (postcomp ρ g))

variable {ρ}

theorem finrankHom_eq_of_iso {Y Z : C} (e : Y ≅ Z) : finrankHom ρ Y = finrankHom ρ Z :=
  (linearEquivOfIso ρ e).finrank_eq

theorem finiteDimensional_of_iso {Y Z : C} (e : Y ≅ Z) [FiniteDimensional K (HomK ρ Y)] :
    FiniteDimensional K (HomK ρ Z) :=
  LinearEquiv.finiteDimensional (linearEquivOfIso ρ e)

theorem postcomp_neg {Y Z : C} (g : Y ⟶ Z) : postcomp ρ (-g) = -postcomp ρ g :=
  LinearMap.ext fun (f : G ⟶ Y) => Preadditive.comp_neg f g

theorem postcomp_units_smul {Y Z : C} (u : ℤˣ) (g : Y ⟶ Z) :
    postcomp ρ (u • g) = postcomp ρ g ∨ postcomp ρ (u • g) = -postcomp ρ g := by
  rcases Int.units_eq_one_or u with rfl | rfl
  · exact Or.inl (by rw [one_smul])
  · exact Or.inr (by rw [Units.neg_smul, one_smul, postcomp_neg])

theorem range_postcomp_units_smul {Y Z : C} (u : ℤˣ) (g : Y ⟶ Z) :
    LinearMap.range (postcomp ρ (u • g)) = LinearMap.range (postcomp ρ g) := by
  rcases postcomp_units_smul (ρ := ρ) u g with h | h <;> rw [h]
  exact LinearMap.range_neg _

theorem ker_postcomp_units_smul {Y Z : C} (u : ℤˣ) (g : Y ⟶ Z) :
    LinearMap.ker (postcomp ρ (u • g)) = LinearMap.ker (postcomp ρ g) := by
  rcases postcomp_units_smul (ρ := ρ) u g with h | h <;> rw [h]
  exact LinearMap.ker_neg _

theorem ker_postcomp_comp_iso {Y Z Z' : C} (g : Y ⟶ Z) (e : Z ≅ Z') :
    LinearMap.ker (postcomp ρ (g ≫ e.hom)) = LinearMap.ker (postcomp ρ g) := by
  refine Submodule.ext fun (f : G ⟶ Y) =>
    LinearMap.mem_ker.trans (Iff.trans ?_ LinearMap.mem_ker.symm)
  change f ≫ (g ≫ e.hom) = 0 ↔ f ≫ g = 0
  rw [← assoc, Preadditive.IsIso.comp_right_eq_zero]

theorem range_postcomp_comp_iso {Y Z Z' : C} (g : Y ⟶ Z) (e : Z ≅ Z') :
    LinearMap.range (postcomp ρ (g ≫ e.hom)) =
      (LinearMap.range (postcomp ρ g)).map (linearEquivOfIso ρ e).toLinearMap := by
  rw [postcomp_comp, LinearMap.range_comp]
  rfl

theorem rankHom_units_smul {Y Z : C} (u : ℤˣ) (g : Y ⟶ Z) : rankHom ρ (u • g) = rankHom ρ g := by
  rw [rankHom, rankHom, range_postcomp_units_smul]

theorem rankHom_comp_iso {Y Z Z' : C} (g : Y ⟶ Z) (e : Z ≅ Z') :
    rankHom ρ (g ≫ e.hom) = rankHom ρ g := by
  rw [rankHom, rankHom, range_postcomp_comp_iso]
  exact LinearEquiv.finrank_map_eq _ _

theorem rankHom_iso_comp {Y Y' Z : C} (e : Y' ≅ Y) (g : Y ⟶ Z) :
    rankHom ρ (e.hom ≫ g) = rankHom ρ g := by
  rw [rankHom, rankHom, postcomp_comp, LinearMap.range_comp,
    show LinearMap.range (postcomp ρ e.hom) = ⊤ from
      LinearMap.range_eq_top.mpr (linearEquivOfIso ρ e).surjective, Submodule.map_top]

/-! ### Exact sequences -/

/-- Exactness of `Hom(G, X) → Hom(G, Y) → Hom(G, Z)` at `Hom(G, Y)`, for `f : X ⟶ Y`,
`g : Y ⟶ Z` with `f ≫ g = 0`: every `φ : G ⟶ Y` with `φ ≫ g = 0` factors through `f`. -/
def IsExactAt {X Y Z : C} (f : X ⟶ Y) (g : Y ⟶ Z) : Prop :=
  ∀ φ : G ⟶ Y, φ ≫ g = 0 → ∃ ψ : G ⟶ X, φ = ψ ≫ f

theorem range_eq_ker {X Y Z : C} {f : X ⟶ Y} {g : Y ⟶ Z} (hfg : f ≫ g = 0)
    (h : IsExactAt (G := G) f g) :
    LinearMap.range (postcomp ρ f) = LinearMap.ker (postcomp ρ g) := by
  refine Submodule.ext fun (φ : G ⟶ Y) => ⟨?_, fun hφ => ?_⟩
  · rintro ⟨ψ, rfl⟩
    exact (assoc ψ f g).trans ((congrArg (CategoryStruct.comp ψ) hfg).trans (comp_zero (f := ψ)))
  · obtain ⟨ψ, hψ⟩ := h φ hφ
    exact ⟨ψ, hψ.symm⟩

/-- For an exact sequence `Hom(G, X) → Hom(G, Y) → Hom(G, Z)` with `Hom(G, Y)`
finite-dimensional, `dim Hom(G, Y) = rank f + rank g`. -/
theorem finrankHom_eq_add {X Y Z : C} {f : X ⟶ Y} {g : Y ⟶ Z} (hfg : f ≫ g = 0)
    (h : IsExactAt (G := G) f g) [FiniteDimensional K (HomK ρ Y)] :
    finrankHom ρ Y = rankHom ρ f + rankHom ρ g := by
  rw [finrankHom, ← LinearMap.finrank_range_add_finrank_ker (postcomp ρ g), ← range_eq_ker hfg h,
    rankHom, rankHom, add_comm]

/-- The middle term of an exact sequence `Hom(G, X) → Hom(G, Y) → Hom(G, Z)` with
finite-dimensional outer terms is finite-dimensional. -/
theorem finiteDimensional_of_isExactAt {X Y Z : C} {f : X ⟶ Y} {g : Y ⟶ Z} (hfg : f ≫ g = 0)
    (h : IsExactAt (G := G) f g) [FiniteDimensional K (HomK ρ X)]
    [FiniteDimensional K (HomK ρ Z)] : FiniteDimensional K (HomK ρ Y) := by
  have h1 : ((⊤ : Submodule K (HomK ρ Y)).map (postcomp ρ g)).FG := IsNoetherian.noetherian _
  have h2 : ((⊤ : Submodule K (HomK ρ Y)) ⊓ LinearMap.ker (postcomp ρ g)).FG := by
    rw [top_inf_eq, ← range_eq_ker hfg h, LinearMap.range_eq_map]
    exact (Module.Finite.fg_top).map _
  exact ⟨Submodule.fg_of_fg_map_of_fg_inf_ker (postcomp ρ g) h1 h2⟩

end HomK

/-! ### An alternating-sum identity -/

/-- For functions `d₁ d₂ d₃ a b c : ℤ → ℕ` related as the dimensions and ranks of a long exact
sequence `⋯ → D₁(n) → D₂(n) → D₃(n) → D₁(n + 1) → ⋯` (`dim D₂(n) = a n + b n`,
`dim D₃(n) = b n + c n`, `dim D₁(n + 1) = c n + a (n + 1)`), with `d₁` and `d₃` of finite
support, `d₂` has finite support and the alternating sums satisfy `χ₂ = χ₁ + χ₃`. -/
theorem alternating_finsum_of_exact (d₁ d₂ d₃ a b c : ℤ → ℕ)
    (h₁ : ∀ n, d₁ (n + 1) = c n + a (n + 1)) (h₂ : ∀ n, d₂ n = a n + b n)
    (h₃ : ∀ n, d₃ n = b n + c n) (hd₁ : (Function.support d₁).Finite)
    (hd₃ : (Function.support d₃).Finite) :
    (Function.support d₂).Finite ∧
      ∑ᶠ n : ℤ, (n.negOnePow : ℤ) * d₂ n =
        ∑ᶠ n : ℤ, (n.negOnePow : ℤ) * d₁ n + ∑ᶠ n : ℤ, (n.negOnePow : ℤ) * d₃ n := by
  have ha : Function.support a ⊆ Function.support d₁ := fun n hn h0 => hn (by
    have := h₁ (n - 1)
    rw [sub_add_cancel] at this
    omega)
  have hb : Function.support b ⊆ Function.support d₃ := fun n hn h0 => hn (by
    have := h₃ n; omega)
  have hc : Function.support c ⊆ Function.support d₃ := fun n hn h0 => hn (by
    have := h₃ n; omega)
  have hd₂ : (Function.support d₂).Finite := (hd₁.union hd₃).subset fun n hn => by
    by_contra h
    simp only [Set.mem_union, Function.mem_support, not_or, not_not] at h
    exact hn (by rw [h₂ n]; have := ha.mt (by simpa using h.1); have := hb.mt (by simpa using h.2)
                 simp_all)
  refine ⟨hd₂, ?_⟩
  have fin : ∀ f : ℤ → ℕ, (Function.support f).Finite →
      Function.HasFiniteSupport fun n : ℤ => (n.negOnePow : ℤ) * f n := fun f hf =>
    hf.subset fun n hn => by
      simp only [Function.mem_support, ne_eq, mul_eq_zero, not_or] at hn
      exact_mod_cast hn.2
  let g : ℤ → ℤ := fun n => (n.negOnePow : ℤ) * c (n - 1)
  have hg : Function.HasFiniteSupport g := (hd₃.subset hc).preimage
    (Set.injOn_of_injective (sub_left_injective (b := 1))) |>.subset fun n hn => by
      simp only [g, Function.mem_support, ne_eq, mul_eq_zero, not_or] at hn
      exact (by exact_mod_cast hn.2 : c (n - 1) ≠ 0)
  have hg' : Function.HasFiniteSupport fun n => g (n + 1) :=
    (hg.preimage (Set.injOn_of_injective (add_left_injective 1))).subset fun n hn => hn
  have key : ∀ n : ℤ, (n.negOnePow : ℤ) * d₁ n + (n.negOnePow : ℤ) * d₃ n -
      (n.negOnePow : ℤ) * d₂ n = g n - g (n + 1) := by
    intro n
    have e₁ := h₁ (n - 1)
    rw [sub_add_cancel] at e₁
    simp only [g, e₁, h₂ n, h₃ n, add_sub_cancel_right, Int.negOnePow_succ, Units.val_neg]
    push_cast
    ring
  have hsum : ∑ᶠ n : ℤ, (g n - g (n + 1)) = 0 := by
    have e := finsum_comp_equiv (Equiv.addRight (1 : ℤ)) (f := g)
    simp only [Equiv.coe_addRight] at e
    rw [finsum_sub_distrib hg hg', e, sub_self]
  have e := finsum_sub_distrib
    (f := fun n : ℤ => (n.negOnePow : ℤ) * d₁ n + (n.negOnePow : ℤ) * d₃ n)
    (g := fun n : ℤ => (n.negOnePow : ℤ) * d₂ n)
    (((hd₁.union hd₃).subset fun n hn => by
      by_contra h
      simp only [Set.mem_union, Function.mem_support, not_or, not_not] at h
      exact hn (by simp [h.1, h.2])) : Function.HasFiniteSupport _) (fin d₂ hd₂)
  rw [← finsum_add_distrib (fin d₁ hd₁) (fin d₃ hd₃), eq_comm, ← sub_eq_zero, ← e]
  simpa only [key] using hsum

/-! ### The long exact sequence of `Hom(G, -)` -/

section Triangulated

variable [HasZeroObject C] [HasShift C ℤ] [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C]

namespace HomK

variable (ρ : K →+* End G)

omit [HasZeroObject C] [Pretriangulated C] in
theorem shift_map_units_smul {X Y : C} (n : ℤ) (u : ℤˣ) (f : X ⟶ Y) :
    (u • f)⟦n⟧' = u • f⟦n⟧' := by
  rw [Units.smul_def, Units.smul_def, Functor.map_zsmul]

/-- The connecting morphism `T.obj₃⟦n⟧ ⟶ T.obj₁⟦n + 1⟧` of a triangle: the third morphism
`(-1)ⁿ T.mor₃⟦n⟧ ≫ (T.obj₁⟦1⟧⟦n⟧ ≅ T.obj₁⟦n⟧⟦1⟧)` of the shifted triangle `T⟦n⟧`, followed by
`T.obj₁⟦n⟧⟦1⟧ ≅ T.obj₁⟦n + 1⟧`. -/
noncomputable def connecting (T : Triangle C) (n : ℤ) : T.obj₃⟦n⟧ ⟶ T.obj₁⟦n + 1⟧ :=
  (n.negOnePow • T.mor₃⟦n⟧' ≫ (shiftFunctorComm C 1 n).hom.app T.obj₁) ≫
    (shiftFunctorAdd' C n 1 (n + 1) rfl).inv.app T.obj₁

variable (T : Triangle C) (hT : T ∈ distTriang C) (n : ℤ)
include hT

theorem shift_mem_distTriang :
    Triangle.mk (n.negOnePow • T.mor₁⟦n⟧') (n.negOnePow • T.mor₂⟦n⟧')
      (n.negOnePow • T.mor₃⟦n⟧' ≫ (shiftFunctorComm C 1 n).hom.app T.obj₁) ∈ distTriang C :=
  Triangle.shift_distinguished T hT n

theorem comp_zero₁₂ : T.mor₁⟦n⟧' ≫ T.mor₂⟦n⟧' = 0 := by
  rw [← Functor.map_comp, comp_distTriang_mor_zero₁₂ T hT, Functor.map_zero]

theorem isExactAt₁₂ : IsExactAt (G := G) (T.mor₁⟦n⟧') (T.mor₂⟦n⟧') := by
  intro φ hφ
  obtain ⟨ψ, hψ⟩ := Triangle.coyoneda_exact₂ _ (shift_mem_distTriang T hT n) φ (by
    dsimp only [Triangle.mk_mor₂]
    rw [Linear.comp_units_smul, hφ, smul_zero])
  refine ⟨n.negOnePow • ψ, ?_⟩
  dsimp only [Triangle.mk_mor₁] at hψ
  rw [hψ, Linear.comp_units_smul, Linear.units_smul_comp]

theorem comp_zero₂₃ : T.mor₂⟦n⟧' ≫ connecting T n = 0 := by
  have h := comp_distTriang_mor_zero₂₃ _ (shift_mem_distTriang T hT n)
  dsimp only [Triangle.mk_mor₂, Triangle.mk_mor₃] at h
  rw [Linear.units_smul_comp, smul_eq_zero_iff_eq] at h
  rw [connecting, ← assoc, h, zero_comp]

theorem isExactAt₂₃ : IsExactAt (G := G) (T.mor₂⟦n⟧') (connecting T n) := by
  intro φ hφ
  rw [connecting, ← assoc, Preadditive.IsIso.comp_right_eq_zero] at hφ
  obtain ⟨ψ, hψ⟩ := Triangle.coyoneda_exact₃ _ (shift_mem_distTriang T hT n) φ hφ
  refine ⟨n.negOnePow • ψ, ?_⟩
  dsimp only [Triangle.mk_mor₂] at hψ
  rw [hψ, Linear.comp_units_smul, Linear.units_smul_comp]

omit hT [Preadditive C] [HasZeroObject C] [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C] in
theorem shift_mor₁_naturality :
    (shiftFunctorAdd' C n 1 (n + 1) rfl).inv.app T.obj₁ ≫ T.mor₁⟦n + 1⟧' =
      (T.mor₁⟦n⟧')⟦1⟧' ≫ (shiftFunctorAdd' C n 1 (n + 1) rfl).inv.app T.obj₂ :=
  ((shiftFunctorAdd' C n 1 (n + 1) rfl).inv.naturality T.mor₁).symm

theorem comp_zero₃₁ : connecting T n ≫ T.mor₁⟦n + 1⟧' = 0 := by
  have h := comp_distTriang_mor_zero₃₁ _ (shift_mem_distTriang T hT n)
  dsimp only [Triangle.mk_mor₁, Triangle.mk_mor₃, Triangle.mk_obj₁] at h
  rw [shift_map_units_smul, Linear.comp_units_smul, smul_eq_zero_iff_eq] at h
  rw [connecting, assoc, shift_mor₁_naturality, ← assoc, h, zero_comp]

theorem isExactAt₃₁ : IsExactAt (G := G) (connecting T n) (T.mor₁⟦n + 1⟧') := by
  intro φ hφ
  obtain ⟨ψ, hψ⟩ := Triangle.coyoneda_exact₁ _ (shift_mem_distTriang T hT n)
    (φ ≫ (shiftFunctorAdd' C n 1 (n + 1) rfl).hom.app T.obj₁) (by
      dsimp only [Triangle.mk_mor₁, Triangle.mk_obj₁]
      have hn : (shiftFunctorAdd' C n 1 (n + 1) rfl).hom.app T.obj₁ ≫ (T.mor₁⟦n⟧')⟦1⟧' =
          T.mor₁⟦n + 1⟧' ≫ (shiftFunctorAdd' C n 1 (n + 1) rfl).hom.app T.obj₂ :=
        ((shiftFunctorAdd' C n 1 (n + 1) rfl).hom.naturality T.mor₁).symm
      rw [shift_map_units_smul, Linear.comp_units_smul, assoc, hn, ← assoc, hφ, zero_comp,
        smul_zero])
  refine ⟨ψ, ?_⟩
  dsimp only [Triangle.mk_mor₃] at hψ
  rw [connecting, ← assoc, ← hψ, assoc, Iso.hom_inv_id_app, comp_id]

theorem finrankHom_obj₂ [FiniteDimensional K (HomK ρ (T.obj₂⟦n⟧))] :
    finrankHom ρ (T.obj₂⟦n⟧) = rankHom ρ (T.mor₁⟦n⟧') + rankHom ρ (T.mor₂⟦n⟧') :=
  finrankHom_eq_add (ρ := ρ) (comp_zero₁₂ T hT n) (isExactAt₁₂ T hT n)

theorem finrankHom_obj₃ [FiniteDimensional K (HomK ρ (T.obj₃⟦n⟧))] :
    finrankHom ρ (T.obj₃⟦n⟧) = rankHom ρ (T.mor₂⟦n⟧') + rankHom ρ (connecting T n) :=
  finrankHom_eq_add (ρ := ρ) (comp_zero₂₃ T hT n) (isExactAt₂₃ T hT n)

theorem finrankHom_obj₁ [FiniteDimensional K (HomK ρ (T.obj₁⟦n + 1⟧))] :
    finrankHom ρ (T.obj₁⟦n + 1⟧) = rankHom ρ (connecting T n) + rankHom ρ (T.mor₁⟦n + 1⟧') :=
  finrankHom_eq_add (ρ := ρ) (comp_zero₃₁ T hT n) (isExactAt₃₁ T hT n)

/-! ### The Euler characteristic -/

section Euler

omit hT

/-- An object `Y` has *finite `G`-cohomology* if every `Hom(G, Y⟦n⟧)` is finite-dimensional and
only finitely many of them are nonzero. -/
def IsFin (Y : C) : Prop :=
  (∀ n : ℤ, FiniteDimensional K (HomK ρ (Y⟦n⟧))) ∧
    (Function.support fun n : ℤ => finrankHom ρ (Y⟦n⟧)).Finite

/-- The Euler characteristic `χ_G(Y) = ∑ₙ (-1)ⁿ dim_K Hom(G, Y⟦n⟧)`. -/
noncomputable def eulerChar (Y : C) : ℤ :=
  ∑ᶠ n : ℤ, (n.negOnePow : ℤ) * finrankHom ρ (Y⟦n⟧)

variable {ρ}

include hT in
/-- In a distinguished triangle whose outer vertices have finite `G`-cohomology, so does the
middle vertex, and the Euler characteristic is additive. -/
theorem isFin_obj₂_and_eulerChar (h₁ : IsFin ρ T.obj₁) (h₃ : IsFin ρ T.obj₃) :
    IsFin ρ T.obj₂ ∧ eulerChar ρ T.obj₂ = eulerChar ρ T.obj₁ + eulerChar ρ T.obj₃ := by
  have fd₂ : ∀ n : ℤ, FiniteDimensional K (HomK ρ (T.obj₂⟦n⟧)) := fun n => by
    have := h₁.1 n; have := h₃.1 n
    exact finiteDimensional_of_isExactAt (ρ := ρ) (comp_zero₁₂ T hT n) (isExactAt₁₂ T hT n)
  obtain ⟨hfin, hsum⟩ := alternating_finsum_of_exact (fun n => finrankHom ρ (T.obj₁⟦n⟧))
    (fun n => finrankHom ρ (T.obj₂⟦n⟧)) (fun n => finrankHom ρ (T.obj₃⟦n⟧))
    (fun n => rankHom ρ (T.mor₁⟦n⟧')) (fun n => rankHom ρ (T.mor₂⟦n⟧'))
    (fun n => rankHom ρ (connecting T n))
    (fun n => by have := h₁.1 (n + 1); exact finrankHom_obj₁ ρ T hT n)
    (fun n => by have := fd₂ n; exact finrankHom_obj₂ ρ T hT n)
    (fun n => by have := h₃.1 n; exact finrankHom_obj₃ ρ T hT n) h₁.2 h₃.2
  exact ⟨⟨fd₂, hfin⟩, hsum⟩

omit [HasZeroObject C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C] in
theorem finrankHom_shift_shift (Y : C) (m n : ℤ) :
    finrankHom ρ (Y⟦m⟧⟦n⟧) = finrankHom ρ (Y⟦m + n⟧) :=
  finrankHom_eq_of_iso ((shiftFunctorAdd' C m n (m + n) rfl).app Y).symm

omit [HasZeroObject C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C] in
theorem IsFin.shift {Y : C} (h : IsFin ρ Y) (m : ℤ) : IsFin ρ (Y⟦m⟧) := by
  refine ⟨fun n => ?_, ?_⟩
  · have := h.1 (m + n)
    exact finiteDimensional_of_iso ((shiftFunctorAdd' C m n (m + n) rfl).app Y)
  · refine (h.2.preimage (Set.injOn_of_injective (add_right_injective m))).subset fun n hn => ?_
    simpa only [Function.mem_support, Set.mem_preimage, finrankHom_shift_shift] using hn

omit [HasZeroObject C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C] in
theorem eulerChar_shift (Y : C) (m : ℤ) :
    eulerChar ρ (Y⟦m⟧) = (m.negOnePow : ℤ) * eulerChar ρ Y := by
  rw [eulerChar, eulerChar, mul_finsum]
  simp only [finrankHom_shift_shift]
  have e := finsum_comp_equiv (Equiv.addLeft m)
    (f := fun k : ℤ => ((k - m).negOnePow : ℤ) * finrankHom ρ (Y⟦k⟧))
  simp only [Equiv.coe_addLeft, add_sub_cancel_left] at e
  rw [e]
  refine finsum_congr fun k => ?_
  rw [Int.negOnePow_sub, Units.val_mul, ← mul_assoc, mul_comm (m.negOnePow : ℤ)]

omit [HasZeroObject C] [Pretriangulated C] in
theorem isFin_of_isZero {Y : C} (hY : IsZero Y) : IsFin ρ Y := by
  have hs : ∀ n : ℤ, Subsingleton (HomK ρ (Y⟦n⟧)) := fun n =>
    ⟨fun f g => ((Functor.map_isZero _ hY).eq_of_tgt f g : _)⟩
  refine ⟨fun n => inferInstance, ?_⟩
  convert Set.finite_empty
  ext n
  simp only [Function.mem_support, ne_eq, Set.mem_empty_iff_false, iff_false, not_not]
  exact Module.finrank_zero_of_subsingleton

omit [HasZeroObject C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C] in
theorem IsFin.of_retract {X Y : C} (r : Retract X Y) (h : IsFin ρ Y) : IsFin ρ X := by
  have hinj : ∀ n : ℤ, Function.Injective (postcomp ρ (r.i⟦n⟧')) := fun n =>
    Function.LeftInverse.injective (g := postcomp ρ (r.r⟦n⟧')) fun (f : G ⟶ X⟦n⟧) => by
      change (f ≫ r.i⟦n⟧') ≫ r.r⟦n⟧' = f
      rw [assoc, ← Functor.map_comp, r.retract, CategoryTheory.Functor.map_id, comp_id]
  have fd : ∀ n : ℤ, FiniteDimensional K (HomK ρ (X⟦n⟧)) := fun n => by
    have := h.1 n
    exact Module.Finite.of_injective _ (hinj n)
  refine ⟨fd, h.2.subset fun n hn => ?_⟩
  have := h.1 n
  simp only [Function.mem_support, ne_eq] at hn ⊢
  have := LinearMap.finrank_le_finrank_of_injective (hinj n)
  exact fun h0 => hn (by rw [finrankHom] at *; omega)

variable (ρ) in
/-- Objects with finite `G`-cohomology form a thick subcategory. -/
theorem isThick_isFin : IsThick (IsFin ρ) where
  zero := isFin_of_isZero (isZero_zero C)
  shift _ n h := h.shift n
  ext₂ T hT h₁ h₃ := (isFin_obj₂_and_eulerChar T hT h₁ h₃).1
  retract r h := h.of_retract r

omit [HasZeroObject C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C] in
theorem eulerChar_eq_of_iso {Y Z : C} (e : Y ≅ Z) : eulerChar ρ Y = eulerChar ρ Z := by
  simp only [eulerChar, finrankHom_eq_of_iso ((shiftFunctor C _).mapIso e)]

end Euler

end HomK

end Triangulated

/-! ### Triangulated subcategories -/

section Subcategory

variable [HasZeroObject C] [HasShift C ℤ] [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C] (𝒮 : ObjectProperty C) [𝒮.IsTriangulated]

/-- A distinguished triangle of `C` whose vertices lie in a triangulated subcategory `𝒮` gives the
relation `[T.obj₂] = [T.obj₁] + [T.obj₃]` in `K₀(𝒮)`. -/
theorem K0.mk_obj₂_of_mem (T : Triangle C) (hT : T ∈ distTriang C) (h₁ : 𝒮 T.obj₁)
    (h₂ : 𝒮 T.obj₂) (h₃ : 𝒮 T.obj₃) :
    K0.mk (⟨T.obj₂, h₂⟩ : 𝒮.FullSubcategory) = K0.mk ⟨T.obj₁, h₁⟩ + K0.mk ⟨T.obj₃, h₃⟩ := by
  let T' : Triangle 𝒮.FullSubcategory :=
    Triangle.mk (𝒮.fullyFaithfulι.preimage T.mor₁ :
        (⟨T.obj₁, h₁⟩ : 𝒮.FullSubcategory) ⟶ ⟨T.obj₂, h₂⟩)
      (𝒮.fullyFaithfulι.preimage T.mor₂ :
        (⟨T.obj₂, h₂⟩ : 𝒮.FullSubcategory) ⟶ ⟨T.obj₃, h₃⟩)
      (𝒮.fullyFaithfulι.preimage
        (T.mor₃ ≫ (𝒮.ι.commShiftIso (1 : ℤ)).inv.app ⟨T.obj₁, h₁⟩))
  have hT' : T' ∈ distTriang _ :=
    isomorphic_distinguished _ hT _ (Triangle.isoMk _ _ (Iso.refl _) (Iso.refl _) (Iso.refl _)
      (by simp [T']) (by simp [T']) (by simp [T']))
  exact K0.mk_obj₂ T' hT'

variable {𝒮}

/-- In `𝒮`, the object `X⟦n⟧` of `C` is the shift of `X`. -/
noncomputable def shiftObjIso (X : 𝒮.FullSubcategory) (n : ℤ) :
    (⟨X.obj⟦n⟧, 𝒮.le_shift n _ X.2⟩ : 𝒮.FullSubcategory) ≅ X⟦n⟧ :=
  𝒮.fullyFaithfulι.preimageIso ((𝒮.ι.commShiftIso n).app X).symm

end Subcategory

/-! ### Orthonormal generating families -/

section Orthonormal

variable [HasShift C ℤ] {J : Type*}

/-- A finite family of objects `G j` with `K`-structures `ρ j : K →+* End (G j)` is an
*orthonormal generating family* of a triangulated subcategory `𝒮` if the `G j` lie in `𝒮`,
`Hom(G j, G j'⟦n⟧) = 0` unless `j = j'` and `n = 0`, every endomorphism of `G j` is some `ρ j c`,
the `G j` are nonzero, every object of `𝒮` has finite `G j`-cohomology, and an object `X` of `𝒮`
with `Hom(G j, X⟦n⟧) = 0` for all `j` and `n` is zero. -/
structure IsOrthonormalGenerating (𝒮 : ObjectProperty C) (G : J → C)
    (ρ : ∀ j, K →+* End (G j)) : Prop where
  mem : ∀ j, 𝒮 (G j)
  orth : ∀ (j j' : J) (n : ℤ), (j ≠ j' ∨ n ≠ 0) → ∀ f : G j ⟶ (G j')⟦n⟧, f = 0
  surj : ∀ (j : J) (f : G j ⟶ G j), ∃ c : K, f = ρ j c
  nonzero : ∀ j, ¬ IsZero (G j)
  isFin : ∀ X, 𝒮 X → ∀ j, HomK.IsFin (ρ j) X
  gen : ∀ X, 𝒮 X → (∀ (j : J) (n : ℤ) (f : G j ⟶ X⟦n⟧), f = 0) → IsZero X

namespace IsOrthonormalGenerating

variable {𝒮 : ObjectProperty C} {G : J → C} {ρ : ∀ j, K →+* End (G j)}
  (hG : IsOrthonormalGenerating 𝒮 G ρ)
include hG

theorem ρ_injective (j : J) : Function.Injective (ρ j) := by
  refine (injective_iff_map_eq_zero _).mpr fun c hc => ?_
  by_contra h
  apply hG.nonzero j
  rw [IsZero.iff_id_eq_zero, ← End.one_def, ← map_one (ρ j), ← mul_inv_cancel₀ h, map_mul, hc,
    zero_mul]

/-- `End(G j) = K`: the map `c ↦ ρ j c` is a linear isomorphism `K ≃ Hom(G j, G j)`. -/
noncomputable def endEquiv (j : J) : K ≃ₗ[K] HomK (ρ j) (G j) :=
  LinearEquiv.ofBijective
    { toFun := fun c => (show HomK (ρ j) (G j) from ρ j c)
      map_add' := fun c c' => map_add (ρ j) c c'
      map_smul' := fun c c' => by
        change ρ j (c * c') = (ρ j c ≫ ρ j c' : G j ⟶ G j)
        rw [mul_comm, map_mul]
        rfl }
    ⟨hG.ρ_injective j, fun f => let ⟨c, hc⟩ := hG.surj j f; ⟨c, hc.symm⟩⟩

theorem finrankHom_self (j : J) : HomK.finrankHom (ρ j) (G j) = 1 :=
  (hG.endEquiv j).finrank_eq.symm.trans (Module.finrank_self K)

theorem subsingleton_homK {j j' : J} {n : ℤ} (h : j ≠ j' ∨ n ≠ 0) :
    Subsingleton (HomK (ρ j) ((G j')⟦n⟧)) :=
  ⟨fun f g => (hG.orth j j' n h f).trans (hG.orth j j' n h g).symm⟩

variable [DecidableEq J]

/-- `dim Hom(G j, G j'⟦n⟧)` is `1` if `j = j'` and `n = 0`, and `0` otherwise. -/
theorem finrankHom_G (j j' : J) (n : ℤ) :
    HomK.finrankHom (ρ j) ((G j')⟦n⟧) = if j = j' ∧ n = 0 then 1 else 0 := by
  split_ifs with h
  · obtain ⟨rfl, rfl⟩ := h
    exact (HomK.finrankHom_eq_of_iso ((shiftFunctorZero C ℤ).app (G j))).trans
      (hG.finrankHom_self j)
  · have := hG.subsingleton_homK (j := j) (j' := j') (n := n) (by tauto)
    exact Module.finrank_zero_of_subsingleton

theorem eulerChar_G (j j' : J) :
    HomK.eulerChar (ρ j) (G j') = if j = j' then 1 else 0 := by
  rw [HomK.eulerChar, finsum_eq_single _ 0 fun n hn => by simp [hG.finrankHom_G, hn]]
  simp [hG.finrankHom_G]

/-! #### The total dimension -/

variable {𝒮 : ObjectProperty C} {G : J → C} {ρ : ∀ j, K →+* End (G j)}

omit [DecidableEq J] in
/-- The total dimension `∑ⱼ ∑ₙ dim Hom(G j, X⟦n⟧)` of an object. -/
noncomputable def totalDim' [Fintype J] (ρ : ∀ j, K →+* End (G j)) (X : C) : ℕ :=
  ∑ j, ∑ᶠ n : ℤ, HomK.finrankHom (ρ j) (X⟦n⟧)

end IsOrthonormalGenerating

end Orthonormal

section Generation

variable [HasZeroObject C] [HasShift C ℤ] [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C] {J : Type*} [Fintype J] [DecidableEq J]
  {𝒮 : ObjectProperty C} [𝒮.IsTriangulated] [𝒮.IsClosedUnderIsomorphisms]
  {G : J → C} {ρ : ∀ j, K →+* End (G j)}

namespace IsOrthonormalGenerating

omit [HasZeroObject C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
  [DecidableEq J] [𝒮.IsTriangulated] [𝒮.IsClosedUnderIsomorphisms] in
theorem totalDim'_shift (X : C) (m : ℤ) : totalDim' ρ (X⟦m⟧) = totalDim' ρ X := by
  refine Finset.sum_congr rfl fun j _ => ?_
  simp only [HomK.finrankHom_shift_shift]
  exact finsum_comp_equiv (Equiv.addLeft m) (f := fun k => HomK.finrankHom (ρ j) (X⟦k⟧))

variable (hG : IsOrthonormalGenerating 𝒮 G ρ)
include hG

omit [Fintype J] [𝒮.IsTriangulated] [𝒮.IsClosedUnderIsomorphisms] in
/-- Completing a nonzero morphism `f : G j ⟶ Y` to a distinguished triangle `G j → Y → Z → ⋯`
lowers the dimensions by one exactly at `Hom(G j, -⟦0⟧)`. -/
theorem finrankHom_cone {j : J} {Y Z : C} (hY : 𝒮 Y) (hZ : 𝒮 Z) {f : G j ⟶ Y} (hf : f ≠ 0)
    {g : Y ⟶ Z} {h : Z ⟶ (G j)⟦(1 : ℤ)⟧} (hT : Triangle.mk f g h ∈ distTriang C) (j' : J)
    (m : ℤ) :
    HomK.finrankHom (ρ j') (Z⟦m⟧) + (if j' = j ∧ m = 0 then 1 else 0) =
      HomK.finrankHom (ρ j') (Y⟦m⟧) := by
  have hinj : ∀ m : ℤ, Function.Injective (HomK.postcomp (ρ j') (f⟦m⟧')) := by
    intro m
    refine (injective_iff_map_eq_zero _).mpr fun (φ : G j' ⟶ (G j)⟦m⟧) hφ => ?_
    change φ ≫ f⟦m⟧' = 0 at hφ
    by_cases hjm : j' = j ∧ m = 0
    · obtain ⟨rfl, rfl⟩ := hjm
      let e := (shiftFunctorZero C ℤ)
      have hnat : f⟦0⟧' ≫ e.hom.app Y = e.hom.app (G j') ≫ f := e.hom.naturality f
      obtain ⟨c, hc⟩ := hG.surj j' (φ ≫ e.hom.app (G j'))
      have h0 : (c • (show HomK (ρ j') Y from f)) = 0 := by
        change ρ j' c ≫ f = 0
        rw [← hc, assoc, ← hnat, ← assoc, hφ, zero_comp]
      rcases smul_eq_zero.mp h0 with hc0 | hf0
      · rw [hc0, map_zero] at hc
        exact (cancel_mono (e.hom.app (G j'))).mp (hc.trans (zero_comp).symm)
      · exact absurd hf0 hf
    · exact (hG.subsingleton_homK (by tauto)).elim _ _
  have fd : ∀ (W : C), 𝒮 W → ∀ m : ℤ, FiniteDimensional K (HomK (ρ j') (W⟦m⟧)) :=
    fun W hW m => (hG.isFin W hW j').1 m
  have hG' : 𝒮 (G j) := hG.mem j
  have ha : ∀ m : ℤ, HomK.rankHom (ρ j') (f⟦m⟧') = HomK.finrankHom (ρ j') ((G j)⟦m⟧) :=
    fun m => LinearMap.finrank_range_of_inj (hinj m)
  have h₁ := by
    have : FiniteDimensional K (HomK (ρ j') ((Triangle.mk f g h).obj₁⟦m + 1⟧)) :=
      fd _ hG' (m + 1)
    exact HomK.finrankHom_obj₁ (ρ j') _ hT m
  have h₂ := by
    have : FiniteDimensional K (HomK (ρ j') ((Triangle.mk f g h).obj₂⟦m⟧)) := fd _ hY m
    exact HomK.finrankHom_obj₂ (ρ j') _ hT m
  have h₃ := by
    have : FiniteDimensional K (HomK (ρ j') ((Triangle.mk f g h).obj₃⟦m⟧)) := fd _ hZ m
    exact HomK.finrankHom_obj₃ (ρ j') _ hT m
  dsimp only [Triangle.mk_obj₁, Triangle.mk_obj₂, Triangle.mk_obj₃, Triangle.mk_mor₁,
    Triangle.mk_mor₂] at h₁ h₂ h₃
  rw [ha] at h₁ h₂
  rw [← hG.finrankHom_G j' j m]
  omega

omit [𝒮.IsTriangulated] [𝒮.IsClosedUnderIsomorphisms] in
/-- Completing a nonzero morphism `f : G j ⟶ Y` to a distinguished triangle `G j → Y → Z → ⋯`
lowers the total dimension by one. -/
theorem totalDim'_cone {j : J} {Y Z : C} (hY : 𝒮 Y) (hZ : 𝒮 Z) {f : G j ⟶ Y} (hf : f ≠ 0)
    {g : Y ⟶ Z} {h : Z ⟶ (G j)⟦(1 : ℤ)⟧} (hT : Triangle.mk f g h ∈ distTriang C) :
    totalDim' ρ Z + 1 = totalDim' ρ Y := by
  have hδ : ∀ j' : J, (Function.support fun m : ℤ => if j' = j ∧ m = 0 then 1 else 0).Finite :=
    fun j' => (Set.finite_singleton (0 : ℤ)).subset fun m hm => by
      by_contra h0
      exact hm (by simp only [Set.mem_singleton_iff] at h0; simp [h0])
  have hsum : ∀ j' : J, ∑ᶠ m : ℤ, HomK.finrankHom (ρ j') (Y⟦m⟧) =
      ∑ᶠ m : ℤ, HomK.finrankHom (ρ j') (Z⟦m⟧) + if j' = j then 1 else 0 := by
    intro j'
    rw [← finsum_congr (hG.finrankHom_cone hY hZ hf hT j'),
      finsum_add_distrib (hG.isFin Z hZ j').2 (hδ j')]
    congr 1
    rw [finsum_eq_single _ 0 fun m hm => by simp [hm]]
    simp
  simp only [totalDim', hsum, Finset.sum_add_distrib, Finset.sum_ite_eq', Finset.mem_univ,
    ite_true]

/-- The classes `[G j]` generate `K₀(𝒮)`: `[X] = ∑ⱼ χ_{G j}(X) [G j]`. -/
theorem mk_eq_sum (X : 𝒮.FullSubcategory) :
    K0.mk X = ∑ j, HomK.eulerChar (ρ j) X.obj • K0.mk (⟨G j, hG.mem j⟩ : 𝒮.FullSubcategory) := by
  induction hN : totalDim' ρ X.obj using Nat.strong_induction_on generalizing X with
  | _ N ih =>
  by_cases h0 : ∀ (j : J) (n : ℤ) (f : G j ⟶ X.obj⟦n⟧), f = 0
  · have hX : IsZero X := IsZero.of_full_of_faithful_of_isZero 𝒮.ι X (hG.gen _ X.2 h0)
    have hχ : ∀ j, HomK.eulerChar (ρ j) X.obj = 0 := fun j => by
      refine finsum_eq_zero_of_forall_eq_zero fun n => ?_
      have : Subsingleton (HomK (ρ j) (X.obj⟦n⟧)) := ⟨fun f g => (h0 j n f).trans (h0 j n g).symm⟩
      rw [HomK.finrankHom, Module.finrank_zero_of_subsingleton, Nat.cast_zero, mul_zero]
    simp only [K0.mk_eq_zero_of_isZero hX, hχ, zero_smul, Finset.sum_const_zero]
  · push Not at h0
    obtain ⟨j, n, f, hf⟩ := h0
    obtain ⟨Z, g, h, hT⟩ := distinguished_cocone_triangle f
    have hY : 𝒮 (X.obj⟦n⟧) := 𝒮.le_shift n _ X.2
    have hZ : 𝒮 Z := 𝒮.ext_of_isTriangulatedClosed₃ _ hT (hG.mem j) hY
    have hdim := hG.totalDim'_cone hY hZ hf hT
    rw [totalDim'_shift, hN] at hdim
    have ihZ := ih _ (show totalDim' ρ Z < N by omega) ⟨Z, hZ⟩ rfl
    have hK := K0.mk_obj₂_of_mem 𝒮 _ hT (hG.mem j) hY hZ
    dsimp only [Triangle.mk_obj₁, Triangle.mk_obj₂, Triangle.mk_obj₃] at hK
    rw [K0.mk_eq_of_iso (shiftObjIso X n), K0.mk_shift] at hK
    have hχ : ∀ j', HomK.eulerChar (ρ j') X.obj =
        (n.negOnePow : ℤ) * ((if j' = j then 1 else 0) + HomK.eulerChar (ρ j') Z) := fun j' => by
      have e := (HomK.isFin_obj₂_and_eulerChar _ hT (hG.isFin _ (hG.mem j) j')
        (hG.isFin _ hZ j')).2
      dsimp only [Triangle.mk_obj₁, Triangle.mk_obj₂, Triangle.mk_obj₃] at e
      rw [HomK.eulerChar_shift, hG.eulerChar_G] at e
      rw [← e, ← mul_assoc, ← Units.val_mul, Int.units_mul_self, Units.val_one, one_mul]
    have hX : K0.mk X = n.negOnePow • (n.negOnePow • K0.mk X) := by
      rw [smul_smul, Int.units_mul_self, one_smul]
    rw [hX, hK, ihZ]
    simp only [hχ, Units.smul_def, mul_smul, add_smul, ite_smul, one_smul, zero_smul,
      Finset.sum_add_distrib, Finset.sum_ite_eq', Finset.mem_univ, ite_true, ← Finset.smul_sum]

/-- The Euler characteristics `χ_{G j}` as a homomorphism `K₀(𝒮) → (J → ℤ)`. -/
noncomputable def eulerCharHom : K0 𝒮.FullSubcategory →+ (J → ℤ) :=
  K0.lift (fun X j => HomK.eulerChar (ρ j) X.obj) fun T hT => by
    funext j
    exact (HomK.isFin_obj₂_and_eulerChar (𝒮.ι.mapTriangle.obj T) hT (hG.isFin _ T.obj₁.2 j)
      (hG.isFin _ T.obj₃.2 j)).2

omit [Fintype J] [DecidableEq J] [𝒮.IsClosedUnderIsomorphisms] in
theorem eulerCharHom_mk (X : 𝒮.FullSubcategory) (j : J) :
    hG.eulerCharHom (K0.mk X) j = HomK.eulerChar (ρ j) X.obj := by
  rw [eulerCharHom, K0.lift_mk]

/-- **`K₀` of a triangulated category with an orthonormal generating family.** `K₀(𝒮)` is free
on the classes `[G j]`: the Euler characteristics give `K₀(𝒮) ≃+ (J → ℤ)`,
`[X] ↦ (χ_{G j}(X))_j`, with `[G j] ↦ Pi.single j 1`. -/
noncomputable def K0Equiv : K0 𝒮.FullSubcategory ≃+ (J → ℤ) where
  toFun := hG.eulerCharHom
  invFun v := ∑ j, v j • K0.mk (⟨G j, hG.mem j⟩ : 𝒮.FullSubcategory)
  left_inv x := by
    induction x using K0.induction_on with
    | zero => simp
    | mk X =>
      conv_rhs => rw [hG.mk_eq_sum X]
      simp only [eulerCharHom_mk]
    | neg x hx =>
      simp only [map_neg, Pi.neg_apply, neg_smul, Finset.sum_neg_distrib, hx]
    | add x y hx hy =>
      simp only [map_add, Pi.add_apply, add_smul, Finset.sum_add_distrib, hx, hy]
  right_inv v := by
    funext j'
    simp only [map_sum, map_zsmul, Finset.sum_apply, Pi.smul_apply, eulerCharHom_mk,
      hG.eulerChar_G, smul_eq_mul, mul_ite, mul_one, mul_zero, Finset.sum_ite_eq,
      Finset.mem_univ, ite_true]
  map_add' := map_add _

theorem K0Equiv_mk (X : 𝒮.FullSubcategory) (j : J) :
    hG.K0Equiv (K0.mk X) j = HomK.eulerChar (ρ j) X.obj :=
  hG.eulerCharHom_mk X j

theorem K0Equiv_mk_G (j : J) :
    hG.K0Equiv (K0.mk (⟨G j, hG.mem j⟩ : 𝒮.FullSubcategory)) = Pi.single j 1 := by
  funext j'
  rw [K0Equiv_mk, hG.eulerChar_G, Pi.single_apply]

theorem K0Equiv_symm_apply (v : J → ℤ) :
    hG.K0Equiv.symm v = ∑ j, v j • K0.mk (⟨G j, hG.mem j⟩ : 𝒮.FullSubcategory) :=
  rfl

end IsOrthonormalGenerating

end Generation

end DG
