import DG.Category.Derived.Schnurer
import DG.K0.DGCategory
import DG.K0.DGRing

/-!
# The Grothendieck group of a positive dg category

Let `C` be a dg category and `K₀(C) = K₀(D^c(C))` (`DG.DGCategory.K0`). The cells
`Q (e · C(X, -))⟦n⟧` are compact, with classes `DG.DGCategory.K0.cell e n = (-1)ⁿ [e · C(X, -)]`
(`DG.DGCategory.K0.cell_eq`), and the class of a finite-cell module is the signed sum of the
classes of its cells (`DG.DGCategory.K0.mk_finiteCell`).

For `C` positive (`DG.DGCategory.IsPositive C`), every compact object has an ordered cell tower
with simple cells (Schnürer's theorem, `DG.DGCategory.IsPositive.hasOrderedCellTower_of_isCompact`),
so `K₀(C)` is generated by the classes `[e · C(X, -)]` of the simple corners
(`DG.DGCategory.IsPositive.closure_cell_eq_top`).
-/

open CategoryTheory Limits

universe w v u

noncomputable section

set_option backward.isDefEq.respectTransparency false

namespace DG

namespace DGCategory

variable {C : Type u} [Category.{v} C] [Preadditive C] [∀ X Y : C, DGAddCommGroup (X ⟶ Y)]
  [DGCategory C] [CatModule.HasDerivedCategory.{max u v w, max u v w} C]

open CatModule CatModule.DerivedCategory

namespace K0

/-- The cell `Q (e · C(X, -))⟦n⟧` as an object of the perfect derived category `D^c(C)`. -/
abbrev perfectCell {X : C} (e : Idempotent X) (n : ℤ) :
    CatModule.PerfectDerivedCategory.{max u v w, max u v w} C :=
  ⟨CatModule.DerivedCategory.cell.{max u v w, max u w} e n, isCompact_cell e n⟩

/-- The class `[Q (e · C(X, -))⟦n⟧] ∈ K₀(C)` of a cell. -/
abbrev cell {X : C} (e : Idempotent X) (n : ℤ) : K0.{max u v w, max u v w} C :=
  DG.K0.mk (perfectCell.{w} e n)

/-- The class of a cell: `[(e · C(X, -))⟦n⟧] = (-1)ⁿ [e · C(X, -)]`. -/
theorem cell_eq {X : C} (e : Idempotent X) (n : ℤ) : cell.{w} e n = n.negOnePow • cell e 0 := by
  rw [cell, ← DG.K0.mk_shift]
  refine DG.K0.mk_eq_of_iso_obj ?_
  exact (cellShiftIso.{max u v w, max u w} e 0 n ≪≫ eqToIso (by rw [zero_add])).symm ≪≫
    (((compactSubcategory.{max u v w} (CatModule.DerivedCategory C)).ι.commShiftIso n).app
      (perfectCell.{w} e 0)).symm

/-- **The class of a finite-cell module**: if `P` has a finite-cell filtration with subquotients
`(eᵢ · C(Xᵢ, -))⟦nᵢ⟧`, then `[P] = ∑ᵢ (-1)^{nᵢ} [eᵢ · C(Xᵢ, -)]` in `K₀(C)`. -/
theorem mk_finiteCell {P : CatModule.{max u v w} C}
    (S : CatModule.FiniteCellFiltration.{max u w} P) :
    DG.K0.mk (⟨Q.obj P, S.isCompact_Q_obj⟩ :
      CatModule.PerfectDerivedCategory.{max u v w, max u v w} C) =
      ∑ i, (S.deg i).negOnePow • cell (S.e i) 0 := by
  rw [S.cellTower.mk_eq_sum fun _ _ => isCompact_cell _ _,
    CatModule.FiniteCellFiltration.cells,
    List.map_ofFn, List.sum_ofFn]
  exact Finset.sum_congr rfl fun i _ => cell_eq _ _

end K0

namespace IsPositive

variable (hC : IsPositive C)
include hC

/-- The class in `K₀(C)` of a compact object of `D(C)` is a `ℤ`-linear combination of the
classes `[e · C(X, -)]` of the simple corners, by Schnürer's theorem. -/
theorem mk_mem_closure_cell (X : CatModule.PerfectDerivedCategory.{max u v w, max u v w} C) :
    DG.K0.mk X ∈ AddSubgroup.closure
      (Set.range fun c : SimpleCorner C => K0.cell.{w} c.1.2 0) := by
  obtain ⟨l, -, hl⟩ := hC.hasOrderedCellTower_of_isCompact.{w} (Y := X.obj) X.property
  have h := CellTower.mk_eq_sum.{max u v w}
    (fun (c : SimpleCorner C) n => isCompact_cell c.1.2 n) hl
  change DG.K0.mk (⟨X.obj, X.property⟩ : CatModule.PerfectDerivedCategory C) ∈ _
  rw [h]
  refine AddSubgroup.list_sum_mem _ fun x hx => ?_
  obtain ⟨c, -, rfl⟩ := List.mem_map.mp hx
  change K0.cell.{w} c.1.1.2 c.2 ∈ _
  rw [K0.cell_eq, Units.smul_def]
  exact AddSubgroup.zsmul_mem _ (AddSubgroup.subset_closure (Set.mem_range_self c.1)) _

/-- `K₀(C)` of a positive dg category is generated by the classes `[e · C(X, -)]` of the simple
corners. -/
theorem closure_cell_eq_top :
    AddSubgroup.closure (Set.range fun c : SimpleCorner C => K0.cell.{w} c.1.2 0) = ⊤ := by
  refine eq_top_iff.mpr fun x _ => ?_
  obtain ⟨X, rfl⟩ := DG.K0.exists_mk_eq x
  exact hC.mk_mem_closure_cell X

end IsPositive

end DGCategory

end DG

end
