import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.LinearAlgebra.Dimension.Free
import Mathlib.LinearAlgebra.FreeModule.PID
import Mathlib.RingTheory.Flat.TorsionFree
import Mathlib.RingTheory.LocalRing.Module
import Mathlib.Algebra.Category.ModuleCat.Projective
import DG.K0.PerfectCompact

/-!
# The rank isomorphism `K₀(R) ≃ ℤ`

Let `R` be a nontrivial commutative ring over which every finitely generated projective module is
free, e.g. a principal ideal domain (`ℤ`, a field) or a local ring. Then the rank is an
isomorphism `DG.ProjK0 R ≃+ ℤ` from the Grothendieck group of finitely generated projective
`R`-modules, sending `[R]` to `1`. Combined with `DG.DGRing.K0.projK0Equiv`, the Grothendieck
group `K₀(R) = K₀(D^c(R))` of the dg ring `R` (concentrated in degree `0`) is `ℤ`, generated by
`[R]` (roadmap 5.6).

## Main definitions and results

* `DG.ProjK0.rank R hfree : DG.ProjK0 R →+ ℤ`, `[P] ↦ rank P`, additive since short exact
  sequences of projective modules split; `DG.ProjK0.mk_eq_finrank_smul`: `[P] = (rank P) • [R]`.
* `DG.ProjK0.rankEquiv R hfree : DG.ProjK0 R ≃+ ℤ`, `DG.ProjK0.rankEquiv_mk_self`: `[R] ↦ 1`;
  the hypothesis `hfree` holds for principal ideal domains (`DG.IsFGProjective.free_of_isPID`) and
  for local rings (`DG.IsFGProjective.free_of_isLocalRing`).
* `DG.DGRing.K0.rankEquiv R hfree : DG.DGRing.K0 R ≃+ ℤ` with `[R] ↦ 1`
  (`DG.DGRing.K0.rankEquiv_self`), `DG.DGRing.K0.equivIntOfIsPrincipalIdealRing` (in
  particular `K₀(ℤ) ≃+ ℤ` with `[ℤ] ↦ 1`) and `DG.DGRing.K0.equivIntOfIsLocalRing`.
-/

open CategoryTheory Category Limits

universe v u

namespace DG

namespace IsFGProjective

variable {R : Type u} [CommRing R]

/-- Over a principal ideal domain, finitely generated projective modules are free (they are
flat, hence torsion-free). -/
theorem free_of_isPID [IsDomain R] [IsPrincipalIdealRing R] {M : ModuleCat.{v} R}
    (hM : IsFGProjective R M) : Module.Free R M := by
  obtain ⟨_, _⟩ := hM
  infer_instance

/-- Over a local ring, finitely generated projective modules are free. -/
theorem free_of_isLocalRing [IsLocalRing R] {M : ModuleCat.{v} R} (hM : IsFGProjective R M) :
    Module.Free R M := by
  obtain ⟨_, _⟩ := hM
  exact Module.free_of_flat_of_isLocalRing

end IsFGProjective

namespace ProjK0

section Pi

variable (R : Type u) [CommRing R]

/-- `Rⁿ` is a finitely generated projective module. -/
theorem isFGProjective_pi (n : ℕ) : IsFGProjective R (ModuleCat.of R (Fin n → R)) :=
  ⟨inferInstance, inferInstance⟩

/-- `[Rⁿ] = n • [R]`. -/
theorem mk_pi (n : ℕ) :
    mk (ModuleCat.of R (Fin n → R)) (isFGProjective_pi R n) =
      n • mk (ModuleCat.of R R) (IsFGProjective.self R) := by
  induction n with
  | zero =>
    rw [zero_smul]
    exact mk_eq_zero_of_isZero (ModuleCat.isZero_of_subsingleton _) _
  | succ n ih =>
    let e : ModuleCat.of R (Fin (n + 1) → R) ≅
        ModuleCat.of R R ⊞ ModuleCat.of R (Fin n → R) :=
      (Fin.consLinearEquiv R fun _ : Fin (n + 1) => R).toModuleIso.symm ≪≫
        (ModuleCat.biprodIsoProd (ModuleCat.of R R) (ModuleCat.of R (Fin n → R))).symm
    rw [mk_eq_of_iso e _ ((IsFGProjective.self R).biprod (isFGProjective_pi R n)),
      mk_biprod (IsFGProjective.self R) (isFGProjective_pi R n), ih,
      succ_nsmul']

end Pi

variable (R : Type u) [CommRing R] [Nontrivial R]
  (hfree : ∀ M : ModuleCat.{u} R, IsFGProjective R M → Module.Free R M)

/-- The rank `[P] ↦ rank P` of a finitely generated projective module over a ring over which
these are free. It is additive on short exact sequences, which split. -/
noncomputable def rank : ProjK0.{u} R →+ ℤ :=
  lift (fun P _ => (Module.finrank R P : ℤ)) fun S hS h₁ h₂ h₃ => by
    have := h₃.2
    have := hfree _ h₁
    have := hfree _ h₃
    have := h₁.1
    have := h₃.1
    let e := (hS.splittingOfProjective.isoBinaryBiproduct ≪≫
      ModuleCat.biprodIsoProd S.X₁ S.X₃).toLinearEquiv
    rw [e.finrank_eq, Module.finrank_prod, Nat.cast_add]

include hfree in
@[simp]
theorem rank_mk (P : ModuleCat.{u} R) (hP : IsFGProjective R P) :
    rank R hfree (mk P hP) = Module.finrank R P :=
  lift_mk _ _ P hP

include hfree in
/-- The class of a finitely generated projective module is `(rank P) • [R]`. -/
theorem mk_eq_finrank_smul (P : ModuleCat.{u} R) (hP : IsFGProjective R P) :
    mk P hP = Module.finrank R P • mk (ModuleCat.of R R) (IsFGProjective.self R) := by
  have := hfree P hP
  have := hP.1
  rw [← mk_pi]
  exact mk_eq_of_iso (Module.finBasis R P).equivFun.toModuleIso _ _

/-- **`K₀` of a ring whose finitely generated projective modules are free**: the rank is an
isomorphism `K₀(R-proj) ≃+ ℤ`. -/
noncomputable def rankEquiv : ProjK0.{u} R ≃+ ℤ where
  toFun := rank R hfree
  invFun n := n • mk (ModuleCat.of R R) (IsFGProjective.self R)
  left_inv x := by
    change rank R hfree x • mk (ModuleCat.of R R) (IsFGProjective.self R) = x
    induction x using induction_on with
    | zero => simp
    | mk P hP => rw [rank_mk, mk_eq_finrank_smul R hfree P hP, natCast_zsmul]
    | neg x hx => rw [map_neg, neg_smul, hx]
    | add x y hx hy => rw [map_add, add_smul, hx, hy]
  right_inv n := by
    rw [map_zsmul, rank_mk, Module.finrank_self, Nat.cast_one, smul_eq_mul, mul_one]
  map_add' := map_add _

@[simp]
theorem rankEquiv_mk (P : ModuleCat.{u} R) (hP : IsFGProjective R P) :
    rankEquiv R hfree (mk P hP) = Module.finrank R P :=
  rank_mk R hfree P hP

theorem rankEquiv_mk_self :
    rankEquiv R hfree (mk (ModuleCat.of R R) (IsFGProjective.self R)) = 1 := by
  rw [rankEquiv_mk, Module.finrank_self, Nat.cast_one]

end ProjK0

namespace DGRing.K0

open DegreeZero

section

variable (R : Type u) [CommRing R] [Nontrivial R] [HasDerivedCategory.{u, u} R]
  (hfree : ∀ M : ModuleCat.{u} R, IsFGProjective R M → Module.Free R M)

/-- **`K₀ ≃ ℤ`** (roadmap 5.6): for a nontrivial commutative ring `R` concentrated in degree
`0` over which finitely generated projective modules are free (a principal ideal domain such as
`ℤ`, or a local ring), `K₀(R) = K₀(D^c(R)) ≃+ ℤ`, the rank of the Euler characteristic of a
perfect complex representing a class. -/
noncomputable def rankEquiv : K0 R ≃+ ℤ :=
  (projK0Equiv R).trans (ProjK0.rankEquiv R hfree)

@[simp]
theorem rankEquiv_self : rankEquiv R hfree (self R) = 1 := by
  rw [rankEquiv, AddEquiv.trans_apply, projK0Equiv_self, ProjK0.rankEquiv_mk_self]

theorem rankEquiv_symm_apply (n : ℤ) : (rankEquiv R hfree).symm n = n • self R := by
  rw [AddEquiv.symm_apply_eq, map_zsmul, rankEquiv_self, smul_eq_mul, mul_one]

end

section PID

variable (R : Type u) [CommRing R] [IsDomain R] [IsPrincipalIdealRing R]
  [HasDerivedCategory.{u, u} R]

/-- `K₀` of a principal ideal domain `R` in degree `0` (e.g. `ℤ`) is `ℤ`, with `[R] ↦ 1`. -/
noncomputable def equivIntOfIsPrincipalIdealRing : K0 R ≃+ ℤ :=
  rankEquiv R fun _ hM => hM.free_of_isPID

@[simp]
theorem equivIntOfIsPrincipalIdealRing_self : equivIntOfIsPrincipalIdealRing R (self R) = 1 :=
  rankEquiv_self R _

end PID

section Local

variable (R : Type u) [CommRing R] [IsLocalRing R] [HasDerivedCategory.{u, u} R]

/-- `K₀` of a local ring `R` in degree `0` is `ℤ`, with `[R] ↦ 1`. -/
noncomputable def equivIntOfIsLocalRing : K0 R ≃+ ℤ :=
  rankEquiv R fun _ hM => hM.free_of_isLocalRing

@[simp]
theorem equivIntOfIsLocalRing_self : equivIntOfIsLocalRing R (self R) = 1 :=
  rankEquiv_self R _

end Local

end DGRing.K0

end DG
