import Mathlib.Algebra.Category.ModuleCat.Biproducts
import Mathlib.Algebra.Homology.ShortComplex.ModuleCat
import Mathlib.Algebra.Module.Projective
import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.RingTheory.Finiteness.Prod
import Mathlib.LinearAlgebra.FreeModule.Basic

/-!
# The Grothendieck group of finitely generated projective modules

Let `R` be a ring. The *Grothendieck group* `K₀(R) = K₀(R-proj)` of the finitely generated
projective (left) `R`-modules is the abelian group generated by symbols `[P]`, one for each
finitely generated projective `R`-module `P`, subject to the relations `[P₂] = [P₁] + [P₃]` for
every short exact sequence `0 ⟶ P₁ ⟶ P₂ ⟶ P₃ ⟶ 0` of finitely generated projective modules
(Weibel, *The K-book*, II.2 and II.7). Since every such sequence splits, this is the group
completion of the monoid of isomorphism classes under `⊕`: the relations are equivalently
`[P ⊕ Q] = [P] + [Q]` (`DG.ProjK0.mk_biprod`), and `[P]` only depends on the isomorphism class of
`P` (`DG.ProjK0.mk_eq_of_iso`). Mathlib has no Grothendieck group of a ring at the pinned
version.

## Main definitions

* `DG.IsFGProjective R`: the property of an object of `ModuleCat R` of being finitely generated
  and projective; `DG.IsFGProjective.of_retract`, `DG.IsFGProjective.of_iso`,
  `DG.IsFGProjective.biprod`, `DG.IsFGProjective.of_isZero`.
* `DG.ProjK0 R`: the Grothendieck group, a quotient of the free abelian group on the full
  subcategory of finitely generated projective modules.
* `DG.ProjK0.mk P hP`: the class `[P]`; `DG.ProjK0.mk_X₂` (the defining relation),
  `DG.ProjK0.lift` (the universal property), `DG.ProjK0.induction_on`.
* `DG.ProjK0.mk_zero`, `DG.ProjK0.mk_eq_of_iso`, `DG.ProjK0.mk_eq_zero_of_isZero`,
  `DG.ProjK0.mk_biprod`.

The modules live in `ModuleCat.{v} R` for an arbitrary universe `v`.
-/

namespace DG

open CategoryTheory Limits ZeroObject

universe v u

variable (R : Type u) [Ring R]

/-- The finitely generated projective `R`-modules, as a property of objects of `ModuleCat R`. -/
def IsFGProjective : ObjectProperty (ModuleCat.{v} R) :=
  fun M => Module.Finite R M ∧ Module.Projective R M

namespace IsFGProjective

variable {R}

/-- A retract of a finitely generated projective module is finitely generated projective. -/
theorem of_retract {M N : ModuleCat.{v} R} (i : M ⟶ N) (r : N ⟶ M) (h : i ≫ r = 𝟙 M)
    (hN : IsFGProjective R N) : IsFGProjective R M := by
  obtain ⟨_, _⟩ := hN
  have h' : r.hom.comp i.hom = LinearMap.id := by
    rw [← ModuleCat.hom_comp, h, ModuleCat.hom_id]
  refine ⟨Module.Finite.of_surjective r.hom fun x => ⟨i.hom x, ?_⟩, ?_⟩
  · exact LinearMap.congr_fun h' x
  · exact Module.Projective.of_split i.hom r.hom h'

theorem of_iso {M N : ModuleCat.{v} R} (e : M ≅ N) (hN : IsFGProjective R N) :
    IsFGProjective R M :=
  of_retract e.hom e.inv e.hom_inv_id hN

theorem of_isZero {M : ModuleCat.{v} R} (hM : IsZero M) : IsFGProjective R M := by
  have : Subsingleton M := ModuleCat.subsingleton_of_isZero hM
  exact ⟨Module.Finite.of_surjective (0 : (Fin 0 → R) →ₗ[R] M)
    fun x => ⟨0, Subsingleton.elim _ _⟩, Module.Projective.of_free⟩

theorem biprod {M N : ModuleCat.{v} R} (hM : IsFGProjective R M) (hN : IsFGProjective R N) :
    IsFGProjective R (M ⊞ N) := by
  obtain ⟨_, _⟩ := hM
  obtain ⟨_, _⟩ := hN
  exact of_iso (ModuleCat.biprodIsoProd M N) ⟨inferInstance, inferInstance⟩

end IsFGProjective

namespace ProjK0

/-- The subgroup of the free abelian group on the finitely generated projective modules generated
by `of P₂ - of P₁ - of P₃` for the short exact sequences `0 ⟶ P₁ ⟶ P₂ ⟶ P₃ ⟶ 0` of finitely
generated projective modules. -/
def relations : AddSubgroup (FreeAbelianGroup (IsFGProjective.{v} R).FullSubcategory) :=
  AddSubgroup.closure {x | ∃ (S : ShortComplex (ModuleCat.{v} R)) (h₁ : IsFGProjective R S.X₁)
    (h₂ : IsFGProjective R S.X₂) (h₃ : IsFGProjective R S.X₃), S.ShortExact ∧
      x = FreeAbelianGroup.of ⟨S.X₂, h₂⟩ - FreeAbelianGroup.of ⟨S.X₁, h₁⟩ -
        FreeAbelianGroup.of ⟨S.X₃, h₃⟩}

end ProjK0

/-- The Grothendieck group `K₀(R) = K₀(R-proj)` of the finitely generated projective modules over
a ring `R`: the free abelian group on the finitely generated projective modules modulo the
relations `[P₂] = [P₁] + [P₃]` for the short exact sequences `0 ⟶ P₁ ⟶ P₂ ⟶ P₃ ⟶ 0`
(Weibel, *The K-book*, II.7). The class of `P` is `DG.ProjK0.mk P hP`. -/
def ProjK0 : Type _ := FreeAbelianGroup (IsFGProjective.{v} R).FullSubcategory ⧸
  ProjK0.relations.{v} R

namespace ProjK0

instance : AddCommGroup (ProjK0.{v} R) := QuotientAddGroup.Quotient.addCommGroup _

/-- The quotient map from the free abelian group. -/
def mkHom : FreeAbelianGroup (IsFGProjective.{v} R).FullSubcategory →+ ProjK0.{v} R :=
  QuotientAddGroup.mk' _

variable {R}

/-- The class `[P] ∈ K₀(R)` of a finitely generated projective module `P`. -/
def mk (P : ModuleCat.{v} R) (hP : IsFGProjective R P) : ProjK0.{v} R :=
  mkHom R (FreeAbelianGroup.of ⟨P, hP⟩)

theorem mkHom_surjective : Function.Surjective (mkHom.{v} R) :=
  QuotientAddGroup.mk'_surjective _

/-- The defining relation: `[P₂] = [P₁] + [P₃]` for a short exact sequence of finitely generated
projective modules. -/
theorem mk_X₂ {S : ShortComplex (ModuleCat.{v} R)} (hS : S.ShortExact)
    (h₁ : IsFGProjective R S.X₁) (h₂ : IsFGProjective R S.X₂) (h₃ : IsFGProjective R S.X₃) :
    mk S.X₂ h₂ = mk S.X₁ h₁ + mk S.X₃ h₃ := by
  have h := (QuotientAddGroup.eq_zero_iff _).2
    (AddSubgroup.subset_closure ⟨S, h₁, h₂, h₃, hS, rfl⟩ : _ ∈ relations.{v} R)
  change mkHom R _ = 0 at h
  rwa [map_sub, map_sub, sub_sub, sub_eq_zero] at h

/-- Induction principle for `K₀(R)`: every element is obtained from the classes of finitely
generated projective modules by sums and negatives. -/
theorem induction_on {p : ProjK0.{v} R → Prop} (x : ProjK0.{v} R) (zero : p 0)
    (mk : ∀ (P : ModuleCat.{v} R) (hP : IsFGProjective R P), p (mk P hP))
    (neg : ∀ x, p x → p (-x)) (add : ∀ x y, p x → p y → p (x + y)) : p x := by
  obtain ⟨y, rfl⟩ := mkHom_surjective x
  induction y using FreeAbelianGroup.induction_on with
  | zero => simpa using zero
  | of P => exact mk P.obj P.property
  | neg y hy => rw [map_neg]; exact neg _ hy
  | add y z hy hz => rw [map_add]; exact add _ _ hy hz

section lift

variable {G : Type*} [AddCommGroup G]

/-- Two homomorphisms out of `K₀(R)` which agree on the classes of modules are equal. -/
@[ext]
theorem addMonoidHom_ext ⦃f g : ProjK0.{v} R →+ G⦄
    (h : ∀ (P : ModuleCat.{v} R) (hP : IsFGProjective R P), f (mk P hP) = g (mk P hP)) :
    f = g := by
  apply QuotientAddGroup.addMonoidHom_ext
  exact FreeAbelianGroup.lift_ext _ _ fun P => h P.obj P.property

/-- The universal property of `K₀(R)`: a function on finitely generated projective modules with
values in an abelian group, additive on short exact sequences, induces a homomorphism
`ProjK0 R →+ G`. -/
def lift (f : ∀ P : ModuleCat.{v} R, IsFGProjective R P → G)
    (hf : ∀ (S : ShortComplex (ModuleCat.{v} R)), S.ShortExact → ∀ (h₁ : IsFGProjective R S.X₁)
      (h₂ : IsFGProjective R S.X₂) (h₃ : IsFGProjective R S.X₃),
        f S.X₂ h₂ = f S.X₁ h₁ + f S.X₃ h₃) :
    ProjK0.{v} R →+ G :=
  QuotientAddGroup.lift _ (FreeAbelianGroup.lift fun P => f P.obj P.property) (by
    refine (AddSubgroup.closure_le _).2 ?_
    rintro x ⟨S, h₁, h₂, h₃, hS, rfl⟩
    simp only [SetLike.mem_coe, AddMonoidHom.mem_ker, map_sub, FreeAbelianGroup.lift_apply_of]
    rw [hf S hS h₁ h₂ h₃]
    abel)

@[simp]
theorem lift_mk (f : ∀ P : ModuleCat.{v} R, IsFGProjective R P → G) (hf)
    (P : ModuleCat.{v} R) (hP : IsFGProjective R P) : lift f hf (mk P hP) = f P hP :=
  (QuotientAddGroup.lift_mk' (relations.{v} R) _ (FreeAbelianGroup.of _)).trans
    (FreeAbelianGroup.lift_apply_of _ _)

end lift

/-! ### Basic relations -/

/-- The class of the zero module is `0`. -/
theorem mk_zero : mk (0 : ModuleCat.{v} R) (IsFGProjective.of_isZero (isZero_zero _)) = 0 := by
  have h := mk_X₂ ((ShortComplex.Splitting.ofIsZeroOfIsIso
    (ShortComplex.mk (0 : (0 : ModuleCat.{v} R) ⟶ 0) (𝟙 0) (by simp)) (isZero_zero _)
    (by dsimp; infer_instance)).shortExact) (IsFGProjective.of_isZero (isZero_zero _))
    (IsFGProjective.of_isZero (isZero_zero _)) (IsFGProjective.of_isZero (isZero_zero _))
  exact right_eq_add.1 h

/-- Isomorphic modules have the same class. -/
theorem mk_eq_of_iso {P Q : ModuleCat.{v} R} (e : P ≅ Q) (hP : IsFGProjective R P)
    (hQ : IsFGProjective R Q) : mk P hP = mk Q hQ := by
  have h := mk_X₂ ((ShortComplex.Splitting.ofIsZeroOfIsIso
    (ShortComplex.mk (0 : (0 : ModuleCat.{v} R) ⟶ P) e.hom (by simp)) (isZero_zero _)
    (by dsimp; infer_instance)).shortExact) (IsFGProjective.of_isZero (isZero_zero _)) hP hQ
  dsimp at h
  rw [h, mk_zero, zero_add]

theorem mk_eq_zero_of_isZero {P : ModuleCat.{v} R} (hP : IsZero P) (h : IsFGProjective R P) :
    mk P h = 0 := by
  rw [mk_eq_of_iso hP.isoZero h (IsFGProjective.of_isZero (isZero_zero _)), mk_zero]

/-- `[P ⊕ Q] = [P] + [Q]`. -/
theorem mk_biprod {P Q : ModuleCat.{v} R} (hP : IsFGProjective R P) (hQ : IsFGProjective R Q) :
    mk (P ⊞ Q) (hP.biprod hQ) = mk P hP + mk Q hQ :=
  mk_X₂ (ShortComplex.Splitting.ofHasBinaryBiproduct P Q).shortExact hP (hP.biprod hQ) hQ

end ProjK0

end DG
