import DG.Category.Derived.ShiftedObjects
import DG.K0.PositiveCategoryBasis

/-!
# Cells and `K₀` under formal shifts of objects

Let `C` be a dg category. Objects of `C` related by a closed invertible morphism of degree `n`
have representable modules which differ by the shift `⟦n⟧`, and the same holds for their corners:
if `a : Y ⟶ X` is a cocycle of degree `n` with a left inverse `b` (`b ≫ a = 𝟙 X`), `e` is a
degree-`0` idempotent cocycle of `X` and `f = a ≫ e ≫ b` the corresponding idempotent of `Y`, then
`f · C(Y, -)` is generated by `a ≫ e`, of degree `n`, as a corner module of `e`
(`DG.CatModule.isCornerGenerator_corner_of_comp_eq`), so `f · C(Y, -) ≅ (e · C(X, -))⟦-n⟧`
(`DG.CatModule.cellModuleIsoOfCompEq`) and `[f · C(Y, -)] = (-1)ⁿ [e · C(X, -)]` in `K₀(C)`
(`DG.DGCategory.K0.cell_eq_of_comp_eq`).

This is applied to the dg categories of formal shifts `DG.ShiftedObjects`. Let
`φ : ι → C × ℤ`, `φ i = (Xᵢ, mᵢ)`, be a family whose first components exhaust the objects of `C`,
such that the dg category `ShiftedObjects φ` of the formal shifts `Xᵢ[mᵢ]` is positive
(`DG.DGCategory.IsPositive`). Then `K₀(C)` is generated by the classes `[e · C(Xᵢ, -)]` of the
simple idempotents `e` of `ShiftedObjects φ`
(`DG.ShiftedObjects.closure_cell_eq_top_of_isPositive`): both `ShiftedObjects φ` and `C` embed
in the closure of `C` under formal shifts by quasi-fully faithful shift-dense dg functors, which
induce isomorphisms on `K₀`, and `K₀` of a positive dg category is generated by the classes of
its simple cells (Schnürer's theorem).

## Main definitions and results

* `DG.CatModule.IsCornerGenerator.isoOfCornerGen`: two dg modules with corner generators of the
  same degree for the same idempotent are isomorphic.
* `DG.CatModule.isCornerGenerator_corner_of_comp_eq`, `DG.CatModule.cellModuleIsoOfCompEq`,
  `DG.DGCategory.K0.cell_eq_of_comp_eq`.
* `DG.ShiftedObjects.toClosureOfFamily φ : ShiftedObjects φ ⥤ ShiftedObjects id`, quasi-fully
  faithful, and shift-dense when the `Xᵢ` exhaust the objects of `C`.
* `DG.ShiftedObjects.idempotentVal`, `DG.ShiftedObjects.idempotentMk`: degree-`0` idempotent
  cocycles of the object `i` of `ShiftedObjects φ` are those of `Xᵢ`.
* `DG.ShiftedObjects.closure_cell_eq_top_of_isPositive`.
-/

open CategoryTheory Limits

universe w v u

noncomputable section

namespace DG

open DGCategory

namespace CatModule

variable {C : Type u} [Category.{v} C] [Preadditive C] [∀ X Y : C, DGAddCommGroup (X ⟶ Y)]

/-! ### Dg modules with a corner generator -/

namespace IsCornerGenerator

variable {R R' N : CatModule.{w} C} {X : C} {e : Idempotent X} {k : ℤ} {g : R.obj X}
  {g' : R'.obj X} (hg : IsCornerGenerator R e k g)
include hg

theorem of_eq {k' : ℤ} (h : k = k') : IsCornerGenerator R e k' g :=
  h ▸ hg

/-- A morphism out of a dg module with a corner generator `g` is determined by the image of
`g`. -/
theorem hom_ext_gen {f f' : R ⟶ N} (h : f.app X g = f'.app X g) : f = f' :=
  hom_ext fun Y r => congrArg (fun z : Cochain R N 0 => z.app Y r)
    (hg.ext_gen (z := Cochain.ofHom f) (z' := Cochain.ofHom f') h)

/-- The morphism out of a dg module `R` with a corner generator `g` of degree `k` attached to a
cocycle `y` of degree `k`; it sends `g` to `e • y`
(`DG.CatModule.IsCornerGenerator.homOfElement_app_gen`). -/
def homOfElement [DGCategory C] (y : N.obj X) (hy : y ∈ grading k) (hdy : d y = 0) : R ⟶ N :=
  Cocycle.homOf (Cocycle.mk (hg.ofElement (n := 0) y (by rwa [add_zero])) 1 (zero_add 1) (by
    rw [hg.δ_ofElement (zero_add 1) y _ (by rw [hdy]; exact zero_mem _),
      hg.ofElement_congr hdy _ (zero_mem _)]
    exact hg.ofElement_zero))

theorem homOfElement_app_gen [DGCategory C] (y : N.obj X) (hy : y ∈ grading k) (hdy : d y = 0)
    (hey : e.val • y = y) : (hg.homOfElement y hy hdy).app X g = y := by
  change (hg.ofElement (n := 0) y (by rwa [add_zero])).app X g = y
  rw [ofElement_gen, hey]

/-- Two dg modules with corner generators of the same degree for the same idempotent `e` are
isomorphic, by the morphisms exchanging the generators: both are `(e · C(X, -))⟦-k⟧`. -/
def isoOfCornerGen [DGCategory C] (hg' : IsCornerGenerator R' e k g') : R ≅ R' where
  hom := hg.homOfElement g' hg'.mem_grading hg'.d_eq_zero
  inv := hg'.homOfElement g hg.mem_grading hg.d_eq_zero
  hom_inv_id := hg.hom_ext_gen (by
    rw [comp_app, hg.homOfElement_app_gen _ _ _ hg'.val_smul,
      hg'.homOfElement_app_gen _ _ _ hg.val_smul, id_app])
  inv_hom_id := hg'.hom_ext_gen (by
    rw [comp_app, hg'.homOfElement_app_gen _ _ _ hg.val_smul,
      hg.homOfElement_app_gen _ _ _ hg'.val_smul, id_app])

end IsCornerGenerator

/-! ### Corners of objects related by a closed invertible morphism -/

section CompEq

variable [DGCategory C] {X Y : C} {n : ℤ} {a : Y ⟶ X} {b : X ⟶ Y}

/-- If `a : Y ⟶ X` is a cocycle of degree `n` with `b ≫ a = 𝟙 X`, `e` is a degree-`0` idempotent
cocycle of `X` and `f` one of `Y` with `f = a ≫ e ≫ b`, then the corner `f · C(Y, -)` is
generated by `a ≫ e ∈ f · C(Y, X)`, of degree `n`, as a corner module of `e`: it is
`(e · C(X, -))⟦-n⟧`. -/
theorem isCornerGenerator_corner_of_comp_eq (ha : a ∈ cocycles (Y ⟶ X) n) (hba : b ≫ a = 𝟙 X)
    (e : Idempotent X) (f : Idempotent Y) (hf : f.val = a ≫ e.val ≫ b) :
    IsCornerGenerator (corner f) e n
      (⟨a ≫ e.val, by
        change f.val ≫ a ≫ e.val = a ≫ e.val
        rw [hf, Category.assoc, Category.assoc, reassoc_of% hba, e.comp_self]⟩ :
        (corner f).obj X) where
  mem_grading := by
    have h := comp_mem_grading ha.1 e.mem_grading
    rw [add_zero] at h
    exact h
  d_eq_zero := Subtype.ext (by
    change d (a ≫ e.val) = 0
    rw [d_comp_of_d_eq_zero_left ha.2, e.d_val, comp_zero])
  val_smul := Subtype.ext (by
    change (a ≫ e.val) ≫ e.val = a ≫ e.val
    rw [Category.assoc, e.comp_self])
  surjective Z h := ⟨b ≫ h.1, Subtype.ext (by
    change (a ≫ e.val) ≫ b ≫ h.1 = h.1
    have h' : f.val ≫ h.1 = h.1 := h.2
    change (f.val ≫ h.1 : Y ⟶ Z) = h.1 at h'
    rw [hf] at h'
    change (a ≫ e.val) ≫ b ≫ h.1 = h.1
    exact (Category.assoc a e.val (b ≫ h.1)).trans
      ((congrArg (a ≫ ·) (Category.assoc e.val b h.1).symm).trans
        ((Category.assoc a (e.val ≫ b) h.1).symm.trans h')))⟩
  val_comp_eq_zero {Z} c hc := by
    have h : (a ≫ e.val) ≫ c = 0 := congrArg Subtype.val hc
    calc e.val ≫ c = (b ≫ a) ≫ e.val ≫ c := by rw [hba, Category.id_comp]
      _ = b ≫ (a ≫ e.val) ≫ c := by simp only [Category.assoc]
      _ = 0 := by rw [h, comp_zero]

/-- For `a : Y ⟶ X` a cocycle of degree `n` with `b ≫ a = 𝟙 X` and idempotents `e` of `X`,
`f = a ≫ e ≫ b` of `Y`: the isomorphism `f · C(Y, -) ≅ (e · C(X, -))⟦-n⟧` of cell modules. -/
def cellModuleIsoOfCompEq (ha : a ∈ cocycles (Y ⟶ X) n) (hba : b ≫ a = 𝟙 X)
    (e : Idempotent X) (f : Idempotent Y) (hf : f.val = a ≫ e.val ≫ b) :
    cellModule.{w} f 0 ≅ cellModule.{w} e (-n) :=
  ((((isCornerGenerator_corner_of_comp_eq ha hba e f hf).ulift.{w}).shift 0).of_eq
    (sub_zero n)).isoOfCornerGen
      ((isCornerGenerator_cellModule.{w} e (-n)).of_eq (by rw [zero_sub, neg_neg]))

end CompEq

end CatModule

namespace DGCategory.K0

variable {C : Type u} [Category.{v} C] [Preadditive C] [∀ X Y : C, DGAddCommGroup (X ⟶ Y)]
  [DGCategory C] [CatModule.HasDerivedCategory.{max u v w, max u v w} C]

/-- For `a : Y ⟶ X` a cocycle of degree `n` with `b ≫ a = 𝟙 X` and idempotents `e` of `X`,
`f = a ≫ e ≫ b` of `Y`: `[f · C(Y, -)] = (-1)ⁿ [e · C(X, -)]` in `K₀(C)`. -/
theorem cell_eq_of_comp_eq {X Y : C} {n : ℤ} {a : Y ⟶ X} {b : X ⟶ Y}
    (ha : a ∈ cocycles (Y ⟶ X) n) (hba : b ≫ a = 𝟙 X) (e : Idempotent X) (f : Idempotent Y)
    (hf : f.val = a ≫ e.val ≫ b) : cell.{w} f 0 = (-n).negOnePow • cell.{w} e 0 := by
  rw [← cell_eq]
  exact DG.K0.mk_eq_of_iso_obj (CatModule.DerivedCategory.Q.mapIso
    (CatModule.cellModuleIsoOfCompEq.{max u w} ha hba e f hf))

end DGCategory.K0

/-! ### Formal shifts of objects -/

namespace ShiftedObjects

variable {C : Type u} [Category.{v} C] [Preadditive C] [∀ X Y : C, DGAddCommGroup (X ⟶ Y)]
  {ι : Type u} (φ : ι → C × ℤ)

/-- The dg functor `ShiftedObjects φ ⥤ ShiftedObjects id`, `i ↦ φ i`, from the formal shifts
`Xᵢ[mᵢ]` of a family to the closure of `C` under formal shifts, the identity on Hom complexes. -/
@[simps obj]
def toClosureOfFamily : ShiftedObjects φ ⥤ ShiftedObjects (id : C × ℤ → C × ℤ) where
  obj i := ⟨φ i.as⟩
  map f := homMk (homVal f)
  map_id _ := rfl
  map_comp _ _ := rfl

omit [Preadditive C] [∀ X Y : C, DGAddCommGroup (X ⟶ Y)] in
@[simp]
theorem homVal_toClosureOfFamily_map {i j : ShiftedObjects φ} (f : i ⟶ j) :
    homVal ((toClosureOfFamily φ).map f) = homVal f :=
  rfl

instance : (toClosureOfFamily φ).Additive where

instance : (toClosureOfFamily φ).IsDGFunctor where
  map_mem' hf := hf
  map_d' _ := rfl

/-- `ShiftedObjects φ ⥤ ShiftedObjects id` is quasi-fully faithful: it is the identity on Hom
complexes. -/
theorem isQuasiFullyFaithful_toClosureOfFamily :
    IsQuasiFullyFaithful (toClosureOfFamily φ) :=
  IsQuasiFullyFaithful.of_bijective _ (fun _ _ => Function.bijective_id) fun h => h

/-- If the first components of the family `φ` exhaust the objects of `C`, then
`ShiftedObjects φ ⥤ ShiftedObjects id` is shift-dense: `(Xᵢ, m)` and `(Xᵢ, mᵢ)` are related by
the identity of `Xᵢ`. -/
theorem isShiftDense_toClosureOfFamily [DGCategory C] (hφ : ∀ Y : C, ∃ i, (φ i).1 = Y) :
    IsShiftDense (toClosureOfFamily φ) := by
  rintro ⟨Y, m⟩
  obtain ⟨i, rfl⟩ := hφ Y
  refine ⟨⟨i⟩, m - (φ i).2,
    shiftHom (i := ⟨((φ i).1, m)⟩) (j := (toClosureOfFamily φ).obj ⟨i⟩) rfl,
    shiftHom (i := (toClosureOfFamily φ).obj ⟨i⟩) (j := ⟨((φ i).1, m)⟩) rfl, ?_, ?_, ?_⟩
  · exact shiftHom_mem_cocycles (φ := id) (i := ⟨((φ i).1, m)⟩)
      (j := (toClosureOfFamily φ).obj ⟨i⟩) rfl
  · rw [neg_sub]
    exact shiftHom_mem_cocycles (φ := id) (i := (toClosureOfFamily φ).obj ⟨i⟩)
      (j := ⟨((φ i).1, m)⟩) rfl
  · change shiftHom (φ := id) (i := ⟨((φ i).1, m)⟩) (j := ⟨φ i⟩) rfl ≫
      shiftHom (φ := id) (i := ⟨φ i⟩) (j := ⟨((φ i).1, m)⟩) rfl = _
    exact (shiftHom_comp_shiftHom _ _).trans (shiftHom_self _)

variable {φ}

/-- A degree-`0` idempotent cocycle of the object `i` of `ShiftedObjects φ`, as a degree-`0`
idempotent cocycle of the underlying object `Xᵢ` of `C`. -/
def idempotentVal {i : ShiftedObjects φ} (e : Idempotent i) : Idempotent (φ i.as).1 where
  val := homVal e.val
  mem_cocycles := by
    refine mem_cocycles.mpr ⟨?_, ?_⟩
    · have h := mem_grading_iff.mp e.mem_grading
      rwa [sub_self, add_zero] at h
    · have h : koszulSign (φ i.as).2 • d (homVal e.val) = 0 :=
        (homVal_d e.val).symm.trans (congrArg homVal e.d_val)
      exact (smul_eq_zero_iff_eq _).mp h
  comp_self := congrArg homVal e.comp_self

@[simp]
theorem idempotentVal_val {i : ShiftedObjects φ} (e : Idempotent i) :
    (idempotentVal e).val = homVal e.val :=
  rfl

/-- A degree-`0` idempotent cocycle of `Xᵢ`, as a degree-`0` idempotent cocycle of the object `i`
of `ShiftedObjects φ`. -/
def idempotentMk {i : ShiftedObjects φ} (e : Idempotent (φ i.as).1) : Idempotent i where
  val := homMk e.val
  mem_cocycles := by
    refine mem_cocycles.mpr ⟨mem_grading_iff.mpr ?_, hom_ext ?_⟩
    · rw [sub_self, add_zero]
      exact e.mem_grading
    · rw [homVal_d]
      exact (congrArg _ e.d_val).trans (smul_zero _)
  comp_self := hom_ext e.comp_self

@[simp]
theorem homVal_idempotentMk_val {i : ShiftedObjects φ} (e : Idempotent (φ i.as).1) :
    homVal (idempotentMk e).val = e.val :=
  rfl

@[simp]
theorem idempotentVal_idempotentMk {i : ShiftedObjects φ} (e : Idempotent (φ i.as).1) :
    idempotentVal (idempotentMk e) = e :=
  rfl

variable [DGCategory C] [CatModule.HasDerivedCategory.{max u v w, max u v w} C]

variable (φ) in
/-- **`K₀` of a dg category which is positive up to formal shifts of its objects.** Let
`φ i = (Xᵢ, mᵢ)` be a family whose first components exhaust the objects of `C`, such that the dg
category `ShiftedObjects φ` of the formal shifts `Xᵢ[mᵢ]` is positive. Then `K₀(C)` is generated
by the classes `[e · C(Xᵢ, -)]`, for the simple degree-`0` idempotents `e` of the objects of
`ShiftedObjects φ` (which are degree-`0` idempotent cocycles of the `Xᵢ`). -/
theorem closure_cell_eq_top_of_isPositive (hφ : ∀ Y : C, ∃ i, (φ i).1 = Y)
    (hP : DGCategory.IsPositive (ShiftedObjects φ)) :
    AddSubgroup.closure (Set.range fun c : SimpleCorner (ShiftedObjects φ) =>
      DGCategory.K0.cell.{max v w} (idempotentVal c.1.2) 0) = ⊤ := by
  let := CatModule.HasDerivedCategory.small.{w} (ShiftedObjects φ)
  let := CatModule.HasDerivedCategory.small.{w} (ShiftedObjects (id : C × ℤ → C × ℤ))
  let E₁ := DGCategory.K0.mapEquivOfIsShiftDense.{max u v w, w}
    (isQuasiFullyFaithful_toClosureOfFamily φ) (isShiftDense_toClosureOfFamily φ hφ)
  let E₂ := DGCategory.K0.mapEquivOfIsShiftDense.{max u v w, w}
    (isQuasiFullyFaithful_toClosure (C := C)) isShiftDense_toClosure
  set S := AddSubgroup.closure (Set.range fun c : SimpleCorner (ShiftedObjects φ) =>
    DGCategory.K0.cell.{max v w} (idempotentVal c.1.2) 0)
  have key : ∀ c : SimpleCorner (ShiftedObjects φ),
      E₂.symm (E₁ (DGCategory.K0.cell.{max v w} c.1.2 0)) ∈ S := by
    intro c
    have h1 : E₁ (DGCategory.K0.cell.{max v w} c.1.2 0) =
        DGCategory.K0.cell.{max v w} (c.1.2.map (toClosureOfFamily φ)) 0 :=
      DGCategory.K0.map_cell.{w} (toClosureOfFamily φ) c.1.2
    have h2 : E₂ (DGCategory.K0.cell.{max v w} (idempotentVal c.1.2) 0) =
        DGCategory.K0.cell.{max v w} ((idempotentVal c.1.2).map (toClosure C)) 0 :=
      DGCategory.K0.map_cell.{w} (toClosure C) (idempotentVal c.1.2)
    have h3 := DGCategory.K0.cell_eq_of_comp_eq.{max v w}
      (shiftHom_mem_cocycles (φ := id) (i := (toClosureOfFamily φ).obj c.1.1)
        (j := (toClosure C).obj (φ c.1.1.as).1) rfl)
      (b := shiftHom (i := (toClosure C).obj (φ c.1.1.as).1)
        (j := (toClosureOfFamily φ).obj c.1.1) rfl)
      ((shiftHom_comp_shiftHom _ _).trans (shiftHom_self _))
      ((idempotentVal c.1.2).map (toClosure C)) (c.1.2.map (toClosureOfFamily φ))
      (hom_ext (by
        change homVal c.1.2.val = 𝟙 _ ≫ homVal c.1.2.val ≫ 𝟙 _
        rw [Category.comp_id, Category.id_comp]))
    rw [h1, h3, ← h2, Units.smul_def, map_zsmul, AddEquiv.symm_apply_apply]
    exact S.zsmul_mem (AddSubgroup.subset_closure ⟨c, rfl⟩) _
  refine eq_top_iff.mpr fun x _ => ?_
  obtain ⟨y, hy⟩ := E₁.surjective (E₂ x)
  have hx : x = (E₂.symm.toAddMonoidHom.comp E₁.toAddMonoidHom) y := by
    change x = E₂.symm (E₁ y)
    rw [hy, AddEquiv.symm_apply_apply]
  rw [hx]
  have hy' : y ∈ AddSubgroup.closure (Set.range fun c : SimpleCorner (ShiftedObjects φ) =>
      DGCategory.K0.cell.{max v w} c.1.2 0) := by
    rw [hP.closure_cell_eq_top.{max v w}]
    trivial
  refine (AddSubgroup.closure_le (K := S.comap (E₂.symm.toAddMonoidHom.comp E₁.toAddMonoidHom))
    |>.mpr ?_) hy'
  rintro _ ⟨c, rfl⟩
  exact key c

end ShiftedObjects

end DG

end
