import Mathlib.Algebra.BigOperators.Fin
import Mathlib.CategoryTheory.Triangulated.Adjunction
import Mathlib.GroupTheory.FreeAbelianGroup

/-!
# The Grothendieck group of a pretriangulated category

Let `C` be a pretriangulated category in the sense of Mathlib (`CategoryTheory.Pretriangulated`):
a preadditive category with a zero object, an additive shift `⟦n⟧` indexed by `ℤ`, and a class of
distinguished triangles `X ⟶ Y ⟶ Z ⟶ X⟦1⟧` satisfying the axioms TR1–TR3 of Verdier. The
*Grothendieck group* `K₀(C)` is the abelian group generated by symbols `[X]`, one for each object
`X` of `C`, subject to the relations `[Y] = [X] + [Z]` for every distinguished triangle
`X ⟶ Y ⟶ Z ⟶ X⟦1⟧` (see [Ve], J.-L. Verdier, *Des catégories dérivées des catégories
abéliennes*, Astérisque 239, Chapitre II, §1). Since every isomorphism `X ≅ Y` fits into a
distinguished triangle `X ⟶ Y ⟶ 0 ⟶ X⟦1⟧`, the class `[X]` depends only on the isomorphism
class of `X`, so this is the usual free abelian group on isomorphism classes modulo the triangle
relations, without any smallness hypothesis: `DG.K0 C` lives in the universe of the objects of
`C`.

## Main definitions

* `DG.K0 C`: the Grothendieck group, defined as the quotient of `FreeAbelianGroup C` by the
  subgroup `DG.K0.relations C` generated by `of Y - of X - of Z` for the distinguished triangles
  `X ⟶ Y ⟶ Z ⟶ X⟦1⟧`.
* `DG.K0.mk X`: the class `[X]` of an object.
* `DG.K0.lift`: the universal property, producing a homomorphism `K0 C →+ G` from a function
  `C → G` satisfying the triangle relation; `DG.K0.addMonoidHom_ext` is the corresponding
  extensionality lemma and `DG.K0.induction_on` the induction principle.
* `DG.K0.map F`: the homomorphism `K0 C →+ K0 D` induced by a triangulated functor `F : C ⥤ D`
  (`[F.CommShift ℤ] [F.IsTriangulated]`), with `DG.K0.map_id` and `DG.K0.map_comp`.
* `DG.K0.mapEquiv e`: the isomorphism `K0 C ≃+ K0 D` induced by an equivalence `e : C ≌ D`
  whose two functors are triangulated.

## Main results

* `DG.K0.mk_obj₂`: `[T.obj₂] = [T.obj₁] + [T.obj₃]` for a distinguished triangle `T`.
* `DG.K0.mk_zero`, `DG.K0.mk_eq_zero_of_isZero`: the class of a zero object is `0`.
* `DG.K0.mk_eq_of_iso`: isomorphic objects have the same class.
* `DG.K0.mk_shift_one`, `DG.K0.mk_shift`: `[X⟦1⟧] = -[X]` and `[X⟦n⟧] = (-1)^n • [X]`, the sign
  being `Int.negOnePow n : ℤˣ`.
* `DG.K0.mk_biprod`: `[X ⊞ Y] = [X] + [Y]`.
* `DG.K0.mk_last_eq_add_sum`: additivity over iterated cones: if `X₀ ⟶ X₁ ⟶ ⋯ ⟶ Xₙ` and each
  `Xᵢ ⟶ Xᵢ₊₁ ⟶ Qᵢ ⟶ Xᵢ⟦1⟧` is distinguished, then `[Xₙ] = [X₀] + ∑ᵢ [Qᵢ]`.
* `DG.K0.map_eq_of_iso`: naturally isomorphic triangulated functors induce the same map.

## Conventions

Signs are units of `ℤ`, as everywhere in this library: `n.negOnePow • x` denotes the action of
`Int.negOnePow n : ℤˣ` on the abelian group `K0 C`, so `n.negOnePow • x = x` for `n` even and
`-x` for `n` odd (`DG.K0.mk_shift_even`, `DG.K0.mk_shift_odd`).
-/

namespace DG

open CategoryTheory Category Limits Pretriangulated ZeroObject

universe v u

variable (C : Type u) [Category.{v} C] [HasZeroObject C] [HasShift C ℤ] [Preadditive C]
  [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]

namespace K0

/-- The subgroup of the free abelian group on the objects of `C` generated by the elements
`of T.obj₂ - of T.obj₁ - of T.obj₃`, for `T` running through the distinguished triangles of `C`.
The Grothendieck group `DG.K0 C` is the quotient by this subgroup. -/
def relations : AddSubgroup (FreeAbelianGroup C) :=
  AddSubgroup.closure {x | ∃ T ∈ distTriang C,
    x = FreeAbelianGroup.of T.obj₂ - FreeAbelianGroup.of T.obj₁ - FreeAbelianGroup.of T.obj₃}

end K0

/-- The Grothendieck group `K₀(C)` of a pretriangulated category `C`: the free abelian group on
the objects of `C` modulo the relations `[T.obj₂] = [T.obj₁] + [T.obj₃]` for every distinguished
triangle `T` ([Ve, II.1]). The class of an object `X` is `DG.K0.mk X`. -/
def K0 : Type u := FreeAbelianGroup C ⧸ K0.relations C

namespace K0

instance : AddCommGroup (K0 C) := QuotientAddGroup.Quotient.addCommGroup _

/-- The quotient map from the free abelian group on the objects of `C` to `K₀(C)`. -/
def mkHom : FreeAbelianGroup C →+ K0 C := QuotientAddGroup.mk' _

variable {C}

/-- The class `[X] ∈ K₀(C)` of an object `X` of `C`. -/
def mk (X : C) : K0 C := mkHom C (FreeAbelianGroup.of X)

theorem mkHom_of (X : C) : mkHom C (FreeAbelianGroup.of X) = mk X := rfl

theorem mkHom_surjective : Function.Surjective (mkHom C) := QuotientAddGroup.mk'_surjective _

theorem relation_mem (T : Triangle C) (hT : T ∈ distTriang C) :
    FreeAbelianGroup.of T.obj₂ - FreeAbelianGroup.of T.obj₁ - FreeAbelianGroup.of T.obj₃ ∈
      relations C :=
  AddSubgroup.subset_closure ⟨T, hT, rfl⟩

/-- The defining relation of `K₀(C)`: `[T.obj₂] = [T.obj₁] + [T.obj₃]` for a distinguished
triangle `T`. -/
theorem mk_obj₂ (T : Triangle C) (hT : T ∈ distTriang C) :
    mk T.obj₂ = mk T.obj₁ + mk T.obj₃ := by
  have h := (QuotientAddGroup.eq_zero_iff _).2 (relation_mem T hT)
  change mkHom C _ = 0 at h
  rwa [map_sub, map_sub, sub_sub, sub_eq_zero] at h

/-- Induction principle for `K₀(C)`: every element is obtained from the classes of objects by
sums and negatives. -/
theorem induction_on {p : K0 C → Prop} (x : K0 C) (zero : p 0) (mk : ∀ X : C, p (mk X))
    (neg : ∀ x, p x → p (-x)) (add : ∀ x y, p x → p y → p (x + y)) : p x := by
  obtain ⟨y, rfl⟩ := mkHom_surjective x
  induction y using FreeAbelianGroup.induction_on with
  | C0 => simpa using zero
  | C1 X => exact mk X
  | Cn y hy => rw [map_neg]; exact neg _ hy
  | Cp y z hy hz => rw [map_add]; exact add _ _ hy hz

section lift

variable {G : Type*} [AddCommGroup G]

/-- Two homomorphisms out of `K₀(C)` which agree on the classes of objects are equal. -/
@[ext]
theorem addMonoidHom_ext ⦃f g : K0 C →+ G⦄ (h : ∀ X : C, f (mk X) = g (mk X)) : f = g := by
  apply QuotientAddGroup.addMonoidHom_ext
  exact FreeAbelianGroup.lift.ext _ _ h

/-- The universal property of `K₀(C)`: a function `f : C → G` to an abelian group which satisfies
`f T.obj₂ = f T.obj₁ + f T.obj₃` for every distinguished triangle `T` induces a homomorphism
`K0 C →+ G` sending `[X]` to `f X`. -/
def lift (f : C → G) (hf : ∀ T ∈ distTriang C, f T.obj₂ = f T.obj₁ + f T.obj₃) :
    K0 C →+ G :=
  QuotientAddGroup.lift _ (FreeAbelianGroup.lift f) (by
    refine (AddSubgroup.closure_le _).2 ?_
    rintro x ⟨T, hT, rfl⟩
    simp only [SetLike.mem_coe, AddMonoidHom.mem_ker, map_sub, FreeAbelianGroup.lift.of, hf T hT]
    abel)

@[simp]
theorem lift_mk (f : C → G) (hf) (X : C) : lift f hf (mk X) = f X :=
  (QuotientAddGroup.lift_mk' (relations C) _ (FreeAbelianGroup.of X)).trans
    (FreeAbelianGroup.lift.of f X)

theorem lift_unique (f : C → G) (hf) (g : K0 C →+ G) (hg : ∀ X, g (mk X) = f X) :
    g = lift f hf := by
  ext X
  simp [hg]

end lift

/-! ### Basic relations -/

theorem mk_obj₁ (T : Triangle C) (hT : T ∈ distTriang C) :
    mk T.obj₁ = mk T.obj₂ - mk T.obj₃ := by
  rw [mk_obj₂ T hT, add_sub_cancel_right]

theorem mk_obj₃ (T : Triangle C) (hT : T ∈ distTriang C) :
    mk T.obj₃ = mk T.obj₂ - mk T.obj₁ := by
  rw [mk_obj₂ T hT, add_sub_cancel_left]

/-- The triangle relation, for a distinguished triangle given by its three morphisms. -/
theorem mk_eq_add_of_distTriang {X Y Z : C} (f : X ⟶ Y) (g : Y ⟶ Z) (h : Z ⟶ X⟦(1 : ℤ)⟧)
    (hT : Triangle.mk f g h ∈ distTriang C) : mk Y = mk X + mk Z :=
  mk_obj₂ _ hT

/-- The class of the zero object is `0`. -/
@[simp]
theorem mk_zero : mk (0 : C) = 0 := by
  have h := mk_obj₂ _ (contractible_distinguished₁ (0 : C))
  dsimp at h
  exact right_eq_add.1 h

/-- Isomorphic objects have the same class in `K₀(C)`. -/
theorem mk_eq_of_iso {X Y : C} (e : X ≅ Y) : mk X = mk Y := by
  have h := mk_obj₂ _ (isomorphic_distinguished _ (contractible_distinguished X) _
    (Triangle.isoMk (Triangle.mk e.hom (0 : Y ⟶ 0) 0) (contractibleTriangle X) (Iso.refl X)
      e.symm (Iso.refl 0) (by simp) (by simp) (by simp)))
  dsimp at h
  rw [h, mk_zero, add_zero]

theorem mk_eq_zero_of_isZero {X : C} (hX : IsZero X) : mk X = 0 := by
  rw [mk_eq_of_iso hX.isoZero, mk_zero]

/-! ### Shifts -/

/-- `[X⟦1⟧] = -[X]`, from the distinguished triangle `X ⟶ 0 ⟶ X⟦1⟧ ⟶ X⟦1⟧`. -/
theorem mk_shift_one (X : C) : mk (X⟦(1 : ℤ)⟧) = -mk X := by
  have h := mk_obj₂ _ (contractible_distinguished₂ X)
  dsimp at h
  rw [mk_zero] at h
  exact eq_neg_of_add_eq_zero_right h.symm

/-- `[X⟦n⟧] = (-1)^n • [X]`, with the sign `Int.negOnePow n : ℤˣ`. -/
theorem mk_shift (n : ℤ) (X : C) : mk (X⟦n⟧) = n.negOnePow • mk X := by
  induction n using Int.induction_on with
  | hz => rw [mk_eq_of_iso ((shiftFunctorZero C ℤ).app X), Functor.id_obj, Int.negOnePow_zero,
      one_smul]
  | hp n hn =>
    rw [mk_eq_of_iso ((shiftFunctorAdd C (n : ℤ) 1).app X), Functor.comp_obj, mk_shift_one, hn,
      Int.negOnePow_succ, Units.smul_def, Units.smul_def, Units.val_neg, neg_smul]
  | hn n hn =>
    rw [mk_eq_of_iso ((shiftFunctorAdd' C (-(n : ℤ) - 1) 1 (-(n : ℤ)) (by omega)).app X),
      Functor.comp_obj, mk_shift_one] at hn
    rw [Int.negOnePow_sub, Int.negOnePow_one, mul_neg, mul_one, Units.smul_def, Units.val_neg,
      neg_smul, ← Units.smul_def, ← hn, neg_neg]

theorem mk_shift_neg_one (X : C) : mk (X⟦(-1 : ℤ)⟧) = -mk X := by
  rw [mk_shift, Int.negOnePow_neg, Int.negOnePow_one, Units.smul_def, Units.val_neg, Units.val_one,
    neg_smul, one_smul]

theorem mk_shift_even {n : ℤ} (hn : Even n) (X : C) : mk (X⟦n⟧) = mk X := by
  rw [mk_shift, Int.negOnePow_even n hn, one_smul]

theorem mk_shift_odd {n : ℤ} (hn : Odd n) (X : C) : mk (X⟦n⟧) = -mk X := by
  rw [mk_shift, Int.negOnePow_odd n hn, Units.smul_def, Units.val_neg, Units.val_one, neg_smul,
    one_smul]

/-! ### Biproducts -/

/-- `[X ⊞ Y] = [X] + [Y]`, from the distinguished triangle `X ⟶ X ⊞ Y ⟶ Y ⟶ X⟦1⟧`. -/
theorem mk_biprod (X Y : C) : mk (X ⊞ Y) = mk X + mk Y :=
  mk_obj₂ _ (binaryBiproductTriangle_distinguished X Y)

theorem mk_prod (X Y : C) : mk (X ⨯ Y) = mk X + mk Y :=
  mk_obj₂ _ (binaryProductTriangle_distinguished X Y)

theorem mk_coprod (X Y : C) : mk (X ⨿ Y) = mk X + mk Y :=
  (mk_eq_of_iso (biprod.isoCoprod X Y).symm).trans (mk_biprod X Y)

/-! ### Iterated cones -/

/-- Additivity of `K₀` over a finite sequence of distinguished triangles: given objects
`X 0, X 1, …, X n` and `Q 0, …, Q (n-1)` and distinguished triangles
`X i ⟶ X (i+1) ⟶ Q i ⟶ (X i)⟦1⟧`, one has `[X n] = [X 0] + ∑ i, [Q i]`. This is the
additivity over a finite filtration whose subquotients are the `Q i`. -/
theorem mk_last_eq_add_sum {n : ℕ} (X : Fin (n + 1) → C) (Q : Fin n → C)
    (h : ∀ i : Fin n, ∃ (f : X i.castSucc ⟶ X i.succ) (g : X i.succ ⟶ Q i)
      (k : Q i ⟶ (X i.castSucc)⟦(1 : ℤ)⟧), Triangle.mk f g k ∈ distTriang C) :
    mk (X (Fin.last n)) = mk (X 0) + ∑ i, mk (Q i) := by
  induction n with
  | zero => simp
  | succ n ih =>
    obtain ⟨f, g, k, hT⟩ := h (Fin.last n)
    have ih' := ih (fun i => X i.castSucc) (fun i => Q i.castSucc) (fun i => h i.castSucc)
    simp only [Fin.castSucc_zero'] at ih'
    rw [Fin.sum_univ_castSucc, ← add_assoc, ← ih', ← Fin.succ_last,
      mk_eq_add_of_distTriang f g k hT]

/-! ### Functoriality -/

section map

variable {D : Type*} [Category D] [HasZeroObject D] [HasShift D ℤ] [Preadditive D]
  [∀ n : ℤ, (shiftFunctor D n).Additive] [Pretriangulated D]
variable {E : Type*} [Category E] [HasZeroObject E] [HasShift E ℤ] [Preadditive E]
  [∀ n : ℤ, (shiftFunctor E n).Additive] [Pretriangulated E]

/-- A triangulated functor `F : C ⥤ D` induces a homomorphism `K₀(C) →+ K₀(D)`, `[X] ↦ [F X]`. -/
def map (F : C ⥤ D) [F.CommShift ℤ] [F.IsTriangulated] : K0 C →+ K0 D :=
  lift (fun X => mk (F.obj X)) (fun T hT => mk_obj₂ _ (F.map_distinguished T hT))

@[simp]
theorem map_mk (F : C ⥤ D) [F.CommShift ℤ] [F.IsTriangulated] (X : C) :
    map F (mk X) = mk (F.obj X) :=
  lift_mk _ _ X

@[simp]
theorem map_id : map (𝟭 C) = AddMonoidHom.id (K0 C) := by
  ext X
  simp

theorem map_comp (F : C ⥤ D) (G : D ⥤ E) [F.CommShift ℤ] [F.IsTriangulated]
    [G.CommShift ℤ] [G.IsTriangulated] : map (F ⋙ G) = (map G).comp (map F) := by
  ext X
  simp

theorem map_comp_apply (F : C ⥤ D) (G : D ⥤ E) [F.CommShift ℤ] [F.IsTriangulated]
    [G.CommShift ℤ] [G.IsTriangulated] (x : K0 C) : map (F ⋙ G) x = map G (map F x) := by
  rw [map_comp, AddMonoidHom.comp_apply]

/-- Naturally isomorphic triangulated functors induce the same map on `K₀`. -/
theorem map_eq_of_iso {F₁ F₂ : C ⥤ D} (e : F₁ ≅ F₂) [F₁.CommShift ℤ] [F₁.IsTriangulated]
    [F₂.CommShift ℤ] [F₂.IsTriangulated] : map F₁ = map F₂ := by
  ext X
  simp only [map_mk]
  exact mk_eq_of_iso (e.app X)

/-- An equivalence of pretriangulated categories induces an isomorphism `K₀(C) ≃+ K₀(D)`.

Both `e.functor` and `e.inverse` are assumed to commute with shifts and to be triangulated;
these instances are provided by Mathlib's `CategoryTheory.Equivalence.IsTriangulated`. -/
def mapEquiv (e : C ≌ D) [e.functor.CommShift ℤ] [e.inverse.CommShift ℤ]
    [e.functor.IsTriangulated] [e.inverse.IsTriangulated] : K0 C ≃+ K0 D where
  toFun := map e.functor
  invFun := map e.inverse
  left_inv x := by
    rw [← AddMonoidHom.comp_apply, ← map_comp, map_eq_of_iso e.unitIso.symm, map_id,
      AddMonoidHom.id_apply]
  right_inv x := by
    rw [← AddMonoidHom.comp_apply, ← map_comp, map_eq_of_iso e.counitIso, map_id,
      AddMonoidHom.id_apply]
  map_add' := map_add _

@[simp]
theorem mapEquiv_apply (e : C ≌ D) [e.functor.CommShift ℤ] [e.inverse.CommShift ℤ]
    [e.functor.IsTriangulated] [e.inverse.IsTriangulated] (x : K0 C) :
    mapEquiv e x = map e.functor x :=
  rfl

@[simp]
theorem mapEquiv_symm_apply (e : C ≌ D) [e.functor.CommShift ℤ] [e.inverse.CommShift ℤ]
    [e.functor.IsTriangulated] [e.inverse.IsTriangulated] (y : K0 D) :
    (mapEquiv e).symm y = map e.inverse y :=
  rfl

theorem mapEquiv_mk (e : C ≌ D) [e.functor.CommShift ℤ] [e.inverse.CommShift ℤ]
    [e.functor.IsTriangulated] [e.inverse.IsTriangulated] (X : C) :
    mapEquiv e (mk X) = mk (e.functor.obj X) :=
  map_mk _ X

end map

end K0

end DG
