import DG.Algebra.AddEquiv

/-!
# Internal direct sums detected by maps of degree zero

This file gives criteria for a family of subgroups `ℳ : ℤ → AddSubgroup T` to be an internal
direct sum, used to build the dg structures on dg submodules, direct sums and graded products.

* `DG.coeAddMonoidHom_injective_of_forall_eq_zero`: if a family of degree-`0` maps `φ i : T →+ P i`
  out of an abelian group `T` with a family of subgroups `ℳ` is jointly injective and the targets
  are dg abelian groups, then `⨁ n, ℳ n → T` is injective. With surjectivity this gives
  `DirectSum.IsInternal ℳ`, hence a `DirectSum.Decomposition` via
  `DirectSum.IsInternal.chooseDecomposition`.
-/

open DirectSum

namespace DG

section Internal

variable {ι : Type*} {T : Type*} [AddCommGroup T] (ℳ : ℤ → AddSubgroup T)
  {P : ι → Type*} [∀ i, AddCommGroup (P i)] [∀ i, DGAddCommGroup (P i)]

/-- If a jointly injective family of additive maps `φ i : T →+ P i` into dg abelian groups sends
`ℳ n` into degree `n`, then the canonical map `⨁ n, ℳ n → T` is injective. -/
theorem coeAddMonoidHom_injective_of_forall_eq_zero (φ : ∀ i, T →+ P i)
    (hφ : ∀ i (n : ℤ), ∀ x ∈ ℳ n, φ i x ∈ grading n)
    (hinj : ∀ x : T, (∀ i, φ i x = 0) → x = 0) :
    Function.Injective (DirectSum.coeAddMonoidHom ℳ) := by
  suffices h : ∀ z, DirectSum.coeAddMonoidHom ℳ z = 0 → z = 0 by
    intro y y' hyy'
    rw [← sub_eq_zero]
    exact h _ (by rw [map_sub, hyy', sub_self])
  let r : ∀ i (n : ℤ), ℳ n →+ grading (M := P i) n := fun i n =>
    AddMonoidHom.codRestrict ((φ i).comp (ℳ n).subtype) _ fun x => hφ i n x x.2
  have key : ∀ i z, DirectSum.coeAddMonoidHom (grading (M := P i)) (DirectSum.map (r i) z) =
      φ i (DirectSum.coeAddMonoidHom ℳ z) := by
    intro i z
    induction z using DirectSum.induction_on with
    | zero => simp
    | of n x => simp [r]
    | add x y hx hy => simp [map_add, hx, hy]
  intro z hz
  ext n
  rw [DirectSum.zero_apply, ZeroMemClass.coe_zero]
  apply hinj
  intro i
  have h1 := key i z
  rw [hz, map_zero] at h1
  have h2 : DirectSum.map (r i) z = 0 :=
    (DirectSum.Decomposition.isInternal (grading (M := P i))).injective
      (h1.trans (map_zero _).symm)
  have h3 := congrArg (fun w => (w n : P i)) h2
  simpa [r] using h3

/-- Single-map version of `DG.coeAddMonoidHom_injective_of_forall_eq_zero`: an injective
degree-`0` additive map into a dg abelian group makes `⨁ n, ℳ n → T` injective. -/
theorem coeAddMonoidHom_injective_of_injective {N : Type*} [AddCommGroup N] [DGAddCommGroup N]
    (φ : T →+ N) (hφ : ∀ (n : ℤ), ∀ x ∈ ℳ n, φ x ∈ grading n) (hinj : Function.Injective φ) :
    Function.Injective (DirectSum.coeAddMonoidHom ℳ) :=
  coeAddMonoidHom_injective_of_forall_eq_zero ℳ (P := fun _ : Unit => N) (fun _ => φ)
    (fun _ => hφ) fun x hx => hinj (by rw [hx (), map_zero])

/-- Two-map version of `DG.coeAddMonoidHom_injective_of_forall_eq_zero`. -/
theorem coeAddMonoidHom_injective_of_pair {M N : Type*} [AddCommGroup M] [DGAddCommGroup M]
    [AddCommGroup N] [DGAddCommGroup N] (φ : T →+ M) (ψ : T →+ N)
    (hφ : ∀ (n : ℤ), ∀ x ∈ ℳ n, φ x ∈ grading n) (hψ : ∀ (n : ℤ), ∀ x ∈ ℳ n, ψ x ∈ grading n)
    (hinj : ∀ x : T, φ x = 0 → ψ x = 0 → x = 0) :
    Function.Injective (DirectSum.coeAddMonoidHom ℳ) := by
  suffices h : ∀ z, DirectSum.coeAddMonoidHom ℳ z = 0 → z = 0 by
    intro y y' hyy'
    rw [← sub_eq_zero]
    exact h _ (by rw [map_sub, hyy', sub_self])
  let rφ : ∀ (n : ℤ), ℳ n →+ grading (M := M) n := fun n =>
    AddMonoidHom.codRestrict (φ.comp (ℳ n).subtype) _ fun x => hφ n x x.2
  let rψ : ∀ (n : ℤ), ℳ n →+ grading (M := N) n := fun n =>
    AddMonoidHom.codRestrict (ψ.comp (ℳ n).subtype) _ fun x => hψ n x x.2
  have keyφ : ∀ z, DirectSum.coeAddMonoidHom (grading (M := M)) (DirectSum.map rφ z) =
      φ (DirectSum.coeAddMonoidHom ℳ z) := by
    intro z
    induction z using DirectSum.induction_on with
    | zero => simp
    | of n x => simp [rφ]
    | add x y hx hy => simp [map_add, hx, hy]
  have keyψ : ∀ z, DirectSum.coeAddMonoidHom (grading (M := N)) (DirectSum.map rψ z) =
      ψ (DirectSum.coeAddMonoidHom ℳ z) := by
    intro z
    induction z using DirectSum.induction_on with
    | zero => simp
    | of n x => simp [rψ]
    | add x y hx hy => simp [map_add, hx, hy]
  intro z hz
  have hφ' := keyφ z
  have hψ' := keyψ z
  rw [hz, map_zero] at hφ' hψ'
  have h2φ : DirectSum.map rφ z = 0 :=
    (DirectSum.Decomposition.isInternal (grading (M := M))).injective
      (hφ'.trans (map_zero _).symm)
  have h2ψ : DirectSum.map rψ z = 0 :=
    (DirectSum.Decomposition.isInternal (grading (M := N))).injective
      (hψ'.trans (map_zero _).symm)
  ext n
  rw [DirectSum.zero_apply, ZeroMemClass.coe_zero]
  refine hinj _ ?_ ?_
  · simpa [rφ] using congrArg (fun w => (w n : M)) h2φ
  · simpa [rψ] using congrArg (fun w => (w n : N)) h2ψ

/-- If every element of `T` lies in the subgroup generated by the `ℳ n`, then
`⨁ n, ℳ n → T` is surjective. -/
theorem coeAddMonoidHom_surjective_of_mem_iSup (h : ∀ x : T, x ∈ ⨆ n, ℳ n) :
    Function.Surjective (DirectSum.coeAddMonoidHom ℳ) := fun x => by
  refine AddSubgroup.iSup_induction ℳ (C := fun x => ∃ y, DirectSum.coeAddMonoidHom ℳ y = x) (h x)
    (fun n x hx => ⟨DirectSum.of _ n ⟨x, hx⟩, DirectSum.coeAddMonoidHom_of _ _ _⟩)
    ⟨0, map_zero _⟩ ?_
  rintro x y ⟨y₁, rfl⟩ ⟨y₂, rfl⟩
  exact ⟨y₁ + y₂, map_add _ _ _⟩

end Internal

end DG
