import Mathlib.CategoryTheory.Limits.Shapes.Products
import Mathlib.Algebra.Homology.HomologicalComplexLimits
import DG.Module.DirectSum
import DG.Homotopy.Forget

/-!
# Coproducts and products of dg modules

The category `DGModuleCat A` has arbitrary coproducts, given by direct sums `⨁ j, M j` with the
componentwise dg structure (`DG.DirectSum.instDGAddCommGroup`), and arbitrary products, given by
the graded products `DG.GradedPi A M` (the submodule of `∀ j, M j` generated by the families of
homogeneous elements of a fixed degree). The forgetful functor to cochain complexes of
`R`-modules preserves coproducts: in each degree `n`, `(⨁ j, M j)ⁿ = ⨁ j, (M j)ⁿ`.

## Universes

For `J : Type w` the (co)products are constructed in `DGModuleCat.{max v w} A`, as for
`ModuleCat` in Mathlib.
-/

open CategoryTheory CategoryTheory.Limits DirectSum

universe w v u

noncomputable section

namespace DG

namespace DGModuleCat

variable {A : Type u} [Ring A] [DGAddCommGroup A]

/-! ### Coproducts -/

section Coproducts

variable {J : Type w} [DecidableEq J] (F : J → DGModuleCat.{max v w} A)

/-- The direct sum of a family of dg modules, as a cofan. -/
def coproductCocone : Cofan F :=
  Cofan.mk (of A (⨁ j : J, F j)) fun j =>
    ofHom (DGModuleHom.lof A (fun j => (F j : Type (max v w))) j)

@[simp]
theorem coproductCocone_pt : (coproductCocone F).pt = of A (⨁ j : J, F j) := rfl

@[simp]
theorem coproductCocone_inj (j : J) :
    (coproductCocone F).inj j = ofHom (DGModuleHom.lof A (fun j => (F j : Type (max v w))) j) :=
  rfl

/-- The direct sum is the coproduct in `DGModuleCat A`. -/
def coproductCoconeIsColimit : IsColimit (coproductCocone F) :=
  mkCofanColimit _ (fun t => ofHom (DGModuleHom.toModule fun j => (t.inj j).hom))
    (fun t j => hom_ext (DGModuleHom.toModule_comp_lof _ j))
    fun t m hm => hom_ext (DGModuleHom.directSum_ext fun j => by
      change m.hom.comp _ = (DGModuleHom.toModule fun j => (t.inj j).hom).comp _
      rw [DGModuleHom.toModule_comp_lof, ← hm j]
      rfl)

instance hasCoproduct : HasCoproduct F :=
  HasColimit.mk ⟨_, coproductCoconeIsColimit F⟩

end Coproducts

instance hasCoproducts : HasCoproducts.{w} (DGModuleCat.{max v w} A) := fun J =>
  { has_colimit := fun K => by
      letI := Classical.decEq J
      exact HasColimit.mk
        ⟨(Cocones.precompose Discrete.natIsoFunctor.hom).obj (coproductCocone (K.obj ∘ Discrete.mk)),
          (IsColimit.precomposeHomEquiv _ _).symm (coproductCoconeIsColimit _)⟩ }

instance hasCoproducts' : HasCoproducts.{v} (DGModuleCat.{v} A) :=
  hasCoproducts.{v, v}

/-! ### Products -/

section Products

variable {J : Type w} (F : J → DGModuleCat.{max v w} A)

/-- The graded product of a family of dg modules, as a fan. -/
def productCone : Fan F :=
  Fan.mk (of A (GradedPi A fun j => (F j : Type (max v w)))) fun j =>
    ofHom (DGModuleHom.proj A (fun j => (F j : Type (max v w))) j)

@[simp]
theorem productCone_pt : (productCone F).pt = of A (GradedPi A fun j => (F j : Type (max v w))) :=
  rfl

@[simp]
theorem productCone_proj (j : J) :
    (productCone F).proj j = ofHom (DGModuleHom.proj A (fun j => (F j : Type (max v w))) j) :=
  rfl

/-- The graded product is the product in `DGModuleCat A`. -/
def productConeIsLimit : IsLimit (productCone F) :=
  mkFanLimit _ (fun s => ofHom (DGModuleHom.pi fun j => (s.proj j).hom)) (fun _ _ => rfl)
    fun _ _ hm => hom_ext (DGModuleHom.gradedPi_ext fun j => congrArg Hom.hom (hm j))

instance hasProduct : HasProduct F :=
  HasLimit.mk ⟨_, productConeIsLimit F⟩

end Products

instance hasProducts : HasProducts.{w} (DGModuleCat.{max v w} A) :=
  hasProducts_of_limit_fans (fun F => productCone F) fun F => productConeIsLimit F

instance hasProducts' : HasProducts.{v} (DGModuleCat.{v} A) :=
  hasProducts.{v, v}

/-! ### The forgetful functor preserves coproducts -/

section Forget

open DGModuleCat.Algebra

variable (R : Type*) [CommRing R] [Algebra R A] [DGRing A] [DGAlgebra R A]
variable {J : Type w} [DecidableEq J] (F : J → DGModuleCat.{max v w} A)

/-- The comparison map `⨁ j, (M j)ⁿ → (⨁ j, M j)ⁿ` in degree `n`. -/
def gradingDirectSum (n : ℤ) :
    (⨁ j, DGModule.gradingSubmodule R A (F j) n) →ₗ[R]
      DGModule.gradingSubmodule R A (coproductCocone F).pt n :=
  DirectSum.toModule R J (DGModule.gradingSubmodule R A (coproductCocone F).pt n) fun j =>
    homRestrict R ((coproductCocone F).inj j) n

theorem gradingDirectSum_lof (n : ℤ) (j : J) (x : DGModule.gradingSubmodule R A (F j) n) :
    gradingDirectSum R F n (DirectSum.lof R J (fun j => DGModule.gradingSubmodule R A (F j) n) j x)
      = homRestrict R ((coproductCocone F).inj j) n x := by
  unfold gradingDirectSum
  exact DirectSum.toModule_lof R (M := fun j => DGModule.gradingSubmodule R A (F j) n)
    (N := DGModule.gradingSubmodule R A (coproductCocone F).pt n)
    (φ := fun j => homRestrict R ((coproductCocone F).inj j) n) j x

/-- The underlying family of an element of `(⨁ j, M j)ⁿ`. -/
abbrev toFamily {n : ℤ} (x : DGModule.gradingSubmodule R A (coproductCocone F).pt n) :
    ⨁ j : J, F j :=
  (x : (coproductCocone F).pt)

theorem toFamily_gradingDirectSum (n : ℤ) (y : ⨁ j, DGModule.gradingSubmodule R A (F j) n)
    (j : J) : toFamily R F (gradingDirectSum R F n y) j = (y j : F j) := by
  induction y using DirectSum.induction_on with
  | zero => rw [map_zero]; rfl
  | of k x =>
    rw [← DirectSum.lof_eq_of R, gradingDirectSum_lof]
    change (DirectSum.of (fun j => (F j : Type (max v w))) k (x : F k)) j = _
    by_cases h : k = j
    · subst h
      rw [DirectSum.of_eq_same, DirectSum.lof_eq_of, DirectSum.of_eq_same]
    · rw [DirectSum.of_eq_of_ne _ _ _ h, DirectSum.lof_eq_of, DirectSum.of_eq_of_ne _ _ _ h,
        ZeroMemClass.coe_zero]
  | add x y hx hy =>
    rw [map_add, DirectSum.add_apply]
    change toFamily R F _ j + toFamily R F _ j = _
    rw [hx, hy]; rfl

theorem gradingDirectSum_bijective (n : ℤ) : Function.Bijective (gradingDirectSum R F n) := by
  classical
  constructor
  · intro y y' h
    ext j
    have := toFamily_gradingDirectSum R F n y j
    rw [h, toFamily_gradingDirectSum] at this
    exact this.symm
  · intro x
    refine ⟨∑ j ∈ (toFamily R F x).support,
      DirectSum.lof R J (fun j => DGModule.gradingSubmodule R A (F j) n) j
        ⟨toFamily R F x j, x.2 j⟩, ?_⟩
    apply Subtype.ext
    rw [map_sum, AddSubmonoidClass.coe_finset_sum]
    simp only [gradingDirectSum_lof, coe_homRestrict_apply, coproductCocone_inj, ofHom_apply,
      DGModuleHom.lof_apply]
    exact DirectSum.sum_support_of (toFamily R F x)

/-- The comparison map `⨁ j, (M j)ⁿ ≃ (⨁ j, M j)ⁿ` as a linear equivalence. -/
def gradingDirectSumEquiv (n : ℤ) :
    (⨁ j, DGModule.gradingSubmodule R A (F j) n) ≃ₗ[R]
      DGModule.gradingSubmodule R A (coproductCocone F).pt n :=
  LinearEquiv.ofBijective _ (gradingDirectSum_bijective R F n)

theorem gradingDirectSumEquiv_symm_homRestrict (n : ℤ) (j : J)
    (x : DGModule.gradingSubmodule R A (F j) n) :
    (gradingDirectSumEquiv R F n).symm (homRestrict R ((coproductCocone F).inj j) n x) =
      DirectSum.lof R J (fun j => DGModule.gradingSubmodule R A (F j) n) j x := by
  rw [LinearEquiv.symm_apply_eq]
  exact (gradingDirectSum_lof R F n j x).symm

variable {R F} in
/-- The morphism out of the degree-`n` part of the direct sum induced by a cocone. -/
def descEval {n : ℤ}
    (s : Cocone ((Discrete.functor F) ⋙ forget R A ⋙ HomologicalComplex.eval _ _ n)) :
    ModuleCat.of R (DGModule.gradingSubmodule R A (coproductCocone F).pt n) ⟶ s.pt :=
  ModuleCat.ofHom ((DirectSum.toModule R J s.pt fun j => (s.ι.app ⟨j⟩).hom) ∘ₗ
    (gradingDirectSumEquiv R F n).symm.toLinearMap)

theorem descEval_fac {n : ℤ}
    (s : Cocone ((Discrete.functor F) ⋙ forget R A ⋙ HomologicalComplex.eval _ _ n)) (j : J) :
    ((forget R A ⋙ HomologicalComplex.eval _ _ n).mapCocone (coproductCocone F)).ι.app ⟨j⟩ ≫
      descEval s = s.ι.app ⟨j⟩ := by
  refine ModuleCat.hom_ext (LinearMap.ext fun x => ?_)
  change DirectSum.toModule R J s.pt (fun j => (s.ι.app ⟨j⟩).hom)
    ((gradingDirectSumEquiv R F n).symm (homRestrict R ((coproductCocone F).inj j) n x)) =
      (s.ι.app ⟨j⟩).hom x
  rw [gradingDirectSumEquiv_symm_homRestrict]
  exact DirectSum.toModule_lof R (M := fun j => DGModule.gradingSubmodule R A (F j) n)
    (N := s.pt) (φ := fun j => (s.ι.app ⟨j⟩).hom) j x

theorem descEval_uniq {n : ℤ}
    (s : Cocone ((Discrete.functor F) ⋙ forget R A ⋙ HomologicalComplex.eval _ _ n))
    (m : ModuleCat.of R (DGModule.gradingSubmodule R A (coproductCocone F).pt n) ⟶ s.pt)
    (hm : ∀ j, m.hom ∘ₗ homRestrict R ((coproductCocone F).inj j) n = (s.ι.app ⟨j⟩).hom) :
    m = descEval s := by
  have key : m.hom ∘ₗ (gradingDirectSumEquiv R F n).toLinearMap =
      DirectSum.toModule R J s.pt fun j => (s.ι.app ⟨j⟩).hom :=
    DirectSum.linearMap_ext R fun j => LinearMap.ext fun x => by
      refine (congrArg m.hom (gradingDirectSum_lof R F n j x)).trans (Eq.trans ?_
        (DirectSum.toModule_lof R (M := fun j => DGModule.gradingSubmodule R A (F j) n)
          (N := s.pt) (φ := fun j => (s.ι.app ⟨j⟩).hom) j x).symm)
      exact LinearMap.congr_fun (hm j) x
  refine ModuleCat.hom_ext (LinearMap.ext fun x => ?_)
  obtain ⟨y, rfl⟩ := (gradingDirectSumEquiv R F n).surjective x
  change m.hom (gradingDirectSumEquiv R F n y) =
    DirectSum.toModule R J s.pt (fun j => (s.ι.app ⟨j⟩).hom)
      ((gradingDirectSumEquiv R F n).symm (gradingDirectSumEquiv R F n y))
  rw [LinearEquiv.symm_apply_apply]
  exact LinearMap.congr_fun key y

/-- In each degree, the forgetful functor sends the direct sum cofan to a colimit cofan. -/
def isColimitMapCoconeEval (n : ℤ) :
    IsColimit ((forget R A ⋙ HomologicalComplex.eval _ _ n).mapCocone (coproductCocone F)) where
  desc s := descEval s
  fac s := by
    rintro ⟨j⟩
    exact descEval_fac R F s j
  uniq s m hm := descEval_uniq R F s m fun j => by
    have h := congrArg ModuleCat.Hom.hom (hm ⟨j⟩)
    rw [ModuleCat.hom_comp] at h
    exact h

instance forget_preservesColimit_discreteFunctor :
    PreservesColimit (Discrete.functor F) (forget R A) :=
  preservesColimit_of_preserves_colimit_cocone (coproductCoconeIsColimit F)
    (HomologicalComplex.isColimitOfEval _ _ fun n =>
      IsColimit.ofIsoColimit (isColimitMapCoconeEval R F n) (Functor.mapCoconeMapCocone _).symm)

omit [DecidableEq J] in
/-- The forgetful functor to cochain complexes preserves coproducts. -/
instance forget_preservesColimitsOfShape_discrete :
    PreservesColimitsOfShape (Discrete J) (forget.{max v w} R A) where
  preservesColimit {K} := by
    letI := Classical.decEq J
    exact preservesColimit_of_iso_diagram (forget R A) (Discrete.natIsoFunctor (F := K)).symm

end Forget

end DGModuleCat

end DG

end
