import DG.Compact.Generation
import Mathlib.CategoryTheory.Limits.Opposites
import Mathlib.CategoryTheory.Triangulated.Opposite.Functor
import Mathlib.CategoryTheory.Triangulated.Yoneda

/-!
# Brown representability for compactly generated triangulated categories

Let `C` be a pretriangulated category with coproducts, compactly generated by a family
`G : ι → C` indexed by a small type (`DG.CompactlyGenerates G`, see `DG.Compact.Generation`).
This file proves Neeman's form of the Brown representability theorem
([Ne96, Thm. 3.1]; see also [Kr, §5.1]):

* `DG.CompactlyGenerates.exists_iso_preadditiveYoneda`: a homological functor
  `H : Cᵒᵖ ⥤ AddCommGrp` (Mathlib's `Functor.IsHomological`, for the pretriangulated structure
  on `Cᵒᵖ`) which sends coproducts to products (`DG.SendsCoproductsToProducts`) is
  representable: `H ≅ C(-, X)` (`preadditiveYoneda.obj X`) for some object `X`. Equivalent
  forms are `DG.CompactlyGenerates.exists_bijective` (there are `X` and `u ∈ H(X)` such that
  `φ ↦ H(φ)(u)` is a bijection `C(Y, X) → H(Y)` for all `Y`) and
  `DG.CompactlyGenerates.isRepresentable` (the underlying functor to types is representable).
* `DG.CompactlyGenerates.isLeftAdjoint`: a triangulated functor `F : C ⥤ D` to a
  pretriangulated category which preserves coproducts has a right adjoint [Ne96, Thm. 4.1].

On the way we prove:

* `DG.CompactlyGenerates.forall_of_isLocalizing`: a property of objects of `C` which contains
  the `G i` and is *localizing* (`DG.IsLocalizing`: closed under isomorphisms, shifts,
  extensions and coproducts) holds for every object. That is, `C` is the smallest localizing
  subcategory of itself containing `G`.
* `DG.CompactlyGenerates.isIso_of_bijective`: a natural transformation between homological
  functors `Cᵒᵖ ⥤ AddCommGrp` sending coproducts to products is an isomorphism as soon as it is
  bijective on all shifts `G i⟦n⟧` of the generators.

## Proof

*Localizing subcategories.* For an object `X`, the cellular tower `P 0 ⟶ P 1 ⟶ ⋯` over `X` of
`DG.Compact.Generation` has homotopy colimit isomorphic to `X`
(`DG.CellTower.isIso_of_comp_hocolimι`). Each `P n` is built from coproducts of shifted
generators by cones, so it lies in every localizing subcategory containing `G`; hence so do
the homotopy colimit (a cone of a morphism between coproducts) and `X`.

*The comparison of two functors.* For `η : F ⟶ H`, the objects `Y` with `η` bijective at every
`Y⟦n⟧` form a localizing subcategory (`DG.isLocalizing_bijective`): the five lemma applied to
the long exact sequences of a distinguished triangle gives the closure under extensions, and
the closure under coproducts holds because both functors send coproducts to products.

*Brown's construction* (`DG.BrownTower`, [Ne96, proof of Thm. 3.1]). Starting from
`X₀ = ∐ G i⟦n⟧` over all `i`, `n` and all `x ∈ H(G i⟦n⟧)`, with the element `u₀ ∈ H(X₀)` whose
components are the `x` (this uses that `H(X₀) = ∏ H(G i⟦n⟧)`), one builds a tower
`X₀ ⟶ X₁ ⟶ ⋯` with compatible elements `uₖ ∈ H(Xₖ)`: `Xₖ₊₁` is the cone of the morphism to `Xₖ`
from the coproduct of the `G i⟦n⟧` over all `φ : G i⟦n⟧ ⟶ Xₖ` with `H(φ)(uₖ) = 0`, and `uₖ₊₁` is
a lift of `uₖ` along `Xₖ ⟶ Xₖ₊₁`, which exists by exactness. Let `X` be the homotopy colimit,
the cone of `1 - shift : ∐ Xₖ ⟶ ∐ Xₖ`. The family `(uₖ)ₖ` is an element of
`H(∐ Xₖ) = ∏ H(Xₖ)` killed by `H(1 - shift)`, so it lifts to `u ∈ H(X)` restricting to every
`uₖ`. The transformation `C(-, X) ⟶ H`, `φ ↦ H(φ)(u)`, is surjective on each `G i⟦n⟧` by
construction of `X₀`, and injective on it since `G i⟦n⟧` is compact: a morphism
`G i⟦n⟧ ⟶ X` factors through some `Xₖ` (`DG.hocolim_exists_factor`), and if it is killed by `u`
it is killed by `Xₖ ⟶ Xₖ₊₁`. By the comparison result it is an isomorphism.

## Conventions and deviations

Neeman works with triangulated categories; the octahedral axiom is not used here, so `C` is
only assumed pretriangulated. Neeman's homological functors on `Cᵒᵖ` are additive functors
sending distinguished triangles to exact sequences; Mathlib's `Functor.IsHomological` for the
opposite pretriangulated structure is this notion (it implies additivity), and
`DG.exact_map_op` extracts the exactness of `H(X₃) → H(X₂) → H(X₁)` for a distinguished
triangle `X₁ ⟶ X₂ ⟶ X₃ ⟶ X₁⟦1⟧` of `C`.

## Universes

As in `DG.Compact.Generation`, with `C : Type u`, `[Category.{v} C]` and `ι : Type w`,
coproducts, compactness and the coproduct condition on `H` are taken relative to
`Type (max w v)`; `H` takes values in `AddCommGrp.{v}`, the universe of the morphism groups.

## References

* [Ne96] A. Neeman, *The Grothendieck duality theorem via Bousfield's techniques and Brown
  representability*, J. Amer. Math. Soc. 9 (1996), 205–236, Thm. 3.1 and Thm. 4.1.
* [Kr] H. Krause, *Localization theory for triangulated categories*, in: Triangulated
  categories, LMS Lecture Note Ser. 375 (2010), arXiv:0806.1324, §5.1.
-/

universe w w' v v' u u'

namespace DG

open CategoryTheory Limits Pretriangulated Opposite

variable {C : Type u} [Category.{v} C]

section Cofan

variable {J : Type w} {Y : J → C}

/-- A cofan over `Y : J → C`, viewed as a cofan over `Y ∘ ULift.down`. -/
abbrev cofanULift (c : Cofan Y) : Cofan fun j : ULift.{w'} J => Y j.down :=
  Cofan.mk c.pt fun j => c.inj j.down

/-- Reindexing a colimit cofan along `ULift.down` gives a colimit cofan. -/
def isColimitCofanULift {c : Cofan Y} (hc : IsColimit c) :
    IsColimit (cofanULift c : Cofan fun j : ULift.{w'} J => Y j.down) :=
  mkCofanColimit _ (fun s => Cofan.IsColimit.desc hc fun j => s.inj ⟨j⟩)
    (fun s j => Cofan.IsColimit.fac hc _ j.down)
    (fun s m hm => Cofan.IsColimit.hom_ext hc _ _ fun j => by
      rw [Cofan.IsColimit.fac]; exact hm ⟨j⟩)

end Cofan

/-- A functor `H : Cᵒᵖ ⥤ AddCommGrp` *sends coproducts to products* (for coproducts indexed by
types in `Type w`) if for every colimit cofan `c` of a family `Y : J → C`, `J : Type w`, the
canonical map `H(c.pt) → ∏ⱼ H(Y j)`, `x ↦ (H(c.inj j)(x))ⱼ`, is bijective. -/
def SendsCoproductsToProducts (H : Cᵒᵖ ⥤ AddCommGrp.{v'}) : Prop :=
  ∀ (J : Type w) (Y : J → C) (c : Cofan Y), IsColimit c →
    Function.Bijective fun (x : H.obj (op c.pt)) (j : J) => H.map (c.inj j).op x

namespace SendsCoproductsToProducts

variable {H : Cᵒᵖ ⥤ AddCommGrp.{v'}}

/-- Sending coproducts to products relative to a universe implies the same for any smaller
universe. -/
theorem down (hH : SendsCoproductsToProducts.{max w w'} H) :
    SendsCoproductsToProducts.{w} H := by
  intro J Y c hc
  have h := hH (ULift.{w'} J) _ _ (isColimitCofanULift hc)
  constructor
  · intro x y hxy
    exact h.1 (funext fun j => congr_fun hxy j.down)
  · intro g
    obtain ⟨x, hx⟩ := h.2 fun j => g j.down
    exact ⟨x, funext fun j => congr_fun hx ⟨j⟩⟩

variable (hH : SendsCoproductsToProducts.{w} H) {J : Type w} (Y : J → C) [HasCoproduct Y]
include hH

/-- Elements of `H(∐ Y)` are determined by their restrictions to the `Y j`. -/
theorem ext_sigma {x y : H.obj (op (∐ Y))}
    (h : ∀ j, H.map (Sigma.ι Y j).op x = H.map (Sigma.ι Y j).op y) : x = y :=
  (hH J Y _ (coproductIsCoproduct Y)).1 (funext h)

/-- Every family of elements of the `H(Y j)` is the family of restrictions of an element of
`H(∐ Y)`. -/
theorem exists_sigma (g : ∀ j, H.obj (op (Y j))) :
    ∃ x : H.obj (op (∐ Y)), ∀ j, H.map (Sigma.ι Y j).op x = g j := by
  obtain ⟨x, hx⟩ := (hH J Y _ (coproductIsCoproduct Y)).2 g
  exact ⟨x, fun j => congr_fun hx j⟩

end SendsCoproductsToProducts

/-- A representable functor `C(-, X)` sends coproducts to products. -/
theorem sendsCoproductsToProducts_preadditiveYoneda [Preadditive C] (X : C) :
    SendsCoproductsToProducts.{w} (preadditiveYoneda.obj X) := by
  intro J Y c hc
  constructor
  · intro φ ψ h
    exact Cofan.IsColimit.hom_ext hc _ _ fun j => congr_fun h j
  · intro g
    exact ⟨Cofan.IsColimit.desc hc g, funext fun j => Cofan.IsColimit.fac hc g j⟩

/-- A homological functor `H : Cᵒᵖ ⥤ AddCommGrp` sends a distinguished triangle
`X₁ ⟶ X₂ ⟶ X₃ ⟶ X₁⟦1⟧` of `C` to an exact sequence `H(X₃) → H(X₂) → H(X₁)`. -/
theorem exact_map_op [Preadditive C] [HasZeroObject C] [HasShift C ℤ]
    [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
    (H : Cᵒᵖ ⥤ AddCommGrp.{v'}) [H.IsHomological] (T : Triangle C) (hT : T ∈ distTriang C) :
    Function.Exact (H.map T.mor₂.op) (H.map T.mor₁.op) :=
  (ShortComplex.ab_exact_iff_function_exact _).1 (H.map_distinguished_op_exact T hT)

section Localizing

variable [Preadditive C] [HasZeroObject C] [HasShift C ℤ] [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C]

/-- A property of objects of a pretriangulated category is *localizing* (relative to coproducts
indexed by types in `Type w`) if it is closed under isomorphisms, stable under all shifts,
contains the middle term of every distinguished triangle whose outer terms it contains, and is
closed under coproducts. -/
structure IsLocalizing (P : ObjectProperty C) : Prop where
  /-- A localizing property is closed under isomorphisms. -/
  of_iso {X Y : C} : (X ≅ Y) → P Y → P X
  /-- A localizing property is stable under shifts. -/
  shift (X : C) (n : ℤ) : P X → P (X⟦n⟧)
  /-- A localizing property is closed under extensions. -/
  ext₂ (T : Triangle C) : (T ∈ distTriang C) → P T.obj₁ → P T.obj₃ → P T.obj₂
  /-- A localizing property is closed under coproducts. -/
  coproduct {J : Type w} {Y : J → C} (c : Cofan Y) : IsColimit c → (∀ j, P (Y j)) → P c.pt

namespace IsLocalizing

variable {P : ObjectProperty C}

/-- A property which is localizing relative to a universe is localizing relative to any
smaller universe. -/
theorem down (hP : IsLocalizing.{max w w'} P) : IsLocalizing.{w} P where
  of_iso := hP.of_iso
  shift := hP.shift
  ext₂ := hP.ext₂
  coproduct _ hc h := hP.coproduct _ (isColimitCofanULift.{w, w'} hc) fun j => h j.down

variable (hP : IsLocalizing.{w} P)
include hP

/-- A localizing property is closed under cones. -/
theorem ext₃ (T : Triangle C) (hT : T ∈ distTriang C) (h₁ : P T.obj₁) (h₂ : P T.obj₂) :
    P T.obj₃ :=
  hP.ext₂ T.rotate (rot_of_distTriang T hT) h₂ (hP.shift _ 1 h₁)

/-- A localizing property contains the chosen coproduct `∐ Y` of a family in it. -/
theorem sigma {J : Type w} (Y : J → C) [HasCoproduct Y] (h : ∀ j, P (Y j)) : P (∐ Y) :=
  hP.coproduct _ (coproductIsCoproduct Y) h

end IsLocalizing

end Localizing

section NatTrans

variable {F H : Cᵒᵖ ⥤ AddCommGrp.{v'}} (η : F ⟶ H)

/-- Bijectivity of the components of a natural transformation is invariant under
isomorphism. -/
theorem bijective_app_of_iso {A B : C} (e : A ≅ B) (h : Function.Bijective (η.app (op B))) :
    Function.Bijective (η.app (op A)) := by
  have nat : (η.app (op A)) ∘ (F.map e.hom.op) = (H.map e.hom.op) ∘ (η.app (op B)) := by
    funext x
    exact NatTrans.naturality_apply η e.hom.op x
  have h1 : Function.Bijective (F.map e.hom.op) :=
    ConcreteCategory.bijective_of_isIso (F.map e.hom.op)
  have h2 : Function.Bijective (H.map e.hom.op) :=
    ConcreteCategory.bijective_of_isIso (H.map e.hom.op)
  rw [← Function.Bijective.of_comp_iff _ h1, nat]
  exact h2.comp h

/-- Naturality of `η`, as an equality of additive maps. -/
theorem map_op_hom_comp_app_hom {A B : C} (f : A ⟶ B) :
    (H.map f.op).hom.comp (η.app (op B)).hom = (η.app (op A)).hom.comp (F.map f.op).hom := by
  rw [← AddCommGrp.hom_comp, ← AddCommGrp.hom_comp, η.naturality]

/-- If `F` and `H` send coproducts to products and `η` is bijective at every `Y j`, then `η`
is bijective at the point of a colimit cofan of `Y`. -/
theorem bijective_app_cofan (hF : SendsCoproductsToProducts.{w} F)
    (hH : SendsCoproductsToProducts.{w} H) {J : Type w} {Y : J → C} (c : Cofan Y)
    (hc : IsColimit c) (h : ∀ j, Function.Bijective (η.app (op (Y j)))) :
    Function.Bijective (η.app (op c.pt)) := by
  have sq : (fun (x : H.obj (op c.pt)) (j : J) => H.map (c.inj j).op x) ∘ η.app (op c.pt) =
      (fun (g : ∀ j, F.obj (op (Y j))) (j : J) => η.app (op (Y j)) (g j)) ∘
        (fun (x : F.obj (op c.pt)) (j : J) => F.map (c.inj j).op x) := by
    funext x j
    exact (NatTrans.naturality_apply η (c.inj j).op x).symm
  have hpi : Function.Bijective
      (fun (g : ∀ j, F.obj (op (Y j))) (j : J) => η.app (op (Y j)) (g j)) :=
    ⟨fun g g' hg => funext fun j => (h j).1 (congr_fun hg j),
      fun g => ⟨fun j => ((h j).2 (g j)).choose, funext fun j => ((h j).2 (g j)).choose_spec⟩⟩
  rw [← Function.Bijective.of_comp_iff' (hH J Y c hc), sq]
  exact hpi.comp (hF J Y c hc)

variable [Preadditive C] [HasZeroObject C] [HasShift C ℤ] [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C] [F.IsHomological] [H.IsHomological]

/-- The five lemma for a natural transformation between homological functors: for a
distinguished triangle `X₁ ⟶ X₂ ⟶ X₃ ⟶ X₁⟦1⟧`, `η` is bijective at `X₃` if it is surjective at
`X₂⟦1⟧`, bijective at `X₁⟦1⟧` and `X₂`, and injective at `X₁`. -/
theorem bijective_app_obj₃ (T : Triangle C) (hT : T ∈ distTriang C)
    (h₁ : Function.Surjective (η.app (op (T.obj₂⟦(1 : ℤ)⟧))))
    (h₂ : Function.Bijective (η.app (op (T.obj₁⟦(1 : ℤ)⟧))))
    (h₄ : Function.Bijective (η.app (op T.obj₂))) (h₅ : Function.Injective (η.app (op T.obj₁))) :
    Function.Bijective (η.app (op T.obj₃)) :=
  AddMonoidHom.bijective_of_surjective_of_bijective_of_bijective_of_injective
    (F.map (-T.mor₁⟦(1 : ℤ)⟧').op).hom (F.map T.mor₃.op).hom (F.map T.mor₂.op).hom
    (F.map T.mor₁.op).hom
    (H.map (-T.mor₁⟦(1 : ℤ)⟧').op).hom (H.map T.mor₃.op).hom (H.map T.mor₂.op).hom
    (H.map T.mor₁.op).hom
    (η.app _).hom (η.app _).hom (η.app _).hom (η.app _).hom (η.app _).hom
    (map_op_hom_comp_app_hom η _) (map_op_hom_comp_app_hom η _)
    (map_op_hom_comp_app_hom η _) (map_op_hom_comp_app_hom η _)
    (exact_map_op F _ (rot_of_distTriang _ (rot_of_distTriang T hT)))
    (exact_map_op F _ (rot_of_distTriang T hT)) (exact_map_op F T hT)
    (exact_map_op H _ (rot_of_distTriang _ (rot_of_distTriang T hT)))
    (exact_map_op H _ (rot_of_distTriang T hT)) (exact_map_op H T hT)
    h₁ h₂ h₄ h₅

/-- For a natural transformation `η` between homological functors `Cᵒᵖ ⥤ AddCommGrp` sending
coproducts to products, the objects `Y` such that `η` is bijective at every shift `Y⟦n⟧` form a
localizing subcategory. -/
theorem isLocalizing_bijective [HasCoproducts.{w} C] (hF : SendsCoproductsToProducts.{w} F)
    (hH : SendsCoproductsToProducts.{w} H) :
    IsLocalizing.{w} fun Y : C => ∀ n : ℤ, Function.Bijective (η.app (op (Y⟦n⟧))) := by
  have shift : ∀ (X : C) (m : ℤ), (∀ n : ℤ, Function.Bijective (η.app (op (X⟦n⟧)))) →
      ∀ n : ℤ, Function.Bijective (η.app (op (X⟦m⟧⟦n⟧))) := fun X m h n =>
    bijective_app_of_iso η ((shiftFunctorAdd C m n).app X).symm (h (m + n))
  have self : ∀ X : C, (∀ n : ℤ, Function.Bijective (η.app (op (X⟦n⟧)))) →
      Function.Bijective (η.app (op X)) := fun X h =>
    bijective_app_of_iso η ((shiftFunctorZero C ℤ).app X).symm (h 0)
  refine ⟨fun e h n => bijective_app_of_iso η ((shiftFunctor C n).mapIso e) (h n), shift, ?_, ?_⟩
  · intro T hT h₁ h₃ n
    let T' := (CategoryTheory.shiftFunctor (Triangle C) n).obj T
    have hT' : T' ∈ distTriang C := Triangle.shift_distinguished T hT n
    exact bijective_app_obj₃ η T'.invRotate (inv_rot_of_distTriang T' hT')
      (self _ (shift _ 1 (shift _ n h₁))).2 (self _ (shift _ 1 (shift _ (-1) (shift _ n h₃))))
      (self _ (shift _ n h₁)) (self _ (shift _ (-1) (shift _ n h₃))).1
  · intro J Y c hc h n
    let e₁ : c.pt ≅ ∐ Y := hc.coconePointUniqueUpToIso (coproductIsCoproduct Y)
    let e : c.pt⟦n⟧ ≅ ∐ fun j => (Y j)⟦n⟧ := (shiftFunctor C n).mapIso e₁ ≪≫
      (asIso (sigmaComparison (shiftFunctor C n) Y)).symm
    exact bijective_app_of_iso η e (bijective_app_cofan η hF hH _ (coproductIsCoproduct _)
      fun j => h j n)

end NatTrans

section Generation

variable [Preadditive C] [HasZeroObject C] [HasShift C ℤ] [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C] {ι : Type w} {G : ι → C}

namespace CellTower

/-- If `G` compactly generates `C`, every object `X` is the homotopy colimit of its cellular
tower: a morphism `hocolim P ⟶ X` compatible with the morphisms `P n ⟶ X` is an isomorphism.
(This is the first half of the proof of `DG.thickClosure_of_isCompact`.) -/
theorem isIso_of_comp_hocolimι [HasCoproducts.{max w v} C] (hG : CompactlyGenerates G) {X : C}
    [HasCoproduct fun n => (tower G X n).left]
    (h : hocolim (fun n => (tower G X n).left) (towerMap G X) ⟶ X)
    (hh : ∀ n, hocolimι _ (towerMap G X) n ≫ h = (tower G X n).hom) : IsIso h := by
  haveI : HasCoproducts.{0} C := hasCoproducts_shrink.{0, max w v}
  let P : ℕ → C := fun n => (tower G X n).left
  let H := hocolim P (towerMap G X)
  have hcpt : ∀ (i : ι) (m : ℤ), IsCompact.{0} ((G i)⟦m⟧) :=
    fun i m => ((hG.isCompact i).shift m).down
  -- `h` is injective on morphisms from shifted generators.
  have inj : ∀ (i : ι) (m : ℤ) (a : (G i)⟦m⟧ ⟶ H), a ≫ h = 0 → a = 0 := by
    intro i m a ha
    obtain ⟨k, b, rfl⟩ := hocolim_exists_factor P (towerMap G X) (hcpt i m) a
    have hb : b ≫ (tower G X k).hom = 0 := by rw [← hh k, ← Category.assoc, ha]
    rw [← f_comp_hocolimι, ← Category.assoc, comp_towerMap_eq_zero G b hb, Limits.zero_comp]
  -- `h` is an isomorphism: its cone has no nonzero morphisms from shifted generators.
  obtain ⟨Z, g₂, g₃, hT⟩ := distinguished_cocone_triangle h
  have hZ : IsZero Z := by
    refine hG.isZero_of_forall_eq_zero Z fun i m φ => ?_
    let adj : shiftFunctor C (-1 : ℤ) ⊣ shiftFunctor C (1 : ℤ) :=
      (shiftEquiv C (1 : ℤ)).symm.toAdjunction
    have h₁ : φ ≫ g₃ = 0 := by
      have h₃₁ : g₃ ≫ h⟦(1 : ℤ)⟧' = 0 := comp_distTriang_mor_zero₃₁ _ hT
      set ψ := (adj.homEquiv _ _).symm (φ ≫ g₃)
      have hψ : ψ ≫ h = 0 := by
        apply (adj.homEquiv _ _).injective
        rw [adj.homEquiv_naturality_right, Equiv.apply_symm_apply, Category.assoc, h₃₁,
          Limits.comp_zero, Adjunction.homEquiv_unit, Functor.map_zero, Limits.comp_zero]
      let e := (shiftFunctorAdd' C m (-1) (m + -1) rfl).app (G i)
      have : e.hom ≫ ψ = 0 := inj i (m + -1) _ (by rw [Category.assoc, hψ, Limits.comp_zero])
      rw [← Equiv.apply_symm_apply (adj.homEquiv _ _) (φ ≫ g₃)]
      change adj.homEquiv _ _ ψ = 0
      rw [(cancel_epi e.hom).1 (this.trans (Limits.comp_zero).symm), Adjunction.homEquiv_unit,
        Functor.map_zero, Limits.comp_zero]
    obtain ⟨x, rfl⟩ := Triangle.coyoneda_exact₃ _ hT φ h₁
    obtain ⟨y, rfl⟩ := exists_lift_base G x
    have h₁₂ : h ≫ g₂ = 0 := comp_distTriang_mor_zero₁₂ _ hT
    change (y ≫ (tower G X 0).hom) ≫ g₂ = 0
    rw [← hh 0, Category.assoc, Category.assoc, h₁₂, Limits.comp_zero, Limits.comp_zero]
  exact (Triangle.isZero₃_iff_isIso₁ _ hT).1 hZ

end CellTower

open CellTower in
/-- **The localizing subcategory generated by a set of compact generators is everything.** If
`G` compactly generates `C`, a localizing property of objects of `C` containing every `G i`
holds for all objects of `C`. -/
theorem CompactlyGenerates.forall_of_isLocalizing [HasCoproducts.{max w v} C]
    (hG : CompactlyGenerates G) {P : ObjectProperty C} (hP : IsLocalizing.{max w v} P)
    (hGP : ∀ i, P (G i)) (X : C) : P X := by
  haveI : HasCoproducts.{0} C := hasCoproducts_shrink.{0, max w v}
  have hP₀ : IsLocalizing.{0} P := hP.down
  have hGn : ∀ (i : ι) (n : ℤ), P ((G i)⟦n⟧) := fun i n => hP.shift _ n (hGP i)
  have htower : ∀ n, P (tower G X n).left := by
    intro n
    induction n with
    | zero => exact hP.sigma _ fun c => hGn _ _
    | succ n ih =>
      exact hP.ext₃ _ (nextTriangle_distinguished G _) (hP.sigma _ fun c => hGn _ _) ih
  obtain ⟨h, hh⟩ := hocolim_exists_desc (fun n => (tower G X n).left) (towerMap G X)
    (fun n => (tower G X n).hom) (towerMap_comp_hom G)
  have := isIso_of_comp_hocolimι hG h hh
  exact hP.of_iso (asIso h).symm (hP₀.ext₃ _ (hocolimTriangle_distinguished _ _)
    (hP₀.sigma _ htower) (hP₀.sigma _ htower))

/-- If `G` compactly generates `C`, a natural transformation `η : F ⟶ H` between homological
functors `Cᵒᵖ ⥤ AddCommGrp` which send coproducts to products is an isomorphism if it is
bijective at every shift `G i⟦n⟧` of a generator. -/
theorem CompactlyGenerates.isIso_of_bijective [HasCoproducts.{max w v} C]
    (hG : CompactlyGenerates G) {F H : Cᵒᵖ ⥤ AddCommGrp.{v'}} [F.IsHomological]
    [H.IsHomological] (hF : SendsCoproductsToProducts.{max w v} F)
    (hH : SendsCoproductsToProducts.{max w v} H) (η : F ⟶ H)
    (h : ∀ (i : ι) (n : ℤ), Function.Bijective (η.app (op ((G i)⟦n⟧)))) : IsIso η := by
  have hY := hG.forall_of_isLocalizing (isLocalizing_bijective η hF hH) h
  have : ∀ Y : Cᵒᵖ, IsIso (η.app Y) := fun Y =>
    (ConcreteCategory.isIso_iff_bijective _).2
      (bijective_app_of_iso η ((shiftFunctorZero C ℤ).app Y.unop).symm (hY Y.unop 0))
  exact NatIso.isIso_of_isIso_app η

end Generation

section Yoneda

variable [Preadditive C] (H : Cᵒᵖ ⥤ AddCommGrp.{v}) [H.Additive]

/-- The natural transformation `C(-, X) ⟶ H` corresponding to an element `u ∈ H(X)` by the
Yoneda lemma: `φ ↦ H(φ)(u)`. -/
noncomputable def preadditiveYonedaNatTrans {X : C} (u : H.obj (op X)) :
    preadditiveYoneda.obj X ⟶ H where
  app Y := AddCommGrp.ofHom
    { toFun := fun φ : Y.unop ⟶ X => H.map φ.op u
      map_zero' := by simp
      map_add' := fun φ ψ => by simp [H.map_add] }
  naturality Y Y' f := by
    ext φ
    change H.map (f.unop ≫ φ).op u = H.map f (H.map φ.op u)
    rw [op_comp, H.map_comp, ConcreteCategory.comp_apply]
    rfl

@[simp]
theorem preadditiveYonedaNatTrans_app_apply {X : C} (u : H.obj (op X)) (Y : C) (φ : Y ⟶ X) :
    (preadditiveYonedaNatTrans H u).app (op Y) φ = H.map φ.op u :=
  rfl

end Yoneda

section Brown

variable [HasShift C ℤ] {ι : Type w} (G : ι → C) (H : Cᵒᵖ ⥤ AddCommGrp.{v})

namespace BrownTower

/-- A stage of the Brown tower: an object `X` with an element of `H(X)`. -/
structure Stage where
  /-- The object. -/
  obj : C
  /-- The element of `H(obj)`. -/
  elt : H.obj (op obj)

/-- The cells of the first stage of the Brown tower: all elements of all `H(G i⟦n⟧)`. -/
def Cells : Type (max w v) :=
  Σ (i : ι) (n : ℤ), H.obj (op ((G i)⟦n⟧))

/-- The cells attached to a stage `A` of the Brown tower: the morphisms
`φ : G i⟦n⟧ ⟶ A.obj` with `H(φ)(A.elt) = 0`. -/
def KerCells (A : Stage H) : Type (max w v) :=
  Σ (i : ι) (n : ℤ), {φ : (G i)⟦n⟧ ⟶ A.obj // H.map φ.op A.elt = 0}

variable {H} [HasCoproducts.{max w v} C] (hH : SendsCoproductsToProducts.{max w v} H)

/-- The first stage of the Brown tower: the coproduct of the `G i⟦n⟧` over all
`x ∈ H(G i⟦n⟧)`, with the element of `H(∐ G i⟦n⟧) = ∏ H(G i⟦n⟧)` whose components are the
`x`. -/
noncomputable def base : Stage H where
  obj := ∐ fun c : Cells G H => (G c.1)⟦c.2.1⟧
  elt := (hH.exists_sigma _ fun c => c.2.2).choose

theorem map_ι_base_elt (c : Cells G H) :
    H.map (Sigma.ι (fun c : Cells G H => (G c.1)⟦c.2.1⟧) c).op (base G hH).elt = c.2.2 :=
  (hH.exists_sigma _ fun c => c.2.2).choose_spec c

/-- The morphism to a stage `A` from the coproduct of the shifted generators over its kernel
cells. -/
noncomputable def kerMap (A : Stage H) :
    (∐ fun c : KerCells G H A => (G c.1)⟦c.2.1⟧) ⟶ A.obj :=
  Sigma.desc fun c => c.2.2.1

include hH in
theorem map_kerMap_elt (A : Stage H) : H.map (kerMap G A).op A.elt = 0 := by
  apply hH.ext_sigma
  intro c
  rw [← ConcreteCategory.comp_apply, ← H.map_comp, ← op_comp, kerMap, Sigma.ι_desc, map_zero]
  exact c.2.2.2

variable [Preadditive C] [HasZeroObject C] [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C]

/-- A chosen distinguished triangle `∐ G i⟦n⟧ ⟶ A.obj ⟶ Z ⟶ (∐ G i⟦n⟧)⟦1⟧` on
`kerMap G A`. -/
noncomputable def nextTriangle (A : Stage H) : Triangle C :=
  Triangle.mk (kerMap G A) (distinguished_cocone_triangle (kerMap G A)).choose_spec.choose
    (distinguished_cocone_triangle (kerMap G A)).choose_spec.choose_spec.choose

theorem nextTriangle_distinguished (A : Stage H) : nextTriangle G A ∈ distTriang C :=
  (distinguished_cocone_triangle (kerMap G A)).choose_spec.choose_spec.choose_spec

variable [H.IsHomological]

/-- The next stage of the Brown tower: the cone of `kerMap G A`, with a chosen element
restricting to `A.elt`. -/
noncomputable def next (A : Stage H) : Stage H where
  obj := (nextTriangle G A).obj₃
  elt := ((exact_map_op H _ (nextTriangle_distinguished G A) A.elt).1
    (map_kerMap_elt G hH A)).choose

theorem map_mor₂_next_elt (A : Stage H) :
    H.map (nextTriangle G A).mor₂.op (next G hH A).elt = A.elt :=
  ((exact_map_op H _ (nextTriangle_distinguished G A) A.elt).1
    (map_kerMap_elt G hH A)).choose_spec

/-- The Brown tower `X₀ ⟶ X₁ ⟶ ⋯` of `H`, with compatible elements `uₖ ∈ H(Xₖ)`. -/
noncomputable def tower : ℕ → Stage H
  | 0 => base G hH
  | n + 1 => next G hH (tower n)

/-- The transition morphisms `Xₖ ⟶ Xₖ₊₁` of the Brown tower. -/
noncomputable def towerMap (n : ℕ) : (tower G hH n).obj ⟶ (tower G hH (n + 1)).obj :=
  (nextTriangle G (tower G hH n)).mor₂

/-- The elements of the Brown tower are compatible with the transition morphisms. -/
theorem map_towerMap_elt (n : ℕ) :
    H.map (towerMap G hH n).op (tower G hH (n + 1)).elt = (tower G hH n).elt :=
  map_mor₂_next_elt G hH _

/-- A morphism `G i⟦m⟧ ⟶ Xₖ` killing the element `uₖ` vanishes in `Xₖ₊₁`. -/
theorem comp_towerMap_eq_zero {n : ℕ} {i : ι} {m : ℤ} (ψ : (G i)⟦m⟧ ⟶ (tower G hH n).obj)
    (hψ : H.map ψ.op (tower G hH n).elt = 0) : ψ ≫ towerMap G hH n = 0 := by
  have h : ψ = Sigma.ι (fun c : KerCells G H (tower G hH n) => (G c.1)⟦c.2.1⟧) ⟨i, m, ψ, hψ⟩ ≫
      kerMap G (tower G hH n) := by
    simp [kerMap]
  rw [h, Category.assoc]
  change _ ≫ (nextTriangle G _).mor₁ ≫ (nextTriangle G _).mor₂ = 0
  rw [comp_distTriang_mor_zero₁₂ _ (nextTriangle_distinguished G _), Limits.comp_zero]

end BrownTower

variable [Preadditive C] [HasZeroObject C] [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C] {G}

open BrownTower in
/-- **Brown representability** [Ne96, Thm. 3.1], element form. Let `C` be a pretriangulated
category with coproducts, compactly generated by `G`, and `H : Cᵒᵖ ⥤ AddCommGrp` a homological
functor sending coproducts to products. There are an object `X` and an element `u ∈ H(X)` such
that `φ ↦ H(φ)(u)` is a bijection `C(Y, X) → H(Y)` for every object `Y`. -/
theorem CompactlyGenerates.exists_bijective [HasCoproducts.{max w v} C]
    (hG : CompactlyGenerates G) {H : Cᵒᵖ ⥤ AddCommGrp.{v}} [H.IsHomological]
    (hH : SendsCoproductsToProducts.{max w v} H) :
    ∃ (X : C) (u : H.obj (op X)), ∀ Y : C,
      Function.Bijective fun φ : Y ⟶ X => H.map φ.op u := by
  haveI : HasCoproducts.{0} C := hasCoproducts_shrink.{0, max w v}
  have hH₀ : SendsCoproductsToProducts.{0} H := hH.down
  let P : ℕ → C := fun n => (tower G hH n).obj
  let f := towerMap G hH
  have hT := hocolimTriangle_distinguished P f
  -- The compatible family `(uₖ)ₖ` is an element `v` of `H(∐ Xₖ)` killed by `H(1 - shift)`.
  obtain ⟨v, hv⟩ := hH₀.exists_sigma P fun n => (tower G hH n).elt
  have hv₀ : H.map (hocolimDiff P f).op v = 0 := by
    apply hH₀.ext_sigma
    intro n
    rw [← ConcreteCategory.comp_apply, ← H.map_comp, ← op_comp, ι_hocolimDiff,
      show ∀ {A B : C} (a b : A ⟶ B), (a - b).op = a.op - b.op from fun _ _ => rfl,
      H.map_sub, map_zero]
    change (H.map _).hom v - (H.map _).hom v = 0
    rw [op_comp, H.map_comp, AddCommGrp.hom_comp, AddMonoidHom.comp_apply, sub_eq_zero]
    erw [hv, hv]
    exact (map_towerMap_elt G hH n).symm
  -- Hence it lifts to `u ∈ H(hocolim)`, which restricts to every `uₖ`.
  obtain ⟨u, hu⟩ : ∃ u : H.obj (op (hocolim P f)), H.map (hocolimπ P f).op u = v :=
    (exact_map_op H _ hT v).1 hv₀
  have hu' : ∀ n, H.map (hocolimι P f n).op u = (tower G hH n).elt := by
    intro n
    rw [hocolimι, op_comp, H.map_comp, ConcreteCategory.comp_apply, hu]
    exact hv n
  -- The transformation `C(-, hocolim) ⟶ H` given by `u` is bijective on shifted generators.
  let η := preadditiveYonedaNatTrans H u
  have hgen : ∀ (i : ι) (n : ℤ), Function.Bijective (η.app (op ((G i)⟦n⟧))) := by
    intro i n
    constructor
    · rw [injective_iff_map_eq_zero]
      intro φ hφ
      change H.map φ.op u = 0 at hφ
      obtain ⟨k, b, rfl⟩ :=
        hocolim_exists_factor P f ((hG.isCompact i).shift n).down φ
      rw [op_comp, H.map_comp, ConcreteCategory.comp_apply, hu'] at hφ
      change b ≫ hocolimι P f k = 0
      rw [← f_comp_hocolimι, ← Category.assoc, comp_towerMap_eq_zero G hH b hφ,
        Limits.zero_comp]
    · intro x
      refine ⟨Sigma.ι (fun c : Cells G H => (G c.1)⟦c.2.1⟧) ⟨i, n, x⟩ ≫ hocolimι P f 0, ?_⟩
      change H.map (_ ≫ _).op u = x
      rw [op_comp, H.map_comp, ConcreteCategory.comp_apply]
      erw [hu' 0]
      exact map_ι_base_elt G hH _
  have := hG.isIso_of_bijective (sendsCoproductsToProducts_preadditiveYoneda _) hH η hgen
  exact ⟨_, u, fun Y => (ConcreteCategory.isIso_iff_bijective (η.app (op Y))).1 inferInstance⟩

/-- **Brown representability** [Ne96, Thm. 3.1]. Let `C` be a pretriangulated category with
coproducts, compactly generated by a family `G` indexed by a small type. A homological functor
`H : Cᵒᵖ ⥤ AddCommGrp` which sends coproducts to products is representable: `H ≅ C(-, X)` for
some object `X`. -/
theorem CompactlyGenerates.exists_iso_preadditiveYoneda [HasCoproducts.{max w v} C]
    (hG : CompactlyGenerates G) {H : Cᵒᵖ ⥤ AddCommGrp.{v}} [H.IsHomological]
    (hH : SendsCoproductsToProducts.{max w v} H) :
    ∃ X : C, Nonempty (preadditiveYoneda.obj X ≅ H) := by
  obtain ⟨X, u, hu⟩ := hG.exists_bijective hH
  have : ∀ Y, IsIso ((preadditiveYonedaNatTrans H u).app Y) := fun Y =>
    (ConcreteCategory.isIso_iff_bijective _).2 (hu Y.unop)
  have : IsIso (preadditiveYonedaNatTrans H u) := NatIso.isIso_of_isIso_app _
  exact ⟨X, ⟨asIso (preadditiveYonedaNatTrans H u)⟩⟩

/-- **Brown representability** [Ne96, Thm. 3.1], in terms of `Functor.IsRepresentable`: the
functor `Cᵒᵖ ⥤ Type` underlying a homological functor `H : Cᵒᵖ ⥤ AddCommGrp` sending coproducts
to products is representable. -/
theorem CompactlyGenerates.isRepresentable [HasCoproducts.{max w v} C]
    (hG : CompactlyGenerates G) {H : Cᵒᵖ ⥤ AddCommGrp.{v}} [H.IsHomological]
    (hH : SendsCoproductsToProducts.{max w v} H) :
    (H ⋙ forget AddCommGrp).IsRepresentable := by
  obtain ⟨X, u, hu⟩ := hG.exists_bijective hH
  exact Functor.RepresentableBy.isRepresentable
    { homEquiv := Equiv.ofBijective _ (hu _)
      homEquiv_comp := fun f g => by
        change H.map (f ≫ g).op u = H.map f.op (H.map g.op u)
        rw [op_comp, H.map_comp, ConcreteCategory.comp_apply] }

section Adjoint

open Pretriangulated.Opposite

variable {D : Type u'} [Category.{v} D]

omit [HasShift C ℤ] [Preadditive C] [HasZeroObject C] [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C] in
/-- For a functor `F : C ⥤ D` preserving coproducts and an object `d` of `D`, the functor
`D(F -, d)` sends coproducts to products. -/
theorem sendsCoproductsToProducts_op_comp_preadditiveYoneda [Preadditive D] (F : C ⥤ D)
    (hF : ∀ J : Type w', PreservesColimitsOfShape (Discrete J) F) (d : D) :
    SendsCoproductsToProducts.{w'} (F.op ⋙ preadditiveYoneda.obj d) := by
  intro J Y c hc
  have hc' : IsColimit (F.mapCocone c) := isColimitOfPreserves F hc
  constructor
  · intro x y hxy
    exact hc'.hom_ext fun j => congr_fun hxy j.as
  · intro g
    refine ⟨hc'.desc (Cocone.mk d (Discrete.natTrans fun j => g j.as)), funext fun j => ?_⟩
    exact hc'.fac (Cocone.mk d (Discrete.natTrans fun j => g j.as)) ⟨j⟩

variable [Preadditive D] [HasZeroObject D] [HasShift D ℤ] [∀ n : ℤ, (shiftFunctor D n).Additive]
  [Pretriangulated D]

/-- **Existence of right adjoints** [Ne96, Thm. 4.1]. Let `C` be a pretriangulated category
with coproducts, compactly generated by a family `G` indexed by a small type. A triangulated
functor `F : C ⥤ D` to a pretriangulated category which preserves coproducts has a right
adjoint: for `d : D`, the right adjoint represents the homological functor `D(F -, d)`. -/
theorem CompactlyGenerates.isLeftAdjoint [HasCoproducts.{max w v} C]
    (hG : CompactlyGenerates G) (F : C ⥤ D) [F.CommShift ℤ] [F.IsTriangulated]
    (hF : ∀ J : Type (max w v), PreservesColimitsOfShape (Discrete J) F) :
    F.IsLeftAdjoint := by
  have h : ∀ d : D, ∃ (X : C) (u : F.obj X ⟶ d), ∀ Y : C,
      Function.Bijective fun φ : Y ⟶ X => F.map φ ≫ u := fun d =>
    hG.exists_bijective (H := F.op ⋙ preadditiveYoneda.obj d)
      (sendsCoproductsToProducts_op_comp_preadditiveYoneda F hF d)
  choose X u hu using h
  let e : ∀ (Y : C) (d : D), (F.obj Y ⟶ d) ≃ (Y ⟶ X d) := fun Y d =>
    (Equiv.ofBijective _ (hu d Y)).symm
  have he : ∀ (Y' Y : C) (d : D) (f : Y' ⟶ Y) (g : F.obj Y ⟶ d),
      e Y' d (F.map f ≫ g) = f ≫ e Y d g := by
    intro Y' Y d f g
    apply (Equiv.ofBijective _ (hu d Y')).injective
    change F.map (e Y' d (F.map f ≫ g)) ≫ u d = F.map (f ≫ e Y d g) ≫ u d
    rw [F.map_comp, Category.assoc]
    change (Equiv.ofBijective _ (hu d Y')) ((Equiv.ofBijective _ (hu d Y')).symm _) =
      F.map f ≫ (Equiv.ofBijective _ (hu d Y)) ((Equiv.ofBijective _ (hu d Y)).symm _)
    rw [Equiv.apply_symm_apply, Equiv.apply_symm_apply]
  exact ⟨_, ⟨Adjunction.adjunctionOfEquivRight e he⟩⟩

end Adjoint

end Brown

end DG
