import DG.Compact.Thick
import DG.K0.Compact

/-!
# Heart towers in triangulated categories

Let `C` be a pretriangulated category and `H` a property of objects of `C` which behaves like the
heart of a bounded t-structure (`DG.IsHeartFamily H`):

* `H` is closed under isomorphisms;
* `Hom(X, Y⟦k⟧) = 0` for `X, Y` in `H` and `k < 0`;
* the cone of a morphism `f : X ⟶ Y` between objects of `H` is an extension of an object of `H`
  by `K⟦1⟧` for some `K` in `H` (the triangulated shadow of `K = ker f`, `Q = coker f`);
* `H` is closed under extensions;
* idempotent endomorphisms of objects of `H` split, with image in `H`.

A *heart tower* of an object `X` (`DG.HeartTower H a X`) is a finite sequence of distinguished
triangles `Xⱼ₋₁ → Xⱼ → Yⱼ⟦bⱼ⟧ → Xⱼ₋₁⟦1⟧`, `X₀ = 0`, `Xₖ = X`, with `Yⱼ` in `H` and strictly
decreasing shifts `b₁ > b₂ > ⋯ > bₖ ≥ a`: the triangulated shadow of the filtration of an object
by the truncations of a bounded t-structure.

The main result (`DG.IsHeartFamily.isThick`) is that, in a triangulated category, the objects
with a heart tower form a thick subcategory: they are closed under shifts, extensions and direct
summands. In particular the thick closure of `H` consists of objects with heart towers, and the
Grothendieck group of a triangulated subcategory containing `H` and contained in the objects with
heart towers is generated by the classes of the objects of `H`
(`DG.HeartTower.mk_mem_closure`).

This generalizes `DG.IsOrderedCellFamily` (`DG/Compact/CellTower.lean`), where the objects of the
heart are semisimple (a Schur lemma holds for the cells), to hearts which are not semisimple, such
as the finitely generated modules over a principal ideal domain.

## Proofs

* Cones (`DG.IsHeartFamily.heartTower_cone`): by induction on a heart tower of the source, with
  the octahedral axiom, reduced to the cone of a morphism from a shifted object of `H` to an object
  with a heart tower (`DG.IsHeartFamily.heartTower_cone_cell`). Depending on the shift of the source
  compared with the bottom shift `b` of the tower, the new cell is placed at the bottom, combined
  with the bottom cell by the cone axiom for `H` (`kernel` and `cokernel`), or pushed into the rest
  of the tower. Two cells of the same shift are merged with the extension axiom.
* Direct summands (`DG.IsHeartFamily.heartTower_split`): every idempotent of an object with a heart
  tower splits, with image again with a heart tower. An idempotent `e` of `X`, with bottom triangle
  `X₁ → X → X₃ → X₁⟦1⟧`, induces idempotents `e₁` of `X₁` and `e₃` of `X₃` (there are no nonzero
  morphisms from `X₁` to `X₃⟦k⟧` for `k ≤ 0`); their images (by induction, and by the splitting
  axiom for `H`) are the outer terms of a triangle whose middle term `Y` is the image of an
  idempotent `q` of `X` inducing `e₁` and `e₃`. Then `n = e - q` factors as `X → X₃ → X₁ → X`, so
  `n x n = 0` for every `x` compatible with the triangle, and
  `u = q e + (1 - q)(1 - e) = 1 + n(2q - 1)` is invertible with `u q = e u` (composition read
  from right to left): `e` is conjugate to `q`.
-/

universe w v v' u u'

namespace DG

open CategoryTheory Limits Pretriangulated ZeroObject

variable {C : Type u} [Category.{v} C] [HasShift C ℤ]

/-! ### Shifted objects -/

/-- `X` is isomorphic to `Y⟦n⟧` for an object `Y` with the property `H`. -/
def ShiftedProp (H : ObjectProperty C) (n : ℤ) (X : C) : Prop :=
  ∃ Y : C, H Y ∧ Nonempty (X ≅ Y⟦n⟧)

namespace ShiftedProp

variable {H : ObjectProperty C}

theorem of_iso {n : ℤ} {X X' : C} (h : ShiftedProp H n X) (e : X ≅ X') : ShiftedProp H n X' :=
  let ⟨Y, hY, ⟨e'⟩⟩ := h
  ⟨Y, hY, ⟨e.symm ≪≫ e'⟩⟩

theorem shift {n : ℤ} {X : C} (h : ShiftedProp H n X) (k : ℤ) : ShiftedProp H (n + k) (X⟦k⟧) :=
  let ⟨Y, hY, ⟨e⟩⟩ := h
  ⟨Y, hY, ⟨(shiftFunctor C k).mapIso e ≪≫ ((shiftFunctorAdd' C n k (n + k) rfl).app Y).symm⟩⟩

theorem shift' {n : ℤ} {X : C} (h : ShiftedProp H n X) (k m : ℤ) (hm : n + k = m) :
    ShiftedProp H m (X⟦k⟧) := by
  subst hm
  exact h.shift k

theorem of_prop {X : C} (hX : H X) (n : ℤ) : ShiftedProp H n (X⟦n⟧) :=
  ⟨X, hX, ⟨Iso.refl _⟩⟩

theorem zero_iff [H.IsClosedUnderIsomorphisms] (X : C) : ShiftedProp H 0 X ↔ H X :=
  ⟨fun ⟨_, hY, ⟨e⟩⟩ => H.prop_of_iso (e ≪≫ (shiftFunctorZero C ℤ).app _).symm hY,
    fun h => ⟨X, h, ⟨((shiftFunctorZero C ℤ).app X).symm⟩⟩⟩

/-- Unshifting: `X⟦-n⟧` has the property `H`. -/
theorem prop_shift_neg [H.IsClosedUnderIsomorphisms] {n : ℤ} {X : C} (h : ShiftedProp H n X) :
    H (X⟦-n⟧) := by
  exact (zero_iff _).mp (h.shift' (-n) 0 (by omega))

end ShiftedProp

variable [HasZeroObject C] [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C]

/-- The axioms of a heart (of a bounded t-structure) for a property of objects of a
pretriangulated category; see the module docstring. -/
structure IsHeartFamily (H : ObjectProperty C) : Prop where
  /-- Closure under isomorphisms. -/
  prop_of_iso {X Y : C} : (X ≅ Y) → H X → H Y
  /-- There are no nonzero morphisms of negative degree between objects of `H`. -/
  hom_eq_zero {X Y : C} : H X → H Y → ∀ {k : ℤ}, k < 0 → ∀ f : X ⟶ Y⟦k⟧, f = 0
  /-- The cone of a morphism between objects of `H` is an extension of an object `Q` of `H` by
  `K⟦1⟧` with `K` in `H`. -/
  cone (T : Triangle C) : T ∈ distTriang C → H T.obj₁ → H T.obj₂ →
    ∃ (A B : C) (a : A ⟶ T.obj₃) (b : T.obj₃ ⟶ B) (c : B ⟶ A⟦(1 : ℤ)⟧),
      Triangle.mk a b c ∈ distTriang C ∧ ShiftedProp H 1 A ∧ H B
  /-- Closure under extensions. -/
  ext (T : Triangle C) : T ∈ distTriang C → H T.obj₁ → H T.obj₃ → H T.obj₂
  /-- Idempotents of objects of `H` split, with image in `H`. -/
  split {X : C} : H X → ∀ e : X ⟶ X, e ≫ e = e →
    ∃ (Y : C) (s : Y ⟶ X) (p : X ⟶ Y), H Y ∧ s ≫ p = 𝟙 Y ∧ p ≫ s = e

namespace IsHeartFamily

variable {H : ObjectProperty C} (hc : IsHeartFamily H)
include hc

theorem isClosedUnderIsomorphisms : H.IsClosedUnderIsomorphisms :=
  ⟨fun e h => hc.prop_of_iso e h⟩

/-- Morphisms from a shifted object of `H` to an object of `H` shifted less vanish. -/
theorem shifted_hom_eq_zero {m n : ℤ} {X Y : C} (hX : ShiftedProp H m X)
    (hY : ShiftedProp H n Y) (h : n < m) (f : X ⟶ Y) : f = 0 := by
  have := hc.isClosedUnderIsomorphisms
  obtain ⟨Y₀, hY₀, ⟨eY⟩⟩ := hY
  have hX' := hX.prop_shift_neg
  let e : Y⟦-m⟧ ≅ Y₀⟦n + -m⟧ :=
    (shiftFunctor C (-m)).mapIso eY ≪≫ ((shiftFunctorAdd' C n (-m) (n + -m) rfl).app Y₀).symm
  have h0 : f⟦-m⟧' ≫ e.hom = 0 := hc.hom_eq_zero hX' hY₀ (by omega) _
  have h1 : f⟦-m⟧' = 0 := by
    rw [← cancel_mono e.hom, h0, zero_comp]
  exact (shiftFunctor C (-m)).map_injective (by rw [h1, Functor.map_zero])

/-- Extensions of shifted objects of `H` (of the same shift). -/
theorem ext_shifted {m : ℤ} (T : Triangle C) (hT : T ∈ distTriang C)
    (h₁ : ShiftedProp H m T.obj₁) (h₃ : ShiftedProp H m T.obj₃) : ShiftedProp H m T.obj₂ := by
  have := hc.isClosedUnderIsomorphisms
  have h := hc.ext _ (Triangle.shift_distinguished T hT (-m)) h₁.prop_shift_neg
    h₃.prop_shift_neg
  exact ⟨_, h, ⟨(shiftNegShift T.obj₂ m).symm⟩⟩

/-- Idempotents of shifted objects of `H` split. -/
theorem split_shifted {m : ℤ} {X : C} (hX : ShiftedProp H m X) (e : X ⟶ X) (he : e ≫ e = e) :
    ∃ (Y : C) (s : Y ⟶ X) (p : X ⟶ Y), ShiftedProp H m Y ∧ s ≫ p = 𝟙 Y ∧ p ≫ s = e := by
  have := hc.isClosedUnderIsomorphisms
  obtain ⟨W, s', p', hW, hsp, hps⟩ := hc.split hX.prop_shift_neg (e⟦-m⟧')
    (by rw [← Functor.map_comp, he])
  let ε : X⟦-m⟧⟦m⟧ ≅ X := shiftNegShift X m
  refine ⟨W⟦m⟧, s'⟦m⟧' ≫ ε.hom, ε.inv ≫ p'⟦m⟧', ShiftedProp.of_prop hW m, ?_, ?_⟩
  · simp [← Functor.map_comp, hsp]
  · rw [Category.assoc, ← Functor.map_comp_assoc, hps]
    simp [ε]

/-- Cones of morphisms between shifted objects of `H` (of the same shift). -/
theorem cone_shifted {m : ℤ} (T : Triangle C) (hT : T ∈ distTriang C)
    (h₁ : ShiftedProp H m T.obj₁) (h₂ : ShiftedProp H m T.obj₂) :
    ∃ (A B : C) (a : A ⟶ T.obj₃) (b : T.obj₃ ⟶ B) (c : B ⟶ A⟦(1 : ℤ)⟧),
      Triangle.mk a b c ∈ distTriang C ∧ ShiftedProp H (m + 1) A ∧ ShiftedProp H m B := by
  have := hc.isClosedUnderIsomorphisms
  obtain ⟨A, B, a, b, c, hT', hA, hB⟩ := hc.cone _ (Triangle.shift_distinguished T hT (-m))
    h₁.prop_shift_neg h₂.prop_shift_neg
  let T'' := (Triangle.shiftFunctor C m).obj (Triangle.mk a b c)
  have hT'' : T'' ∈ distTriang C := Triangle.shift_distinguished _ hT' m
  obtain ⟨ε⟩ : Nonempty (T.obj₃⟦-m⟧⟦m⟧ ≅ T.obj₃) := ⟨shiftNegShift T.obj₃ m⟩
  refine ⟨T''.obj₁, T''.obj₃, T''.mor₁ ≫ ε.hom, ε.inv ≫ T''.mor₂, T''.mor₃, ?_,
    hA.shift' m (m + 1) (by omega), (ShiftedProp.of_prop hB m)⟩
  refine isomorphic_distinguished _ hT'' _ (Triangle.isoMk _ _ (Iso.refl _) ε.symm (Iso.refl _)
    (by dsimp; erw [Category.assoc, ε.hom_inv_id, Category.comp_id, Category.id_comp])
    (by dsimp; erw [Category.comp_id]; rfl) (by simp))

end IsHeartFamily

/-! ### Heart towers -/

variable (H : ObjectProperty C) in
/-- A *heart tower* of `X` with all shifts `≥ a`: `X` is zero, or sits in a distinguished
triangle `X₁ → X → X₃ → X₁⟦1⟧` with `X₃ ≅ Y⟦b⟧` (`Y` in `H`, `a ≤ b`) and `X₁` with a heart tower
whose shifts are `≥ b + 1`. -/
inductive HeartTower : ℤ → C → Prop
  /-- A zero object has the empty heart tower. -/
  | zero {a : ℤ} {X : C} : IsZero X → HeartTower a X
  /-- Extension by a bottom cell. -/
  | ext {a b : ℤ} (hab : a ≤ b) (T : Triangle C) (hT : T ∈ distTriang C)
      (h₁ : HeartTower (b + 1) T.obj₁) (h₃ : ShiftedProp H b T.obj₃) : HeartTower a T.obj₂

namespace HeartTower

variable {H : ObjectProperty C}

theorem of_iso {a : ℤ} {X Y : C} (h : HeartTower H a X) (e : X ≅ Y) : HeartTower H a Y := by
  cases h with
  | zero hX => exact .zero (hX.of_iso e.symm)
  | ext hab T hT h₁ h₃ =>
    refine .ext hab (Triangle.mk (T.mor₁ ≫ e.hom) (e.inv ≫ T.mor₂) T.mor₃) ?_ h₁ h₃
    exact isomorphic_distinguished T hT _
      (Triangle.isoMk _ _ (Iso.refl _) e.symm (Iso.refl _) (by simp) (by simp) (by simp))

theorem mono {a b : ℤ} {X : C} (h : HeartTower H b X) (hab : a ≤ b) : HeartTower H a X := by
  cases h with
  | zero hX => exact .zero hX
  | ext hb T hT h₁ h₃ => exact .ext (hab.trans hb) T hT h₁ h₃

/-- A shifted object of `H` has a heart tower with one cell. -/
theorem of_shiftedProp {b : ℤ} {X : C} (h : ShiftedProp H b X) : HeartTower H b X :=
  .ext le_rfl (Triangle.mk (0 : 0 ⟶ X) (𝟙 X) 0) (contractible_distinguished₁ X)
    (.zero (isZero_zero C)) h

theorem shift {a : ℤ} {X : C} (h : HeartTower H a X) (k : ℤ) : HeartTower H (a + k) (X⟦k⟧) := by
  induction h with
  | zero hX => exact .zero (Functor.map_isZero _ hX)
  | @ext a b hab T hT h₁ h₃ ih =>
    refine .ext (b := b + k) (by omega) ((Triangle.shiftFunctor C k).obj T)
      (Triangle.shift_distinguished T hT k) ?_ (h₃.shift k)
    have e : b + 1 + k = b + k + 1 := by omega
    exact e ▸ ih

/-- **`K₀`**: in a triangulated subcategory `P` containing the objects of `H`, the class of an
object with a heart tower lies in the subgroup generated by the classes of the objects of `H`. -/
theorem mk_mem_closure {P : ObjectProperty C} [P.IsTriangulated] [P.IsClosedUnderIsomorphisms]
    (hP : ∀ Y, H Y → P Y) {a : ℤ} {X : C} (hX : HeartTower H a X) :
    ∃ h : P X, K0.mk (⟨X, h⟩ : P.FullSubcategory) ∈ AddSubgroup.closure
      {x | ∃ (Y : C) (hY : H Y), x = K0.mk (⟨Y, hP Y hY⟩ : P.FullSubcategory)} := by
  induction hX with
  | zero hX0 =>
    refine ⟨P.prop_of_isZero hX0, ?_⟩
    rw [K0.mk_eq_zero_of_isZero ((IsZero.iff_id_eq_zero _).mpr (by
      ext
      exact hX0.eq_of_src _ _))]
    exact zero_mem _
  | @ext a b hab T hT h₁ h₃ ih =>
    obtain ⟨h₁P, h₁mem⟩ := ih
    obtain ⟨Y, hY, ⟨e⟩⟩ := h₃
    have h₃P : P T.obj₃ := P.prop_of_iso e.symm (P.le_shift b _ (hP Y hY))
    have h₂P : P T.obj₂ := P.ext_of_isTriangulatedClosed₂ T hT h₁P h₃P
    refine ⟨h₂P, ?_⟩
    rw [K0.mk_fullSubcategory_obj₂ T hT h₁P h₂P h₃P]
    refine add_mem h₁mem ?_
    have : K0.mk (⟨T.obj₃, h₃P⟩ : P.FullSubcategory) =
        b.negOnePow • K0.mk (⟨Y, hP Y hY⟩ : P.FullSubcategory) := by
      rw [← K0.mk_shift]
      exact K0.mk_eq_of_iso_obj
        (e ≪≫ ((P.ι.commShiftIso b).app (⟨Y, hP Y hY⟩ : P.FullSubcategory)).symm)
    rw [this, Units.smul_def]
    exact AddSubgroup.zsmul_mem _ (AddSubgroup.subset_closure (by exact ⟨Y, hY, rfl⟩)) _

end HeartTower

namespace IsHeartFamily

variable {H : ObjectProperty C} (hc : IsHeartFamily H)
include hc

/-- **Orthogonality**: there are no nonzero morphisms from an object with a heart tower with
shifts `≥ a` to a shifted object `Y⟦n⟧` of `H` with `n < a`. -/
theorem heartTower_hom_eq_zero {a : ℤ} {X : C} (h : HeartTower H a X) :
    ∀ {n : ℤ} {Y : C}, ShiftedProp H n Y → n < a → ∀ f : X ⟶ Y, f = 0 := by
  induction h with
  | zero hX => intro _ _ _ _ f; exact hX.eq_of_src _ _
  | @ext a b hab T hT h₁ h₃ ih =>
    intro n Y hY hn f
    have h0 : T.mor₁ ≫ f = 0 := ih hY (by omega) _
    obtain ⟨g, rfl⟩ := Triangle.yoneda_exact₂ T hT f h0
    rw [hc.shifted_hom_eq_zero h₃ hY (by omega) g, comp_zero]

variable [IsTriangulated C]

/-- **Merging** a bottom cell of shift `b` into an object with a heart tower with shifts
`≥ b`. -/
theorem heartTower_merge {b : ℤ} {X E K : C} (hX : HeartTower H b X) (f : X ⟶ E) (g : E ⟶ K)
    (h : K ⟶ X⟦(1 : ℤ)⟧) (hT : Triangle.mk f g h ∈ distTriang C) (hK : ShiftedProp H b K) :
    HeartTower H b E := by
  cases hX with
  | zero hX0 => exact .ext le_rfl _ hT (.zero hX0) hK
  | @ext _ b' hbb' T' hT' h₁ h₃ =>
    rcases hbb'.lt_or_eq with hlt | heq
    · exact .ext le_rfl _ hT (.ext (by omega) T' hT' h₁ h₃) hK
    · subst heq
      obtain ⟨Z, v, w, hZ⟩ := distinguished_cocone_triangle (T'.mor₁ ≫ f)
      let o := Triangulated.someOctahedron rfl hT' hT hZ
      exact .ext le_rfl _ hZ h₁ (hc.ext_shifted _ o.mem h₃ hK)

/-- **The cone of a cell** `Y⟦n⟧ ⟶ X`, `Y` in `H`, into an object with a heart tower with shifts
`≥ a` has a heart tower with shifts `≥ min a (n + 1)`. -/
theorem heartTower_cone_cell {a : ℤ} {X : C} (hX : HeartTower H a X) :
    ∀ {n : ℤ} {Y Z : C}, ShiftedProp H n Y → ∀ (c : Y ⟶ X) (v : X ⟶ Z) (w : Z ⟶ Y⟦(1 : ℤ)⟧),
      Triangle.mk c v w ∈ distTriang C → HeartTower H (min a (n + 1)) Z := by
  induction hX with
  | zero hX0 =>
    intro n Y Z hY c v w hT
    have : IsIso w := (Triangle.isZero₂_iff_isIso₃ _ hT).1 hX0
    exact (HeartTower.of_shiftedProp ((hY.shift 1).of_iso (asIso w).symm)).mono
      (min_le_right _ _)
  | @ext a b hab T hT' h₁ h₃ ih =>
    intro n Y Z hY c v w hT
    rcases lt_trichotomy n b with hnb | rfl | hnb
    · -- The new cell goes to the bottom.
      have hX : HeartTower H b T.obj₂ := .ext le_rfl T hT' h₁ h₃
      have hrot := rot_of_distTriang _ hT
      have hZ : HeartTower H (n + 1) Z := by
        rcases (show n + 1 < b ∨ n + 1 = b by omega) with h | h
        · exact .ext le_rfl _ hrot (hX.mono (by omega)) (hY.shift 1)
        · exact hc.heartTower_merge (hX.mono (by omega)) _ _ _ hrot (hY.shift 1)
      exact hZ.mono (min_le_right _ _)
    · -- The new cell has the shift of the bottom cell: cone axiom.
      obtain ⟨Z₃, v₃, w₃, h₃T⟩ := distinguished_cocone_triangle (c ≫ T.mor₂)
      let o := Triangulated.someOctahedron rfl hT (rot_of_distTriang _ hT') h₃T
      obtain ⟨A, B, a', b', c', hAB, hA, hB⟩ := hc.cone_shifted _ h₃T hY h₃
      obtain ⟨W, i, δ, hW⟩ := distinguished_cocone_triangle₁ (o.m₁ ≫ b')
      let o' := Triangulated.someOctahedron' rfl (inv_rot_of_distTriang _ o.mem) hAB hW
      have hF : HeartTower H (n + 1) (T.obj₁⟦(1 : ℤ)⟧⟦(-1 : ℤ)⟧) :=
        h₁.of_iso (shiftShiftNeg T.obj₁ (1 : ℤ)).symm
      have hW' : HeartTower H (n + 1) W := hc.heartTower_merge hF _ _ _ o'.mem hA
      exact .ext (by omega) _ hW hW' hB
    · -- The new cell is pushed into the rest of the tower.
      have h0 : c ≫ T.mor₂ = 0 := hc.shifted_hom_eq_zero hY h₃ hnb _
      obtain ⟨c₁, hc₁⟩ := Triangle.coyoneda_exact₂ T hT' c h0
      obtain ⟨Z₁, v₁, w₁, h₁T⟩ := distinguished_cocone_triangle c₁
      have hZ₁ : HeartTower H (b + 1) Z₁ := (ih hY c₁ v₁ w₁ h₁T).mono (le_min le_rfl (by omega))
      let o := Triangulated.someOctahedron hc₁.symm h₁T hT' hT
      exact .ext (by omega) _ o.mem hZ₁ h₃

/-- **Cones**: the cone of a morphism `X ⟶ Y` between objects with heart towers with shifts
`≥ a` and `≥ b` has a heart tower with shifts `≥ min b (a + 1)`. -/
theorem heartTower_cone {a : ℤ} {X : C} (hX : HeartTower H a X) :
    ∀ {b : ℤ} {Y Z : C}, HeartTower H b Y → ∀ (f : X ⟶ Y) (v : Y ⟶ Z) (w : Z ⟶ X⟦(1 : ℤ)⟧),
      Triangle.mk f v w ∈ distTriang C → HeartTower H (min b (a + 1)) Z := by
  induction hX with
  | zero hX0 =>
    intro b Y Z hY f v w hT
    have : IsIso v := (Triangle.isZero₁_iff_isIso₂ _ hT).1 hX0
    exact (hY.of_iso (asIso v)).mono (min_le_left _ _)
  | @ext a b' hab T hT' h₁ h₃ ih =>
    intro b Y Z hY f v w hT
    obtain ⟨Z'', v'', w'', h''⟩ := distinguished_cocone_triangle (T.mor₁ ≫ f)
    have hZ'' := ih hY (T.mor₁ ≫ f) v'' w'' h''
    let o := Triangulated.someOctahedron rfl hT' hT h''
    exact (hc.heartTower_cone_cell hZ'' h₃ o.m₁ o.m₃ _ o.mem).mono (by omega)

omit [IsTriangulated C] in
/-- **Splitting of idempotents**: every idempotent endomorphism `e` of an object with a heart
tower with shifts `≥ a` splits, through an object with a heart tower with shifts `≥ a`. -/
theorem heartTower_split {a : ℤ} {X : C} (hX : HeartTower H a X) :
    ∀ e : X ⟶ X, e ≫ e = e →
      ∃ (Y : C) (s : Y ⟶ X) (p : X ⟶ Y), HeartTower H a Y ∧ s ≫ p = 𝟙 Y ∧ p ≫ s = e := by
  induction hX with
  | zero hX0 =>
    intro e _
    exact ⟨_, 𝟙 _, 𝟙 _, .zero hX0, by simp, hX0.eq_of_src _ _⟩
  | @ext a b hab T hT h₁ h₃ ih =>
    intro e he
    -- Orthogonality between the bottom cell and the rest of the tower.
    have O₁ : ∀ f : T.obj₁ ⟶ T.obj₃, f = 0 := fun f =>
      hc.heartTower_hom_eq_zero h₁ h₃ (by omega) f
    have O₂ : ∀ f : T.obj₁ ⟶ T.obj₃⟦(-1 : ℤ)⟧, f = 0 := fun f =>
      hc.heartTower_hom_eq_zero h₁ (h₃.shift (-1)) (by omega) f
    have O₃ : ∀ f : T.obj₁⟦(1 : ℤ)⟧ ⟶ T.obj₃, f = 0 := fun f =>
      hc.heartTower_hom_eq_zero (h₁.shift 1) h₃ (by omega) f
    have U₁ : ∀ x y : T.obj₁ ⟶ T.obj₁, x ≫ T.mor₁ = y ≫ T.mor₁ → x = y := by
      intro x y hxy
      rw [← sub_eq_zero] at hxy ⊢
      rw [← Preadditive.sub_comp] at hxy
      obtain ⟨g, hg⟩ := Triangle.coyoneda_exact₂ _ (inv_rot_of_distTriang T hT) (x - y) hxy
      obtain rfl : g = 0 := O₂ g
      rw [hg]
      exact zero_comp
    have U₃ : ∀ x y : T.obj₃ ⟶ T.obj₃, T.mor₂ ≫ x = T.mor₂ ≫ y → x = y := by
      intro x y hxy
      rw [← sub_eq_zero] at hxy ⊢
      rw [← Preadditive.comp_sub] at hxy
      obtain ⟨g, hg⟩ := Triangle.yoneda_exact₃ T hT (x - y) hxy
      obtain rfl : g = 0 := O₃ g
      rw [hg]
      exact comp_zero
    -- The induced idempotents of the outer terms.
    obtain ⟨e₁, he₁⟩ := Triangle.coyoneda_exact₂ T hT (T.mor₁ ≫ e)
      (by rw [Category.assoc]; exact O₁ _)
    obtain ⟨e₃, he₃⟩ := Triangle.yoneda_exact₂ T hT (e ≫ T.mor₂)
      (by rw [← Category.assoc, he₁, Category.assoc, comp_distTriang_mor_zero₁₂ _ hT, comp_zero])
    have he₁' : e₁ ≫ e₁ = e₁ := U₁ _ _ (by
      rw [Category.assoc, ← he₁, ← Category.assoc, ← he₁, Category.assoc, he, he₁])
    have he₃' : e₃ ≫ e₃ = e₃ := U₃ _ _ (by
      rw [← Category.assoc, ← he₃, Category.assoc, ← he₃, ← Category.assoc, he])
    have hδ : T.mor₃ ≫ e₁⟦(1 : ℤ)⟧' = e₃ ≫ T.mor₃ := by
      obtain ⟨c, hc₁, hc₂⟩ := complete_distinguished_triangle_morphism T T hT hT e₁ e he₁
      rw [hc₂, U₃ c e₃ (by rw [hc₁, he₃])]
    -- Their images.
    obtain ⟨Y₁, s₁, p₁, hY₁, hsp₁, hps₁⟩ := ih e₁ he₁'
    obtain ⟨Y₃, s₃, p₃, hY₃, hsp₃, hps₃⟩ := hc.split_shifted h₃ e₃ he₃'
    have hs₃ : s₃ ≫ e₃ = s₃ := by rw [← hps₃, ← Category.assoc, hsp₃, Category.id_comp]
    have hp₁ : e₁ ≫ p₁ = p₁ := by rw [← hps₁, Category.assoc, hsp₁, Category.comp_id]
    obtain ⟨Y, iY, πY, hTY⟩ := distinguished_cocone_triangle₂ (s₃ ≫ T.mor₃ ≫ p₁⟦(1 : ℤ)⟧')
    obtain ⟨s, hs₁, hs₂⟩ := complete_distinguished_triangle_morphism₂ _ _ hTY hT s₁ s₃ (by
      dsimp
      rw [Category.assoc, Category.assoc, ← Functor.map_comp, hps₁, hδ, ← Category.assoc, hs₃])
    obtain ⟨p, hp₁', hp₂'⟩ := complete_distinguished_triangle_morphism₂ _ _ hT hTY p₁ p₃ (by
      dsimp
      rw [← Category.assoc, ← Category.assoc, hps₃, ← hδ, Category.assoc, ← Functor.map_comp, hp₁])
    dsimp at hs₁ hs₂ hp₁' hp₂'
    -- `s ≫ p` is an automorphism of `Y` inducing the identity on the outer terms.
    have hψ₁ : iY ≫ s ≫ p = iY := by
      rw [reassoc_of% hs₁, hp₁', reassoc_of% hsp₁]
    have hψ₂ : (s ≫ p) ≫ πY = πY := by
      rw [Category.assoc, ← hp₂', ← reassoc_of% hs₂, hsp₃, Category.comp_id]
    have hψ : IsIso (s ≫ p) := by
      let φ : Triangle.mk iY πY (s₃ ≫ T.mor₃ ≫ p₁⟦(1 : ℤ)⟧') ⟶
          Triangle.mk iY πY (s₃ ≫ T.mor₃ ≫ p₁⟦(1 : ℤ)⟧') :=
        { hom₁ := 𝟙 _
          hom₂ := s ≫ p
          hom₃ := 𝟙 _
          comm₁ := by dsimp; rw [hψ₁, Category.id_comp]
          comm₂ := by dsimp; rw [hψ₂, Category.comp_id]
          comm₃ := by simp }
      exact isIso₂_of_isIso₁₃ φ hTY hTY (by change IsIso (𝟙 _); infer_instance)
        (by change IsIso (𝟙 _); infer_instance)
    have hiY : iY ≫ inv (s ≫ p) = iY := by
      rw [IsIso.comp_inv_eq, hψ₁]
    have hπY : inv (s ≫ p) ≫ πY = πY := by
      rw [IsIso.inv_comp_eq, hψ₂]
    have hsq : s ≫ p ≫ inv (s ≫ p) = 𝟙 Y := by
      exact (Category.assoc _ _ _).symm.trans (IsIso.hom_inv_id (s ≫ p))
    -- The idempotent `q` with image `Y`, inducing `e₁` and `e₃`.
    obtain ⟨q, hqdef⟩ : ∃ q : T.obj₂ ⟶ T.obj₂, q = p ≫ inv (s ≫ p) ≫ s := ⟨_, rfl⟩
    have hq : q ≫ q = q := by
      rw [hqdef]
      simp only [Category.assoc]
      erw [reassoc_of% hsq, Category.id_comp]
    have hq₁ : T.mor₁ ≫ q = e₁ ≫ T.mor₁ := by
      rw [hqdef, reassoc_of% hp₁', reassoc_of% hiY, hs₁, ← Category.assoc, hps₁]
    have hq₂ : q ≫ T.mor₂ = T.mor₂ ≫ e₃ := by
      rw [hqdef, Category.assoc, Category.assoc, ← hs₂, reassoc_of% hπY, ← reassoc_of% hp₂', hps₃]
    -- `n = e - q` factors through `T.obj₃ ⟶ T.obj₁`.
    have hn₁ : T.mor₁ ≫ (e - q) = 0 := by
      rw [Preadditive.comp_sub, he₁, hq₁, sub_self]
    have hn₂ : (e - q) ≫ T.mor₂ = 0 := by
      rw [Preadditive.sub_comp, he₃, hq₂, sub_self]
    obtain ⟨h', hh'⟩ := Triangle.yoneda_exact₂ T hT (e - q) hn₁
    have hh'₂ : h' ≫ T.mor₂ = 0 := U₃ _ 0 (by rw [← Category.assoc, ← hh', hn₂, comp_zero])
    obtain ⟨h, rfl⟩ := Triangle.coyoneda_exact₂ T hT h' hh'₂
    have key : ∀ (x : T.obj₂ ⟶ T.obj₂) (x₁ : T.obj₁ ⟶ T.obj₁), T.mor₁ ≫ x = x₁ ≫ T.mor₁ →
        (e - q) ≫ x ≫ (e - q) = 0 := by
      intro x x₁ hx
      rw [hh']
      simp only [Category.assoc]
      rw [reassoc_of% hx, comp_distTriang_mor_zero₁₂_assoc _ hT]
      simp
    -- `u = q ≫ e + (1 - q) ≫ (1 - e)` is an automorphism conjugating `q` to `e`.
    obtain ⟨m, hmdef⟩ : ∃ m : T.obj₂ ⟶ T.obj₂, m = (q + q - 𝟙 _) ≫ (e - q) := ⟨_, rfl⟩
    have hm : m ≫ m = 0 := by
      rw [hmdef, Category.assoc, key _ (e₁ + e₁ - 𝟙 _) (by
        simp only [Preadditive.comp_add, Preadditive.comp_sub, Preadditive.add_comp,
          Preadditive.sub_comp, hq₁, Category.comp_id, Category.id_comp]), comp_zero]
    obtain ⟨u, hudef⟩ : ∃ u : T.obj₂ ⟶ T.obj₂, u = q ≫ e + (𝟙 _ - q) ≫ (𝟙 _ - e) := ⟨_, rfl⟩
    have hu : u = 𝟙 _ + m := by
      rw [hudef, hmdef]
      simp only [Preadditive.add_comp, Preadditive.comp_sub,
        Preadditive.sub_comp, Category.comp_id, Category.id_comp, hq]
      abel
    have huinv : IsIso u := by
      refine ⟨⟨𝟙 _ - m, ?_, ?_⟩⟩
      · rw [hu, Preadditive.add_comp, Preadditive.comp_sub, Preadditive.comp_sub, hm]
        simp
      · rw [hu, Preadditive.sub_comp, Preadditive.comp_add, Preadditive.comp_add, hm]
        simp
    have hqu : q ≫ u = u ≫ e := by
      rw [hudef]
      simp only [Preadditive.comp_add, Preadditive.add_comp, Preadditive.comp_sub,
        Preadditive.sub_comp, Category.comp_id, Category.id_comp, Category.assoc, he,
        reassoc_of% hq, hq]
      abel
    refine ⟨Y, s ≫ u, inv u ≫ p ≫ inv (s ≫ p), .ext hab _ hTY hY₁ hY₃, ?_, ?_⟩
    · rw [Category.assoc, IsIso.hom_inv_id_assoc, hsq]
    · calc (inv u ≫ p ≫ inv (s ≫ p)) ≫ s ≫ u = inv u ≫ q ≫ u := by
            rw [hqdef]; simp only [Category.assoc]
        _ = e := by rw [hqu, IsIso.inv_hom_id_assoc]

omit [IsTriangulated C] in
/-- Direct summands of objects with heart towers have heart towers. -/
theorem heartTower_of_retract {a : ℤ} {X Y : C} (r : Retract Y X) (hX : HeartTower H a X) :
    HeartTower H a Y := by
  obtain ⟨Y₀, s, p, hY₀, hsp, hps⟩ := hc.heartTower_split hX (r.r ≫ r.i) (by
    simp only [Category.assoc, r.retract_assoc])
  refine hY₀.of_iso ⟨s ≫ r.r, r.i ≫ p, ?_, ?_⟩
  · calc (s ≫ r.r) ≫ r.i ≫ p = s ≫ (r.r ≫ r.i) ≫ p := by simp only [Category.assoc]
      _ = s ≫ (p ≫ s) ≫ p := by rw [hps]
      _ = 𝟙 _ := by simp only [Category.assoc]; rw [reassoc_of% hsp, hsp]
  · calc (r.i ≫ p) ≫ s ≫ r.r = r.i ≫ (p ≫ s) ≫ r.r := by simp only [Category.assoc]
      _ = r.i ≫ (r.r ≫ r.i) ≫ r.r := by rw [hps]
      _ = 𝟙 _ := by simp only [Category.assoc]; rw [r.retract_assoc, r.retract]

/-- The objects with a heart tower. -/
def HasHeartTower (H : ObjectProperty C) (X : C) : Prop := ∃ a : ℤ, HeartTower H a X

/-- **Thickness**: in a triangulated category, the objects with a heart tower for a heart family
form a thick subcategory. -/
theorem isThick : IsThick (HasHeartTower H) where
  zero := ⟨0, .zero (isZero_zero C)⟩
  shift X n h := let ⟨a, ha⟩ := h; ⟨a + n, ha.shift n⟩
  ext₂ T hT h₁ h₃ := by
    obtain ⟨a, ha⟩ := h₁
    obtain ⟨c, hc₃⟩ := h₃
    exact ⟨_, hc.heartTower_cone (hc₃.shift (-1)) ha _ _ _ (inv_rot_of_distTriang T hT)⟩
  retract r h := let ⟨a, ha⟩ := h; ⟨a, hc.heartTower_of_retract r ha⟩

/-- The thick closure of the objects of `H` consists of objects with heart towers. -/
theorem thickClosure_le : ThickClosure H ≤ HasHeartTower H :=
  DG.thickClosure_le hc.isThick fun X hX =>
    have := hc.isClosedUnderIsomorphisms
    ⟨0, HeartTower.of_shiftedProp ((ShiftedProp.zero_iff X).mpr hX)⟩

end IsHeartFamily

/-! ### Transport along a triangulated functor -/

section Transport

variable {D : Type u'} [Category.{v'} D] [HasZeroObject D] [HasShift D ℤ] [Preadditive D]
  [∀ n : ℤ, (shiftFunctor D n).Additive] [Pretriangulated D]
  (F : D ⥤ C) [F.CommShift ℤ] [F.IsTriangulated]

/-- The objects of `C` isomorphic to `F.obj A` for an object `A` of `D` with the property `𝒜`. -/
def mapHeart (𝒜 : ObjectProperty D) : ObjectProperty C :=
  fun X => ∃ A : D, 𝒜 A ∧ Nonempty (X ≅ F.obj A)

variable {F} in
/-- **Transport of a heart family** along a triangulated functor `F` which is fully faithful on
the heart, has no morphisms of negative degree between images of the heart, and is surjective on
morphisms of degree one between images of the heart (so that extensions of images are images of
extensions). -/
theorem IsHeartFamily.map {𝒜 : ObjectProperty D} (h𝒜 : IsHeartFamily 𝒜)
    (full : ∀ {A B : D}, 𝒜 A → 𝒜 B → ∀ g : F.obj A ⟶ F.obj B, ∃ f : A ⟶ B, F.map f = g)
    (faithful : ∀ {A B : D}, 𝒜 A → 𝒜 B → ∀ f f' : A ⟶ B, F.map f = F.map f' → f = f')
    (neg : ∀ {A B : D}, 𝒜 A → 𝒜 B → ∀ {k : ℤ}, k < 0 → ∀ g : F.obj A ⟶ (F.obj B)⟦k⟧, g = 0)
    (one : ∀ {A B : D}, 𝒜 A → 𝒜 B → ∀ g : F.obj A ⟶ (F.obj B)⟦(1 : ℤ)⟧,
      ∃ f : A ⟶ B⟦(1 : ℤ)⟧, F.map f ≫ (F.commShiftIso (1 : ℤ)).hom.app B = g) :
    IsHeartFamily (mapHeart F 𝒜) where
  prop_of_iso e := fun ⟨A, hA, ⟨e'⟩⟩ => ⟨A, hA, ⟨e.symm ≪≫ e'⟩⟩
  hom_eq_zero := by
    rintro X Y ⟨A, hA, ⟨eX⟩⟩ ⟨B, hB, ⟨eY⟩⟩ k hk f
    have h0 := neg hA hB hk (eX.inv ≫ f ≫ eY.hom⟦k⟧')
    have hf : f = eX.hom ≫ (eX.inv ≫ f ≫ eY.hom⟦k⟧') ≫ eY.inv⟦k⟧' := by
      simp [← Functor.map_comp]
    rw [hf, h0, zero_comp, comp_zero]
  cone := by
    rintro T hT ⟨A, hA, ⟨e₁⟩⟩ ⟨B, hB, ⟨e₂⟩⟩
    obtain ⟨f, hf⟩ := full hA hB (e₁.inv ≫ T.mor₁ ≫ e₂.hom)
    obtain ⟨Z, v, w, hZ⟩ := distinguished_cocone_triangle f
    obtain ⟨A', B', a, b, c, habc, hA', hB'⟩ := h𝒜.cone _ hZ hA hB
    obtain ⟨e, -, -⟩ := exists_iso_of_arrow_iso _ _ hT (F.map_distinguished _ hZ)
      (Arrow.isoMk e₁ e₂ (by simp [hf]))
    let e₃ : T.obj₃ ≅ F.obj Z := Triangle.π₃.mapIso e
    refine ⟨F.obj A', F.obj B', F.map a ≫ e₃.inv, e₃.hom ≫ F.map b,
      F.map c ≫ (F.commShiftIso (1 : ℤ)).hom.app A', ?_, ?_, ⟨B', hB', ⟨Iso.refl _⟩⟩⟩
    · refine isomorphic_distinguished _ (F.map_distinguished _ habc) _
        (Triangle.isoMk _ _ (Iso.refl _) e₃ (Iso.refl _) (by simp) (by simp) (by simp))
    · obtain ⟨K, hK, ⟨eK⟩⟩ := hA'
      exact ⟨F.obj K, ⟨K, hK, ⟨Iso.refl _⟩⟩,
        ⟨F.mapIso eK ≪≫ (F.commShiftIso (1 : ℤ)).app K⟩⟩
  ext := by
    rintro T hT ⟨A, hA, ⟨e₁⟩⟩ ⟨B, hB, ⟨e₃⟩⟩
    obtain ⟨δ, hδ⟩ := one hB hA (e₃.inv ≫ T.mor₃ ≫ e₁.hom⟦(1 : ℤ)⟧')
    obtain ⟨E, u, v, hE⟩ := distinguished_cocone_triangle₂ δ
    let e := isoTriangleOfIso₁₃ T (F.mapTriangle.obj (Triangle.mk u v δ)) hT
      (F.map_distinguished _ hE) e₁ e₃ (by
        dsimp
        rw [hδ]
        simp)
    exact ⟨E, h𝒜.ext _ hE hA hB, ⟨Triangle.π₂.mapIso e⟩⟩
  split := by
    rintro X ⟨A, hA, ⟨eX⟩⟩ e he
    obtain ⟨e₀, he₀⟩ := full hA hA (eX.inv ≫ e ≫ eX.hom)
    have he₀' : e₀ ≫ e₀ = e₀ := faithful hA hA _ _ (by
      rw [F.map_comp, he₀]
      simp [reassoc_of% he])
    obtain ⟨Y, s, p, hY, hsp, hps⟩ := h𝒜.split hA e₀ he₀'
    refine ⟨F.obj Y, F.map s ≫ eX.inv, eX.hom ≫ F.map p, ⟨Y, hY, ⟨Iso.refl _⟩⟩, ?_, ?_⟩
    · simp [← F.map_comp, hsp]
    · rw [Category.assoc, ← F.map_comp_assoc, hps, he₀]
      simp

end Transport

end DG
