import DG.Derived.IntegralHeart
import DG.Derived.PerfectCompact
import DG.Derived.ExternalTensorOver
import DG.Category.Derived.ExtendScalars
import DG.Module.HomAction
import DG.Homotopy.HomShift
import DG.K0.ProjectiveRank

/-!
# `K₀` of dg rings whose low-degree cohomology is that of `ℤ`

Let `A` be a dg ring such that `Hⁿ(A) = 0` for `n < 0` and for `n = 1`, `H⁰(A) ≅ ℤ`, and `H²(A)`
is torsion-free (`DG.DGRing.K0.IntegralLowDegree`; for instance `A` concentrated in non-negative
degrees with `A⁰ = ℤ · 1`, `DG.IsConnectedInt`, `H¹(A) = 0` and `H²(A)` torsion-free). Then every
compact object of `D(A)` has a heart tower whose cells are the derived inductions of shifted finitely
generated abelian groups along `ℤ → A`, and the Grothendieck group `K₀(A)` of compact objects is
generated by the class `[A]` (`DG.DGRing.K0.exists_eq_zsmul_self`). If moreover `A` has a morphism
of dg rings to `ℤ` (an augmentation, e.g. `DG.IsConnectedInt.augmentation`), then `K₀(A) ≃ ℤ` with
`[A] ↦ 1` (`DG.DGRing.K0.equivIntOfAugmentation`, `DG.DGRing.K0.equivIntOfIsConnectedInt`).

This is an integral counterpart of `K₀(A) ≅ K₀(A⁰)` for positive dg rings (`A⁰` semisimple,
`DG.IsPositive`), which does not apply when `A⁰ = ℤ`. The proof applies
`DG.IntegralHeart.exists_eq_zsmul` (`DG/Derived/IntegralHeart.lean`) to the triangulated functor
`D(Mod ℤ) ≌ D(ℤ) ⥤ D(A)` (Mathlib's derived category of abelian groups, the comparison equivalence
`DG.DegreeZero.derivedComparisonEquivalence`, and derived induction along the unit `ℤ → A`), which
sends `ℤ` in degree `0` to `A` (`DG.DGRingHom.derivedInductionSelfIso`). Its hypotheses are read
off `Hom_{D(A)}(A, A⟦n⟧) ≅ Hⁿ(A)` (`DG.DerivedCategory.homSelfShiftAddEquiv`), and `End(A)` is
generated by the identity because it is a ring whose additive group is infinite cyclic
(`DG.isUnit_of_addEquiv_int`).

## Main results

* `DG.DerivedCategory.homShiftAddEquivOfIsKProjective`: `Hom_{D(A)}(P, N⟦n⟧) ≃+ Hⁿ(HOM_A(P, N))`
  for a K-projective `P`; `DG.DerivedCategory.homSelfShiftAddEquiv`: `Hom(A, A⟦n⟧) ≃+ Hⁿ(A)`.
* `DG.DGRingHom.extendScalarsSelfEquiv`, `DG.DGRingHom.derivedInductionSelfIso`: `A ⊗_B B ≅ A`
  and `φ^*(B) ≅ A` for a morphism of dg rings `φ : B → A`.
* `DG.DegreeZero.intHom A : ℤ →ᵈᵍ+* A`, the unit.
* `DG.IsConnectedInt`, `DG.IsConnectedInt.cohomologyZeroEquiv` (`H⁰(A) ≃ ℤ`),
  `DG.IsConnectedInt.augmentation` (`A → ℤ`, `a ↦ a₀`).
* `DG.DGRing.K0.exists_eq_zsmul_self`, `DG.DGRing.K0.equivIntOfAugmentation`,
  `DG.DGRing.K0.equivIntOfIsConnectedInt`.
-/

universe w v u

open CategoryTheory Limits Pretriangulated DirectSum

namespace DG

/-! ### Cohomology along isomorphisms of dg modules -/

section CohomologyEquiv

variable {A : Type*} [Ring A] [DGAddCommGroup A] {M N : Type*} [AddCommGroup M]
  [DGAddCommGroup M] [Module A M] [AddCommGroup N] [DGAddCommGroup N] [Module A N]

/-- An isomorphism of dg modules induces isomorphisms on cohomology. -/
noncomputable def DGModuleEquiv.cohomologyAddEquiv (e : M ≃ᵈᵍ[A] N) (n : ℤ) :
    cohomology M n ≃+ cohomology N n where
  toFun := cohomology.map e.toDGModuleHom n
  invFun := cohomology.map e.symm.toDGModuleHom n
  left_inv x := by
    rw [← cohomology.map_comp_apply]
    induction x using cohomology.induction_on with
    | h z =>
      rw [cohomology.map_mk]
      congr 1
      exact Subtype.ext (e.symm_apply_apply _)
  right_inv x := by
    rw [← cohomology.map_comp_apply]
    induction x using cohomology.induction_on with
    | h z =>
      rw [cohomology.map_mk]
      congr 1
      exact Subtype.ext (e.apply_symm_apply _)
  map_add' := map_add _

end CohomologyEquiv

/-! ### Morphisms out of K-projective modules -/

namespace DerivedCategory

variable {A : Type u} [Ring A] [DGAddCommGroup A] [DGRing A] [HasDerivedCategory.{w, v} A]

/-- For `P` K-projective, `Hom_{D(A)}(Q P, (Q N)⟦n⟧) ≃+ Hⁿ(HOM_A(P, N))`: the derived Hom
complex out of `P` is computed by the dg Hom complex. -/
noncomputable def homShiftAddEquivOfIsKProjective {P : DGModuleCat.{v} A}
    (hP : IsKProjective.{v} A P) (N : DGModuleCat.{v} A) (n : ℤ) :
    (Q.obj P ⟶ (Q.obj N)⟦n⟧) ≃+ cohomology (DGModule.HOM A P N) n :=
  let Y := ((HomotopyCategory.quotient A).obj N)⟦n⟧
  let e : Qh.obj Y ≅ (Q.obj N)⟦n⟧ := (Qh.commShiftIso n).app ((HomotopyCategory.quotient A).obj N)
  let c : (Qh.obj ((HomotopyCategory.quotient A).obj P) ⟶ Qh.obj Y) ≃+
      (Qh.obj ((HomotopyCategory.quotient A).obj P) ⟶ (Q.obj N)⟦n⟧) :=
    { toFun := fun f => f ≫ e.hom
      invFun := fun g => g ≫ e.inv
      left_inv := fun f => by simp
      right_inv := fun g => by simp
      map_add' := fun f g => Preadditive.add_comp _ _ _ _ _ _ }
  ((AddEquiv.ofBijective (Qh.mapAddHom (X := (HomotopyCategory.quotient A).obj P) (Y := Y))
      (Qh_map_bijective_of_isKProjective hP Y)).trans c).symm.trans
    (HomotopyCategory.homShiftAddEquivCohomology P N n)

open scoped DGModule.HOM.LeftAction in
/-- `Hom_{D(A)}(A, A⟦n⟧) ≃+ Hⁿ(A)`. -/
noncomputable def homSelfShiftAddEquiv [HasDerivedCategory.{w, u} A] (n : ℤ) :
    (Q.obj (DGModuleCat.of A A) ⟶ (Q.obj (DGModuleCat.of A A))⟦n⟧) ≃+ cohomology A n :=
  (homShiftAddEquivOfIsKProjective (isKProjective_self.{u} A) (DGModuleCat.of A A) n).trans
    ((DGModule.HOM.evalOneEquiv (A := A) (P := A)).cohomologyAddEquiv n)

end DerivedCategory

/-! ### `A ⊗_B B ≅ A` -/

namespace DGRingHom

variable {A B : Type u} [Ring A] [DGAddCommGroup A] [DGRing A] [Ring B] [DGAddCommGroup B]
  [DGRing B] (φ : B →ᵈᵍ+* A)

open TensorProductOver in
/-- `A ⊗_B B ≅ A` as dg `A`-modules, `x ⊗ b ↦ x φ(b)`. -/
noncomputable def extendScalarsSelfEquiv : TensorProductOver B φ.Bimodule B ≃ᵈᵍ[A] A where
  toFun y := φ.bimoduleEquiv.symm (rid B φ.Bimodule y)
  invFun a := (rid B φ.Bimodule).symm (φ.bimoduleEquiv a)
  left_inv y := by simp
  right_inv a := by simp
  map_add' y y' := by simp
  map_smul' a y := by
    induction y using TensorProductOver.induction_on with
    | zero => simp
    | tmul x b =>
      rw [smul_tmul, rid_tmul, rid_tmul]
      exact (smul_comm a (MulOpposite.op b) x).symm
    | add y y' hy hy' => simp only [smul_add, map_add, hy, hy']
  map_mem' hm := (rid B φ.Bimodule).map_mem hm
  map_d' y := (rid B φ.Bimodule).map_d y

variable [CatModule.HasDerivedCategory.{w, u} (SingleObj B)]
  [CatModule.HasDerivedCategory.{w, u} (SingleObj A)]
  [DG.HasDerivedCategory.{v, u} B] [DG.HasDerivedCategory.{v, u} A]

/-- **Derived induction of the regular module**: `φ^*(B) ≅ A` in `D(A)`. -/
noncomputable def derivedInductionSelfIso :
    φ.derivedInduction.obj (DerivedCategory.Q.obj (DGModuleCat.of B B)) ≅
      DerivedCategory.Q.obj (DGModuleCat.of A A) :=
  φ.derivedInductionObjIso (isKProjective_self.{u} B) ≪≫
    DerivedCategory.Q.mapIso (extendScalarsSelfEquiv φ).toDGModuleCatIso

end DGRingHom

/-! ### The unit `ℤ → A` -/

namespace DegreeZero

theorem intCast_mem_grading_zero (A : Type*) [Ring A] [DGAddCommGroup A] [DGRing A] (z : ℤ) :
    (z : A) ∈ grading (M := A) 0 := by
  rw [← zsmul_one]
  exact AddSubgroup.zsmul_mem _ one_mem_grading z

/-- The unit `ℤ → A` of a dg ring, `ℤ` concentrated in degree `0` (the scoped dg ring structure
`DG.DegreeZero.instDGRing`). -/
def intHom (A : Type*) [Ring A] [DGAddCommGroup A] [DGRing A] : ℤ →ᵈᵍ+* A where
  toFun z := (z : A)
  map_one' := Int.cast_one
  map_mul' := Int.cast_mul
  map_zero' := Int.cast_zero
  map_add' := Int.cast_add
  map_mem' {n} {z} hz := by
    rcases (mem_grading_iff (R := ℤ)).mp hz with rfl | rfl
    · exact intCast_mem_grading_zero A z
    · rw [Int.cast_zero]
      exact zero_mem _
  map_d' z := by
    rw [d_apply, Int.cast_zero]
    exact (d_intCast z).symm

end DegreeZero

/-! ### Connected dg rings -/

/-- `A` is *connected over `ℤ`*: concentrated in non-negative degrees, with `A⁰ = ℤ · 1` and
`ℤ → A` injective. -/
structure IsConnectedInt (A : Type*) [Ring A] [DGAddCommGroup A] [DGRing A] : Prop where
  grading_neg : ∀ n : ℤ, n < 0 → grading (M := A) n = ⊥
  exists_intCast : ∀ a ∈ grading (M := A) 0, ∃ z : ℤ, (z : A) = a
  intCast_injective : Function.Injective (Int.cast : ℤ → A)

namespace IsConnectedInt

variable {A : Type*} [Ring A] [DGAddCommGroup A] [DGRing A] (hA : IsConnectedInt A)
include hA

theorem eq_zero_of_mem_neg {n : ℤ} (hn : n < 0) {a : A} (ha : a ∈ grading n) : a = 0 := by
  rwa [hA.grading_neg n hn, AddSubgroup.mem_bot] at ha

theorem cohomology_neg {n : ℤ} (hn : n < 0) (x : cohomology A n) : x = 0 := by
  induction x using cohomology.induction_on with
  | h z =>
    rw [show z = 0 from Subtype.ext (hA.eq_zero_of_mem_neg hn (cocycles.mem_grading z)), map_zero]

omit hA in
/-- The integers as degree-`0` cocycles. -/
def intCocycles (A : Type*) [Ring A] [DGAddCommGroup A] [DGRing A] : ℤ →+ cocycles A 0 where
  toFun z := ⟨(z : A), mem_cocycles.mpr ⟨DegreeZero.intCast_mem_grading_zero A z, d_intCast z⟩⟩
  map_zero' := Subtype.ext Int.cast_zero
  map_add' z z' := Subtype.ext (Int.cast_add z z')

/-- `H⁰(A) ≃ ℤ`. -/
noncomputable def cohomologyZeroEquiv : cohomology A 0 ≃+ ℤ :=
  (AddEquiv.ofBijective ((cohomology.mk A 0).comp (intCocycles A)) ⟨fun z z' h => by
      rw [← sub_eq_zero, ← map_sub, AddMonoidHom.comp_apply, cohomology.mk_eq_zero_iff] at h
      obtain ⟨b, hb, hdb⟩ := mem_coboundaries.mp h
      rw [hA.eq_zero_of_mem_neg (by omega) hb, d_zero] at hdb
      have : ((z - z' : ℤ) : A) = 0 := hdb.symm
      exact sub_eq_zero.mp (hA.intCast_injective (by rw [this, Int.cast_zero])),
    fun x => by
      induction x using cohomology.induction_on with
      | h w =>
        obtain ⟨z, hz⟩ := hA.exists_intCast _ (cocycles.mem_grading w)
        exact ⟨z, by rw [AddMonoidHom.comp_apply]; congr 1; exact Subtype.ext hz⟩⟩).symm

/-- The integer `z` with `z · 1 = a₀`, the degree-`0` component of `a`. -/
noncomputable def toInt (a : A) : ℤ :=
  (hA.exists_intCast _ (decompose (grading (M := A)) a 0).2).choose

theorem toInt_spec (a : A) : ((hA.toInt a : ℤ) : A) = decompose (grading (M := A)) a 0 :=
  (hA.exists_intCast _ (decompose (grading (M := A)) a 0).2).choose_spec

open DegreeZero in
/-- The **augmentation** `A → ℤ`, `a ↦ a₀`, of a connected dg ring, a morphism of dg rings. -/
noncomputable def augmentation : A →ᵈᵍ+* ℤ where
  toFun := hA.toInt
  map_one' := hA.intCast_injective (by
    rw [hA.toInt_spec, decompose_of_mem_same _ one_mem_grading, Int.cast_one])
  map_mul' a b := hA.intCast_injective (by
    rw [hA.toInt_spec, Int.cast_mul, hA.toInt_spec, hA.toInt_spec,
      coe_decompose_mul_zero hA.grading_neg a b])
  map_zero' := hA.intCast_injective (by
    rw [hA.toInt_spec, decompose_zero, Int.cast_zero]
    rfl)
  map_add' a b := hA.intCast_injective (by
    rw [Int.cast_add, hA.toInt_spec, hA.toInt_spec, hA.toInt_spec, decompose_add]
    rfl)
  map_mem' {n} {a} ha := by
    rw [mem_grading_iff]
    by_cases hn : n = 0
    · exact Or.inl hn
    · refine Or.inr (hA.intCast_injective ?_)
      rw [hA.toInt_spec, decompose_of_mem_ne _ ha hn, Int.cast_zero]
  map_d' a := by
    rw [d_apply]
    refine hA.intCast_injective ?_
    have h := decompose_d a (-1)
    rw [neg_add_cancel] at h
    rw [hA.toInt_spec, h, hA.eq_zero_of_mem_neg (by omega) (decompose (grading (M := A)) a (-1)).2,
      d_zero, Int.cast_zero]

theorem augmentation_intCast (z : ℤ) : hA.augmentation (z : A) = z :=
  hA.intCast_injective (by
    change ((hA.toInt (z : A) : ℤ) : A) = z
    rw [hA.toInt_spec, decompose_of_mem_same _ (DegreeZero.intCast_mem_grading_zero A z)])

end IsConnectedInt

/-! ### Rings whose additive group is infinite cyclic -/

/-- In a ring whose additive group is infinite cyclic, `n ↦ n • 1` is bijective: the identity
generates. -/
theorem bijective_zsmul_one_of_addEquiv {R : Type*} [Ring R] (e : R ≃+ ℤ) :
    Function.Bijective fun n : ℤ => n • (1 : R) := by
  set g : R := e.symm 1 with hg
  have hrep : ∀ r : R, r = (e r) • g := fun r =>
    e.injective (by rw [map_zsmul, hg, AddEquiv.apply_symm_apply, smul_eq_mul, mul_one])
  have h1 := hrep 1
  have hgg := hrep (g * g)
  set u := e 1
  set v := e (g * g)
  have huv : u * v = 1 := by
    have : g = (u * v) • g := by
      calc g = 1 * g := (one_mul g).symm
        _ = (u • g) * g := by rw [← h1]
        _ = u • (g * g) := by rw [smul_mul_assoc]
        _ = u • v • g := by rw [← hgg]
        _ = (u * v) • g := by rw [smul_smul]
    have h := congrArg e this
    rw [map_zsmul, hg, AddEquiv.apply_symm_apply, smul_eq_mul, mul_one] at h
    exact h.symm
  have hu : u = 1 ∨ u = -1 := Int.eq_one_or_neg_one_of_mul_eq_one huv
  have huu : u * u = 1 := by rcases hu with h | h <;> rw [h] <;> norm_num
  have hu0 : u ≠ 0 := fun h => by
    rw [h, zero_mul] at huv
    exact zero_ne_one huv
  refine ⟨fun n n' h => ?_, fun r => ⟨e r * u, ?_⟩⟩
  · have h' := congrArg e h
    simp only [map_zsmul, smul_eq_mul] at h'
    exact mul_right_cancel₀ hu0 h'
  · change (e r * u) • (1 : R) = r
    rw [h1, smul_smul, mul_assoc, huu, mul_one, ← hrep r]

/-! ### The main theorem -/

namespace DGRing.K0

variable (A : Type) [Ring A] [DGAddCommGroup A] [DGRing A]

/-- The cohomology of `A` in degrees `≤ 2` is that of `ℤ`, except that `H²(A)` is only required
to be torsion-free: `Hⁿ(A) = 0` for `n < 0` and `n = 1`, `H⁰(A) ≅ ℤ`, `H²(A)` torsion-free. -/
structure IntegralLowDegree : Prop where
  neg : ∀ n : ℤ, n < 0 → ∀ x : cohomology A n, x = 0
  zero : Nonempty (cohomology A 0 ≃+ ℤ)
  one : ∀ x : cohomology A 1, x = 0
  two : ∀ m : ℤ, m ≠ 0 → ∀ x : cohomology A 2, m • x = 0 → x = 0

variable {A}

section Main

open DegreeZero

/-- Conjugation by an isomorphism `X ≅ Y` identifies `Hom(X, X⟦k⟧)` with `Hom(Y, Y⟦k⟧)`. -/
def conjShiftAddEquiv {C : Type*} [Category C] [Preadditive C] [HasShift C ℤ]
    [∀ n : ℤ, (shiftFunctor C n).Additive] {X Y : C} (e : X ≅ Y) (k : ℤ) :
    (X ⟶ X⟦k⟧) ≃+ (Y ⟶ Y⟦k⟧) where
  toFun g := e.inv ≫ g ≫ e.hom⟦k⟧'
  invFun h := e.hom ≫ h ≫ e.inv⟦k⟧'
  left_inv g := by simp [← Functor.map_comp]
  right_inv h := by simp [← Functor.map_comp]
  map_add' g g' := by simp [Preadditive.add_comp, Preadditive.comp_add]

/-- `End(X) ≃+ Hom(X, X⟦0⟧)`. -/
def endShiftZeroAddEquiv {C : Type*} [Category C] [Preadditive C] [HasShift C ℤ]
    [∀ n : ℤ, (shiftFunctor C n).Additive] (X : C) : (X ⟶ X) ≃+ (X ⟶ X⟦(0 : ℤ)⟧) where
  toFun g := g ≫ ((shiftFunctorZero C ℤ).app X).inv
  invFun g := g ≫ ((shiftFunctorZero C ℤ).app X).hom
  left_inv g := by simp
  right_inv g := by simp
  map_add' g g' := Preadditive.add_comp _ _ _ _ _ _

variable [HasDerivedCategory.{0, 0} A]

/-- **`K₀(A)` is generated by `[A]`** for a dg ring whose cohomology in degrees `≤ 2` is that of
`ℤ` up to torsion-free `H²` (`DG.DGRing.K0.IntegralLowDegree`). -/
theorem exists_eq_zsmul_self (hA : IntegralLowDegree A) (x : DGRing.K0 A) :
    ∃ n : ℤ, x = n • self A := by
  let : _root_.HasDerivedCategory (ModuleCat.{0} ℤ) := _root_.HasDerivedCategory.standard _
  let : DG.HasDerivedCategory.{0, 0} ℤ := DG.HasDerivedCategory.small ℤ
  let := CatModule.HasDerivedCategory.small.{0} (SingleObj ℤ)
  let := CatModule.HasDerivedCategory.small.{0} (SingleObj A)
  let E := derivedComparisonEquivalence ℤ
  let : E.inverse.CommShift ℤ := E.commShiftInverse ℤ
  let : E.CommShift ℤ := E.commShift_of_functor ℤ
  have : E.IsTriangulated := Equivalence.IsTriangulated.mk' _ inferInstance
  let F : _root_.DerivedCategory (ModuleCat.{0} ℤ) ⥤ DerivedCategory A :=
    E.inverse ⋙ (intHom A).derivedInduction.{0, 0, 0, 0}
  -- `F` sends `ℤ` in degree `0` to `A`.
  let eP : IntegralHeart.P F ≅ DerivedCategory.Q.obj (DGModuleCat.of A A) :=
    (intHom A).derivedInduction.mapIso (E.inverse.mapIso (derivedComparisonObjSelfIso ℤ).symm ≪≫
      (E.unitIso.app _).symm) ≪≫ (intHom A).derivedInductionSelfIso
  let conj : ∀ k : ℤ, (IntegralHeart.P F ⟶ (IntegralHeart.P F)⟦k⟧) ≃+ cohomology A k :=
    fun k => (conjShiftAddEquiv eP k).trans (DerivedCategory.homSelfShiftAddEquiv k)
  have hyp : IntegralHeart.Hyp F := by
    refine ⟨fun k hk g => (conj k).injective ?_, fun g => (conj 1).injective ?_, ?_,
      fun m hm g hg => (conj 2).injective ?_⟩
    · rw [map_zero]
      exact hA.neg k hk _
    · rw [map_zero]
      exact hA.one _
    · let e₀ := endShiftZeroAddEquiv (IntegralHeart.P F)
      exact bijective_zsmul_one_of_addEquiv
        (R := End (IntegralHeart.P F)) ((e₀.trans (conj 0)).trans hA.zero.some)
    · rw [map_zero]
      exact hA.two m hm _ (by rw [← map_zsmul, hg, map_zero])
  have hP : IsCompact.{0} (IntegralHeart.P F) :=
    DerivedCategory.isCompact_Q_self.of_iso eP
  have h𝒦 : ∀ X : DerivedCategory A, compactSubcategory.{0} (DerivedCategory A) X →
      IsHeartFamily.HasHeartTower (mapHeart F (fgSingle ℤ)) X := by
    intro X hX
    have hX' : ThickClosure (fun Y : DerivedCategory A =>
        ∃ _ : Unit, DerivedCategory.Q.obj (DGModuleCat.of A A) = Y) X := by
      rw [DerivedCategory.thickClosure_self_eq_isCompact]
      exact hX
    exact IntegralHeart.thickClosure_le hyp (fun Y ⟨_, hY⟩ => ⟨eqToIso hY.symm ≪≫ eP.symm⟩) X hX'
  obtain ⟨n, hn⟩ := IntegralHeart.exists_eq_zsmul (𝒦 := compactSubcategory.{0} (DerivedCategory A))
    hP h𝒦 x
  refine ⟨n, hn.trans ?_⟩
  congr 1
  exact DG.K0.mk_eq_of_iso_obj eP

/-- **`K₀(A) ≃ ℤ`**, `[A] ↦ 1`, for a dg ring `A` as in `DG.DGRing.K0.exists_eq_zsmul_self` with an
augmentation `A → ℤ` (a morphism of dg rings to `ℤ` in degree `0`). -/
noncomputable def equivIntOfAugmentation (hA : IntegralLowDegree A) (ε : A →ᵈᵍ+* ℤ) :
    DGRing.K0 A ≃+ ℤ :=
  letI : DG.HasDerivedCategory.{0, 0} ℤ := DG.HasDerivedCategory.small ℤ
  let f : DGRing.K0 A →+ ℤ :=
    (DGRing.K0.equivIntOfIsPrincipalIdealRing ℤ).toAddMonoidHom.comp (DGRing.K0.map ε)
  have hf : ∀ n : ℤ, f (n • self A) = n := fun n => by
    simp [f, map_zsmul, map_self, equivIntOfIsPrincipalIdealRing_self]
  AddEquiv.ofBijective f ⟨fun x y hxy => by
      obtain ⟨n, rfl⟩ := exists_eq_zsmul_self hA x
      obtain ⟨n', rfl⟩ := exists_eq_zsmul_self hA y
      rw [hf, hf] at hxy
      rw [hxy],
    fun n => ⟨n • self A, hf n⟩⟩

theorem equivIntOfAugmentation_self (hA : IntegralLowDegree A) (ε : A →ᵈᵍ+* ℤ) :
    equivIntOfAugmentation hA ε (self A) = 1 := by
  let : DG.HasDerivedCategory.{0, 0} ℤ := DG.HasDerivedCategory.small ℤ
  simp [equivIntOfAugmentation, map_self, equivIntOfIsPrincipalIdealRing_self]

omit [HasDerivedCategory.{0, 0} A] in
/-- A connected dg ring with `H¹(A) = 0` and `H²(A)` torsion-free satisfies the hypotheses of
`DG.DGRing.K0.exists_eq_zsmul_self`. -/
theorem IntegralLowDegree.of_isConnectedInt (hA : IsConnectedInt A)
    (h₁ : ∀ x : cohomology A 1, x = 0)
    (h₂ : ∀ m : ℤ, m ≠ 0 → ∀ x : cohomology A 2, m • x = 0 → x = 0) : IntegralLowDegree A :=
  ⟨fun _ hn => hA.cohomology_neg hn, ⟨hA.cohomologyZeroEquiv⟩, h₁, h₂⟩

/-- **`K₀(A) ≃ ℤ`** for a connected dg ring `A` with `H¹(A) = 0` and `H²(A)` torsion-free, through
the augmentation `A → ℤ`. -/
noncomputable def equivIntOfIsConnectedInt (hA : IsConnectedInt A)
    (h₁ : ∀ x : cohomology A 1, x = 0)
    (h₂ : ∀ m : ℤ, m ≠ 0 → ∀ x : cohomology A 2, m • x = 0 → x = 0) : DGRing.K0 A ≃+ ℤ :=
  equivIntOfAugmentation (IntegralLowDegree.of_isConnectedInt hA h₁ h₂) hA.augmentation

theorem equivIntOfIsConnectedInt_self (hA : IsConnectedInt A)
    (h₁ : ∀ x : cohomology A 1, x = 0)
    (h₂ : ∀ m : ℤ, m ≠ 0 → ∀ x : cohomology A 2, m • x = 0 → x = 0) :
    equivIntOfIsConnectedInt hA h₁ h₂ (self A) = 1 :=
  equivIntOfAugmentation_self _ _

end Main

end DGRing.K0

end DG
