import DG.Derived.ModuleHeart
import Mathlib.Algebra.Homology.DerivedCategory.Ext.EnoughProjectives
import Mathlib.Algebra.Module.PID
import Mathlib.Algebra.Category.ModuleCat.Biproducts
import Mathlib.Algebra.Category.ModuleCat.Projective
import Mathlib.Algebra.DirectSum.Module

/-!
# Hearts of finitely generated abelian groups in triangulated categories

Let `F : D(ℤ) ⥤ C` be a triangulated functor from Mathlib's derived category of abelian groups
to a pretriangulated category, and let `P = F(ℤ)` be the image of `ℤ` in degree `0`. Suppose that
`P` looks, in low degrees, like `ℤ` (`DG.IntegralHeart.Hyp F`):

* `Hom(P, P⟦k⟧) = 0` for `k < 0` and for `k = 1`;
* `ℤ → End(P)`, `n ↦ n • 𝟙`, is bijective;
* `Hom(P, P⟦2⟧)` has no torsion.

(For a dg ring `A` and `F` derived induction along `ℤ → A`, these say `Hⁿ(A) = 0` for `n < 0` and
`n = 1`, `H⁰(A) = ℤ`, and `H²(A)` is torsion-free.) Then `F` is fully faithful on finitely
generated abelian groups in degree `0`, has no morphisms of negative degree between them, and is
surjective on morphisms of degree one between them (`DG.IntegralHeart.good₂`), so the images of
finitely generated abelian groups form a heart family in `C`
(`DG.IntegralHeart.isHeartFamily`, from `DG.isHeartFamily_fgSingle` and
`DG.IsHeartFamily.map`). Consequently every object of the thick closure of `P` has a heart tower
whose cells are images of shifted finitely generated abelian groups
(`DG.IntegralHeart.thickClosure_le`), and the Grothendieck group of any triangulated subcategory
of `C` between `{P}` and its thick closure is generated by `[P]`
(`DG.IntegralHeart.exists_eq_zsmul`): the class of the image of a finitely generated abelian group
`M` is `rank(M) [P]`.

## Proofs

Finitely generated abelian groups are finite products of copies of `ℤ` and of cyclic groups
`ℤ/m`, `m ≠ 0` (`DG.moduleCat_int_induction`, from the structure theorem). All statements are
compatible with finite products; for `ℤ` they are the hypotheses, and for `ℤ/m` they follow from
the long exact sequences of the triangle `P --m--> P → F(ℤ/m) → P⟦1⟧` (the image of
`0 → ℤ --m--> ℤ → ℤ/m → 0`), using that multiplication by `m` is injective on `End(P)` and on
`Hom(P, P⟦2⟧)`.
-/

universe w v u

set_option linter.unusedSectionVars false

namespace DG

open CategoryTheory Limits Pretriangulated DerivedCategory

/-! ### Finitely generated abelian groups -/

/-- **Induction principle for finitely generated abelian groups**: a property of `ℤ`-modules
which is invariant under isomorphisms and binary biproducts and holds for zero modules, `ℤ`, and
the cyclic groups `ℤ/m` (`m ≠ 0`) holds for every finitely generated `ℤ`-module (structure
theorem). -/
theorem moduleCat_int_induction (Pr : ModuleCat.{0} ℤ → Prop)
    (hiso : ∀ {M N : ModuleCat.{0} ℤ}, (M ≅ N) → Pr M → Pr N)
    (hzero : ∀ M : ModuleCat.{0} ℤ, IsZero M → Pr M)
    (hbiprod : ∀ M N : ModuleCat.{0} ℤ, Pr M → Pr N → Pr (M ⊞ N))
    (hZ : Pr (ModuleCat.of ℤ ℤ))
    (hcyc : ∀ m : ℤ, m ≠ 0 → Pr (ModuleCat.of ℤ (ℤ ⧸ Submodule.span ℤ {m}))) :
    ∀ M : ModuleCat.{0} ℤ, Module.Finite ℤ M → Pr M := by
  have hprod : ∀ M N : ModuleCat.{0} ℤ, Pr M → Pr N →
      Pr (@ModuleCat.of ℤ _ (M × N) _ Prod.instModule) :=
    fun M N hM hN => hiso (ModuleCat.biprodIsoProd M N) (hbiprod M N hM hN)
  have hfree : ∀ n : ℕ, Pr (ModuleCat.of ℤ (Fin n → ℤ)) := by
    intro n
    induction n with
    | zero => exact hzero _ (ModuleCat.isZero_of_subsingleton _)
    | succ n ih =>
      exact hiso (Fin.consLinearEquiv ℤ (fun _ : Fin (n + 1) => ℤ)).toModuleIso
        (hprod (ModuleCat.of ℤ ℤ) (ModuleCat.of ℤ (Fin n → ℤ)) hZ ih)
  have htors : ∀ (ι : Type) [Finite ι] (q : ι → ℤ), (∀ i, q i ≠ 0) →
      Pr (ModuleCat.of ℤ (∀ i, ℤ ⧸ Submodule.span ℤ {q i})) := by
    intro ι _
    refine Finite.induction_empty_option (P := fun ι => ∀ (q : ι → ℤ), (∀ i, q i ≠ 0) →
      Pr (ModuleCat.of ℤ (∀ i, ℤ ⧸ Submodule.span ℤ {q i}))) ?_ ?_ ?_ ι
    · intro α β e h q hq
      exact hiso (LinearEquiv.piCongrLeft ℤ (fun j => ℤ ⧸ Submodule.span ℤ {q j}) e).toModuleIso
        (h (q ∘ e) fun i => hq _)
    · intro q _
      exact hzero _ (ModuleCat.isZero_of_subsingleton _)
    · intro α _ h q hq
      exact hiso
        (LinearEquiv.piOptionEquivProd (M := fun i => ℤ ⧸ Submodule.span ℤ {q i}) ℤ).symm.toModuleIso
        (hprod (ModuleCat.of ℤ (ℤ ⧸ Submodule.span ℤ {q none}))
          (ModuleCat.of ℤ (∀ i, ℤ ⧸ Submodule.span ℤ {q (some i)})) (hcyc _ (hq none))
          (h (fun i => q (some i)) fun i => hq _))
  intro M hM
  obtain ⟨n, ι, _, p, hp, e, ⟨f⟩⟩ := Module.equiv_free_prod_directSum ℤ M
  have h₁ : Pr (ModuleCat.of ℤ (Fin n →₀ ℤ)) :=
    hiso (Finsupp.linearEquivFunOnFinite ℤ ℤ (Fin n)).symm.toModuleIso (hfree n)
  have h₂ : Pr (ModuleCat.of ℤ (DirectSum ι fun i => ℤ ⧸ Submodule.span ℤ {p i ^ e i})) :=
    hiso (DirectSum.linearEquivFunOnFintype ℤ ι _).symm.toModuleIso
      (htors ι _ fun i => pow_ne_zero _ (hp i).ne_zero)
  exact hiso f.symm.toModuleIso (hprod _ _ h₁ h₂)

/-- The short exact sequence `0 → ℤ --m--> ℤ → ℤ/m → 0`. -/
noncomputable abbrev cyclicShortComplex (m : ℤ) : ShortComplex (ModuleCat.{0} ℤ) :=
  ModuleCat.shortComplexOfCompEqZero (m • LinearMap.id : ℤ →ₗ[ℤ] ℤ)
    (Submodule.span ℤ {m}).mkQ (LinearMap.ext fun x =>
      (Submodule.Quotient.mk_eq_zero _).mpr (Submodule.mem_span_singleton.mpr
        ⟨x, by simp [mul_comm]⟩))

theorem cyclicShortComplex_shortExact {m : ℤ} (hm : m ≠ 0) :
    (cyclicShortComplex m).ShortExact :=
  ModuleCat.shortComplex_shortExact _
    (LinearMap.exact_iff.mpr (by
      change LinearMap.ker (Submodule.span ℤ {m}).mkQ = LinearMap.range (m • LinearMap.id)
      rw [Submodule.ker_mkQ]
      ext x
      rw [Submodule.mem_span_singleton, LinearMap.mem_range]
      constructor
      · rintro ⟨a, rfl⟩
        exact ⟨a, by simp [mul_comm]⟩
      · rintro ⟨a, rfl⟩
        exact ⟨a, by simp [mul_comm]⟩))
    (show Function.Injective (m • LinearMap.id : ℤ →ₗ[ℤ] ℤ) from fun x y h =>
      mul_left_cancel₀ hm (by simpa using h))
    (Submodule.mkQ_surjective _)

theorem ofHom_zsmul_id (m : ℤ) :
    ModuleCat.ofHom (m • LinearMap.id : ℤ →ₗ[ℤ] ℤ) = m • 𝟙 (ModuleCat.of ℤ ℤ) := by
  ext
  change (m • LinearMap.id : ℤ →ₗ[ℤ] ℤ) 1 = (m • 𝟙 (ModuleCat.of ℤ ℤ)).hom 1
  rw [ModuleCat.hom_zsmul]
  rfl

theorem cyclicShortComplex_f (m : ℤ) : (cyclicShortComplex m).f = m • 𝟙 _ := by
  ext
  change (m • LinearMap.id : ℤ →ₗ[ℤ] ℤ) 1 = (m • 𝟙 (ModuleCat.of ℤ ℤ)).hom 1
  rw [ModuleCat.hom_zsmul]
  rfl

/-! ### Morphisms between shifted objects -/

section ShiftHom

variable {C : Type u} [Category.{v} C] [Preadditive C] [HasShift C ℤ]
  [∀ n : ℤ, (shiftFunctor C n).Additive]

/-- `Hom(X⟦a⟧, M)` embeds additively into `Hom(X, M⟦-a⟧)`. -/
noncomputable def shiftHomAddHom (X M : C) (a : ℤ) : (X⟦a⟧ ⟶ M) →+ (X ⟶ M⟦-a⟧) where
  toFun g := (shiftShiftNeg X a).inv ≫ g⟦-a⟧'
  map_zero' := by rw [Functor.map_zero, Limits.comp_zero]
  map_add' g g' := by rw [Functor.map_add]; exact Preadditive.comp_add _ _ _ _ _ _

theorem shiftHomAddHom_injective (X M : C) (a : ℤ) :
    Function.Injective (shiftHomAddHom X M a) := by
  intro g g' h
  change (shiftShiftNeg X a).inv ≫ g⟦-a⟧' = (shiftShiftNeg X a).inv ≫ g'⟦-a⟧' at h
  rw [cancel_epi] at h
  exact (shiftFunctor C (-a)).map_injective h

/-- `Hom(X, M⟦k⟧)` embeds additively into `Hom(X⟦-k⟧, M)`. -/
noncomputable def homShiftAddHom (X M : C) (k : ℤ) : (X ⟶ M⟦k⟧) →+ (X⟦-k⟧ ⟶ M) where
  toFun g := g⟦-k⟧' ≫ (shiftShiftNeg M k).hom
  map_zero' := by rw [Functor.map_zero, Limits.zero_comp]
  map_add' g g' := by rw [Functor.map_add]; exact Preadditive.add_comp _ _ _ _ _ _

theorem homShiftAddHom_injective (X M : C) (k : ℤ) :
    Function.Injective (homShiftAddHom X M k) := by
  intro g g' h
  change g⟦-k⟧' ≫ (shiftShiftNeg M k).hom = g'⟦-k⟧' ≫ (shiftShiftNeg M k).hom at h
  rw [cancel_mono] at h
  exact (shiftFunctor C (-k)).map_injective h

/-- Postcomposition with an isomorphism, as an additive equivalence. -/
def homIsoAddEquiv (X : C) {M M' : C} (e : M ≅ M') : (X ⟶ M) ≃+ (X ⟶ M') where
  toFun g := g ≫ e.hom
  invFun g := g ≫ e.inv
  left_inv g := by simp
  right_inv g := by simp
  map_add' g g' := Preadditive.add_comp _ _ _ _ _ _

/-- Transfer of the vanishing of a group of morphisms along an injective additive map. -/
theorem eq_zero_of_injective {G G' : Type*} [AddCommGroup G] [AddCommGroup G'] (φ : G →+ G')
    (hφ : Function.Injective φ) (h : ∀ y : G', y = 0) (x : G) : x = 0 :=
  hφ (by rw [h (φ x), map_zero])

/-- Transfer of `m`-torsion-freeness along an injective additive map. -/
theorem eq_zero_of_injective_of_zsmul {G G' : Type*} [AddCommGroup G] [AddCommGroup G']
    (φ : G →+ G') (hφ : Function.Injective φ) {m : ℤ} (h : ∀ y : G', m • y = 0 → y = 0) (x : G)
    (hx : m • x = 0) : x = 0 :=
  hφ (by rw [h (φ x) (by rw [← map_zsmul, hx, map_zero]), map_zero])

end ShiftHom

namespace IntegralHeart

variable [HasDerivedCategory.{w} (ModuleCat.{0} ℤ)]
  {C : Type u} [Category.{v} C] [HasZeroObject C] [HasShift C ℤ] [Preadditive C]
  [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
  (F : DerivedCategory (ModuleCat.{0} ℤ) ⥤ C) [F.CommShift ℤ] [F.IsTriangulated]

/-- `ℤ` in degree `0`. -/
noncomputable abbrev Z : DerivedCategory (ModuleCat.{0} ℤ) :=
  (singleFunctor (ModuleCat.{0} ℤ) 0).obj (ModuleCat.of ℤ ℤ)

/-- The image `P = F(ℤ)` of `ℤ` in degree `0`. -/
noncomputable abbrev P : C := F.obj Z

/-- The hypotheses on `P = F(ℤ)`: `Hom(P, P⟦k⟧) = 0` for `k < 0` and `k = 1`, `End(P) = ℤ`, and
`Hom(P, P⟦2⟧)` torsion-free. -/
structure Hyp : Prop where
  neg : ∀ k : ℤ, k < 0 → ∀ g : P F ⟶ (P F)⟦k⟧, g = 0
  one : ∀ g : P F ⟶ (P F)⟦(1 : ℤ)⟧, g = 0
  zero : Function.Bijective fun n : ℤ => n • 𝟙 (P F)
  two : ∀ n : ℤ, n ≠ 0 → ∀ g : P F ⟶ (P F)⟦(2 : ℤ)⟧, n • g = 0 → g = 0

/-- The one-variable statements for an object `Y` of `D(ℤ)`. -/
structure Good (Y : DerivedCategory (ModuleCat.{0} ℤ)) : Prop where
  neg : ∀ k : ℤ, k < 0 → ∀ g : P F ⟶ (F.obj Y)⟦k⟧, g = 0
  one : ∀ g : P F ⟶ (F.obj Y)⟦(1 : ℤ)⟧, g = 0
  bij : Function.Bijective fun f : Z ⟶ Y => F.map f

variable {F}

theorem Good.of_iso {Y Y' : DerivedCategory (ModuleCat.{0} ℤ)} (h : Good F Y) (e : Y ≅ Y') :
    Good F Y' where
  neg k hk g := by
    have := h.neg k hk (g ≫ (F.map e.inv)⟦k⟧')
    rw [← cancel_mono ((F.map e.inv)⟦k⟧'), this, zero_comp]
  one g := by
    have := h.one (g ≫ (F.map e.inv)⟦(1 : ℤ)⟧')
    rw [← cancel_mono ((F.map e.inv)⟦(1 : ℤ)⟧'), this, zero_comp]
  bij := by
    refine ⟨fun f f' hf => ?_, fun g => ?_⟩
    · have : f ≫ e.inv = f' ≫ e.inv := h.bij.1 (by simp [hf])
      simpa using congrArg (· ≫ e.hom) this
    · obtain ⟨f, hf⟩ := h.bij.2 (g ≫ F.map e.inv)
      refine ⟨f ≫ e.hom, ?_⟩
      simp only [Functor.map_comp]
      rw [show F.map f = g ≫ F.map e.inv from hf, Category.assoc, ← F.map_comp, e.inv_hom_id,
        F.map_id, Category.comp_id]

theorem Good.of_isZero {Y : DerivedCategory (ModuleCat.{0} ℤ)} (hY : IsZero Y) : Good F Y where
  neg _ _ _ := ((shiftFunctor C _).map_isZero (F.map_isZero hY)).eq_of_tgt _ _
  one _ := ((shiftFunctor C (1 : ℤ)).map_isZero (F.map_isZero hY)).eq_of_tgt _ _
  bij := ⟨fun _ _ _ => hY.eq_of_tgt _ _, fun _ => ⟨0, (F.map_isZero hY).eq_of_tgt _ _⟩⟩

theorem Good.biprod {Y₁ Y₂ : DerivedCategory (ModuleCat.{0} ℤ)} (h₁ : Good F Y₁)
    (h₂ : Good F Y₂) : Good F (Y₁ ⊞ Y₂) := by
  have htot : F.map (biprod.fst : Y₁ ⊞ Y₂ ⟶ Y₁) ≫ F.map biprod.inl +
      F.map biprod.snd ≫ F.map biprod.inr = 𝟙 _ := by
    rw [← F.map_comp, ← F.map_comp, ← F.map_add, biprod.total, F.map_id]
  have hk : ∀ k : ℤ, (F.map (biprod.fst : Y₁ ⊞ Y₂ ⟶ Y₁))⟦k⟧' ≫ (F.map biprod.inl)⟦k⟧' +
      (F.map biprod.snd)⟦k⟧' ≫ (F.map biprod.inr)⟦k⟧' = 𝟙 _ := fun k => by
    rw [← (shiftFunctor C k).map_comp, ← (shiftFunctor C k).map_comp,
      ← (shiftFunctor C k).map_add, htot, CategoryTheory.Functor.map_id]
  have hsplit : ∀ {k : ℤ} (g : P F ⟶ (F.obj (Y₁ ⊞ Y₂))⟦k⟧),
      g = (g ≫ (F.map biprod.fst)⟦k⟧') ≫ (F.map biprod.inl)⟦k⟧' +
        (g ≫ (F.map biprod.snd)⟦k⟧') ≫ (F.map biprod.inr)⟦k⟧' := by
    intro k g
    conv_lhs => rw [← Category.comp_id g, ← hk k]
    rw [Preadditive.comp_add, Category.assoc, Category.assoc]
  refine ⟨fun k hk' g => ?_, fun g => ?_, ?_, ?_⟩
  · rw [hsplit g, h₁.neg k hk' (g ≫ _), h₂.neg k hk' (g ≫ _), zero_comp, zero_comp, add_zero]
  · rw [hsplit g, h₁.one (g ≫ _), h₂.one (g ≫ _), zero_comp, zero_comp, add_zero]
  · intro f f' hf
    have hf' : F.map f = F.map f' := hf
    apply biprod.hom_ext
    · exact h₁.bij.1 (by simp only [F.map_comp, hf'])
    · exact h₂.bij.1 (by simp only [F.map_comp, hf'])
  · intro g
    obtain ⟨f₁, hf₁⟩ := h₁.bij.2 (g ≫ F.map biprod.fst)
    obtain ⟨f₂, hf₂⟩ := h₂.bij.2 (g ≫ F.map biprod.snd)
    refine ⟨biprod.lift f₁ f₂, ?_⟩
    change F.map (biprod.lift f₁ f₂) = g
    rw [show biprod.lift f₁ f₂ = f₁ ≫ biprod.inl + f₂ ≫ biprod.inr by
        ext <;> simp, F.map_add, F.map_comp, F.map_comp,
      show F.map f₁ = g ≫ F.map biprod.fst from hf₁, show F.map f₂ = g ≫ F.map biprod.snd from hf₂,
      Category.assoc, Category.assoc, ← Preadditive.comp_add, htot, Category.comp_id]

/-- Every endomorphism of `ℤ` in degree `0` is an integer multiple of the identity. -/
theorem Z_endo (f : (Z : DerivedCategory (ModuleCat.{0} ℤ)) ⟶ Z) : ∃ n : ℤ, f = n • 𝟙 _ := by
  obtain ⟨f₀, rfl⟩ := (singleFunctor (ModuleCat.{0} ℤ) 0).map_surjective f
  refine ⟨f₀.hom 1, ?_⟩
  have : f₀ = (f₀.hom 1) • 𝟙 _ := ModuleCat.hom_ext (LinearMap.ext_ring (by simp))
  conv_lhs => rw [this]
  rw [Functor.map_zsmul, CategoryTheory.Functor.map_id]

theorem good_Z (h : Hyp F) : Good F Z where
  neg := h.neg
  one := h.one
  bij := by
    refine ⟨fun f f' hf => ?_, fun g => ?_⟩
    · obtain ⟨n, rfl⟩ := Z_endo f
      obtain ⟨n', rfl⟩ := Z_endo f'
      have : n • 𝟙 (P F) = n' • 𝟙 (P F) := by
        simpa [Functor.map_zsmul] using hf
      rw [h.zero.1 this]
    · obtain ⟨n, rfl⟩ := h.zero.2 g
      exact ⟨n • 𝟙 _, by simp⟩

/-! ### Cyclic groups -/

section Cyclic

variable {m : ℤ} (hm : m ≠ 0)

/-- `ℤ/m` in degree `0`. -/
noncomputable abbrev Zmod (m : ℤ) : DerivedCategory (ModuleCat.{0} ℤ) :=
  (singleFunctor (ModuleCat.{0} ℤ) 0).obj (ModuleCat.of ℤ (ℤ ⧸ Submodule.span ℤ {m}))

/-- The projection `ℤ → ℤ/m` in degree `0`. -/
noncomputable abbrev cycπ (m : ℤ) : (Z : DerivedCategory (ModuleCat.{0} ℤ)) ⟶ Zmod m :=
  (singleFunctor (ModuleCat.{0} ℤ) 0).map (ModuleCat.ofHom (Submodule.span ℤ {m}).mkQ)

/-- The triangle `ℤ --m--> ℤ → ℤ/m → ℤ⟦1⟧` in `D(ℤ)`. -/
noncomputable abbrev cycTriangle : Triangle (DerivedCategory (ModuleCat.{0} ℤ)) :=
  Triangle.mk (m • 𝟙 Z) (cycπ m)
    ((cyclicShortComplex_shortExact hm).singleδ : Zmod m ⟶ Z⟦(1 : ℤ)⟧)

include hm in
theorem cycTriangle_distinguished : cycTriangle hm ∈ distTriang _ := by
  refine isomorphic_distinguished _ (cyclicShortComplex_shortExact hm).singleTriangle_distinguished
    _ (Triangle.isoMk _ _ (Iso.refl _) (Iso.refl _) (Iso.refl _) ?_ (by simp) (by simp))
  dsimp
  rw [ofHom_zsmul_id, Functor.map_zsmul, CategoryTheory.Functor.map_id, Category.comp_id,
    Category.id_comp]

variable (F) in
/-- The image `P --m--> P → F(ℤ/m) → P⟦1⟧` of the triangle of `ℤ/m`. -/
noncomputable abbrev cycTriangleF : Triangle C :=
  Triangle.mk (m • 𝟙 (P F)) (F.map (cycπ m))
    (F.map (cycTriangle hm).mor₃ ≫ (F.commShiftIso (1 : ℤ)).hom.app Z)

include hm in
theorem cycTriangleF_distinguished : cycTriangleF F hm ∈ distTriang C := by
  refine isomorphic_distinguished _ (F.map_distinguished _ (cycTriangle_distinguished hm)) _
    (Triangle.isoMk _ _ (Iso.refl _) (Iso.refl _) (Iso.refl _) ?_ (by simp) (by simp))
  dsimp
  rw [Functor.map_zsmul, CategoryTheory.Functor.map_id, Category.comp_id, Category.id_comp]

include hm in
/-- Morphisms from `W` to `F(ℤ/m)` vanish if morphisms `W ⟶ P` vanish and `Hom(W, P⟦1⟧)` has no
`m`-torsion. -/
theorem cyc_hom_eq_zero {W : C} (h₀ : ∀ y : W ⟶ P F, y = 0)
    (h₁ : ∀ z : W ⟶ (P F)⟦(1 : ℤ)⟧, m • z = 0 → z = 0) (g : W ⟶ F.obj (Zmod m)) : g = 0 := by
  have hT := cycTriangleF_distinguished (F := F) hm
  have hz : g ≫ (cycTriangleF F hm).mor₃ = 0 := by
    refine h₁ _ ?_
    have h31 : (cycTriangleF F hm).mor₃ ≫ (m • 𝟙 (P F))⟦(1 : ℤ)⟧' = 0 :=
      comp_distTriang_mor_zero₃₁ _ hT
    have e : ((m • 𝟙 (P F))⟦(1 : ℤ)⟧' : (P F)⟦(1 : ℤ)⟧ ⟶ (P F)⟦(1 : ℤ)⟧) = m • 𝟙 _ := by
      rw [Functor.map_zsmul, CategoryTheory.Functor.map_id]
    erw [e, Preadditive.comp_zsmul, Category.comp_id] at h31
    rw [← Preadditive.comp_zsmul, h31, comp_zero]
  obtain ⟨y, hy⟩ := Triangle.coyoneda_exact₃ _ hT g hz
  rw [hy, h₀ y, zero_comp]

include hm in
/-- `End(P)` has no torsion. -/
theorem Hyp.zsmul_eq_zero (h : Hyp F) {x : P F ⟶ P F} (hx : m • x = 0) : x = 0 := by
  obtain ⟨n, rfl⟩ := h.zero.2 x
  have h0 : (m * n) • 𝟙 (P F) = (0 : ℤ) • 𝟙 (P F) := by
    rw [mul_smul, zero_smul]
    exact hx
  have : m * n = 0 := h.zero.1 h0
  change n • 𝟙 (P F) = 0
  rw [(mul_eq_zero.mp this).resolve_left hm, zero_smul]

include hm in
theorem good_cyc (h : Hyp F) : Good F (Zmod m) := by
  have hT := cycTriangleF_distinguished (F := F) hm
  -- Morphisms `P⟦a⟧ ⟶ P` vanish for `a ≥ 1`.
  have hpos : ∀ a : ℤ, 0 < a → ∀ y : (P F)⟦a⟧ ⟶ P F, y = 0 := fun a ha y =>
    eq_zero_of_injective _ (shiftHomAddHom_injective _ _ a) (h.neg (-a) (by omega)) y
  have hP1 : ∀ a : ℤ, 0 < a → ∀ z : (P F)⟦a⟧ ⟶ (P F)⟦(1 : ℤ)⟧, m • z = 0 → z = 0 := by
    intro a ha z hz
    refine eq_zero_of_injective_of_zsmul _ (shiftHomAddHom_injective _ _ a) ?_ z hz
    intro y hy
    rcases (show a = 1 ∨ 1 < a by omega) with rfl | ha'
    · exact eq_zero_of_injective_of_zsmul
        (homIsoAddEquiv _ (shiftShiftNeg (P F) (1 : ℤ))).toAddMonoidHom
        (homIsoAddEquiv _ _).injective (fun x hx => h.zsmul_eq_zero hm hx) y hy
    · exact eq_zero_of_injective (homIsoAddEquiv _ ((shiftFunctorAdd' C 1 (-a) (1 + -a) rfl).app
        (P F)).symm).toAddMonoidHom (homIsoAddEquiv _ _).injective
        (h.neg (1 + -a) (by omega)) y
  refine ⟨fun k hk g => ?_, fun g => ?_, ⟨fun f f' hf => ?_, fun g => ?_⟩⟩
  · refine (homShiftAddHom_injective _ _ k) ?_
    rw [map_zero]
    exact cyc_hom_eq_zero hm (hpos (-k) (by omega)) (hP1 (-k) (by omega)) _
  · refine (homShiftAddHom_injective _ _ 1) ?_
    rw [map_zero]
    refine cyc_hom_eq_zero hm (fun y => ?_) (fun z hz => ?_) _
    · exact eq_zero_of_injective _ (shiftHomAddHom_injective _ _ (-1)) h.one y
    · refine eq_zero_of_injective_of_zsmul _ (shiftHomAddHom_injective _ _ (-1)) ?_ z hz
      intro y hy
      exact eq_zero_of_injective_of_zsmul (homIsoAddEquiv _
        ((shiftFunctorAdd' C 1 1 2 rfl).app (P F)).symm).toAddMonoidHom
        (homIsoAddEquiv _ _).injective (fun x hx => h.two m hm x hx) y hy
  · -- injectivity
    have hf' : F.map (f - f') = 0 := by
      rw [F.map_sub]
      exact sub_eq_zero.mpr hf
    rw [← sub_eq_zero]
    obtain ⟨f₀, hf₀⟩ : ∃ f₀ : Z ⟶ Zmod m, f₀ = f - f' := ⟨_, rfl⟩
    rw [← hf₀] at hf' ⊢
    have hD := cycTriangle_distinguished hm
    have hz : f₀ ≫ (cycTriangle hm).mor₃ = 0 := by
      have : HasExt.{w} (ModuleCat.{0} ℤ) := hasExt_of_hasDerivedCategory _
      obtain ⟨e, he⟩ := (Abelian.Ext.homEquiv (X := ModuleCat.of ℤ ℤ)
        (Y := ModuleCat.of ℤ ℤ) (n := 0 + 1)).surjective (f₀ ≫ (cycTriangle hm).mor₃)
      rw [← he, Abelian.Ext.eq_zero_of_projective e]
      exact Abelian.Ext.zero_hom _ _ _
    obtain ⟨y, hy⟩ := Triangle.coyoneda_exact₃ _ hD f₀ hz
    have hFy : F.map y ≫ (cycTriangleF F hm).mor₂ = 0 := by
      change F.map y ≫ F.map (cycπ m) = 0
      rw [← F.map_comp]
      change F.map (y ≫ (cycTriangle hm).mor₂) = 0
      rw [← hy, hf']
    obtain ⟨z, hz'⟩ := Triangle.coyoneda_exact₂ _ hT (F.map y) hFy
    obtain ⟨z₀, hz₀⟩ := (good_Z h).bij.2 z
    have hyz : y = m • z₀ := (good_Z h).bij.1 (by
      change F.map y = F.map (m • z₀)
      rw [hz', Functor.map_zsmul]
      change z ≫ (m • 𝟙 (P F)) = m • F.map z₀
      erw [Preadditive.comp_zsmul, Category.comp_id, show F.map z₀ = z from hz₀])
    have hm2 : m • (cycTriangle hm).mor₂ = 0 := by
      have := comp_distTriang_mor_zero₁₂ _ hD
      simpa using this
    rw [hy, hyz, Preadditive.zsmul_comp, ← Preadditive.comp_zsmul, hm2, comp_zero]
  · -- surjectivity
    have hz : g ≫ (cycTriangleF F hm).mor₃ = 0 := h.one _
    obtain ⟨y, hy⟩ := Triangle.coyoneda_exact₃ _ hT g hz
    obtain ⟨y₀, hy₀⟩ := (good_Z h).bij.2 y
    refine ⟨y₀ ≫ cycπ m, ?_⟩
    change F.map (y₀ ≫ cycπ m) = g
    rw [F.map_comp, show F.map y₀ = y from hy₀, hy]
    rfl

end Cyclic

/-- The one-variable statements hold for every finitely generated abelian group. -/
theorem good_single (h : Hyp F) (M : ModuleCat.{0} ℤ) (hM : Module.Finite ℤ M) :
    Good F ((singleFunctor (ModuleCat.{0} ℤ) 0).obj M) := by
  have := preservesBinaryBiproducts_of_preservesBiproducts (singleFunctor (ModuleCat.{0} ℤ) 0)
  exact moduleCat_int_induction (fun M => Good F ((singleFunctor (ModuleCat.{0} ℤ) 0).obj M))
    (fun e hM => hM.of_iso ((singleFunctor (ModuleCat.{0} ℤ) 0).mapIso e))
    (fun _ hM => Good.of_isZero (Functor.map_isZero _ hM))
    (fun M N hM hN => (hM.biprod hN).of_iso
      ((singleFunctor (ModuleCat.{0} ℤ) 0).mapBiprod M N).symm)
    (good_Z h) (fun _ hm => good_cyc hm h) M hM

/-! ### Two variables -/

variable (F) in
/-- The two-variable statements for objects `X`, `Y` of `D(ℤ)`: `F` is bijective on
`Hom(X, Y)`, there are no morphisms `F X ⟶ (F Y)⟦k⟧` for `k < 0`, and every morphism
`F X ⟶ (F Y)⟦1⟧` comes from `Hom(X, Y⟦1⟧)`. -/
structure Good₂ (X Y : DerivedCategory (ModuleCat.{0} ℤ)) : Prop where
  bij : Function.Bijective fun f : X ⟶ Y => F.map f
  neg : ∀ k : ℤ, k < 0 → ∀ g : F.obj X ⟶ (F.obj Y)⟦k⟧, g = 0
  one : ∀ g : F.obj X ⟶ (F.obj Y)⟦(1 : ℤ)⟧,
    ∃ f : X ⟶ Y⟦(1 : ℤ)⟧, F.map f ≫ (F.commShiftIso (1 : ℤ)).hom.app Y = g

theorem Good₂.of_iso_left {X X' Y : DerivedCategory (ModuleCat.{0} ℤ)} (h : Good₂ F X Y)
    (e : X ≅ X') : Good₂ F X' Y where
  bij := by
    refine ⟨fun f f' hf => ?_, fun g => ?_⟩
    · have hf' : F.map f = F.map f' := hf
      have : e.hom ≫ f = e.hom ≫ f' := h.bij.1 (by simp only [F.map_comp, hf'])
      simpa using congrArg (e.inv ≫ ·) this
    · obtain ⟨f, hf⟩ := h.bij.2 (F.map e.hom ≫ g)
      refine ⟨e.inv ≫ f, ?_⟩
      change F.map (e.inv ≫ f) = g
      rw [F.map_comp, show F.map f = F.map e.hom ≫ g from hf, ← Category.assoc, ← F.map_comp,
        e.inv_hom_id, F.map_id, Category.id_comp]
  neg k hk g := by
    have := h.neg k hk (F.map e.hom ≫ g)
    rw [← cancel_epi (F.map e.hom), this, comp_zero]
  one g := by
    obtain ⟨f, hf⟩ := h.one (F.map e.hom ≫ g)
    refine ⟨e.inv ≫ f, ?_⟩
    rw [F.map_comp, Category.assoc, hf, ← Category.assoc, ← F.map_comp, e.inv_hom_id, F.map_id,
      Category.id_comp]

theorem Good₂.of_iso_right {X Y Y' : DerivedCategory (ModuleCat.{0} ℤ)} (h : Good₂ F X Y)
    (e : Y ≅ Y') : Good₂ F X Y' where
  bij := by
    refine ⟨fun f f' hf => ?_, fun g => ?_⟩
    · have hf' : F.map f = F.map f' := hf
      have : f ≫ e.inv = f' ≫ e.inv := h.bij.1 (by simp only [F.map_comp, hf'])
      simpa using congrArg (· ≫ e.hom) this
    · obtain ⟨f, hf⟩ := h.bij.2 (g ≫ F.map e.inv)
      refine ⟨f ≫ e.hom, ?_⟩
      change F.map (f ≫ e.hom) = g
      rw [F.map_comp, show F.map f = g ≫ F.map e.inv from hf, Category.assoc, ← F.map_comp,
        e.inv_hom_id, F.map_id, Category.comp_id]
  neg k hk g := by
    have := h.neg k hk (g ≫ (F.map e.inv)⟦k⟧')
    rw [← cancel_mono ((F.map e.inv)⟦k⟧'), this, zero_comp]
  one g := by
    obtain ⟨f, hf⟩ := h.one (g ≫ (F.map e.inv)⟦(1 : ℤ)⟧')
    refine ⟨f ≫ e.hom⟦(1 : ℤ)⟧', ?_⟩
    rw [F.map_comp, Category.assoc, F.commShiftIso_hom_naturality, ← Category.assoc, hf,
      Category.assoc, ← Functor.map_comp, ← F.map_comp, e.inv_hom_id, F.map_id,
      CategoryTheory.Functor.map_id, Category.comp_id]

theorem Good₂.of_isZero_left {X Y : DerivedCategory (ModuleCat.{0} ℤ)} (hX : IsZero X) :
    Good₂ F X Y where
  bij := ⟨fun _ _ _ => hX.eq_of_src _ _, fun _ => ⟨0, (F.map_isZero hX).eq_of_src _ _⟩⟩
  neg _ _ _ := (F.map_isZero hX).eq_of_src _ _
  one _ := ⟨0, (F.map_isZero hX).eq_of_src _ _⟩

theorem Good₂.biprod_left {X₁ X₂ Y : DerivedCategory (ModuleCat.{0} ℤ)} (h₁ : Good₂ F X₁ Y)
    (h₂ : Good₂ F X₂ Y) : Good₂ F (X₁ ⊞ X₂) Y := by
  have htot : F.map (biprod.fst : X₁ ⊞ X₂ ⟶ X₁) ≫ F.map biprod.inl +
      F.map biprod.snd ≫ F.map biprod.inr = 𝟙 _ := by
    rw [← F.map_comp, ← F.map_comp, ← F.map_add, biprod.total, F.map_id]
  have hsplit : ∀ {W : C} (g : F.obj (X₁ ⊞ X₂) ⟶ W),
      g = F.map biprod.fst ≫ (F.map biprod.inl ≫ g) +
        F.map biprod.snd ≫ (F.map biprod.inr ≫ g) := by
    intro W g
    conv_lhs => rw [← Category.id_comp g, ← htot]
    rw [Preadditive.add_comp, Category.assoc, Category.assoc]
  refine ⟨⟨fun f f' hf => ?_, fun g => ?_⟩, fun k hk g => ?_, fun g => ?_⟩
  · have hf' : F.map f = F.map f' := hf
    apply biprod.hom_ext'
    · exact h₁.bij.1 (by simp only [F.map_comp, hf'])
    · exact h₂.bij.1 (by simp only [F.map_comp, hf'])
  · obtain ⟨f₁, hf₁⟩ := h₁.bij.2 (F.map biprod.inl ≫ g)
    obtain ⟨f₂, hf₂⟩ := h₂.bij.2 (F.map biprod.inr ≫ g)
    refine ⟨biprod.fst ≫ f₁ + biprod.snd ≫ f₂, ?_⟩
    change F.map (biprod.fst ≫ f₁ + biprod.snd ≫ f₂) = g
    rw [F.map_add, F.map_comp, F.map_comp, show F.map f₁ = F.map biprod.inl ≫ g from hf₁,
      show F.map f₂ = F.map biprod.inr ≫ g from hf₂, ← hsplit]
  · rw [hsplit g, h₁.neg k hk (F.map biprod.inl ≫ g), h₂.neg k hk (F.map biprod.inr ≫ g),
      comp_zero, comp_zero, add_zero]
  · obtain ⟨f₁, hf₁⟩ := h₁.one (F.map biprod.inl ≫ g)
    obtain ⟨f₂, hf₂⟩ := h₂.one (F.map biprod.inr ≫ g)
    refine ⟨biprod.fst ≫ f₁ + biprod.snd ≫ f₂, ?_⟩
    rw [F.map_add, Preadditive.add_comp, F.map_comp, F.map_comp, Category.assoc, Category.assoc,
      hf₁, hf₂, ← hsplit]

theorem good₂_Z {Y : DerivedCategory (ModuleCat.{0} ℤ)} (hY : Good F Y) : Good₂ F Z Y where
  bij := hY.bij
  neg := hY.neg
  one g := ⟨0, by rw [F.map_zero, zero_comp, hY.one g]⟩

theorem good₂_cyc {m : ℤ} (hm : m ≠ 0) {Y : DerivedCategory (ModuleCat.{0} ℤ)} (hY : Good F Y)
    (hYZ : ∀ z : Z⟦(1 : ℤ)⟧ ⟶ Y, z = 0) : Good₂ F (Zmod m) Y := by
  have hD := cycTriangle_distinguished hm
  have hT := cycTriangleF_distinguished (F := F) hm
  -- Morphisms out of `P⟦1⟧`.
  have hP1 : ∀ (k : ℤ) (z : (P F)⟦(1 : ℤ)⟧ ⟶ (F.obj Y)⟦k⟧), k ≤ 0 → z = 0 := by
    intro k z hk
    refine eq_zero_of_injective _ (shiftHomAddHom_injective _ _ 1) ?_ z
    intro y
    exact eq_zero_of_injective (homIsoAddEquiv _ ((shiftFunctorAdd' C k (-1) (k + -1) rfl).app
        (F.obj Y)).symm).toAddMonoidHom (homIsoAddEquiv _ _).injective
        (hY.neg (k + -1) (by omega)) y
  have hP1' : ∀ z : (P F)⟦(1 : ℤ)⟧ ⟶ F.obj Y, z = 0 := by
    intro z
    have := hP1 0 (z ≫ ((shiftFunctorZero C ℤ).app (F.obj Y)).inv) le_rfl
    rw [← cancel_mono ((shiftFunctorZero C ℤ).app (F.obj Y)).inv, this, zero_comp]
  refine ⟨⟨fun f f' hf => ?_, fun g => ?_⟩, fun k hk g => ?_, fun g => ?_⟩
  · -- injectivity
    have hf' : F.map (f - f') = 0 := by
      rw [F.map_sub]
      exact sub_eq_zero.mpr hf
    rw [← sub_eq_zero]
    have h0 : (cycTriangle hm).mor₂ ≫ (f - f') = 0 := hY.bij.1 (by
      change F.map (cycπ m ≫ (f - f')) = F.map 0
      rw [F.map_comp, hf', comp_zero, F.map_zero])
    obtain ⟨z, hz⟩ := Triangle.yoneda_exact₃ _ hD (f - f') h0
    rw [hz, hYZ z, comp_zero]
  · -- surjectivity
    obtain ⟨h₀, hh₀⟩ := hY.bij.2 (F.map (cycπ m) ≫ g)
    have h1 : (cycTriangle hm).mor₁ ≫ h₀ = 0 := hY.bij.1 (by
      change F.map ((m • 𝟙 Z) ≫ h₀) = F.map 0
      rw [F.map_comp, show F.map h₀ = F.map (cycπ m) ≫ g from hh₀, F.map_zero, ← Category.assoc,
        ← F.map_comp]
      change F.map ((cycTriangle hm).mor₁ ≫ (cycTriangle hm).mor₂) ≫ g = 0
      rw [comp_distTriang_mor_zero₁₂ _ hD, F.map_zero, zero_comp])
    obtain ⟨f₀, hf₀⟩ : ∃ f₀ : Zmod m ⟶ Y, h₀ = cycπ m ≫ f₀ := Triangle.yoneda_exact₂ _ hD h₀ h1
    have h2 : (cycTriangleF F hm).mor₂ ≫ (g - F.map f₀) = 0 := by
      change F.map (cycπ m) ≫ (g - F.map f₀) = 0
      rw [Preadditive.comp_sub, ← F.map_comp, ← hh₀]
      rw [← hf₀, sub_self]
    obtain ⟨z, hz⟩ := Triangle.yoneda_exact₃ _ hT _ h2
    refine ⟨f₀, ?_⟩
    change F.map f₀ = g
    rw [← sub_eq_zero, ← neg_sub, hz, hP1' z, comp_zero, neg_zero]
  · -- negative degrees
    have h2 : (cycTriangleF F hm).mor₂ ≫ g = 0 := hY.neg k hk _
    obtain ⟨z, hz⟩ := Triangle.yoneda_exact₃ _ hT g h2
    rw [hz, hP1 k z (by omega), comp_zero]
  · -- degree one
    have h2 : (cycTriangleF F hm).mor₂ ≫ g = 0 := hY.one _
    obtain ⟨z, hz⟩ := Triangle.yoneda_exact₃ _ hT g h2
    obtain ⟨v₀, hv₀⟩ := hY.bij.2 ((shiftFunctor C (1 : ℤ)).preimage z)
    refine ⟨(cycTriangle hm).mor₃ ≫ v₀⟦(1 : ℤ)⟧', ?_⟩
    rw [hz, F.map_comp, Category.assoc, F.commShiftIso_hom_naturality,
      show F.map v₀ = (shiftFunctor C (1 : ℤ)).preimage z from hv₀, Functor.map_preimage,
      ← Category.assoc]
    rfl

/-- The two-variable statements hold for finitely generated abelian groups in degree `0`. -/
theorem good₂_fg (h : Hyp F) {A B : DerivedCategory (ModuleCat.{0} ℤ)} (hA : fgSingle ℤ A)
    (hB : fgSingle ℤ B) : Good₂ F A B := by
  obtain ⟨M, hM, ⟨eA⟩⟩ := hA
  obtain ⟨N, hN, ⟨eB⟩⟩ := hB
  have hY : Good F B := (good_single h N hN).of_iso eB.symm
  have hYZ : ∀ z : Z⟦(1 : ℤ)⟧ ⟶ B, z = 0 := by
    intro z
    have : (Z⟦(1 : ℤ)⟧).IsLE (-1) := TStructure.t.isLE_shift Z 0 1 (-1) (by omega)
    have : B.IsGE 0 := TStructure.t.isGE_of_iso eB.symm 0
    exact TStructure.t.zero z (-1) 0 (by omega)
  have := preservesBinaryBiproducts_of_preservesBiproducts (singleFunctor (ModuleCat.{0} ℤ) 0)
  refine Good₂.of_iso_left ?_ eA.symm
  exact moduleCat_int_induction (fun M => Good₂ F ((singleFunctor (ModuleCat.{0} ℤ) 0).obj M) B)
    (fun e hM => hM.of_iso_left ((singleFunctor (ModuleCat.{0} ℤ) 0).mapIso e))
    (fun _ hM => Good₂.of_isZero_left (Functor.map_isZero _ hM))
    (fun M N hM hN => (hM.biprod_left hN).of_iso_left
      ((singleFunctor (ModuleCat.{0} ℤ) 0).mapBiprod M N).symm)
    (good₂_Z hY) (fun _ hm => good₂_cyc hm hY hYZ) M hM

/-! ### The heart family and `K₀` -/

/-- **The images of finitely generated abelian groups form a heart family** in `C`. -/
theorem isHeartFamily (h : Hyp F) : IsHeartFamily (mapHeart F (fgSingle ℤ)) :=
  isHeartFamily_fgSingle.map (fun hA hB g => (good₂_fg h hA hB).bij.2 g)
    (fun hA hB _ _ hff => (good₂_fg h hA hB).bij.1 hff)
    (fun hA hB k hk g => (good₂_fg h hA hB).neg k hk g)
    (fun hA hB g => (good₂_fg h hA hB).one g)

/-- `P` has a heart tower (with one cell). -/
theorem hasHeartTower_P : IsHeartFamily.HasHeartTower (mapHeart F (fgSingle ℤ)) (P F) :=
  ⟨0, HeartTower.of_shiftedProp ⟨P F, ⟨Z, ⟨ModuleCat.of ℤ ℤ, inferInstance, ⟨Iso.refl _⟩⟩,
    ⟨Iso.refl _⟩⟩, ⟨((shiftFunctorZero C ℤ).app (P F)).symm⟩⟩⟩

/-- Every object of the thick closure of `P` has a heart tower whose cells are images of shifted
finitely generated abelian groups. -/
theorem thickClosure_le [IsTriangulated C] (h : Hyp F) {S : ObjectProperty C}
    (hS : ∀ X, S X → Nonempty (X ≅ P F)) :
    ThickClosure S ≤ IsHeartFamily.HasHeartTower (mapHeart F (fgSingle ℤ)) :=
  DG.thickClosure_le (isHeartFamily h).isThick fun X hX =>
    let ⟨a, ha⟩ := hasHeartTower_P (F := F)
    ⟨a, ha.of_iso (hS X hX).some.symm⟩

section K0

variable {𝒦 : ObjectProperty C} [𝒦.IsTriangulated] [𝒦.IsClosedUnderIsomorphisms]
  (hP : 𝒦 (P F))
include hP

theorem mapHeart_prop : ∀ X, mapHeart F (fgSingle ℤ) X → 𝒦 X := by
  rintro X ⟨A, ⟨M, hM, ⟨eA⟩⟩, ⟨eX⟩⟩
  refine 𝒦.prop_of_iso (eX ≪≫ F.mapIso eA).symm ?_
  have := preservesBinaryBiproducts_of_preservesBiproducts (singleFunctor (ModuleCat.{0} ℤ) 0)
  have := preservesBinaryBiproducts_of_preservesBiproducts F
  refine moduleCat_int_induction
    (fun M => 𝒦 (F.obj ((singleFunctor (ModuleCat.{0} ℤ) 0).obj M)))
    (fun e hM => 𝒦.prop_of_iso (F.mapIso ((singleFunctor (ModuleCat.{0} ℤ) 0).mapIso e)) hM)
    (fun _ hM => 𝒦.prop_of_isZero (F.map_isZero (Functor.map_isZero _ hM)))
    (fun M N hM hN => 𝒦.prop_of_iso (F.mapIso
        ((singleFunctor (ModuleCat.{0} ℤ) 0).mapBiprod M N).symm)
      (𝒦.prop_of_iso (F.mapBiprod _ _).symm
        (𝒦.ext_of_isTriangulatedClosed₂ _ (binaryBiproductTriangle_distinguished _ _) hM hN)))
    hP (fun _ hm => 𝒦.ext_of_isTriangulatedClosed₃ _ (cycTriangleF_distinguished hm) hP hP) M hM

theorem mk_mapHeart_mem (X : C) (hX : mapHeart F (fgSingle ℤ) X) :
    K0.mk (⟨X, mapHeart_prop hP X hX⟩ : 𝒦.FullSubcategory) ∈
      AddSubgroup.zmultiples (K0.mk (⟨P F, hP⟩ : 𝒦.FullSubcategory)) := by
  obtain ⟨A, ⟨M, hM, ⟨eA⟩⟩, ⟨eX⟩⟩ := hX
  have hiso : ∀ {X Y : C} (hX : 𝒦 X) (hY : 𝒦 Y), (X ≅ Y) →
      K0.mk (⟨X, hX⟩ : 𝒦.FullSubcategory) = K0.mk ⟨Y, hY⟩ := fun _ _ e => K0.mk_eq_of_iso_obj e
  suffices H : ∀ (M : ModuleCat.{0} ℤ), Module.Finite ℤ M → ∃ hM' :
      𝒦 (F.obj ((singleFunctor (ModuleCat.{0} ℤ) 0).obj M)),
        K0.mk (⟨_, hM'⟩ : 𝒦.FullSubcategory) ∈
          AddSubgroup.zmultiples (K0.mk (⟨P F, hP⟩ : 𝒦.FullSubcategory)) by
    obtain ⟨hM', hmem⟩ := H M hM
    rwa [hiso _ hM' (eX ≪≫ F.mapIso eA)]
  have := preservesBinaryBiproducts_of_preservesBiproducts (singleFunctor (ModuleCat.{0} ℤ) 0)
  have := preservesBinaryBiproducts_of_preservesBiproducts F
  refine moduleCat_int_induction _ ?_ ?_ ?_ ?_ ?_
  · rintro M N e ⟨hM', hmem⟩
    have e' := F.mapIso ((singleFunctor (ModuleCat.{0} ℤ) 0).mapIso e)
    exact ⟨𝒦.prop_of_iso e' hM', by rwa [← hiso hM' _ e']⟩
  · intro M hM
    have hz := F.map_isZero (Functor.map_isZero (singleFunctor (ModuleCat.{0} ℤ) 0) hM)
    refine ⟨𝒦.prop_of_isZero hz, ?_⟩
    have hz0 : K0.mk (⟨_, 𝒦.prop_of_isZero hz⟩ : 𝒦.FullSubcategory) = 0 :=
      K0.mk_eq_zero_of_isZero ((IsZero.iff_id_eq_zero _).mpr (by
        ext
        exact hz.eq_of_src _ _))
    rw [hz0]
    exact zero_mem _
  · rintro M N ⟨hM', hmM⟩ ⟨hN', hmN⟩
    have hB := 𝒦.ext_of_isTriangulatedClosed₂ _ (binaryBiproductTriangle_distinguished _ _) hM' hN'
    have e : F.obj ((singleFunctor (ModuleCat.{0} ℤ) 0).obj (M ⊞ N)) ≅
        F.obj ((singleFunctor (ModuleCat.{0} ℤ) 0).obj M) ⊞
          F.obj ((singleFunctor (ModuleCat.{0} ℤ) 0).obj N) :=
      F.mapIso ((singleFunctor (ModuleCat.{0} ℤ) 0).mapBiprod M N) ≪≫ F.mapBiprod _ _
    refine ⟨𝒦.prop_of_iso e.symm hB, ?_⟩
    rw [hiso _ hB e, K0.mk_fullSubcategory_obj₂ _ (binaryBiproductTriangle_distinguished _ _)
      hM' hB hN']
    exact add_mem hmM hmN
  · exact ⟨hP, AddSubgroup.mem_zmultiples _⟩
  · intro m hm
    have hT := cycTriangleF_distinguished (F := F) hm
    have h₃ := 𝒦.ext_of_isTriangulatedClosed₃ _ hT hP hP
    refine ⟨h₃, ?_⟩
    have := K0.mk_fullSubcategory_obj₂ _ hT hP hP h₃
    have h0 : K0.mk (⟨(cycTriangleF F hm).obj₃, h₃⟩ : 𝒦.FullSubcategory) = 0 := by
      have := this
      exact (add_eq_left.mp this.symm)
    change K0.mk (⟨(cycTriangleF F hm).obj₃, h₃⟩ : 𝒦.FullSubcategory) ∈ _
    rw [h0]
    exact zero_mem _

/-- **`K₀` is generated by `[P]`**: in a triangulated subcategory `𝒦` of `C` containing `P` whose
objects have heart towers (e.g. contained in the thick closure of `P`), every class is an integer
multiple of `[P]`. -/
theorem exists_eq_zsmul
    (h𝒦 : ∀ X, 𝒦 X → IsHeartFamily.HasHeartTower (mapHeart F (fgSingle ℤ)) X)
    (x : K0 𝒦.FullSubcategory) : ∃ n : ℤ, x = n • K0.mk (⟨P F, hP⟩ : 𝒦.FullSubcategory) := by
  obtain ⟨X, rfl⟩ := K0.exists_mk_eq x
  obtain ⟨a, ha⟩ := h𝒦 X.obj X.property
  obtain ⟨hX', hmem⟩ := HeartTower.mk_mem_closure (mapHeart_prop hP) ha
  have hle : AddSubgroup.closure {x | ∃ (Y : C) (hY : mapHeart F (fgSingle ℤ) Y),
      x = K0.mk (⟨Y, mapHeart_prop hP Y hY⟩ : 𝒦.FullSubcategory)} ≤
        AddSubgroup.zmultiples (K0.mk (⟨P F, hP⟩ : 𝒦.FullSubcategory)) := by
    rw [AddSubgroup.closure_le]
    rintro _ ⟨Y, hY, rfl⟩
    exact mk_mapHeart_mem hP Y hY
  obtain ⟨n, hn⟩ := AddSubgroup.mem_zmultiples_iff.mp (hle hmem)
  exact ⟨n, hn.symm⟩

end K0

end IntegralHeart

end DG
