import DG.Derived.Resolution

/-!
# Minimal dg modules

A dg module `P` over a dg ring `A` is *minimal* if its differential takes values in the
*decomposable* elements, the sums of products `a • x` with `a` homogeneous of nonzero degree
(`DG.IsMinimal`, `DG.decomposables`). For a positive dg ring (no negative degrees) this is the
condition `d(P) ⊆ A^{>0} P` defining minimal semi-free modules: these are the minimal models of
dg modules (as opposed to Sullivan models of commutative dg algebras).

The main result is the uniqueness of minimal models: a homotopy equivalence between minimal
dg modules is an isomorphism (`DG.DGHomotopyEquiv.bijective_hom`), when `A` has no negative
degrees and the modules are bounded below, or `A` has no positive degrees and the modules are
bounded above (`DG.IsBoundedMinimal`). The argument is the usual one. If `h` is a homotopy from
`f` to the identity of `P`, then `v = id - f = -(d h + h d)` takes values in the decomposables.
In the first case, a decomposable homogeneous element of degree `m` lies in the span of the
`a • x` with `x` homogeneous of degree `< m` (`DG.degSpan`), so `v` lowers this filtration, which
is exhaustive and vanishes in low degrees: `v` is locally nilpotent, and `f = id - v` is
bijective, with inverse `∑ₖ vᵏ`. The second case is symmetric.

## Main definitions and results

* `DG.decomposables A P`, `DG.IsMinimal A P`, `DG.IsBoundedBelow P`, `DG.IsBoundedAbove P`,
  `DG.IsBoundedMinimal A P`; `DG.Cochain.map_mem_decomposables`,
  `DG.DGModuleHom.map_mem_decomposables`;
* `DG.degSpan A P s`: the span of the `a • x` with `x` homogeneous of degree in `s`;
  `DG.mem_degSpan_of_mem_decomposables`;
* `DG.bijective_sub_of_filtration`: an additive endomorphism lowering an exhaustive filtration
  which vanishes in some index is locally nilpotent, so `id - v` is bijective;
* `DG.IsBoundedMinimal.bijective_of_homotopic_id`: an endomorphism homotopic to the identity
  is bijective;
* `DG.DGHomotopyEquiv.bijective_hom`: **uniqueness of minimal models**, a homotopy equivalence
  between minimal bounded dg modules is bijective;
* `DG.IsKProjective.bijective_of_isQuasiIso`: a quasi-isomorphism between such modules which
  are K-projective is bijective; `DG.IsKProjective.exists_bijective_of_isBoundedMinimal`:
  minimal bounded K-projective resolutions of a dg module are isomorphic as dg modules,
  compatibly with the augmentations up to homotopy.
-/

open DirectSum

namespace DG

section Defs

variable (A : Type*) [Ring A] [DGAddCommGroup A] (P : Type*) [AddCommGroup P] [DGAddCommGroup P]
  [Module A P]

/-- The decomposable elements of a dg module: the additive subgroup generated by the products
`a • x` with `a` homogeneous of nonzero degree. -/
def decomposables : AddSubgroup P :=
  AddSubgroup.closure {y | ∃ (i : ℤ) (_ : i ≠ 0) (a : A) (_ : a ∈ grading i) (x : P), a • x = y}

/-- A dg module is *minimal* if its differential takes values in the decomposable elements. -/
def IsMinimal : Prop := ∀ x : P, d x ∈ decomposables A P

/-- The span of the products `a • x` with `x` homogeneous of degree in `s`. -/
def degSpan (s : Set ℤ) : AddSubgroup P :=
  AddSubgroup.closure {y | ∃ (i : ℤ) (_ : i ∈ s) (a : A) (x : P) (_ : x ∈ grading i), a • x = y}

/-- A graded abelian group is bounded below if its components of sufficiently negative degree
vanish. -/
def IsBoundedBelow : Prop := ∃ N : ℤ, ∀ i < N, ∀ x ∈ grading (M := P) i, x = 0

/-- A graded abelian group is bounded above if its components of sufficiently large degree
vanish. -/
def IsBoundedAbove : Prop := ∃ N : ℤ, ∀ i > N, ∀ x ∈ grading (M := P) i, x = 0

/-- The hypotheses for the uniqueness of minimal models: `P` is minimal, and either `A` has no
negative degrees and `P` is bounded below, or `A` has no positive degrees and `P` is bounded
above. -/
def IsBoundedMinimal : Prop :=
  IsMinimal A P ∧ (((∀ j < 0, ∀ a ∈ grading (M := A) j, a = 0) ∧ IsBoundedBelow P) ∨
    ((∀ j > 0, ∀ a ∈ grading (M := A) j, a = 0) ∧ IsBoundedAbove P))

end Defs

variable {A : Type*} [Ring A] [DGAddCommGroup A]
  {M N P : Type*} [AddCommGroup M] [DGAddCommGroup M] [Module A M]
  [AddCommGroup N] [DGAddCommGroup N] [Module A N]
  [AddCommGroup P] [DGAddCommGroup P] [Module A P]

/-! ### Decomposable elements -/

omit [DGAddCommGroup P] in
theorem smul_mem_decomposables {i : ℤ} (hi : i ≠ 0) {a : A} (ha : a ∈ grading i) (x : P) :
    a • x ∈ decomposables A P :=
  AddSubgroup.subset_closure ⟨i, hi, a, ha, x, rfl⟩

/-- Cochains of the Hom complex preserve decomposable elements. -/
theorem Cochain.map_mem_decomposables {n : ℤ} (z : Cochain A M N n) {y : M}
    (hy : y ∈ decomposables A M) : z y ∈ decomposables A N := by
  induction hy using AddSubgroup.closure_induction with
  | mem y hy =>
    obtain ⟨i, hi, a, ha, x, rfl⟩ := hy
    rw [z.map_smul ha, Units.smul_def]
    exact zsmul_mem (smul_mem_decomposables hi ha _) _
  | zero => rw [map_zero]; exact zero_mem _
  | add y y' _ _ h h' => rw [map_add]; exact add_mem h h'
  | neg y _ h => rw [map_neg]; exact neg_mem h

/-- Morphisms of dg modules preserve decomposable elements. -/
theorem DGModuleHom.map_mem_decomposables (f : M →ᵈᵍ[A] N) {y : M}
    (hy : y ∈ decomposables A M) : f y ∈ decomposables A N :=
  (Cochain.ofHom f).map_mem_decomposables hy

/-! ### The spans `degSpan s` -/

omit [DGAddCommGroup A] in
theorem degSpan_mono {s s' : Set ℤ} (h : s ⊆ s') : degSpan A P s ≤ degSpan A P s' :=
  AddSubgroup.closure_mono fun _ ⟨i, hi, a, x, hx, hy⟩ => ⟨i, h hi, a, x, hx, hy⟩

omit [DGAddCommGroup A] in
theorem smul_mem_degSpan_of_mem {s : Set ℤ} {i : ℤ} (hi : i ∈ s) (a : A) {x : P}
    (hx : x ∈ grading i) : a • x ∈ degSpan A P s :=
  AddSubgroup.subset_closure ⟨i, hi, a, x, hx, rfl⟩

omit [DGAddCommGroup A] in
/-- `degSpan s` is stable under the action of `A`. -/
theorem smul_mem_degSpan (a : A) {s : Set ℤ} {y : P} (hy : y ∈ degSpan A P s) :
    a • y ∈ degSpan A P s := by
  induction hy using AddSubgroup.closure_induction with
  | mem y hy =>
    obtain ⟨i, hi, b, x, hx, rfl⟩ := hy
    rw [smul_smul]
    exact smul_mem_degSpan_of_mem hi _ hx
  | zero => rw [smul_zero]; exact zero_mem _
  | add y y' _ _ h h' => rw [smul_add]; exact add_mem h h'
  | neg y _ h => rw [smul_neg]; exact neg_mem h

omit [DGAddCommGroup A] in
theorem mem_degSpan_of_mem_grading {s : Set ℤ} {i : ℤ} (hi : i ∈ s) {x : P}
    (hx : x ∈ grading i) : x ∈ degSpan A P s := by
  rw [← one_smul A x]
  exact smul_mem_degSpan_of_mem hi _ hx

omit [DGAddCommGroup A] in
/-- If `Pⁱ = 0` for `i ∈ s`, then `degSpan s = 0`. -/
theorem eq_zero_of_mem_degSpan {s : Set ℤ} (hs : ∀ i ∈ s, ∀ x ∈ grading (M := P) i, x = 0)
    {y : P} (hy : y ∈ degSpan A P s) : y = 0 := by
  induction hy using AddSubgroup.closure_induction with
  | mem y hy =>
    obtain ⟨i, hi, a, x, hx, rfl⟩ := hy
    rw [hs i hi x hx, smul_zero]
  | zero => rfl
  | add y y' _ _ h h' => rw [h, h', add_zero]
  | neg y _ h => rw [h, neg_zero]

omit [DGAddCommGroup A] in
/-- Every element lies in `degSpan (Set.Iio c)` for some `c`. -/
theorem exists_mem_degSpan_Iio (y : P) : ∃ c, y ∈ degSpan A P (Set.Iio c) := by
  induction y using DG.induction_on with
  | h_zero => exact ⟨0, zero_mem _⟩
  | @h_homogeneous i x =>
    exact ⟨i + 1,
      mem_degSpan_of_mem_grading (s := Set.Iio (i + 1)) (Set.mem_Iio.mpr (by omega)) x.2⟩
  | h_add y y' h h' =>
    obtain ⟨c, hc⟩ := h
    obtain ⟨c', hc'⟩ := h'
    exact ⟨max c c', add_mem (degSpan_mono (Set.Iio_subset_Iio (le_max_left c c')) hc)
      (degSpan_mono (Set.Iio_subset_Iio (le_max_right c c')) hc')⟩

omit [DGAddCommGroup A] in
/-- Every element lies in `degSpan (Set.Ioi c)` for some `c`. -/
theorem exists_mem_degSpan_Ioi (y : P) : ∃ c, y ∈ degSpan A P (Set.Ioi c) := by
  induction y using DG.induction_on with
  | h_zero => exact ⟨0, zero_mem _⟩
  | @h_homogeneous i x =>
    exact ⟨i - 1,
      mem_degSpan_of_mem_grading (s := Set.Ioi (i - 1)) (Set.mem_Ioi.mpr (by omega)) x.2⟩
  | h_add y y' h h' =>
    obtain ⟨c, hc⟩ := h
    obtain ⟨c', hc'⟩ := h'
    exact ⟨min c c', add_mem (degSpan_mono (Set.Ioi_subset_Ioi (min_le_left c c')) hc)
      (degSpan_mono (Set.Ioi_subset_Ioi (min_le_right c c')) hc')⟩

section Decomposables

variable [DGModule A P]

/-- The homogeneous component of degree `m` of `a • y`, for `a` of degree `j`, is `a` times the
component of degree `m - j` of `y`. -/
theorem coe_decompose_smul {j : ℤ} {a : A} (ha : a ∈ grading j) (y : P) (m : ℤ) :
    (decompose (grading (M := P)) (a • y) m : P) =
      a • (decompose (grading (M := P)) y (m - j) : P) := by
  induction y using DG.induction_on with
  | h_zero => simp
  | @h_homogeneous i y =>
    have hay : a • (y : P) ∈ grading (j + i) := smul_mem_grading ha y.2
    by_cases h : j + i = m
    · subst h
      rw [decompose_of_mem_same _ hay, show j + i - j = i by ring, decompose_of_mem_same _ y.2]
    · rw [decompose_of_mem_ne _ hay h, decompose_of_mem_ne _ y.2 (by omega), smul_zero]
  | h_add y y' h h' =>
    simp only [smul_add, decompose_add, DirectSum.add_apply, AddMemClass.coe_add, h, h']

/-- A decomposable homogeneous element of degree `m` lies in `degSpan s` if `m - j ∈ s` for
every nonzero degree `j` in which `A` is nonzero. -/
theorem mem_degSpan_of_mem_decomposables {s : Set ℤ} {m : ℤ}
    (hs : ∀ j ≠ 0, ∀ a ∈ grading (M := A) j, a ≠ 0 → m - j ∈ s) {x : P} (hx : x ∈ grading m)
    (hd : x ∈ decomposables A P) : x ∈ degSpan A P s := by
  suffices h : ∀ y ∈ decomposables A P, (decompose (grading (M := P)) y m : P) ∈ degSpan A P s by
    simpa [decompose_of_mem_same _ hx] using h x hd
  intro y hy
  induction hy using AddSubgroup.closure_induction with
  | mem y hy =>
    obtain ⟨j, hj, a, ha, x, rfl⟩ := hy
    rw [coe_decompose_smul ha]
    by_cases ha0 : a = 0
    · rw [ha0, zero_smul]
      exact zero_mem _
    · exact smul_mem_degSpan_of_mem (hs j hj a ha ha0) a
        (decompose (grading (M := P)) x (m - j)).2
  | zero => simp
  | add y y' _ _ h h' => simpa using add_mem h h'
  | neg y _ h =>
    rw [decompose_neg, DFinsupp.neg_apply, NegMemClass.coe_neg]
    exact neg_mem h

/-- An endomorphism of dg modules with values in the decomposables maps `degSpan s` into
`degSpan s'` if `i - j ∈ s'` for `i ∈ s` and every nonzero degree `j` in which `A` is
nonzero. -/
theorem map_mem_degSpan (v : P →ᵈᵍ[A] P) (hv : ∀ x, v x ∈ decomposables A P) {s s' : Set ℤ}
    (hss' : ∀ i ∈ s, ∀ j ≠ 0, ∀ a ∈ grading (M := A) j, a ≠ 0 → i - j ∈ s') {y : P}
    (hy : y ∈ degSpan A P s) : v y ∈ degSpan A P s' := by
  induction hy using AddSubgroup.closure_induction with
  | mem y hy =>
    obtain ⟨i, hi, a, x, hx, rfl⟩ := hy
    rw [map_smul]
    exact smul_mem_degSpan a
      (mem_degSpan_of_mem_decomposables (hss' i hi) (v.map_mem hx) (hv x))
  | zero => rw [map_zero]; exact zero_mem _
  | add y y' _ _ h h' => rw [map_add]; exact add_mem h h'
  | neg y _ h => rw [map_neg]; exact neg_mem h

end Decomposables

/-! ### Locally nilpotent endomorphisms -/

omit [DGAddCommGroup P] in
/-- If `v` is a locally nilpotent additive endomorphism, then `id - v` is bijective, with
inverse `∑ₖ vᵏ`. -/
theorem bijective_sub_of_locallyNilpotent (v : P →+ P) (hv : ∀ y, ∃ k : ℕ, v^[k] y = 0) :
    Function.Bijective fun y => y - v y := by
  refine ⟨fun y y' hyy' => ?_, fun y => ?_⟩
  · have h₁ : y - y' = v y - v y' := sub_eq_sub_iff_sub_eq_sub.mp hyy'
    have hz : v (y - y') = y - y' := by rw [map_sub, h₁]
    obtain ⟨k, hk⟩ := hv (y - y')
    rw [Function.iterate_fixed hz] at hk
    exact sub_eq_zero.mp hk
  · obtain ⟨k, hk⟩ := hv y
    refine ⟨∑ i ∈ Finset.range k, v^[i] y, ?_⟩
    have h := Finset.sum_range_sub' (fun i => v^[i] y) k
    simp only [Function.iterate_zero_apply, hk, sub_zero] at h
    show (∑ i ∈ Finset.range k, v^[i] y) - v (∑ i ∈ Finset.range k, v^[i] y) = y
    rw [map_sum, ← Finset.sum_sub_distrib]
    simp_rw [← Function.iterate_succ_apply' v]
    exact h

omit [DGAddCommGroup P] in
/-- An additive endomorphism `v` which lowers an exhaustive increasing filtration `F` vanishing
in some index (`v (F c) ⊆ F (c - 1)`) is locally nilpotent, so `id - v` is bijective. -/
theorem bijective_sub_of_filtration (v : P →+ P) (F : ℤ → AddSubgroup P) (hF : Monotone F)
    (hex : ∀ y, ∃ c, y ∈ F c) (N : ℤ) (hN : ∀ y ∈ F N, y = 0)
    (hv : ∀ c, ∀ y ∈ F c, v y ∈ F (c - 1)) : Function.Bijective fun y => y - v y := by
  have hiter : ∀ (k : ℕ) {c : ℤ} {y : P}, y ∈ F c → v^[k] y ∈ F (c - k) := by
    intro k
    induction k with
    | zero => intro c y hy; simpa using hy
    | succ k ih =>
      intro c y hy
      rw [Function.iterate_succ_apply']
      have := hv _ _ (ih hy)
      rwa [show c - (k : ℤ) - 1 = c - ((k + 1 : ℕ) : ℤ) by push_cast; ring] at this
  refine bijective_sub_of_locallyNilpotent v fun y => ?_
  obtain ⟨c, hc⟩ := hex y
  exact ⟨(c - N).toNat, hN _ (hF (by omega) (hiter _ hc))⟩

/-! ### Uniqueness of minimal models -/

section Uniqueness

variable [DGModule A M] [DGModule A N] [DGModule A P]

/-- If `P` is minimal and `f` is homotopic to the identity, `x - f x` is decomposable. -/
theorem IsMinimal.sub_mem_decomposables (hP : IsMinimal A P) {f : P →ᵈᵍ[A] P}
    (h : Homotopic f DGModuleHom.id) (x : P) : x - f x ∈ decomposables A P := by
  have hx := h.some.comm x
  have : x - f x = -(d (h.some.hom x) + h.some.hom (d x)) := by
    rw [hx, DGModuleHom.id_apply]
    abel
  rw [this]
  exact neg_mem (add_mem (hP _) (h.some.hom.map_mem_decomposables (hP x)))

/-- An endomorphism `f` of a minimal bounded dg module (`DG.IsBoundedMinimal`) which is
homotopic to the identity is bijective: `id - f = -(d h + h d)` takes values in the
decomposables, hence is locally nilpotent. -/
theorem IsBoundedMinimal.bijective_of_homotopic_id (hP : IsBoundedMinimal A P)
    {f : P →ᵈᵍ[A] P} (h : Homotopic f DGModuleHom.id) : Function.Bijective f := by
  let v : P →ᵈᵍ[A] P := DGModuleHom.id - f
  have hv : ∀ x, v x ∈ decomposables A P := hP.1.sub_mem_decomposables h
  have hf : ⇑f = fun y => y - v.toLinearMap.toAddMonoidHom y := funext fun x => by
    change f x = x - (x - f x)
    abel
  rw [hf]
  rcases hP.2 with ⟨hA, N, hN⟩ | ⟨hA, N, hN⟩
  · refine bijective_sub_of_filtration _ (fun c => degSpan A P (Set.Iio c))
      (fun c c' h => degSpan_mono (Set.Iio_subset_Iio h)) exists_mem_degSpan_Iio N
      (fun _ => eq_zero_of_mem_degSpan fun i hi => hN i hi) fun c y hy => ?_
    refine map_mem_degSpan v hv (fun i hi j hj a ha ha0 => ?_) hy
    have : 0 < j := lt_of_le_of_ne (not_lt.mp fun hj' => ha0 (hA j hj' a ha)) hj.symm
    exact Set.mem_Iio.mpr (by have := Set.mem_Iio.mp hi; omega)
  · refine bijective_sub_of_filtration _ (fun c => degSpan A P (Set.Ioi (-c)))
      (fun c c' h => degSpan_mono (Set.Ioi_subset_Ioi (by omega))) (fun y => ?_) (-N)
      (fun _ => eq_zero_of_mem_degSpan fun i hi => hN i (by
        have := Set.mem_Ioi.mp hi; omega)) fun c y hy => ?_
    · obtain ⟨c, hc⟩ := exists_mem_degSpan_Ioi (A := A) y
      exact ⟨-c, by simpa using hc⟩
    refine map_mem_degSpan v hv (fun i hi j hj a ha ha0 => ?_) hy
    have : j < 0 := lt_of_le_of_ne (not_lt.mp fun hj' => ha0 (hA j hj' a ha)) hj
    exact Set.mem_Ioi.mpr (by have := Set.mem_Ioi.mp hi; omega)

omit [DGModule A P] in
theorem IsBoundedMinimal.of_nonneg (hA : ∀ j < 0, ∀ a ∈ grading (M := A) j, a = 0)
    (hP : IsMinimal A P) (hPb : IsBoundedBelow P) : IsBoundedMinimal A P :=
  ⟨hP, Or.inl ⟨hA, hPb⟩⟩

omit [DGModule A P] in
theorem IsBoundedMinimal.of_nonpos (hA : ∀ j > 0, ∀ a ∈ grading (M := A) j, a = 0)
    (hP : IsMinimal A P) (hPb : IsBoundedAbove P) : IsBoundedMinimal A P :=
  ⟨hP, Or.inr ⟨hA, hPb⟩⟩

/-- **Uniqueness of minimal models**: a homotopy equivalence between minimal bounded dg
modules (over a dg ring without negative degrees, between bounded-below modules; or without
positive degrees, between bounded-above modules) is bijective, hence an isomorphism of dg
modules. -/
theorem DGHomotopyEquiv.bijective_hom (e : DGHomotopyEquiv A M N) (hM : IsBoundedMinimal A M)
    (hN : IsBoundedMinimal A N) : Function.Bijective e.hom := by
  have h₁ := hM.bijective_of_homotopic_id ⟨e.homotopyHomInvId⟩
  have h₂ := hN.bijective_of_homotopic_id ⟨e.homotopyInvHomId⟩
  refine ⟨fun x y hxy => h₁.1 (by simp only [DGModuleHom.comp_apply, hxy]), fun y => ?_⟩
  obtain ⟨z, hz⟩ := h₂.2 y
  exact ⟨e.inv z, hz⟩

end Uniqueness

/-! ### Minimal K-projective resolutions -/

section KProjective

universe w

variable {A : Type*} [Ring A] [DGAddCommGroup A] [DGRing A]
  {P P' M : Type w} [AddCommGroup P] [DGAddCommGroup P] [Module A P] [DGModule A P]
  [AddCommGroup P'] [DGAddCommGroup P'] [Module A P'] [DGModule A P']
  [AddCommGroup M] [DGAddCommGroup M] [Module A M] [DGModule A M]

/-- A quasi-isomorphism between minimal bounded K-projective dg modules is bijective, hence an
isomorphism of dg modules. -/
theorem IsKProjective.bijective_of_isQuasiIso (hP : IsKProjective.{w} A P)
    (hP' : IsKProjective.{w} A P') (hPm : IsBoundedMinimal A P) (hP'm : IsBoundedMinimal A P')
    {f : P →ᵈᵍ[A] P'} (hf : f.IsQuasiIso) : Function.Bijective f := by
  obtain ⟨e, he, -⟩ :=
    hP.exists_dgHomotopyEquiv hP' hf (DGModuleHom.isQuasiIso_id (A := A) (M := P'))
  rw [DGModuleHom.id_comp] at he
  have h₁ : Homotopic (e.inv.comp f) DGModuleHom.id :=
    (he.symm.comp_right e.inv).trans ⟨e.homotopyHomInvId⟩
  have h₂ : Homotopic (f.comp e.inv) DGModuleHom.id :=
    (he.symm.comp_left e.inv).trans ⟨e.homotopyInvHomId⟩
  exact DGHomotopyEquiv.bijective_hom ⟨f, e.inv, h₁.some, h₂.some⟩ hPm hP'm

/-- **Uniqueness of minimal resolutions**: two minimal bounded K-projective resolutions
`p : P → M`, `p' : P' → M` of a dg module are isomorphic: there is a bijective morphism of dg
modules `e : P → P'` with `p' ∘ e` homotopic to `p`. -/
theorem IsKProjective.exists_bijective_of_isBoundedMinimal (hP : IsKProjective.{w} A P)
    (hP' : IsKProjective.{w} A P') (hPm : IsBoundedMinimal A P) (hP'm : IsBoundedMinimal A P')
    {p : P →ᵈᵍ[A] M} (hp : p.IsQuasiIso) {p' : P' →ᵈᵍ[A] M} (hp' : p'.IsQuasiIso) :
    ∃ e : P →ᵈᵍ[A] P', Function.Bijective e ∧ Homotopic (p'.comp e) p := by
  obtain ⟨e, he, -⟩ := hP.exists_dgHomotopyEquiv hP' hp hp'
  exact ⟨e.hom, DGHomotopyEquiv.bijective_hom e hPm hP'm, he⟩

end KProjective

end DG
