import DG.Compact.HeartTower
import Mathlib.Algebra.Homology.DerivedCategory.TStructure
import Mathlib.Algebra.Homology.DerivedCategory.FullyFaithful
import Mathlib.Algebra.Homology.DerivedCategory.SingleTriangle
import Mathlib.Algebra.Homology.DerivedCategory.HomologySequence
import Mathlib.Algebra.Homology.ShortComplex.ModuleCat
import Mathlib.CategoryTheory.Triangulated.TStructure.TruncLTGE
import Mathlib.RingTheory.Noetherian.Basic
import Mathlib.CategoryTheory.Idempotents.Basic

/-!
# The finitely generated modules form a heart family in the derived category

Let `R` be a (left) noetherian ring. In Mathlib's derived category `D(R)` of `R`-modules, the
objects isomorphic to a finitely generated module placed in degree `0`
(`DG.fgSingle R`) satisfy the axioms of a heart family (`DG.isHeartFamily_fgSingle`):

* `Hom(M, N⟦k⟧) = 0` for `k < 0` (the canonical t-structure);
* the cone of `f : M ⟶ N` is an extension of `coker f` by `(ker f)⟦1⟧` (octahedral axiom
  applied to `f = (M ↠ im f) ≫ (im f ↪ N)` and the triangles of the short exact sequences
  `0 → ker f → M → im f → 0`, `0 → im f → N → coker f → 0`);
* an extension of `N` by `M` lies in the heart of the canonical t-structure, hence is a module
  in degree `0`, finitely generated by the exact sequence `M → H⁰ → N` (`R` is noetherian);
* idempotents split in the category of modules.

With `DG.IsHeartFamily.isThick` (`DG/Compact/HeartTower.lean`), objects of `D(R)` obtained from
finitely generated modules by shifts, extensions and direct summands have towers whose
subquotients are shifted finitely generated modules.
-/

universe w u

namespace DG

open CategoryTheory Limits Pretriangulated DerivedCategory

variable {R : Type u} [Ring R]

/-- In an exact sequence `X₁ → X₂ → X₃` of modules over a noetherian ring, if `X₁` and `X₃` are
finitely generated, so is `X₂`. -/
theorem _root_.CategoryTheory.ShortComplex.Exact.moduleCat_finite [IsNoetherianRing R]
    {S : ShortComplex (ModuleCat.{u} R)} (hS : S.Exact) (h₁ : Module.Finite R S.X₁)
    (h₃ : Module.Finite R S.X₃) : Module.Finite R S.X₂ := by
  refine ⟨Submodule.fg_of_fg_map_of_fg_inf_ker S.g.hom ?_ ?_⟩
  · exact IsNoetherian.noetherian _
  · rw [top_inf_eq, ← hS.moduleCat_range_eq_ker, LinearMap.range_eq_map]
    exact h₁.fg_top.map _

/-- A module isomorphic in `ModuleCat` to a finitely generated module is finitely generated. -/
theorem moduleFinite_of_iso {M N : ModuleCat.{u} R} (e : M ≅ N) (hM : Module.Finite R M) :
    Module.Finite R N :=
  Module.Finite.equiv e.toLinearEquiv

variable (R) [HasDerivedCategory.{w} (ModuleCat.{u} R)]

/-- The objects of `D(R)` isomorphic to a finitely generated `R`-module in degree `0`. -/
def fgSingle : ObjectProperty (DerivedCategory (ModuleCat.{u} R)) :=
  fun X => ∃ M : ModuleCat.{u} R, Module.Finite R M ∧
    Nonempty (X ≅ (singleFunctor (ModuleCat.{u} R) 0).obj M)

variable {R}

/-- `H⁰` of a finitely generated module in degree `0` is finitely generated. -/
theorem moduleFinite_homology_single {M : ModuleCat.{u} R} (hM : Module.Finite R M)
    {X : DerivedCategory (ModuleCat.{u} R)} (e : X ≅ (singleFunctor (ModuleCat.{u} R) 0).obj M) :
    Module.Finite R ((homologyFunctor (ModuleCat.{u} R) 0).obj X) :=
  moduleFinite_of_iso ((homologyFunctor (ModuleCat.{u} R) 0).mapIso e ≪≫
    (singleFunctorCompHomologyFunctorIso (ModuleCat.{u} R) 0).app M).symm hM

variable [IsNoetherianRing R]

/-- **The finitely generated modules in degree `0` form a heart family** in the derived category
of a noetherian ring. -/
theorem isHeartFamily_fgSingle : IsHeartFamily (fgSingle R) where
  prop_of_iso e := fun ⟨M, hM, ⟨e'⟩⟩ => ⟨M, hM, ⟨e.symm ≪≫ e'⟩⟩
  hom_eq_zero := by
    rintro X Y ⟨M, -, ⟨eX⟩⟩ ⟨N, -, ⟨eY⟩⟩ k hk f
    have : X.IsLE 0 := TStructure.t.isLE_of_iso eX.symm 0
    have : Y.IsGE 0 := TStructure.t.isGE_of_iso eY.symm 0
    have : (Y⟦k⟧).IsGE (-k) := TStructure.t.isGE_shift Y 0 k (-k) (by omega)
    exact TStructure.t.zero f 0 (-k) (by omega)
  cone := by
    rintro T hT ⟨M, hM, ⟨e₁⟩⟩ ⟨N, hN, ⟨e₂⟩⟩
    let f₀ : M ⟶ N := (singleFunctor (ModuleCat.{u} R) 0).preimage (e₁.inv ≫ T.mor₁ ≫ e₂.hom)
    have hf₀ : (singleFunctor (ModuleCat.{u} R) 0).map f₀ = e₁.inv ≫ T.mor₁ ≫ e₂.hom :=
      Functor.map_preimage _ _
    -- The two short exact sequences.
    let S₁ : ShortComplex (ModuleCat.{u} R) :=
      ShortComplex.mk (ModuleCat.ofHom (LinearMap.ker f₀.hom).subtype)
        (ModuleCat.ofHom f₀.hom.rangeRestrict) (by ext x; simp)
    have hS₁ : S₁.ShortExact := ModuleCat.shortComplex_shortExact S₁
      (LinearMap.exact_iff.mpr (by
        change LinearMap.ker f₀.hom.rangeRestrict = LinearMap.range (LinearMap.ker f₀.hom).subtype
        rw [LinearMap.ker_rangeRestrict, Submodule.range_subtype]))
      (LinearMap.ker f₀.hom).injective_subtype
      f₀.hom.surjective_rangeRestrict
    let S₂ : ShortComplex (ModuleCat.{u} R) :=
      ShortComplex.mk (ModuleCat.ofHom (LinearMap.range f₀.hom).subtype)
        (ModuleCat.ofHom (LinearMap.range f₀.hom).mkQ) (by ext x; simp)
    have hS₂ : S₂.ShortExact := ModuleCat.shortComplex_shortExact S₂
      (LinearMap.exact_subtype_mkQ _) (LinearMap.range f₀.hom).injective_subtype
      (LinearMap.range f₀.hom).mkQ_surjective
    have hcomp : S₁.g ≫ S₂.f = f₀ := by ext x; rfl
    -- `T` with first morphism `F f₀`.
    let T' : Triangle (DerivedCategory (ModuleCat.{u} R)) :=
      Triangle.mk ((singleFunctor (ModuleCat.{u} R) 0).map f₀) (e₂.inv ≫ T.mor₂)
        (T.mor₃ ≫ e₁.hom⟦(1 : ℤ)⟧')
    have hT' : T' ∈ distTriang _ := isomorphic_distinguished T hT T'
      (Triangle.isoMk _ _ e₁.symm e₂.symm (Iso.refl _) (by simp [T', hf₀]) (by simp [T'])
        (by simp [T', ← Functor.map_comp]))
    have h₁₂ := rot_of_distTriang _ hS₁.singleTriangle_distinguished
    have h₂₃ := hS₂.singleTriangle_distinguished
    let o := Triangulated.someOctahedron
      (show (singleFunctor (ModuleCat.{u} R) 0).map S₁.g ≫
        (singleFunctor (ModuleCat.{u} R) 0).map S₂.f =
          (singleFunctor (ModuleCat.{u} R) 0).map f₀ by rw [← Functor.map_comp, hcomp])
      h₁₂ h₂₃ hT'
    refine ⟨_, _, o.m₁, o.m₃, _, o.mem, ⟨(singleFunctor (ModuleCat.{u} R) 0).obj S₁.X₁,
      ⟨S₁.X₁, ?_, ⟨Iso.refl _⟩⟩, ⟨Iso.refl _⟩⟩, ⟨S₂.X₃, ?_, ⟨Iso.refl _⟩⟩⟩
    · exact Module.Finite.of_injective (LinearMap.ker f₀.hom).subtype
        (LinearMap.ker f₀.hom).injective_subtype
    · exact Module.Finite.of_surjective _ (LinearMap.range f₀.hom).mkQ_surjective
  ext := by
    rintro T hT ⟨M, hM, ⟨e₁⟩⟩ ⟨N, hN, ⟨e₃⟩⟩
    have : T.obj₁.IsLE 0 := TStructure.t.isLE_of_iso e₁.symm 0
    have : T.obj₁.IsGE 0 := TStructure.t.isGE_of_iso e₁.symm 0
    have : T.obj₃.IsLE 0 := TStructure.t.isLE_of_iso e₃.symm 0
    have : T.obj₃.IsGE 0 := TStructure.t.isGE_of_iso e₃.symm 0
    have : T.obj₂.IsLE 0 := TStructure.t.isLE₂ T hT 0 inferInstance inferInstance
    have : T.obj₂.IsGE 0 := TStructure.t.isGE₂ T hT 0 inferInstance inferInstance
    obtain ⟨E, ⟨e⟩⟩ := T.obj₂.exists_iso_singleFunctor_obj_of_isGE_of_isLE 0
    refine ⟨E, ?_, ⟨e⟩⟩
    have hH : Module.Finite R ((homologyFunctor (ModuleCat.{u} R) 0).obj T.obj₂) :=
      ((homologyFunctor (ModuleCat.{u} R) 0).map_distinguished_exact T hT).moduleCat_finite
        (moduleFinite_homology_single hM e₁) (moduleFinite_homology_single hN e₃)
    exact moduleFinite_of_iso ((homologyFunctor (ModuleCat.{u} R) 0).mapIso e ≪≫
      (singleFunctorCompHomologyFunctorIso (ModuleCat.{u} R) 0).app E) hH
  split := by
    rintro X ⟨M, hM, ⟨eX⟩⟩ e he
    let e₀ : M ⟶ M := (singleFunctor (ModuleCat.{u} R) 0).preimage (eX.inv ≫ e ≫ eX.hom)
    have he₀ : (singleFunctor (ModuleCat.{u} R) 0).map e₀ = eX.inv ≫ e ≫ eX.hom :=
      Functor.map_preimage _ _
    have he₀' : e₀ ≫ e₀ = e₀ := (singleFunctor (ModuleCat.{u} R) 0).map_injective (by
      rw [Functor.map_comp, he₀]
      simp [reassoc_of% he])
    obtain ⟨Y, i, p, hip, hpi⟩ :=
      (inferInstance : IsIdempotentComplete (ModuleCat.{u} R)).idempotents_split M e₀ he₀'
    refine ⟨(singleFunctor (ModuleCat.{u} R) 0).obj Y,
      (singleFunctor (ModuleCat.{u} R) 0).map i ≫ eX.inv,
      eX.hom ≫ (singleFunctor (ModuleCat.{u} R) 0).map p, ⟨Y, ?_, ⟨Iso.refl _⟩⟩, ?_, ?_⟩
    · have hsurj : Function.Surjective p.hom := fun y =>
        ⟨i.hom y, by rw [← ModuleCat.comp_apply, hip]; rfl⟩
      exact Module.Finite.of_surjective _ hsurj
    · simp [← Functor.map_comp, hip]
    · rw [Category.assoc, ← Functor.map_comp_assoc, hpi, he₀]
      simp

end DG
