import DG.Derived.Comparison
import DG.Derived.ExternalTensorCompact
import DG.Derived.PerfectThick
import Mathlib.RingTheory.Finiteness.Projective

/-!
# Compact objects of the derived category of a ring are the perfect complexes

Let `R` be a ring. The perfect objects of Mathlib's derived category of `R`-modules
(`DG.IsPerfect R`: the objects isomorphic to a strictly bounded complex of finitely generated
projective modules) form a thick subcategory (`DG.IsPerfect.isThick`). This file shows that it is
the thick subcategory generated by `R` placed in degree `0`, and, for a commutative ring `R`,
identifies it with the compact objects of the derived category `D(R)` of dg modules over `R`
(concentrated in degree `0`) under the comparison equivalence
`DG.DerivedCategory.comparisonEquivalence R : D(R) ≌ D(Mod R)` (`DG/Derived/Comparison.lean`).

## Main results

* `DG.IsPerfect.le_of_isThick`: a thick subcategory of `D(Mod R)` containing `R[0]` contains
  every perfect object. A finitely generated projective module is a direct summand of some
  `Rⁿ` (`Module.Finite.exists_comp_eq_id_of_projective`), and `Rⁿ[0]` is a finite direct sum
  of copies of `R[0]`; the general case follows from the induction principle
  `DG.IsPerfect.induction`.
* `DG.IsPerfect.thickClosure_eq`: for any ring `R`, the perfect objects are exactly the thick
  closure of `R[0]`.
* `DG.DerivedCategory.isCompact_iff_isPerfect`: for a commutative ring `R`, an object `X` of
  `D(R)` is compact if and only if its image in `D(Mod R)` is perfect. One inclusion follows
  from the description of the compact objects as the thick closure of `R`
  (`DG.DerivedCategory.thickClosure_self_eq_isCompact`, Keller's theorem), the other from
  `DG.IsPerfect.le_of_isThick` applied to the thick subcategory of objects whose image in
  `D(R)` is compact.

## Universes

Compactness refers to coproducts indexed by types in the universe `u` of `R`, and uses a model of
`D(R)` with morphisms in `Type u` (`[DG.HasDerivedCategory.{u, u} R]`), as needed for the
description of the compact objects as a thick closure. The model of Mathlib's derived category
is arbitrary.
-/

open CategoryTheory Category Limits Pretriangulated ZeroObject

universe w u

namespace DG

/-! ### Perfect complexes are the thick closure of the ring -/

/-- The ring `R` is a finitely generated projective module over itself. -/
theorem IsFGProjective.self (R : Type u) [Ring R] : IsFGProjective R (ModuleCat.of R R) :=
  ⟨inferInstance, inferInstance⟩

namespace IsPerfect

variable {R : Type u} [Ring R] [_root_.HasDerivedCategory.{w} (ModuleCat.{u} R)]

section Thick

variable {P : ObjectProperty (_root_.DerivedCategory (ModuleCat.{u} R))} (hP : IsThick P)
  (hR : P ((_root_.DerivedCategory.singleFunctor (ModuleCat.{u} R) 0).obj (ModuleCat.of R R)))
include hP hR

/-- A thick subcategory containing `R[0]` contains `Rⁿ[0]`. -/
theorem singleFunctor_obj_pi_mem (n : ℕ) :
    P ((_root_.DerivedCategory.singleFunctor (ModuleCat.{u} R) 0).obj
      (ModuleCat.of R (Fin n → R))) := by
  induction n with
  | zero =>
    refine hP.of_isZero (Functor.map_isZero _ ?_)
    exact ModuleCat.isZero_of_subsingleton _
  | succ n ih =>
    have := preservesBinaryBiproducts_of_preservesBiproducts
      (_root_.DerivedCategory.singleFunctor (ModuleCat.{u} R) 0)
    let e : ModuleCat.of R (Fin (n + 1) → R) ≅
        ModuleCat.of R R ⊞ ModuleCat.of R (Fin n → R) :=
      (Fin.consLinearEquiv R fun _ : Fin (n + 1) => R).toModuleIso.symm ≪≫
        (ModuleCat.biprodIsoProd (ModuleCat.of R R) (ModuleCat.of R (Fin n → R))).symm
    exact hP.of_iso ((_root_.DerivedCategory.singleFunctor (ModuleCat.{u} R) 0).mapIso e ≪≫
      (_root_.DerivedCategory.singleFunctor (ModuleCat.{u} R) 0).mapBiprod _ _) (hP.biprod hR ih)

/-- A thick subcategory containing `R[0]` contains every finitely generated projective module
placed in degree `0`: such a module is a direct summand of some `Rⁿ`. -/
theorem singleFunctor_obj_mem {M : ModuleCat.{u} R} (hM : IsFGProjective R M) :
    P ((_root_.DerivedCategory.singleFunctor (ModuleCat.{u} R) 0).obj M) := by
  obtain ⟨_, _⟩ := hM
  obtain ⟨n, f, g, -, -, h⟩ := Module.Finite.exists_comp_eq_id_of_projective R M
  let r : Retract M (ModuleCat.of R (Fin n → R)) :=
    ⟨ModuleCat.ofHom g, ModuleCat.ofHom f, by ext x; exact LinearMap.congr_fun h x⟩
  exact hP.retract (r.map _) (singleFunctor_obj_pi_mem hP hR n)

/-- A thick subcategory of the derived category of `R`-modules which contains `R` placed in
degree `0` contains every perfect object. -/
theorem le_of_isThick : IsPerfect R ≤ P := fun _ hX =>
  IsPerfect.induction (motive := fun X _ => P X) (fun _ _ e h => hP.of_iso e.symm h)
    (fun _ hM => singleFunctor_obj_mem hP hR hM) (fun _ n h => hP.shift _ n h)
    (fun T hT _ _ _ h₁ h₃ => hP.ext₂ T hT h₁ h₃) hX

end Thick

/-- `R` placed in degree `0` is perfect. -/
theorem singleFunctor_obj_self :
    IsPerfect R
      ((_root_.DerivedCategory.singleFunctor (ModuleCat.{u} R) 0).obj (ModuleCat.of R R)) :=
  singleFunctor_obj (IsFGProjective.self R) 0

variable (R) in
/-- **The perfect objects are the thick closure of `R`**: for any ring `R`, the thick subcategory
of the derived category of `R`-modules generated by `R` placed in degree `0` consists exactly of
the perfect objects. -/
theorem thickClosure_eq :
    ThickClosure (fun X : _root_.DerivedCategory (ModuleCat.{u} R) =>
      (_root_.DerivedCategory.singleFunctor (ModuleCat.{u} R) 0).obj (ModuleCat.of R R) = X) =
      IsPerfect R :=
  le_antisymm (thickClosure_le (isThick R) (by rintro _ rfl; exact singleFunctor_obj_self))
    (le_of_isThick (isThick_thickClosure _) (.of_mem rfl))

end IsPerfect

/-! ### Compact objects and perfect complexes over a commutative ring -/

namespace DerivedCategory

open DegreeZero

variable (R : Type u) [CommRing R] [_root_.HasDerivedCategory.{w} (ModuleCat.{u} R)]

/-- The dg module `R`, concentrated in degree `0`, as a cochain complex is `R` placed in
degree `0`. -/
noncomputable def forgetObjSelfIso :
    (DGModuleCat.forget R R).obj (DGModuleCat.of R R) ≅
      (HomologicalComplex.single (ModuleCat.{u} R) (ComplexShape.up ℤ) 0).obj
        (ModuleCat.of R R) := by
  have hz : ∀ n : ℤ, n ≠ 0 →
      IsZero (((DGModuleCat.forget R R).obj (DGModuleCat.of R R)).X n) := by
    intro n hn
    have : Subsingleton (((DGModuleCat.forget R R).obj (DGModuleCat.of R R)).X n) :=
      ⟨fun x y => Subtype.ext (by
        rw [((mem_grading_iff (R := R)).mp x.2).resolve_left hn,
          ((mem_grading_iff (R := R)).mp y.2).resolve_left hn])⟩
    exact ModuleCat.isZero_of_subsingleton _
  let φ := HomologicalComplex.mkHomToSingle
    (K := (DGModuleCat.forget R R).obj (DGModuleCat.of R R)) (j := 0)
    (ModuleCat.ofHom (Submodule.subtype _))
    (fun i hi => (hz i (by simp at hi; omega)).eq_of_src _ _)
  have : ∀ n, IsIso (φ.f n) := fun n => by
    by_cases hn : n = 0
    · subst hn
      rw [show φ.f 0 = _ from HomologicalComplex.mkHomToSingle_f _ _]
      have : IsIso (ModuleCat.ofHom (Submodule.subtype
          (DGModule.gradingSubmodule R R (DGModuleCat.of R R) 0))) :=
        (LinearEquiv.ofBijective (Submodule.subtype _) ⟨Subtype.val_injective, fun r =>
          ⟨⟨r, (mem_grading_iff (R := R)).mpr (Or.inl rfl)⟩, rfl⟩⟩).toModuleIso.isIso_hom
      exact IsIso.comp_isIso' this inferInstance
    · exact ⟨0, (hz n hn).eq_of_src _ _,
        (HomologicalComplex.isZero_single_obj_X _ _ _ _ hn).eq_of_src _ _⟩
  have := HomologicalComplex.Hom.isIso_of_components φ
  exact asIso φ

variable [HasDerivedCategory.{u, u} R]

/-- The image of the dg module `R` under the comparison functor `D(R) ⥤ D(Mod R)` is `R` placed
in degree `0`. -/
noncomputable def comparisonObjSelfIso :
    (comparison R).obj (Q.obj (DGModuleCat.of R R)) ≅
      (_root_.DerivedCategory.singleFunctor (ModuleCat.{u} R) 0).obj (ModuleCat.of R R) :=
  (QCompComparisonIso R).app _ ≪≫ _root_.DerivedCategory.Q.mapIso (forgetObjSelfIso R) ≪≫
    (IsPerfect.singleFunctorObjIso 0 _).symm

noncomputable instance : (comparisonEquivalence R).functor.CommShift ℤ :=
  inferInstanceAs ((comparison R).CommShift ℤ)

instance : (comparisonEquivalence R).functor.IsTriangulated :=
  inferInstanceAs (comparison R).IsTriangulated

/-- The image of a compact object of `D(R)` in `D(Mod R)` is perfect. -/
theorem isPerfect_comparison_obj {X : DerivedCategory R} (hX : IsCompact.{u} X) :
    IsPerfect R ((comparison R).obj X) := by
  rw [← thickClosure_self_eq_isCompact] at hX
  refine thickClosure_le ((IsPerfect.isThick R).comap (comparison R)) ?_ X hX
  rintro _ ⟨-, rfl⟩
  exact (IsPerfect.singleFunctor_obj_self).of_iso (comparisonObjSelfIso R)

/-- The objects of `D(Mod R)` whose image in `D(R)` under the inverse of the comparison
equivalence is compact form a thick subcategory. -/
theorem isThick_isCompact_comparisonEquivalence_inverse_obj :
    IsThick fun Y => IsCompact.{u} ((comparisonEquivalence R).inverse.obj Y) := by
  let := (comparisonEquivalence R).commShiftInverse ℤ
  have := (comparisonEquivalence R).commShift_of_functor ℤ
  have : (comparisonEquivalence R).inverse.IsTriangulated :=
    (comparisonEquivalence R).toAdjunction.isTriangulated_rightAdjoint
  exact (isThick_isCompact _).comap (comparisonEquivalence R).inverse

/-- An object of `D(R)` whose image in `D(Mod R)` is perfect is compact. -/
theorem isCompact_of_isPerfect_comparison_obj {X : DerivedCategory R}
    (hX : IsPerfect R ((comparison R).obj X)) : IsCompact.{u} X := by
  have h := IsPerfect.le_of_isThick (isThick_isCompact_comparisonEquivalence_inverse_obj R)
    (((isCompact_Q_self (A := R)).of_iso
      ((comparisonEquivalence R).unitIso.app _).symm).of_iso
        ((comparisonEquivalence R).inverse.mapIso (comparisonObjSelfIso R).symm)) _ hX
  exact h.of_iso ((comparisonEquivalence R).unitIso.app X)

/-- **Compact objects are perfect complexes**: for a commutative ring `R` (a dg ring concentrated
in degree `0`), an object of the derived category `D(R)` of dg modules is compact if and only if
its image under the comparison equivalence `D(R) ≌ D(Mod R)` is perfect, i.e. isomorphic to a
strictly bounded complex of finitely generated projective `R`-modules. -/
theorem isCompact_iff_isPerfect (X : DerivedCategory R) :
    IsCompact.{u} X ↔ IsPerfect R ((comparison R).obj X) :=
  ⟨isPerfect_comparison_obj R, isCompact_of_isPerfect_comparison_obj R⟩

omit [_root_.HasDerivedCategory.{w} (ModuleCat.{u} R)] in
/-- A dg module whose underlying cochain complex is a perfect complex is compact in `D(R)`. -/
theorem isCompact_Q_obj_of_isPerfectComplex (M : DGModuleCat.{u} R)
    (hM : IsPerfectComplex ((DGModuleCat.forget R R).obj M)) : IsCompact.{u} (Q.obj M) := by
  let := _root_.HasDerivedCategory.standard (ModuleCat.{u} R)
  exact isCompact_of_isPerfect_comparison_obj R
    ((IsPerfect.Q_obj hM).of_iso ((QCompComparisonIso R).app M))

end DerivedCategory

end DG
