import Mathlib.CategoryTheory.Idempotents.Basic
import DG.Compact.Thick
import DG.Derived.PerfectComplex

/-!
# Perfect complexes form a thick subcategory

Let `R` be a ring. The perfect objects of the derived category of `R`-modules
(`DG.IsPerfect R`: the objects isomorphic to a strictly bounded complex of finitely generated
projective modules) are closed under shifts and cones (`DG/Derived/PerfectComplex.lean`). This
file proves that they are closed under direct summands, so that they form a thick subcategory
(`DG.IsPerfect.isThick`). See The Stacks Project, Chapter "More on Algebra", Section "Perfect
complexes", where this is deduced from the characterization of perfect complexes as the
pseudo-coherent complexes of finite Tor dimension; the proof given here is a direct induction on
the number of nonzero terms.

## Proof

Let `X` be a direct summand of `Q K` in the derived category, for a complex `K` of finitely
generated projective modules with `Kⁱ = 0` outside `[a, b]`, and let `e : K ⟶ K` be a morphism of
complexes representing the idempotent of `Q K` with image `X`.

* If `a = b`, then `X` is a direct summand of a module placed in one degree. As
  `DerivedCategory.singleFunctor` is fully faithful and idempotents split in the category of
  modules, `X` is isomorphic to a direct summand `P'` of `Kᵇ` placed in degree `b`
  (`DG.IsPerfect.of_retract_single`, `DG.exists_iso_obj_of_retract`).
* If `a < b`, let `S` be the module `P = Kᵇ` placed in degree `b`, with its inclusion
  `ι : S ⟶ K`, and let `X'` be the cone of `Q S ⟶ Q K ⟶ X`. The morphism
  `g = (ι ≫ e, ι ≫ (1 - e)) : S ⊕ S ⟶ K` is surjective in degree `b`, and `X'` is a direct
  summand of the cone of `Q g`: the inclusion of the first summand of `S ⊕ S` and the inclusion
  of `X` in `Q K` extend to a morphism of triangles, as do the projections, and the composition
  of the two is an isomorphism. As `gᵇ` is surjective, the top differential of the mapping cone
  of `g` is a split epimorphism, so the canonical truncation `τ_{≤ b - 1}` of the mapping cone is
  a quasi-isomorphic complex of finitely generated projective modules which vanishes outside
  `[a, b - 1]` (`DG.IsPerfectComplex.exists_quasiIso_mappingCone`). By induction `X'` is perfect,
  hence so is `X`, an extension of `X'` by `Q S`.

## Main results

* `DG.IsPerfectComplex.exists_quasiIso_of_epi_d`: a perfect complex whose last differential is
  surjective is quasi-isomorphic to a perfect complex with one term less.
* `DG.IsPerfect.of_retract`: a direct summand of a perfect object is perfect.
* `DG.IsPerfect.isThick`: the perfect objects form a thick subcategory of the derived category;
  instances `ObjectProperty.IsClosedUnderIsomorphisms` and `ObjectProperty.IsTriangulated`.
* `DG.IsPerfect.induction`: the perfect objects form the triangulated subcategory generated by
  the finitely generated projective modules placed in degree `0`, in the form of an induction
  principle (via `DG.IsPerfectComplex.exists_shortExact`, which splits off the lowest term of a
  perfect complex).
-/

open CategoryTheory Category Limits Pretriangulated ZeroObject

universe w u

namespace DG

/-- A retract of the image of an object under a fully faithful functor whose source is
idempotent complete is isomorphic to the image of a retract. -/
theorem exists_iso_obj_of_retract {C D : Type*} [Category C] [Category D]
    [IsIdempotentComplete C] (F : C ⥤ D) [F.Full] [F.Faithful] {X : D} {M : C}
    (h : Retract X (F.obj M)) : ∃ (M' : C) (_ : Retract M' M), Nonempty (X ≅ F.obj M') := by
  obtain ⟨p, hp⟩ := F.map_surjective (h.r ≫ h.i)
  have hpp : p ≫ p = p := F.map_injective (by
    rw [F.map_comp, hp, assoc, reassoc_of% h.retract])
  obtain ⟨M', j, q, hjq, hqj⟩ := IsIdempotentComplete.idempotents_split M p hpp
  have hjpq : j ≫ p ≫ q = 𝟙 M' := by rw [← hqj, assoc, reassoc_of% hjq, hjq]
  refine ⟨M', ⟨j, q, hjq⟩,
    ⟨{ hom := h.i ≫ F.map q, inv := F.map j ≫ h.r, hom_inv_id := ?_, inv_hom_id := ?_ }⟩⟩
  · rw [assoc, ← F.map_comp_assoc, hqj, hp, assoc, h.retract, comp_id, h.retract]
  · rw [assoc, ← assoc h.r, ← hp, ← F.map_comp, ← F.map_comp, hjpq, F.map_id]

variable {R : Type u} [Ring R]

namespace IsPerfectComplex

/-! ### Removing a surjective last differential -/

section Truncation

variable {C : CochainComplex (ModuleCat.{u} R) ℤ}

/-- If the differential `Cᵖ ⟶ Cᵖ⁺¹` of a complex of finitely generated projective modules is
surjective, the cocycles `Zᵖ` are finitely generated projective: the differential splits, so
`Zᵖ` is a direct summand of `Cᵖ`. -/
theorem fgProjective_cycles (hC : IsPerfectComplex C) (p q : ℤ) (hpq : p + 1 = q)
    [Epi (C.d p q)] : IsFGProjective R (C.cycles p) := by
  have : Projective (C.X q) := (IsProjective.iff_projective (C.X q)).1 (hC.fgProjective q).2
  have hs : Projective.factorThru (𝟙 _) (C.d p q) ≫ C.d p q = 𝟙 _ :=
    Projective.factorThru_comp _ _
  refine IsFGProjective.of_retract (C.iCycles p)
    (C.liftCycles (𝟙 _ - C.d p q ≫ Projective.factorThru (𝟙 _) (C.d p q)) q
      (by subst hpq; simp) (by
        rw [Preadditive.sub_comp, id_comp, assoc, hs, comp_id, sub_self])) ?_ (hC.fgProjective p)
  rw [← cancel_mono (C.iCycles p), assoc, HomologicalComplex.liftCycles_i, Preadditive.comp_sub,
    comp_id, HomologicalComplex.iCycles_d_assoc, zero_comp, sub_zero, id_comp]

/-- A complex which vanishes above degree `p + 1` and whose differential `Cᵖ ⟶ Cᵖ⁺¹` is
surjective has no cohomology above degree `p`. -/
theorem isLE_of_epi_d (p q : ℤ) (hpq : p + 1 = q) (h₁ : ∀ n, q < n → IsZero (C.X n))
    [Epi (C.d p q)] : C.IsLE p := by
  subst hpq
  refine (C.isLE_iff p).2 fun i hi => ?_
  by_cases hi' : i = p + 1
  · subst hi'
    rw [HomologicalComplex.exactAt_iff' C p (p + 1) (p + 1 + 1) (by simp) (by simp)]
    exact (ShortComplex.exact_iff_epi _ ((h₁ _ (by omega)).eq_of_tgt _ _)).2
      (inferInstanceAs (Epi (C.d p (p + 1))))
  · rw [HomologicalComplex.exactAt_iff]
    exact ShortComplex.exact_of_isZero_X₂ _ (h₁ i (by omega))

/-- A perfect complex `C` with `Cⁿ = 0` for `n < a` and for `n > p + 1` whose differential
`Cᵖ ⟶ Cᵖ⁺¹` is surjective is quasi-isomorphic to a perfect complex which vanishes outside
`[a, p]`, namely its canonical truncation `τ_{≤ p} C`, whose term in degree `p` is the module of
cocycles `Zᵖ`. -/
theorem exists_quasiIso_of_epi_d (hC : IsPerfectComplex C) (a p q : ℤ) (hpq : p + 1 = q)
    (h₀ : ∀ n, n < a → IsZero (C.X n)) (h₁ : ∀ n, q < n → IsZero (C.X n)) [Epi (C.d p q)] :
    ∃ (C' : CochainComplex (ModuleCat.{u} R) ℤ) (f : C' ⟶ C), IsPerfectComplex C' ∧
      QuasiIso f ∧ ∀ n, n < a ∨ p < n → IsZero (C'.X n) := by
  have := isLE_of_epi_d p q hpq h₁
  have hX : ∀ n, n < p → Nonempty ((C.truncLE p).X n ≅ C.X n) := fun n hn =>
    ⟨HomologicalComplex.truncLEXIso C (ComplexShape.embeddingUpIntLE p) (i := (p - n).toNat)
      (by simp only [ComplexShape.embeddingUpIntLE_f]; omega)
      (fun h => by rw [ComplexShape.boundaryLE_embeddingUpIntLE_iff] at h; omega)⟩
  have hp : Nonempty ((C.truncLE p).X p ≅ C.cycles p) :=
    ⟨HomologicalComplex.truncLEXIsoCycles C (ComplexShape.embeddingUpIntLE p) (i := 0)
      (by simp) ((ComplexShape.boundaryLE_embeddingUpIntLE_iff p 0).2 rfl)⟩
  have hfg : ∀ n, IsFGProjective R ((C.truncLE p).X n) := fun n => by
    obtain hn | hn | hn := lt_trichotomy n p
    · exact IsFGProjective.of_iso (hX n hn).some (hC.fgProjective n)
    · subst hn
      exact IsFGProjective.of_iso hp.some (hC.fgProjective_cycles n q hpq)
    · exact IsFGProjective.of_isZero ((C.truncLE p).isZero_of_isStrictlyLE p n hn)
  have hz : ∀ n, n < a ∨ p < n → IsZero ((C.truncLE p).X n) := by
    rintro n (hn | hn)
    · obtain hn' | hn' | hn' := lt_trichotomy n p
      · exact IsZero.of_iso (h₀ n hn) (hX n hn').some
      · subst hn'
        exact IsZero.of_iso (IsZero.of_mono (C.iCycles n) (h₀ n hn)) hp.some
      · exact (C.truncLE p).isZero_of_isStrictlyLE p n hn'
    · exact (C.truncLE p).isZero_of_isStrictlyLE p n hn
  exact ⟨C.truncLE p, C.ιTruncLE p,
    mk' hfg a (p + 1 - a).toNat fun n hn => hz n (by omega), inferInstance, hz⟩

end Truncation

section MappingCone

open CochainComplex

variable {S K : CochainComplex (ModuleCat.{u} R) ℤ}

/-- Let `g : S ⟶ K` be a morphism of perfect complexes, where `S` is concentrated in degree `b`,
`K` vanishes outside `[a, b]` with `a < b`, and `g` is surjective in degree `b`. Then the mapping
cone of `g` is quasi-isomorphic to a perfect complex which vanishes outside `[a, b - 1]`. -/
theorem exists_quasiIso_mappingCone (hS : IsPerfectComplex S) (hK : IsPerfectComplex K)
    (g : S ⟶ K) (a b : ℤ) (hab : a < b) (hS' : ∀ n, n ≠ b → IsZero (S.X n))
    (hK' : ∀ n, n < a ∨ b < n → IsZero (K.X n)) [Epi (g.f b)] :
    ∃ (C' : CochainComplex (ModuleCat.{u} R) ℤ) (f : C' ⟶ CochainComplex.mappingCone g), IsPerfectComplex C' ∧
      QuasiIso f ∧ ∀ n, n < a ∨ b - 1 < n → IsZero (C'.X n) := by
  have hz : ∀ n, n < a ∨ b < n → IsZero ((CochainComplex.mappingCone g).X n) := fun n hn =>
    IsZero.of_iso ((biprod_isZero_iff _ _).2 ⟨hS' (n + 1) (by omega), hK' n hn⟩) (mappingConeXIso g n)
  have hinr : Epi ((mappingCone.inr g).f b) :=
    ⟨fun u v h => mappingCone.ext_from g (b + 1) b rfl
      ((hS' (b + 1) (by omega)).eq_of_src _ _) h⟩
  have hd : (mappingCone.inl g).v b (b - 1) (by omega) ≫ (CochainComplex.mappingCone g).d (b - 1) b =
      g.f b ≫ (mappingCone.inr g).f b := by
    rw [mappingCone.inl_v_d g b (b - 1) (b + 1) (by omega) (by omega),
      (hS' (b + 1) (by omega)).eq_of_tgt (S.d b (b + 1)) 0, zero_comp, sub_zero]
  have : Epi ((CochainComplex.mappingCone g).d (b - 1) b) := epi_of_epi_fac hd
  exact (hS.mappingCone g hK).exists_quasiIso_of_epi_d a (b - 1) b (by omega)
    (fun n hn => hz n (Or.inl hn)) (fun n hn => hz n (Or.inr hn))

end MappingCone

end IsPerfectComplex

/-! ### Direct summands of perfect objects -/

namespace IsPerfect

variable [_root_.HasDerivedCategory.{w} (ModuleCat.{u} R)]

/-- The isomorphism between a module placed in degree `n` by `DerivedCategory.singleFunctor` and
the image in the derived category of the complex with this module in degree `n`. -/
noncomputable def singleFunctorObjIso (n : ℤ) (M : ModuleCat.{u} R) :
    (_root_.DerivedCategory.singleFunctor (ModuleCat.{u} R) n).obj M ≅
      _root_.DerivedCategory.Q.obj
        ((HomologicalComplex.single (ModuleCat.{u} R) (ComplexShape.up ℤ) n).obj M) :=
  ((SingleFunctors.evaluation _ _ n).mapIso
    (_root_.DerivedCategory.singleFunctorsPostcompQIso (ModuleCat.{u} R))).app M

/-- A finitely generated projective module placed in a single degree is perfect. -/
theorem singleFunctor_obj {M : ModuleCat.{u} R} (hM : IsFGProjective R M) (n : ℤ) :
    IsPerfect R ((_root_.DerivedCategory.singleFunctor (ModuleCat.{u} R) n).obj M) :=
  ⟨_, IsPerfectComplex.single hM n, ⟨(singleFunctorObjIso n M).symm⟩⟩

/-- A direct summand, in the derived category, of a perfect complex concentrated in a single
degree is perfect: it is a direct summand of the module, placed in that degree. -/
theorem of_retract_single {X : _root_.DerivedCategory (ModuleCat.{u} R)}
    {S : CochainComplex (ModuleCat.{u} R) ℤ} (hS : IsPerfectComplex S) (b : ℤ)
    (hS' : ∀ n, n ≠ b → IsZero (S.X n)) (h : Retract X (_root_.DerivedCategory.Q.obj S)) :
    IsPerfect R X := by
  have : S.IsStrictlyGE b := (S.isStrictlyGE_iff b).2 fun i hi => hS' i (by omega)
  have : S.IsStrictlyLE b := (S.isStrictlyLE_iff b).2 fun i hi => hS' i (by omega)
  obtain ⟨M, ⟨e⟩⟩ := S.exists_iso_single b
  have hM : IsFGProjective R M := IsFGProjective.of_iso
    ((HomologicalComplex.singleObjXSelf (ComplexShape.up ℤ) b M).symm ≪≫
      (HomologicalComplex.eval _ _ b).mapIso e.symm) (hS.fgProjective b)
  obtain ⟨M', hM', ⟨e'⟩⟩ := exists_iso_obj_of_retract
    (_root_.DerivedCategory.singleFunctor (ModuleCat.{u} R) b) (X := X) (M := M)
    ⟨h.i ≫ _root_.DerivedCategory.Q.map e.hom ≫ (singleFunctorObjIso b M).inv,
      (singleFunctorObjIso b M).hom ≫ _root_.DerivedCategory.Q.map e.inv ≫ h.r, by
        rw [assoc, assoc, Iso.inv_hom_id_assoc, ← CategoryTheory.Functor.map_comp_assoc, e.hom_inv_id,
          CategoryTheory.Functor.map_id, id_comp, h.retract]⟩
  exact ⟨_, IsPerfectComplex.single (IsFGProjective.of_retract hM'.i hM'.r hM'.retract hM) b,
    ⟨(singleFunctorObjIso b M').symm ≪≫ e'.symm⟩⟩

/-- The inductive step: a direct summand `X` of a perfect complex `K` which vanishes outside
`[a, b]`, `a < b`, is perfect, provided that direct summands of perfect complexes which vanish
outside `[a, b - 1]` are perfect. Here `S` is the top term of `K` placed in degree `b`, with its
inclusion `ι : S ⟶ K`, and `S₂` is the direct sum of two copies of `S`, with inclusion `in₁` of
the first summand, diagonal `σ` and projections `pr₁`, `pr₂`. -/
theorem of_retract_step {X : _root_.DerivedCategory (ModuleCat.{u} R)}
    {K S S₂ : CochainComplex (ModuleCat.{u} R) ℤ} (hK : IsPerfectComplex K)
    (hS : IsPerfectComplex S) (hS₂ : IsPerfectComplex S₂) (a b : ℤ) (hab : a < b)
    (hK' : ∀ i, i < a ∨ b < i → IsZero (K.X i)) (hS₂' : ∀ i, i ≠ b → IsZero (S₂.X i))
    (ι : S ⟶ K) [Epi (ι.f b)] (in₁ σ : S ⟶ S₂) (pr₁ pr₂ : S₂ ⟶ S) (h₁ : in₁ ≫ pr₁ = 𝟙 S)
    (h₂ : in₁ ≫ pr₂ = 0) (h₃ : σ ≫ pr₁ = 𝟙 S) (h₄ : σ ≫ pr₂ = 𝟙 S)
    (h : Retract X (_root_.DerivedCategory.Q.obj K))
    (ih : ∀ C' : CochainComplex (ModuleCat.{u} R) ℤ, IsPerfectComplex C' →
      (∀ i, i < a ∨ b - 1 < i → IsZero (C'.X i)) →
      ∀ Y : _root_.DerivedCategory (ModuleCat.{u} R),
        Retract Y (_root_.DerivedCategory.Q.obj C') → IsPerfect R Y) :
    IsPerfect R X := by
  obtain ⟨e, he⟩ := hK.exists_Q_map_eq (h.r ≫ h.i)
  obtain ⟨g, hg⟩ : ∃ g : S₂ ⟶ K, g = pr₁ ≫ ι ≫ e + pr₂ ≫ ι ≫ (𝟙 K - e) := ⟨_, rfl⟩
  have hσg : σ ≫ g = ι := by
    rw [hg, Preadditive.comp_add, reassoc_of% h₃, reassoc_of% h₄, Preadditive.comp_sub, comp_id,
      add_sub_cancel]
  have hing : in₁ ≫ g = ι ≫ e := by
    rw [hg, Preadditive.comp_add, reassoc_of% h₁, reassoc_of% h₂, zero_comp, add_zero]
  have : Epi (g.f b) := epi_of_epi_fac (f := σ.f b) (h := ι.f b) (by
    rw [← HomologicalComplex.comp_f, hσg])
  have her : _root_.DerivedCategory.Q.map e ≫ h.r = h.r := by
    rw [he, assoc, h.retract, comp_id]
  have hgr : _root_.DerivedCategory.Q.map g ≫ h.r =
      _root_.DerivedCategory.Q.map pr₁ ≫ _root_.DerivedCategory.Q.map ι ≫ h.r := by
    rw [hg, CategoryTheory.Functor.map_add, Preadditive.add_comp, CategoryTheory.Functor.map_comp, CategoryTheory.Functor.map_comp,
      CategoryTheory.Functor.map_comp, CategoryTheory.Functor.map_comp, CategoryTheory.Functor.map_sub, CategoryTheory.Functor.map_id, assoc, assoc, assoc,
      assoc, her, Preadditive.sub_comp, id_comp, her, sub_self, comp_zero, comp_zero, add_zero]
  -- the cone of `Q S ⟶ Q K ⟶ X`, and the cone of `Q g`
  obtain ⟨X', v, w, hT₁⟩ := distinguished_cocone_triangle (_root_.DerivedCategory.Q.map ι ≫ h.r)
  have hT₂ := _root_.DerivedCategory.mappingCone_triangle_distinguished g
  obtain ⟨α, hα₁, hα₂⟩ := complete_distinguished_triangle_morphism _ _ hT₁ hT₂
    (_root_.DerivedCategory.Q.map in₁) h.i (by
      change (_root_.DerivedCategory.Q.map ι ≫ h.r) ≫ h.i =
        _root_.DerivedCategory.Q.map in₁ ≫ _root_.DerivedCategory.Q.map g
      rw [assoc, ← he, ← CategoryTheory.Functor.map_comp, ← CategoryTheory.Functor.map_comp, hing])
  obtain ⟨β, hβ₁, hβ₂⟩ := complete_distinguished_triangle_morphism _ _ hT₂ hT₁
    (_root_.DerivedCategory.Q.map pr₁) h.r hgr
  dsimp [CochainComplex.mappingCone.triangle] at α β hα₁ hβ₁ hα₂ hβ₂
  -- `α ≫ β` is an isomorphism: it completes the identities to an endomorphism of a triangle
  have hαβ : IsIso (α ≫ β) := by
    let φ : Triangle.mk (_root_.DerivedCategory.Q.map ι ≫ h.r) v w ⟶
        Triangle.mk (_root_.DerivedCategory.Q.map ι ≫ h.r) v w :=
      Triangle.homMk _ _ (𝟙 _) (𝟙 _) (α ≫ β) (by simp)
      (by
        dsimp [CochainComplex.mappingCone.triangle] at hα₁ hβ₁ ⊢
        rw [reassoc_of% hα₁, hβ₁, id_comp, reassoc_of% h.retract])
      (by
        dsimp at hα₂ hβ₂ ⊢
        simp only [assoc] at hα₂ hβ₂
        rw [CategoryTheory.Functor.map_id, comp_id, assoc, ← hβ₂, ← reassoc_of% hα₂, ← CategoryTheory.Functor.map_comp,
          ← CategoryTheory.Functor.map_comp, h₁, CategoryTheory.Functor.map_id, CategoryTheory.Functor.map_id, comp_id])
    exact isIso₃_of_isIso₁₂ φ hT₁ hT₁
      (by change IsIso (𝟙 (_root_.DerivedCategory.Q.obj S)); infer_instance)
      (by change IsIso (𝟙 X); infer_instance)
  -- the cone of `Q g` is represented by a shorter perfect complex
  obtain ⟨C', f, hC', hf, hC'z⟩ := hS₂.exists_quasiIso_mappingCone hK g a b hab hS₂' hK'
  have : QuasiIso f := hf
  have hX' : IsPerfect R X' := ih C' hC' hC'z X'
    ⟨α ≫ inv (_root_.DerivedCategory.Q.map f),
      _root_.DerivedCategory.Q.map f ≫ β ≫ inv (α ≫ β), by
        rw [assoc, IsIso.inv_hom_id_assoc, ← assoc, IsIso.hom_inv_id]⟩
  exact ext₂ _ hT₁ (Q_obj hS) hX'

/-- A direct summand of a perfect complex with at most `n` nonzero terms is perfect. -/
theorem of_retract_aux (n : ℕ) : ∀ (a : ℤ) (K : CochainComplex (ModuleCat.{u} R) ℤ),
    IsPerfectComplex K → (∀ i, i < a ∨ a + n ≤ i → IsZero (K.X i)) →
    ∀ X : _root_.DerivedCategory (ModuleCat.{u} R),
      Retract X (_root_.DerivedCategory.Q.obj K) → IsPerfect R X := by
  induction n with
  | zero =>
    intro a K hK hK' X h
    have hK0 : IsZero K := (IsZero.iff_id_eq_zero K).2 (HomologicalComplex.hom_ext _ _ fun i =>
      (hK' i (by omega)).eq_of_src _ _)
    refine of_isZero ((IsZero.iff_id_eq_zero X).2 ?_)
    rw [← h.retract, (_root_.DerivedCategory.Q.map_isZero hK0).eq_of_tgt h.i 0, zero_comp]
  | succ n ih =>
    intro a K hK hK' X h
    rcases Nat.eq_zero_or_pos n with rfl | hn
    · exact of_retract_single hK a (fun i hi => hK' i (by omega)) h
    · have : Epi ((HomologicalComplex.mkHomFromSingle (𝟙 (K.X (a + n))) (fun k hk =>
          (hK' k (Or.inr (by
            have : a + n + 1 = k := hk
            omega))).eq_of_tgt _ _)).f (a + n)) := by
        rw [HomologicalComplex.mkHomFromSingle_f]
        infer_instance
      exact of_retract_step hK (IsPerfectComplex.single (hK.fgProjective (a + n)) (a + n))
        (IsPerfectComplex.single ((hK.fgProjective (a + n)).biprod (hK.fgProjective (a + n)))
          (a + n)) a (a + n) (by omega) (fun i hi => hK' i (by omega))
        (fun i hi => HomologicalComplex.isZero_single_obj_X _ _ _ _ hi)
        (HomologicalComplex.mkHomFromSingle (𝟙 (K.X (a + n))) _)
        ((HomologicalComplex.single _ _ (a + n)).map biprod.inl)
        ((HomologicalComplex.single _ _ (a + n)).map (biprod.lift (𝟙 _) (𝟙 _)))
        ((HomologicalComplex.single _ _ (a + n)).map biprod.fst)
        ((HomologicalComplex.single _ _ (a + n)).map biprod.snd)
        (by rw [← CategoryTheory.Functor.map_comp, biprod.inl_fst, CategoryTheory.Functor.map_id])
        (by rw [← CategoryTheory.Functor.map_comp, biprod.inl_snd, CategoryTheory.Functor.map_zero])
        (by rw [← CategoryTheory.Functor.map_comp, biprod.lift_fst, CategoryTheory.Functor.map_id])
        (by rw [← CategoryTheory.Functor.map_comp, biprod.lift_snd, CategoryTheory.Functor.map_id]) h
        (fun C' hC' hz Y hY => ih a C' hC' (fun i hi => hz i (by omega)) Y hY)

/-- **Direct summands of perfect objects are perfect.** -/
theorem of_retract {X Y : _root_.DerivedCategory (ModuleCat.{u} R)} (h : Retract X Y)
    (hY : IsPerfect R Y) : IsPerfect R X := by
  obtain ⟨K, hK, ⟨e⟩⟩ := hY
  obtain ⟨a, m, hm⟩ := hK.exists_bounds
  exact of_retract_aux m a K hK hm X
    ⟨h.i ≫ e.inv, e.hom ≫ h.r, by rw [assoc, Iso.inv_hom_id_assoc, h.retract]⟩

variable (R) in
/-- The perfect objects form a thick subcategory of the derived category of `R`-modules: they
contain `0` and are closed under shifts, extensions and direct summands. -/
theorem isThick : IsThick (IsPerfect R) where
  zero := of_isZero (isZero_zero _)
  shift _ n hX := hX.shift n
  ext₂ T hT h₁ h₃ := ext₂ T hT h₁ h₃
  retract h hY := of_retract h hY

instance : (IsPerfect R).IsClosedUnderIsomorphisms := (isThick R).isClosedUnderIsomorphisms

instance : (IsPerfect R).IsTriangulated := (isThick R).isTriangulated

/-! ### Generation by modules -/

section Induction

omit [_root_.HasDerivedCategory.{w} (ModuleCat.{u} R)] in
/-- A perfect complex `K` with `Kⁿ = 0` outside `[a, a + m]` is an extension of its lowest term
`Kᵃ`, placed in degree `a`, by a perfect complex which vanishes outside `[a + 1, a + m]`. -/
theorem _root_.DG.IsPerfectComplex.exists_shortExact {K : CochainComplex (ModuleCat.{u} R) ℤ}
    (hK : IsPerfectComplex K) (a : ℤ) (m : ℕ)
    (hK' : ∀ n, n < a ∨ a + (m + 1 : ℕ) ≤ n → IsZero (K.X n)) :
    ∃ (K' : CochainComplex (ModuleCat.{u} R) ℤ) (i : K' ⟶ K)
      (π : K ⟶ (HomologicalComplex.single (ModuleCat.{u} R) (ComplexShape.up ℤ) a).obj (K.X a))
      (w : i ≫ π = 0), (ShortComplex.mk i π w).ShortExact ∧ IsPerfectComplex K' ∧
        ∀ n, n < a + 1 ∨ a + 1 + m ≤ n → IsZero (K'.X n) := by
  let π : K ⟶ (HomologicalComplex.single (ModuleCat.{u} R) (ComplexShape.up ℤ) a).obj (K.X a) :=
    HomologicalComplex.mkHomToSingle (𝟙 _) (fun i hi =>
      (hK' i (Or.inl (by simp at hi; omega))).eq_of_src _ _)
  have hπa : IsIso (π.f a) := by
    rw [HomologicalComplex.mkHomToSingle_f]
    infer_instance
  have hπ : ∀ i, Epi (π.f i) := fun i => by
    by_cases hi : i = a
    · subst hi
      infer_instance
    · exact (HomologicalComplex.isZero_single_obj_X _ _ _ _ hi).epi _
  have : Epi π := HomologicalComplex.epi_of_epi_f π hπ
  let S := ShortComplex.mk (kernel.ι π) π (kernel.condition π)
  have hS : S.ShortExact := ShortComplex.ShortExact.mk'
    (S.exact_of_f_is_kernel (kernelIsKernel π)) (by dsimp [S]; infer_instance) this
  have hS' := (HomologicalComplex.shortExact_iff_degreewise_shortExact S).1 hS
  have hiso : ∀ n, n ≠ a → IsIso ((kernel.ι π).f n) := fun n hna =>
    (hS' n).isIso_f_iff.2
      (HomologicalComplex.isZero_single_obj_X (ComplexShape.up ℤ) a (K.X a) n hna)
  have h₁ : ∀ n, n < a + 1 ∨ a + 1 + m ≤ n → IsZero ((kernel π).X n) := by
    intro n hn
    by_cases hna : n = a
    · subst hna
      exact (hS' n).isIso_g_iff.1 hπa
    · have := hiso n hna
      exact IsZero.of_iso (hK' n (by omega)) (asIso ((kernel.ι π).f n))
  have hfg : ∀ n, IsFGProjective R ((kernel π).X n) := fun n => by
    by_cases hna : n = a
    · exact IsFGProjective.of_isZero (h₁ n (by omega))
    · have := hiso n hna
      exact IsFGProjective.of_iso (asIso ((kernel.ι π).f n)) (hK.fgProjective n)
  exact ⟨kernel π, kernel.ι π, π, kernel.condition π, hS,
    IsPerfectComplex.mk' hfg (a + 1) m h₁, h₁⟩

/-- **Induction principle for perfect objects**: a property of perfect objects of the derived
category which is invariant under isomorphisms, holds for finitely generated projective modules
placed in degree `0`, and is stable under shifts and extensions, holds for all perfect objects.
In other words, the perfect objects form the triangulated subcategory generated by the finitely
generated projective modules. -/
theorem induction
    {motive : ∀ X : _root_.DerivedCategory (ModuleCat.{u} R), IsPerfect R X → Prop}
    (iso : ∀ {X Y : _root_.DerivedCategory (ModuleCat.{u} R)} (hX : IsPerfect R X)
      (hY : IsPerfect R Y), (X ≅ Y) → motive X hX → motive Y hY)
    (single : ∀ (M : ModuleCat.{u} R) (hM : IsFGProjective R M),
      motive _ (singleFunctor_obj hM 0))
    (shift : ∀ {X : _root_.DerivedCategory (ModuleCat.{u} R)} (hX : IsPerfect R X) (n : ℤ),
      motive X hX → motive (X⟦n⟧) (hX.shift n))
    (ext₂ : ∀ (T : Triangle (_root_.DerivedCategory (ModuleCat.{u} R))) (_ : T ∈ distTriang _)
      (h₁ : IsPerfect R T.obj₁) (h₂ : IsPerfect R T.obj₂) (h₃ : IsPerfect R T.obj₃),
      motive _ h₁ → motive _ h₃ → motive _ h₂)
    {X : _root_.DerivedCategory (ModuleCat.{u} R)} (hX : IsPerfect R X) : motive X hX := by
  have hsingle : ∀ (M : ModuleCat.{u} R) (hM : IsFGProjective R M) (n : ℤ),
      motive _ (Q_obj (IsPerfectComplex.single hM n)) := fun M hM n =>
    iso ((singleFunctor_obj hM 0).shift (-n)) _
      (((_root_.DerivedCategory.singleFunctors (ModuleCat.{u} R)).shiftIso (-n) n 0
        (by omega)).app M ≪≫ singleFunctorObjIso n M)
      (shift _ (-n) (single M hM))
  have aux : ∀ (m : ℕ) (a : ℤ) (K : CochainComplex (ModuleCat.{u} R) ℤ)
      (hK : IsPerfectComplex K), (∀ n, n < a ∨ a + m ≤ n → IsZero (K.X n)) →
      motive _ (Q_obj hK) := by
    intro m
    induction m with
    | zero =>
      intro a K hK hK'
      have hK0 : IsZero K := (IsZero.iff_id_eq_zero K).2 (HomologicalComplex.hom_ext _ _ fun i =>
        (hK' i (by omega)).eq_of_src _ _)
      exact iso (singleFunctor_obj (IsFGProjective.of_isZero (isZero_zero _)) 0) _
        (((_root_.DerivedCategory.singleFunctor (ModuleCat.{u} R) 0).map_isZero
          (isZero_zero _)).iso (_root_.DerivedCategory.Q.map_isZero hK0))
        (single 0 (IsFGProjective.of_isZero (isZero_zero _)))
    | succ m ih =>
      intro a K hK hK'
      obtain ⟨K', i, π, w, hS, hK'p, hK'z⟩ := hK.exists_shortExact a m hK'
      exact ext₂ _ (_root_.DerivedCategory.triangleOfSES_distinguished hS) (Q_obj hK'p)
        (Q_obj hK) (Q_obj (IsPerfectComplex.single (hK.fgProjective a) a))
        (ih (a + 1) K' hK'p hK'z) (hsingle _ (hK.fgProjective a) a)
  have hX' := hX
  obtain ⟨K, hK, ⟨e⟩⟩ := hX'
  obtain ⟨a, m, hm⟩ := hK.exists_bounds
  exact iso (Q_obj hK) hX e (aux m a K hK hm)

end Induction

end IsPerfect

end DG
