import DG.Derived.ConnectiveResolution
import DG.Derived.KProjective
import DG.Examples.Truncation
import DG.Homotopy.ConeQuotient
import DG.Module.HomShiftIso
import Mathlib.CategoryTheory.Triangulated.TStructure.Heart

/-!
# The standard t-structure on the derived category of a connective dg ring

Let `A` be a dg ring concentrated in non-positive degrees (`Aⁿ = 0` for `n > 0`,
`DG.IsNonposGraded A`). Then the derived category `D(A)` carries the *standard t-structure*
`DG.DerivedCategory.tStructure hA` (in Mathlib's sense, `CategoryTheory.Triangulated.TStructure`,
[BBD, Déf. 1.3.1]):

* `D^{≤ n}` consists of the objects `X` with `Hᵏ(X) = 0` for all `k > n`;
* `D^{≥ n}` consists of the objects `X` with `Hᵏ(X) = 0` for all `k < n`.

## Truncations of dg modules

For a dg module `M` over such an `A`, the *good truncation*
`τ^{≤ n} M = (⋯ → M^{n-1} → Zⁿ(M) → 0 → ⋯)` is a dg submodule (`DG.truncLE hA M n`): for
`a ∈ Aⁱ` with `i ≤ 0` the action lowers degrees, and for `a ∈ A⁰` and a cocycle `z`,
`d (a • z) = d a • z = 0` since `d a ∈ A¹ = 0`. (For `A` concentrated in non-negative degrees it
is instead `τ^{≥ n}` that is a submodule of a quotient; the good truncation `τ^{≤ n}` is not a
submodule in general.) Its inclusion induces isomorphisms `Hᵏ(τ^{≤ n} M) ≅ Hᵏ(M)` for `k ≤ n`
(`DG.bijective_cohomology_map_truncLE`), `Hᵏ(τ^{≤ n} M) = 0` for `k > n`
(`DG.subsingleton_cohomology_truncLE`), and `Hᵏ(M ⧸ τ^{≤ n} M) = 0` for `k ≤ n`
(`DG.subsingleton_cohomology_quotient_truncLE`).

## The t-structure axioms

* Shifts: `Hᵏ(X⟦a⟧) ≅ H^{k + a}(X)` (`DG.DerivedCategory.isZero_homologyFunctor_shift_iff`).
* Orthogonality (`DG.DerivedCategory.tStructure_zero`): if `X ∈ D^{≤ 0}` and `Y ∈ D^{≥ 1}`,
  every morphism `X ⟶ Y` vanishes. Write `X = Q M` with `M = τ^{≤ 0} M`, resolve `M` by a
  semi-free module `P` concentrated in non-positive degrees
  (`DG.exists_semiFreeResolution_of_isNonposGraded`); a morphism `Q P ⟶ Q N` is the image of a
  morphism of dg modules `P → N` (`P` is K-projective), which factors through the acyclic
  submodule `τ^{≤ 0} N` since `P¹ = 0`.
* Truncation triangles (`DG.DerivedCategory.tStructure_exists_triangle`): the triangle
  `τ^{≤ 0} M → M → Cone → (τ^{≤ 0} M)⟦1⟧` of the inclusion, whose cone is quasi-isomorphic to
  `M ⧸ τ^{≤ 0} M` (`DG.DGSubmodule.isQuasiIso_coneToQuotient`).

The heart and its identification with modules over `H⁰(A)` are in `DG/Derived/Heart.lean`.

## Positively graded dg algebras

For a positive dg algebra in the sense of Schnürer (`DG.IsPositive`: `Aⁿ = 0` for `n < 0`, `A⁰`
semisimple, `d (A⁰) = 0`) the action raises degrees, the good truncations are not dg
submodules, and the cohomological conditions above do not define a t-structure adapted to `A`.
The natural t-structure is Schnürer's [Sch, Thm. 2 and Thm. 16], on the perfect derived
category: `per^{≤ 0}(A)` (resp. `per^{≥ 0}(A)`) consists of the objects `M` with
`Hⁱ(M ⊗^L_A A⁰) = 0` for `i > 0` (resp. `i < 0`); it is bounded, its truncations are given on
Schnürer's ordered finite-cell modules (`DG.FiniteCellFiltration.IsOrdered`) by the submodules
generated by the cells in degrees `≤ n`, and its heart is the category of modules with a finite
flag of the simple modules `A e`. Such modules are *minimal* in the sense of
`DG/Positive/Minimal.lean` (their reduction `M ⊗_A A⁰` has zero differential, [Sch, Rem. 15]).
It is not formalized here: the library proves Schnürer's description of the compact objects
directly by ordered cell towers (`DG/Compact/CellTower.lean`, `DG/Positive/Schnurer.lean`),
without the t-structure.

## References

* [A. Beilinson, J. Bernstein, P. Deligne, *Faisceaux pervers*, Astérisque 100 (1982), §1.3]
* [B. Keller, *Deriving DG categories*, Ann. Sci. ÉNS 27 (1994)]
* [O. M. Schnürer, *Perfect derived categories of positively graded DG algebras*,
  Appl. Categ. Structures 19 (2011); arXiv:0809.4782v2]
-/

open CategoryTheory Limits Pretriangulated DirectSum

universe w v u

set_option backward.isDefEq.respectTransparency false

namespace DG

/-! ### Cohomology groups which vanish -/

theorem subsingleton_cohomology_iff {M : Type*} [AddCommGroup M] [DGAddCommGroup M] {n : ℤ} :
    Subsingleton (cohomology M n) ↔ ∀ m ∈ grading (M := M) n, d m = 0 → m ∈ coboundaries M n := by
  constructor
  · intro h m hm hdm
    exact (cohomology.mk_eq_zero_iff ⟨m, hm, hdm⟩).mp (Subsingleton.elim _ _)
  · intro h
    refine subsingleton_of_forall_eq 0 fun x => ?_
    induction x using cohomology.induction_on with
    | h z => exact (cohomology.mk_eq_zero_iff z).mpr (h z z.2.1 z.2.2)

/-! ### Good truncations of dg modules -/

section Truncation

variable {A : Type*} [Ring A] [DGAddCommGroup A] (hA : IsNonposGraded A)
  {M : Type*} [AddCommGroup M] [DGAddCommGroup M] [Module A M] [DGModule A M]

variable (M) in
/-- The components of the good truncation `τ^{≤ n} M`: `0` in degrees `> n`, the cocycles in
degree `n`, and everything in degrees `< n`. -/
def truncLEComponents (n k : ℤ) : AddSubgroup M :=
  if n < k then ⊥ else if k = n then cocycles M n else ⊤

omit [DGModule A M] in
theorem mem_truncLEComponents_iff {n k : ℤ} {x : M} (hx : x ∈ grading k) :
    x ∈ ofComponents (truncLEComponents M n) ↔ (n < k → x = 0) ∧ (k = n → d x = 0) := by
  rw [mem_ofComponents_of_mem_grading hx, truncLEComponents]
  by_cases h1 : n < k
  · simp [h1, h1.ne']
  · by_cases h2 : k = n
    · subst h2
      simp [mem_cocycles, hx]
    · simp [h1, h2]

omit [DGModule A M] in
theorem truncLE_d_mem {n : ℤ} {x : M} (hx : x ∈ ofComponents (truncLEComponents M n)) :
    d x ∈ ofComponents (truncLEComponents M n) := by
  refine induction_on_of_isHomogeneous (isHomogeneous_ofComponents _)
    (P := fun x => d x ∈ ofComponents (truncLEComponents M n)) (by simp [zero_mem]) ?_
    (fun x x' h h' => by simpa only [d_add] using add_mem h h') hx
  intro k x hxk hxS
  rw [mem_truncLEComponents_iff hxk] at hxS
  rw [mem_truncLEComponents_iff (d_mem hxk)]
  refine ⟨fun h => ?_, fun _ => d_d x⟩
  by_cases hk : n < k
  · rw [hxS.1 hk, d_zero]
  · exact hxS.2 (by omega)

include hA in
theorem truncLE_smul_mem {n : ℤ} (a : A) {x : M}
    (hx : x ∈ ofComponents (truncLEComponents M n)) :
    a • x ∈ ofComponents (truncLEComponents M n) := by
  refine induction_on_of_isHomogeneous (isHomogeneous_ofComponents _)
    (P := fun x => a • x ∈ ofComponents (truncLEComponents M n)) (by simp [zero_mem]) ?_
    (fun x x' h h' => by simpa only [smul_add] using add_mem h h') hx
  intro k x hxk hxS
  induction a using induction_on with
  | h_zero => simp [zero_mem]
  | h_add a a' ha ha' => rw [add_smul]; exact add_mem ha ha'
  | h_homogeneous a =>
    obtain ⟨a, ha⟩ := a
    rename_i i
    change a • x ∈ _
    rw [mem_truncLEComponents_iff hxk] at hxS
    by_cases hi : 0 < i
    · rw [hA.eq_zero hi ha, zero_smul]
      exact zero_mem _
    by_cases hk : n < k
    · rw [hxS.1 hk, smul_zero]
      exact zero_mem _
    rw [mem_truncLEComponents_iff (smul_mem_grading ha hxk)]
    refine ⟨fun h => absurd h (by omega), fun h => ?_⟩
    obtain rfl : i = 0 := by omega
    rw [d_smul_of_mem_zero ha, hA.eq_zero one_pos (d_mem ha), zero_smul, zero_add,
      hxS.2 (by omega), smul_zero]

variable (M) in
include hA in
/-- The good truncation `τ^{≤ n} M = (⋯ → M^{n-1} → Zⁿ(M) → 0 → ⋯)` of a dg module over a dg
ring concentrated in non-positive degrees, as a dg submodule. -/
def truncLE (n : ℤ) : DGSubmodule A M where
  carrier := ofComponents (truncLEComponents M n)
  add_mem' := add_mem
  zero_mem' := zero_mem _
  smul_mem' a _ hx := truncLE_smul_mem hA a hx
  d_mem' := truncLE_d_mem
  decompose_mem' k _ hx := isHomogeneous_ofComponents _ k hx

theorem mem_truncLE_iff_of_mem_grading {n k : ℤ} {x : M} (hx : x ∈ grading k) :
    x ∈ truncLE hA M n ↔ (n < k → x = 0) ∧ (k = n → d x = 0) :=
  mem_truncLEComponents_iff hx

theorem mem_truncLE_of_lt {n k : ℤ} {x : M} (hx : x ∈ grading k) (hk : k < n) :
    x ∈ truncLE hA M n :=
  (mem_truncLE_iff_of_mem_grading hA hx).mpr ⟨fun h => absurd h (by omega),
    fun h => absurd h (by omega)⟩

theorem mem_truncLE_of_d_eq_zero {n k : ℤ} {x : M} (hx : x ∈ grading k) (hk : k ≤ n)
    (hdx : d x = 0) : x ∈ truncLE hA M n :=
  (mem_truncLE_iff_of_mem_grading hA hx).mpr ⟨fun h => absurd h (by omega), fun _ => hdx⟩

/-- The good truncation `τ^{≤ n} M` is concentrated in degrees `≤ n`. -/
theorem truncLE_eq_zero_of_mem_grading {n k : ℤ} {x : truncLE hA M n}
    (hx : x ∈ DGAddCommGroup.grading k) (hk : n < k) : x = 0 :=
  Subtype.ext (((mem_truncLE_iff_of_mem_grading hA ((DGSubmodule.mem_grading _).mp hx)).mp
    x.2).1 hk)

/-- `τ^{≤ 0} M` is concentrated in non-positive degrees. -/
theorem isNonposGraded_truncLE_zero : IsNonposGraded (truncLE hA M 0) :=
  isNonposGraded_iff.mpr fun _ hk _ hx => truncLE_eq_zero_of_mem_grading hA hx hk

/-- The inclusion `τ^{≤ n} M → M` induces isomorphisms `Hᵏ(τ^{≤ n} M) ≅ Hᵏ(M)` for `k ≤ n`. -/
theorem bijective_cohomology_map_truncLE {n k : ℤ} (hk : k ≤ n) :
    Function.Bijective (cohomology.map (truncLE hA M n).subtype k) := by
  constructor
  · rw [cohomology.map_injective_iff]
    intro z hz _ hzb
    obtain ⟨m, hm, hdm⟩ := mem_coboundaries.mp hzb
    have hmS : m ∈ truncLE hA M n := mem_truncLE_of_lt hA hm (by omega)
    exact mem_coboundaries.mpr ⟨⟨m, hmS⟩, (DGSubmodule.mem_grading _).mpr hm,
      Subtype.ext (by rw [DGSubmodule.coe_d]; exact hdm)⟩
  · rw [cohomology.map_surjective_iff]
    intro y hy hdy
    refine ⟨⟨y, mem_truncLE_of_d_eq_zero hA hy hk hdy⟩, (DGSubmodule.mem_grading _).mpr hy,
      Subtype.ext (by rw [DGSubmodule.coe_d]; exact hdy), ?_⟩
    rw [DGSubmodule.subtype_apply, sub_self]
    exact zero_mem _

/-- `Hᵏ(τ^{≤ n} M) = 0` for `k > n`. -/
theorem subsingleton_cohomology_truncLE {n k : ℤ} (hk : n < k) :
    Subsingleton (cohomology (truncLE hA M n) k) :=
  subsingleton_cohomology_iff.mpr fun z hz _ => by
    rw [truncLE_eq_zero_of_mem_grading hA hz hk]
    exact zero_mem _

/-- `Hᵏ(M ⧸ τ^{≤ n} M) = 0` for `k ≤ n`. -/
theorem subsingleton_cohomology_quotient_truncLE {n k : ℤ} (hk : k ≤ n) :
    Subsingleton (cohomology (M ⧸ (truncLE hA M n).toSubmodule) k) :=
  subsingleton_cohomology_iff.mpr fun yq hyq hdyq => by
    obtain ⟨y, hy, hyy⟩ := (truncLE hA M n).exists_mem_grading_mk hyq
    subst hyy
    rw [← DGModuleHom.map_d, DGSubmodule.mkQ_eq_zero_iff] at hdyq
    have hyS : y ∈ truncLE hA M n := by
      rcases lt_or_eq_of_le hk with hk | rfl
      · exact mem_truncLE_of_lt hA hy hk
      · refine mem_truncLE_of_d_eq_zero hA hy le_rfl ?_
        exact ((mem_truncLE_iff_of_mem_grading hA (d_mem hy)).mp hdyq).1 (by omega)
    rw [(DGSubmodule.mkQ_eq_zero_iff _).mpr hyS]
    exact zero_mem _

end Truncation

namespace DerivedCategory

variable {A : Type u} [Ring A] [DGAddCommGroup A] [DGRing A]

/-! ### Cohomology in the derived category -/

section Cohomology

variable [HasDerivedCategory.{w, v} A]

theorem isZero_homologyFunctor_Q_obj_iff (M : DGModuleCat.{v} A) (k : ℤ) :
    IsZero ((homologyFunctor ℤ k).obj (Q.obj M)) ↔ Subsingleton (cohomology M k) := by
  rw [ModuleCat.isZero_iff_subsingleton]
  exact (cohomologyAddEquiv ℤ M k).subsingleton_congr.symm

theorem isZero_homologyFunctor_iff_of_iso {X Y : DerivedCategory.{w, v} A} (e : X ≅ Y) (k : ℤ) :
    IsZero ((homologyFunctor ℤ k).obj X) ↔ IsZero ((homologyFunctor ℤ k).obj Y) :=
  ((homologyFunctor ℤ k).mapIso e).isZero_iff

/-- `Hᵏ(X⟦a⟧) = 0` iff `H^{k + a}(X) = 0`. -/
theorem isZero_homologyFunctor_shift_iff (X : DerivedCategory.{w, v} A) (a k l : ℤ)
    (h : k + a = l) :
    IsZero ((homologyFunctor ℤ k).obj (X⟦a⟧)) ↔ IsZero ((homologyFunctor ℤ l).obj X) := by
  obtain ⟨M, ⟨e⟩⟩ := exists_iso_Q_obj X
  rw [isZero_homologyFunctor_iff_of_iso ((shiftFunctor _ a).mapIso e ≪≫
      ((Q.commShiftIso a).app M).symm), isZero_homologyFunctor_iff_of_iso e, Functor.comp_obj,
    isZero_homologyFunctor_Q_obj_iff, isZero_homologyFunctor_Q_obj_iff]
  exact (cohomology.shiftAddEquiv M a k l h).subsingleton_congr

theorem isZero_homologyFunctor_Q_map_iff {M N : DGModuleCat.{v} A} {f : M ⟶ N}
    (hf : f.hom.IsQuasiIso) (k : ℤ) :
    IsZero ((homologyFunctor ℤ k).obj (Q.obj M)) ↔ IsZero ((homologyFunctor ℤ k).obj (Q.obj N)) :=
  have : IsIso (Q.map f) := (isIso_Q_map_iff f).mpr hf
  isZero_homologyFunctor_iff_of_iso (asIso (Q.map f)) k

end Cohomology

/-! ### The t-structure -/

section TStructure

variable (A) [HasDerivedCategory.{w, max u v} A]

/-- The objects `X` of `D(A)` with `Hᵏ(X) = 0` for `k > n`. -/
def tLE (n : ℤ) : ObjectProperty (DerivedCategory.{w, max u v} A) :=
  fun X => ∀ k, n < k → IsZero ((homologyFunctor ℤ k).obj X)

/-- The objects `X` of `D(A)` with `Hᵏ(X) = 0` for `k < n`. -/
def tGE (n : ℤ) : ObjectProperty (DerivedCategory.{w, max u v} A) :=
  fun X => ∀ k, k < n → IsZero ((homologyFunctor ℤ k).obj X)

instance (n : ℤ) : (tLE A n).IsClosedUnderIsomorphisms where
  of_iso e h k hk := (isZero_homologyFunctor_iff_of_iso e k).mp (h k hk)

instance (n : ℤ) : (tGE A n).IsClosedUnderIsomorphisms where
  of_iso e h k hk := (isZero_homologyFunctor_iff_of_iso e k).mp (h k hk)

variable {A}

theorem tLE_Q_obj_iff (M : DGModuleCat.{max u v} A) (n : ℤ) :
    tLE A n (Q.obj M) ↔ ∀ k, n < k → Subsingleton (cohomology M k) :=
  forall₂_congr fun k _ => isZero_homologyFunctor_Q_obj_iff M k

theorem tGE_Q_obj_iff (M : DGModuleCat.{max u v} A) (n : ℤ) :
    tGE A n (Q.obj M) ↔ ∀ k, k < n → Subsingleton (cohomology M k) :=
  forall₂_congr fun k _ => isZero_homologyFunctor_Q_obj_iff M k

theorem tLE_shift (n a n' : ℤ) (h : a + n' = n) (X : DerivedCategory.{w, max u v} A)
    (hX : tLE A n X) : tLE A n' (X⟦a⟧) := fun k hk =>
  (isZero_homologyFunctor_shift_iff X a k (k + a) rfl).mpr (hX _ (by omega))

theorem tGE_shift (n a n' : ℤ) (h : a + n' = n) (X : DerivedCategory.{w, max u v} A)
    (hX : tGE A n X) : tGE A n' (X⟦a⟧) := fun k hk =>
  (isZero_homologyFunctor_shift_iff X a k (k + a) rfl).mpr (hX _ (by omega))

variable (hA : IsNonposGraded A)

omit [DGRing A] [HasDerivedCategory A] in
/-- The inclusion `τ^{≤ 0} M → M` is a quasi-isomorphism when `Hᵏ(M) = 0` for `k > 0`. -/
theorem isQuasiIso_truncLE_subtype {M : Type*} [AddCommGroup M] [DGAddCommGroup M] [Module A M]
    [DGModule A M] (hM : ∀ k, 0 < k → Subsingleton (cohomology M k)) :
    (truncLE hA M 0).subtype.IsQuasiIso := fun k => by
  by_cases hk : k ≤ 0
  · exact bijective_cohomology_map_truncLE hA hk
  · have := subsingleton_cohomology_truncLE hA (M := M) (not_le.mp hk)
    have := hM k (not_le.mp hk)
    exact ⟨fun _ _ _ => Subsingleton.elim _ _, fun _ => ⟨0, Subsingleton.elim _ _⟩⟩

include hA in
/-- Orthogonality: in `D(A)`, every morphism from an object with cohomology in degrees `≤ 0` to
an object with cohomology in degrees `≥ 1` vanishes. -/
theorem tStructure_zero ⦃X Y : DerivedCategory.{w, max u v} A⦄ (f : X ⟶ Y) (hX : tLE A 0 X)
    (hY : tGE A 1 Y) : f = 0 := by
  obtain ⟨M, ⟨eX⟩⟩ := exists_iso_Q_obj X
  obtain ⟨N, ⟨eY⟩⟩ := exists_iso_Q_obj Y
  have hM : ∀ k, 0 < k → Subsingleton (cohomology M k) := fun k hk =>
    (tLE_Q_obj_iff M 0).mp ((tLE A 0).prop_of_iso eX hX) k hk
  have hN : ∀ k, k < 1 → Subsingleton (cohomology N k) := fun k hk =>
    (tGE_Q_obj_iff N 1).mp ((tGE A 1).prop_of_iso eY hY) k hk
  -- replace `M` by `τ^{≤ 0} M` and resolve it by a semi-free module in non-positive degrees
  obtain ⟨P, _, _, _, _, π, hπ, ⟨F⟩, hP⟩ :=
    exists_semiFreeResolution_of_isNonposGraded A (truncLE hA M 0) hA
      (isNonposGraded_truncLE_zero hA)
  let ι₁ : DGModuleCat.of A (truncLE hA M 0) ⟶ M := DGModuleCat.ofHom (truncLE hA M 0).subtype
  let π₁ : DGModuleCat.of A P ⟶ DGModuleCat.of A (truncLE hA M 0) := DGModuleCat.ofHom π
  have : IsIso (Q.map ι₁) := (isIso_Q_map_iff _).mpr (isQuasiIso_truncLE_subtype hA hM)
  have : IsIso (Q.map π₁) := (isIso_Q_map_iff _).mpr hπ
  let e : X ≅ Q.obj (DGModuleCat.of A P) :=
    eX ≪≫ (asIso (Q.map ι₁)).symm ≪≫ (asIso (Q.map π₁)).symm
  obtain ⟨g, hg⟩ := exists_Q_map_eq (N := N) F.isKProjective (e.inv ≫ f ≫ eY.hom)
  -- `g` factors through the acyclic submodule `τ^{≤ 0} N`
  have hgN : ∀ x, g x ∈ truncLE hA N 0 := by
    intro x
    induction x using DG.induction_on with
    | h_zero => rw [map_zero]; exact zero_mem _
    | h_add x x' hx hx' => rw [map_add]; exact add_mem hx hx'
    | h_homogeneous x =>
      obtain ⟨x, hx⟩ := x
      rename_i k
      change g x ∈ _
      by_cases hk : 0 < k
      · rw [hP.eq_zero hk hx, map_zero]
        exact zero_mem _
      rcases lt_or_eq_of_le (not_lt.mp hk) with hk | rfl
      · exact mem_truncLE_of_lt hA (g.hom.map_mem hx) hk
      refine mem_truncLE_of_d_eq_zero hA (g.hom.map_mem hx) le_rfl ?_
      rw [← DGModuleHom.map_d, hP.eq_zero one_pos (d_mem hx), map_zero]
  let g' : DGModuleCat.of A P ⟶ DGModuleCat.of A (truncLE hA N 0) :=
    DGModuleCat.ofHom ((truncLE hA N 0).codRestrict g.hom hgN)
  have hfac : g = g' ≫ DGModuleCat.ofHom (truncLE hA N 0).subtype := rfl
  have hZ : IsZero (Q.obj (DGModuleCat.of A (truncLE hA N 0))) := by
    rw [isZero_Q_obj_iff]
    intro k
    by_cases hk : k ≤ 0
    · have := hN k (by omega)
      exact (Equiv.ofBijective _ (bijective_cohomology_map_truncLE hA (M := N) hk)).subsingleton
    · exact subsingleton_cohomology_truncLE hA (not_le.mp hk)
  have h0 : e.inv ≫ f ≫ eY.hom = 0 := by
    rw [← hg, hfac, Functor.map_comp, hZ.eq_of_tgt (Q.map g') 0, zero_comp]
  simpa using congrArg (fun φ => e.hom ≫ φ ≫ eY.inv) h0

include hA in
/-- The truncation triangles: every object `X` of `D(A)` sits in a distinguished triangle
`X' → X → X'' → X'⟦1⟧` with `Hᵏ(X') = 0` for `k > 0` and `Hᵏ(X'') = 0` for `k ≤ 0`. -/
theorem tStructure_exists_triangle (X : DerivedCategory.{w, max u v} A) :
    ∃ (X' X'' : DerivedCategory.{w, max u v} A) (_ : tLE A 0 X') (_ : tGE A 1 X'')
      (f : X' ⟶ X) (g : X ⟶ X'') (h : X'' ⟶ X'⟦(1 : ℤ)⟧),
      Triangle.mk f g h ∈ distTriang (DerivedCategory.{w, max u v} A) := by
  obtain ⟨M, ⟨e⟩⟩ := exists_iso_Q_obj X
  let S := truncLE hA M 0
  let φ : DGModuleCat.of A S ⟶ M := DGModuleCat.ofHom S.subtype
  let T := Q.mapTriangle.obj (Cone.triangle φ)
  have hT : T ∈ distTriang _ := (mem_distTriang_iff T).mpr ⟨_, _, φ, ⟨Iso.refl _⟩⟩
  refine ⟨T.obj₁, T.obj₃, ?_, ?_, T.mor₁ ≫ e.inv, e.hom ≫ T.mor₂, T.mor₃, ?_⟩
  · refine (tLE_Q_obj_iff _ 0).mpr fun k hk => ?_
    exact subsingleton_cohomology_truncLE hA hk
  · refine (tGE_Q_obj_iff _ 1).mpr fun k hk => ?_
    have := subsingleton_cohomology_quotient_truncLE hA (M := M) (show k ≤ 0 by omega)
    exact ((S.isQuasiIso_coneToQuotient) k).1.subsingleton
  · refine isomorphic_distinguished _ hT _ (Triangle.isoMk _ _ (Iso.refl _) e (Iso.refl _)
      ?_ ?_ ?_)
    · simp
    · simp
    · simp

/-- The standard t-structure on the derived category of a dg ring `A` concentrated in
non-positive degrees: `D^{≤ n}` (resp. `D^{≥ n}`) consists of the objects whose cohomology
vanishes in degrees `> n` (resp. `< n`). -/
noncomputable def tStructure : Triangulated.TStructure (DerivedCategory.{w, max u v} A) where
  le := tLE A
  ge := tGE A
  le_shift := tLE_shift
  ge_shift := tGE_shift
  zero' := tStructure_zero hA
  le_zero_le _ hX k hk := hX k (by omega)
  ge_one_le _ hX k hk := hX k (by omega)
  exists_triangle_zero_one := tStructure_exists_triangle hA

@[simp]
theorem tStructure_le (n : ℤ) : (tStructure hA).le n = tLE A n := rfl

@[simp]
theorem tStructure_ge (n : ℤ) : (tStructure hA).ge n = tGE A n := rfl

/-- An object of `D(A)` lies in the heart of the standard t-structure iff its cohomology is
concentrated in degree `0`. -/
theorem mem_heart_tStructure_iff (X : DerivedCategory.{w, max u v} A) :
    (tStructure hA).heart X ↔ ∀ k, k ≠ 0 → IsZero ((homologyFunctor ℤ k).obj X) := by
  constructor
  · rintro ⟨h₁, h₂⟩ k hk
    rcases lt_or_gt_of_ne hk with hk | hk
    · exact h₂ k hk
    · exact h₁ k hk
  · intro h
    exact ⟨fun k hk => h k (by omega), fun k hk => h k (by omega)⟩

end TStructure

end DerivedCategory

end DG
