import Mathlib.Algebra.DirectSum.Module
import DG.Algebra.Decompose
import DG.Module.Basic

/-!
# Direct sums and graded products of families of dg modules

For a family `M : ι → Type*` of dg `A`-modules:

* the direct sum `⨁ i, M i` is a dg `A`-module, graded by `(⨁ i, M i)ⁿ = {x | ∀ i, x i ∈ (M i)ⁿ}`
  (the finitely supported families of homogeneous elements of degree `n`), with componentwise
  differential; the inclusions `DG.DGModuleHom.lof A M i : M i →ᵈᵍ[A] ⨁ i, M i` and the map
  `DG.DGModuleHom.toModule` out of the direct sum are morphisms. This is the coproduct in the
  category of dg modules.
* the graded product `DG.GradedPi A M`: the product `∀ i, M i` is not graded by the products of
  the homogeneous components (a family of homogeneous elements of unbounded degrees is not a
  finite sum of homogeneous families), so the product in the category of dg modules is the
  submodule of `∀ i, M i` generated by the homogeneous families, `⨁ₙ ∏ᵢ (M i)ⁿ`. Its graded
  pieces are the homogeneous families of degree `n`, the projections `DG.DGModuleHom.proj` and the
  pairing `DG.DGModuleHom.pi` are morphisms. This is the product in the category of dg modules.
-/

open DirectSum

namespace DG

variable {A : Type*} [Ring A] [DGAddCommGroup A] {ι : Type*} (M : ι → Type*)
  [∀ i, AddCommGroup (M i)] [∀ i, DGAddCommGroup (M i)]

/-! ### Direct sums -/

namespace DirectSum

variable [DecidableEq ι]

/-- The homogeneous components of `⨁ i, M i`: the families whose components all have degree
`n`. -/
def grading (n : ℤ) : AddSubgroup (⨁ i, M i) where
  carrier := {x | ∀ i, x i ∈ DGAddCommGroup.grading n}
  zero_mem' i := by rw [DirectSum.zero_apply]; exact zero_mem _
  add_mem' hx hy i := by rw [DirectSum.add_apply]; exact add_mem (hx i) (hy i)
  neg_mem' hx i := by
    rw [neg_eq_zero_sub, DirectSum.sub_apply, DirectSum.zero_apply, zero_sub]
    exact neg_mem (hx i)

omit [DecidableEq ι] in
theorem mem_grading_iff {n : ℤ} {x : ⨁ i, M i} :
    x ∈ grading M n ↔ ∀ i, x i ∈ DGAddCommGroup.grading n :=
  Iff.rfl

theorem of_mem_grading {n : ℤ} (i : ι) {m : M i} (hm : m ∈ DGAddCommGroup.grading n) :
    DirectSum.of M i m ∈ grading M n := by
  intro j
  by_cases hij : i = j
  · subst hij; rwa [DirectSum.of_eq_same]
  · rw [DirectSum.of_eq_of_ne _ _ _ (Ne.symm hij)]; exact zero_mem _

theorem mem_iSup_grading (x : ⨁ i, M i) : x ∈ ⨆ n, grading M n := by
  induction x using DirectSum.induction_on with
  | zero => exact zero_mem _
  | of i m =>
    induction m using DG.induction_on with
    | h_zero => rw [map_zero]; exact zero_mem _
    | h_homogeneous m => exact AddSubgroup.mem_iSup_of_mem _ (of_mem_grading M i m.2)
    | h_add m m' hm hm' => rw [map_add]; exact add_mem hm hm'
  | add x y hx hy => exact add_mem hx hy

theorem isInternal_grading : DirectSum.IsInternal (grading M) :=
  ⟨coeAddMonoidHom_injective_of_forall_eq_zero _ (fun i => DFinsupp.evalAddMonoidHom i)
      (fun _ _ _ hx => hx _) fun _ hx => DFinsupp.ext hx,
    coeAddMonoidHom_surjective_of_mem_iSup _ (mem_iSup_grading M)⟩

/-- The componentwise differential. -/
def d : (⨁ i, M i) →+ ⨁ i, M i :=
  DirectSum.map fun i => (DGAddCommGroup.d : M i →+ M i)

omit [DecidableEq ι] in
@[simp]
theorem d_apply (x : ⨁ i, M i) (i : ι) : d M x i = DGAddCommGroup.d (x i) :=
  DirectSum.map_apply _ _ _

noncomputable instance instDGAddCommGroup : DGAddCommGroup (⨁ i, M i) where
  grading := grading M
  decomposition := (isInternal_grading M).chooseDecomposition
  d := d M
  d_mem' hx i := by rw [d_apply]; exact DG.d_mem (hx i)
  d_d' x := by ext i; simp

theorem mem_grading {n : ℤ} {x : ⨁ i, M i} :
    x ∈ DGAddCommGroup.grading n ↔ ∀ i, x i ∈ DGAddCommGroup.grading n :=
  Iff.rfl

@[simp]
theorem coe_d_apply (x : ⨁ i, M i) (i : ι) : DGAddCommGroup.d x i = DGAddCommGroup.d (x i) :=
  d_apply M x i

theorem d_of (i : ι) (m : M i) :
    DGAddCommGroup.d (DirectSum.of M i m) = DirectSum.of M i (DGAddCommGroup.d m) :=
  DirectSum.map_of _ _ _

variable [∀ i, Module A (M i)] [∀ i, DGModule A (M i)]

instance instDGModule : DGModule A (⨁ i, M i) where
  smul_mem _ _ _ _ ha hx i := by rw [DirectSum.smul_apply]; exact smul_mem_grading ha (hx i)
  d_smul' ha x := by
    ext i
    rw [coe_d_apply, DirectSum.smul_apply, d_smul ha, DirectSum.add_apply, DirectSum.smul_apply,
      Units.smul_def, Units.smul_def, DirectSum.smul_apply, DirectSum.smul_apply, coe_d_apply]

end DirectSum

namespace DGModuleHom

variable [DecidableEq ι] [∀ i, Module A (M i)]

variable (A)

/-- The inclusion of a summand into the direct sum, as a morphism of dg modules. -/
def lof (i : ι) : M i →ᵈᵍ[A] ⨁ i, M i where
  __ := DirectSum.lof A ι M i
  map_mem' hm := DirectSum.of_mem_grading M i hm
  map_d' m := (DirectSum.d_of M i m).symm

@[simp]
theorem lof_apply (i : ι) (m : M i) : lof A M i m = DirectSum.of M i m := rfl

variable {A M} {N : Type*} [AddCommGroup N] [DGAddCommGroup N] [Module A N]

/-- The morphism out of a direct sum determined by its restrictions to the summands. -/
def toModule (f : ∀ i, M i →ᵈᵍ[A] N) : (⨁ i, M i) →ᵈᵍ[A] N where
  __ := DirectSum.toModule A ι N fun i => (f i).toLinearMap
  map_mem' := by
    classical
    intro n x hx
    change DirectSum.toModule A ι N (fun i => (f i).toLinearMap) x ∈ _
    rw [← DirectSum.sum_support_of x, map_sum]
    refine sum_mem fun i _ => ?_
    rw [← DirectSum.lof_eq_of A, DirectSum.toModule_lof]
    exact (f i).map_mem (hx i)
  map_d' x := by
    let T := DirectSum.toModule A ι N fun i => (f i).toLinearMap
    change T (DirectSum.d M x) = DGAddCommGroup.d (T x)
    have h : T.toAddMonoidHom.comp (DirectSum.d M) =
        (DGAddCommGroup.d : N →+ N).comp T.toAddMonoidHom :=
      DirectSum.addHom_ext fun i m => by
        simp only [AddMonoidHom.comp_apply, LinearMap.toAddMonoidHom_coe, DirectSum.d,
          DirectSum.map_of, T]
        rw [← DirectSum.lof_eq_of A, ← DirectSum.lof_eq_of A, DirectSum.toModule_lof,
          DirectSum.toModule_lof]
        exact (f i).map_d m
    exact congrArg (fun φ : (⨁ i, M i) →+ N => φ x) h

@[simp]
theorem toModule_lof (f : ∀ i, M i →ᵈᵍ[A] N) (i : ι) (m : M i) :
    toModule f (DirectSum.of M i m) = f i m :=
  DirectSum.toModule_lof A i m

@[simp]
theorem toModule_comp_lof (f : ∀ i, M i →ᵈᵍ[A] N) (i : ι) :
    (toModule f).comp (lof A M i) = f i :=
  DGModuleHom.ext fun m => toModule_lof f i m

/-- Two morphisms out of a direct sum agreeing on the summands are equal. -/
theorem directSum_ext {f g : (⨁ i, M i) →ᵈᵍ[A] N}
    (h : ∀ i, f.comp (lof A M i) = g.comp (lof A M i)) : f = g :=
  toLinearMap_injective <| DirectSum.linearMap_ext A fun i => LinearMap.ext fun m =>
    congrArg (fun φ : M i →ᵈᵍ[A] N => φ m) (h i)

end DGModuleHom

/-! ### Graded products -/

namespace GradedPi

/-- The families of homogeneous elements of degree `n`. -/
def piGrading (n : ℤ) : AddSubgroup (∀ i, M i) :=
  AddSubgroup.pi Set.univ fun _ => DGAddCommGroup.grading n

theorem mem_piGrading_iff {n : ℤ} {x : ∀ i, M i} :
    x ∈ piGrading M n ↔ ∀ i, x i ∈ DGAddCommGroup.grading n := by
  simp [piGrading, AddSubgroup.mem_pi]

variable (A) [∀ i, Module A (M i)] [∀ i, DGModule A (M i)]

/-- The graded product as a submodule of the product: the submodule generated by the families
of homogeneous elements of a fixed degree. -/
def submodule : Submodule A (∀ i, M i) where
  __ := (⨆ n, piGrading M n).toAddSubmonoid
  smul_mem' a x hx := by
    change x ∈ ⨆ n, piGrading M n at hx
    change a • x ∈ ⨆ n, piGrading M n
    refine AddSubgroup.iSup_induction _ (C := fun x => a • x ∈ ⨆ n, piGrading M n) hx
      (fun n x hx => ?_) (by rw [smul_zero]; exact zero_mem _)
      (fun x y hx hy => by rw [smul_add]; exact add_mem hx hy)
    induction a using DG.induction_on with
    | h_zero => rw [zero_smul]; exact zero_mem _
    | @h_homogeneous k a =>
      refine AddSubgroup.mem_iSup_of_mem (k + n) ((mem_piGrading_iff M).mpr fun i => ?_)
      rw [Pi.smul_apply]
      exact smul_mem_grading a.2 ((mem_piGrading_iff M).mp hx i)
    | h_add a a' ha ha' => rw [add_smul]; exact add_mem ha ha'

theorem mem_submodule_iff {x : ∀ i, M i} : x ∈ submodule A M ↔ x ∈ ⨆ n, piGrading M n :=
  Iff.rfl

theorem piGrading_le_submodule (n : ℤ) : piGrading M n ≤ (submodule A M).toAddSubgroup :=
  fun _ hx => AddSubgroup.mem_iSup_of_mem n hx

end GradedPi

variable [∀ i, Module A (M i)] [∀ i, DGModule A (M i)]

variable (A) in
/-- The graded product `⨁ₙ ∏ᵢ (M i)ⁿ` of a family of dg modules: the submodule of `∀ i, M i`
generated by the families of homogeneous elements of a fixed degree. -/
def GradedPi : Type _ :=
  GradedPi.submodule A M

namespace GradedPi

variable (A)

instance : AddCommGroup (GradedPi A M) :=
  inferInstanceAs (AddCommGroup (submodule A M))

instance : Module A (GradedPi A M) :=
  inferInstanceAs (Module A (submodule A M))

/-- The underlying family of an element of the graded product. -/
def toPi : GradedPi A M →ₗ[A] ∀ i, M i :=
  (submodule A M).subtype

@[simp]
theorem toPi_add (x y : GradedPi A M) : toPi A M (x + y) = toPi A M x + toPi A M y := rfl

@[simp]
theorem toPi_zero : toPi A M 0 = 0 := rfl

@[simp]
theorem toPi_smul (a : A) (x : GradedPi A M) : toPi A M (a • x) = a • toPi A M x := rfl

theorem toPi_injective : Function.Injective (toPi A M) :=
  Subtype.val_injective

@[ext]
theorem ext {x y : GradedPi A M} (h : ∀ i, toPi A M x i = toPi A M y i) : x = y :=
  toPi_injective A M (funext h)

theorem toPi_mem (x : GradedPi A M) : toPi A M x ∈ ⨆ n, piGrading M n :=
  x.2

/-- Build an element of the graded product from a family in the generated submodule. -/
def mk (x : ∀ i, M i) (hx : x ∈ ⨆ n, piGrading M n) : GradedPi A M :=
  ⟨x, hx⟩

@[simp]
theorem toPi_mk (x : ∀ i, M i) (hx : x ∈ ⨆ n, piGrading M n) : toPi A M (mk A M x hx) = x := rfl

/-- The homogeneous components of the graded product. -/
def grading (n : ℤ) : AddSubgroup (GradedPi A M) :=
  (piGrading M n).comap (toPi A M).toAddMonoidHom

theorem mem_grading_iff {n : ℤ} {x : GradedPi A M} :
    x ∈ grading A M n ↔ ∀ i, toPi A M x i ∈ DGAddCommGroup.grading n :=
  mem_piGrading_iff M

theorem isInternal_grading : DirectSum.IsInternal (grading A M) :=
  ⟨coeAddMonoidHom_injective_of_forall_eq_zero _
      (fun i => (Pi.evalAddMonoidHom M i).comp (toPi A M).toAddMonoidHom)
      (fun i _ _ hx => (mem_grading_iff A M).mp hx i) fun _ hx => ext A M hx,
    coeAddMonoidHom_surjective_of_mem_iSup _ fun x => by
      refine AddSubgroup.iSup_induction' (piGrading M)
        (C := fun y hy => mk A M y hy ∈ ⨆ n, grading A M n) ?_ (zero_mem _) ?_ x.2
      · intro n y hy
        exact AddSubgroup.mem_iSup_of_mem n ((mem_grading_iff A M).mpr fun i =>
          (mem_piGrading_iff M).mp hy i)
      · intro y z hy hz hy' hz'
        exact add_mem hy' hz'⟩

/-- The differential on the product `∀ i, M i`, componentwise. -/
def dPi : (∀ i, M i) →+ ∀ i, M i :=
  AddMonoidHom.pi fun i => (DGAddCommGroup.d : M i →+ M i).comp (Pi.evalAddMonoidHom M i)

@[simp]
theorem dPi_apply (x : ∀ i, M i) (i : ι) : dPi M x i = DGAddCommGroup.d (x i) := rfl

theorem dPi_mem {x : ∀ i, M i} (hx : x ∈ ⨆ n, piGrading M n) : dPi M x ∈ ⨆ n, piGrading M n := by
  refine AddSubgroup.iSup_induction _ (C := fun x => dPi M x ∈ ⨆ n, piGrading M n) hx
    (fun n x hx => ?_) (by rw [map_zero]; exact zero_mem _)
    (fun x y hx hy => by rw [map_add]; exact add_mem hx hy)
  exact AddSubgroup.mem_iSup_of_mem (n + 1) ((mem_piGrading_iff M).mpr fun i =>
    DG.d_mem ((mem_piGrading_iff M).mp hx i))

/-- The differential of the graded product. -/
def d : GradedPi A M →+ GradedPi A M :=
  AddMonoidHom.codRestrict ((dPi M).comp (toPi A M).toAddMonoidHom) (submodule A M)
    fun x => dPi_mem M x.2

@[simp]
theorem toPi_d_apply (x : GradedPi A M) (i : ι) :
    toPi A M (d A M x) i = DGAddCommGroup.d (toPi A M x i) := rfl

noncomputable instance instDGAddCommGroup : DGAddCommGroup (GradedPi A M) where
  grading := grading A M
  decomposition := (isInternal_grading A M).chooseDecomposition
  d := d A M
  d_mem' hx := (mem_grading_iff A M).mpr fun i =>
    DG.d_mem ((mem_grading_iff A M).mp hx i)
  d_d' x := ext A M fun i => by simp

theorem mem_grading {n : ℤ} {x : GradedPi A M} :
    x ∈ DGAddCommGroup.grading n ↔ ∀ i, toPi A M x i ∈ DGAddCommGroup.grading n :=
  mem_grading_iff A M

@[simp]
theorem toPi_d (x : GradedPi A M) (i : ι) :
    toPi A M (DGAddCommGroup.d x) i = DGAddCommGroup.d (toPi A M x i) := rfl

instance instDGModule : DGModule A (GradedPi A M) where
  smul_mem _ _ _ _ ha hx := (mem_grading A M).mpr fun i => by
    rw [toPi_smul, Pi.smul_apply]
    exact smul_mem_grading ha ((mem_grading A M).mp hx i)
  d_smul' ha x := ext A M fun i => by
    rw [toPi_d, toPi_smul, Pi.smul_apply, d_smul ha, toPi_add, Pi.add_apply, toPi_smul,
      Pi.smul_apply, Units.smul_def, Units.smul_def, map_zsmul (toPi A M), Pi.smul_apply,
      toPi_smul, Pi.smul_apply, toPi_d]

end GradedPi

namespace DGModuleHom

variable (A)

/-- The projection of the graded product onto a factor. -/
def proj (i : ι) : GradedPi A M →ᵈᵍ[A] M i where
  __ := (LinearMap.proj i).comp (GradedPi.toPi A M)
  map_mem' hx := (GradedPi.mem_grading A M).mp hx i
  map_d' _ := rfl

@[simp]
theorem proj_apply (i : ι) (x : GradedPi A M) : proj A M i x = GradedPi.toPi A M x i := rfl

variable {A M} {N : Type*} [AddCommGroup N] [DGAddCommGroup N] [Module A N]

omit [∀ i, DGModule A (M i)] in
theorem pi_mem (f : ∀ i, N →ᵈᵍ[A] M i) (x : N) :
    (fun i => f i x) ∈ ⨆ n, GradedPi.piGrading M n := by
  induction x using DG.induction_on with
  | h_zero =>
    have : (fun i => f i (0 : N)) = 0 := funext fun i => map_zero (f i)
    rw [this]; exact zero_mem _
  | h_homogeneous x =>
    exact AddSubgroup.mem_iSup_of_mem _ ((GradedPi.mem_piGrading_iff M).mpr fun i =>
      (f i).map_mem x.2)
  | h_add x y hx hy =>
    have : (fun i => f i (x + y)) = (fun i => f i x) + fun i => f i y :=
      funext fun i => map_add (f i) x y
    rw [this]; exact add_mem hx hy

/-- The morphism into the graded product determined by its components. -/
def pi (f : ∀ i, N →ᵈᵍ[A] M i) : N →ᵈᵍ[A] GradedPi A M where
  __ := LinearMap.codRestrict (GradedPi.submodule A M) (LinearMap.pi fun i => (f i).toLinearMap)
    (pi_mem f)
  map_mem' hx := (GradedPi.mem_grading A M).mpr fun i => (f i).map_mem hx
  map_d' x := GradedPi.ext A M fun i => (f i).map_d x

@[simp]
theorem toPi_pi_apply (f : ∀ i, N →ᵈᵍ[A] M i) (x : N) (i : ι) :
    GradedPi.toPi A M (pi f x) i = f i x := rfl

@[simp]
theorem proj_comp_pi (f : ∀ i, N →ᵈᵍ[A] M i) (i : ι) : (proj A M i).comp (pi f) = f i := rfl

/-- Two morphisms into a graded product with the same components are equal. -/
theorem gradedPi_ext {f g : N →ᵈᵍ[A] GradedPi A M}
    (h : ∀ i, (proj A M i).comp f = (proj A M i).comp g) : f = g :=
  DGModuleHom.ext fun x => GradedPi.ext A M fun i =>
    congrArg (fun φ : N →ᵈᵍ[A] M i => φ x) (h i)

end DGModuleHom

end DG
