import DG.Module.ExternalTensor
import DG.Module.Equiv

/-!
# The external tensor product over a commutative ring

Let `R` be a commutative ring, `A`, `B` dg `R`-algebras, `M` a dg `A`-module and `N` a dg
`B`-module, both `R`-modules compatibly (`IsScalarTower R A M`, `IsScalarTower R B N`). The
tensor product `M ⊗[R] N`, carried by the type synonym `DG.ExternalTensorOver R A B M N`, is

* a dg `R`-module (`DG.ExternalTensorOver.instDGAddCommGroup`): `(M ⊗_R N)ᵏ` is generated by the
  `m ⊗ n` with `|m| + |n| = k`, and `d (m ⊗ n) = d m ⊗ n + (-1)^{|m|} m ⊗ d n`
  (`DG.ExternalTensorOver.d_tmul_of_mem`);
* a dg module over `A ᵍ⊗[R] B` (`DG.ExternalTensorOver.instDGModule`), with the Koszul sign rule
  `(a ⊗ b) • (m ⊗ n) = (-1)^{|b| |m|} (a • m) ⊗ (b • n)` (`DG.ExternalTensorOver.tmul_smul_tmul`).

This generalizes the external tensor product over `ℤ` (`DG/Module/ExternalTensor.lean`, on
`M ⊗[ℤ] N`), and for `R = ℤ` the two agree: `DG.ExternalTensorOver.intEquiv` is the identity
`M ⊗[ℤ] N ≃ M ⊗[ℤ] N` as an isomorphism of dg modules over `A ᵍ⊗[ℤ] B`. The type synonym keeps
the two structures apart. Tensor products of morphisms of dg modules are morphisms of dg modules
(`DG.ExternalTensorOver.tensorDGHom`).
-/

open scoped TensorProduct
open DirectSum

set_option linter.unusedSectionVars false

noncomputable section

namespace DG

/-- The external tensor product `M ⊗_R N` of a dg `A`-module and a dg `B`-module over a
commutative ring `R` (a type synonym for `M ⊗[R] N` carrying the dg module structure over
`A ᵍ⊗[R] B`). The rings `A`, `B` are parameters so that the structure can be found by instance
search. -/
@[nolint unusedArguments]
def ExternalTensorOver (R : Type*) [CommRing R] (_A _B : Type*) (M N : Type*) [AddCommGroup M]
    [AddCommGroup N] [Module R M] [Module R N] : Type _ :=
  M ⊗[R] N

namespace ExternalTensorOver

private theorem ks_eq {m n : ℤ} (h : Even (m - n)) : koszulSign m = koszulSign n :=
  (Int.negOnePow_eq_iff m n).mpr h

private theorem ks_val (n : ℤ) : (koszulSign n : ℤ) = if Even n then 1 else -1 := by
  split_ifs with h
  · rw [koszulSign, Int.negOnePow_even n h]; rfl
  · rw [koszulSign, Int.negOnePow_odd n (Int.not_even_iff_odd.mp h)]; rfl

section Basic

variable (R : Type*) [CommRing R] (A B : Type*) (M N : Type*) [AddCommGroup M]
  [AddCommGroup N] [Module R M] [Module R N]

instance instAddCommGroup : AddCommGroup (ExternalTensorOver R A B M N) :=
  inferInstanceAs (AddCommGroup (M ⊗[R] N))

instance instModuleBase : Module R (ExternalTensorOver R A B M N) :=
  inferInstanceAs (Module R (M ⊗[R] N))

variable {R A B M N}

/-- The pure tensor `m ⊗ n`. -/
def tmul (m : M) (n : N) : ExternalTensorOver R A B M N := m ⊗ₜ[R] n

theorem tmul_add (m : M) (n n' : N) :
    (tmul m (n + n') : ExternalTensorOver R A B M N) = tmul m n + tmul m n' :=
  TensorProduct.tmul_add m n n'

theorem add_tmul (m m' : M) (n : N) :
    (tmul (m + m') n : ExternalTensorOver R A B M N) = tmul m n + tmul m' n :=
  TensorProduct.add_tmul m m' n

@[simp]
theorem zero_tmul (n : N) : (tmul (0 : M) n : ExternalTensorOver R A B M N) = 0 :=
  TensorProduct.zero_tmul M n

@[simp]
theorem tmul_zero (m : M) : (tmul m (0 : N) : ExternalTensorOver R A B M N) = 0 :=
  TensorProduct.tmul_zero N m

theorem smul_tmul (r : R) (m : M) (n : N) :
    (tmul (r • m) n : ExternalTensorOver R A B M N) = tmul m (r • n) :=
  TensorProduct.smul_tmul r m n

theorem smul_tmul' (r : R) (m : M) (n : N) :
    (r • tmul m n : ExternalTensorOver R A B M N) = tmul (r • m) n :=
  TensorProduct.smul_tmul' r m n

theorem neg_tmul (m : M) (n : N) :
    (tmul (-m) n : ExternalTensorOver R A B M N) = -tmul m n :=
  TensorProduct.neg_tmul m n

theorem tmul_neg (m : M) (n : N) :
    (tmul m (-n) : ExternalTensorOver R A B M N) = -tmul m n :=
  TensorProduct.tmul_neg m n

theorem zsmul_tmul (k : ℤ) (m : M) (n : N) :
    (tmul (k • m) n : ExternalTensorOver R A B M N) = k • tmul m n := by
  change (k • m) ⊗ₜ[R] n = k • (m ⊗ₜ[R] n)
  rw [TensorProduct.smul_tmul']

theorem tmul_zsmul (k : ℤ) (m : M) (n : N) :
    (tmul m (k • n) : ExternalTensorOver R A B M N) = k • tmul m n := by
  change m ⊗ₜ[R] (k • n) = k • (m ⊗ₜ[R] n)
  rw [TensorProduct.tmul_smul]

theorem units_tmul (u : ℤˣ) (m : M) (n : N) :
    (tmul (u • m) n : ExternalTensorOver R A B M N) = u • tmul m n := by
  rw [Units.smul_def, Units.smul_def, zsmul_tmul]

theorem tmul_units (u : ℤˣ) (m : M) (n : N) :
    (tmul m (u • n) : ExternalTensorOver R A B M N) = u • tmul m n := by
  rw [Units.smul_def, Units.smul_def, tmul_zsmul]

/-- Additive maps out of `M ⊗_R N` from `R`-balanced biadditive maps. -/
def liftAddHom {P : Type*} [AddCommGroup P] (f : M →+ N →+ P)
    (hf : ∀ (r : R) (m : M) (n : N), f (r • m) n = f m (r • n)) :
    ExternalTensorOver R A B M N →+ P :=
  TensorProduct.liftAddHom f hf

@[simp]
theorem liftAddHom_tmul {P : Type*} [AddCommGroup P] (f : M →+ N →+ P)
    (hf : ∀ (r : R) (m : M) (n : N), f (r • m) n = f m (r • n)) (m : M) (n : N) :
    liftAddHom (A := A) (B := B) f hf (tmul m n) = f m n := rfl

end Basic

/-! ### The dg abelian group -/

section DGGroup

variable {R : Type*} [CommRing R]
  {A : Type*} [Ring A] [Algebra R A] [DGAddCommGroup A] [DGRing A] [DGAlgebra R A]
  {B : Type*} [Ring B] [Algebra R B] [DGAddCommGroup B] [DGRing B] [DGAlgebra R B]
  {M : Type*} [AddCommGroup M] [DGAddCommGroup M] [Module A M] [DGModule A M] [Module R M]
  [IsScalarTower R A M]
  {N : Type*} [AddCommGroup N] [DGAddCommGroup N] [Module B N] [DGModule B N] [Module R N]
  [IsScalarTower R B N]

/-- Induction principle on sums of tensors of homogeneous elements. -/
theorem induction_on {P : ExternalTensorOver R A B M N → Prop} (x : ExternalTensorOver R A B M N)
    (zero : P 0)
    (tmul' : ∀ {i j : ℤ} (m : M), m ∈ grading i → ∀ n : N, n ∈ grading j → P (tmul m n))
    (add : ∀ x y, P x → P y → P (x + y)) : P x := by
  refine TensorProduct.inductionOn (motive := P) x (fun m n => ?_) add
  induction m using DG.induction_on with
  | h_zero => rw [TensorProduct.zero_tmul]; exact zero
  | h_homogeneous m =>
    induction n using DG.induction_on with
    | h_zero => rw [TensorProduct.tmul_zero]; exact zero
    | h_homogeneous n => exact tmul' m.1 m.2 n.1 n.2
    | h_add n n' hn hn' => rw [TensorProduct.tmul_add]; exact add _ _ hn hn'
  | h_add m m' hm hm' => rw [TensorProduct.add_tmul]; exact add _ _ hm hm'

theorem addHom_ext {P : Type*} [AddCommGroup P] {f g : ExternalTensorOver R A B M N →+ P}
    (h : ∀ {i j : ℤ} (m : M), m ∈ grading i → ∀ n : N, n ∈ grading j →
      f (tmul m n) = g (tmul m n)) : f = g :=
  AddMonoidHom.ext fun x => induction_on (P := fun x => f x = g x) x (by simp) h
    fun x y (hx : f x = g x) (hy : f y = g y) => by
      show f (x + y) = g (x + y); rw [map_add, map_add, hx, hy]

variable (R A M) in
/-- The grade involution `m ↦ (-1)^{|m|} m`, an `R`-linear map. -/
def gradeInvolutionLinear : M →ₗ[R] M where
  __ := gradeInvolution M
  map_smul' r m := by
    change gradeInvolution M (r • m) = r • gradeInvolution M m
    induction m using DG.induction_on with
    | h_zero => simp
    | h_homogeneous m =>
      rw [gradeInvolution_of_mem (DGModule.ground_smul_mem A r m.2), gradeInvolution_of_mem m.2,
        Units.smul_def, Units.smul_def, smul_comm]
    | h_add m m' hm hm' => rw [smul_add, map_add, hm, hm', map_add, smul_add]

variable (R A B M N) in
/-- The degree-`k` part of `M ⊗_R N`, generated by the `m ⊗ n` with `|m| + |n| = k`. -/
def tensorGrading (k : ℤ) : AddSubgroup (ExternalTensorOver R A B M N) :=
  AddSubgroup.closure {x | ∃ i j, i + j = k ∧
    ∃ m ∈ grading (M := M) i, ∃ n ∈ grading (M := N) j, tmul m n = x}

theorem tmul_mem_tensorGrading {i j k : ℤ} (h : i + j = k) {m : M} (hm : m ∈ grading i) {n : N}
    (hn : n ∈ grading j) : tmul m n ∈ tensorGrading R A B M N k :=
  AddSubgroup.subset_closure ⟨i, j, h, m, hm, n, hn, rfl⟩

variable (R A B M N) in
/-- The differential `d (m ⊗ n) = d m ⊗ n + (-1)^{|m|} m ⊗ d n`. -/
def tensorD : ExternalTensorOver R A B M N →+ ExternalTensorOver R A B M N :=
  (TensorProduct.map (DGModule.dLinear R A M) LinearMap.id +
    TensorProduct.map (gradeInvolutionLinear R A M) (DGModule.dLinear R B N)).toAddMonoidHom

theorem tensorD_tmul (m : M) (n : N) :
    tensorD R A B M N (tmul m n) = tmul (d m) n + tmul (gradeInvolution M m) (d n) := rfl

theorem tensorD_tmul_of_mem {i : ℤ} {m : M} (hm : m ∈ grading i) (n : N) :
    tensorD R A B M N (tmul m n) = tmul (d m) n + koszulSign i • tmul m (d n) := by
  rw [tensorD_tmul, gradeInvolution_of_mem hm, units_tmul]

theorem tensorD_tensorD (x : ExternalTensorOver R A B M N) :
    tensorD R A B M N (tensorD R A B M N x) = 0 := by
  induction x using induction_on with
  | zero => rw [map_zero, map_zero]
  | add x y hx hy => rw [map_add, map_add, hx, hy, add_zero]
  | tmul' m _ n _ =>
    rw [tensorD_tmul, map_add, tensorD_tmul, tensorD_tmul, d_d, zero_tmul, zero_add, d_d,
      tmul_zero, d_gradeInvolution, neg_tmul, add_zero, add_neg_cancel]

theorem tensorD_mem {k : ℤ} {x : ExternalTensorOver R A B M N}
    (hx : x ∈ tensorGrading R A B M N k) :
    tensorD R A B M N x ∈ tensorGrading R A B M N (k + 1) := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨i, j, rfl, m, hm, n, hn, rfl⟩ := hx
    rw [tensorD_tmul_of_mem hm]
    refine add_mem (tmul_mem_tensorGrading (by ring) (d_mem hm) hn) ?_
    rw [Units.smul_def]
    exact zsmul_mem (tmul_mem_tensorGrading (by ring) hm (d_mem hn)) _
  | zero => rw [map_zero]; exact zero_mem _
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | neg x _ hx => rw [map_neg]; exact neg_mem hx

include A B in
/-- `liftHomogeneous₂` of an `R`-balanced family is `R`-balanced. -/
theorem liftHomogeneous₂_balanced {P : Type*} [AddCommGroup P]
    (φ : ∀ i j, grading (M := M) i →+ grading (M := N) j →+ P)
    (hφ : ∀ (r : R) {i j : ℤ} (m : grading (M := M) i) (n : grading (M := N) j),
      φ i j ⟨r • (m : M), DGModule.ground_smul_mem A r m.2⟩ n =
        φ i j m ⟨r • (n : N), DGModule.ground_smul_mem B r n.2⟩)
    (r : R) (m : M) (n : N) : liftHomogeneous₂ φ (r • m) n = liftHomogeneous₂ φ m (r • n) := by
  induction m using DG.induction_on with
  | h_zero => simp
  | h_homogeneous m =>
    induction n using DG.induction_on with
    | h_zero => simp
    | h_homogeneous n =>
      rw [liftHomogeneous₂_of_mem φ (DGModule.ground_smul_mem A r m.2) n.2,
        liftHomogeneous₂_of_mem φ m.2 (DGModule.ground_smul_mem B r n.2)]
      exact hφ r m n
    | h_add n n' hn hn' => rw [smul_add, map_add, map_add, hn, hn']
  | h_add m m' hm hm' => rw [smul_add, map_add, map_add, AddMonoidHom.add_apply,
      AddMonoidHom.add_apply, hm, hm']

/-- The additive map `M ⊗_R N →+ P` defined on tensors of homogeneous elements by an
`R`-balanced family. -/
def tensorLiftHomogeneous {P : Type*} [AddCommGroup P]
    (φ : ∀ i j, grading (M := M) i →+ grading (M := N) j →+ P)
    (hφ : ∀ (r : R) {i j : ℤ} (m : grading (M := M) i) (n : grading (M := N) j),
      φ i j ⟨r • (m : M), DGModule.ground_smul_mem A r m.2⟩ n =
        φ i j m ⟨r • (n : N), DGModule.ground_smul_mem B r n.2⟩) :
    ExternalTensorOver R A B M N →+ P :=
  liftAddHom (liftHomogeneous₂ φ) (liftHomogeneous₂_balanced (A := A) (B := B) φ hφ)

theorem tensorLiftHomogeneous_tmul {P : Type*} [AddCommGroup P]
    (φ : ∀ i j, grading (M := M) i →+ grading (M := N) j →+ P) (hφ) {i j : ℤ} {m : M}
    (hm : m ∈ grading i) {n : N} (hn : n ∈ grading j) :
    tensorLiftHomogeneous (R := R) (A := A) (B := B) φ hφ (tmul m n) = φ i j ⟨m, hm⟩ ⟨n, hn⟩ :=
  liftHomogeneous₂_of_mem φ hm hn

variable (R A B M N) in
/-- The decomposition of `M ⊗_R N` into total degrees, on homogeneous tensors. -/
def tensorDecomposeAux (i j : ℤ) :
    grading (M := M) i →+ grading (M := N) j →+ ⨁ k, tensorGrading R A B M N k :=
  AddMonoidHom.mk' (fun m => AddMonoidHom.mk'
    (fun n => DirectSum.of (fun k => tensorGrading R A B M N k) (i + j)
      ⟨tmul (m : M) (n : N), tmul_mem_tensorGrading rfl m.2 n.2⟩)
    (fun n n' => by
      rw [← map_add]; congr 1; ext; exact tmul_add _ _ _))
    (fun m m' => by
      ext n : 1
      simp only [AddMonoidHom.mk'_apply, AddMonoidHom.add_apply]
      rw [← map_add]; congr 1; ext; exact add_tmul _ _ _)

variable (R A B M N) in
/-- The decomposition of `M ⊗_R N` into total degrees. -/
def tensorDecompose : ExternalTensorOver R A B M N →+ ⨁ k, tensorGrading R A B M N k :=
  tensorLiftHomogeneous (tensorDecomposeAux R A B M N) fun r i j m n => by
    change DirectSum.of (fun k => tensorGrading R A B M N k) (i + j) ⟨_, _⟩ =
      DirectSum.of (fun k => tensorGrading R A B M N k) (i + j) ⟨_, _⟩
    congr 1; ext; exact smul_tmul r (m : M) (n : N)

theorem tensorDecompose_tmul {i j k : ℤ} (h : i + j = k) {m : M} (hm : m ∈ grading i) {n : N}
    (hn : n ∈ grading j) :
    tensorDecompose R A B M N (tmul m n) =
      DirectSum.of (fun k => tensorGrading R A B M N k) k
        ⟨tmul m n, tmul_mem_tensorGrading h hm hn⟩ := by
  subst h
  exact tensorLiftHomogeneous_tmul _ _ hm hn

theorem tensorDecompose_of_mem {k : ℤ} {x : ExternalTensorOver R A B M N}
    (hx : x ∈ tensorGrading R A B M N k) :
    tensorDecompose R A B M N x = DirectSum.of (fun k => tensorGrading R A B M N k) k ⟨x, hx⟩ := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨i, j, h, m, hm, n, hn, rfl⟩ := hx
    rw [tensorDecompose_tmul h hm hn]
  | zero => rw [map_zero]; exact (map_zero _).symm.trans (congrArg _ rfl)
  | add x y hx' hy' hx hy => rw [map_add, hx, hy, ← map_add]; rfl
  | neg x hx' hx => rw [map_neg, hx, ← map_neg]; rfl

/-- The decomposition `(M ⊗_R N)ᵏ = Σ_{i+j=k} Mⁱ ⊗ Nʲ`. -/
instance tensorDecomposition : Decomposition (tensorGrading R A B M N) :=
  Decomposition.ofAddHom _ (tensorDecompose R A B M N)
    (addHom_ext fun m hm n hn => by
      simp only [AddMonoidHom.coe_comp, Function.comp_apply, AddMonoidHom.id_apply]
      rw [tensorDecompose_tmul rfl hm hn, coeAddMonoidHom_of])
    (DirectSum.addHom_ext fun k x => by
      simp only [AddMonoidHom.coe_comp, Function.comp_apply, coeAddMonoidHom_of,
        AddMonoidHom.id_apply]
      exact tensorDecompose_of_mem x.2)

/-- **`M ⊗_R N` is a dg abelian group.** -/
instance instDGAddCommGroup : DGAddCommGroup (ExternalTensorOver R A B M N) where
  grading := tensorGrading R A B M N
  d := tensorD R A B M N
  d_mem' := tensorD_mem
  d_d' := tensorD_tensorD

theorem tmul_mem_grading {i j : ℤ} {m : M} (hm : m ∈ grading i) {n : N} (hn : n ∈ grading j) :
    (tmul m n : ExternalTensorOver R A B M N) ∈ grading (i + j) :=
  tmul_mem_tensorGrading rfl hm hn

theorem d_tmul (m : M) (n : N) :
    d (tmul m n : ExternalTensorOver R A B M N) =
      tmul (d m) n + tmul (gradeInvolution M m) (d n) := rfl

/-- `d (m ⊗ n) = d m ⊗ n + (-1)^{|m|} m ⊗ d n`. -/
theorem d_tmul_of_mem {i : ℤ} {m : M} (hm : m ∈ grading i) (n : N) :
    d (tmul m n : ExternalTensorOver R A B M N) = tmul (d m) n + koszulSign i • tmul m (d n) :=
  tensorD_tmul_of_mem hm n

/-- An additive map out of `M ⊗_R N` taking `Mⁱ ⊗ Nʲ` to degree `i + j + s` has degree `s`. -/
theorem map_mem_grading_of_tmul {Y : Type*} [AddCommGroup Y] [DGAddCommGroup Y]
    (f : ExternalTensorOver R A B M N →+ Y) (s : ℤ)
    (h : ∀ {i j : ℤ} {m : M} {n : N}, m ∈ grading i → n ∈ grading j →
      f (tmul m n) ∈ grading (i + j + s)) {k : ℤ} {x : ExternalTensorOver R A B M N}
    (hx : x ∈ grading k) : f x ∈ grading (k + s) := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨i, j, rfl, m, hm, n, hn, rfl⟩ := hx
    exact h hm hn
  | zero => rw [map_zero]; exact zero_mem _
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | neg x _ hx => rw [map_neg]; exact neg_mem hx

end DGGroup

/-! ### The dg module over `A ᵍ⊗[R] B` -/

section Module

variable {R : Type*} [CommRing R]
  {A : Type*} [Ring A] [Algebra R A] [DGAddCommGroup A] [DGRing A] [DGAlgebra R A]
  {B : Type*} [Ring B] [Algebra R B] [DGAddCommGroup B] [DGRing B] [DGAlgebra R B]
  {M : Type*} [AddCommGroup M] [DGAddCommGroup M] [Module A M] [DGModule A M] [Module R M]
  [IsScalarTower R A M]
  {N : Type*} [AddCommGroup N] [DGAddCommGroup N] [Module B N] [DGModule B N] [Module R N]
  [IsScalarTower R B N]

local notation "𝒜" => DGAlgebra.gradingSubmodule R A
local notation "ℬ" => DGAlgebra.gradingSubmodule R B

omit [DGRing A] [DGAlgebra R A] [DGModule A M] in
theorem smul_ground_comm (a : A) (r : R) (m : M) : a • (r • m) = r • (a • m) := by
  rw [← algebraMap_smul A r m, smul_smul, ← Algebra.commutes, ← smul_smul, algebraMap_smul]

omit [DGRing A] [DGAlgebra R A] in
theorem twist_ground_smul (i : ℤ) (r : R) (b : B) :
    ExternalTensor.twist B i (r • b) = r • ExternalTensor.twist B i b := by
  induction b using DG.induction_on with
  | h_zero => simp
  | @h_homogeneous k b =>
    have hrb : r • (b : B) ∈ grading k := by
      rw [Algebra.smul_def]
      simpa using mul_mem_grading (algebraMap_mem_grading R (A := B) r) b.2
    rw [ExternalTensor.twist_of_mem i hrb, ExternalTensor.twist_of_mem i b.2, Units.smul_def,
      Units.smul_def, smul_comm]
  | h_add b b' hb hb' => rw [smul_add, map_add, hb, hb', map_add, smul_add]

variable (R M N) in
/-- The action of `a ⊗ b`, `m ⊗ n ↦ (-1)^{|b| |m|} (a • m) ⊗ (b • n)`. -/
def act (a : A) (b : B) : ExternalTensorOver R A B M N →+ ExternalTensorOver R A B M N :=
  tensorLiftHomogeneous (fun i _ =>
    AddMonoidHom.mk' (fun m => AddMonoidHom.mk'
      (fun n => (tmul (a • (m : M)) (ExternalTensor.twist B i b • (n : N)) :
        ExternalTensorOver R A B M N))
      fun n n' => by simp [smul_add, tmul_add])
      fun m m' => by ext n; simp [smul_add, add_tmul])
    fun r i j m n => by
      change (tmul (a • (r • (m : M))) (ExternalTensor.twist B i b • (n : N)) :
          ExternalTensorOver R A B M N) =
        tmul (a • (m : M)) (ExternalTensor.twist B i b • (r • (n : N)))
      rw [smul_ground_comm, smul_ground_comm, smul_tmul]

theorem act_tmul (a : A) (b : B) {i j : ℤ} {m : M} (hm : m ∈ grading i) {n : N}
    (hn : n ∈ grading j) :
    act R M N a b (tmul m n) = tmul (a • m) (ExternalTensor.twist B i b • n) :=
  tensorLiftHomogeneous_tmul _ _ hm hn

theorem act_tmul_of_mem (a : A) {k : ℤ} {b : B} (hb : b ∈ grading k) {i : ℤ} {m : M}
    (hm : m ∈ grading i) (n : N) :
    act R M N a b (tmul m n) = koszulSign (k * i) • tmul (a • m) (b • n) := by
  induction n using DG.induction_on with
  | h_zero => simp
  | h_homogeneous n =>
    rw [act_tmul a b hm n.2, ExternalTensor.twist_of_mem i hb, Units.smul_def, Units.smul_def,
      smul_assoc, tmul_zsmul]
  | h_add n n' hn hn' => rw [tmul_add, map_add, hn, hn', smul_add, tmul_add, smul_add]

variable (R M N) in
/-- The action as a biadditive map. -/
def actBilin : A →+ B →+ AddMonoid.End (ExternalTensorOver R A B M N) :=
  AddMonoidHom.mk' (fun a => AddMonoidHom.mk' (fun b => act R M N a b) fun b b' =>
      addHom_ext fun m hm n hn => by
        change act R M N a (b + b') _ = act R M N a b _ + act R M N a b' _
        rw [act_tmul a _ hm hn, act_tmul a _ hm hn, act_tmul a _ hm hn, map_add, add_smul,
          tmul_add])
    fun a a' => by
      ext b : 1
      refine addHom_ext fun m hm n hn => ?_
      change act R M N (a + a') b _ = act R M N a b _ + act R M N a' b _
      rw [act_tmul _ b hm hn, act_tmul _ b hm hn, act_tmul _ b hm hn, add_smul, add_tmul]

theorem actBilin_balanced (r : R) (a : A) (b : B) :
    actBilin R M N (r • a) b = actBilin R M N a (r • b) :=
  addHom_ext fun {i j} m hm n hn => by
    change act R M N (r • a) b (tmul m n) = act R M N a (r • b) (tmul m n)
    rw [act_tmul _ _ hm hn, act_tmul _ _ hm hn, twist_ground_smul, smul_assoc, smul_assoc,
      smul_tmul]

variable (R M N) in
/-- The action of `A ⊗_R B`, as an additive map to the endomorphisms. -/
def actionAdd : (𝒜 ᵍ⊗[R] ℬ) →+ AddMonoid.End (ExternalTensorOver R A B M N) :=
  (TensorProduct.liftAddHom (R := R) (M := A) (N := B) (actBilin R M N)
    (fun r a b => actBilin_balanced (M := M) (N := N) r a b)).comp
    (_root_.GradedTensorProduct.of R 𝒜 ℬ).symm.toLinearMap.toAddMonoidHom

theorem actionAdd_tmul (a : A) (b : B) :
    actionAdd R M N (a ᵍ⊗ₜ[R] b) = act R M N a b := rfl

theorem tmul_mul_tmul_act {j i' j' : ℤ} (a : A) {b : B}
    (hb : b ∈ grading j) {a' : A} (ha' : a' ∈ grading i') {b' : B} (hb' : b' ∈ grading j')
    (x : ExternalTensorOver R A B M N) :
    actionAdd R M N ((a ᵍ⊗ₜ[R] b : 𝒜 ᵍ⊗[R] ℬ) * (a' ᵍ⊗ₜ[R] b')) x =
      act R M N a b (act R M N a' b' x) := by
  rw [GradedTensorProduct.tmul_mul_tmul 𝒜 ℬ a hb ha' b', Units.smul_def, map_zsmul,
    actionAdd_tmul]
  induction x using induction_on with
  | zero => simp
  | add x y hx hy => rw [map_add, map_add, map_add, ← hx, ← hy]
  | @tmul' p q m hm n hn =>
    change ((koszulSign (j * i') : ℤ) • act R M N (a * a') (b * b')) (tmul m n) = _
    rw [AddMonoidHom.zsmul_apply, act_tmul_of_mem _ (mul_mem_grading hb hb') hm,
      act_tmul_of_mem _ hb' hm, map_units_zsmul,
      act_tmul_of_mem _ hb (smul_mem_grading ha' hm), smul_smul, smul_smul, mul_smul, mul_smul,
      ← Units.smul_def, smul_smul, ← koszulSign_add, ← koszulSign_add]
    congr 1
    exact ks_eq ⟨0, by ring⟩

variable (R M N) in
/-- The action of `A ⊗_R B` on `M ⊗_R N`, a ring homomorphism. -/
def actionHom : (𝒜 ᵍ⊗[R] ℬ) →+* AddMonoid.End (ExternalTensorOver R A B M N) where
  __ := actionAdd R M N
  map_one' := by
    show actionAdd R M N 1 = (1 : AddMonoid.End (ExternalTensorOver R A B M N))
    refine AddMonoidHom.ext fun x => ?_
    show act R M N 1 1 x = x
    induction x using induction_on with
    | zero => simp
    | add x y hx hy => rw [map_add, hx, hy]
    | tmul' m hm n hn =>
      rw [act_tmul_of_mem _ (one_mem_grading (A := B)) hm, zero_mul, koszulSign_zero, one_smul,
        one_smul, one_smul]
  map_mul' x y := by
    show actionAdd R M N (x * y) = actionAdd R M N x * actionAdd R M N y
    induction x using GradedTensorProduct.induction_on_tmul (R := R) with
    | zero => rw [zero_mul, map_zero, zero_mul]
    | add x x' hx hx' => rw [add_mul, map_add, hx, hx', map_add, add_mul]
    | @tmul i j a ha b hb =>
      induction y using GradedTensorProduct.induction_on_tmul (R := R) with
      | zero => rw [mul_zero, map_zero, mul_zero]
      | add y y' hy hy' => rw [mul_add, map_add, hy, hy', map_add, mul_add]
      | @tmul i' j' a' ha' b' hb' =>
        ext x
        exact tmul_mul_tmul_act a hb ha' hb' x

instance instModule : Module (𝒜 ᵍ⊗[R] ℬ) (ExternalTensorOver R A B M N) :=
  Module.compHom (ExternalTensorOver R A B M N) (actionHom R M N)

theorem smul_def (x : 𝒜 ᵍ⊗[R] ℬ) (y : ExternalTensorOver R A B M N) :
    x • y = actionHom R M N x y := rfl

/-- **The Koszul sign rule** `(a ⊗ b) • (m ⊗ n) = (-1)^{|b| |m|} (a • m) ⊗ (b • n)`. -/
theorem tmul_smul_tmul (a : A) {k : ℤ} {b : B} (hb : b ∈ grading k) {i : ℤ} {m : M}
    (hm : m ∈ grading i) (n : N) :
    (a ᵍ⊗ₜ[R] b : 𝒜 ᵍ⊗[R] ℬ) • (tmul m n : ExternalTensorOver R A B M N) =
      koszulSign (k * i) • tmul (a • m) (b • n) :=
  act_tmul_of_mem a hb hm n

theorem act_mem {i j : ℤ} {a : A} (ha : a ∈ grading i) {b : B} (hb : b ∈ grading j) {q : ℤ}
    {y : ExternalTensorOver R A B M N} (hy : y ∈ grading q) :
    act R M N a b y ∈ grading (q + (i + j)) := by
  refine map_mem_grading_of_tmul (act R M N a b) (i + j) (fun {i' j' m n} hm hn => ?_) hy
  rw [act_tmul_of_mem a hb hm n, Units.smul_def]
  refine zsmul_mem ?_ _
  have := tmul_mem_grading (R := R) (A := A) (B := B) (smul_mem_grading ha hm)
    (smul_mem_grading hb hn)
  rwa [show i + i' + (j + j') = i' + j' + (i + j) by ring] at this

theorem smul_units_smul (x : 𝒜 ᵍ⊗[R] ℬ) (u : ℤˣ) (y : ExternalTensorOver R A B M N) :
    x • (u • y) = u • (x • y) := by
  rw [smul_def, smul_def]
  exact map_units_zsmul (actionHom R M N x : ExternalTensorOver R A B M N →+ _) u y

theorem units_smul_smul (u : ℤˣ) (x : 𝒜 ᵍ⊗[R] ℬ) (y : ExternalTensorOver R A B M N) :
    (u • x) • y = u • (x • y) := by
  rw [smul_def, smul_def, Units.smul_def, map_zsmul, Units.smul_def]
  rfl

theorem zero_smul' (y : ExternalTensorOver R A B M N) : (0 : 𝒜 ᵍ⊗[R] ℬ) • y = 0 := by
  rw [smul_def, map_zero]; rfl

theorem smul_zero' (x : 𝒜 ᵍ⊗[R] ℬ) : x • (0 : ExternalTensorOver R A B M N) = 0 := by
  rw [smul_def, map_zero]

theorem add_smul' (x x' : 𝒜 ᵍ⊗[R] ℬ) (y : ExternalTensorOver R A B M N) :
    (x + x') • y = x • y + x' • y := by
  rw [smul_def, smul_def, smul_def, map_add]; rfl

theorem smul_add' (x : 𝒜 ᵍ⊗[R] ℬ) (y y' : ExternalTensorOver R A B M N) :
    x • (y + y') = x • y + x • y' := by
  rw [smul_def, smul_def, smul_def, map_add]

theorem d_tmul_smul_tmul {i j k : ℤ} {a : A} (ha : a ∈ grading i) {b : B} (hb : b ∈ grading j)
    {m : M} (hm : m ∈ grading k) (n : N) :
    d ((a ᵍ⊗ₜ[R] b : 𝒜 ᵍ⊗[R] ℬ) • (tmul m n : ExternalTensorOver R A B M N)) =
      d (a ᵍ⊗ₜ[R] b : 𝒜 ᵍ⊗[R] ℬ) • (tmul m n : ExternalTensorOver R A B M N) +
        koszulSign (i + j) • ((a ᵍ⊗ₜ[R] b : 𝒜 ᵍ⊗[R] ℬ) •
          d (tmul m n : ExternalTensorOver R A B M N)) := by
  rw [tmul_smul_tmul a hb hm n, d_units_smul, d_tmul_of_mem (smul_mem_grading ha hm),
    d_smul ha m, d_smul hb n, GradedTensorProduct.d_tmul ha b, add_smul', d_tmul_of_mem hm n,
    units_smul_smul, smul_add' (a ᵍ⊗ₜ[R] b : 𝒜 ᵍ⊗[R] ℬ), smul_units_smul,
    tmul_smul_tmul (d a) hb hm n,
    tmul_smul_tmul a (d_mem hb) hm n, tmul_smul_tmul a hb (d_mem hm) n,
    tmul_smul_tmul a hb hm (d n)]
  simp only [Units.smul_def, add_tmul, tmul_add, zsmul_tmul, tmul_zsmul, smul_add, smul_smul,
    ks_val]
  by_cases hi : Even i <;> by_cases hj : Even j <;> by_cases hk : Even k <;>
    simp [Int.even_add, Int.even_mul, ← Int.not_even_iff_odd, hi, hj, hk] <;> abel

theorem smul_mem_grading' {p q : ℤ} {x : 𝒜 ᵍ⊗[R] ℬ} (hx : x ∈ grading p)
    {y : ExternalTensorOver R A B M N} (hy : y ∈ grading q) : x • y ∈ grading (p + q) := by
  refine GradedTensorProduct.grading_induction 𝒜 ℬ hx
    (motive := fun x => x • y ∈ grading (p + q)) ?_ ?_ ?_
  · rw [zero_smul']; exact zero_mem _
  · intro i j a b hij
    have := act_mem a.2 b.2 hy
    rw [show q + (i + j) = p + q by omega] at this
    exact this
  · intro x x' hx hx'
    rw [add_smul']
    exact add_mem hx hx'

theorem d_smul_tmul {i j : ℤ} {a : A} (ha : a ∈ grading i) {b : B} (hb : b ∈ grading j)
    (y : ExternalTensorOver R A B M N) :
    d ((a ᵍ⊗ₜ[R] b : 𝒜 ᵍ⊗[R] ℬ) • y) =
      d (a ᵍ⊗ₜ[R] b : 𝒜 ᵍ⊗[R] ℬ) • y +
        koszulSign (i + j) • ((a ᵍ⊗ₜ[R] b : 𝒜 ᵍ⊗[R] ℬ) • d y) := by
  induction y using induction_on with
  | zero => simp only [d_zero, smul_zero, add_zero]
  | add y y' hy hy' =>
    simp only [d_add, hy, hy', smul_add]
    abel
  | tmul' m hm n hn => exact d_tmul_smul_tmul ha hb hm n

theorem d_smul_of_mem {p : ℤ} {x : 𝒜 ᵍ⊗[R] ℬ} (hx : x ∈ grading p)
    (y : ExternalTensorOver R A B M N) :
    d (x • y) = d x • y + koszulSign p • (x • d y) := by
  refine GradedTensorProduct.grading_induction 𝒜 ℬ hx
    (motive := fun x => d (x • y) = d x • y + koszulSign p • (x • d y)) ?_ ?_ ?_
  · rw [zero_smul', d_zero, d_zero, zero_smul', zero_smul', smul_zero, add_zero]
  · intro i j a b hij
    subst hij
    exact d_smul_tmul a.2 b.2 y
  · intro x x' hx hx'
    rw [add_smul', d_add, hx, hx', d_add, add_smul', add_smul', smul_add]
    abel

/-- **`M ⊗_R N` is a dg module over `A ⊗_R B`.** -/
instance instDGModule : DGModule (𝒜 ᵍ⊗[R] ℬ) (ExternalTensorOver R A B M N) where
  smul_mem _ _ _ _ hx hy := smul_mem_grading' hx hy
  d_smul' hx y := d_smul_of_mem hx y

/-! ### Functoriality -/

variable {M' : Type*} [AddCommGroup M'] [DGAddCommGroup M'] [Module A M'] [DGModule A M']
  [Module R M'] [IsScalarTower R A M']
  {N' : Type*} [AddCommGroup N'] [DGAddCommGroup N'] [Module B N'] [DGModule B N']
  [Module R N'] [IsScalarTower R B N']

variable (R A B) in
/-- The tensor product `f ⊗ g` of `A`- and `B`-linear maps, as an additive map. -/
def tensorMap (f : M →ₗ[A] M') (g : N →ₗ[B] N') :
    ExternalTensorOver R A B M N →+ ExternalTensorOver R A B M' N' :=
  (TensorProduct.map (f.restrictScalars R) (g.restrictScalars R)).toAddMonoidHom

@[simp]
theorem tensorMap_tmul (f : M →ₗ[A] M') (g : N →ₗ[B] N') (m : M) (n : N) :
    tensorMap R A B f g (tmul m n) = tmul (f m) (g n) := rfl

/-- `f ⊠ g` as a morphism of dg modules over `A ⊗_R B`. -/
def tensorDGHom (f : M →ᵈᵍ[A] M') (g : N →ᵈᵍ[B] N') :
    ExternalTensorOver R A B M N →ᵈᵍ[𝒜 ᵍ⊗[R] ℬ] ExternalTensorOver R A B M' N' where
  toFun := tensorMap R A B f.toLinearMap g.toLinearMap
  map_add' := map_add _
  map_smul' x y := by
    change tensorMap R A B f.toLinearMap g.toLinearMap (x • y) =
      x • tensorMap R A B f.toLinearMap g.toLinearMap y
    induction x using GradedTensorProduct.induction_on_tmul (R := R) with
    | zero => rw [zero_smul', zero_smul', map_zero]
    | add x x' hx hx' => rw [add_smul', map_add, hx, hx', add_smul']
    | @tmul i j a ha b hb =>
      induction y using induction_on with
      | zero => rw [smul_zero', map_zero, smul_zero']
      | add y y' hy hy' => rw [smul_add', map_add, hy, hy', map_add, smul_add']
      | tmul' m hm n hn =>
        rw [tmul_smul_tmul a hb hm n, map_units_zsmul, tensorMap_tmul]
        change _ = (a ᵍ⊗ₜ[R] b : 𝒜 ᵍ⊗[R] ℬ) • (tmul (f m) (g n) : ExternalTensorOver R A B M' N')
        rw [tmul_smul_tmul a hb (f.map_mem hm) (g n)]
        change koszulSign (j * _) •
          (tmul (f (a • m)) (g (b • n)) : ExternalTensorOver R A B M' N') = _
        rw [map_smul, map_smul]
  map_mem' {k y} hy := by
    have := map_mem_grading_of_tmul (tensorMap R A B f.toLinearMap g.toLinearMap) 0
      (fun {i j m n} hm hn => by
        rw [add_zero, tensorMap_tmul]
        exact tmul_mem_grading (f.map_mem hm) (g.map_mem hn)) hy
    rwa [add_zero] at this
  map_d' y := by
    change tensorMap R A B f.toLinearMap g.toLinearMap (d y) =
      d (tensorMap R A B f.toLinearMap g.toLinearMap y)
    induction y using induction_on with
    | zero => simp
    | add y y' hy hy' => rw [d_add, map_add, hy, hy', map_add, d_add]
    | tmul' m hm n hn =>
      rw [d_tmul_of_mem hm, map_add, map_units_zsmul, tensorMap_tmul, tensorMap_tmul,
        tensorMap_tmul]
      change (tmul (f (d m)) (g n) : ExternalTensorOver R A B M' N') +
          koszulSign _ • tmul (f m) (g (d n)) = d (tmul (f m) (g n))
      rw [d_tmul_of_mem (f.map_mem hm), f.map_d, g.map_d]

@[simp]
theorem tensorDGHom_tmul (f : M →ᵈᵍ[A] M') (g : N →ᵈᵍ[B] N') (m : M) (n : N) :
    tensorDGHom (R := R) f g (tmul m n) = tmul (f m) (g n) := rfl

end Module

/-! ### Comparison with the external tensor product over `ℤ` -/

section Int

variable {A : Type*} [Ring A] [DGAddCommGroup A] [DGRing A]
  {B : Type*} [Ring B] [DGAddCommGroup B] [DGRing B]
  {M : Type*} [AddCommGroup M] [DGAddCommGroup M] [Module A M] [DGModule A M]
  {N : Type*} [AddCommGroup N] [DGAddCommGroup N] [Module B N] [DGModule B N]

local notation "𝒜" => DGAlgebra.gradingSubmodule ℤ A
local notation "ℬ" => DGAlgebra.gradingSubmodule ℤ B

theorem act_int_eq (a : A) (b : B) :
    (act ℤ M N a b : ExternalTensorOver ℤ A B M N →+ ExternalTensorOver ℤ A B M N) =
      (ExternalTensor.act M N a b : M ⊗[ℤ] N →+ M ⊗[ℤ] N) :=
  DG.tensor_addHom_ext fun m n =>
    (act_tmul (R := ℤ) a b m.2 n.2).trans (ExternalTensor.act_tmul a b m.2 n.2).symm

theorem actionAdd_int_eq :
    (actionAdd ℤ M N : 𝒜 ᵍ⊗[ℤ] ℬ →+ AddMonoid.End (ExternalTensorOver ℤ A B M N)) =
      (ExternalTensor.actionAdd M N : 𝒜 ᵍ⊗[ℤ] ℬ →+ AddMonoid.End (M ⊗[ℤ] N)) := by
  have h : (actBilin ℤ M N : A →+ B →+ AddMonoid.End (ExternalTensorOver ℤ A B M N)) =
      (ExternalTensor.actBilin M N : A →+ B →+ AddMonoid.End (M ⊗[ℤ] N)) :=
    AddMonoidHom.ext fun a => AddMonoidHom.ext fun b => act_int_eq a b
  unfold actionAdd ExternalTensor.actionAdd
  congr 1

variable (A B M N) in
/-- **For `R = ℤ`, `M ⊗_ℤ N` is the external tensor product over `ℤ`**: the identity of
`M ⊗[ℤ] N` is an isomorphism of dg modules over `A ᵍ⊗[ℤ] B` between
`DG.ExternalTensorOver ℤ A B M N` and `M ⊗[ℤ] N` with the structure of
`DG/Module/ExternalTensor.lean`. -/
def intEquiv : ExternalTensorOver ℤ A B M N ≃ᵈᵍ[𝒜 ᵍ⊗[ℤ] ℬ] (M ⊗[ℤ] N) where
  toFun x := x
  invFun x := x
  left_inv _ := rfl
  right_inv _ := rfl
  map_add' _ _ := rfl
  map_smul' x y := DFunLike.congr_fun (DFunLike.congr_fun actionAdd_int_eq x) y
  map_mem' {k y} hy := by
    have := map_mem_grading_of_tmul (R := ℤ) (A := A) (B := B) (M := M) (N := N)
      (Y := M ⊗[ℤ] N) (AddMonoidHom.id _) 0
      (fun {i j m n} hm hn => by
        rw [add_zero]
        exact DG.tmul_mem_grading hm hn) hy
    rw [add_zero] at this
    exact this
  map_d' y := by
    have h : (d : ExternalTensorOver ℤ A B M N →+ ExternalTensorOver ℤ A B M N) =
        (d : M ⊗[ℤ] N →+ M ⊗[ℤ] N) := addHom_ext fun {i j} m hm n hn => by
      change d (tmul m n : ExternalTensorOver ℤ A B M N) = d (m ⊗ₜ[ℤ] n : M ⊗[ℤ] N)
      rw [d_tmul_of_mem hm, DG.d_tmul_of_mem hm]
      rfl
    exact DFunLike.congr_fun h y

@[simp]
theorem intEquiv_tmul (m : M) (n : N) :
    intEquiv A B M N (tmul m n) = m ⊗ₜ[ℤ] n := rfl

end Int

end ExternalTensorOver

end DG
