import DG.Algebra.Basic
import Mathlib.Algebra.Group.Subgroup.Pointwise
import Mathlib.GroupTheory.QuotientGroup.Defs

/-!
# Quotients of dg abelian groups

A subgroup `S` of a dg abelian group `M` is a *dg subgroup* (`DG.IsDGAddSubgroup S`) if it is
homogeneous (it contains the homogeneous components of each of its elements) and stable under
the differential. The quotient `M ⧸ S` is then a dg abelian group
(`DG.DGAddCommGroup.quotient`), graded by the images `(M ⧸ S)ⁿ = π (Mⁿ)` of the homogeneous
components and with the induced differential `d (π x) = π (d x)`, `π : M → M ⧸ S` the quotient
map.

A subgroup generated by homogeneous elements is homogeneous
(`DG.IsDGAddSubgroup.decompose_mem_closure`); this is the usual way to check the first
condition.
-/

open DirectSum

namespace DG

variable {M : Type*} [AddCommGroup M] [DGAddCommGroup M]

/-- A dg subgroup of a dg abelian group: a subgroup which is homogeneous (it contains the
homogeneous components of each of its elements) and stable under the differential. -/
class IsDGAddSubgroup (S : AddSubgroup M) : Prop where
  decompose_mem : ∀ {x : M}, x ∈ S → ∀ n : ℤ, (decompose (grading (M := M)) x n : M) ∈ S
  d_mem : ∀ {x : M}, x ∈ S → d x ∈ S

/-- A subgroup generated by homogeneous elements contains the homogeneous components of each
of its elements. -/
theorem decompose_mem_closure {T : Set M} (hT : ∀ x ∈ T, ∃ n, x ∈ grading (M := M) n) {x : M}
    (hx : x ∈ AddSubgroup.closure T) (n : ℤ) :
    (decompose (grading (M := M)) x n : M) ∈ AddSubgroup.closure T := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨k, hk⟩ := hT x hx
    by_cases hkn : k = n
    · subst hkn
      rw [decompose_of_mem_same _ hk]
      exact AddSubgroup.subset_closure hx
    · rw [decompose_of_mem_ne _ hk hkn]
      exact zero_mem _
  | one => simpa using zero_mem (AddSubgroup.closure T)
  | mul x y _ _ hx hy => simpa [decompose_add] using add_mem hx hy
  | inv x _ hx =>
    rw [decompose_neg, ← zero_sub, DirectSum.sub_apply]
    simpa using neg_mem hx

/-- A subgroup generated by homogeneous elements, whose differentials lie in it, is a dg
subgroup. -/
theorem IsDGAddSubgroup.closure {T : Set M} (hT : ∀ x ∈ T, ∃ n, x ∈ grading (M := M) n)
    (hd : ∀ x ∈ T, d x ∈ AddSubgroup.closure T) : IsDGAddSubgroup (AddSubgroup.closure T) where
  decompose_mem hx n := decompose_mem_closure hT hx n
  d_mem {x} hx := by
    induction hx using AddSubgroup.closure_induction with
    | mem x hx => exact hd x hx
    | one => rw [d_zero]; exact zero_mem _
    | mul x y _ _ hx hy => rw [d_add]; exact add_mem hx hy
    | inv x _ hx => rw [d_neg]; exact neg_mem hx

namespace DGAddCommGroup

variable (S : AddSubgroup M) [hS : IsDGAddSubgroup S]

/-- The homogeneous components of `M ⧸ S`: the images of those of `M`. -/
def quotientGrading (n : ℤ) : AddSubgroup (M ⧸ S) :=
  (grading (M := M) n).map (QuotientAddGroup.mk' S)

/-- The homogeneous decomposition of `M`, followed by the quotient map on each component. -/
def quotientDecomposeAux : M →+ ⨁ n, quotientGrading S n :=
  (DirectSum.map fun n => ((QuotientAddGroup.mk' S).restrict (grading (M := M) n)).codRestrict
    (quotientGrading S n) fun x => ⟨x, x.2, rfl⟩).comp
    (decomposeAddEquiv (grading (M := M))).toAddMonoidHom

omit hS in
theorem quotientDecomposeAux_of_mem {n : ℤ} {x : M} (hx : x ∈ grading n) :
    quotientDecomposeAux S x = DirectSum.of (fun n => quotientGrading S n) n
      ⟨QuotientAddGroup.mk x, x, hx, rfl⟩ := by
  simp only [quotientDecomposeAux, AddMonoidHom.coe_comp, Function.comp_apply,
    AddEquiv.coe_toAddMonoidHom, decomposeAddEquiv_apply, decompose_of_mem _ hx,
    DirectSum.map_of]
  rfl

/-- The homogeneous decomposition of `M ⧸ S`. -/
def quotientDecompose : M ⧸ S →+ ⨁ n, quotientGrading S n :=
  QuotientAddGroup.lift S (quotientDecomposeAux S) fun x hx => by
    refine DirectSum.ext _ fun n => Subtype.ext ?_
    simp only [quotientDecomposeAux, AddMonoidHom.coe_comp, Function.comp_apply,
      AddEquiv.coe_toAddMonoidHom, decomposeAddEquiv_apply, DirectSum.map_apply,
      AddMonoidHom.codRestrict_apply, AddMonoidHom.restrict_apply, QuotientAddGroup.mk'_apply,
      DirectSum.zero_apply, ZeroMemClass.coe_zero]
    exact (QuotientAddGroup.eq_zero_iff _).mpr (hS.decompose_mem hx n)

instance quotientDecomposition : Decomposition (quotientGrading S) :=
  Decomposition.ofAddHom _ (quotientDecompose S)
    (by
      refine QuotientAddGroup.addMonoidHom_ext S (AddMonoidHom.ext fun x => ?_)
      induction x using induction_on with
      | h_zero => simp
      | h_homogeneous x =>
        simp [quotientDecompose, quotientDecomposeAux_of_mem S x.2]
      | h_add x y hx hy =>
        simp only [AddMonoidHom.coe_comp, Function.comp_apply, AddMonoidHom.id_apply] at hx hy ⊢
        rw [QuotientAddGroup.mk'_apply, QuotientAddGroup.mk_add, map_add, map_add,
          ← QuotientAddGroup.mk'_apply, hx, ← QuotientAddGroup.mk'_apply, hy])
    (DirectSum.addHom_ext fun n y => by
      obtain ⟨x, hx, hxy⟩ := y.2
      obtain rfl : y = ⟨QuotientAddGroup.mk x, x, hx, rfl⟩ := Subtype.ext hxy.symm
      simp only [AddMonoidHom.coe_comp, Function.comp_apply, coeAddMonoidHom_of,
        AddMonoidHom.id_apply]
      exact quotientDecomposeAux_of_mem S hx)

/-- The quotient of a dg abelian group by a dg subgroup is a dg abelian group, with
`(M ⧸ S)ⁿ` the image of `Mⁿ` and the induced differential. -/
instance quotient : DGAddCommGroup (M ⧸ S) where
  grading := quotientGrading S
  d := QuotientAddGroup.map S S d fun _ hx => hS.d_mem hx
  d_mem' {n y} hy := by
    obtain ⟨x, hx, rfl⟩ := hy
    exact ⟨d x, d_mem hx, rfl⟩
  d_d' y := by
    induction y using QuotientAddGroup.induction_on with
    | H x =>
      simp only [QuotientAddGroup.map_mk, d_d, QuotientAddGroup.mk_zero]

end DGAddCommGroup

section Quotient

variable {S : AddSubgroup M} [IsDGAddSubgroup S]

theorem mem_grading_quotient_iff {n : ℤ} {y : M ⧸ S} :
    y ∈ grading n ↔ ∃ x ∈ grading (M := M) n, (QuotientAddGroup.mk x : M ⧸ S) = y :=
  Iff.rfl

theorem mk_mem_grading_quotient {n : ℤ} {x : M} (hx : x ∈ grading n) :
    (QuotientAddGroup.mk x : M ⧸ S) ∈ grading n :=
  ⟨x, hx, rfl⟩

@[simp]
theorem d_quotient_mk (x : M) : d (QuotientAddGroup.mk x : M ⧸ S) = QuotientAddGroup.mk (d x) :=
  rfl

end Quotient

end DG
