import DG.Graded.Basic
import DG.Module.Right
import DG.Algebra.AddEquiv
import Mathlib.LinearAlgebra.TensorProduct.Associator

/-!
# Tensor products of dg abelian groups

For dg abelian groups `M` and `N` (`DG.DGAddCommGroup`), this file puts a dg abelian group
structure on the tensor product `M ⊗[ℤ] N`:

* the grading (`DG.tensorGrading`): `(M ⊗ N)ᵏ` is the subgroup generated by the tensors
  `m ⊗ₜ n` with `m ∈ Mⁱ`, `n ∈ Nʲ` and `i + j = k`, i.e. `(M ⊗ N)ᵏ = Σ_{i+j=k} Mⁱ ⊗ Nʲ`; the
  homogeneous decomposition (`DG.tensorDecomposition`) is built from the decompositions of `M`
  and `N`;
* the differential (`DG.tensorD`): `d (m ⊗ n) = d m ⊗ n + (-1)^{|m|} m ⊗ d n`
  (`DG.d_tmul_of_mem`), defined globally as `d ⊗ 1 + ε ⊗ d` where
  `ε = DG.gradeInvolution M` is the grade involution `m ↦ (-1)^{|m|} m` (`DG.d_tmul`).

The structure is the instance `DG.instDGAddCommGroupTensorProduct`. It is put directly on
`TensorProduct ℤ M N`: the tensor product of dg abelian groups has only one natural dg
structure, and Mathlib's (unsigned) multiplication on `A ⊗[ℤ] B` for rings `A`, `B` plays no
role here. The signed (Koszul) multiplication of the tensor product of graded rings lives on
Mathlib's type synonym `GradedTensorProduct`, to which this structure transfers.

## Main definitions and results

* `DG.gradeInvolution M : M →+ M`, `m ↦ (-1)^{|m|} m` on homogeneous elements, with
  `ε ∘ ε = id` and `d ∘ ε = -ε ∘ d`.
* `DG.tensorMap f g`: the tensor product of additive maps; it has degree `0` and commutes with
  the differentials when `f` and `g` do (`DG.tensorMap_mem`, `DG.tensorMap_d`).
* `DG.tensorComm M N : DGAddEquiv (M ⊗ N) (N ⊗ M)`: the symmetry
  `m ⊗ n ↦ (-1)^{|m||n|} n ⊗ m` (`DG.tensorComm_tmul`).
* `DG.tensorAssoc M N P : DGAddEquiv ((M ⊗ N) ⊗ P) (M ⊗ (N ⊗ P))`: the associativity
  isomorphism `(m ⊗ n) ⊗ p ↦ m ⊗ (n ⊗ p)` (no signs).
* `DG.instDGModuleTensorProduct`: for a left dg `A`-module `M`, `M ⊗ N` is a left dg
  `A`-module with `a • (m ⊗ n) = (a • m) ⊗ n` (no sign; the Leibniz rule holds because `A`
  acts on the left factor).

Tensor products over a dg ring are in `DG.Module.TensorProductOver`.

## Conventions

See `docs/CONVENTIONS.md`: signs are Koszul signs `koszulSign n = Int.negOnePow n : ℤˣ`, and
exchanging homogeneous symbols of degrees `m` and `n` costs `(-1)^{mn}`.
-/

open DirectSum TensorProduct

noncomputable section

namespace DG

section GradeInvolution

variable (M : Type*) [AddCommGroup M] [DGAddCommGroup M]

/-- The grade involution `m ↦ (-1)^{|m|} • m`. -/
def gradeInvolution : M →+ M :=
  liftHomogeneous (grading (M := M)) fun n =>
    ((koszulSign n : ℤ) • (grading (M := M) n).subtype)

variable {M}

theorem gradeInvolution_of_mem {n : ℤ} {m : M} (hm : m ∈ grading n) :
    gradeInvolution M m = koszulSign n • m := by
  rw [gradeInvolution, liftHomogeneous_of_mem _ _ hm, Units.smul_def]
  rfl

theorem gradeInvolution_mem {n : ℤ} {m : M} (hm : m ∈ grading n) :
    gradeInvolution M m ∈ grading n := by
  rw [gradeInvolution_of_mem hm, Units.smul_def]
  exact zsmul_mem hm _

/-- Additive maps commute with the action of `ℤˣ`. -/
theorem map_units_zsmul {X Y : Type*} [AddCommGroup X] [AddCommGroup Y] (f : X →+ Y) (u : ℤˣ)
    (x : X) : f (u • x) = u • f x := by
  rw [Units.smul_def, Units.smul_def, map_zsmul]

@[simp]
theorem gradeInvolution_gradeInvolution (m : M) :
    gradeInvolution M (gradeInvolution M m) = m := by
  induction m using induction_on with
  | h_zero => simp
  | h_homogeneous m =>
    rw [gradeInvolution_of_mem m.2, map_units_zsmul, gradeInvolution_of_mem m.2, smul_smul,
      Int.units_mul_self, one_smul]
  | h_add m m' hm hm' => rw [map_add, map_add, hm, hm']

theorem d_gradeInvolution (m : M) : d (gradeInvolution M m) = -gradeInvolution M (d m) := by
  induction m using induction_on with
  | h_zero => simp
  | h_homogeneous m =>
    rw [gradeInvolution_of_mem m.2, gradeInvolution_of_mem (d_mem m.2), d_units_smul,
      show koszulSign (_ + 1) = -koszulSign _ from Int.negOnePow_succ _, Units.neg_smul, neg_neg]
  | h_add m m' hm hm' => simp only [map_add, hm, hm', neg_add]

end GradeInvolution

section Tensor

variable (M N : Type*) [AddCommGroup M] [DGAddCommGroup M] [AddCommGroup N] [DGAddCommGroup N]

/-- The degree-`n` part of `M ⊗ N`: the subgroup generated by the tensors `m ⊗ₜ n` with `m`
homogeneous of degree `i`, `n` homogeneous of degree `j`, and `i + j = n`. -/
def tensorGrading (k : ℤ) : AddSubgroup (M ⊗[ℤ] N) :=
  AddSubgroup.closure {x | ∃ i j, i + j = k ∧
    ∃ m ∈ grading (M := M) i, ∃ n ∈ grading (M := N) j, m ⊗ₜ n = x}

variable {M N}

theorem tmul_mem_tensorGrading {i j k : ℤ} (h : i + j = k) {m : M} (hm : m ∈ grading i) {n : N}
    (hn : n ∈ grading j) : m ⊗ₜ[ℤ] n ∈ tensorGrading M N k :=
  AddSubgroup.subset_closure ⟨i, j, h, m, hm, n, hn, rfl⟩

/-- Induction principle for `M ⊗ N` on sums of tensors of homogeneous elements. -/
theorem tensor_induction_on {P : M ⊗[ℤ] N → Prop} (x : M ⊗[ℤ] N) (zero : P 0)
    (tmul : ∀ {i j : ℤ} (m : grading (M := M) i) (n : grading (M := N) j), P ((m : M) ⊗ₜ (n : N)))
    (add : ∀ x y, P x → P y → P (x + y)) : P x := by
  induction x using TensorProduct.inductionOn with
  | tmul m n =>
    induction m using induction_on with
    | h_zero => simpa using zero
    | h_homogeneous m =>
      induction n using induction_on with
      | h_zero => simpa using zero
      | h_homogeneous n => exact tmul m n
      | h_add n n' hn hn' => rw [tmul_add]; exact add _ _ hn hn'
    | h_add m m' hm hm' => rw [add_tmul]; exact add _ _ hm hm'
  | add x y hx hy => exact add x y hx hy

/-- Two additive maps out of `M ⊗ N` agreeing on tensors of homogeneous elements are equal. -/
theorem tensor_addHom_ext {P : Type*} [AddCommGroup P] {f g : M ⊗[ℤ] N →+ P}
    (h : ∀ {i j : ℤ} (m : grading (M := M) i) (n : grading (M := N) j),
      f ((m : M) ⊗ₜ (n : N)) = g ((m : M) ⊗ₜ (n : N))) : f = g :=
  AddMonoidHom.ext fun x => tensor_induction_on (P := fun x => f x = g x) x (by simp) h
    (fun x y (hx : f x = g x) (hy : f y = g y) => by
      show f (x + y) = g (x + y); rw [map_add, map_add, hx, hy])

variable (M N) in
/-- The differential `d (m ⊗ n) = d m ⊗ n + (-1)^{|m|} m ⊗ d n` of `M ⊗ N`, written as
`d ⊗ 1 + ε ⊗ d` with `ε` the grade involution of `M`. -/
def tensorD : M ⊗[ℤ] N →+ M ⊗[ℤ] N :=
  (TensorProduct.map (d : M →+ M).toIntLinearMap LinearMap.id +
    TensorProduct.map (gradeInvolution M).toIntLinearMap (d : N →+ N).toIntLinearMap).toAddMonoidHom

theorem tensorD_tmul (m : M) (n : N) :
    tensorD M N (m ⊗ₜ n) = d m ⊗ₜ n + gradeInvolution M m ⊗ₜ d n := rfl

theorem tensorD_tmul_of_mem {i : ℤ} {m : M} (hm : m ∈ grading i) (n : N) :
    tensorD M N (m ⊗ₜ n) = d m ⊗ₜ n + koszulSign i • (m ⊗ₜ d n) := by
  rw [tensorD_tmul, gradeInvolution_of_mem hm, Units.smul_def, Units.smul_def, smul_tmul']

theorem tensorD_tensorD (x : M ⊗[ℤ] N) : tensorD M N (tensorD M N x) = 0 := by
  induction x using TensorProduct.inductionOn with
  | tmul m n =>
    rw [tensorD_tmul, map_add, tensorD_tmul, tensorD_tmul, d_d, zero_tmul, zero_add, d_d,
      tmul_zero, d_gradeInvolution, neg_tmul, add_zero, add_neg_cancel]
  | add x y hx hy => rw [map_add, map_add, hx, hy, add_zero]

theorem tensorD_mem {k : ℤ} {x : M ⊗[ℤ] N} (hx : x ∈ tensorGrading M N k) :
    tensorD M N x ∈ tensorGrading M N (k + 1) := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨i, j, rfl, m, hm, n, hn, rfl⟩ := hx
    rw [tensorD_tmul_of_mem hm]
    refine add_mem (tmul_mem_tensorGrading (by ring) (d_mem hm) hn) ?_
    rw [Units.smul_def]
    exact zsmul_mem (tmul_mem_tensorGrading (by ring) hm (d_mem hn)) _
  | zero => rw [map_zero]; exact zero_mem _
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | neg x _ hx => rw [map_neg]; exact neg_mem hx

/-- The bi-additive extension of a family of bi-additive maps on homogeneous components. -/
def liftHomogeneous₂ {P : Type*} [AddCommGroup P]
    (φ : ∀ i j, grading (M := M) i →+ grading (M := N) j →+ P) : M →+ N →+ P :=
  liftHomogeneous (grading (M := M)) fun i =>
    (liftHomogeneousEquiv (grading (M := N))).toAddMonoidHom.comp (AddMonoidHom.pi (φ i))

theorem liftHomogeneous₂_of_mem {P : Type*} [AddCommGroup P]
    (φ : ∀ i j, grading (M := M) i →+ grading (M := N) j →+ P) {i j : ℤ} {m : M}
    (hm : m ∈ grading i) {n : N} (hn : n ∈ grading j) :
    liftHomogeneous₂ φ m n = φ i j ⟨m, hm⟩ ⟨n, hn⟩ := by
  rw [liftHomogeneous₂, liftHomogeneous_of_mem _ _ hm]
  exact liftHomogeneous_of_mem _ _ hn

/-- The additive map `M ⊗ N →+ P` defined on tensors of homogeneous elements. -/
def tensorLiftHomogeneous {P : Type*} [AddCommGroup P]
    (φ : ∀ i j, grading (M := M) i →+ grading (M := N) j →+ P) : M ⊗[ℤ] N →+ P :=
  TensorProduct.liftAddHom (liftHomogeneous₂ φ) fun r m n => by
    rw [map_zsmul, map_zsmul (liftHomogeneous₂ φ m)]; rfl

theorem tensorLiftHomogeneous_tmul {P : Type*} [AddCommGroup P]
    (φ : ∀ i j, grading (M := M) i →+ grading (M := N) j →+ P) {i j : ℤ} {m : M}
    (hm : m ∈ grading i) {n : N} (hn : n ∈ grading j) :
    tensorLiftHomogeneous φ (m ⊗ₜ n) = φ i j ⟨m, hm⟩ ⟨n, hn⟩ :=
  liftHomogeneous₂_of_mem φ hm hn

variable (M N) in
/-- The decomposition of `M ⊗ N` into total degrees, on homogeneous tensors. -/
def tensorDecomposeAux (i j : ℤ) :
    grading (M := M) i →+ grading (M := N) j →+ ⨁ k, tensorGrading M N k :=
  AddMonoidHom.mk' (fun m => AddMonoidHom.mk'
    (fun n => DirectSum.of (fun k => tensorGrading M N k) (i + j)
      ⟨(m : M) ⊗ₜ (n : N), tmul_mem_tensorGrading rfl m.2 n.2⟩)
    (fun n n' => by
      rw [← map_add]; simp [tmul_add]))
    (fun m m' => by
      ext n : 1
      simp only [AddMonoidHom.mk'_apply, AddMonoidHom.add_apply]
      rw [← map_add]; congr 1; ext; simp [add_tmul])

variable (M N) in
/-- The decomposition of `M ⊗ N` into total degrees. -/
def tensorDecompose : M ⊗[ℤ] N →+ ⨁ k, tensorGrading M N k :=
  tensorLiftHomogeneous (tensorDecomposeAux M N)

theorem tensorDecompose_tmul {i j k : ℤ} (h : i + j = k) {m : M} (hm : m ∈ grading i) {n : N}
    (hn : n ∈ grading j) :
    tensorDecompose M N (m ⊗ₜ n) =
      DirectSum.of (fun k => tensorGrading M N k) k ⟨m ⊗ₜ n, tmul_mem_tensorGrading h hm hn⟩ := by
  subst h
  exact tensorLiftHomogeneous_tmul _ hm hn

theorem tensorDecompose_of_mem {k : ℤ} {x : M ⊗[ℤ] N} (hx : x ∈ tensorGrading M N k) :
    tensorDecompose M N x = DirectSum.of (fun k => tensorGrading M N k) k ⟨x, hx⟩ := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨i, j, h, m, hm, n, hn, rfl⟩ := hx
    rw [tensorDecompose_tmul h hm hn]
  | zero => rw [map_zero]; exact (map_zero _).symm.trans (congrArg _ rfl)
  | add x y hx' hy' hx hy => rw [map_add, hx, hy, ← map_add]; rfl
  | neg x hx' hx => rw [map_neg, hx, ← map_neg]; rfl

/-- The decomposition of `M ⊗ N` into total degrees `(M ⊗ N)ᵏ = Σ_{i+j=k} Mⁱ ⊗ Nʲ`. -/
instance tensorDecomposition : Decomposition (tensorGrading M N) :=
  Decomposition.ofAddHom _ (tensorDecompose M N)
    (tensor_addHom_ext fun m n => by
      simp [tensorDecompose_tmul rfl m.2 n.2])
    (DirectSum.addHom_ext fun k x => by
      simp only [AddMonoidHom.coe_comp, Function.comp_apply, coeAddMonoidHom_of,
        AddMonoidHom.id_apply]
      exact tensorDecompose_of_mem x.2)

/-- The dg abelian group structure on the tensor product `M ⊗[ℤ] N` of dg abelian groups. -/
instance instDGAddCommGroupTensorProduct : DGAddCommGroup (M ⊗[ℤ] N) where
  grading := tensorGrading M N
  d := tensorD M N
  d_mem' := tensorD_mem
  d_d' := tensorD_tensorD


end Tensor

section API

variable {M N : Type*} [AddCommGroup M] [DGAddCommGroup M] [AddCommGroup N] [DGAddCommGroup N]

theorem grading_tensorProduct (k : ℤ) :
    grading (M := M ⊗[ℤ] N) k = tensorGrading M N k := rfl

theorem tmul_mem_grading {i j : ℤ} {m : M} (hm : m ∈ grading i) {n : N} (hn : n ∈ grading j) :
    m ⊗ₜ[ℤ] n ∈ grading (M := M ⊗[ℤ] N) (i + j) :=
  tmul_mem_tensorGrading rfl hm hn

/-- The differential of `M ⊗ N`: `d (m ⊗ n) = d m ⊗ n + ε m ⊗ d n`, with `ε` the grade
involution. -/
theorem d_tmul (m : M) (n : N) : d (m ⊗ₜ[ℤ] n) = d m ⊗ₜ n + gradeInvolution M m ⊗ₜ d n := rfl

/-- The differential of `M ⊗ N`: `d (m ⊗ n) = d m ⊗ n + (-1)^{|m|} m ⊗ d n`. -/
theorem d_tmul_of_mem {i : ℤ} {m : M} (hm : m ∈ grading i) (n : N) :
    d (m ⊗ₜ[ℤ] n) = d m ⊗ₜ n + koszulSign i • (m ⊗ₜ d n) :=
  tensorD_tmul_of_mem hm n

/-- An additive map out of `M ⊗ N` which maps `Mⁱ ⊗ Nʲ` into degree `i + j + s` maps
`(M ⊗ N)ᵏ` into degree `k + s`. -/
theorem map_mem_grading_of_tmul {Y : Type*} [AddCommGroup Y] [DGAddCommGroup Y]
    (f : M ⊗[ℤ] N →+ Y) (s : ℤ)
    (h : ∀ {i j : ℤ} {m : M} {n : N}, m ∈ grading i → n ∈ grading j →
      f (m ⊗ₜ n) ∈ grading (i + j + s)) {k : ℤ} {x : M ⊗[ℤ] N}
    (hx : x ∈ grading (M := M ⊗[ℤ] N) k) : f x ∈ grading (k + s) := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨i, j, rfl, m, hm, n, hn, rfl⟩ := hx
    exact h hm hn
  | zero => rw [map_zero]; exact zero_mem _
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | neg x _ hx => rw [map_neg]; exact neg_mem hx

theorem gradeInvolution_tmul (m : M) (n : N) :
    gradeInvolution (M ⊗[ℤ] N) (m ⊗ₜ n) = gradeInvolution M m ⊗ₜ gradeInvolution N n := by
  induction m using induction_on with
  | h_zero => simp
  | h_homogeneous m =>
    induction n using induction_on with
    | h_zero => simp
    | h_homogeneous n =>
      rw [gradeInvolution_of_mem (tmul_mem_grading m.2 n.2), gradeInvolution_of_mem m.2,
        gradeInvolution_of_mem n.2, koszulSign_add, Units.smul_def, Units.smul_def,
        Units.smul_def, smul_tmul_smul, Units.val_mul]
    | h_add n n' hn hn' => rw [tmul_add, map_add, hn, hn', map_add, tmul_add]
  | h_add m m' hm hm' => rw [add_tmul, map_add, hm, hm', map_add, add_tmul]

/-- An additive map of degree `0` commutes with the grade involutions. -/
theorem gradeInvolution_map {Y : Type*} [AddCommGroup Y] [DGAddCommGroup Y] (f : M →+ Y)
    (hf : ∀ {n : ℤ} {m : M}, m ∈ grading n → f m ∈ grading n) (m : M) :
    gradeInvolution Y (f m) = f (gradeInvolution M m) := by
  induction m using induction_on with
  | h_zero => simp
  | h_homogeneous m =>
    rw [gradeInvolution_of_mem (hf m.2), gradeInvolution_of_mem m.2, map_units_zsmul]
  | h_add m m' hm hm' => rw [map_add, map_add, hm, hm', map_add, map_add]

end API

/-! ### Functoriality -/

section Map

variable {M N M' N' : Type*} [AddCommGroup M] [DGAddCommGroup M] [AddCommGroup N]
  [DGAddCommGroup N] [AddCommGroup M'] [DGAddCommGroup M'] [AddCommGroup N'] [DGAddCommGroup N']

/-- The tensor product `f ⊗ g : M ⊗ N →+ M' ⊗ N'` of additive maps. -/
def tensorMap (f : M →+ M') (g : N →+ N') : M ⊗[ℤ] N →+ M' ⊗[ℤ] N' :=
  (TensorProduct.map f.toIntLinearMap g.toIntLinearMap).toAddMonoidHom

omit [DGAddCommGroup M] [DGAddCommGroup N] [DGAddCommGroup M'] [DGAddCommGroup N'] in
@[simp]
theorem tensorMap_tmul (f : M →+ M') (g : N →+ N') (m : M) (n : N) :
    tensorMap f g (m ⊗ₜ n) = f m ⊗ₜ g n := rfl

/-- The tensor product of maps of degree `0` has degree `0`. -/
theorem tensorMap_mem (f : M →+ M') (g : N →+ N')
    (hf : ∀ {n : ℤ} {m : M}, m ∈ grading n → f m ∈ grading n)
    (hg : ∀ {n : ℤ} {m : N}, m ∈ grading n → g m ∈ grading n) {k : ℤ} {x : M ⊗[ℤ] N}
    (hx : x ∈ grading (M := M ⊗[ℤ] N) k) : tensorMap f g x ∈ grading k := by
  simpa using map_mem_grading_of_tmul (tensorMap f g) 0
    (fun hm hn => by simpa using tmul_mem_grading (hf hm) (hg hn)) hx

/-- The tensor product of chain maps of degree `0` is a chain map. -/
theorem tensorMap_d (f : M →+ M') (g : N →+ N')
    (hf : ∀ {n : ℤ} {m : M}, m ∈ grading n → f m ∈ grading n)
    (hfd : ∀ m, f (d m) = d (f m)) (hgd : ∀ n, g (d n) = d (g n)) (x : M ⊗[ℤ] N) :
    tensorMap f g (d x) = d (tensorMap f g x) := by
  induction x using TensorProduct.inductionOn with
  | tmul m n =>
    rw [d_tmul, map_add, tensorMap_tmul, tensorMap_tmul, tensorMap_tmul, d_tmul, hfd, hgd,
      gradeInvolution_map f hf]
  | add x y hx hy => rw [d_add, map_add, hx, hy, map_add, d_add]

end Map

/-! ### Symmetry and associativity -/

section Symmetry

variable (M N : Type*) [AddCommGroup M] [DGAddCommGroup M] [AddCommGroup N] [DGAddCommGroup N]

/-- The bi-additive map `(m, n) ↦ m ⊗ n`. -/
def tmulAddHom : M →+ N →+ M ⊗[ℤ] N :=
  AddMonoidHom.mk' (fun m => (TensorProduct.mk ℤ M N m).toAddMonoidHom)
    (fun m m' => by ext n; simp)

omit [DGAddCommGroup M] [DGAddCommGroup N] in
@[simp]
theorem tmulAddHom_apply (m : M) (n : N) : tmulAddHom M N m n = m ⊗ₜ n := rfl

/-- The signed symmetry `m ⊗ n ↦ (-1)^{|m||n|} n ⊗ m` on tensors of homogeneous elements. -/
def tensorCommHom : M ⊗[ℤ] N →+ N ⊗[ℤ] M :=
  tensorLiftHomogeneous fun i j =>
    (((koszulSign (i * j) : ℤ) • (tmulAddHom N M).flip).compl₂ (grading (M := N) j).subtype).comp
      (grading (M := M) i).subtype

variable {M N}

theorem tensorCommHom_tmul {i j : ℤ} {m : M} (hm : m ∈ grading i) {n : N}
    (hn : n ∈ grading j) : tensorCommHom M N (m ⊗ₜ n) = koszulSign (i * j) • (n ⊗ₜ m) := by
  rw [tensorCommHom, tensorLiftHomogeneous_tmul _ hm hn, Units.smul_def]
  rfl

theorem tensorCommHom_tensorCommHom (x : M ⊗[ℤ] N) :
    tensorCommHom N M (tensorCommHom M N x) = x := by
  induction x using tensor_induction_on with
  | zero => simp
  | tmul m n =>
    rename_i i j
    rw [tensorCommHom_tmul m.2 n.2, map_units_zsmul, tensorCommHom_tmul n.2 m.2, smul_smul,
      mul_comm j i, Int.units_mul_self, one_smul]
  | add x y hx hy => rw [map_add, map_add, hx, hy]

theorem tensorCommHom_mem {k : ℤ} {x : M ⊗[ℤ] N} (hx : x ∈ grading (M := M ⊗[ℤ] N) k) :
    tensorCommHom M N x ∈ grading k := by
  simpa using map_mem_grading_of_tmul (tensorCommHom M N) 0 (fun {i j} _ _ hm hn => by
    rw [tensorCommHom_tmul hm hn, Units.smul_def, add_zero, add_comm]
    exact zsmul_mem (tmul_mem_grading hn hm) _) hx

theorem tensorCommHom_d (x : M ⊗[ℤ] N) :
    tensorCommHom M N (d x) = d (tensorCommHom M N x) := by
  induction x using tensor_induction_on with
  | zero => simp
  | tmul m n =>
    rename_i i j
    rw [d_tmul_of_mem m.2, map_add, map_units_zsmul, tensorCommHom_tmul (d_mem m.2) n.2,
      tensorCommHom_tmul m.2 (d_mem n.2), tensorCommHom_tmul m.2 n.2, d_units_smul,
      d_tmul_of_mem n.2, smul_add, smul_smul, smul_smul, add_comm]
    congr 1
    · rw [← koszulSign_add]
      congr 1
      rw [koszulSign, koszulSign, Int.negOnePow_eq_iff]
      exact ⟨i, by ring⟩
    · rw [← koszulSign_add]
      congr 1
      rw [koszulSign, koszulSign, Int.negOnePow_eq_iff]
      exact ⟨0, by ring⟩
  | add x y hx hy => rw [d_add, map_add, hx, hy, map_add, d_add]

variable (M N)

/-- The symmetry isomorphism `M ⊗ N ≅ N ⊗ M`, `m ⊗ n ↦ (-1)^{|m||n|} n ⊗ m`. -/
def tensorComm : DGAddEquiv (M ⊗[ℤ] N) (N ⊗[ℤ] M) :=
  DGAddEquiv.ofAddMonoidHom (tensorCommHom M N) (tensorCommHom N M) tensorCommHom_tensorCommHom
    tensorCommHom_tensorCommHom tensorCommHom_mem tensorCommHom_d

variable {M N}

theorem tensorComm_tmul {i j : ℤ} {m : M} (hm : m ∈ grading i) {n : N} (hn : n ∈ grading j) :
    tensorComm M N (m ⊗ₜ n) = koszulSign (i * j) • (n ⊗ₜ m) :=
  tensorCommHom_tmul hm hn

@[simp]
theorem tensorComm_symm : (tensorComm M N).symm = tensorComm N M := rfl

end Symmetry

section Associativity

variable (M N P : Type*) [AddCommGroup M] [DGAddCommGroup M] [AddCommGroup N] [DGAddCommGroup N]
  [AddCommGroup P] [DGAddCommGroup P]

set_option backward.isDefEq.respectTransparency false in
theorem assoc_mem {k : ℤ} {x : (M ⊗[ℤ] N) ⊗[ℤ] P}
    (hx : x ∈ grading (M := (M ⊗[ℤ] N) ⊗[ℤ] P) k) :
    TensorProduct.assoc ℤ M N P x ∈ grading k := by
  simpa using map_mem_grading_of_tmul (TensorProduct.assoc ℤ M N P).toLinearMap.toAddMonoidHom
    0 (fun {a c y p} hy hp => by
      simpa using map_mem_grading_of_tmul
        ((TensorProduct.assoc ℤ M N P).toLinearMap.toAddMonoidHom.comp
          ((TensorProduct.mk ℤ (M ⊗[ℤ] N) P).flip p).toAddMonoidHom) c
        (fun {i j m n} hm hn => by
          simpa [add_assoc] using tmul_mem_grading hm (tmul_mem_grading hn hp)) hy) hx

set_option backward.isDefEq.respectTransparency false in
theorem assoc_d (x : (M ⊗[ℤ] N) ⊗[ℤ] P) :
    TensorProduct.assoc ℤ M N P (d x) = d (TensorProduct.assoc ℤ M N P x) := by
  induction x using TensorProduct.inductionOn with
  | tmul y p =>
    induction y using TensorProduct.inductionOn with
    | tmul m n =>
      simp [d_tmul, gradeInvolution_tmul, add_tmul, tmul_add, add_assoc]
    | add y y' hy hy' => rw [add_tmul, d_add, map_add, hy, hy', map_add, d_add]
  | add x y hx hy => rw [d_add, map_add, hx, hy, map_add, d_add]

/-- The associativity isomorphism `(M ⊗ N) ⊗ P ≅ M ⊗ (N ⊗ P)` (no signs). -/
def tensorAssoc : DGAddEquiv ((M ⊗[ℤ] N) ⊗[ℤ] P) (M ⊗[ℤ] (N ⊗[ℤ] P)) where
  __ := (TensorProduct.assoc ℤ M N P).toAddEquiv
  map_mem' := assoc_mem M N P
  map_d' := assoc_d M N P

variable {M N P}

@[simp]
theorem tensorAssoc_tmul (m : M) (n : N) (p : P) :
    tensorAssoc M N P ((m ⊗ₜ n) ⊗ₜ p) = m ⊗ₜ (n ⊗ₜ p) := rfl

end Associativity

/-! ### Tensor products with a left dg module -/

section Module

variable {A M N : Type*} [Ring A] [DGAddCommGroup A] [AddCommGroup M] [DGAddCommGroup M]
  [Module A M] [DGModule A M] [AddCommGroup N] [DGAddCommGroup N]

/-- For a left dg `A`-module `M` and a dg abelian group `N`, `M ⊗ N` is a left dg `A`-module,
with `A` acting on the left factor, `a • (m ⊗ n) = (a • m) ⊗ n` (no sign). -/
instance instDGModuleTensorProduct : DGModule A (M ⊗[ℤ] N) where
  smul_mem {i k a x} ha hx := by
    show a • x ∈ grading (i + k)
    rw [add_comm]
    exact map_mem_grading_of_tmul ((DistribSMul.toAddMonoidHom _ a)) i
      (fun {p q m n} hm hn => by
        rw [DistribSMul.toAddMonoidHom_apply, smul_tmul', add_right_comm, add_comm p i]
        exact tmul_mem_grading (smul_mem_grading ha hm) hn) hx
  d_smul' {k a} ha x := by
    induction x using tensor_induction_on with
    | zero => simp
    | tmul m n =>
      rename_i i j
      rw [smul_tmul', d_tmul_of_mem (smul_mem_grading ha m.2), d_smul ha, add_tmul,
        d_tmul_of_mem m.2, smul_add, smul_add, smul_tmul', smul_tmul', koszulSign_add, mul_smul,
        add_assoc]
      simp only [Units.smul_def, smul_tmul', smul_comm a ((koszulSign i : ℤ))]
    | add x y hx hy => rw [smul_add, d_add, hx, hy, d_add, smul_add, smul_add, smul_add]; abel

end Module

end DG
end
