import DG.Module.TensorProduct
import DG.Module.Quotient

/-!
# Tensor products over a dg ring

For a dg ring `A`, a right dg `A`-module `M` (`DG.DGRightModule A M`, the right action being
`Module Aᵐᵒᵖ M`) and a left dg `A`-module `N`, this file constructs the tensor product
`M ⊗_A N` (`DG.TensorProductOver A M N`) as a dg abelian group.

Mathlib's `TensorProduct` requires a commutative ring and has no balanced tensor product over a
noncommutative ring, so `M ⊗_A N` is defined as the quotient of `M ⊗[ℤ] N` by the subgroup
`DG.balancedRel A M N` generated by the balancing relations `(m • a) ⊗ n - m ⊗ (a • n)`
(written `(op a • m) ⊗ₜ n - m ⊗ₜ (a • n)`). This subgroup is generated by the relations with
`a`, `m`, `n` homogeneous (`DG.balancedRel_eq_closure_gen`), hence homogeneous, and it is stable
under the differential of `M ⊗[ℤ] N` (`DG.d_balancedRel_gen`): for `a ∈ Aⁱ`, `m ∈ Mʲ`,
`d ((m a) ⊗ n - m ⊗ (a n)) = ((d m) a ⊗ n - d m ⊗ a n) + (-1)^j (m (d a) ⊗ n - m ⊗ (d a) n)
  + (-1)^{j+i} ((m a) ⊗ d n - m ⊗ a (d n))`,
using the right Leibniz rule `d (m a) = d m a + (-1)^{|m|} m d a` and the left Leibniz rule
`d (a n) = d a n + (-1)^{|a|} a d n`. The quotient is therefore a dg abelian group
(`DG.DGAddCommGroup.quotient`), with the differential
`d (m ⊗ n) = d m ⊗ n + (-1)^{|m|} m ⊗ d n` (`DG.TensorProductOver.d_tmul_of_mem`).

## Main definitions and results

* `DG.TensorProductOver A M N`, with `DG.TensorProductOver.tmul A m n` the class of `m ⊗ n`,
  the quotient map `DG.TensorProductOver.mk`, and the balancing relation
  `DG.TensorProductOver.op_smul_tmul : tmul A (op a • m) n = tmul A m (a • n)`.
* `DG.TensorProductOver.lift`: the additive map induced by an `A`-balanced bi-additive map,
  with `lift_tmul`, uniqueness (`lift_unique`, `addHom_ext`), and compatibility with gradings
  and differentials (`lift_mem`, `lift_d`).
* `DG.TensorProductOver.map f g` for a right `A`-linear `f` and a left `A`-linear `g`
  (functoriality, `map_id`, `map_comp`); it is a chain map of degree `0` when `f` and `g` are
  (`map_mem`, `map_d`).
* `DG.TensorProductOver.instDGModule`: for a dg `(B, A)`-bimodule `M`, `M ⊗_A N` is a left dg
  `B`-module, `b • (m ⊗ n) = (b • m) ⊗ n`.
* The unit isomorphism `A ⊗_A N ≅ N`, `a ⊗ n ↦ a • n`, as mutually inverse morphisms of dg
  `A`-modules `DG.TensorProductOver.lid` and `DG.TensorProductOver.lidInv`, and as
  `DG.TensorProductOver.lidLinearEquiv` and `DG.TensorProductOver.lidEquiv`.
* The right unit isomorphism `M ⊗_A A ≅ M`, `m ⊗ a ↦ m • a` (`DG.TensorProductOver.rid`), which
  is right `A`-linear (`DG.TensorProductOver.rid_op_smul`).
* For a dg `(A, B)`-bimodule `N`, the right dg `B`-module structure on `M ⊗_A N` through `N`,
  `(m ⊗ n) • b = m ⊗ (n • b)`. These instances are scoped
  (`open scoped DG.TensorProductOver.RightAction`): when `M` also carries a left action of `Bᵐᵒᵖ`
  commuting with its right `A`-action, the action through the left factor is a second,
  different `Bᵐᵒᵖ`-module structure on `M ⊗_A N`.
* Associativity: for a right dg `A`-module `M`, a dg `(A, B)`-bimodule `N` and a left dg
  `B`-module `P`, the isomorphism of dg abelian groups
  `DG.TensorProductOver.assocEquiv : (M ⊗_A N) ⊗_B P ≅ M ⊗_A (N ⊗_B P)`,
  `(m ⊗ n) ⊗ p ↦ m ⊗ (n ⊗ p)` (no signs).

## Implementation notes

For a dg `(B, A)`-bimodule `M`, the action of `B` on `M ⊗_A N` is defined by `Quotient.map'`, so
that for `B = ℤ` it agrees, with instance transparency, with the `ℤ`-module structure of the
additive group `M ⊗_A N`.
-/

open DirectSum TensorProduct MulOpposite

noncomputable section

namespace DG

section Relations

variable (A M N : Type*) [Ring A] [AddCommGroup M] [Module Aᵐᵒᵖ M] [AddCommGroup N] [Module A N]

/-- The balancing relations: the subgroup of `M ⊗[ℤ] N` generated by the elements
`(m • a) ⊗ n - m ⊗ (a • n)`, where `m • a` is `op a • m`. -/
def balancedRel : AddSubgroup (M ⊗[ℤ] N) :=
  AddSubgroup.closure {x | ∃ (a : A) (m : M) (n : N), (op a • m) ⊗ₜ n - m ⊗ₜ (a • n) = x}

variable {A M N}

theorem balancedRel_mem (a : A) (m : M) (n : N) :
    (op a • m) ⊗ₜ[ℤ] n - m ⊗ₜ (a • n) ∈ balancedRel A M N :=
  AddSubgroup.subset_closure ⟨a, m, n, rfl⟩

end Relations

section Homogeneous

variable {A M N : Type*} [Ring A] [DGAddCommGroup A] [AddCommGroup M] [DGAddCommGroup M]
  [Module Aᵐᵒᵖ M] [DGRightModule A M] [AddCommGroup N] [DGAddCommGroup N] [Module A N]
  [DGModule A N]

variable (A M N) in
/-- The homogeneous balancing relations, for `a`, `m`, `n` homogeneous. -/
def balancedRelGen : Set (M ⊗[ℤ] N) :=
  {x | ∃ (i j k : ℤ) (a : A) (m : M) (n : N), a ∈ grading i ∧ m ∈ grading j ∧ n ∈ grading k ∧
    (op a • m) ⊗ₜ n - m ⊗ₜ (a • n) = x}

omit [DGRightModule A M] [DGModule A N] in
theorem balancedRel_eq_closure_gen :
    balancedRel A M N = AddSubgroup.closure (balancedRelGen A M N) := by
  refine le_antisymm (AddSubgroup.closure_le _ |>.mpr ?_)
    (AddSubgroup.closure_mono fun x ⟨_, _, _, a, m, n, _, _, _, hx⟩ => ⟨a, m, n, hx⟩)
  rintro _ ⟨a, m, n, rfl⟩
  set S := AddSubgroup.closure (balancedRelGen A M N)
  induction a using induction_on with
  | h_zero => simpa using zero_mem S
  | h_add a a' ha ha' =>
    have : (op (a + a') • m) ⊗ₜ[ℤ] n - m ⊗ₜ ((a + a') • n) =
        ((op a • m) ⊗ₜ[ℤ] n - m ⊗ₜ (a • n)) + ((op a' • m) ⊗ₜ[ℤ] n - m ⊗ₜ (a' • n)) := by
      rw [op_add, add_smul, add_smul, add_tmul, tmul_add]; abel
    rw [this]; exact add_mem ha ha'
  | h_homogeneous a =>
    induction m using induction_on with
    | h_zero => simpa using zero_mem S
    | h_add m m' hm hm' =>
      have : (op (a : A) • (m + m')) ⊗ₜ[ℤ] n - (m + m') ⊗ₜ ((a : A) • n) =
          ((op (a : A) • m) ⊗ₜ[ℤ] n - m ⊗ₜ ((a : A) • n)) +
            ((op (a : A) • m') ⊗ₜ[ℤ] n - m' ⊗ₜ ((a : A) • n)) := by
        rw [smul_add, add_tmul, add_tmul]; abel
      rw [this]; exact add_mem hm hm'
    | h_homogeneous m =>
      induction n using induction_on with
      | h_zero => simpa using zero_mem S
      | h_add n n' hn hn' =>
        have : (op (a : A) • (m : M)) ⊗ₜ[ℤ] (n + n') - (m : M) ⊗ₜ ((a : A) • (n + n')) =
            ((op (a : A) • (m : M)) ⊗ₜ[ℤ] n - (m : M) ⊗ₜ ((a : A) • n)) +
              ((op (a : A) • (m : M)) ⊗ₜ[ℤ] n' - (m : M) ⊗ₜ ((a : A) • n')) := by
          rw [smul_add, tmul_add, tmul_add]; abel
        rw [this]; exact add_mem hn hn'
      | h_homogeneous n =>
        exact AddSubgroup.subset_closure ⟨_, _, _, a, m, n, a.2, m.2, n.2, rfl⟩

/-- The differential of a balancing relation is a combination of balancing relations:
`d ((m a) ⊗ n - m ⊗ (a n)) = ((d m) a ⊗ n - d m ⊗ a n) + (-1)^{|m|} (m (d a) ⊗ n - m ⊗ (d a) n)
+ (-1)^{|m| + |a|} ((m a) ⊗ d n - m ⊗ a (d n))`. -/
theorem d_balancedRel_gen {i j : ℤ} {a : A} (ha : a ∈ grading i) {m : M} (hm : m ∈ grading j)
    (n : N) :
    d ((op a • m) ⊗ₜ[ℤ] n - m ⊗ₜ (a • n)) =
      ((op a • d m) ⊗ₜ[ℤ] n - d m ⊗ₜ (a • n)) +
        koszulSign j • ((op (d a) • m) ⊗ₜ[ℤ] n - m ⊗ₜ (d a • n)) +
        koszulSign (j + i) • ((op a • m) ⊗ₜ[ℤ] d n - m ⊗ₜ (a • d n)) := by
  rw [d_sub, d_tmul_of_mem (op_smul_mem_grading ha hm), d_tmul_of_mem hm, d_op_smul hm,
    d_smul ha, add_tmul, tmul_add, smul_sub, smul_sub, koszulSign_add, mul_smul]
  simp only [Units.smul_def, smul_tmul', tmul_smul, smul_add, Units.val_mul, mul_smul]
  abel

instance isDGAddSubgroup_balancedRel : IsDGAddSubgroup (balancedRel A M N) := by
  rw [balancedRel_eq_closure_gen]
  refine IsDGAddSubgroup.closure ?_ ?_
  · rintro _ ⟨i, j, k, a, m, n, ha, hm, hn, rfl⟩
    exact ⟨j + i + k, sub_mem (tmul_mem_grading (op_smul_mem_grading ha hm) hn)
      (tmul_mem_tensorGrading (by ring) hm (smul_mem_grading ha hn))⟩
  · rintro _ ⟨i, j, k, a, m, n, ha, hm, hn, rfl⟩
    rw [d_balancedRel_gen ha hm, ← balancedRel_eq_closure_gen]
    refine add_mem (add_mem (balancedRel_mem _ _ _) ?_) ?_ <;>
      (rw [Units.smul_def]; exact zsmul_mem (balancedRel_mem _ _ _) _)

end Homogeneous

section Def

variable (A M N : Type*) [Ring A] [AddCommGroup M] [Module Aᵐᵒᵖ M] [AddCommGroup N] [Module A N]

/-- The tensor product `M ⊗_A N` of a right `A`-module `M` and a left `A`-module `N`: the
quotient of `M ⊗[ℤ] N` by the balancing relations `(m • a) ⊗ n = m ⊗ (a • n)`. -/
def TensorProductOver : Type _ := (M ⊗[ℤ] N) ⧸ balancedRel A M N

instance : AddCommGroup (TensorProductOver A M N) :=
  inferInstanceAs (AddCommGroup ((M ⊗[ℤ] N) ⧸ balancedRel A M N))

namespace TensorProductOver

/-- The quotient map `M ⊗[ℤ] N →+ M ⊗_A N`. -/
def mk : M ⊗[ℤ] N →+ TensorProductOver A M N := QuotientAddGroup.mk' _

variable {M N}

/-- The class `m ⊗ n ∈ M ⊗_A N` of the tensor `m ⊗ₜ n`. -/
def tmul (m : M) (n : N) : TensorProductOver A M N := mk A M N (m ⊗ₜ n)

variable {A}

theorem mk_tmul (m : M) (n : N) : mk A M N (m ⊗ₜ n) = tmul A m n := rfl

theorem mk_surjective : Function.Surjective (mk A M N) :=
  QuotientAddGroup.mk'_surjective _

theorem mk_eq_zero_iff {x : M ⊗[ℤ] N} : mk A M N x = 0 ↔ x ∈ balancedRel A M N :=
  QuotientAddGroup.eq_zero_iff x

/-- The balancing relation `(m • a) ⊗ n = m ⊗ (a • n)`. -/
theorem op_smul_tmul (a : A) (m : M) (n : N) : tmul A (op a • m) n = tmul A m (a • n) := by
  rw [tmul, tmul, ← sub_eq_zero, ← map_sub, mk_eq_zero_iff]
  exact balancedRel_mem a m n

theorem tmul_add (m : M) (n n' : N) : tmul A m (n + n') = tmul A m n + tmul A m n' := by
  rw [tmul, TensorProduct.tmul_add, map_add]; rfl

theorem add_tmul (m m' : M) (n : N) : tmul A (m + m') n = tmul A m n + tmul A m' n := by
  rw [tmul, TensorProduct.add_tmul, map_add]; rfl

@[simp]
theorem tmul_zero (m : M) : tmul A m (0 : N) = 0 := by
  rw [tmul, TensorProduct.tmul_zero, map_zero]

@[simp]
theorem zero_tmul (n : N) : tmul A (0 : M) n = 0 := by
  rw [tmul, TensorProduct.zero_tmul, map_zero]

theorem tmul_neg (m : M) (n : N) : tmul A m (-n) = -tmul A m n := by
  rw [tmul, TensorProduct.tmul_neg, map_neg]; rfl

theorem neg_tmul (m : M) (n : N) : tmul A (-m) n = -tmul A m n := by
  rw [tmul, TensorProduct.neg_tmul, map_neg]; rfl

theorem tmul_zsmul (k : ℤ) (m : M) (n : N) : tmul A m (k • n) = k • tmul A m n := by
  rw [tmul, TensorProduct.tmul_smul, map_zsmul]; rfl

theorem zsmul_tmul (k : ℤ) (m : M) (n : N) : tmul A (k • m) n = k • tmul A m n := by
  rw [tmul, ← TensorProduct.smul_tmul', map_zsmul]; rfl

theorem tmul_units_smul (u : ℤˣ) (m : M) (n : N) : tmul A m (u • n) = u • tmul A m n := by
  rw [Units.smul_def, Units.smul_def, tmul_zsmul]

theorem units_smul_tmul (u : ℤˣ) (m : M) (n : N) : tmul A (u • m) n = u • tmul A m n := by
  rw [Units.smul_def, Units.smul_def, zsmul_tmul]

/-- Induction principle for `M ⊗_A N`. -/
@[elab_as_elim]
theorem induction_on {P : TensorProductOver A M N → Prop} (x : TensorProductOver A M N)
    (zero : P 0) (tmul : ∀ m n, P (tmul A m n)) (add : ∀ x y, P x → P y → P (x + y)) : P x := by
  obtain ⟨x, rfl⟩ := mk_surjective x
  induction x using TensorProduct.induction_on with
  | zero => simpa using zero
  | tmul m n => exact tmul m n
  | add x y hx hy => rw [map_add]; exact add _ _ hx hy

/-- Two additive maps out of `M ⊗_A N` agreeing on the tensors `m ⊗ n` are equal. -/
@[ext]
theorem addHom_ext {P : Type*} [AddCommGroup P] {f g : TensorProductOver A M N →+ P}
    (h : ∀ m n, f (tmul A m n) = g (tmul A m n)) : f = g :=
  AddMonoidHom.ext fun x => induction_on (P := fun x => f x = g x) x (by simp) h
    (fun x y (hx : f x = g x) (hy : f y = g y) => by
      show f (x + y) = g (x + y); rw [map_add, map_add, hx, hy])

variable (A M N) in
/-- The bi-additive map `(m, n) ↦ m ⊗ n` into `M ⊗_A N`. -/
def tmulAddHom : M →+ N →+ TensorProductOver A M N :=
  AddMonoidHom.compHom (mk A M N) |>.comp (DG.tmulAddHom M N)

@[simp]
theorem tmulAddHom_apply (m : M) (n : N) : tmulAddHom A M N m n = tmul A m n := rfl

section Lift

variable {P : Type*} [AddCommGroup P]

/-- The additive map `M ⊗_A N →+ P` induced by an `A`-balanced bi-additive map
`f : M →+ N →+ P`, i.e. one with `f (m • a) n = f m (a • n)`. -/
def lift (f : M →+ N →+ P) (hf : ∀ (a : A) (m : M) (n : N), f (op a • m) n = f m (a • n)) :
    TensorProductOver A M N →+ P :=
  QuotientAddGroup.lift _
    (TensorProduct.liftAddHom f fun r m n => by
      rw [map_zsmul, map_zsmul (f m)]; rfl)
    ((AddSubgroup.closure_le _).mpr fun _ ⟨a, m, n, hx⟩ => by
      rw [← hx, SetLike.mem_coe, AddMonoidHom.mem_ker, map_sub, liftAddHom_tmul, liftAddHom_tmul,
        hf, sub_self])

@[simp]
theorem lift_tmul (f : M →+ N →+ P)
    (hf : ∀ (a : A) (m : M) (n : N), f (op a • m) n = f m (a • n)) (m : M) (n : N) :
    lift f hf (tmul A m n) = f m n := rfl

theorem lift_mk_tmul (f : M →+ N →+ P)
    (hf : ∀ (a : A) (m : M) (n : N), f (op a • m) n = f m (a • n)) (m : M) (n : N) :
    lift f hf (mk A M N (m ⊗ₜ n)) = f m n := rfl

/-- The universal property: `lift` identifies additive maps out of `M ⊗_A N` with
`A`-balanced bi-additive maps. -/
theorem lift_unique (f : M →+ N →+ P)
    (hf : ∀ (a : A) (m : M) (n : N), f (op a • m) n = f m (a • n))
    (g : TensorProductOver A M N →+ P) (hg : ∀ m n, g (tmul A m n) = f m n) :
    g = lift f hf :=
  addHom_ext fun m n => by rw [hg, lift_tmul]

end Lift

section Map

variable {M' N' M'' N'' : Type*} [AddCommGroup M'] [Module Aᵐᵒᵖ M'] [AddCommGroup N'] [Module A N']
  [AddCommGroup M''] [Module Aᵐᵒᵖ M''] [AddCommGroup N''] [Module A N'']

/-- The map `f ⊗ g : M ⊗_A N →+ M' ⊗_A N'` induced by a right `A`-linear map `f` and a left
`A`-linear map `g`. -/
def map (f : M →ₗ[Aᵐᵒᵖ] M') (g : N →ₗ[A] N') :
    TensorProductOver A M N →+ TensorProductOver A M' N' :=
  lift (((tmulAddHom A M' N').compl₂ g.toAddMonoidHom).comp f.toAddMonoidHom)
    fun a m n => by
      simp only [AddMonoidHom.coe_comp, Function.comp_apply, AddMonoidHom.compl₂_apply,
        LinearMap.toAddMonoidHom_coe, tmulAddHom_apply, map_smul, op_smul_tmul]

@[simp]
theorem map_tmul (f : M →ₗ[Aᵐᵒᵖ] M') (g : N →ₗ[A] N') (m : M) (n : N) :
    map f g (tmul A m n) = tmul A (f m) (g n) := rfl

@[simp]
theorem map_id : map (LinearMap.id : M →ₗ[Aᵐᵒᵖ] M) (LinearMap.id : N →ₗ[A] N) =
    AddMonoidHom.id _ :=
  addHom_ext fun _ _ => rfl

theorem map_comp (f : M →ₗ[Aᵐᵒᵖ] M')
    (f' : M' →ₗ[Aᵐᵒᵖ] M'') (g : N →ₗ[A] N') (g' : N' →ₗ[A] N'') :
    map (f'.comp f) (g'.comp g) = (map f' g').comp (map f g) :=
  addHom_ext fun _ _ => rfl

end Map

/-! ### Left module structure from a bimodule -/

section Bimodule

variable {B : Type*} [Ring B] [Module B M] [SMulCommClass B Aᵐᵒᵖ M]

theorem smul_mem_balancedRel (b : B) {x : M ⊗[ℤ] N} (hx : x ∈ balancedRel A M N) :
    b • x ∈ balancedRel A M N := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨a, m, n, rfl⟩ := hx
    rw [smul_sub, smul_tmul', smul_tmul', smul_comm b (op a) m]
    exact balancedRel_mem a (b • m) n
  | one => rw [smul_zero]; exact zero_mem _
  | mul x y _ _ hx hy => rw [smul_add]; exact add_mem hx hy
  | inv x _ hx => rw [smul_neg]; exact neg_mem hx

/-- For a `(B, A)`-bimodule `M`, `B` acts on `M ⊗_A N` through `M`. -/
instance : SMul B (TensorProductOver A M N) where
  smul b := Quotient.map' (b • ·) fun x y h => QuotientAddGroup.leftRel_apply.mpr <| by
    simpa [smul_add, smul_neg] using
      smul_mem_balancedRel b (QuotientAddGroup.leftRel_apply.mp h)

theorem smul_mk (b : B) (x : M ⊗[ℤ] N) : b • mk A M N x = mk A M N (b • x) := rfl

/-- For a `(B, A)`-bimodule `M`, `M ⊗_A N` is a left `B`-module,
`b • (m ⊗ n) = (b • m) ⊗ n`. -/
instance : Module B (TensorProductOver A M N) :=
  Function.Surjective.module B (mk A M N) mk_surjective fun _ _ => rfl

theorem smul_tmul (b : B) (m : M) (n : N) : b • tmul A m n = tmul A (b • m) n := rfl

end Bimodule

end TensorProductOver

end Def

/-! ### The dg structure on `M ⊗_A N` -/

section DG

variable {A M N : Type*} [Ring A] [DGAddCommGroup A] [AddCommGroup M] [DGAddCommGroup M]
  [Module Aᵐᵒᵖ M] [DGRightModule A M] [AddCommGroup N] [DGAddCommGroup N] [Module A N]
  [DGModule A N]

/-- The tensor product `M ⊗_A N` of a right dg `A`-module and a left dg `A`-module is a dg
abelian group, with `(M ⊗_A N)ⁿ` the image of `(M ⊗ N)ⁿ` and the differential induced by
`d (m ⊗ n) = d m ⊗ n + (-1)^{|m|} m ⊗ d n`. -/
instance TensorProductOver.instDGAddCommGroup : DGAddCommGroup (TensorProductOver A M N) :=
  inferInstanceAs (DGAddCommGroup ((M ⊗[ℤ] N) ⧸ balancedRel A M N))

namespace TensorProductOver

theorem mem_grading_iff {k : ℤ} {y : TensorProductOver A M N} :
    y ∈ grading k ↔ ∃ x ∈ grading (M := M ⊗[ℤ] N) k, mk A M N x = y :=
  Iff.rfl

theorem mk_mem_grading {k : ℤ} {x : M ⊗[ℤ] N} (hx : x ∈ grading k) :
    mk A M N x ∈ grading k :=
  ⟨x, hx, rfl⟩

@[simp]
theorem d_mk (x : M ⊗[ℤ] N) : d (mk A M N x) = mk A M N (d x) := rfl

/-- The tensor of homogeneous elements of degrees `i` and `j` has degree `i + j`. -/
theorem tmul_mem_grading {i j : ℤ} {m : M} (hm : m ∈ grading i) {n : N} (hn : n ∈ grading j) :
    tmul A m n ∈ grading (i + j) :=
  mk_mem_grading (DG.tmul_mem_grading hm hn)

/-- Induction on the homogeneous elements of `M ⊗_A N` of a given degree `k`: they are generated
by the tensors `m ⊗ n` with `m ∈ Mⁱ`, `n ∈ Nʲ` and `i + j = k`. -/
theorem induction_on_mem_grading {k : ℤ} {P : TensorProductOver A M N → Prop} (zero : P 0)
    (tmul : ∀ {i j : ℤ} {m : M} {n : N}, m ∈ grading i → n ∈ grading j → i + j = k →
      P (tmul A m n))
    (add : ∀ x y, P x → P y → P (x + y)) (neg : ∀ x, P x → P (-x))
    {y : TensorProductOver A M N} (hy : y ∈ grading k) : P y := by
  obtain ⟨x, hx, rfl⟩ := hy
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨i, j, h, m, hm, n, hn, rfl⟩ := hx
    exact tmul hm hn h
  | one => simpa using zero
  | mul x y _ _ hx hy => rw [map_add]; exact add _ _ hx hy
  | inv x _ hx => rw [map_neg]; exact neg _ hx

/-- The differential of `M ⊗_A N`: `d (m ⊗ n) = d m ⊗ n + ε m ⊗ d n`, with `ε` the grade
involution of `M`. -/
theorem d_tmul (m : M) (n : N) :
    d (tmul A m n) = tmul A (d m) n + tmul A (gradeInvolution M m) (d n) := by
  rw [tmul, d_mk, DG.d_tmul, map_add]; rfl

/-- The differential of `M ⊗_A N`: `d (m ⊗ n) = d m ⊗ n + (-1)^{|m|} m ⊗ d n`. -/
theorem d_tmul_of_mem {i : ℤ} {m : M} (hm : m ∈ grading i) (n : N) :
    d (tmul A m n) = tmul A (d m) n + koszulSign i • tmul A m (d n) := by
  rw [tmul, d_mk, DG.d_tmul_of_mem hm, map_add, map_units_zsmul]; rfl

section Lift

variable {P : Type*} [AddCommGroup P] [DGAddCommGroup P]

/-- If a balanced bi-additive map sends `Mⁱ × Nʲ` to `Pⁱ⁺ʲ`, the induced map has degree `0`. -/
theorem lift_mem (f : M →+ N →+ P)
    (hf : ∀ (a : A) (m : M) (n : N), f (op a • m) n = f m (a • n))
    (hdeg : ∀ {i j : ℤ} {m : M} {n : N}, m ∈ grading i → n ∈ grading j →
      f m n ∈ grading (i + j))
    {k : ℤ} {y : TensorProductOver A M N} (hy : y ∈ grading k) : lift f hf y ∈ grading k := by
  obtain ⟨x, hx, rfl⟩ := hy
  simpa using map_mem_grading_of_tmul ((lift f hf).comp (mk A M N)) 0
    (fun hm hn => by simpa using hdeg hm hn) hx

/-- If a balanced bi-additive map sends `Mⁱ × Nʲ` to `Pⁱ⁺ʲ⁺ˢ`, the induced map has degree
`s`. -/
theorem lift_mem_add (f : M →+ N →+ P)
    (hf : ∀ (a : A) (m : M) (n : N), f (op a • m) n = f m (a • n)) (s : ℤ)
    (hdeg : ∀ {i j : ℤ} {m : M} {n : N}, m ∈ grading i → n ∈ grading j →
      f m n ∈ grading (i + j + s))
    {k : ℤ} {y : TensorProductOver A M N} (hy : y ∈ grading k) :
    lift f hf y ∈ grading (k + s) := by
  obtain ⟨x, hx, rfl⟩ := hy
  exact map_mem_grading_of_tmul ((lift f hf).comp (mk A M N)) s (fun hm hn => hdeg hm hn) hx

/-- If a balanced bi-additive map satisfies the Leibniz rule
`d (f m n) = f (d m) n + (-1)^{|m|} f m (d n)`, the induced map commutes with `d`. -/
theorem lift_d (f : M →+ N →+ P)
    (hf : ∀ (a : A) (m : M) (n : N), f (op a • m) n = f m (a • n))
    (hd : ∀ {i : ℤ} {m : M}, m ∈ grading i → ∀ n : N,
      d (f m n) = f (d m) n + koszulSign i • f m (d n))
    (y : TensorProductOver A M N) : lift f hf (d y) = d (lift f hf y) := by
  induction y using induction_on with
  | zero => simp
  | tmul m n =>
    induction m using DG.induction_on with
    | h_zero => simp
    | h_homogeneous m =>
      rw [d_tmul_of_mem m.2, map_add, map_units_zsmul, lift_tmul, lift_tmul, lift_tmul,
        hd m.2]
    | h_add m m' hm hm' =>
      rw [add_tmul, d_add, map_add, hm, hm', map_add, d_add]
  | add x y hx hy => rw [d_add, map_add, hx, hy, map_add, d_add]

end Lift

/-! ### Functoriality -/

section Map

variable {M' N' : Type*} [AddCommGroup M'] [DGAddCommGroup M'] [Module Aᵐᵒᵖ M']
  [DGRightModule A M'] [AddCommGroup N'] [DGAddCommGroup N'] [Module A N'] [DGModule A N']

/-- The tensor product of maps of degree `0` has degree `0`. -/
theorem map_mem (f : M →ₗ[Aᵐᵒᵖ] M') (g : N →ₗ[A] N')
    (hf : ∀ {n : ℤ} {m : M}, m ∈ grading n → f m ∈ grading n)
    (hg : ∀ {n : ℤ} {m : N}, m ∈ grading n → g m ∈ grading n)
    {k : ℤ} {y : TensorProductOver A M N} (hy : y ∈ grading k) : map f g y ∈ grading k :=
  lift_mem _ _ (fun hm hn => tmul_mem_grading (hf hm) (hg hn)) hy

/-- The tensor product of chain maps of degree `0` commutes with the differentials. -/
theorem map_d (f : M →ₗ[Aᵐᵒᵖ] M') (g : N →ₗ[A] N')
    (hf : ∀ {n : ℤ} {m : M}, m ∈ grading n → f m ∈ grading n)
    (hfd : ∀ m, f (d m) = d (f m)) (hgd : ∀ n, g (d n) = d (g n))
    (y : TensorProductOver A M N) : map f g (d y) = d (map f g y) :=
  lift_d _ _ (fun hm n => by
    simp only [AddMonoidHom.coe_comp, Function.comp_apply, AddMonoidHom.compl₂_apply,
      LinearMap.toAddMonoidHom_coe, tmulAddHom_apply]
    rw [d_tmul_of_mem (hf hm), hfd, hgd]) y

/-- Functoriality of `M ⊗_A N` for a morphism of dg modules in the second variable. -/
theorem map_d_of_dgModuleHom (f : M →ₗ[Aᵐᵒᵖ] M') (g : N →ᵈᵍ[A] N')
    (hf : ∀ {n : ℤ} {m : M}, m ∈ grading n → f m ∈ grading n)
    (hfd : ∀ m, f (d m) = d (f m)) (y : TensorProductOver A M N) :
    map f g.toLinearMap (d y) = d (map f g.toLinearMap y) :=
  map_d f g.toLinearMap hf hfd (fun n => g.map_d n) y

end Map

/-! ### Left dg module structure from a dg bimodule -/

section Bimodule

variable {B : Type*} [Ring B] [DGAddCommGroup B] [Module B M] [DGModule B M]
  [SMulCommClass B Aᵐᵒᵖ M]


/-- The Leibniz rule for the action of `B` on `M ⊗_A N`. -/
theorem d_smul_eq {i : ℤ} {b : B} (hb : b ∈ grading i) (y : TensorProductOver A M N) :
    d (b • y) = d b • y + koszulSign i • (b • d y) := by
  obtain ⟨x, rfl⟩ := mk_surjective y
  rw [smul_mk b, d_mk, d_mk, d_smul (M := M ⊗[ℤ] N) hb x, map_add, map_units_zsmul, smul_mk b,
    smul_mk (d b)]

/-- For a dg `(B, A)`-bimodule `M` and a left dg `A`-module `N`, `M ⊗_A N` is a left dg
`B`-module, `b • (m ⊗ n) = (b • m) ⊗ n`. -/
instance instDGModule : DGModule B (TensorProductOver A M N) where
  smul_mem {i k b y} hb hy := by
    obtain ⟨x, hx, rfl⟩ := hy
    show b • mk A M N x ∈ grading (i + k)
    rw [smul_mk b]
    exact mk_mem_grading (smul_mem_grading hb hx)
  d_smul' hb y := d_smul_eq hb y

end Bimodule

/-! ### The unit isomorphism `A ⊗_A N ≅ N` -/

section Unit

variable [DGRing A]

variable (A N)

/-- The multiplication map `A ⊗_A N → N`, `a ⊗ n ↦ a • n`, as a morphism of dg `A`-modules. -/
def lid : TensorProductOver A A N →ᵈᵍ[A] N where
  toFun := lift (smulAddHom A N) fun a a' n => by
    simp only [smulAddHom_apply, op_smul_eq_mul, mul_smul]
  map_add' := map_add _
  map_smul' a y := by
    induction y using induction_on with
    | zero => simp
    | tmul a' n =>
      simp only [smul_tmul, lift_tmul, smulAddHom_apply, smul_eq_mul, mul_smul, RingHom.id_apply]
    | add x y hx hy => simp only [smul_add, map_add, hx, hy, RingHom.id_apply] at *
  map_mem' hy := lift_mem _ _ (fun ha hn => smul_mem_grading ha hn) hy
  map_d' y := lift_d _ _ (fun ha n => by
    simp only [smulAddHom_apply]
    exact d_smul ha n) y

/-- The map `N → A ⊗_A N`, `n ↦ 1 ⊗ n`, as a morphism of dg `A`-modules. -/
def lidInv : N →ᵈᵍ[A] TensorProductOver A A N where
  toFun n := tmul A (1 : A) n
  map_add' := tmul_add 1
  map_smul' a n := by
    rw [RingHom.id_apply, smul_tmul, smul_eq_mul, mul_one, ← op_smul_tmul, op_smul_eq_mul,
      one_mul]
  map_mem' {k n} hn := by
    simpa using tmul_mem_grading (one_mem_grading (A := A)) hn
  map_d' n := by
    rw [d_tmul_of_mem (one_mem_grading (A := A)), d_one, zero_tmul, zero_add, koszulSign,
      Int.negOnePow_zero, one_smul]

variable {A N}

@[simp]
theorem lid_tmul (a : A) (n : N) : lid A N (tmul A a n) = a • n := rfl

@[simp]
theorem lidInv_apply (n : N) : lidInv A N n = tmul A (1 : A) n := rfl

@[simp]
theorem lid_lidInv (n : N) : lid A N (lidInv A N n) = n := by
  simp

@[simp]
theorem lidInv_lid (y : TensorProductOver A A N) : lidInv A N (lid A N y) = y := by
  induction y using induction_on with
  | zero => simp
  | tmul a n =>
    rw [lid_tmul, lidInv_apply, ← op_smul_tmul, op_smul_eq_mul, one_mul]
  | add x y hx hy => rw [map_add, map_add, hx, hy]

theorem lid_comp_lidInv : (lid A N).comp (lidInv A N) = DGModuleHom.id :=
  DGModuleHom.ext lid_lidInv

theorem lidInv_comp_lid : (lidInv A N).comp (lid A N) = DGModuleHom.id :=
  DGModuleHom.ext lidInv_lid

variable (A N)

/-- The unit isomorphism `A ⊗_A N ≅ N`, `a ⊗ n ↦ a • n`, as an `A`-linear equivalence. -/
def lidLinearEquiv : TensorProductOver A A N ≃ₗ[A] N :=
  LinearEquiv.ofLinear (lid A N).toLinearMap (lidInv A N).toLinearMap
    (LinearMap.ext lid_lidInv) (LinearMap.ext lidInv_lid)

/-- The unit isomorphism `A ⊗_A N ≅ N`, `a ⊗ n ↦ a • n`, as an isomorphism of dg abelian
groups; it is `A`-linear (`DG.TensorProductOver.lidLinearEquiv`). -/
def lidEquiv : DGAddEquiv (TensorProductOver A A N) N :=
  DGAddEquiv.ofAddMonoidHom (lid A N).toLinearMap.toAddMonoidHom
    (lidInv A N).toLinearMap.toAddMonoidHom lidInv_lid lid_lidInv
    (fun hy => (lid A N).map_mem hy) (lid A N).map_d

end Unit

end TensorProductOver

end DG

/-! ### The right action and associativity -/

section RightAction

variable {A B M N : Type*} [Ring A] [Ring B] [AddCommGroup M] [Module Aᵐᵒᵖ M]
  [AddCommGroup N] [Module A N] [Module Bᵐᵒᵖ N] [SMulCommClass A Bᵐᵒᵖ N]

namespace TensorProductOver

variable (A M N) in
/-- The action of `b ∈ Bᵐᵒᵖ` on `M ⊗_A N` through the right factor, `(m ⊗ n) • b = m ⊗ (n • b)`,
as an additive map. -/
def rightAct (b : Bᵐᵒᵖ) : TensorProductOver A M N →+ TensorProductOver A M N :=
  lift ((tmulAddHom A M N).compl₂ (DistribMulAction.toAddMonoidHom N b)) fun a m n => by
    simp only [AddMonoidHom.compl₂_apply, DistribMulAction.toAddMonoidHom_apply,
      tmulAddHom_apply, op_smul_tmul, smul_comm a b n]

@[simp]
theorem rightAct_tmul (b : Bᵐᵒᵖ) (m : M) (n : N) :
    rightAct A M N b (tmul A m n) = tmul A m (b • n) :=
  rfl

/-! Scoped instances making `M ⊗_A N` a right `B`-module through `N`, for an `(A, B)`-bimodule
`N`: `(m ⊗ n) • b = m ⊗ (n • b)`. They are scoped
(`open scoped DG.TensorProductOver.RightAction`) because, when `M` also carries a left action of
`Bᵐᵒᵖ` commuting with its right `A`-action, the action through the left factor
(`DG.TensorProductOver.instModule`) is a second, different `Bᵐᵒᵖ`-module structure on the same
type. -/
namespace RightAction

/-- The action of `Bᵐᵒᵖ` on `M ⊗_A N` through the right factor. -/
scoped instance instSMulOp : SMul Bᵐᵒᵖ (TensorProductOver A M N) where
  smul b := rightAct A M N b

/-- `M ⊗_A N` is a right `B`-module through the right factor. -/
scoped instance instModuleOp : Module Bᵐᵒᵖ (TensorProductOver A M N) where
  one_smul y := by
    change rightAct A M N 1 y = y
    induction y using induction_on with
    | zero => simp
    | tmul m n => rw [rightAct_tmul, one_smul]
    | add x y hx hy => rw [map_add, hx, hy]
  mul_smul b b' y := by
    change rightAct A M N (b * b') y = rightAct A M N b (rightAct A M N b' y)
    induction y using induction_on with
    | zero => simp
    | tmul m n => rw [rightAct_tmul, rightAct_tmul, rightAct_tmul, mul_smul]
    | add x y hx hy => rw [map_add, hx, hy, map_add, map_add]
  smul_zero b := map_zero (rightAct A M N b)
  smul_add b := map_add (rightAct A M N b)
  add_smul b b' y := by
    change rightAct A M N (b + b') y = rightAct A M N b y + rightAct A M N b' y
    induction y using induction_on with
    | zero => simp
    | tmul m n => rw [rightAct_tmul, rightAct_tmul, rightAct_tmul, add_smul, tmul_add]
    | add x y hx hy => rw [map_add, hx, hy, map_add, map_add]; abel
  zero_smul y := by
    change rightAct A M N 0 y = 0
    induction y using induction_on with
    | zero => simp
    | tmul m n => rw [rightAct_tmul, zero_smul, tmul_zero]
    | add x y hx hy => rw [map_add, hx, hy, add_zero]

end RightAction

open RightAction

theorem op_smul_eq_rightAct (b : Bᵐᵒᵖ) (y : TensorProductOver A M N) :
    b • y = rightAct A M N b y := rfl

/-- The right action on `M ⊗_A N` through `N`: `(m ⊗ n) • b = m ⊗ (n • b)`. -/
theorem op_smul_tmul_right (b : Bᵐᵒᵖ) (m : M) (n : N) : b • tmul A m n = tmul A m (b • n) := rfl

theorem op_smul_units_smul (b : Bᵐᵒᵖ) (u : ℤˣ) (y : TensorProductOver A M N) :
    b • (u • y) = u • (b • y) :=
  map_units_zsmul (rightAct A M N b) u y

end TensorProductOver

end RightAction

section DGRightAction

variable {A B M N : Type*} [Ring A] [DGAddCommGroup A] [Ring B] [DGAddCommGroup B]
  [AddCommGroup M] [DGAddCommGroup M] [Module Aᵐᵒᵖ M] [DGRightModule A M]
  [AddCommGroup N] [DGAddCommGroup N] [Module A N] [DGModule A N] [Module Bᵐᵒᵖ N]
  [DGRightModule B N] [SMulCommClass A Bᵐᵒᵖ N]

namespace TensorProductOver

open RightAction

theorem op_smul_mem_grading_right {i j : ℤ} {b : B} (hb : b ∈ grading i)
    {y : TensorProductOver A M N} (hy : y ∈ grading j) : op b • y ∈ grading (j + i) := by
  refine induction_on_mem_grading (P := fun y => op b • y ∈ grading (j + i)) ?_ ?_ ?_ ?_ hy
  all_goals beta_reduce
  · rw [smul_zero]; exact zero_mem _
  · intro p q m n hm hn h
    rw [op_smul_tmul_right, ← h, add_assoc]
    exact tmul_mem_grading hm (op_smul_mem_grading hb hn)
  · intro x y hx hy; rw [smul_add]; exact add_mem hx hy
  · intro x hx; rw [smul_neg]; exact neg_mem hx

theorem d_op_smul_right {j : ℤ} {y : TensorProductOver A M N} (hy : y ∈ grading j) (b : B) :
    d (op b • y) = op b • d y + koszulSign j • (op (d b) • y) := by
  refine induction_on_mem_grading
    (P := fun y => d (op b • y) = op b • d y + koszulSign j • (op (d b) • y)) ?_ ?_ ?_ ?_ hy
  all_goals beta_reduce
  · simp
  · intro p q m n hm hn h
    rw [op_smul_tmul_right, d_tmul_of_mem hm, d_tmul_of_mem hm, d_op_smul hn, tmul_add,
      smul_add, smul_add, op_smul_tmul_right, op_smul_units_smul, op_smul_tmul_right,
      op_smul_tmul_right, tmul_units_smul, smul_smul, ← h, koszulSign_add, add_assoc]
  · intro x y hx hy
    rw [smul_add, d_add, hx, hy, d_add, smul_add, smul_add, smul_add]; abel
  · intro x hx; rw [smul_neg, d_neg, hx, d_neg, smul_neg, smul_neg, smul_neg, neg_add]

namespace RightAction

/-- For a dg `(A, B)`-bimodule `N`, `M ⊗_A N` is a right dg `B`-module through `N`. -/
scoped instance instDGRightModule : DGRightModule B (TensorProductOver A M N) where
  op_smul_mem' hb hy := op_smul_mem_grading_right hb hy
  d_op_smul' hy b := d_op_smul_right hy b

end RightAction

end TensorProductOver

end DGRightAction

/-! ### Associativity -/

section Assoc

variable {A B M N P : Type*} [Ring A] [Ring B] [AddCommGroup M] [Module Aᵐᵒᵖ M]
  [AddCommGroup N] [Module A N] [Module Bᵐᵒᵖ N] [SMulCommClass A Bᵐᵒᵖ N]
  [AddCommGroup P] [Module B P]

namespace TensorProductOver

open RightAction

variable (A B M N P)

/-- For fixed `m`, the map `N ⊗_B P → (M ⊗_A N) ⊗_B P`, `n ⊗ p ↦ (m ⊗ n) ⊗ p`. -/
def assocInvAux (m : M) :
    TensorProductOver B N P →+ TensorProductOver B (TensorProductOver A M N) P :=
  lift ((tmulAddHom B (TensorProductOver A M N) P).comp (tmulAddHom A M N m)) fun b n p => by
    simp only [AddMonoidHom.coe_comp, Function.comp_apply, tmulAddHom_apply]
    rw [← op_smul_tmul_right, op_smul_tmul]

/-- The map `M ⊗_A (N ⊗_B P) → (M ⊗_A N) ⊗_B P`, `m ⊗ (n ⊗ p) ↦ (m ⊗ n) ⊗ p`. -/
def assocInv :
    TensorProductOver A M (TensorProductOver B N P) →+
      TensorProductOver B (TensorProductOver A M N) P :=
  lift (AddMonoidHom.mk' (assocInvAux A B M N P) fun m m' => addHom_ext fun n p => by
      simp only [assocInvAux, lift_tmul, AddMonoidHom.coe_comp, Function.comp_apply,
        tmulAddHom_apply, AddMonoidHom.add_apply, add_tmul])
    fun a m y => by
      induction y using induction_on with
      | zero => simp
      | tmul n p =>
        simp only [AddMonoidHom.mk'_apply, assocInvAux, smul_tmul, lift_tmul,
          AddMonoidHom.coe_comp, Function.comp_apply, tmulAddHom_apply, op_smul_tmul]
      | add x y hx hy => rw [smul_add, map_add, map_add, hx, hy]

/-- For fixed `p`, the map `M ⊗_A N → M ⊗_A (N ⊗_B P)`, `m ⊗ n ↦ m ⊗ (n ⊗ p)`. -/
def assocAux (p : P) :
    TensorProductOver A M N →+ TensorProductOver A M (TensorProductOver B N P) :=
  lift ((tmulAddHom A M (TensorProductOver B N P)).compl₂ ((tmulAddHom B N P).flip p))
    fun a m n => by
      simp only [AddMonoidHom.compl₂_apply, AddMonoidHom.flip_apply, tmulAddHom_apply]
      rw [op_smul_tmul, smul_tmul]

/-- The associativity map `(M ⊗_A N) ⊗_B P → M ⊗_A (N ⊗_B P)`,
`(m ⊗ n) ⊗ p ↦ m ⊗ (n ⊗ p)`. -/
def assoc :
    TensorProductOver B (TensorProductOver A M N) P →+
      TensorProductOver A M (TensorProductOver B N P) :=
  lift (AddMonoidHom.mk' (assocAux A B M N P) fun p p' => addHom_ext fun m n => by
      simp only [assocAux, lift_tmul, AddMonoidHom.compl₂_apply, AddMonoidHom.flip_apply,
        tmulAddHom_apply, AddMonoidHom.add_apply, tmul_add]).flip
    fun b x p => by
      induction x using induction_on with
      | zero => simp
      | tmul m n =>
        simp only [AddMonoidHom.flip_apply, AddMonoidHom.mk'_apply, assocAux,
          op_smul_tmul_right, lift_tmul, AddMonoidHom.compl₂_apply, tmulAddHom_apply,
          op_smul_tmul]
      | add x y hx hy => rw [smul_add, map_add, map_add, AddMonoidHom.add_apply, hx, hy,
          AddMonoidHom.add_apply]

variable {A B M N P}

@[simp]
theorem assocInvAux_tmul (m : M) (n : N) (p : P) :
    assocInvAux A B M N P m (tmul B n p) = tmul B (tmul A m n) p := rfl

@[simp]
theorem assocInv_tmul_tmul (m : M) (n : N) (p : P) :
    assocInv A B M N P (tmul A m (tmul B n p)) = tmul B (tmul A m n) p := rfl

@[simp]
theorem assoc_tmul_tmul (m : M) (n : N) (p : P) :
    assoc A B M N P (tmul B (tmul A m n) p) = tmul A m (tmul B n p) := rfl

theorem assocInv_assoc (z : TensorProductOver B (TensorProductOver A M N) P) :
    assocInv A B M N P (assoc A B M N P z) = z := by
  induction z using induction_on with
  | zero => simp
  | tmul x p =>
    induction x using induction_on with
    | zero => simp
    | tmul m n => rfl
    | add x y hx hy => rw [add_tmul, map_add, map_add, hx, hy]
  | add x y hx hy => rw [map_add, map_add, hx, hy]

theorem assoc_assocInv (z : TensorProductOver A M (TensorProductOver B N P)) :
    assoc A B M N P (assocInv A B M N P z) = z := by
  induction z using induction_on with
  | zero => simp
  | tmul m y =>
    induction y using induction_on with
    | zero => simp
    | tmul n p => rfl
    | add x y hx hy => rw [tmul_add, map_add, map_add, hx, hy]
  | add x y hx hy => rw [map_add, map_add, hx, hy]

end TensorProductOver

end Assoc

section DGAssoc

variable {A B M N P : Type*} [Ring A] [DGAddCommGroup A] [Ring B] [DGAddCommGroup B]
  [AddCommGroup M] [DGAddCommGroup M] [Module Aᵐᵒᵖ M] [DGRightModule A M]
  [AddCommGroup N] [DGAddCommGroup N] [Module A N] [DGModule A N] [Module Bᵐᵒᵖ N]
  [DGRightModule B N] [SMulCommClass A Bᵐᵒᵖ N]
  [AddCommGroup P] [DGAddCommGroup P] [Module B P] [DGModule B P]

namespace TensorProductOver

open RightAction

theorem assocInv_mem {k : ℤ} {z : TensorProductOver A M (TensorProductOver B N P)}
    (hz : z ∈ grading k) : assocInv A B M N P z ∈ grading k := by
  unfold assocInv
  refine lift_mem _ _ (fun {i j m y} hm hy => ?_) hz
  rw [add_comm, AddMonoidHom.mk'_apply]
  unfold assocInvAux
  refine lift_mem_add _ _ i (fun {p r n q} hn hq => ?_) hy
  have h := tmul_mem_grading (A := B) (tmul_mem_grading (A := A) hm hn) hq
  rwa [show i + p + r = p + r + i by ring] at h

theorem assocInv_d (z : TensorProductOver A M (TensorProductOver B N P)) :
    assocInv A B M N P (d z) = d (assocInv A B M N P z) := by
  unfold assocInv
  refine lift_d _ _ (fun {i m} hm y => ?_) z
  simp only [AddMonoidHom.mk'_apply]
  induction y using induction_on with
  | zero => simp
  | tmul n p =>
    induction n using DG.induction_on with
    | h_zero => simp
    | h_homogeneous n =>
      rename_i j
      rw [assocInvAux_tmul, assocInvAux_tmul, d_tmul_of_mem (tmul_mem_grading hm n.2),
        d_tmul_of_mem hm, add_tmul, units_smul_tmul, d_tmul_of_mem n.2, map_add,
        map_units_zsmul, assocInvAux_tmul, assocInvAux_tmul, smul_add, smul_smul,
        ← koszulSign_add, add_assoc]
    | h_add n n' hn hn' =>
      simp only [add_tmul, map_add, d_add, hn, hn', smul_add]; abel
  | add x y hx hy => rw [map_add, d_add, hx, hy, d_add, map_add, map_add, smul_add]; abel

theorem assoc_mem {k : ℤ} {z : TensorProductOver B (TensorProductOver A M N) P}
    (hz : z ∈ grading k) : assoc A B M N P z ∈ grading k := by
  exact (DGAddEquiv.ofAddMonoidHom (assocInv A B M N P) (assoc A B M N P) assoc_assocInv
    assocInv_assoc assocInv_mem assocInv_d).symm.map_mem hz

variable (A B M N P)

/-- Associativity of the tensor product over dg rings: for a right dg `A`-module `M`, a dg
`(A, B)`-bimodule `N` and a left dg `B`-module `P`, the isomorphism of dg abelian groups
`(M ⊗_A N) ⊗_B P ≅ M ⊗_A (N ⊗_B P)`, `(m ⊗ n) ⊗ p ↦ m ⊗ (n ⊗ p)` (no signs). The right
`B`-module structure on `M ⊗_A N` is the scoped instance of
`DG.TensorProductOver.RightAction`. -/
def assocEquiv :
    DGAddEquiv (TensorProductOver B (TensorProductOver A M N) P)
      (TensorProductOver A M (TensorProductOver B N P)) :=
  (DGAddEquiv.ofAddMonoidHom (assocInv A B M N P) (assoc A B M N P) assoc_assocInv
    assocInv_assoc assocInv_mem assocInv_d).symm

variable {A B M N P}

@[simp]
theorem assocEquiv_tmul_tmul (m : M) (n : N) (p : P) :
    assocEquiv A B M N P (tmul B (tmul A m n) p) = tmul A m (tmul B n p) := rfl

@[simp]
theorem assocEquiv_symm_tmul_tmul (m : M) (n : N) (p : P) :
    (assocEquiv A B M N P).symm (tmul A m (tmul B n p)) = tmul B (tmul A m n) p := rfl

end TensorProductOver

end DGAssoc

/-! ### The right unit isomorphism `M ⊗_A A ≅ M` -/

section RightUnit

variable {A M : Type*} [Ring A] [DGAddCommGroup A] [DGRing A] [AddCommGroup M]
  [DGAddCommGroup M] [Module Aᵐᵒᵖ M] [DGRightModule A M]

namespace TensorProductOver

variable (A M)

/-- The action map `M ⊗_A A → M`, `m ⊗ a ↦ m • a`. -/
def ridHom : TensorProductOver A M A →+ M :=
  lift ((smulAddHom Aᵐᵒᵖ M).comp (MulOpposite.opAddEquiv : A ≃+ Aᵐᵒᵖ).toAddMonoidHom).flip
    fun a m a' => by
      simp only [AddMonoidHom.flip_apply, AddMonoidHom.coe_comp, Function.comp_apply,
        AddEquiv.coe_toAddMonoidHom, MulOpposite.opAddEquiv_apply, smulAddHom_apply, smul_eq_mul,
        op_mul, mul_smul]

variable {A M}

omit [DGAddCommGroup A] [DGRing A] [DGAddCommGroup M] [DGRightModule A M] in
@[simp]
theorem ridHom_tmul (m : M) (a : A) : ridHom A M (tmul A m a) = op a • m := rfl

theorem ridHom_mem {k : ℤ} {y : TensorProductOver A M A} (hy : y ∈ grading k) :
    ridHom A M y ∈ grading k :=
  lift_mem _ _ (fun hm ha => op_smul_mem_grading ha hm) hy

theorem ridHom_d (y : TensorProductOver A M A) : ridHom A M (d y) = d (ridHom A M y) :=
  lift_d _ _ (fun hm a => by
    simp only [AddMonoidHom.flip_apply, AddMonoidHom.coe_comp, Function.comp_apply,
      AddEquiv.coe_toAddMonoidHom, MulOpposite.opAddEquiv_apply, smulAddHom_apply]
    exact d_op_smul hm a) y

variable (A M)

/-- The right unit isomorphism `M ⊗_A A ≅ M`, `m ⊗ a ↦ m • a`, with inverse `m ↦ m ⊗ 1`, as an
isomorphism of dg abelian groups; it is right `A`-linear (`DG.TensorProductOver.rid_op_smul`). -/
def rid : DGAddEquiv (TensorProductOver A M A) M :=
  DGAddEquiv.ofAddMonoidHom (ridHom A M) ((tmulAddHom A M A).flip 1)
    (fun y => by
      induction y using induction_on with
      | zero => simp
      | tmul m a =>
        simp only [ridHom_tmul, AddMonoidHom.flip_apply, tmulAddHom_apply, op_smul_tmul,
          smul_eq_mul, mul_one]
      | add x y hx hy => rw [map_add, map_add, hx, hy])
    (fun m => by simp) ridHom_mem ridHom_d

variable {A M}

@[simp]
theorem rid_tmul (m : M) (a : A) : rid A M (tmul A m a) = op a • m := rfl

@[simp]
theorem rid_symm_apply (m : M) : (rid A M).symm m = tmul A m (1 : A) := rfl

open RightAction in
/-- The right unit isomorphism is right `A`-linear. -/
theorem rid_op_smul (a : A) (y : TensorProductOver A M A) :
    rid A M (op a • y) = op a • rid A M y := by
  induction y using induction_on with
  | zero => simp
  | tmul m a' =>
    rw [op_smul_tmul_right, rid_tmul, rid_tmul, op_smul_eq_mul, op_mul, mul_smul]
  | add x y hx hy => rw [smul_add, map_add, hx, hy, map_add, smul_add]

end TensorProductOver

end RightUnit

end DG
