import DG.Category.Homotopy.Homotopy
import DG.Category.Homotopy.Shift
import DG.Category.SubQuotient
import DG.Category.Tensor.YonedaHom
import DG.Category.Yoneda
import DG.Module.ULift

/-!
# Generators of dg modules over a dg category

Let `C` be a dg category. The representable dg module `C(X, -)` (`DG.CatModule.representable X`)
is generated by the cocycle `𝟙 X`, freely: every element of `C(X, Y)` is `f • 𝟙 X = f` for a
unique `f`. This file axiomatizes this situation, together with its variant for direct summands
`e · C(X, -)` of representable modules cut out by degree-`0` idempotent cocycles `e` of `X`, and
proves the dg Yoneda lemma for cochains out of such modules.

## Main definitions

* `DG.DGCategory.Idempotent X`: a degree-`0` idempotent cocycle `e ∈ C(X, X)`.
* `DG.CatModule.corner e`: the dg submodule `e · C(X, -) = {h | e ≫ h = h}` of `C(X, -)`, a
  direct summand; `DG.CatModule.corner (DG.DGCategory.Idempotent.id X)` is `C(X, -)`.
* `DG.CatModule.ulift M`: a dg module with values in a larger universe, `ULift (M.obj X)`. It is
  used to place the representable modules `C(X, -)`, whose values lie in the universe of the Hom
  types of `C`, in any larger universe.
* `DG.CatModule.IsCornerGenerator R e k g`: `g ∈ R.obj X` is a cocycle of degree `k` such that
  `f ↦ f • g` identifies `e · C(X, -)` with `R` up to the shift by `-k`, i.e.
  `R ≅ (e · C(X, -))⟦-k⟧`. Instances: `DG.CatModule.isCornerGenerator_representable`
  (`𝟙 X ∈ C(X, -)`), `DG.CatModule.isCornerGenerator_corner`, and the stability under shifts
  and `ulift`.
* `DG.CatModule.IsCornerGenerator.ofElement`: the cochain of degree `n` out of `R` attached to
  `y ∈ (N X)ᵏ⁺ⁿ` with `e • y = y`, `f • g ↦ (-1)^{n |f|} f • y`.

## Main results

* `DG.CatModule.IsCornerGenerator.eq_ofElement`, `DG.CatModule.IsCornerGenerator.ext_gen`,
  `DG.CatModule.IsCornerGenerator.δ_ofElement`: the dg Yoneda lemma for cochains, every cochain
  of degree `n` out of `R` is `ofElement` of its value at `g`, and `δ` corresponds to `d`. For
  `R = C(X, -)` this is the Hom-complex form of the dg Yoneda lemma
  `DG.CatModule.yonedaHOM : HOM_C(C(X, -), N) ≅ N X` (`DG.Category.Tensor.YonedaHom`), the two
  descriptions of cochains out of `C(X, -)` being identified by
  `DG.CatModule.ofElement_representable_eq_yonedaCochain`; the present version applies as well
  to the universe lifts and shifts of representable modules and to their direct summands
  `e · C(X, -)`.
-/

open CategoryTheory DirectSum

universe w' w v u

set_option backward.isDefEq.respectTransparency false

namespace DG

variable {C : Type u} [Category.{v} C] [Preadditive C] [∀ X Y : C, DGAddCommGroup (X ⟶ Y)]

/-! ### Idempotents -/

namespace DGCategory

/-- A degree-`0` idempotent cocycle of an object `X` of a dg category. -/
structure Idempotent (X : C) where
  /-- The underlying endomorphism. -/
  val : X ⟶ X
  mem_cocycles : val ∈ cocycles (X ⟶ X) 0
  comp_self : val ≫ val = val

namespace Idempotent

variable {X : C} (e : Idempotent X)

theorem mem_grading : e.val ∈ grading (M := X ⟶ X) 0 := e.mem_cocycles.1

@[simp]
theorem d_val : d e.val = 0 := e.mem_cocycles.2

@[simp]
theorem comp_self_assoc {Y : C} (f : X ⟶ Y) : e.val ≫ e.val ≫ f = e.val ≫ f := by
  rw [← Category.assoc, e.comp_self]

variable [DGCategory C]

/-- The identity of `X`, as a degree-`0` idempotent cocycle. -/
@[simps]
def id (X : C) : Idempotent X where
  val := 𝟙 X
  mem_cocycles := id_mem_cocycles X
  comp_self := Category.comp_id _

omit [DGCategory C] in
@[simp]
theorem twist_val (n : ℤ) : CatModule.twist n e.val = e.val := by
  rw [CatModule.twist_of_mem e.mem_grading, mul_zero, koszulSign_zero, one_smul]

end Idempotent

end DGCategory


namespace CatModule

section ULift

variable (M : CatModule.{w} C)

/-- The dg module `X ↦ ULift (M.obj X)`, with values in the universe `max w w'`. -/
@[simps obj]
noncomputable def ulift : CatModule.{max w w'} C where
  obj X := ULift.{w'} (M.obj X)
  act := AddMonoidHom.mk'
    (fun f => (ULift.upAddHom _).comp ((M.act f).comp (ULift.downAddHom _)))
    fun f g => by
      ext m
      exact add_smul (M := M) f g m.down
  act_mem' hf hm := smul_mem_grading (M := M) hf hm
  act_id' _ m := ULift.ext _ _ (id_smul (M := M) m.down)
  act_comp' f g m := ULift.ext _ _ (comp_smul (M := M) f g m.down)
  d_act' {X Y i f} hf m := ULift.ext _ _ (by
    change d (f • m.down) = d f • m.down + (koszulSign i • f • d m.down : M.obj Y)
    exact d_smul hf m.down)

variable {M}

@[simp]
theorem ulift_smul_down {X Y : C} (f : X ⟶ Y) (m : (ulift.{w'} M).obj X) :
    (f • m : (ulift.{w'} M).obj Y).down = f • m.down := rfl

theorem ulift_smul_up {X Y : C} (f : X ⟶ Y) (m : M.obj X) :
    f • (show (ulift.{w'} M).obj X from ULift.up m) =
      (show (ulift.{w'} M).obj Y from ULift.up (f • m)) := rfl

end ULift

/-! ### Corners of representable modules -/

section Corner

variable [DGCategory C] {X : C} (e : DGCategory.Idempotent X)

/-- The dg submodule `e · C(X, -)` of the representable module `C(X, -)`, for a degree-`0`
idempotent cocycle `e` of `X`: the morphisms `h : X ⟶ Y` with `e ≫ h = h`. -/
def cornerSubmodule : CatSubmodule (representable X) where
  carrier Y :=
    { carrier := {h : X ⟶ Y | e.val ≫ h = h}
      add_mem' := fun {a b} ha hb => by
        change e.val ≫ (a + b) = a + b
        rw [Preadditive.comp_add, ha, hb]
      zero_mem' := Limits.comp_zero
      neg_mem' := fun {a} ha => by
        change e.val ≫ (-a) = -a
        rw [Preadditive.comp_neg, ha] }
  decompose_mem' {Y h} hh n := by
    have hh' : e.val ≫ h = h := hh
    have := decompose_comp_left e.mem_grading (h : X ⟶ Y) n
    rw [add_zero, hh'] at this
    exact this.symm
  d_mem' {Y h} hh := by
    change e.val ≫ d h = d h
    rw [← d_comp_of_d_eq_zero_left e.d_val]
    exact congrArg d hh
  smul_mem' {Y Z} f h hh := by
    change e.val ≫ (h ≫ f) = h ≫ f
    rw [← Category.assoc]
    exact congrArg (· ≫ f) hh

theorem mem_cornerSubmodule_iff {Y : C} {h : X ⟶ Y} :
    h ∈ (cornerSubmodule e).carrier Y ↔ e.val ≫ h = h :=
  Iff.rfl

/-- The dg module `e · C(X, -)`, a direct summand of the representable module `C(X, -)`. -/
noncomputable abbrev corner : CatModule.{v} C := (cornerSubmodule e).toCatModule

/-- The generator `e ∈ e · C(X, X)` of the corner. -/
def cornerGen : (corner e).obj X := ⟨e.val, e.comp_self⟩

end Corner

/-! ### Corner generators -/

section Generator

/-- A corner generator of a dg module `R` over `C`: a cocycle `g ∈ R.obj X` of degree `k`
together with a degree-`0` idempotent cocycle `e` of `X` with `e • g = g`, such that every
element of every `R.obj Y` is of the form `f • g` for some `f : X ⟶ Y`, and `f • g = 0` only if
`e ≫ f = 0`. Equivalently, `f ↦ f • g` is an isomorphism `(e · C(X, -))⟦-k⟧ ≅ R`. For
`e = 𝟙 X` (`DG.DGCategory.Idempotent.id`) the module `R` is free on `g`, i.e.
`R ≅ C(X, -)⟦-k⟧`. -/
structure IsCornerGenerator (R : CatModule.{w} C) {X : C} (e : DGCategory.Idempotent X) (k : ℤ)
    (g : R.obj X) : Prop where
  mem_grading : g ∈ grading k
  d_eq_zero : d g = 0
  val_smul : e.val • g = g
  surjective : ∀ Y : C, Function.Surjective fun f : X ⟶ Y => f • g
  val_comp_eq_zero : ∀ {Y : C} (f : X ⟶ Y), f • g = (0 : R.obj Y) → e.val ≫ f = 0

namespace IsCornerGenerator

variable {R : CatModule.{w} C} {X : C} {e : DGCategory.Idempotent X} {k : ℤ} {g : R.obj X}
  (hg : IsCornerGenerator R e k g)

/-- The generator of `R`, a free generator: `f ↦ f • g` is bijective. -/
theorem of_bijective [DGCategory C] (hk : g ∈ grading k) (hd : d g = 0)
    (hb : ∀ Y : C, Function.Bijective fun f : X ⟶ Y => f • g) :
    IsCornerGenerator R (DGCategory.Idempotent.id X) k g where
  mem_grading := hk
  d_eq_zero := hd
  val_smul := id_smul g
  surjective Y := (hb Y).2
  val_comp_eq_zero {Y} f hf := by
    rw [DGCategory.Idempotent.id_val, Category.id_comp]
    exact (hb Y).1 (hf.trans (zero_smul (M := R) g).symm)

/-! #### Cochains out of `R` -/

variable {N : CatModule.{w} C}


/-- Every cochain of degree `n` out of `R` is determined on the generator:
`z (f • g) = (-1)^{n |f|} f • z g`, i.e. `z (f • g) = twist n f • z g` for all `f`. -/
theorem app_smul_gen {n : ℤ} (z : Cochain R N n) {Y : C} (f : X ⟶ Y) :
    z.app Y (f • g) = twist n f • z.app X g := by
  induction f using DG.induction_on with
  | h_zero => simp
  | h_homogeneous f => rw [z.map_smul f.2, twist_of_mem f.2, units_smul_smul]
  | h_add f f' hf hf' => rw [add_smul, map_add, hf, hf', map_add, add_smul]

include hg

theorem val_comp_eq {Y : C} {f f' : X ⟶ Y} (h : f • g = f' • g) : e.val ≫ f = e.val ≫ f' := by
  rw [← sub_eq_zero, ← Preadditive.comp_sub]
  exact hg.val_comp_eq_zero _ (by rw [sub_smul, h, sub_self])

theorem val_comp_smul {Y : C} (f : X ⟶ Y) : (e.val ≫ f) • g = f • g := by
  rw [comp_smul, hg.val_smul]

/-- The coordinate of an element `r ∈ R.obj Y`: the unique `h : X ⟶ Y` with `e ≫ h = h` and
`h • g = r` (`DG.CatModule.IsCornerGenerator.coord_smul`). -/
noncomputable def coord (Y : C) : R.obj Y →+ (X ⟶ Y) where
  toFun r := e.val ≫ Function.surjInv (hg.surjective Y) r
  map_zero' := hg.val_comp_eq_zero _ (Function.surjInv_eq (hg.surjective Y) 0)
  map_add' r r' := by
    rw [← Preadditive.comp_add]
    refine hg.val_comp_eq ?_
    simp only [add_smul, Function.surjInv_eq (hg.surjective Y)]

theorem coord_apply {Y : C} (r : R.obj Y) :
    hg.coord Y r = e.val ≫ Function.surjInv (hg.surjective Y) r := rfl

theorem coord_eq {Y : C} {r : R.obj Y} {f : X ⟶ Y} (h : f • g = r) :
    hg.coord Y r = e.val ≫ f :=
  hg.val_comp_eq ((Function.surjInv_eq (hg.surjective Y) r).trans h.symm)

@[simp]
theorem coord_smul_gen {Y : C} (f : X ⟶ Y) : hg.coord Y (f • g) = e.val ≫ f :=
  hg.coord_eq rfl

@[simp]
theorem coord_gen : hg.coord X g = e.val := by
  rw [hg.coord_eq (id_smul g), Category.comp_id]

@[simp]
theorem coord_smul {Y : C} (r : R.obj Y) : hg.coord Y r • g = r := by
  rw [coord_apply, hg.val_comp_smul, Function.surjInv_eq (hg.surjective Y)]

@[simp]
theorem val_comp_coord {Y : C} (r : R.obj Y) : e.val ≫ hg.coord Y r = hg.coord Y r := by
  rw [coord_apply, e.comp_self_assoc]

theorem coord_act {Y Z : C} (f : Y ⟶ Z) (r : R.obj Y) :
    hg.coord Z (f • r) = hg.coord Y r ≫ f := by
  conv_lhs => rw [← hg.coord_smul r, ← comp_smul]
  rw [coord_smul_gen, ← Category.assoc, val_comp_coord]

theorem app_eq {n : ℤ} (z : Cochain R N n) {Y : C} (r : R.obj Y) :
    z.app Y r = twist n (hg.coord Y r) • z.app X g := by
  conv_lhs => rw [← hg.coord_smul r]
  exact app_smul_gen z _

/-- Two cochains out of `R` agreeing on the generator are equal. -/
theorem ext_gen {n : ℤ} {z z' : Cochain R N n} (h : z.app X g = z'.app X g) : z = z' :=
  Cochain.ext fun Y r => by rw [hg.app_eq z r, hg.app_eq z' r, h]

theorem app_gen_mem {n : ℤ} (z : Cochain R N n) : z.app X g ∈ grading (k + n) :=
  z.map_mem hg.mem_grading

theorem val_smul_app_gen {n : ℤ} (z : Cochain R N n) : e.val • z.app X g = z.app X g := by
  rw [← e.twist_val n, ← app_smul_gen z, hg.val_smul]

variable [DGCategory C]

theorem coord_mem {Y : C} {i : ℤ} {r : R.obj Y} (hr : r ∈ grading i) :
    hg.coord Y r ∈ grading (i - k) := by
  set f := Function.surjInv (hg.surjective Y) r
  have hf : f • g = r := Function.surjInv_eq (hg.surjective Y) r
  have h := decompose_map (k := k) ((R.act (X := X) (Y := Y)).flip g)
    (fun hm => smul_mem_grading hm hg.mem_grading) f (i - k)
  rw [sub_add_cancel] at h
  change (decompose (grading (M := R.obj Y)) (f • g) i : R.obj Y) =
    (decompose (grading (M := X ⟶ Y)) f (i - k) : X ⟶ Y) • g at h
  rw [hf, decompose_of_mem_same _ hr] at h
  rw [hg.coord_eq h.symm]
  have := comp_mem_grading e.mem_grading
    (SetLike.coe_mem (decompose (grading (M := X ⟶ Y)) f (i - k)))
  rwa [zero_add] at this

theorem coord_d {Y : C} (r : R.obj Y) : hg.coord Y (d r) = d (hg.coord Y r) := by
  conv_lhs => rw [← hg.coord_smul r, d_smul_of_d_eq_zero_right hg.d_eq_zero]
  rw [coord_smul_gen, ← d_comp_of_d_eq_zero_left e.d_val, val_comp_coord]

/-- The cochain of degree `n` out of `R` attached to `y ∈ (N X)ᵏ⁺ⁿ` with `e • y = y`:
`f • g ↦ (-1)^{n |f|} f • y`, i.e. `r ↦ twist n (coord r) • y`. -/
noncomputable def ofElement {n : ℤ} (y : N.obj X) (hy : y ∈ grading (k + n)) :
    Cochain R N n where
  app Y := ((N.act (X := X) (Y := Y)).flip y).comp ((twist n).comp (hg.coord Y))
  map_mem' {Y i r} hr := by
    have := smul_mem_grading (M := N) (twist_mem (n := n) (hg.coord_mem hr)) hy
    rwa [show i - k + (k + n) = i + n by ring] at this
  map_smul' {Y Z i f} hf r := by
    change twist n (hg.coord Z (f • r)) • y = _ • (f • (twist n (hg.coord Y r) • y))
    rw [hg.coord_act, twist_comp, comp_smul, twist_of_mem hf, units_smul_smul]

theorem ofElement_apply {n : ℤ} (y : N.obj X) (hy : y ∈ grading (k + n)) {Y : C}
    (r : R.obj Y) : (hg.ofElement y hy).app Y r = twist n (hg.coord Y r) • y := rfl

@[simp]
theorem ofElement_smul_gen {n : ℤ} (y : N.obj X) (hy : y ∈ grading (k + n)) {Y : C}
    (f : X ⟶ Y) : (hg.ofElement y hy).app Y (f • g) = twist n (e.val ≫ f) • y := by
  rw [ofElement_apply, coord_smul_gen]

@[simp]
theorem ofElement_gen {n : ℤ} (y : N.obj X) (hy : y ∈ grading (k + n)) :
    (hg.ofElement y hy).app X g = e.val • y := by
  rw [ofElement_apply, coord_gen, e.twist_val]

theorem ofElement_congr {n : ℤ} {y y' : N.obj X} (h : y = y') (hy : y ∈ grading (k + n))
    (hy' : y' ∈ grading (k + n)) : hg.ofElement y hy = hg.ofElement y' hy' := by
  subst h; rfl

/-- The dg Yoneda lemma for cochains: every cochain of degree `n` out of `R` is `ofElement` of
its value at the generator. -/
theorem eq_ofElement {n : ℤ} (z : Cochain R N n) : z = hg.ofElement _ (hg.app_gen_mem z) :=
  hg.ext_gen (by rw [ofElement_gen, hg.val_smul_app_gen])

/-- The differential of `ofElement y` is `ofElement (d y)`. -/
theorem δ_ofElement {n m : ℤ} (hnm : n + 1 = m) (y : N.obj X) (hy : y ∈ grading (k + n))
    (hdy : d y ∈ grading (k + m)) : δ n m (hg.ofElement y hy) = hg.ofElement (d y) hdy :=
  hg.ext_gen (by
    rw [δ_apply _ _ hnm, hg.d_eq_zero, map_zero, _root_.smul_zero, sub_zero, ofElement_gen,
      ofElement_gen, d_smul_of_d_eq_zero (e.mem_grading) e.d_val, koszulSign_zero, one_smul])

theorem ofElement_add {n : ℤ} (y y' : N.obj X) (hy : y ∈ grading (k + n))
    (hy' : y' ∈ grading (k + n)) :
    hg.ofElement (y + y') (add_mem hy hy') = hg.ofElement y hy + hg.ofElement y' hy' :=
  Cochain.ext fun _ _ => by simp [ofElement_apply]

@[simp]
theorem ofElement_zero {n : ℤ} : hg.ofElement (0 : N.obj X) (zero_mem (grading (k + n))) = 0 :=
  Cochain.ext fun _ _ => by simp [ofElement_apply]

/-- The `0`-cochain of a morphism out of `R` is `ofElement` of the image of the generator. -/
theorem ofHom_eq_ofElement (φ : R ⟶ N) :
    Cochain.ofHom φ = hg.ofElement (φ.app X g) (by simpa using φ.map_mem hg.mem_grading) :=
  hg.ext_gen (by rw [ofElement_gen, Cochain.ofHom_apply, ← φ.map_smul, hg.val_smul])

/-! #### Stability under shifts and universe lifts -/

omit hg [DGCategory C] in
theorem twist_twist_self (n : ℤ) {Y : C} (f : X ⟶ Y) : twist n (twist n f) = f := by
  rw [twist_twist]
  induction f using DG.induction_on with
  | h_zero => simp
  | h_homogeneous f =>
    rename_i i
    rw [twist_of_mem f.2, koszulSign_even ⟨n * i, by ring⟩, one_smul]
  | h_add f f' hf hf' => rw [map_add, hf, hf']

/-- A corner generator of `R` gives a corner generator of the shift `R⟦n⟧`, of degree
`k - n`. -/
theorem shift (n : ℤ) : IsCornerGenerator (CatModule.shift n R) e (k - n) (shift.mk n g) where
  mem_grading := shift.mk_mem_grading hg.mem_grading
  d_eq_zero := by rw [shift.d_mk, hg.d_eq_zero, _root_.smul_zero]; rfl
  val_smul := by rw [shift.smul_mk_eq, e.twist_val, hg.val_smul]
  surjective Y r := by
    obtain ⟨f, hf⟩ := hg.surjective Y (shift.unmk n r)
    refine ⟨twist n f, ?_⟩
    change shift.mk n (twist n (twist n f) • g) = r
    rw [twist_twist_self]
    exact (congrArg (shift.mk n) hf).trans (shift.mk_unmk r)
  val_comp_eq_zero {Y} f hf := by
    rw [shift.smul_mk_eq] at hf
    have h := hg.val_comp_eq_zero _ ((shift.mk n).injective (hf.trans (map_zero _).symm))
    rw [← e.twist_val n, ← twist_comp] at h
    rw [← twist_twist_self n (e.val ≫ f), h, map_zero]

omit [DGCategory C] in
/-- A corner generator of `R` gives a corner generator of its universe lift. -/
theorem ulift : IsCornerGenerator (CatModule.ulift.{w'} R) e k (ULift.up g) where
  mem_grading := hg.mem_grading
  d_eq_zero := ULift.ext _ _ hg.d_eq_zero
  val_smul := ULift.ext _ _ hg.val_smul
  surjective Y r := by
    obtain ⟨f, hf⟩ := hg.surjective Y r.down
    exact ⟨f, ULift.ext _ _ hf⟩
  val_comp_eq_zero f hf := hg.val_comp_eq_zero f (congrArg ULift.down hf)

end IsCornerGenerator

variable [DGCategory C] (X : C)

/-- The representable module `C(X, -)` is free on `𝟙 X`. -/
theorem isCornerGenerator_representable :
    IsCornerGenerator (representable X) (DGCategory.Idempotent.id X) 0 (𝟙 X) :=
  IsCornerGenerator.of_bijective (id_mem_grading X) (d_id X) fun Y =>
    ⟨fun f f' h => by
      have h' : 𝟙 X ≫ f = 𝟙 X ≫ f' := h
      simpa using h', fun h => ⟨h, show 𝟙 X ≫ h = h from Category.id_comp h⟩⟩

/-- For the representable module `C(X, -)`, generated by `𝟙 X`, the cochain attached to an
element `y ∈ (N X)ⁿ` by `DG.CatModule.IsCornerGenerator.ofElement` is the cochain
`DG.CatModule.yonedaCochain` of the Hom-complex form of the dg Yoneda lemma
(`DG.CatModule.yonedaHOM`). -/
theorem ofElement_representable_eq_yonedaCochain {N : CatModule.{v} C} {n : ℤ} (y : N.obj X)
    (hy : y ∈ grading (0 + n)) :
    (isCornerGenerator_representable X).ofElement y hy =
      yonedaCochain n ⟨y, by rwa [zero_add] at hy⟩ :=
  (isCornerGenerator_representable X).ext_gen (by
    rw [IsCornerGenerator.ofElement_gen, DGCategory.Idempotent.id_val, yonedaCochain_app_id]
    exact id_smul y)

/-- The Hom-complex form of the dg Yoneda lemma in terms of
`DG.CatModule.IsCornerGenerator.ofElement`: the inverse of `DG.CatModule.yonedaHOM` sends a
homogeneous element `y ∈ (N X)ⁿ` to the class of the cochain `ofElement y`. -/
theorem yonedaHOM_symm_eq_ofElement {N : CatModule.{v} C} {n : ℤ} {y : N.obj X}
    (hy : y ∈ grading n) :
    (yonedaHOM X N).symm y =
      DirectSum.of (fun n => Cochain (representable X) N n) n
        ((isCornerGenerator_representable X).ofElement y (by rwa [zero_add])) := by
  rw [yonedaHOM_symm_of_mem hy, ofElement_representable_eq_yonedaCochain]

variable {X} in
/-- The corner `e · C(X, -)` is generated by `e`. -/
theorem isCornerGenerator_corner (e : DGCategory.Idempotent X) :
    IsCornerGenerator (corner e) e 0 (cornerGen e) where
  mem_grading := e.mem_grading
  d_eq_zero := Subtype.ext e.d_val
  val_smul := Subtype.ext e.comp_self
  surjective _ h := ⟨h.1, Subtype.ext h.2⟩
  val_comp_eq_zero _ hf := congrArg Subtype.val hf

end Generator

end CatModule

end DG
