import DG.Category.Derived.Compact
import DG.Compact.Brown
import DG.Category.Derived.Comparison
import DG.Category.Derived.Small
import DG.Category.Derived.Induction

/-!
# Keller's theorem: quasi-equivalences induce equivalences of derived categories

A dg functor `F : C ⥤ D` between dg categories is a *quasi-equivalence*
(`DG.IsQuasiEquivalence F`) if it induces quasi-isomorphisms `C(X, X') → D(F X, F X')` of Hom
complexes and every object of `D` is isomorphic in `H⁰(D)` to an object `F X`. Keller's theorem
[Keller, *Deriving DG categories*, §9.1] states that derived induction `LF_! : D(C) ⥤ D(D)` is then
an equivalence of triangulated categories, with quasi-inverse the restriction `F^* : D(D) ⥤ D(C)`.

## Proof

* The unit `X ⟶ F^* LF_! X` is an isomorphism on the representable modules `C(X, -)`: induction
  takes `C(X, -)` to `D(F X, -)` (`DG.CatModule.inductionULiftRepresentableIso`), and the unit
  becomes the morphism `C(X, -) ⟶ D(F X, F -)` given by `F`, a quasi-isomorphism by assumption.
  The objects at which the unit is an isomorphism form a localizing subcategory of `D(C)`, since
  `LF_!` and `F^*` are triangulated and preserve coproducts; as the representables compactly
  generate `D(C)` (`DG.CatModule.DerivedCategory.compactlyGenerates`), the unit is an
  isomorphism.
* Restriction `F^*` reflects zero objects: if `N(F X)` is acyclic for all `X`, so is `N(Y)` for
  every `Y`, since `Y ≅ F X` in `H⁰(D)` makes `N(Y)` and `N(F X)` homotopy equivalent. By the
  triangle identity `F^*` of the counit is an isomorphism, hence so is the counit.

The first step only uses that `F` is quasi-fully faithful (`DG.IsQuasiFullyFaithful F`), and the
second only that restriction along `F` reflects acyclicity; under these two hypotheses `LF_!` is
still an equivalence (`DG.CatModule.DerivedCategory.inductionEquivalence`). This is used for
Morita theory (`DG.Category.Derived.Morita`).

## Main definitions and results

* `DG.IsQuasiFullyFaithful F`, `DG.IsQuasiEquivalence F`.
* `DG.CatModule.isAcyclic_of_isAcyclic_precomp`: restriction along a functor which is
  essentially surjective on `H⁰` reflects acyclicity.
* `DG.CatTensorProduct.ridULift`, `DG.CatModule.inductionULiftRepresentableIso`: the co-Yoneda
  isomorphism `F_! C(X, -) ≅ D(F X, -)`, for representable modules lifted to a larger universe.
* `DG.CatModule.representableMapULift F X : C(X, -) ⟶ F^* D(F X, -)`, a quasi-isomorphism when
  `F` is quasi-fully faithful; `DG.CatModule.isQuasiIso_unit_app_representable`.
* `DG.CatModule.DerivedCategory.restrict_preservesCoproducts`,
  `DG.CatModule.DerivedCategory.isLocalizing_unitIsIso`,
  `DG.CatModule.DerivedCategory.isIso_unit_app`, `DG.CatModule.DerivedCategory.isIso_counit_app`.
* `DG.CatModule.DerivedCategory.inductionEquivalence : D(C) ≌ D(D)` for `F` quasi-fully faithful
  with restriction reflecting acyclicity.
* `DG.CatModule.DerivedCategory.kellerEquivalence : D(C) ≌ D(D)` (functor `LF_!`, inverse `F^*`),
  `DG.CatModule.DerivedCategory.induction_isEquivalence`,
  `DG.CatModule.DerivedCategory.restrict_isEquivalence`.
* For dg rings: `DG.DGRingHom.singleObjFunctor`, `DG.DGRingHom.isQuasiEquivalence_singleObjFunctor`
  and `DG.DGRingHom.derivedEquivalence : D(B) ≌ D(A)` for a quasi-isomorphism `B → A`.

## Universes

For `C : Type u₁` with `[Category.{v₁} C]` and `D : Type u₂` with `[Category.{v₂} D]`, dg modules
take values in `Type (max u₁ v₁ v₂ w)`, the derived category of `C` has morphisms in the same
universe (as it is compactly generated by a family indexed by `C`; such a model exists by
`DG.CatModule.HasDerivedCategory.small`), and that of `D` is arbitrary.
-/

open CategoryTheory Limits Pretriangulated

universe w w' w₁ w₂ v v₁ v₂ u₂ u₁

set_option backward.isDefEq.respectTransparency false

namespace DG

section General

variable {C : Type u₁} [Category.{v₁} C] [Preadditive C] [∀ X Y : C, DGAddCommGroup (X ⟶ Y)]
  [DGCategory C] {D : Type u₂} [Category.{v₂} D] [Preadditive D]
  [∀ X Y : D, DGAddCommGroup (X ⟶ Y)] [DGCategory D] (F : C ⥤ D) [F.Additive] [F.IsDGFunctor]

/-- A dg functor `F : C ⥤ D` is *quasi-fully faithful* if the maps of Hom complexes
`C(X, X') → D(F X, F X')` are quasi-isomorphisms. -/
structure IsQuasiFullyFaithful : Prop where
  bijective_cohomology (X X' : C) (n : ℤ) :
    Function.Bijective (cohomology.mapAddMonoidHom (F.mapAddHom (X := X) (Y := X'))
      (fun h => F.map_mem_grading h) (fun f => F.map_d f) n)

/-- A dg functor `F : C ⥤ D` is a *quasi-equivalence* if the maps of Hom complexes
`C(X, X') → D(F X, F X')` are quasi-isomorphisms, and every object `Y` of `D` is isomorphic in
`H⁰(D)` to an object `F X`: there are cocycles `a : F X ⟶ Y`, `b : Y ⟶ F X` of degree `0` with
`a ≫ b - 𝟙` and `b ≫ a - 𝟙` coboundaries. -/
structure IsQuasiEquivalence : Prop extends IsQuasiFullyFaithful F where
  exists_iso (Y : D) : ∃ (X : C) (a : F.obj X ⟶ Y) (b : Y ⟶ F.obj X),
    a ∈ cocycles (F.obj X ⟶ Y) 0 ∧ b ∈ cocycles (Y ⟶ F.obj X) 0 ∧
      a ≫ b - 𝟙 (F.obj X) ∈ coboundaries (F.obj X ⟶ F.obj X) 0 ∧
      b ≫ a - 𝟙 Y ∈ coboundaries (Y ⟶ Y) 0

namespace CatModule

variable {F}

omit [DGCategory C] [DGCategory D] in
/-- Restriction along a dg functor which is essentially surjective on `H⁰` reflects acyclicity:
if `N(F X)` is acyclic for every `X`, then `N` is acyclic. -/
theorem isAcyclic_of_isAcyclic_precomp (hF : IsQuasiEquivalence F) {N : CatModule.{w} D}
    (h : IsAcyclic ((precomp F).obj N)) : IsAcyclic N := by
  intro Y
  obtain ⟨X, a, b, ha, hb, -, hba⟩ := hF.exists_iso Y
  obtain ⟨ha₀, hda⟩ := mem_cocycles.mp ha
  obtain ⟨hb₀, hdb⟩ := mem_cocycles.mp hb
  obtain ⟨t, ht, hdt⟩ := mem_coboundaries.mp hba
  refine DG.isAcyclic_iff.mpr fun k y hy hdy => ?_
  have hby : b • y ∈ grading k := by simpa using smul_mem_grading hb₀ hy
  have hdby : d (b • y) = 0 := by
    rw [d_smul hb₀, hdb, hdy]
    simp
  obtain ⟨z, hz, hdz⟩ : ∃ z : N.obj (F.obj X), z ∈ grading (k - 1) ∧ d z = b • y :=
    DG.isAcyclic_iff.mp (h X) k (b • y) hby hdby
  refine ⟨a • z - t • y, sub_mem (by simpa using smul_mem_grading ha₀ hz)
    (by simpa [sub_eq_neg_add] using smul_mem_grading ht hy), ?_⟩
  have e1 : d (a • z) = a • (b • y) := by
    rw [d_smul ha₀, hda, zero_smul, zero_add, koszulSign_zero, one_smul]
    exact congrArg _ hdz
  have e2 : d (t • y) = (b ≫ a) • y - y := by
    rw [d_smul ht, hdy, hdt, sub_smul, id_smul]
    simp
  rw [d_sub, e1, e2, comp_smul]
  abel


end CatModule

end General


/-! ### Induction of lifted representable modules -/

section ULift

variable {C : Type u₁} [Category.{v₁} C] [Preadditive C] [∀ X Y : C, DGAddCommGroup (X ⟶ Y)]
  [DGCategory C] {D : Type u₂} [Category.{v₂} D] [Preadditive D]
  [∀ X Y : D, DGAddCommGroup (X ⟶ Y)] [DGCategory D] {F : C ⥤ D} [F.Additive] [F.IsDGFunctor]

theorem ULift.mem_coboundaries_iff {A : Type w} [AddCommGroup A] [DGAddCommGroup A] {n : ℤ}
    {a : ULift.{w'} A} : a ∈ coboundaries (ULift.{w'} A) n ↔ a.down ∈ coboundaries A n := by
  simp only [mem_coboundaries]
  constructor
  · rintro ⟨b, hb, rfl⟩
    exact ⟨b.down, hb, rfl⟩
  · rintro ⟨b, hb, hdb⟩
    exact ⟨ULift.up b, hb, ULift.ext _ _ hdb⟩

namespace CatTensorProduct

open DGOpposite CatModule

variable (N : CatModule.{w} (DGOpposite C))

theorem balanced_ridULift (X : C) :
    Balanced (M := ulift.{w'} (representable X))
      fun Y => (N.ract (X := X) (Y := Y)).flip.compl₂ (ULift.downAddHom (X ⟶ Y)) :=
  fun f n h => by
    change (n <• f) <• h.down = n <• (h.down ≫ f)
    rw [ract_comp]

/-- The co-Yoneda isomorphism `N ⊗_C C(X, -) ≅ N(X)` for the representable module lifted to a
larger universe, `n ⊗ h ↦ n • h`. -/
noncomputable def ridULift (X : C) :
    DGAddEquiv (CatTensorProduct N (ulift.{w'} (representable X))) (N.obj (op X)) :=
  DGAddEquiv.ofAddMonoidHom (lift _ (balanced_ridULift N X))
    ((tmulAddHom N (ulift.{w'} (representable X)) X).flip (ULift.up (𝟙 X)))
    (fun x => by
      induction x using induction_on with
      | zero => simp
      | tmul Y n h =>
        rw [lift_tmul, AddMonoidHom.flip_apply, tmulAddHom_apply]
        change tmul X (n <• h.down) (ULift.up (𝟙 X)) = tmul Y n h
        rw [ract_tmul]
        congr 1
        exact ULift.ext _ _ (Category.id_comp h.down)
      | add x y hx hy => rw [map_add, map_add, hx, hy])
    (fun n => by
      rw [AddMonoidHom.flip_apply, tmulAddHom_apply, lift_tmul]
      exact ract_id n)
    (fun hy => lift_mem _ (balanced_ridULift N X) (fun _ _ _ _ _ hn hh => by
      exact ract_mem_grading hn hh) hy)
    (lift_d _ (balanced_ridULift N X) fun _ _ _ hn h => d_ract hn h.down)

@[simp]
theorem ridULift_tmul (X Y : C) (n : N.obj (op Y)) (h : ULift.{w'} (X ⟶ Y)) :
    ridULift N X (tmul (M := ulift.{w'} (representable X)) Y n h) = n <• h.down :=
  lift_tmul _ (balanced_ridULift N X) Y n h

end CatTensorProduct

namespace CatModule

open CatBimodule

variable (F)

/-- Induction takes lifted representable modules to lifted representable modules:
`F_! C(X, -) ≅ D(F X, -)`, `h ⊗ k ↦ F k ≫ h`. -/
noncomputable def inductionULiftRepresentableIso (X : C) :
    inductionObj F (ulift.{w'} (representable X)) ≅
      ulift.{max u₁ v₁ w'} (representable (F.obj X)) :=
  isoMk (fun Y => (CatTensorProduct.ridULift ((ofFunctor F).right Y) X).toAddEquiv.trans
      AddEquiv.ulift.symm)
    (fun {Y n y} => ⟨fun h => by
      have := (CatTensorProduct.ridULift ((ofFunctor F).right Y) X).symm.map_mem h
      change (CatTensorProduct.ridULift ((ofFunctor F).right Y) X).symm
        ((CatTensorProduct.ridULift ((ofFunctor F).right Y) X) y) ∈ grading n at this
      rwa [DGAddEquiv.symm_apply_apply] at this,
      fun h => (CatTensorProduct.ridULift ((ofFunctor F).right Y) X).map_mem h⟩)
    (fun {Y} y => ULift.ext _ _ ((CatTensorProduct.ridULift ((ofFunctor F).right Y) X).map_d y))
    (fun {Y Y'} g y => ULift.ext _ _ (by
      change CatTensorProduct.ridULift _ X
          ((ofFunctor F).tensorAct (ulift.{w'} (representable X)) g y) =
        (CatTensorProduct.ridULift ((ofFunctor F).right Y) X y : F.obj X ⟶ Y) ≫ g
      induction y using CatTensorProduct.induction_on with
      | zero => rw [map_zero, map_zero, map_zero, Limits.zero_comp]
      | tmul X' h k =>
        rw [tensorAct_tmul, CatTensorProduct.ridULift_tmul, CatTensorProduct.ridULift_tmul,
          right_ract, right_ract, ofFunctor_ract, ofFunctor_ract, ofFunctor_lact, Category.assoc]
      | add x y hx hy => rw [map_add, map_add, hx, hy, map_add, Preadditive.add_comp]))

theorem inductionULiftRepresentableIso_hom_app_tmul (X : C) {Y : D} (X' : C)
    (h : F.obj X' ⟶ Y) (k : ULift.{w'} (X ⟶ X')) :
    ((inductionULiftRepresentableIso.{w'} F X).hom.app Y
      (CatTensorProduct.tmul (N := (ofFunctor F).right Y) X' h k)).down = F.map k.down ≫ h :=
  (CatTensorProduct.ridULift_tmul (N := (ofFunctor F).right Y) X X' h k).trans
    (right_ract _ _ _ _)

end CatModule

end ULift

/-! ### Keller's theorem -/

section Keller

variable {C : Type u₁} [Category.{v₁} C] [Preadditive C] [∀ X Y : C, DGAddCommGroup (X ⟶ Y)]
  [DGCategory C] {D : Type u₂} [Category.{v₂} D] [Preadditive D]
  [∀ X Y : D, DGAddCommGroup (X ⟶ Y)] [DGCategory D] {F : C ⥤ D} [F.Additive] [F.IsDGFunctor]

namespace CatModule

variable (F) in
/-- The morphism `C(X, -) ⟶ F^* D(F X, -)`, `h ↦ F h`, between lifted representable modules. -/
noncomputable def representableMapULift (X : C) :
    ulift.{max u₁ v₂ w} (representable X) ⟶
      (precomp F).obj (ulift.{max u₁ v₁ v₂ w} (representable (F.obj X))) where
  app _ := (ULift.upAddHom _).comp (F.mapAddHom.comp (ULift.downAddHom _))
  map_mem' hf := F.map_mem_grading hf
  map_d' f := ULift.ext _ _ (F.map_d f.down)
  map_smul' f h := ULift.ext _ _ (F.map_comp h.down f)

/-- For a quasi-fully faithful dg functor, `C(X, -) ⟶ F^* D(F X, -)` is a quasi-isomorphism. -/
theorem isQuasiIso_representableMapULift (hF : IsQuasiFullyFaithful F) (X : C) :
    IsQuasiIso (representableMapULift.{w} F X) := by
  intro X' n
  have hb := hF.bijective_cohomology X X' n
  rw [Function.Bijective, cohomology.mapAddMonoidHom_injective_iff,
    cohomology.mapAddMonoidHom_surjective_iff] at hb
  constructor
  · rw [cohomologyMap_injective_iff]
    intro x hx hdx hfx
    exact ULift.mem_coboundaries_iff.mpr (hb.1 x.down hx (congrArg ULift.down hdx)
      (ULift.mem_coboundaries_iff.mp hfx))
  · rw [cohomologyMap_surjective_iff]
    intro y hy hdy
    obtain ⟨x, hx, hdx, hxy⟩ := hb.2 y.down hy (congrArg ULift.down hdy)
    exact ⟨ULift.up x, hx, ULift.ext _ _ hdx, ULift.mem_coboundaries_iff.mpr hxy⟩

/-- On a representable module, the unit of `F_! ⊣ F^*` followed by the isomorphism
`F^* F_! C(X, -) ≅ F^* D(F X, -)` is `h ↦ F h`. -/
theorem unit_app_representable_comp (X : C) :
    (inductionAdjunction.{max v₁ w} F).unit.app (ulift.{max u₁ v₂ w} (representable X)) ≫
      (precomp F).map (inductionULiftRepresentableIso.{max u₁ v₂ w} F X).hom =
        representableMapULift.{w} F X := by
  refine ((isCornerGenerator_representable X).ulift.{max u₁ v₂ w}).ext_hom ?_
  refine ULift.ext _ _ ?_
  change ((inductionULiftRepresentableIso.{max u₁ v₂ w} F X).hom.app (F.obj X)
      (CatTensorProduct.tmul (N := (CatBimodule.ofFunctor F).right (F.obj X)) X (𝟙 (F.obj X))
        (ULift.up (𝟙 X)))).down = F.map (𝟙 X)
  rw [inductionULiftRepresentableIso_hom_app_tmul, F.map_id, Category.id_comp]

/-- For a quasi-fully faithful dg functor, the unit of `F_! ⊣ F^*` is a quasi-isomorphism on the
(lifted) representable modules. -/
theorem isQuasiIso_unit_app_representable (hF : IsQuasiFullyFaithful F) (X : C) :
    IsQuasiIso ((inductionAdjunction.{max v₁ w} F).unit.app
      (ulift.{max u₁ v₂ w} (representable X))) := by
  have h := isQuasiIso_representableMapULift.{w} hF X
  rw [← unit_app_representable_comp] at h
  have e : ((inductionAdjunction.{max v₁ w} F).unit.app (ulift.{max u₁ v₂ w} (representable X)) ≫
      (precomp F).map (inductionULiftRepresentableIso.{max u₁ v₂ w} F X).hom) ≫
        (precomp F).map (inductionULiftRepresentableIso.{max u₁ v₂ w} F X).inv =
      (inductionAdjunction.{max v₁ w} F).unit.app (ulift.{max u₁ v₂ w} (representable X)) := by
    rw [Category.assoc, ← Functor.map_comp, Iso.hom_inv_id, CategoryTheory.Functor.map_id]
    exact Category.comp_id _
  rw [← e]
  exact h.comp (IsQuasiIso.of_isIso _)

/-! #### Restriction preserves coproducts -/

variable (F)

omit [DGCategory C] [DGCategory D] in
/-- Restriction commutes with direct sums. -/
noncomputable def precompDirectSumIso {J : Type max u₁ v₁ v₂ w} [DecidableEq J]
    (N : J → CatModule.{max u₁ v₁ v₂ w} D) :
    (precomp F).obj (directSum N) ≅ directSum fun j => (precomp F).obj (N j) :=
  isoMk (fun _ => AddEquiv.refl _) (fun {_ _ _} => Iff.rfl) (fun _ => rfl) (fun _ _ => rfl)

omit [DGCategory C] [DGCategory D] in
/-- Restriction of dg modules preserves coproducts. -/
instance precomp_preservesCoproducts (J : Type max u₁ v₁ v₂ w) :
    PreservesColimitsOfShape (Discrete J) (precomp.{max u₁ v₁ v₂ w} F) := by
  suffices ∀ N : J → CatModule.{max u₁ v₁ v₂ w} D,
      PreservesColimit (Discrete.functor N) (precomp F) from
    preservesColimitsOfShape_of_discrete _
  intro N
  classical
  refine preservesColimit_of_preserves_colimit_cocone
    (coproductCoconeIsColimit.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} N) ?_
  refine (isColimitMapCoconeCofanMkEquiv _ _ _).symm ?_
  refine IsColimit.ofIsoColimit
    (coproductCoconeIsColimit.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} fun j => (precomp F).obj (N j))
    (Cocone.ext (precompDirectSumIso F N).symm fun j => ?_)
  exact hom_ext fun _ _ => rfl

end CatModule

namespace CatModule.DerivedCategory

variable [HasDerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C]
  [HasDerivedCategory.{w₂, max u₁ v₁ v₂ w} D]

variable (F) in
/-- Restriction on derived categories preserves coproducts. -/
instance restrict_preservesCoproducts (J : Type max u₁ v₁ v₂ w) :
    PreservesColimitsOfShape (Discrete J)
      (restrict F : DerivedCategory.{w₂, max u₁ v₁ v₂ w} D ⥤
        DerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C) := by
  suffices ∀ Y : J → DerivedCategory.{w₂, max u₁ v₁ v₂ w} D,
      PreservesColimit (Discrete.functor Y) (restrict F) from
    preservesColimitsOfShape_of_discrete _
  intro Y
  classical
  choose N e using fun j => exists_iso_Q_obj (Y j)
  suffices PreservesColimit (Discrete.functor N ⋙ Q) (restrict F) from
    preservesColimit_of_iso_diagram _
      (Discrete.natIso fun j => (e j.as).some.symm : Discrete.functor N ⋙ Q ≅ Discrete.functor Y)
  have : PreservesColimit (Discrete.functor N) (Q ⋙ restrict F) :=
    preservesColimit_of_natIso _ (QCompRestrictIso F).symm
  exact preservesColimit_of_preserves_colimit_cocone
    (isColimitOfPreserves Q (coproductCoconeIsColimit.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} N))
    (isColimitOfPreserves (Q ⋙ restrict F)
      (coproductCoconeIsColimit.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} N))

variable (F) in
/-- The objects at which the unit is an isomorphism form a localizing subcategory of `D(C)`. -/
theorem isLocalizing_unitIsIso : IsLocalizing.{max u₁ v₁ v₂ w}
    (fun X : DerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C =>
    IsIso ((inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).unit.app X)) where
  of_iso {X Y} e hY := by
    have : IsIso ((inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).unit.app Y) := hY
    have h := (inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).unit.naturality e.hom
    simp only [Functor.id_map] at h
    have h' : (inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).unit.app X =
        e.hom ≫ (inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).unit.app Y ≫
          (induction F ⋙ restrict F).map e.inv := by
      rw [reassoc_of% h]
      simp [← Functor.map_comp]
    change IsIso _
    rw [h']
    infer_instance
  shift X n hX := by
    have : IsIso ((inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).unit.app X) := hX
    change IsIso _
    rw [NatTrans.app_shift (inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).unit n X]
    infer_instance
  ext₂ T hT h₁ h₃ := by
    let adj := inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F
    have hT' := (induction F ⋙ restrict F).map_distinguished T hT
    refine isIso₂_of_isIso₁₃ (T' := (induction F ⋙ restrict F).mapTriangle.obj T)
      (Triangle.homMk _ _ (adj.unit.app _) (adj.unit.app _) (adj.unit.app _)
        (adj.unit.naturality _) (adj.unit.naturality _) ?_) hT hT' h₁ h₃
    have h0 := NatTrans.shift_app_comm adj.unit (1 : ℤ) T.obj₁
    simp only [Functor.commShiftIso_id_hom_app] at h0
    have h1 : (adj.unit.app T.obj₁)⟦(1 : ℤ)⟧' = adj.unit.app (T.obj₁⟦(1 : ℤ)⟧) ≫
        ((induction F ⋙ restrict F).commShiftIso (1 : ℤ)).hom.app T.obj₁ :=
      (Category.id_comp _).symm.trans h0
    dsimp [Functor.mapTriangle]
    rw [h1, ← Category.assoc, ← Category.assoc]
    congr 1
    exact adj.unit.naturality T.mor₃
  coproduct {J Y} c hc hY := by
    let adj := inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F
    have : ∀ j, IsIso (adj.unit.app (Y j)) := hY
    have := adj.leftAdjoint_preservesColimits
    have hc' : IsColimit ((induction F ⋙ restrict F).mapCocone c) :=
      isColimitOfPreserves (induction F ⋙ restrict F) hc
    let w : Discrete.functor Y ≅ Discrete.functor Y ⋙ (induction F ⋙ restrict F) :=
      NatIso.ofComponents (fun j => asIso (adj.unit.app (Y j.as)))
        (fun f => adj.unit.naturality ((Discrete.functor Y).map f))
    have key : (hc.coconePointsIsoOfNatIso hc' w).hom = adj.unit.app c.pt := by
      refine hc.hom_ext fun j => ?_
      rw [IsColimit.comp_coconePointsIsoOfNatIso_hom]
      exact (adj.unit.naturality (c.ι.app j)).symm
    change IsIso _
    rw [← key]
    infer_instance

/-- For a quasi-fully faithful dg functor, the unit is an isomorphism at the representable
modules. -/
theorem isIso_unit_app_representable (hF : IsQuasiFullyFaithful F) (X : C) :
    IsIso ((inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).unit.app
      (Q.obj (representableW.{max v₂ w} C X))) := by
  have hR := (isCornerGenerator_representableW.{max v₂ w} X).isKProjective
  rw [← unitMap_comp_inductionObjIsoHom F hR]
  have : IsIso (Q.map ((CatModule.inductionAdjunction.{max v₁ w} F).unit.app
      (ulift.{max u₁ v₂ w} (representable X)))) :=
    (isIso_Q_map_iff _).mpr (isQuasiIso_unit_app_representable hF X)
  have : IsIso (inductionObjIsoHom F hR) :=
    (inductionObjIso F _).isIso_hom
  dsimp only [unitMap]
  infer_instance

/-- For a quasi-fully faithful dg functor `F`, the unit `X ⟶ F^* LF_! X` is an isomorphism. -/
theorem isIso_unit_app_of_isQuasiFullyFaithful (hF : IsQuasiFullyFaithful F)
    (X : DerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C) :
    IsIso ((inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).unit.app X) :=
  (compactlyGenerates.{max v₂ w} (C := C)).forall_of_isLocalizing (isLocalizing_unitIsIso F)
    (isIso_unit_app_representable hF) X

/-- For a quasi-equivalence `F`, the unit `X ⟶ F^* LF_! X` is an isomorphism. -/
theorem isIso_unit_app (hF : IsQuasiEquivalence F)
    (X : DerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C) :
    IsIso ((inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).unit.app X) :=
  isIso_unit_app_of_isQuasiFullyFaithful hF.toIsQuasiFullyFaithful X

/-- If restriction of dg modules along `F` reflects acyclicity, then restriction on derived
categories reflects zero objects. -/
theorem isZero_of_isZero_restrict_of_reflects
    (hR : ∀ N : CatModule.{max u₁ v₁ v₂ w} D, IsAcyclic ((precomp F).obj N) → IsAcyclic N)
    {Z : DerivedCategory.{w₂, max u₁ v₁ v₂ w} D}
    (h : IsZero ((restrict F).obj Z : DerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C)) :
    IsZero Z := by
  obtain ⟨N, ⟨e⟩⟩ := exists_iso_Q_obj Z
  refine IsZero.of_iso ?_ e
  rw [isZero_Q_obj_iff]
  refine hR N ?_
  rw [← isZero_Q_obj_iff (C := C)]
  exact IsZero.of_iso h (((QCompRestrictIso F).app N).symm ≪≫ (restrict F).mapIso e.symm)

/-- Restriction along a quasi-equivalence reflects zero objects. -/
theorem isZero_of_isZero_restrict (hF : IsQuasiEquivalence F)
    {Z : DerivedCategory.{w₂, max u₁ v₁ v₂ w} D}
    (h : IsZero ((restrict F).obj Z : DerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C)) :
    IsZero Z :=
  isZero_of_isZero_restrict_of_reflects (fun _ => isAcyclic_of_isAcyclic_precomp hF) h

/-- For a quasi-fully faithful dg functor `F` such that restriction along `F` reflects
acyclicity, the counit `LF_! F^* Y ⟶ Y` is an isomorphism. -/
theorem isIso_counit_app_of_reflects (hF : IsQuasiFullyFaithful F)
    (hR : ∀ N : CatModule.{max u₁ v₁ v₂ w} D, IsAcyclic ((precomp F).obj N) → IsAcyclic N)
    (Y : DerivedCategory.{w₂, max u₁ v₁ v₂ w} D) :
    IsIso ((inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).counit.app Y) := by
  let adj := inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F
  have : IsIso (adj.unit.app ((restrict F).obj Y)) :=
    isIso_unit_app_of_isQuasiFullyFaithful hF _
  have h1 : IsIso ((restrict F).map (adj.counit.app Y)) := by
    rw [IsIso.eq_inv_of_hom_inv_id (adj.right_triangle_components Y)]
    infer_instance
  obtain ⟨Z, g, h, hT⟩ := distinguished_cocone_triangle (adj.counit.app Y)
  have hRT := (restrict F).map_distinguished _ hT
  have hZ : IsZero Z :=
    isZero_of_isZero_restrict_of_reflects hR ((Triangle.isZero₃_iff_isIso₁ _ hRT).mpr h1)
  exact (Triangle.isZero₃_iff_isIso₁ _ hT).mp hZ

/-- For a quasi-equivalence `F`, the counit `LF_! F^* Y ⟶ Y` is an isomorphism. -/
theorem isIso_counit_app (hF : IsQuasiEquivalence F) (Y : DerivedCategory.{w₂, max u₁ v₁ v₂ w} D) :
    IsIso ((inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).counit.app Y) :=
  isIso_counit_app_of_reflects hF.toIsQuasiFullyFaithful
    (fun _ => isAcyclic_of_isAcyclic_precomp hF) Y

/-- A quasi-fully faithful dg functor `F : C ⥤ D` such that restriction of dg modules along `F`
reflects acyclicity induces an equivalence of derived categories `LF_! : D(C) ≌ D(D)`, with
quasi-inverse the restriction `F^*`. Both functors are triangulated. -/
noncomputable def inductionEquivalence (hF : IsQuasiFullyFaithful F)
    (hR : ∀ N : CatModule.{max u₁ v₁ v₂ w} D, IsAcyclic ((precomp F).obj N) → IsAcyclic N) :
    DerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C ≌ DerivedCategory.{w₂, max u₁ v₁ v₂ w} D :=
  have : ∀ X, IsIso ((inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).unit.app X) :=
    isIso_unit_app_of_isQuasiFullyFaithful hF
  have : ∀ Y,
      IsIso ((inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).counit.app Y) :=
    isIso_counit_app_of_reflects hF hR
  (inductionAdjunction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).toEquivalence

@[simp]
theorem inductionEquivalence_functor (hF : IsQuasiFullyFaithful F)
    (hR : ∀ N : CatModule.{max u₁ v₁ v₂ w} D, IsAcyclic ((precomp F).obj N) → IsAcyclic N) :
    (inductionEquivalence hF hR :
      DerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C ≌
        DerivedCategory.{w₂, max u₁ v₁ v₂ w} D).functor =
      induction F :=
  rfl

@[simp]
theorem inductionEquivalence_inverse (hF : IsQuasiFullyFaithful F)
    (hR : ∀ N : CatModule.{max u₁ v₁ v₂ w} D, IsAcyclic ((precomp F).obj N) → IsAcyclic N) :
    (inductionEquivalence hF hR :
      DerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C ≌
        DerivedCategory.{w₂, max u₁ v₁ v₂ w} D).inverse =
      restrict F :=
  rfl

/-- **Keller's theorem** [Keller, *Deriving DG categories*, §9.1]: a quasi-equivalence of dg
categories `F : C ⥤ D` induces an equivalence of derived categories `LF_! : D(C) ≌ D(D)`, with
quasi-inverse the restriction `F^*`. Both functors are triangulated. -/
noncomputable def kellerEquivalence (hF : IsQuasiEquivalence F) :
    DerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C ≌ DerivedCategory.{w₂, max u₁ v₁ v₂ w} D :=
  inductionEquivalence hF.toIsQuasiFullyFaithful (fun _ => isAcyclic_of_isAcyclic_precomp hF)

@[simp]
theorem kellerEquivalence_functor (hF : IsQuasiEquivalence F) :
    (kellerEquivalence hF :
      DerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C ≌
        DerivedCategory.{w₂, max u₁ v₁ v₂ w} D).functor =
      induction F :=
  rfl

@[simp]
theorem kellerEquivalence_inverse (hF : IsQuasiEquivalence F) :
    (kellerEquivalence hF :
      DerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C ≌
        DerivedCategory.{w₂, max u₁ v₁ v₂ w} D).inverse =
      restrict F :=
  rfl

/-- For a quasi-equivalence, derived induction is an equivalence. -/
theorem induction_isEquivalence (hF : IsQuasiEquivalence F) :
    (induction.{max u₁ v₁ v₂ w, w₂, w, v₁, v₂, u₁, u₂} F).IsEquivalence :=
  (kellerEquivalence hF :
    DerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C ≌
      DerivedCategory.{w₂, max u₁ v₁ v₂ w} D).isEquivalence_functor

/-- For a quasi-equivalence, restriction on derived categories is an equivalence. -/
theorem restrict_isEquivalence (hF : IsQuasiEquivalence F) :
    (restrict F : DerivedCategory.{w₂, max u₁ v₁ v₂ w} D ⥤
      DerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C).IsEquivalence :=
  (kellerEquivalence hF :
    DerivedCategory.{max u₁ v₁ v₂ w, max u₁ v₁ v₂ w} C ≌
      DerivedCategory.{w₂, max u₁ v₁ v₂ w} D).isEquivalence_inverse

end CatModule.DerivedCategory

end Keller

/-! ### Dg rings -/

section DGRing

variable {A : Type u₂} [Ring A] [DGAddCommGroup A] [DGRing A] {B : Type u₁} [Ring B]
  [DGAddCommGroup B] [DGRing B]

namespace DGRingHom

variable (φ : B →ᵈᵍ+* A)

/-- The dg functor `SingleObj B ⥤ SingleObj A` induced by a morphism of dg rings. -/
def singleObjFunctor : SingleObj B ⥤ SingleObj A :=
  SingleObj.mapHom B A φ.toRingHom.toMonoidHom

instance : φ.singleObjFunctor.Additive where
  map_add {_ _ f g} := map_add φ f g

instance : φ.singleObjFunctor.IsDGFunctor where
  map_mem' hf := φ.map_mem hf
  map_d' f := φ.map_d f

omit [DGRing B] in
/-- A quasi-isomorphism of dg rings induces a quasi-equivalence of one-object dg categories. -/
theorem isQuasiEquivalence_singleObjFunctor (hφ : φ.IsQuasiIso) :
    IsQuasiEquivalence φ.singleObjFunctor where
  bijective_cohomology _ _ n := hφ n
  exists_iso Y := ⟨SingleObj.star B, (1 : A), (1 : A),
    mem_cocycles.mpr ⟨one_mem_grading, d_one⟩, mem_cocycles.mpr ⟨one_mem_grading, d_one⟩,
    by rw [show ((1 : A) : SingleObj.star A ⟶ Y) ≫ ((1 : A) : Y ⟶ SingleObj.star A) -
      𝟙 (φ.singleObjFunctor.obj (SingleObj.star B)) = (1 * 1 - 1 : A) from rfl, mul_one,
      sub_self]; exact zero_mem _,
    by rw [show ((1 : A) : Y ⟶ SingleObj.star A) ≫ ((1 : A) : SingleObj.star A ⟶ Y) - 𝟙 Y =
      (1 * 1 - 1 : A) from rfl, mul_one, sub_self]; exact zero_mem _⟩

/-- **Keller's theorem for dg rings** [Keller, *Deriving DG categories*, Ex. 6.1],
[Bernstein–Lunts, 10.12.5.1]: a quasi-isomorphism of dg rings `φ : B → A` induces an
equivalence of derived categories `D(B) ≌ D(A)`, obtained from the equivalences
`D(SingleObj B) ≌ D(SingleObj A)` (derived induction along `φ`) and `D(SingleObj A) ≌ D(A)`. -/
noncomputable def derivedEquivalence (hφ : φ.IsQuasiIso)
    [DG.HasDerivedCategory.{w₁, max u₁ u₂ w} B] [DG.HasDerivedCategory.{w₂, max u₁ u₂ w} A] :
    DG.DerivedCategory B ≌ DG.DerivedCategory A :=
  letI := CatModule.HasDerivedCategory.small.{max u₂ w} (SingleObj B)
  letI := CatModule.HasDerivedCategory.small.{max u₁ w} (SingleObj A)
  (CatModule.DerivedCategory.singleObjEquivalence B).symm.trans
    ((CatModule.DerivedCategory.kellerEquivalence
      (φ.isQuasiEquivalence_singleObjFunctor hφ)).trans
      (CatModule.DerivedCategory.singleObjEquivalence A))

end DGRingHom

end DGRing

end DG
