import DG.HalfGraded.Field
import DG.HalfGraded.Hom
import DG.HalfGraded.InternalZero
import DG.K0.ShiftedObjects
import DG.Bigraded.K0Basis
import DG.Positive.Category

/-!
# Positive half-graded dg rings

Let `H` be a half-graded dg ring with parameter `k > 0`: a ring `A = ⨁ (j, ε), A^{j,ε}` graded by
an internal degree `j : ℤ` and a parity `ε : ℤ/2`, with a differential of bidegree `(k, 1̄)`.
`H` is *positive* (`DG.HalfGradedDGRing.IsPositive`) if

* `A^{j,ε} = 0` for `j < 0` and for `0 < j < k`;
* the part `A^{0,•} = A^{0,0̄} ⊕ A^{0,1̄}` of internal degree `0`
  (`DG.HalfGradedDGRing.internalZeroSubring`) is a graded semisimple `ℤ/2`-graded ring
  (`DG.IsGradedSemisimpleRing`: every graded `A^{0,•}`-module is a direct sum of graded simple
  modules; equivalently `1` is a sum of orthogonal even idempotents `e` with `A^{0,•} e` graded
  simple);
* the differential vanishes on `A^{0,•}`.

This is the analogue of Schnürer's positivity [Sch, §1, (P1)–(P3)] for a differential of internal
degree `k`: the internal degree is non-negative, takes no values strictly between `0` and `k`, and
the part of internal degree `0` is semisimple as a superring. Examples are the simple
superalgebras `M(m|n)` and `Q(n)` placed in internal degree `0`
(`DG/HalfGraded/PositiveSuper.lean`).
The special case `A^{0,1̄} = 0`, `A^{0,0̄}` a semisimple ring, is
`DG.HalfGradedDGRing.IsPositive.of_isSemisimpleRing`.

## The positive model

Half-graded dg modules are dg modules over the weight dg category `C_H` of the regraded ring
(`DG/HalfGraded/Basic.lean`), `C_H(w, w')ⁿ = A^{w' - w + n k, n}`. This dg category is not
positive: the periodicity unit is an invertible morphism `w ⟶ w - 2k` of degree `2`. But the dg
category of the formal shifts `w[-⌊w / k⌋]` of its objects
(`DG.HalfGradedDGRing.PositiveModel H`, a `DG.ShiftedObjects`) has

  `P(w, w')ⁿ = A^{(w' mod k) - (w mod k) + n k, n + ⌊w / k⌋ - ⌊w' / k⌋}`,

which vanishes for `n < 0`, and for `n = 0` is `A^{0,ε}` with `ε = ⌊w / k⌋ - ⌊w' / k⌋ mod 2` if
`w ≡ w' (mod k)` and `0` otherwise: on each residue class modulo `k`, the degree-`0` category of
`P` is equivalent to the full subcategory of graded `A^{0,•}`-modules on `A^{0,•}` and its parity
shift, which is semisimple when `A^{0,•}` is graded semisimple. Hence `P` is a positive dg category
(`DG.HalfGradedDGRing.IsPositive.isPositive_positiveModel`), and by Schnürer's theorem for
positive dg categories and the invariance of `K₀` under formal shifts
(`DG.ShiftedObjects.closure_cell_eq_top_of_isPositive`), `K₀(C_H) = K₀(D^c(C_H))` is generated by
the classes of the modules `e · C_H(w, -)` for the idempotents `e` of `A^{0,0̄}`
(`DG.HalfGradedDGRing.IsPositive.closure_cell_eq_top`).

## `K₀(A) ≅ K₀(A^{0,•})`

The ring `A^{0,•}` is a half-graded dg ring concentrated in internal degree `0`, with zero
differential (`DG.HalfGradedDGRing.internalZeroPart`), and the inclusion `A^{0,•} → A` and the
projection `A → A^{0,•}` (`a ↦ a_{0,0̄} + a_{0,1̄}`) are morphisms of half-graded dg rings
(`DG.HalfGradedDGRing.IsPositive.incl`, `DG.HalfGradedDGRing.IsPositive.proj`). They induce
mutually inverse isomorphisms

  `DG.HalfGradedDGRing.IsPositive.K0DegreeZeroEquiv : K₀(C_H) ≃ₗ[ℤ[q, q⁻¹]] K₀(C_{H^{0,•}})`

of `ℤ[q, q⁻¹]`-modules (`qⁿ` acting by the internal shift `⟨n⟩`), sending the class of
`e · C_H(w, -)` to that of `e · C_{H^{0,•}}(w, -)`, and an isomorphism of the super Grothendieck
groups (`DG.HalfGradedDGRing.IsPositive.superK0cDegreeZeroEquiv`). More generally, any retraction
`p : H → H'` of a morphism `i : H' → H` such that `i ∘ p` is the identity on `A^{0,0̄}` induces an
isomorphism on `K₀` (`DG.HalfGradedDGRing.IsPositive.K0EquivOfRetract`). When `A^{0,1̄} = 0` this
applies to `A⁰ = A^{0,0̄}` (`DG.HalfGradedDGRing.degreeZeroPart`), giving
`DG.HalfGradedDGRing.IsPositive.K0DegreeZeroEvenEquiv : K₀(C_H) ≃ₗ[ℤ[q, q⁻¹]] K₀(C_{A⁰})`.

## References

* [Sch] O. M. Schnürer, *Perfect derived categories of positively graded DG algebras*,
  Appl. Categ. Structures 19 (2011), 757–782; arXiv:0809.4782v2.
-/

open CategoryTheory DirectSum

universe w u

noncomputable section

namespace DG

namespace HalfGradedDGRing

variable {A : Type u} [Ring A] {k : ℤ} (H : HalfGradedDGRing A k)

/-! ### Bihomogeneous elements of the regraded ring -/

variable {H} in
/-- An element of the regraded ring of cohomological degree `n` and weight `w` is an element of
`A^{w + n k, n}` placed in bidegree `(n, w)`. -/
theorem exists_eq_place {x : H.Regraded} {n w : ℤ} (hn : x ∈ grading n) (hw : x ∈ wgrading w) :
    ∃ (a : A) (ha : a ∈ H.hgrading (halfDegree k (n, w))), x = H.place (n, w) a ha := by
  let y : ⨁ p : ℤ × ℤ, ↥(halfGrading H.hgrading k p) := x
  refine ⟨(y (n, w) : A), (y (n, w)).2, ?_⟩
  have hsupp : ∀ p, p ≠ (n, w) → y p = 0 := fun p hp => by
    by_cases h1 : p.1 = n
    · exact hw p (fun h2 => hp (Prod.ext h1 h2))
    · exact hn p h1
  change y = DirectSum.of _ (n, w) (y (n, w))
  ext p : 1
  by_cases hp : p = (n, w)
  · subst hp; rw [DirectSum.of_eq_same]
  · rw [hsupp p hp, DirectSum.of_eq_of_ne _ _ _ hp]

variable {H} in
theorem place_injective {p : ℤ × ℤ} {a a' : A} {ha : a ∈ H.hgrading (halfDegree k p)}
    {ha' : a' ∈ H.hgrading (halfDegree k p)} (h : H.place p a ha = H.place p a' ha') : a = a' :=
  congrArg Subtype.val (DirectSum.of_injective (β := fun p => ↥(halfGrading H.hgrading k p)) p
    (a₁ := ⟨a, ha⟩) (a₂ := ⟨a', ha'⟩) h)

/-! ### The ring `A⁰ = A^{0,0̄}` -/

/-- The subring `A⁰ = A^{0,0̄}` of a half-graded dg ring. -/
def zeroSubring : Subring A := SetLike.GradeZero.subring H.hgrading

variable {H} in
theorem mem_zeroSubring {a : A} : a ∈ H.zeroSubring ↔ a ∈ H.hgrading 0 :=
  Iff.rfl

/-- The ring `A⁰ = A^{0,0̄}`, as a half-graded dg ring concentrated in bidegree `(0, 0̄)` with zero
differential. -/
abbrev degreeZeroPart : HalfGradedDGRing H.zeroSubring k :=
  degreeZero H.zeroSubring k

/-- An element of `A⁰ = A^{0,0̄}`, as an endomorphism of degree `0` of an object of the weight dg
category `C_H`. -/
def zeroHom (X : WeightCategory H.Regraded) : H.zeroSubring →+ (X ⟶ X) where
  toFun s := ⟨H.place 0 s (by rw [map_zero]; exact mem_zeroSubring.mp s.2), by
    rw [sub_self]; exact place_mem_wgrading (H := H) 0 _⟩
  map_zero' := WeightCategory.hom_ext ((place_congr rfl rfl _ (zero_mem _)).trans (place_zero _))
  map_add' _ _ := WeightCategory.hom_ext (place_add _ _ _)

variable {H}

theorem zeroHom_val (X : WeightCategory H.Regraded) (s : H.zeroSubring) :
    (H.zeroHom X s).1 = H.place 0 s (by rw [map_zero]; exact mem_zeroSubring.mp s.2) :=
  rfl

theorem zeroHom_mem_grading (X : WeightCategory H.Regraded) (s : H.zeroSubring) :
    H.zeroHom X s ∈ grading 0 :=
  place_mem_grading (H := H) 0 _

theorem zeroHom_comp (X : WeightCategory H.Regraded) (s t : H.zeroSubring) :
    H.zeroHom X s ≫ H.zeroHom X t = H.zeroHom X (t * s) :=
  WeightCategory.hom_ext (by
    rw [WeightCategory.comp_val, zeroHom_val, zeroHom_val, zeroHom_val, place_mul_place]
    exact place_congr (add_zero 0) rfl _ _)

theorem zeroHom_one (X : WeightCategory H.Regraded) : H.zeroHom X 1 = 𝟙 X :=
  WeightCategory.hom_ext rfl

theorem zeroHom_injective (X : WeightCategory H.Regraded) :
    Function.Injective (H.zeroHom X) := by
  intro s t h
  exact Subtype.ext (place_injective (congrArg Subtype.val h))

/-! ### The projection onto `A^{0,•}` -/

variable (H) in
/-- The projection `a ↦ a_{0,0̄} + a_{0,1̄}` of `A` onto its part `A^{0,•}` of internal degree
`0`, as an additive map `A → A`. -/
def internalZeroProj : A →+ A where
  toFun a := ∑ ε : ZMod 2, (decompose H.hgrading a (0, ε) : A)
  map_zero' := by simp
  map_add' a b := by simp [Finset.sum_add_distrib]

theorem internalZeroProj_apply (a : A) :
    H.internalZeroProj a = ∑ ε : ZMod 2, (decompose H.hgrading a (0, ε) : A) :=
  rfl

/-- The projection onto `A^{0,•}` is the identity on `A^{0,ε}` and vanishes on `A^{j,ε}` for
`j ≠ 0`. -/
theorem internalZeroProj_of_mem {p : ℤ × ZMod 2} {a : A} (ha : a ∈ H.hgrading p) :
    H.internalZeroProj a = if p.1 = 0 then a else 0 := by
  obtain ⟨j, ε₀⟩ := p
  rw [internalZeroProj_apply]
  split_ifs with hj
  · change j = 0 at hj
    subst hj
    rw [Finset.sum_eq_single ε₀ (fun ε _ hε => decompose_of_mem_ne _ ha
        (fun h => hε (congrArg Prod.snd h).symm)) (fun h => absurd (Finset.mem_univ ε₀) h),
      decompose_of_mem_same _ ha]
  · exact Finset.sum_eq_zero fun ε _ => decompose_of_mem_ne _ ha
      (fun h => hj (congrArg Prod.fst h))

theorem internalZeroProj_mem (a : A) : H.internalZeroProj a ∈ H.internalZeroSubring := by
  rw [internalZeroProj_apply]
  exact sum_mem fun _ _ => mem_internalZeroSubring_of_mem (SetLike.coe_mem _)

theorem internalZeroProj_of_mem_internalZeroSubring {a : A} (ha : a ∈ H.internalZeroSubring) :
    H.internalZeroProj a = a :=
  internalZeroSubring_induction (P := fun a => H.internalZeroProj a = a)
    (fun ha' => (internalZeroProj_of_mem ha').trans (ite_eq_left rfl))
    (fun a b ha hb => by rw [map_add, ha, hb]) ha

/-! ### Retractions onto subrings containing `A^{0,0̄}` -/

section Retract

variable {A' : Type u} [Ring A'] {H' : HalfGradedDGRing A' k} (i : Hom H' H) (p : Hom H H')
  (hip : ∀ {a : A}, a ∈ H.hgrading 0 → i (p a) = a)
include hip

/-- If `i ∘ p` is the identity on `A^{0,0̄}`, it is the identity on bihomogeneous elements of the
regraded ring of cohomological degree `0` and weight `0`. -/
theorem regraded_regraded_of_retract {x : H.Regraded} (hx : x ∈ grading 0)
    (hw : x ∈ wgrading 0) : i.regraded (p.regraded x) = x := by
  obtain ⟨a, ha, rfl⟩ := exists_eq_place hx hw
  have h0 : halfDegree k ((0 : ℤ), (0 : ℤ)) = 0 := map_zero (halfDegree k)
  have ha0 : a ∈ H.hgrading 0 := by
    rw [← h0]
    exact ha
  rw [Hom.regraded_place, Hom.regraded_place]
  exact place_congr rfl (hip ha0) _ _

/-- A degree-`0` idempotent cocycle of an object of `C_H` is fixed by `C_H ⥤ C_{H'} ⥤ C_H`. -/
theorem map_map_of_retract {X : WeightCategory H.Regraded} (e : DGCategory.Idempotent X) :
    (e.map p.weightFunctor).map i.weightFunctor = e :=
  WeightCategory.idempotent_ext (regraded_regraded_of_retract i p hip (x := e.val.1)
    (WeightCategory.mem_grading_iff.mp e.mem_grading)
    (WeightCategory.mem_wgrading_of_eq (sub_self _) e.val.2))

end Retract

/-! ### Positivity -/

variable (H) in
/-- A half-graded dg ring with parameter `k` is *positive* if `k > 0`, `A^{j,ε} = 0` for `j < 0`
and for `0 < j < k`, the part `A^{0,•} = A^{0,0̄} ⊕ A^{0,1̄}` of internal degree `0` is a graded
semisimple ring (for its `ℤ/2`-grading by parity; `DG.IsGradedSemisimpleRing`), and the
differential vanishes on `A^{0,•}`. -/
structure IsPositive : Prop where
  /-- The internal degree of the differential is positive. -/
  pos : 0 < k
  /-- `A^{j,ε} = 0` for `j < k` and `j ≠ 0`. -/
  eq_zero_of_lt : ∀ {j : ℤ} {ε : ZMod 2} {a : A}, j < k → j ≠ 0 → a ∈ H.hgrading (j, ε) → a = 0
  /-- `A^{0,•}` is a graded semisimple ring. -/
  isGradedSemisimple : IsGradedSemisimpleRing H.internalZeroGrading
  /-- The differential vanishes on `A^{0,•}`. -/
  hd_eq_zero : ∀ {ε : ZMod 2} {a : A}, a ∈ H.hgrading (0, ε) → H.hd a = 0

/-- The positivity conditions with `A^{0,1̄} = 0`: if `k > 0`, `A^{j,ε} = 0` for `j < k` unless
`(j, ε) = (0, 0̄)`, the ring `A^{0,0̄}` is semisimple, and the differential vanishes on
`A^{0,0̄}`, then `H` is positive. -/
theorem IsPositive.of_isSemisimpleRing (pos : 0 < k)
    (eq_zero_of_lt : ∀ {j : ℤ} {ε : ZMod 2} {a : A}, j < k → (j, ε) ≠ 0 →
      a ∈ H.hgrading (j, ε) → a = 0)
    (isSemisimple : IsSemisimpleRing H.zeroSubring)
    (hd_eq_zero : ∀ {a : A}, a ∈ H.hgrading 0 → H.hd a = 0) : H.IsPositive where
  pos := pos
  eq_zero_of_lt hj hj0 ha := eq_zero_of_lt hj (fun h => hj0 (congrArg Prod.fst h)) ha
  isGradedSemisimple := isGradedSemisimpleRing_internalZeroGrading_of_odd
    (fun _ ha => eq_zero_of_lt pos (fun h => one_ne_zero (congrArg Prod.snd h)) ha) isSemisimple
  hd_eq_zero {ε} {a} ha := by
    rcases HalfGradedDGRing.zmod_two_cases ε with rfl | rfl
    · exact hd_eq_zero ha
    · rw [eq_zero_of_lt pos (fun h => one_ne_zero (congrArg Prod.snd h)) ha, map_zero]

namespace IsPositive

variable (hH : H.IsPositive)
include hH

theorem hd_eq_zero_of_mem_zero {a : A} (ha : a ∈ H.hgrading 0) : H.hd a = 0 :=
  hH.hd_eq_zero (ε := 0) ha

/-- The differential vanishes on `A^{0,•}`. -/
theorem hd_eq_zero_of_mem_internalZeroSubring {a : A} (ha : a ∈ H.internalZeroSubring) :
    H.hd a = 0 :=
  internalZeroSubring_induction (P := fun a => H.hd a = 0) (fun ha' => hH.hd_eq_zero ha')
    (fun a b ha hb => by rw [map_add, ha, hb, add_zero]) ha

theorem d_zeroHom (X : WeightCategory H.Regraded) (s : H.zeroSubring) :
    d (H.zeroHom X s) = 0 :=
  WeightCategory.hom_ext (by
    rw [WeightCategory.d_val, zeroHom_val, d_place]
    exact (place_congr rfl (hH.hd_eq_zero_of_mem_zero (mem_zeroSubring.mp s.2)) _ _).trans
      (place_zero _))

/-- An idempotent `s` of `A^{0,0̄}`, as a degree-`0` idempotent cocycle of an object of `C_H`. -/
def idem (X : WeightCategory H.Regraded) (s : H.zeroSubring) (hs : IsIdempotentElem s) :
    DGCategory.Idempotent X where
  val := H.zeroHom X s
  mem_cocycles := mem_cocycles.mpr ⟨zeroHom_mem_grading X s, hH.d_zeroHom X s⟩
  comp_self := by rw [zeroHom_comp, hs.eq]

/-- The projection onto `A^{0,•}` is multiplicative on homogeneous elements: the internal degrees
of `A` are `0` or at least `k > 0`. -/
theorem internalZeroProj_mul_of_mem {p q : ℤ × ZMod 2} {a b : A}
    (ha : a ∈ H.hgrading p) (hb : b ∈ H.hgrading q) :
    H.internalZeroProj (a * b) = H.internalZeroProj a * H.internalZeroProj b := by
  have hab : a * b ∈ H.hgrading (p + q) := SetLike.GradedMul.mul_mem ha hb
  rw [internalZeroProj_of_mem hab, internalZeroProj_of_mem ha, internalZeroProj_of_mem hb,
    Prod.fst_add]
  have hk := hH.pos
  by_cases hp : p.1 = 0
  · by_cases hq : q.1 = 0
    · rw [ite_eq_left (by rw [hp, hq, add_zero]), ite_eq_left hp, ite_eq_left hq]
    · rw [ite_eq_right (by rw [hp, zero_add]; exact hq), ite_eq_right hq, mul_zero]
  · rw [ite_eq_right hp, zero_mul]
    by_cases hq : q.1 = 0
    · rw [ite_eq_right (by rw [hq, add_zero]; exact hp)]
    · split_ifs with hpq
      · by_cases hp0 : p.1 < 0
        · rw [hH.eq_zero_of_lt (by omega) hp ha, zero_mul]
        · rw [hH.eq_zero_of_lt (j := q.1) (ε := q.2) (by omega) hq hb, mul_zero]
      · rfl

/-- The projection onto `A^{0,•}` is multiplicative. -/
theorem internalZeroProj_mul (a b : A) :
    H.internalZeroProj (a * b) = H.internalZeroProj a * H.internalZeroProj b := by
  refine DirectSum.Decomposition.inductionOn H.hgrading
    (motive := fun a => H.internalZeroProj (a * b) = H.internalZeroProj a * H.internalZeroProj b)
    ?_ (fun {p} x => ?_) (fun x y hx hy => ?_) a
  · simp
  · refine DirectSum.Decomposition.inductionOn H.hgrading
      (motive := fun b => H.internalZeroProj ((x : A) * b) =
        H.internalZeroProj (x : A) * H.internalZeroProj b) ?_ (fun {q} y => ?_)
      (fun y z hy hz => ?_) b
    · simp
    · exact hH.internalZeroProj_mul_of_mem x.2 y.2
    · simp only [mul_add, map_add, hy, hz]
  · simp only [add_mul, map_add, hx, hy]

/-- The projection onto `A^{0,•}` vanishes on boundaries: `A` has no component of internal degree
`-k`. -/
theorem internalZeroProj_hd (a : A) : H.internalZeroProj (H.hd a) = 0 := by
  refine DirectSum.Decomposition.inductionOn H.hgrading
    (motive := fun a => H.internalZeroProj (H.hd a) = 0) ?_ (fun {p} x => ?_)
    (fun x y hx hy => ?_) a
  · simp
  · have hx : H.hd x ∈ H.hgrading (p.1 + k, p.2 + 1) := H.hd_mem (j := p.1) (ε := p.2) x.2
    rw [internalZeroProj_of_mem hx]
    split_ifs with h0
    · have hk := hH.pos
      have h1 : p.1 + k = 0 := h0
      rw [hH.eq_zero_of_lt (j := p.1) (ε := p.2) (by omega) (by omega) x.2, map_zero]
    · rfl
  · rw [map_add, map_add, hx, hy, add_zero]

/-! ### The inclusion of and the projection onto `A^{0,•}` -/

/-- The inclusion `A^{0,•} → A`, a morphism of half-graded dg rings. -/
def incl : Hom H.internalZeroPart H where
  toRingHom := H.internalZeroSubring.subtype
  map_mem' ha := ha
  map_hd' a := (hH.hd_eq_zero_of_mem_internalZeroSubring a.2).symm

/-- The projection `A → A^{0,•}`, `a ↦ a_{0,0̄} + a_{0,1̄}`, a morphism of half-graded dg rings: it
is multiplicative because the internal degrees of `A` are `0` or at least `k > 0`, and commutes
with the differentials because `A` has no component of internal degree `-k` and `d` vanishes on
`A^{0,•}`. -/
def proj : Hom H H.internalZeroPart where
  toFun a := ⟨H.internalZeroProj a, internalZeroProj_mem a⟩
  map_one' := Subtype.ext ((internalZeroProj_of_mem SetLike.GradedOne.one_mem).trans
    (ite_eq_left rfl))
  map_mul' a b := Subtype.ext (hH.internalZeroProj_mul a b)
  map_zero' := Subtype.ext (map_zero _)
  map_add' a b := Subtype.ext (map_add _ a b)
  map_mem' := by
    intro p a ha
    refine mem_internalZeroGrading_iff.mpr ?_
    change H.internalZeroProj a ∈ H.hgrading p
    rw [internalZeroProj_of_mem ha]
    split_ifs
    · exact ha
    · exact zero_mem _
  map_hd' a := Subtype.ext (hH.internalZeroProj_hd a)

theorem coe_incl_apply (a : H.internalZeroSubring) : hH.incl a = (a : A) :=
  rfl

theorem coe_proj_apply (a : A) : (hH.proj a : A) = H.internalZeroProj a :=
  rfl

/-- The projection `A → A^{0,•}` is a retraction of the inclusion `A^{0,•} → A`. -/
theorem proj_comp_incl : hH.proj.comp hH.incl = Hom.id H.internalZeroPart :=
  Hom.ext fun a => Subtype.ext (internalZeroProj_of_mem_internalZeroSubring a.2)

/-- The composite `A → A^{0,•} → A` is the identity on `A^{0,0̄}`. -/
theorem incl_proj_of_mem_zero {a : A} (ha : a ∈ H.hgrading 0) : hH.incl (hH.proj a) = a :=
  (internalZeroProj_of_mem ha).trans (ite_eq_left rfl)

/-! ### The case `A^{0,1̄} = 0`: the inclusion of and the projection onto `A^{0,0̄}` -/

/-- The inclusion `A^{0,0̄} → A`, a morphism of half-graded dg rings. -/
def inclEven : Hom H.degreeZeroPart H where
  toRingHom := H.zeroSubring.subtype
  map_mem' := by
    intro p a ha
    rcases mem_degreeZeroGrading_iff.mp ha with rfl | rfl
    · exact mem_zeroSubring.mp a.2
    · exact zero_mem _
  map_hd' a := (hH.hd_eq_zero_of_mem_zero (mem_zeroSubring.mp a.2)).symm

variable (hodd : ∀ a ∈ H.hgrading (0, 1), a = 0)
include hodd

omit hH in
/-- If `A^{0,1̄} = 0`, the component of bidegree `(0, 0̄)` is the projection onto `A^{0,•}`. -/
theorem coe_decompose_zero_eq_internalZeroProj (a : A) :
    (decompose H.hgrading a 0 : A) = H.internalZeroProj a := by
  rw [internalZeroProj_apply, Finset.sum_eq_single (0 : ZMod 2)]
  · rfl
  · intro ε _ hε
    rcases HalfGradedDGRing.zmod_two_cases ε with rfl | rfl
    · exact absurd rfl hε
    · exact hodd _ (SetLike.coe_mem _)
  · intro h
    exact absurd (Finset.mem_univ _) h

/-- If `A^{0,1̄} = 0`, the projection `A → A^{0,0̄}` onto the component of bidegree `(0, 0̄)`, a
morphism of half-graded dg rings. -/
def projEven : Hom H H.degreeZeroPart where
  toFun a := ⟨(decompose H.hgrading a 0 : A), mem_zeroSubring.mpr (decompose H.hgrading a 0).2⟩
  map_one' := Subtype.ext (decompose_of_mem_same _ SetLike.GradedOne.one_mem)
  map_mul' a b := Subtype.ext (by
    simp only [coe_decompose_zero_eq_internalZeroProj hodd]
    exact hH.internalZeroProj_mul a b)
  map_zero' := Subtype.ext (by simp)
  map_add' a b := Subtype.ext (by simp)
  map_mem' := by
    intro p a ha
    refine mem_degreeZeroGrading_iff.mpr ?_
    by_cases hp : p = 0
    · exact Or.inl hp
    · exact Or.inr (Subtype.ext (decompose_of_mem_ne _ ha hp))
  map_hd' a := Subtype.ext (by
    change (decompose H.hgrading (H.hd a) 0 : A) = 0
    rw [coe_decompose_zero_eq_internalZeroProj hodd]
    exact hH.internalZeroProj_hd a)

theorem projEven_comp_inclEven : (hH.projEven hodd).comp hH.inclEven = Hom.id H.degreeZeroPart :=
  Hom.ext fun a => Subtype.ext (decompose_of_mem_same _ (mem_zeroSubring.mp a.2))

theorem inclEven_projEven_of_mem_zero {a : A} (ha : a ∈ H.hgrading 0) :
    hH.inclEven (hH.projEven hodd a) = a :=
  decompose_of_mem_same _ ha

end IsPositive

/-! ### The positive model -/

variable (H) in
/-- The family `w ↦ (w, -⌊w / k⌋)` of formal shifts of the objects of `C_H`. -/
def shiftFamily (X : WeightCategory H.Regraded) : WeightCategory H.Regraded × ℤ :=
  (X, -(X.as / k))

variable (H) in
/-- The dg category of the formal shifts `w[-⌊w / k⌋]` of the objects of `C_H`; it is positive
when `H` is. -/
abbrev PositiveModel : Type := ShiftedObjects H.shiftFamily

/-- The bidegree (cohomological degree, weight) in the regraded ring of the morphisms `i ⟶ j` of
degree `n` of the positive model. -/
def bidegree (i j : PositiveModel H) (n : ℤ) : ℤ × ℤ :=
  (n + ((H.shiftFamily j.as).2 - (H.shiftFamily i.as).2), j.as.as - i.as.as)

theorem bidegree_swap (i j : PositiveModel H) : bidegree j i 0 = -bidegree i j 0 :=
  Prod.ext (by
    change 0 + ((H.shiftFamily i.as).2 - (H.shiftFamily j.as).2) =
      -(0 + ((H.shiftFamily j.as).2 - (H.shiftFamily i.as).2))
    ring) (by
    change i.as.as - j.as.as = -(j.as.as - i.as.as)
    ring)

/-- The internal degree of the morphisms `i ⟶ j` of degree `n` of the positive model. -/
theorem halfDegree_bidegree_fst (i j : PositiveModel H) (n : ℤ) :
    (halfDegree k (bidegree i j n)).1 = j.as.as % k - i.as.as % k + n * k := by
  change j.as.as - i.as.as + (n + (-(j.as.as / k) - -(i.as.as / k))) * k = _
  rw [Int.emod_def, Int.emod_def]
  ring

/-- A morphism `i ⟶ j` of degree `n` of the positive model is an element of `A` placed in
bidegree `bidegree i j n`. -/
theorem exists_eq_place_of_mem_grading {i j : PositiveModel H} {n : ℤ} {f : i ⟶ j}
    (hf : f ∈ grading n) :
    ∃ (a : A) (ha : a ∈ H.hgrading (halfDegree k (bidegree i j n))),
      (ShiftedObjects.homVal f).1 = H.place (bidegree i j n) a ha :=
  exists_eq_place (x := (ShiftedObjects.homVal f).1)
    (n := n + ((H.shiftFamily j.as).2 - (H.shiftFamily i.as).2)) (w := j.as.as - i.as.as)
    (WeightCategory.mem_grading_iff.mp (ShiftedObjects.mem_grading_iff.mp hf))
    (ShiftedObjects.homVal f).2

namespace IsPositive

variable (hH : H.IsPositive)
include hH

/-- A nonzero morphism of degree `n ≤ 0` of the positive model has degree `0`, and is an element
of `A^{0,ε}` for some parity `ε`. -/
theorem eq_zero_and_halfDegree_fst_eq_zero {i j : PositiveModel H} {n : ℤ} {f : i ⟶ j}
    (hf : f ∈ grading n) (hn : n ≤ 0) (hf0 : f ≠ 0) :
    n = 0 ∧ (halfDegree k (bidegree i j n)).1 = 0 := by
  obtain ⟨a, ha, hfa⟩ := exists_eq_place_of_mem_grading hf
  have hk := hH.pos
  have ha0 : a ≠ 0 := by
    rintro rfl
    exact hf0 (ShiftedObjects.hom_ext (WeightCategory.hom_ext (hfa.trans (place_zero _))))
  have h1 := halfDegree_bidegree_fst i j n
  have hj := Int.emod_lt_of_pos j.as.as hk
  have hi := Int.emod_nonneg i.as.as hk.ne'
  have hnk : n * k ≤ 0 := by
    have := mul_nonneg (neg_nonneg.mpr hn) hk.le
    linarith
  have hz : (halfDegree k (bidegree i j n)).1 = 0 := by
    by_contra h
    exact ha0 (hH.eq_zero_of_lt (j := (halfDegree k (bidegree i j n)).1)
      (ε := (halfDegree k (bidegree i j n)).2) (by rw [h1]; linarith) h ha)
  refine ⟨?_, hz⟩
  by_contra hn0
  have hn1 : n ≤ -1 := by omega
  have h2 : n * k ≤ -1 * k := mul_le_mul_of_nonneg_right hn1 hk.le
  rw [h1] at hz
  linarith

/-- A morphism of degree `0` of the positive model is an element of `A^{0,•}`. -/
theorem mem_internalZero_of_mem_grading_zero {i j : PositiveModel H} {f : i ⟶ j}
    (hf : f ∈ grading 0) {a : A} (ha : a ∈ H.hgrading (halfDegree k (bidegree i j 0)))
    (hfa : (ShiftedObjects.homVal f).1 = H.place (bidegree i j 0) a ha) :
    a ∈ H.hgrading (0, (halfDegree k (bidegree i j 0)).2) := by
  by_cases hf0 : f = 0
  · have : a = 0 := by
      have h0 : (ShiftedObjects.homVal f).1 = 0 := by rw [hf0]; rfl
      rw [hfa] at h0
      exact place_injective (h0.trans (place_zero _).symm)
    rw [this]
    exact zero_mem _
  · have hz := (hH.eq_zero_and_halfDegree_fst_eq_zero hf le_rfl hf0).2
    rwa [show halfDegree k (bidegree i j 0) = (0, (halfDegree k (bidegree i j 0)).2) from
      Prod.ext hz rfl] at ha

/-- An idempotent `e` of `A^{0,0̄}` which is a graded simple idempotent of `A^{0,•}` (the graded
left ideal `A^{0,•} e` is graded simple) gives a simple idempotent of every object of the positive
model. -/
theorem isSimple_idempotentMk (i : PositiveModel H) {s : H.zeroSubring}
    (hs : IsIdempotentElem s) {e : H.internalZeroSubring} (hse : (e : A) = s)
    (hes : IsGradedSimpleIdempotent H.internalZeroGrading e) :
    (ShiftedObjects.idempotentMk (i := i) (hH.idem i.as s hs)).IsSimple := by
  refine ⟨fun h0 => ?_, fun j h hh heh hh0 => ?_⟩
  · have h0' : H.zeroHom i.as s = 0 := h0
    have hs0 : s = 0 := zeroHom_injective i.as (h0'.trans (map_zero (H.zeroHom i.as)).symm)
    exact hes.1 (Subtype.ext (by rw [hse, hs0]; rfl))
  obtain ⟨a, ha, hfa⟩ := exists_eq_place_of_mem_grading hh
  have ha' := hH.mem_internalZero_of_mem_grading_zero hh ha hfa
  have ha0 : a ≠ 0 := by
    rintro rfl
    exact hh0 (ShiftedObjects.hom_ext (WeightCategory.hom_ext (hfa.trans (place_zero _))))
  have hmem : a * (s : A) ∈ H.hgrading (halfDegree k (bidegree i j 0)) := by
    have := SetLike.GradedMul.mul_mem ha (mem_zeroSubring.mp s.2)
    rwa [add_zero] at this
  have has : a * (s : A) = a := by
    have h1 : (ShiftedObjects.homVal h).1 * (H.zeroHom i.as s).1 = (ShiftedObjects.homVal h).1 :=
      congrArg (fun f : i ⟶ j => (ShiftedObjects.homVal f).1) heh
    rw [hfa, zeroHom_val, place_mul_place] at h1
    exact place_injective ((place_congr (add_zero _) rfl _ hmem).symm.trans h1)
  let x : H.internalZeroSubring := ⟨a, mem_internalZeroSubring_of_mem ha'⟩
  have hx : x ∈ H.internalZeroGrading (halfDegree k (bidegree i j 0)) :=
    mem_internalZeroGrading_iff.mpr ha
  have hxe : x * e = x := Subtype.ext (by
    change a * (e : A) = a
    rw [hse, has])
  have hx0 : x ≠ 0 := fun h => ha0 (congrArg Subtype.val h)
  obtain ⟨c, hc, hcx⟩ := hes.2 hx hxe hx0
  have hcmem : (c : A) ∈ H.hgrading (halfDegree k (bidegree j i 0)) := by
    rw [bidegree_swap i j, map_neg]
    exact mem_internalZeroGrading_iff.mp hc
  have he : (ShiftedObjects.homVal
      (ShiftedObjects.idempotentMk (i := i) (hH.idem i.as s hs)).val).1 =
      H.place 0 s (by rw [map_zero]; exact mem_zeroSubring.mp s.2) := rfl
  refine ⟨ShiftedObjects.homMk ⟨H.place (bidegree j i 0) c hcmem,
      place_mem_wgrading (H := H) (bidegree j i 0) hcmem⟩,
    ShiftedObjects.mem_grading_iff.mpr (WeightCategory.mem_grading_iff.mpr
      (place_mem_grading (H := H) (bidegree j i 0) hcmem)), ?_⟩
  refine ShiftedObjects.hom_ext (WeightCategory.hom_ext ?_)
  exact ((congrArg (fun y => H.place (bidegree j i 0) c hcmem * y) hfa).trans
    ((place_mul_place hcmem ha).trans
      (place_congr (by rw [bidegree_swap i j, neg_add_cancel])
        ((congrArg Subtype.val hcx).trans hse) _ _))).trans he.symm

/-- The degree-`0` category of the positive model is semisimple. -/
theorem isDegreeZeroSemisimple : DGCategory.IsDegreeZeroSemisimple (PositiveModel H) := by
  intro i
  obtain ⟨l, hl, hlp, hlsum⟩ := hH.isGradedSemisimple.exists_list_sum_eq_one
  let z : ∀ e ∈ l, H.zeroSubring := fun e he =>
    ⟨e, mem_zeroSubring.mpr (mem_internalZeroGrading_iff.mp (hl e he).1)⟩
  have hz : ∀ e (he : e ∈ l), IsIdempotentElem (z e he) := fun e he =>
    Subtype.ext (show (e : A) * e = e from congrArg Subtype.val (hl e he).2.1)
  let E : ∀ e ∈ l, DGCategory.Idempotent i := fun e he =>
    ShiftedObjects.idempotentMk (i := i) (hH.idem i.as (z e he) (hz e he))
  refine ⟨l.pmap E fun _ h => h, fun f hf => ?_, ?_, ?_⟩
  · obtain ⟨e, he, rfl⟩ := List.mem_pmap.mp hf
    exact hH.isSimple_idempotentMk i (hz e he) rfl (hl e he).2.2
  · rw [List.pairwise_pmap]
    refine hlp.imp_of_mem fun {a b} ha hb hab _ _ => ?_
    have hba : z b hb * z a ha = 0 :=
      Subtype.ext (show (b : A) * a = 0 from congrArg Subtype.val hab.2)
    have hab' : z a ha * z b hb = 0 :=
      Subtype.ext (show (a : A) * b = 0 from congrArg Subtype.val hab.1)
    refine ⟨ShiftedObjects.hom_ext ?_, ShiftedObjects.hom_ext ?_⟩
    · change H.zeroHom i.as (z a ha) ≫ H.zeroHom i.as (z b hb) = 0
      rw [zeroHom_comp, hba, map_zero]
    · change H.zeroHom i.as (z b hb) ≫ H.zeroHom i.as (z a ha) = 0
      rw [zeroHom_comp, hab', map_zero]
  · rw [List.map_pmap]
    let ψ : H.zeroSubring →+ (i ⟶ i) :=
      { toFun := fun s => ShiftedObjects.homMk (H.zeroHom i.as s)
        map_zero' := ShiftedObjects.hom_ext (map_zero (H.zeroHom i.as))
        map_add' := fun s t => ShiftedObjects.hom_ext (map_add (H.zeroHom i.as) s t) }
    change (l.pmap (fun (e : H.internalZeroSubring) (he : e ∈ l) => ψ (z e he))
      fun _ h => h).sum = 𝟙 i
    have hsum : (l.pmap z fun _ h => h).sum = 1 := by
      apply H.zeroSubring.subtype_injective
      rw [map_list_sum, List.map_pmap, map_one]
      change (l.pmap (fun (e : H.internalZeroSubring) _ => (e : A)) fun _ h => h).sum = 1
      rw [List.pmap_eq_map]
      exact (map_list_sum H.internalZeroSubring.subtype l).symm.trans (congrArg Subtype.val hlsum)
    have hmap : l.pmap (fun e he => ψ (z e he)) (fun _ h => h) =
        (l.pmap z fun _ h => h).map ψ := by
      rw [List.map_pmap]
    rw [hmap, ← map_list_sum, hsum]
    exact ShiftedObjects.hom_ext (zeroHom_one i.as)

/-- The dg category of the formal shifts `w[-⌊w / k⌋]` of the objects of `C_H` is positive, for a
positive half-graded dg ring `H`. -/
theorem isPositive_positiveModel : DGCategory.IsPositive (PositiveModel H) where
  eq_zero_of_neg := by
    intro i j n hn f hf
    by_contra hf0
    have := (hH.eq_zero_and_halfDegree_fst_eq_zero hf hn.le hf0).1
    omega
  semisimple := hH.isDegreeZeroSemisimple
  d_eq_zero := by
    intro i j f hf
    by_cases hf0 : f = 0
    · rw [hf0, d_zero]
    obtain ⟨a, ha, hfa⟩ := exists_eq_place_of_mem_grading hf
    have ha' := hH.mem_internalZero_of_mem_grading_zero hf ha hfa
    have hd : d (ShiftedObjects.homVal f) = 0 := WeightCategory.hom_ext (by
      rw [WeightCategory.d_val, hfa, d_place]
      exact (place_congr rfl (hH.hd_eq_zero ha') _ _).trans (place_zero _))
    refine ShiftedObjects.hom_ext ?_
    rw [ShiftedObjects.homVal_d]
    exact (congrArg _ hd).trans (smul_zero _)

/-! ### Generators of `K₀` -/

variable [CatModule.HasDerivedCategory.{max u w, max u w} (WeightCategory H.Regraded)]

/-- For a positive half-graded dg ring `H`, `K₀(C_H) = K₀(D^c(C_H))` is generated by the classes
of the modules `e · C_H(w, -)`, for the degree-`0` idempotent cocycles `e` of the objects `w` of
`C_H` (the idempotents of `A^{0,0̄}`). -/
theorem closure_cell_eq_top :
    AddSubgroup.closure (Set.range fun c : DGCategory.Corner (WeightCategory H.Regraded) =>
      DGCategory.K0.cell.{max u w} c.2 0) = ⊤ := by
  refine eq_top_iff.mpr (le_trans (le_of_eq (ShiftedObjects.closure_cell_eq_top_of_isPositive.{w}
    H.shiftFamily (fun Y => ⟨Y, rfl⟩) hH.isPositive_positiveModel).symm)
    (AddSubgroup.closure_mono ?_))
  rintro _ ⟨c, rfl⟩
  exact ⟨⟨_, ShiftedObjects.idempotentVal c.1.2⟩, rfl⟩

/-! ### `K₀` and retractions onto subrings containing `A^{0,0̄}` -/

section Retract

variable {A' : Type u} [Ring A'] {H' : HalfGradedDGRing A' k} (i : Hom H' H) (p : Hom H H')
  (hip : ∀ {a : A}, a ∈ H.hgrading 0 → i (p a) = a)
include hip

variable [CatModule.HasDerivedCategory.{max u w, max u w} (WeightCategory H'.Regraded)]

/-- For `H` positive, the composite `K₀(C_H) → K₀(C_{H'}) → K₀(C_H)` is the identity: it fixes
the generating classes `[e · C_H(w, -)]`. -/
theorem K0Map_K0Map_of_retract (x : DGCategory.K0.{max u w, max u w} (WeightCategory H.Regraded)) :
    i.K0Map.{w} (p.K0Map.{w} x) = x := by
  have hx : x ∈ AddSubgroup.closure
      (Set.range fun c : DGCategory.Corner (WeightCategory H.Regraded) =>
        DGCategory.K0.cell.{max u w} c.2 0) := by
    rw [hH.closure_cell_eq_top.{w}]
    trivial
  induction hx using AddSubgroup.closure_induction with
  | mem y hy =>
    obtain ⟨c, rfl⟩ := hy
    exact ((congrArg (fun y => i.K0Map.{w} y)
      (DGCategory.K0.map_cell.{max u w} p.weightFunctor c.2)).trans
      (DGCategory.K0.map_cell.{max u w} i.weightFunctor (c.2.map p.weightFunctor))).trans
      (congrArg (fun e => DGCategory.K0.cell.{max u w} e 0) (map_map_of_retract i p hip c.2))
  | zero => rw [map_zero, map_zero]
  | add x y _ _ hx hy => rw [map_add, map_add, hx, hy]
  | neg x _ hx => rw [map_neg, map_neg, hx]

omit hH hip in
theorem K0Map_K0Map_of_comp_eq_id (hpi : p.comp i = Hom.id H')
    (x : DGCategory.K0.{max u w, max u w} (WeightCategory H'.Regraded)) :
    p.K0Map.{w} (i.K0Map.{w} x) = x := by
  rw [Hom.K0Map_apply, Hom.K0Map_apply, ← AddMonoidHom.comp_apply, ← DGCategory.K0.map_comp]
  simp only [← Hom.weightFunctor_comp, hpi, Hom.weightFunctor_id, DGCategory.K0.map_id,
    AddMonoidHom.id_apply]

/-- For `H` positive, a morphism `p : H → H'` of half-graded dg rings with a section `i`
(`p ∘ i = id`) such that `i ∘ p` is the identity on `A^{0,0̄}` induces an isomorphism
`K₀(C_H) ≃ K₀(C_{H'})` of `ℤ[q, q⁻¹]`-modules, with inverse induced by `i`. -/
def K0EquivOfRetract (hpi : p.comp i = Hom.id H') :
    DGCategory.K0.{max u w, max u w} (WeightCategory H.Regraded) ≃ₗ[LaurentPolynomial ℤ]
      DGCategory.K0.{max u w, max u w} (WeightCategory H'.Regraded) :=
  { p.K0Map.{w} with
    invFun := i.K0Map.{w}
    left_inv := hH.K0Map_K0Map_of_retract i p hip
    right_inv := K0Map_K0Map_of_comp_eq_id i p hpi }

theorem K0EquivOfRetract_apply (hpi : p.comp i = Hom.id H')
    (x : DGCategory.K0.{max u w, max u w} (WeightCategory H.Regraded)) :
    hH.K0EquivOfRetract i p hip hpi x = p.K0Map.{w} x :=
  rfl

theorem K0EquivOfRetract_symm_apply (hpi : p.comp i = Hom.id H')
    (x : DGCategory.K0.{max u w, max u w} (WeightCategory H'.Regraded)) :
    (hH.K0EquivOfRetract i p hip hpi).symm x = i.K0Map.{w} x :=
  rfl

end Retract

/-! ### `K₀(A) ≅ K₀(A^{0,•})` -/

section Internal

variable [CatModule.HasDerivedCategory.{max u w, max u w}
    (WeightCategory H.internalZeroPart.Regraded)]

/-- **`K₀(A) ≅ K₀(A^{0,•})` for a positive half-graded dg ring**, as `ℤ[q, q⁻¹]`-modules (`qⁿ`
acting by the internal shift `⟨n⟩`): the isomorphism `K₀(C_H) ≃ K₀(C_{H^{0,•}})` is induced by the
projection `A → A^{0,•}` onto the part of internal degree `0`, with inverse induced by the
inclusion `A^{0,•} → A` (derived induction between the weight dg categories). It sends
`[e · C_H(w, -)]` to `[e · C_{H^{0,•}}(w, -)]`
(`DG.HalfGradedDGRing.IsPositive.K0DegreeZeroEquiv_cell`). -/
def K0DegreeZeroEquiv :
    DGCategory.K0.{max u w, max u w} (WeightCategory H.Regraded) ≃ₗ[LaurentPolynomial ℤ]
      DGCategory.K0.{max u w, max u w} (WeightCategory H.internalZeroPart.Regraded) :=
  hH.K0EquivOfRetract hH.incl hH.proj (fun ha => hH.incl_proj_of_mem_zero ha) hH.proj_comp_incl

theorem K0DegreeZeroEquiv_apply
    (x : DGCategory.K0.{max u w, max u w} (WeightCategory H.Regraded)) :
    hH.K0DegreeZeroEquiv x = hH.proj.K0Map.{w} x :=
  rfl

theorem K0DegreeZeroEquiv_symm_apply
    (x : DGCategory.K0.{max u w, max u w} (WeightCategory H.internalZeroPart.Regraded)) :
    hH.K0DegreeZeroEquiv.symm x = hH.incl.K0Map.{w} x :=
  rfl

/-- `K₀(C_H) ≅ K₀(C_{H^{0,•}})` sends `[e · C_H(w, -)]` to `[e · C_{H^{0,•}}(w, -)]`. -/
theorem K0DegreeZeroEquiv_cell {X : WeightCategory H.Regraded} (e : DGCategory.Idempotent X) :
    hH.K0DegreeZeroEquiv (DGCategory.K0.cell.{max u w} e 0) =
      DGCategory.K0.cell.{max u w} (e.map hH.proj.weightFunctor) 0 :=
  DGCategory.K0.map_cell.{max u w} _ e

theorem K0DegreeZeroEquiv_symm_cell {X : WeightCategory H.internalZeroPart.Regraded}
    (e : DGCategory.Idempotent X) :
    hH.K0DegreeZeroEquiv.symm (DGCategory.K0.cell.{max u w} e 0) =
      DGCategory.K0.cell.{max u w} (e.map hH.incl.weightFunctor) 0 :=
  DGCategory.K0.map_cell.{max u w} _ e

/-- The super Grothendieck groups: `K₀^{super}(C_H) ≅ K₀^{super}(C_{H^{0,•}})`, induced by
`K0DegreeZeroEquiv` (both are `K₀` modulo `(1 + qᵏ)`). -/
def superK0cDegreeZeroEquiv :
    SuperK0c.{max u w, w} H ≃ₗ[LaurentPolynomial ℤ] SuperK0c.{max u w, w} H.internalZeroPart :=
  LinearEquiv.ofLinearMap (superK0cMap H H.internalZeroPart hH.K0DegreeZeroEquiv.toLinearMap)
    (superK0cMap H.internalZeroPart H hH.K0DegreeZeroEquiv.symm.toLinearMap)
    (by
      ext x
      obtain ⟨y, rfl⟩ := superK0cMk_surjective H.internalZeroPart x
      simp only [LinearMap.comp_apply, superK0cMap_mk, LinearEquiv.coe_toLinearMap,
        LinearEquiv.apply_symm_apply, LinearMap.id_apply])
    (by
      ext x
      obtain ⟨y, rfl⟩ := superK0cMk_surjective H x
      simp only [LinearMap.comp_apply, superK0cMap_mk, LinearEquiv.coe_toLinearMap,
        LinearEquiv.symm_apply_apply, LinearMap.id_apply])

theorem superK0cDegreeZeroEquiv_mk (x : CompactK0.{max u w, w} H) :
    hH.superK0cDegreeZeroEquiv (superK0cMk H x) =
      superK0cMk H.internalZeroPart (hH.K0DegreeZeroEquiv x) :=
  superK0cMap_mk _ _ _ x

end Internal

/-! ### The case `A^{0,1̄} = 0`: `K₀(A) ≅ K₀(A^{0,0̄})` -/

section Even

variable [CatModule.HasDerivedCategory.{max u w, max u w}
  (WeightCategory H.degreeZeroPart.Regraded)]

/-- **`K₀(A) ≅ K₀(A^{0,0̄})` for a positive half-graded dg ring with `A^{0,1̄} = 0`**, as
`ℤ[q, q⁻¹]`-modules: induced by the projection `A → A^{0,0̄}` onto the component of bidegree
`(0, 0̄)`, with inverse induced by the inclusion. -/
def K0DegreeZeroEvenEquiv (hodd : ∀ a ∈ H.hgrading (0, 1), a = 0) :
    DGCategory.K0.{max u w, max u w} (WeightCategory H.Regraded) ≃ₗ[LaurentPolynomial ℤ]
      DGCategory.K0.{max u w, max u w} (WeightCategory H.degreeZeroPart.Regraded) :=
  hH.K0EquivOfRetract hH.inclEven (hH.projEven hodd)
    (fun ha => hH.inclEven_projEven_of_mem_zero hodd ha) (hH.projEven_comp_inclEven hodd)

theorem K0DegreeZeroEvenEquiv_cell (hodd : ∀ a ∈ H.hgrading (0, 1), a = 0)
    {X : WeightCategory H.Regraded} (e : DGCategory.Idempotent X) :
    hH.K0DegreeZeroEvenEquiv hodd (DGCategory.K0.cell.{max u w} e 0) =
      DGCategory.K0.cell.{max u w} (e.map (hH.projEven hodd).weightFunctor) 0 :=
  DGCategory.K0.map_cell.{max u w} _ e

end Even

end IsPositive

end HalfGradedDGRing

end DG

end
