import DG.HalfGraded.Field
import DG.HalfGraded.Hom
import DG.K0.ShiftedObjects
import DG.Bigraded.K0Basis
import DG.Positive.Category

/-!
# Positive half-graded dg rings

Let `H` be a half-graded dg ring with parameter `k > 0`: a ring `A = ⨁ (j, ε), A^{j,ε}` graded by
an internal degree `j : ℤ` and a parity `ε : ℤ/2`, with a differential of bidegree `(k, 1̄)`.
`H` is *positive* (`DG.HalfGradedDGRing.IsPositive`) if

* `A^{j,ε} = 0` for `j < k` unless `(j, ε) = (0, 0̄)`;
* the ring `A⁰ = A^{0,0̄}` (`DG.HalfGradedDGRing.zeroSubring`) is semisimple;
* the differential vanishes on `A^{0,0̄}`.

This is the analogue of Schnürer's positivity [Sch, §1, (P1)–(P3)] for a differential of internal
degree `k`: the internal degree is non-negative, takes no values strictly between `0` and `k`, and
the part of internal degree `0` is even and semisimple. (More generally one could allow
`A^{0,1̄} ≠ 0` with `A^{0,•}` semisimple as a `ℤ/2`-graded ring; this is not done here.)

## The positive model

Half-graded dg modules are dg modules over the weight dg category `C_H` of the regraded ring
(`DG/HalfGraded/Basic.lean`), `C_H(w, w')ⁿ = A^{w' - w + n k, n}`. This dg category is not
positive: the periodicity unit is an invertible morphism `w ⟶ w - 2k` of degree `2`. But the dg
category of the formal shifts `w[-⌊w / k⌋]` of its objects
(`DG.HalfGradedDGRing.PositiveModel H`, a `DG.ShiftedObjects`) has

  `P(w, w')ⁿ = A^{(w' mod k) - (w mod k) + n k, n + ⌊w / k⌋ - ⌊w' / k⌋}`,

which vanishes for `n < 0`, and for `n = 0` is `A^{0,0̄}` if `w ≡ w' (mod 2k)` and `0` otherwise.
Hence `P` is a positive dg category (`DG.HalfGradedDGRing.IsPositive.isPositive_positiveModel`),
and by Schnürer's theorem for positive dg categories and the invariance of `K₀` under formal
shifts (`DG.ShiftedObjects.closure_cell_eq_top_of_isPositive`), `K₀(C_H) = K₀(D^c(C_H))` is
generated by the classes of the modules `e · C_H(w, -)` for the idempotents `e` of `A^{0,0̄}`
(`DG.HalfGradedDGRing.IsPositive.closure_cell_eq_top`).

## `K₀(A) ≅ K₀(A⁰)`

The ring `A⁰ = A^{0,0̄}` is a half-graded dg ring concentrated in bidegree `(0, 0̄)`
(`DG.HalfGradedDGRing.degreeZeroPart`), and the inclusion `A⁰ → A` and the projection `A → A⁰`
are morphisms of half-graded dg rings (`DG.HalfGradedDGRing.IsPositive.incl`,
`DG.HalfGradedDGRing.IsPositive.proj`). They induce mutually inverse isomorphisms

  `DG.HalfGradedDGRing.IsPositive.K0DegreeZeroEquiv : K₀(C_H) ≃ₗ[ℤ[q, q⁻¹]] K₀(C_{H⁰})`

of `ℤ[q, q⁻¹]`-modules (`qⁿ` acting by the internal shift `⟨n⟩`), sending the class of
`e · C_H(w, -)` to that of `e · C_{H⁰}(w, -)`.

## References

* [Sch] O. M. Schnürer, *Perfect derived categories of positively graded DG algebras*,
  Appl. Categ. Structures 19 (2011), 757–782; arXiv:0809.4782v2.
-/

open CategoryTheory DirectSum

universe w u

noncomputable section

set_option backward.isDefEq.respectTransparency false

namespace DG

namespace HalfGradedDGRing

variable {A : Type u} [Ring A] {k : ℤ} (H : HalfGradedDGRing A k)

/-! ### Bihomogeneous elements of the regraded ring -/

variable {H} in
/-- An element of the regraded ring of cohomological degree `n` and weight `w` is an element of
`A^{w + n k, n}` placed in bidegree `(n, w)`. -/
theorem exists_eq_place {x : H.Regraded} {n w : ℤ} (hn : x ∈ grading n) (hw : x ∈ wgrading w) :
    ∃ (a : A) (ha : a ∈ H.hgrading (halfDegree k (n, w))), x = H.place (n, w) a ha := by
  let y : ⨁ p : ℤ × ℤ, ↥(halfGrading H.hgrading k p) := x
  refine ⟨(y (n, w) : A), (y (n, w)).2, ?_⟩
  have hsupp : ∀ p, p ≠ (n, w) → y p = 0 := fun p hp => by
    by_cases h1 : p.1 = n
    · exact hw p (fun h2 => hp (Prod.ext h1 h2))
    · exact hn p h1
  change y = DirectSum.of _ (n, w) (y (n, w))
  ext p : 1
  by_cases hp : p = (n, w)
  · subst hp; rw [DirectSum.of_eq_same]
  · rw [hsupp p hp, DirectSum.of_eq_of_ne _ _ _ hp]

variable {H} in
theorem place_injective {p : ℤ × ℤ} {a a' : A} {ha : a ∈ H.hgrading (halfDegree k p)}
    {ha' : a' ∈ H.hgrading (halfDegree k p)} (h : H.place p a ha = H.place p a' ha') : a = a' :=
  congrArg Subtype.val (DirectSum.of_injective (β := fun p => ↥(halfGrading H.hgrading k p)) p
    (a₁ := ⟨a, ha⟩) (a₂ := ⟨a', ha'⟩) h)

/-! ### The ring `A⁰ = A^{0,0̄}` -/

/-- The subring `A⁰ = A^{0,0̄}` of a half-graded dg ring. -/
def zeroSubring : Subring A := SetLike.GradeZero.subring H.hgrading

variable {H} in
theorem mem_zeroSubring {a : A} : a ∈ H.zeroSubring ↔ a ∈ H.hgrading 0 :=
  Iff.rfl

/-- The ring `A⁰ = A^{0,0̄}`, as a half-graded dg ring concentrated in bidegree `(0, 0̄)` with zero
differential. -/
abbrev degreeZeroPart : HalfGradedDGRing H.zeroSubring k :=
  degreeZero H.zeroSubring k

/-- An element of `A⁰ = A^{0,0̄}`, as an endomorphism of degree `0` of an object of the weight dg
category `C_H`. -/
def zeroHom (X : WeightCategory H.Regraded) : H.zeroSubring →+ (X ⟶ X) where
  toFun s := ⟨H.place 0 s (by rw [map_zero]; exact mem_zeroSubring.mp s.2), by
    rw [sub_self]; exact place_mem_wgrading (H := H) 0 _⟩
  map_zero' := WeightCategory.hom_ext ((place_congr rfl rfl _ (zero_mem _)).trans (place_zero _))
  map_add' _ _ := WeightCategory.hom_ext (place_add _ _ _)

variable {H}

theorem zeroHom_val (X : WeightCategory H.Regraded) (s : H.zeroSubring) :
    (H.zeroHom X s).1 = H.place 0 s (by rw [map_zero]; exact mem_zeroSubring.mp s.2) :=
  rfl

theorem zeroHom_mem_grading (X : WeightCategory H.Regraded) (s : H.zeroSubring) :
    H.zeroHom X s ∈ grading 0 :=
  place_mem_grading (H := H) 0 _

theorem zeroHom_comp (X : WeightCategory H.Regraded) (s t : H.zeroSubring) :
    H.zeroHom X s ≫ H.zeroHom X t = H.zeroHom X (t * s) :=
  WeightCategory.hom_ext (by
    rw [WeightCategory.comp_val, zeroHom_val, zeroHom_val, zeroHom_val, place_mul_place]
    exact place_congr (add_zero 0) rfl _ _)

theorem zeroHom_one (X : WeightCategory H.Regraded) : H.zeroHom X 1 = 𝟙 X :=
  WeightCategory.hom_ext rfl

theorem zeroHom_injective (X : WeightCategory H.Regraded) :
    Function.Injective (H.zeroHom X) := by
  intro s t h
  exact Subtype.ext (place_injective (congrArg Subtype.val h))

/-! ### Positivity -/

variable (H) in
/-- A half-graded dg ring with parameter `k` is *positive* if `k > 0`, `A^{j,ε} = 0` for `j < k`
unless `(j, ε) = (0, 0̄)`, the ring `A^{0,0̄}` is semisimple, and the differential vanishes on
`A^{0,0̄}`. -/
structure IsPositive : Prop where
  /-- The internal degree of the differential is positive. -/
  pos : 0 < k
  /-- `A^{j,ε} = 0` for `j < k`, unless `(j, ε) = (0, 0̄)`. -/
  eq_zero_of_lt : ∀ {j : ℤ} {ε : ZMod 2} {a : A}, j < k → (j, ε) ≠ 0 → a ∈ H.hgrading (j, ε) →
    a = 0
  /-- `A^{0,0̄}` is a semisimple ring. -/
  isSemisimple : IsSemisimpleRing H.zeroSubring
  /-- The differential vanishes on `A^{0,0̄}`. -/
  hd_eq_zero : ∀ {a : A}, a ∈ H.hgrading 0 → H.hd a = 0

namespace IsPositive

variable (hH : H.IsPositive)
include hH

theorem d_zeroHom (X : WeightCategory H.Regraded) (s : H.zeroSubring) :
    d (H.zeroHom X s) = 0 :=
  WeightCategory.hom_ext (by
    rw [WeightCategory.d_val, zeroHom_val, d_place]
    exact (place_congr rfl (hH.hd_eq_zero (mem_zeroSubring.mp s.2)) _ _).trans (place_zero _))

/-- An idempotent `s` of `A^{0,0̄}`, as a degree-`0` idempotent cocycle of an object of `C_H`. -/
def idem (X : WeightCategory H.Regraded) (s : H.zeroSubring) (hs : IsIdempotentElem s) :
    DGCategory.Idempotent X where
  val := H.zeroHom X s
  mem_cocycles := mem_cocycles.mpr ⟨zeroHom_mem_grading X s, hH.d_zeroHom X s⟩
  comp_self := by rw [zeroHom_comp, hs.eq]

/-- The component of bidegree `(0, 0̄)` of a product of homogeneous elements. -/
theorem coe_decompose_mul_zero_of_mem {p q : ℤ × ZMod 2} {a b : A}
    (ha : a ∈ H.hgrading p) (hb : b ∈ H.hgrading q) :
    (decompose H.hgrading (a * b) 0 : A) =
      decompose H.hgrading a 0 * decompose H.hgrading b 0 := by
  have hab : a * b ∈ H.hgrading (p + q) := SetLike.GradedMul.mul_mem ha hb
  by_cases hp : p = 0
  · subst hp
    by_cases hq : q = 0
    · subst hq
      have hab' : a * b ∈ H.hgrading 0 := by rwa [add_zero] at hab
      rw [decompose_of_mem_same _ ha, decompose_of_mem_same _ hb, decompose_of_mem_same _ hab']
    · rw [decompose_of_mem_ne _ hab (by rwa [zero_add]), decompose_of_mem_ne _ hb hq, mul_zero]
  · rw [decompose_of_mem_ne _ ha hp, zero_mul]
    by_cases hpq : p + q = 0
    · have hq : q ≠ 0 := by
        rintro rfl
        exact hp (by rwa [add_zero] at hpq)
      by_cases hpk : p.1 < k
      · have ha0 : a = 0 := hH.eq_zero_of_lt (j := p.1) (ε := p.2) hpk hp ha
        rw [ha0, zero_mul, decompose_zero, DirectSum.zero_apply, ZeroMemClass.coe_zero]
      · by_cases hqk : q.1 < k
        · have hb0 : b = 0 := hH.eq_zero_of_lt (j := q.1) (ε := q.2) hqk hq hb
          rw [hb0, mul_zero, decompose_zero, DirectSum.zero_apply, ZeroMemClass.coe_zero]
        · exfalso
          have h1 : p.1 + q.1 = 0 := congrArg Prod.fst hpq
          have := hH.pos
          omega
    · exact decompose_of_mem_ne _ hab hpq

/-- The component of bidegree `(0, 0̄)` is multiplicative. -/
theorem coe_decompose_mul_zero (a b : A) :
    (decompose H.hgrading (a * b) 0 : A) =
      decompose H.hgrading a 0 * decompose H.hgrading b 0 := by
  refine DirectSum.Decomposition.inductionOn H.hgrading
    (motive := fun a => (decompose H.hgrading (a * b) 0 : A) =
      decompose H.hgrading a 0 * decompose H.hgrading b 0) ?_ (fun {p} x => ?_)
    (fun x y hx hy => ?_) a
  · simp
  · refine DirectSum.Decomposition.inductionOn H.hgrading
      (motive := fun b => (decompose H.hgrading ((x : A) * b) 0 : A) =
        decompose H.hgrading (x : A) 0 * decompose H.hgrading b 0) ?_ (fun {q} y => ?_)
      (fun y z hy hz => ?_) b
    · simp
    · exact hH.coe_decompose_mul_zero_of_mem x.2 y.2
    · simp only [mul_add, decompose_add, DirectSum.add_apply, AddSubgroup.coe_add, hy, hz]
  · simp only [add_mul, decompose_add, DirectSum.add_apply, AddSubgroup.coe_add, hx, hy]

/-- The component of bidegree `(0, 0̄)` of a boundary vanishes. -/
theorem coe_decompose_hd_zero (a : A) : (decompose H.hgrading (H.hd a) 0 : A) = 0 := by
  refine DirectSum.Decomposition.inductionOn H.hgrading
    (motive := fun a => (decompose H.hgrading (H.hd a) 0 : A) = 0) ?_ (fun {p} x => ?_)
    (fun x y hx hy => ?_) a
  · simp
  · have hx : H.hd x ∈ H.hgrading (p.1 + k, p.2 + 1) := H.hd_mem (j := p.1) (ε := p.2) x.2
    by_cases h0 : (p.1 + k, p.2 + 1) = (0 : ℤ × ZMod 2)
    · have hk := hH.pos
      have h1 : p.1 + k = 0 := congrArg Prod.fst h0
      have hx0 : (x : A) = 0 := hH.eq_zero_of_lt (j := p.1) (ε := p.2) (by omega) (fun hp => by
        have h2 : p.1 = 0 := congrArg Prod.fst hp
        omega) x.2
      rw [hx0, map_zero, decompose_zero, DirectSum.zero_apply, ZeroMemClass.coe_zero]
    · exact decompose_of_mem_ne _ hx h0
  · simp only [map_add, decompose_add, DirectSum.add_apply, AddSubgroup.coe_add, hx, hy,
      add_zero]

/-! ### The inclusion of and the projection onto `A⁰` -/

/-- The inclusion `A⁰ → A` of `A⁰ = A^{0,0̄}`, a morphism of half-graded dg rings. -/
def incl : Hom H.degreeZeroPart H where
  toRingHom := H.zeroSubring.subtype
  map_mem' := by
    intro p a ha
    rcases mem_degreeZeroGrading_iff.mp ha with rfl | rfl
    · exact mem_zeroSubring.mp a.2
    · exact zero_mem _
  map_hd' a := (hH.hd_eq_zero (mem_zeroSubring.mp a.2)).symm

/-- The projection `A → A⁰` onto the component of bidegree `(0, 0̄)`, a morphism of half-graded dg
rings: it is multiplicative because the internal degrees of `A` are `0` or at least `k > 0`, and
commutes with the differentials because `A` has no component of internal degree `-k`. -/
def proj : Hom H H.degreeZeroPart where
  toFun a := ⟨(decompose H.hgrading a 0 : A), mem_zeroSubring.mpr (decompose H.hgrading a 0).2⟩
  map_one' := Subtype.ext (decompose_of_mem_same _ SetLike.GradedOne.one_mem)
  map_mul' a b := Subtype.ext (hH.coe_decompose_mul_zero a b)
  map_zero' := Subtype.ext (by simp)
  map_add' a b := Subtype.ext (by simp)
  map_mem' := by
    intro p a ha
    refine mem_degreeZeroGrading_iff.mpr ?_
    by_cases hp : p = 0
    · exact Or.inl hp
    · exact Or.inr (Subtype.ext (decompose_of_mem_ne _ ha hp))
  map_hd' a := Subtype.ext (hH.coe_decompose_hd_zero a)

theorem coe_incl_apply (a : H.zeroSubring) : hH.incl a = (a : A) :=
  rfl

theorem coe_proj_apply (a : A) : (hH.proj a : A) = decompose H.hgrading a 0 :=
  rfl

/-- The projection `A → A⁰` is a retraction of the inclusion `A⁰ → A`. -/
theorem proj_comp_incl : hH.proj.comp hH.incl = Hom.id H.degreeZeroPart :=
  Hom.ext fun a => Subtype.ext (decompose_of_mem_same _ (mem_zeroSubring.mp a.2))

/-- The composite `A → A⁰ → A` is the identity on bihomogeneous elements of the regraded ring of
cohomological degree `0` and weight `0`. -/
theorem regraded_incl_regraded_proj {x : H.Regraded} (hx : x ∈ grading 0)
    (hw : x ∈ wgrading 0) : hH.incl.regraded (hH.proj.regraded x) = x := by
  obtain ⟨a, ha, rfl⟩ := exists_eq_place hx hw
  have h0 : halfDegree k ((0 : ℤ), (0 : ℤ)) = 0 := map_zero (halfDegree k)
  have ha0 : a ∈ H.hgrading 0 := by
    rw [← h0]
    exact ha
  rw [Hom.regraded_place, Hom.regraded_place]
  exact place_congr rfl (decompose_of_mem_same H.hgrading ha0) _ _

/-- A degree-`0` idempotent cocycle of an object of `C_H` is fixed by `C_H ⥤ C_{H⁰} ⥤ C_H`. -/
theorem map_proj_map_incl {X : WeightCategory H.Regraded} (e : DGCategory.Idempotent X) :
    (e.map hH.proj.weightFunctor).map hH.incl.weightFunctor = e :=
  WeightCategory.idempotent_ext (hH.regraded_incl_regraded_proj (x := e.val.1)
    (WeightCategory.mem_grading_iff.mp e.mem_grading)
    (WeightCategory.mem_wgrading_of_eq (sub_self _) e.val.2))

end IsPositive

/-! ### The positive model -/

variable (H) in
/-- The family `w ↦ (w, -⌊w / k⌋)` of formal shifts of the objects of `C_H`. -/
def shiftFamily (X : WeightCategory H.Regraded) : WeightCategory H.Regraded × ℤ :=
  (X, -(X.as / k))

variable (H) in
/-- The dg category of the formal shifts `w[-⌊w / k⌋]` of the objects of `C_H`; it is positive
when `H` is. -/
abbrev PositiveModel : Type u := ShiftedObjects H.shiftFamily

/-- The bidegree (cohomological degree, weight) in the regraded ring of the morphisms `i ⟶ j` of
degree `n` of the positive model. -/
def bidegree (i j : PositiveModel H) (n : ℤ) : ℤ × ℤ :=
  (n + ((H.shiftFamily j.as).2 - (H.shiftFamily i.as).2), j.as.as - i.as.as)

theorem bidegree_swap (i j : PositiveModel H) : bidegree j i 0 = -bidegree i j 0 :=
  Prod.ext (by
    change 0 + ((H.shiftFamily i.as).2 - (H.shiftFamily j.as).2) =
      -(0 + ((H.shiftFamily j.as).2 - (H.shiftFamily i.as).2))
    ring) (by
    change i.as.as - j.as.as = -(j.as.as - i.as.as)
    ring)

/-- The internal degree of the morphisms `i ⟶ j` of degree `n` of the positive model. -/
theorem halfDegree_bidegree_fst (i j : PositiveModel H) (n : ℤ) :
    (halfDegree k (bidegree i j n)).1 = j.as.as % k - i.as.as % k + n * k := by
  change j.as.as - i.as.as + (n + (-(j.as.as / k) - -(i.as.as / k))) * k = _
  rw [Int.emod_def, Int.emod_def]
  ring

/-- A morphism `i ⟶ j` of degree `n` of the positive model is an element of `A` placed in
bidegree `bidegree i j n`. -/
theorem exists_eq_place_of_mem_grading {i j : PositiveModel H} {n : ℤ} {f : i ⟶ j}
    (hf : f ∈ grading n) :
    ∃ (a : A) (ha : a ∈ H.hgrading (halfDegree k (bidegree i j n))),
      (ShiftedObjects.homVal f).1 = H.place (bidegree i j n) a ha :=
  exists_eq_place (x := (ShiftedObjects.homVal f).1)
    (n := n + ((H.shiftFamily j.as).2 - (H.shiftFamily i.as).2)) (w := j.as.as - i.as.as)
    (WeightCategory.mem_grading_iff.mp (ShiftedObjects.mem_grading_iff.mp hf))
    (ShiftedObjects.homVal f).2

namespace IsPositive

variable (hH : H.IsPositive)
include hH

/-- A nonzero morphism of degree `n ≤ 0` of the positive model has degree `0`, and is an element
of `A^{0,0̄}`. -/
theorem eq_zero_and_halfDegree_eq_zero {i j : PositiveModel H} {n : ℤ} {f : i ⟶ j}
    (hf : f ∈ grading n) (hn : n ≤ 0) (hf0 : f ≠ 0) :
    n = 0 ∧ halfDegree k (bidegree i j n) = 0 := by
  obtain ⟨a, ha, hfa⟩ := exists_eq_place_of_mem_grading hf
  have hk := hH.pos
  have ha0 : a ≠ 0 := by
    rintro rfl
    exact hf0 (ShiftedObjects.hom_ext (WeightCategory.hom_ext (hfa.trans (place_zero _))))
  have h1 := halfDegree_bidegree_fst i j n
  have hj := Int.emod_lt_of_pos j.as.as hk
  have hi := Int.emod_nonneg i.as.as hk.ne'
  have hnk : n * k ≤ 0 := by
    have := mul_nonneg (neg_nonneg.mpr hn) hk.le
    linarith
  have hz : halfDegree k (bidegree i j n) = 0 := by
    by_contra h
    exact ha0 (hH.eq_zero_of_lt (j := (halfDegree k (bidegree i j n)).1)
      (ε := (halfDegree k (bidegree i j n)).2) (by rw [h1]; linarith) h ha)
  refine ⟨?_, hz⟩
  by_contra hn0
  have hn1 : n ≤ -1 := by omega
  have h2 : n * k ≤ -1 * k := mul_le_mul_of_nonneg_right hn1 hk.le
  have h3 : (halfDegree k (bidegree i j n)).1 = 0 := congrArg Prod.fst hz
  rw [h1] at h3
  linarith

/-- An idempotent `s` of `A^{0,0̄}` with `A⁰ s` simple gives a simple idempotent of every object
of the positive model. -/
theorem isSimple_idempotentMk (i : PositiveModel H) {s : H.zeroSubring}
    (hs : IsIdempotentElem s)
    (hss : IsSimpleModule H.zeroSubring (Submodule.span H.zeroSubring {s})) :
    (ShiftedObjects.idempotentMk (i := i) (hH.idem i.as s hs)).IsSimple := by
  refine ⟨fun h0 => ?_, fun j h hh heh hh0 => ?_⟩
  · have h0' : H.zeroHom i.as s = 0 := h0
    exact ne_zero_of_isSimpleModule hss
      (zeroHom_injective i.as (h0'.trans (map_zero (H.zeroHom i.as)).symm))
  obtain ⟨a, ha, hfa⟩ := exists_eq_place_of_mem_grading hh
  obtain ⟨-, hz⟩ := hH.eq_zero_and_halfDegree_eq_zero hh le_rfl hh0
  have ha' : a ∈ H.hgrading 0 := by
    rw [← hz]
    exact ha
  have ha0 : a ≠ 0 := by
    rintro rfl
    exact hh0 (ShiftedObjects.hom_ext (WeightCategory.hom_ext (hfa.trans (place_zero _))))
  have hmem : a * (s : A) ∈ H.hgrading (halfDegree k (bidegree i j 0)) := by
    rw [hz]
    exact mem_zeroSubring.mp (H.zeroSubring.mul_mem (mem_zeroSubring.mpr ha') s.2)
  have has : a * (s : A) = a := by
    have h1 : (ShiftedObjects.homVal h).1 * (H.zeroHom i.as s).1 = (ShiftedObjects.homVal h).1 :=
      congrArg (fun f : i ⟶ j => (ShiftedObjects.homVal f).1) heh
    rw [hfa, zeroHom_val, place_mul_place] at h1
    exact place_injective ((place_congr (add_zero _) rfl _ hmem).symm.trans h1)
  let x : H.zeroSubring := ⟨a, mem_zeroSubring.mpr ha'⟩
  have hx0 : x ≠ 0 := fun h => ha0 (congrArg Subtype.val h)
  have hxs : x ∈ Submodule.span H.zeroSubring {s} :=
    (mem_span_singleton_iff_mul_eq hs).mpr (Subtype.ext has)
  have hat := isSimpleModule_iff_isAtom.mp hss
  have hle : Submodule.span H.zeroSubring {x} ≤ Submodule.span H.zeroSubring {s} :=
    (Submodule.span_singleton_le_iff_mem _ _).mpr hxs
  rcases hat.le_iff.mp hle with h' | h'
  · exact absurd (Submodule.span_singleton_eq_bot.mp h') hx0
  · have hsx : s ∈ Submodule.span H.zeroSubring {x} := by
      rw [h']
      exact Submodule.mem_span_singleton_self _
    obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hsx
    have hcmem : (c : A) ∈ H.hgrading (halfDegree k (bidegree j i 0)) := by
      rw [bidegree_swap i j, map_neg, hz, neg_zero]
      exact mem_zeroSubring.mp c.2
    have he : (ShiftedObjects.homVal
        (ShiftedObjects.idempotentMk (i := i) (hH.idem i.as s hs)).val).1 =
        H.place 0 s (by rw [map_zero]; exact mem_zeroSubring.mp s.2) := rfl
    refine ⟨ShiftedObjects.homMk ⟨H.place (bidegree j i 0) c hcmem,
        place_mem_wgrading (H := H) (bidegree j i 0) hcmem⟩,
      ShiftedObjects.mem_grading_iff.mpr (WeightCategory.mem_grading_iff.mpr
        (place_mem_grading (H := H) (bidegree j i 0) hcmem)), ?_⟩
    refine ShiftedObjects.hom_ext (WeightCategory.hom_ext ?_)
    exact ((congrArg (fun y => H.place (bidegree j i 0) c hcmem * y) hfa).trans
      ((place_mul_place hcmem ha).trans
        (place_congr (by rw [bidegree_swap i j, neg_add_cancel]) (congrArg Subtype.val hc)
          _ _))).trans he.symm

/-- The degree-`0` category of the positive model is semisimple. -/
theorem isDegreeZeroSemisimple : DGCategory.IsDegreeZeroSemisimple (PositiveModel H) := by
  intro i
  have := hH.isSemisimple
  obtain ⟨l, hl, hlp, hlsum⟩ :=
    exists_list_sum_eq_of_isSemisimpleRing (R := H.zeroSubring) IsIdempotentElem.one
  let E : ∀ s ∈ l, DGCategory.Idempotent i := fun s hs =>
    ShiftedObjects.idempotentMk (i := i) (hH.idem i.as s (hl s hs).1)
  refine ⟨l.pmap E fun _ h => h, fun e he => ?_, ?_, ?_⟩
  · obtain ⟨s, hs, rfl⟩ := List.mem_pmap.mp he
    exact hH.isSimple_idempotentMk i (hl s hs).1 (hl s hs).2.1
  · rw [List.pairwise_pmap]
    refine hlp.imp_of_mem fun {a b} _ _ hab _ _ => ?_
    refine ⟨ShiftedObjects.hom_ext ?_, ShiftedObjects.hom_ext ?_⟩
    · change H.zeroHom i.as a ≫ H.zeroHom i.as b = 0
      rw [zeroHom_comp, hab.2, map_zero]
    · change H.zeroHom i.as b ≫ H.zeroHom i.as a = 0
      rw [zeroHom_comp, hab.1, map_zero]
  · rw [List.map_pmap]
    let ψ : H.zeroSubring →+ (i ⟶ i) :=
      { toFun := fun s => ShiftedObjects.homMk (H.zeroHom i.as s)
        map_zero' := ShiftedObjects.hom_ext (map_zero (H.zeroHom i.as))
        map_add' := fun s t => ShiftedObjects.hom_ext (map_add (H.zeroHom i.as) s t) }
    change (l.pmap (fun (s : H.zeroSubring) (_ : s ∈ l) => ψ s) fun _ h => h).sum = 𝟙 i
    rw [List.pmap_eq_map, ← map_list_sum, hlsum]
    exact ShiftedObjects.hom_ext (zeroHom_one i.as)

/-- The dg category of the formal shifts `w[-⌊w / k⌋]` of the objects of `C_H` is positive, for a
positive half-graded dg ring `H`. -/
theorem isPositive_positiveModel : DGCategory.IsPositive (PositiveModel H) where
  eq_zero_of_neg := by
    intro i j n hn f hf
    by_contra hf0
    have := (hH.eq_zero_and_halfDegree_eq_zero hf hn.le hf0).1
    omega
  semisimple := hH.isDegreeZeroSemisimple
  d_eq_zero := by
    intro i j f hf
    by_cases hf0 : f = 0
    · rw [hf0, d_zero]
    obtain ⟨a, ha, hfa⟩ := exists_eq_place_of_mem_grading hf
    have hz := (hH.eq_zero_and_halfDegree_eq_zero hf le_rfl hf0).2
    have ha' : a ∈ H.hgrading 0 := by
      rw [← hz]
      exact ha
    have hd : d (ShiftedObjects.homVal f) = 0 := WeightCategory.hom_ext (by
      rw [WeightCategory.d_val, hfa, d_place]
      exact (place_congr rfl (hH.hd_eq_zero ha') _ _).trans (place_zero _))
    refine ShiftedObjects.hom_ext ?_
    rw [ShiftedObjects.homVal_d]
    exact (congrArg _ hd).trans (smul_zero _)

/-! ### Generators of `K₀` -/

variable [CatModule.HasDerivedCategory.{max u w, max u w} (WeightCategory H.Regraded)]

/-- For a positive half-graded dg ring `H`, `K₀(C_H) = K₀(D^c(C_H))` is generated by the classes
of the modules `e · C_H(w, -)`, for the degree-`0` idempotent cocycles `e` of the objects `w` of
`C_H` (the idempotents of `A^{0,0̄}`). -/
theorem closure_cell_eq_top :
    AddSubgroup.closure (Set.range fun c : DGCategory.Corner (WeightCategory H.Regraded) =>
      DGCategory.K0.cell.{max u w} c.2 0) = ⊤ := by
  refine eq_top_iff.mpr (le_trans (le_of_eq (ShiftedObjects.closure_cell_eq_top_of_isPositive.{w}
    H.shiftFamily (fun Y => ⟨Y, rfl⟩) hH.isPositive_positiveModel).symm)
    (AddSubgroup.closure_mono ?_))
  rintro _ ⟨c, rfl⟩
  exact ⟨⟨_, ShiftedObjects.idempotentVal c.1.2⟩, rfl⟩

/-! ### `K₀(A) ≅ K₀(A⁰)` -/

variable [CatModule.HasDerivedCategory.{max u w, max u w}
  (WeightCategory H.degreeZeroPart.Regraded)]

theorem K0Map_proj_K0Map_incl
    (x : DGCategory.K0.{max u w, max u w} (WeightCategory H.degreeZeroPart.Regraded)) :
    hH.proj.K0Map.{w} (hH.incl.K0Map.{w} x) = x := by
  rw [Hom.K0Map_apply, Hom.K0Map_apply, ← AddMonoidHom.comp_apply, ← DGCategory.K0.map_comp,
    ← Hom.weightFunctor_comp, hH.proj_comp_incl, Hom.weightFunctor_id, DGCategory.K0.map_id,
    AddMonoidHom.id_apply]

theorem K0Map_incl_K0Map_proj
    (x : DGCategory.K0.{max u w, max u w} (WeightCategory H.Regraded)) :
    hH.incl.K0Map.{w} (hH.proj.K0Map.{w} x) = x := by
  have hx : x ∈ AddSubgroup.closure
      (Set.range fun c : DGCategory.Corner (WeightCategory H.Regraded) =>
        DGCategory.K0.cell.{max u w} c.2 0) := by
    rw [hH.closure_cell_eq_top.{w}]
    trivial
  induction hx using AddSubgroup.closure_induction with
  | mem y hy =>
    obtain ⟨c, rfl⟩ := hy
    exact ((congrArg (fun y => hH.incl.K0Map.{w} y)
      (DGCategory.K0.map_cell.{max u w} hH.proj.weightFunctor c.2)).trans
      (DGCategory.K0.map_cell.{max u w} hH.incl.weightFunctor
        (c.2.map hH.proj.weightFunctor))).trans
      (congrArg (fun e => DGCategory.K0.cell.{max u w} e 0) (hH.map_proj_map_incl c.2))
  | zero => rw [map_zero, map_zero]
  | add x y _ _ hx hy => rw [map_add, map_add, hx, hy]
  | neg x _ hx => rw [map_neg, map_neg, hx]

/-- **`K₀(A) ≅ K₀(A⁰)` for a positive half-graded dg ring**, as `ℤ[q, q⁻¹]`-modules (`qⁿ` acting
by the internal shift `⟨n⟩`): the isomorphism `K₀(C_H) ≃ K₀(C_{H⁰})` is induced by the projection
`A → A⁰ = A^{0,0̄}`, with inverse induced by the inclusion `A⁰ → A` (derived induction between
the weight dg categories). It sends `[e · C_H(w, -)]` to `[e · C_{H⁰}(w, -)]`
(`DG.HalfGradedDGRing.IsPositive.K0DegreeZeroEquiv_cell`). -/
def K0DegreeZeroEquiv :
    DGCategory.K0.{max u w, max u w} (WeightCategory H.Regraded) ≃ₗ[LaurentPolynomial ℤ]
      DGCategory.K0.{max u w, max u w} (WeightCategory H.degreeZeroPart.Regraded) :=
  { hH.proj.K0Map.{w} with
    invFun := hH.incl.K0Map.{w}
    left_inv := hH.K0Map_incl_K0Map_proj
    right_inv := hH.K0Map_proj_K0Map_incl }

theorem K0DegreeZeroEquiv_apply
    (x : DGCategory.K0.{max u w, max u w} (WeightCategory H.Regraded)) :
    hH.K0DegreeZeroEquiv x = hH.proj.K0Map.{w} x :=
  rfl

theorem K0DegreeZeroEquiv_symm_apply
    (x : DGCategory.K0.{max u w, max u w} (WeightCategory H.degreeZeroPart.Regraded)) :
    hH.K0DegreeZeroEquiv.symm x = hH.incl.K0Map.{w} x :=
  rfl

/-- `K₀(C_H) ≅ K₀(C_{H⁰})` sends `[e · C_H(w, -)]` to `[e · C_{H⁰}(w, -)]`. -/
theorem K0DegreeZeroEquiv_cell {X : WeightCategory H.Regraded} (e : DGCategory.Idempotent X) :
    hH.K0DegreeZeroEquiv (DGCategory.K0.cell.{max u w} e 0) =
      DGCategory.K0.cell.{max u w} (e.map hH.proj.weightFunctor) 0 :=
  DGCategory.K0.map_cell.{max u w} _ e

theorem K0DegreeZeroEquiv_symm_cell {X : WeightCategory H.degreeZeroPart.Regraded}
    (e : DGCategory.Idempotent X) :
    hH.K0DegreeZeroEquiv.symm (DGCategory.K0.cell.{max u w} e 0) =
      DGCategory.K0.cell.{max u w} (e.map hH.incl.weightFunctor) 0 :=
  DGCategory.K0.map_cell.{max u w} _ e

end IsPositive

end HalfGradedDGRing

end DG

end
