import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Mathlib.Order.CompactlyGenerated.Basic
import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal
import Mathlib.RingTheory.SimpleModule.Basic
import DG.Positive.Idempotent

/-!
# Graded semisimple rings

Let `R` be a ring with a `ℤ`-grading `𝒜` (`GradedRing 𝒜`). We call `R` *graded semisimple*
(`DG.IsGradedSemisimpleRing 𝒜`) if the lattice of homogeneous left ideals of `R` (Mathlib's
`HomogeneousIdeal 𝒜`; `Ideal R` is the type of left ideals) is complemented: `R` is a semisimple
object of the category of graded left `R`-modules. This is the graded analogue of Mathlib's
`IsSemisimpleRing` (complementedness of the lattice of left ideals); equivalently every graded
`R`-module is a direct sum of graded simple modules.

An idempotent `e ∈ R₀` is *graded simple* (`DG.IsGradedSimpleIdempotent 𝒜 e`) if `e ≠ 0` and
every nonzero homogeneous `h ∈ R e` generates `e`, i.e. `g h = e` for a homogeneous `g`: the graded
left ideal `R e` is a graded simple module.

## Main results

* `DG.HomogeneousIdeal.isModularLattice`, `DG.HomogeneousIdeal.isCompactlyGenerated`: the lattice
  of homogeneous left ideals is modular and compactly generated (by the left ideals generated by
  one homogeneous element), and `⊤ = R 1` is compact.
* `DG.IsGradedSemisimpleRing.exists_list_sum_eq_one`: in a graded semisimple ring, `1` is the sum
  of a list of pairwise orthogonal graded simple idempotents of degree `0`.
* `DG.isGradedSemisimpleRing_iff_exists_list`: conversely such a decomposition of `1` makes `R`
  graded semisimple.
* `DG.isGradedSemisimpleRing_of_isSemisimpleRing`: a semisimple ring is graded semisimple for
  every grading. The projection of `R` onto a homogeneous left ideal `I` along a complement is
  right multiplication by an idempotent `e`; its degree-`0` component `e₀` is again an idempotent
  generating `I`, and `R (1 - e₀)` is a homogeneous complement of `I`.
* `DG.isSemisimpleRing_of_isGradedSemisimpleRing`: conversely, a graded semisimple ring whose
  grading is bounded below is semisimple: a graded simple idempotent `e` of degree `0` generates a
  simple left ideal (`DG.isSimpleModule_of_isGradedSimpleIdempotent`; elements of negative degrees
  are nilpotent). In particular (`DG.isGradedSemisimpleRing_iff_isSemisimpleRing`) for a
  finite-dimensional graded algebra over a field the two notions coincide
  (`DG.exists_forall_lt_eq_zero_of_finiteDimensional`).
-/

open DirectSum

namespace DG

variable {R : Type*} [Ring R] (𝒜 : ℤ → AddSubgroup R) [GradedRing 𝒜]

/-! ### The lattice of homogeneous left ideals -/

namespace HomogeneousIdeal

/-- The homogeneous left ideal `R a` generated by a homogeneous element `a`. -/
def spanSingleton {a : R} {i : ℤ} (ha : a ∈ 𝒜 i) : _root_.HomogeneousIdeal 𝒜 where
  toSubmodule := Ideal.span {a}
  is_homogeneous' := Ideal.homogeneous_span 𝒜 {a} (by
    rintro x rfl
    exact ⟨i, ha⟩)

variable {𝒜}

@[simp]
theorem toIdeal_spanSingleton {a : R} {i : ℤ} (ha : a ∈ 𝒜 i) :
    (spanSingleton 𝒜 ha).toIdeal = Ideal.span {a} :=
  rfl

theorem le_iff_toIdeal_le {I J : _root_.HomogeneousIdeal 𝒜} : I ≤ J ↔ I.toIdeal ≤ J.toIdeal :=
  Iff.rfl

variable (𝒜)

/-- The lattice of homogeneous left ideals is modular (it is a sublattice of the modular lattice
of left ideals). -/
instance isModularLattice : IsModularLattice (_root_.HomogeneousIdeal 𝒜) :=
  ⟨fun {x} y {z} hxz => by
    rw [le_iff_toIdeal_le, HomogeneousIdeal.toIdeal_inf, HomogeneousIdeal.toIdeal_sup,
      HomogeneousIdeal.toIdeal_sup, HomogeneousIdeal.toIdeal_inf]
    exact IsModularLattice.sup_inf_le_assoc_of_le _ (le_iff_toIdeal_le.mp hxz)⟩

variable {𝒜}

/-- The homogeneous left ideal generated by a homogeneous element is compact. -/
theorem isCompactElement_spanSingleton {a : R} {i : ℤ} (ha : a ∈ 𝒜 i) :
    IsCompactElement (spanSingleton 𝒜 ha) := by
  rw [isCompactElement_iff_le_of_directed_sSup_le]
  intro D hne hdir hle
  have hmem : a ∈ (sSup D).toIdeal := le_iff_toIdeal_le.mp hle (Ideal.subset_span rfl)
  rw [HomogeneousIdeal.toIdeal_sSup, ← sSup_image] at hmem
  obtain ⟨y, ⟨x, hx, rfl⟩, hay⟩ := (Submodule.mem_sSup_of_directed (hne.image _)
    (directedOn_image.mpr (hdir.mono fun _ _ h => le_iff_toIdeal_le.mp h))).mp hmem
  exact ⟨x, hx, le_iff_toIdeal_le.mpr ((Ideal.span_singleton_le_iff_mem _).mpr hay)⟩

variable (𝒜)

theorem spanSingleton_one : spanSingleton 𝒜 (SetLike.GradedOne.one_mem (A := 𝒜)) = ⊤ :=
  HomogeneousIdeal.ext (by
    rw [toIdeal_spanSingleton, HomogeneousIdeal.toIdeal_top, Ideal.span_singleton_one])

theorem isCompactElement_top : IsCompactElement (⊤ : _root_.HomogeneousIdeal 𝒜) := by
  rw [← spanSingleton_one]
  exact isCompactElement_spanSingleton _

/-- The lattice of homogeneous left ideals is compactly generated, by the homogeneous left ideals
generated by one homogeneous element. -/
instance isCompactlyGenerated : IsCompactlyGenerated (_root_.HomogeneousIdeal 𝒜) := by
  refine ⟨fun I => ⟨{J | ∃ (a : R) (i : ℤ) (ha : a ∈ 𝒜 i), a ∈ I ∧ spanSingleton 𝒜 ha = J},
    ?_, le_antisymm (sSup_le ?_) ?_⟩⟩
  · rintro _ ⟨a, i, ha, -, rfl⟩
    exact isCompactElement_spanSingleton ha
  · rintro _ ⟨a, i, ha, haI, rfl⟩
    exact le_iff_toIdeal_le.mpr ((Ideal.span_singleton_le_iff_mem _).mpr haI)
  · intro b hb
    classical
    rw [← DirectSum.sum_support_decompose 𝒜 b]
    refine sum_mem fun i _ => ?_
    have hbi : (decompose 𝒜 b i : R) ∈ I := I.isHomogeneous i hb
    have hle : spanSingleton 𝒜 (decompose 𝒜 b i).2 ≤
        sSup {J | ∃ (a : R) (i : ℤ) (ha : a ∈ 𝒜 i), a ∈ I ∧ spanSingleton 𝒜 ha = J} :=
      le_sSup ⟨_, i, (decompose 𝒜 b i).2, hbi, rfl⟩
    exact hle (Ideal.subset_span rfl)

end HomogeneousIdeal

/-! ### Graded semisimple rings and graded simple idempotents -/

/-- A `ℤ`-graded ring is *graded semisimple* if its lattice of homogeneous left ideals is
complemented (equivalently, every graded left module is a direct sum of graded simple
modules). -/
def IsGradedSemisimpleRing : Prop :=
  ComplementedLattice (HomogeneousIdeal 𝒜)

/-- An idempotent `e` is *graded simple* if `e ≠ 0` and every nonzero homogeneous `h` with
`h e = h` (i.e. `h ∈ R e`) satisfies `g h = e` for some homogeneous `g` (of the opposite degree):
the graded left ideal `R e` is a graded simple module. -/
def IsGradedSimpleIdempotent (e : R) : Prop :=
  e ≠ 0 ∧ ∀ ⦃j : ℤ⦄ ⦃h : R⦄, h ∈ 𝒜 j → h * e = h → h ≠ 0 → ∃ g ∈ 𝒜 (-j), g * h = e

section Split

variable {𝒜}

/-- A left ideal generated by an idempotent `g` which is the direct sum of two left ideals `S`,
`T` is generated by two orthogonal idempotents `s ∈ S`, `t ∈ T` with `s + t = g`. -/
theorem exists_add_of_inf_eq_bot {g : R} (hg : IsIdempotentElem g) {S T : Ideal R}
    (hST : S ⊓ T = ⊥) (hsup : S ⊔ T = Ideal.span {g}) :
    ∃ s t : R, s ∈ S ∧ t ∈ T ∧ s + t = g ∧ IsIdempotentElem s ∧ IsIdempotentElem t ∧
      s * t = 0 ∧ t * s = 0 ∧ Ideal.span {s} = S ∧ Ideal.span {t} = T := by
  have hgmem : g ∈ S ⊔ T := hsup ▸ Ideal.subset_span rfl
  obtain ⟨s, hs, t, ht, hst⟩ := Submodule.mem_sup.mp hgmem
  have hdisj : ∀ x, x ∈ S → x ∈ T → x = 0 := fun x hxS hxT => by
    have : x ∈ S ⊓ T := ⟨hxS, hxT⟩
    rwa [hST, Submodule.mem_bot] at this
  have hmem : ∀ x ∈ S ⊔ T, x * g = x := fun x hx =>
    (mem_span_singleton_iff_mul_eq hg).mp (show x ∈ Ideal.span {g} by rw [← hsup]; exact hx)
  have hsplit : ∀ x ∈ S ⊔ T, x * s + x * t = x := fun x hx => by
    rw [← mul_add, hst, hmem x hx]
  have hS : ∀ x ∈ S, x * s = x ∧ x * t = 0 := fun x hx => by
    have h := hsplit x (Submodule.mem_sup_left hx)
    have h0 : x * t = 0 := hdisj _ (by
      rw [eq_sub_of_add_eq' h]
      exact S.sub_mem hx (S.smul_mem x hs)) (T.smul_mem x ht)
    exact ⟨by rw [h0, add_zero] at h; exact h, h0⟩
  have hT : ∀ x ∈ T, x * t = x ∧ x * s = 0 := fun x hx => by
    have h := hsplit x (Submodule.mem_sup_right hx)
    have h0 : x * s = 0 := hdisj _ (S.smul_mem x hs) (by
      rw [eq_sub_of_add_eq h]
      exact T.sub_mem hx (T.smul_mem x ht))
    exact ⟨by rw [h0, zero_add] at h; exact h, h0⟩
  have hsI : IsIdempotentElem s := (hS s hs).1
  have htI : IsIdempotentElem t := (hT t ht).1
  refine ⟨s, t, hs, ht, hst, hsI, htI, (hS s hs).2, (hT t ht).2, ?_, ?_⟩
  · refine le_antisymm ((Ideal.span_singleton_le_iff_mem _).mpr hs) fun x hx => ?_
    exact (mem_span_singleton_iff_mul_eq hsI).mpr (hS x hx).1
  · refine le_antisymm ((Ideal.span_singleton_le_iff_mem _).mpr ht) fun x hx => ?_
    exact (mem_span_singleton_iff_mul_eq htI).mpr (hT x hx).1

/-- In the situation of `DG.exists_add_of_inf_eq_bot`, if `S` and `T` are homogeneous and `g` has
degree `0`, then so have `s` and `t`. -/
theorem mem_zero_of_add_eq {S T : HomogeneousIdeal 𝒜} (hST : S ⊓ T = ⊥) {s t g : R}
    (hs : s ∈ S) (ht : t ∈ T) (hg : g ∈ 𝒜 0) (hsum : s + t = g) : s ∈ 𝒜 0 ∧ t ∈ 𝒜 0 := by
  classical
  set s₀ := (decompose 𝒜 s 0 : R)
  set t₀ := (decompose 𝒜 t 0 : R)
  have hs₀ : s₀ ∈ S := S.isHomogeneous 0 hs
  have ht₀ : t₀ ∈ T := T.isHomogeneous 0 ht
  have h0 : s₀ + t₀ = g := by
    rw [← decompose_of_mem_same 𝒜 hg, ← hsum, decompose_add, add_apply, AddMemClass.coe_add]
  have hd : s - s₀ = t₀ - t := by
    rw [sub_eq_sub_iff_add_eq_add, hsum, add_comm, h0]
  have hmem : s - s₀ ∈ S.toIdeal ⊓ T.toIdeal :=
    ⟨S.toIdeal.sub_mem hs hs₀, hd ▸ T.toIdeal.sub_mem ht₀ ht⟩
  rw [← HomogeneousIdeal.toIdeal_inf, hST, HomogeneousIdeal.toIdeal_bot] at hmem
  have hs' : s = s₀ := sub_eq_zero.mp ((Submodule.mem_bot R).mp hmem)
  have ht' : t = t₀ := by
    rw [hs', sub_self] at hd
    exact (sub_eq_zero.mp hd.symm).symm
  exact ⟨hs' ▸ SetLike.coe_mem _, ht' ▸ SetLike.coe_mem _⟩

/-- If `R s` is an atom of the lattice of homogeneous left ideals, the idempotent `s` of degree `0`
is graded simple. -/
theorem isGradedSimpleIdempotent_of_isAtom {s : R} (hs0 : s ∈ 𝒜 0) (hs : IsIdempotentElem s)
    (hat : IsAtom (HomogeneousIdeal.spanSingleton 𝒜 hs0)) : IsGradedSimpleIdempotent 𝒜 s := by
  classical
  refine ⟨fun h => hat.1 (HomogeneousIdeal.ext ?_), fun j h hh hhs hh0 => ?_⟩
  · rw [HomogeneousIdeal.toIdeal_spanSingleton, h, Set.singleton_zero, Ideal.span_zero]
    rfl
  · have hle : HomogeneousIdeal.spanSingleton 𝒜 hh ≤ HomogeneousIdeal.spanSingleton 𝒜 hs0 :=
      HomogeneousIdeal.le_iff_toIdeal_le.mpr ((Ideal.span_singleton_le_iff_mem _).mpr
        ((mem_span_singleton_iff_mul_eq hs).mpr hhs))
    rcases hat.le_iff.mp hle with h' | h'
    · exfalso
      apply hh0
      have : h ∈ (HomogeneousIdeal.spanSingleton 𝒜 hh).toIdeal := Ideal.subset_span rfl
      rw [h'] at this
      exact this
    · have : s ∈ (HomogeneousIdeal.spanSingleton 𝒜 hh).toIdeal := by
        rw [h']
        exact Ideal.subset_span rfl
      obtain ⟨g, rfl⟩ := Ideal.mem_span_singleton'.mp this
      refine ⟨decompose 𝒜 g (-j), SetLike.coe_mem _, ?_⟩
      have := coe_decompose_mul_add_of_right_mem 𝒜 (a := g) (i := -j) hh
      rw [neg_add_cancel, decompose_of_mem_same 𝒜 hs0] at this
      exact this.symm

/-- Conversely, the left ideal generated by a graded simple idempotent of degree `0` is an atom
of the lattice of homogeneous left ideals. -/
theorem isAtom_of_isGradedSimpleIdempotent {s : R} (hs0 : s ∈ 𝒜 0) (hs : IsIdempotentElem s)
    (hsimple : IsGradedSimpleIdempotent 𝒜 s) : IsAtom (HomogeneousIdeal.spanSingleton 𝒜 hs0) := by
  classical
  refine ⟨fun h => hsimple.1 ?_, fun J hJ => ?_⟩
  · have : s ∈ (HomogeneousIdeal.spanSingleton 𝒜 hs0).toIdeal := Ideal.subset_span rfl
    rw [h] at this
    exact this
  · by_contra hJ0
    obtain ⟨x, hxJ, hx0⟩ := J.toIdeal.ne_bot_iff.mp fun h =>
      hJ0 (HomogeneousIdeal.ext (by rw [h]; rfl))
    obtain ⟨j, hj⟩ : ∃ j, (decompose 𝒜 x j : R) ≠ 0 := by
      by_contra! h
      apply hx0
      rw [← DirectSum.sum_support_decompose 𝒜 x]
      exact Finset.sum_eq_zero fun i _ => h i
    set h := (decompose 𝒜 x j : R)
    have hhJ : h ∈ J := J.isHomogeneous j hxJ
    have hhs : h * s = h := (mem_span_singleton_iff_mul_eq hs).mp (hJ.le hhJ)
    obtain ⟨g, -, hgh⟩ := hsimple.2 (SetLike.coe_mem _) hhs hj
    apply hJ.2
    refine HomogeneousIdeal.le_iff_toIdeal_le.mpr ((Ideal.span_singleton_le_iff_mem _).mpr ?_)
    rw [← hgh]
    exact J.toIdeal.mul_mem_left g hhJ

end Split

/-! ### Decomposition of `1` -/

section Decomposition

variable {𝒜}

/-- In a graded semisimple ring, every idempotent `g` of degree `0` whose left ideal is the
supremum of an independent finite set `t` of atoms of the lattice of homogeneous left ideals is
the sum of a list of pairwise orthogonal graded simple idempotents of degree `0`. -/
theorem exists_list_of_finset (t : Finset (HomogeneousIdeal 𝒜)) :
    sSupIndep (t : Set (HomogeneousIdeal 𝒜)) → (∀ a ∈ t, IsAtom a) → ∀ {g : R} (hg0 : g ∈ 𝒜 0),
      IsIdempotentElem g → HomogeneousIdeal.spanSingleton 𝒜 hg0 = t.sup id →
      ∃ l : List R, (∀ e ∈ l, e ∈ 𝒜 0 ∧ IsIdempotentElem e ∧ IsGradedSimpleIdempotent 𝒜 e) ∧
        l.Pairwise (fun a b => a * b = 0 ∧ b * a = 0) ∧ l.sum = g ∧
        ∀ e ∈ l, e * g = e ∧ g * e = e := by
  classical
  induction t using Finset.induction_on with
  | empty =>
    intro _ _ g hg0 _ hgt
    have : g ∈ (HomogeneousIdeal.spanSingleton 𝒜 hg0).toIdeal := Ideal.subset_span rfl
    rw [hgt, Finset.sup_empty, HomogeneousIdeal.toIdeal_bot] at this
    exact ⟨[], by simp, List.Pairwise.nil, ((Submodule.mem_bot R).mp this).symm, by simp⟩
  | insert a t hat ih =>
    intro hind hatom g hg0 hg hgt
    have hdisj : a ⊓ t.sup id = ⊥ := by
      have := hind (Finset.mem_insert_self a t)
      refine (this.mono_right ?_).eq_bot
      refine Finset.sup_le fun b hb => le_sSup ⟨Finset.mem_insert_of_mem hb, ?_⟩
      rintro rfl
      exact hat hb
    have hST : a.toIdeal ⊓ (t.sup id).toIdeal = ⊥ := by
      rw [← HomogeneousIdeal.toIdeal_inf, hdisj, HomogeneousIdeal.toIdeal_bot]
    have hsup : a.toIdeal ⊔ (t.sup id).toIdeal = Ideal.span {g} := by
      have e1 := congrArg HomogeneousIdeal.toIdeal (hgt.trans (Finset.sup_insert (f := id)))
      rw [HomogeneousIdeal.toIdeal_sup] at e1
      exact e1.symm
    obtain ⟨s, u, hs, hu, hsu, hsI, huI, hsu0, hus0, hspan_s, hspan_u⟩ :=
      exists_add_of_inf_eq_bot hg hST hsup
    obtain ⟨hs0, hu0⟩ := mem_zero_of_add_eq hdisj hs hu hg0 hsu
    have hsa : HomogeneousIdeal.spanSingleton 𝒜 hs0 = a := HomogeneousIdeal.ext hspan_s
    have hut : HomogeneousIdeal.spanSingleton 𝒜 hu0 = t.sup id := HomogeneousIdeal.ext hspan_u
    obtain ⟨l, hl, hlp, hlsum, hlg⟩ := ih (hind.mono (by simp))
      (fun b hb => hatom b (Finset.mem_insert_of_mem hb)) hu0 huI hut
    have hssimple : IsGradedSimpleIdempotent 𝒜 s :=
      isGradedSimpleIdempotent_of_isAtom hs0 hsI (hsa ▸ hatom a (Finset.mem_insert_self a t))
    have hsg : s * g = s := by rw [← hsu, mul_add, hsI.eq, hsu0, add_zero]
    have hgs : g * s = s := by rw [← hsu, add_mul, hsI.eq, hus0, add_zero]
    refine ⟨s :: l, fun x hx => ?_, List.pairwise_cons.mpr ⟨fun x hx => ?_, hlp⟩, ?_, ?_⟩
    · rcases List.mem_cons.mp hx with rfl | hx
      · exact ⟨hs0, hsI, hssimple⟩
      · exact hl x hx
    · obtain ⟨hxu, hux⟩ := hlg x hx
      exact ⟨by rw [← hux, ← mul_assoc, hsu0, zero_mul], by rw [← hxu, mul_assoc, hus0, mul_zero]⟩
    · rw [List.sum_cons, hlsum, hsu]
    · intro x hx
      rcases List.mem_cons.mp hx with rfl | hx
      · exact ⟨hsg, hgs⟩
      · obtain ⟨hxu, hux⟩ := hlg x hx
        have hxs : x * s = 0 := by rw [← hxu, mul_assoc, hus0, mul_zero]
        have hsx : s * x = 0 := by rw [← hux, ← mul_assoc, hsu0, zero_mul]
        exact ⟨by rw [← hsu, mul_add, hxs, zero_add, hxu],
          by rw [← hsu, add_mul, hsx, zero_add, hux]⟩

/-- In a graded semisimple ring, `1` is the sum of a list of pairwise orthogonal graded simple
idempotents of degree `0`. -/
theorem IsGradedSemisimpleRing.exists_list_sum_eq_one (h : IsGradedSemisimpleRing 𝒜) :
    ∃ l : List R, (∀ e ∈ l, e ∈ 𝒜 0 ∧ IsIdempotentElem e ∧ IsGradedSimpleIdempotent 𝒜 e) ∧
      l.Pairwise (fun a b => a * b = 0 ∧ b * a = 0) ∧ l.sum = 1 := by
  have : ComplementedLattice (HomogeneousIdeal 𝒜) := h
  obtain ⟨s, hind, htop, hatoms⟩ := exists_sSupIndep_of_sSup_atoms_eq_top
    (α := HomogeneousIdeal 𝒜) sSup_atoms_eq_top
  obtain ⟨t, hts, htop'⟩ := (isCompactElement_iff_exists_le_sSup_of_le_sSup _).mp
    (HomogeneousIdeal.isCompactElement_top 𝒜) s htop.ge
  have ht : t.sup id = ⊤ := top_le_iff.mp htop'
  obtain ⟨l, hl, hlp, hlsum, -⟩ := exists_list_of_finset t (hind.mono hts)
    (fun a ha => hatoms (hts ha)) (SetLike.GradedOne.one_mem (A := 𝒜)) IsIdempotentElem.one
    (by rw [ht, HomogeneousIdeal.spanSingleton_one])
  exact ⟨l, hl, hlp, hlsum⟩

/-- A graded ring is graded semisimple iff `1` is the sum of a list of pairwise orthogonal graded
simple idempotents of degree `0`. -/
theorem isGradedSemisimpleRing_iff_exists_list :
    IsGradedSemisimpleRing 𝒜 ↔
      ∃ l : List R, (∀ e ∈ l, e ∈ 𝒜 0 ∧ IsIdempotentElem e ∧ IsGradedSimpleIdempotent 𝒜 e) ∧
        l.Pairwise (fun a b => a * b = 0 ∧ b * a = 0) ∧ l.sum = 1 := by
  refine ⟨fun h => h.exists_list_sum_eq_one, ?_⟩
  rintro ⟨l, hl, -, hsum⟩
  refine complementedLattice_of_sSup_atoms_eq_top (eq_top_iff.mpr ?_)
  rw [← HomogeneousIdeal.spanSingleton_one 𝒜]
  refine HomogeneousIdeal.le_iff_toIdeal_le.mpr ((Ideal.span_singleton_le_iff_mem _).mpr ?_)
  rw [← hsum]
  refine list_sum_mem fun e he => ?_
  obtain ⟨he0, heI, hes⟩ := hl e he
  have hle : HomogeneousIdeal.spanSingleton 𝒜 he0 ≤ sSup {a : HomogeneousIdeal 𝒜 | IsAtom a} :=
    le_sSup (isAtom_of_isGradedSimpleIdempotent he0 heI hes)
  exact HomogeneousIdeal.le_iff_toIdeal_le.mp hle (Ideal.subset_span rfl)

end Decomposition

/-! ### Semisimple rings are graded semisimple -/

variable {𝒜} in
/-- Every homogeneous left ideal of a ring whose lattice of left ideals is complemented has a
homogeneous complement: if `I = R e` for an idempotent `e`, then `I = R e₀` for the degree-`0`
component `e₀` of `e`, and `R (1 - e₀)` is a homogeneous complement. -/
theorem exists_isCompl_homogeneousIdeal [ComplementedLattice (Ideal R)]
    (I : HomogeneousIdeal 𝒜) : ∃ J : HomogeneousIdeal 𝒜, IsCompl I J := by
  classical
  obtain ⟨J, hJ⟩ := exists_isCompl I.toIdeal
  obtain ⟨e, f, he, -, hef, heI, -, -, -, hspan, -⟩ := exists_add_of_inf_eq_bot
    IsIdempotentElem.one hJ.inf_eq_bot (by rw [hJ.sup_eq_top, Ideal.span_singleton_one])
  set e₀ := (decompose 𝒜 e 0 : R) with he₀def
  have he₀0 : e₀ ∈ 𝒜 0 := SetLike.coe_mem _
  have he₀I : e₀ ∈ I := I.isHomogeneous 0 he
  -- `x e₀ = x` for `x ∈ I`.
  have hhom : ∀ j (x : R), x ∈ 𝒜 j → x ∈ I → x * e₀ = x := by
    intro j x hxj hxI
    have hxe : x * e = x := (mem_span_singleton_iff_mul_eq heI).mp
      (show x ∈ Ideal.span {e} by rw [hspan]; exact hxI)
    have := coe_decompose_mul_add_of_left_mem 𝒜 (b := e) (j := 0) hxj
    rw [add_zero, hxe, decompose_of_mem_same 𝒜 hxj] at this
    exact this.symm
  have hmul : ∀ x ∈ I, x * e₀ = x := by
    intro x hxI
    rw [← DirectSum.sum_support_decompose 𝒜 x, Finset.sum_mul]
    exact Finset.sum_congr rfl fun j _ =>
      hhom j _ (SetLike.coe_mem _) (I.isHomogeneous j hxI)
  have he₀I' : IsIdempotentElem e₀ := hmul e₀ he₀I
  have h1e : (1 : R) - e₀ ∈ 𝒜 0 := sub_mem (SetLike.GradedOne.one_mem (A := 𝒜)) he₀0
  refine ⟨HomogeneousIdeal.spanSingleton 𝒜 h1e, ⟨?_, ?_⟩⟩
  · rw [disjoint_iff, ← HomogeneousIdeal.toIdeal_injective.eq_iff, HomogeneousIdeal.toIdeal_inf,
      HomogeneousIdeal.toIdeal_bot, HomogeneousIdeal.toIdeal_spanSingleton, eq_bot_iff]
    rintro x ⟨hxI, hx⟩
    obtain ⟨y, rfl⟩ := Ideal.mem_span_singleton'.mp hx
    rw [Submodule.mem_bot, ← hmul _ hxI, mul_assoc, sub_mul, one_mul, he₀I'.eq, sub_self,
      mul_zero]
  · rw [codisjoint_iff, ← HomogeneousIdeal.toIdeal_injective.eq_iff,
      HomogeneousIdeal.toIdeal_sup, HomogeneousIdeal.toIdeal_top, eq_top_iff]
    intro x _
    rw [show x = x * e₀ + x * (1 - e₀) by rw [← mul_add, add_sub_cancel, mul_one]]
    exact Submodule.add_mem_sup (I.toIdeal.mul_mem_left x he₀I)
      (Ideal.mul_mem_left _ x (Ideal.subset_span rfl))

/-- A semisimple ring is graded semisimple, for every `ℤ`-grading. -/
theorem isGradedSemisimpleRing_of_isSemisimpleRing [IsSemisimpleRing R] :
    IsGradedSemisimpleRing 𝒜 :=
  ⟨fun I => exists_isCompl_homogeneousIdeal I⟩

/-! ### Graded semisimple rings with a grading bounded below are semisimple -/

section Bounded

variable {𝒜}

/-- If the homogeneous components of `x` vanish above `a` and those of `y` above `b`, those of
`x y` vanish above `a + b`. -/
theorem decompose_mul_eq_zero {a b : ℤ} {x y : R}
    (hx : ∀ i, a < i → (decompose 𝒜 x i : R) = 0) (hy : ∀ j, b < j → (decompose 𝒜 y j : R) = 0)
    {n : ℤ} (hn : a + b < n) : (decompose 𝒜 (x * y) n : R) = 0 := by
  classical
  rw [decompose_mul, coe_mul_apply]
  refine Finset.sum_eq_zero fun ij hij => ?_
  rw [Finset.mem_filter] at hij
  by_cases hi : a < ij.1
  · rw [hx _ hi, zero_mul]
  · rw [hy _ (by omega), mul_zero]

theorem decompose_pow_eq_zero {x : R} (hx : ∀ i, -1 < i → (decompose 𝒜 x i : R) = 0) (j : ℕ) :
    ∀ n : ℤ, -(j : ℤ) < n → (decompose 𝒜 (x ^ j) n : R) = 0 := by
  induction j with
  | zero =>
    intro n hn
    rw [pow_zero, decompose_of_mem_ne 𝒜 (SetLike.GradedOne.one_mem (A := 𝒜) : (1 : R) ∈ 𝒜 0)
      (by omega)]
  | succ j ih =>
    intro n hn
    rw [pow_succ]
    exact decompose_mul_eq_zero ih hx (by omega)

theorem eq_zero_of_decompose_eq_zero {x : R} (h : ∀ i, (decompose 𝒜 x i : R) = 0) : x = 0 := by
  classical
  rw [← DirectSum.sum_support_decompose 𝒜 x]
  exact Finset.sum_eq_zero fun i _ => h i

/-- If the grading is bounded below, every element whose homogeneous components of non-negative
degree vanish is nilpotent. -/
theorem isNilpotent_of_decompose_eq_zero (hbdd : ∃ N : ℤ, ∀ k < N, ∀ x ∈ 𝒜 k, x = 0) {x : R}
    (hx : ∀ i, -1 < i → (decompose 𝒜 x i : R) = 0) : IsNilpotent x := by
  obtain ⟨N, hN⟩ := hbdd
  refine ⟨N.natAbs + 1, eq_zero_of_decompose_eq_zero (𝒜 := 𝒜) fun i => ?_⟩
  by_cases hi : -((N.natAbs + 1 : ℕ) : ℤ) < i
  · exact decompose_pow_eq_zero hx _ i hi
  · exact hN i (by omega) _ (SetLike.coe_mem _)

/-- A graded simple idempotent of degree `0` of a ring whose grading is bounded below generates a
simple left ideal: for a nonzero `s ∈ N ⊆ R e`, if `sₘ` is the top homogeneous component of `s`
and `g sₘ = e`, then `e g s = e + n'` with `n'` of negative degrees, hence nilpotent, and `e` is a
left multiple of `e g s ∈ N`. -/
theorem isSimpleModule_of_isGradedSimpleIdempotent
    (hbdd : ∃ N : ℤ, ∀ k < N, ∀ x ∈ 𝒜 k, x = 0) {e : R} (he0 : e ∈ 𝒜 0)
    (heI : IsIdempotentElem e) (hs : IsGradedSimpleIdempotent 𝒜 e) :
    IsSimpleModule R (Ideal.span {e}) := by
  classical
  rw [isSimpleModule_iff_isAtom]
  refine ⟨fun h => hs.1 (by
    have : e ∈ Ideal.span {e} := Ideal.subset_span rfl
    rw [h] at this
    exact this), fun N hN => ?_⟩
  by_contra hN0
  obtain ⟨s, hsN, hs0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hN0
  have hse : s * e = s := (mem_span_singleton_iff_mul_eq heI).mp (hN.le hsN)
  -- The top homogeneous component `sₘ` of `s`.
  have hsupp : (decompose 𝒜 s).support.Nonempty := by
    by_contra h
    rw [Finset.not_nonempty_iff_eq_empty] at h
    exact hs0 (eq_zero_of_decompose_eq_zero fun i => by
      have : i ∉ (decompose 𝒜 s).support := by rw [h]; exact Finset.notMem_empty i
      rw [DFinsupp.notMem_support_iff] at this
      rw [this, ZeroMemClass.coe_zero])
  set m := (decompose 𝒜 s).support.max' hsupp
  have htop : ∀ k, m < k → (decompose 𝒜 s k : R) = 0 := fun k hk => by
    have : k ∉ (decompose 𝒜 s).support := fun hk' =>
      absurd ((decompose 𝒜 s).support.le_max' k hk') (not_le.mpr hk)
    rw [DFinsupp.notMem_support_iff] at this
    rw [this, ZeroMemClass.coe_zero]
  have hsm0 : (decompose 𝒜 s m : R) ≠ 0 := by
    have := (decompose 𝒜 s).support.max'_mem hsupp
    rw [DFinsupp.mem_support_iff] at this
    exact fun h => this (Subtype.ext h)
  have hsme : (decompose 𝒜 s m : R) * e = decompose 𝒜 s m := by
    have := coe_decompose_mul_add_of_right_mem 𝒜 (a := s) (i := m) he0
    rw [add_zero, hse] at this
    exact this.symm
  obtain ⟨g, hg, hgs⟩ := hs.2 (SetLike.coe_mem _) hsme hsm0
  -- `u = g s = e + n` with `n` of negative degrees.
  set u := g * s
  have huN : u ∈ N := N.smul_mem g hsN
  have hue : u * e = u := by rw [mul_assoc, hse]
  have hu : ∀ k, -1 < k → (decompose 𝒜 (u - e) k : R) = 0 := by
    intro k hk
    have h1 := coe_decompose_mul_add_of_left_mem 𝒜 (b := s) (j := k + m) hg
    rw [show -m + (k + m) = k by ring] at h1
    rw [decompose_sub, DFinsupp.sub_apply, AddSubgroupClass.coe_sub, h1]
    rcases (show k = 0 ∨ 0 < k by omega) with rfl | hk0
    · rw [zero_add, hgs, decompose_of_mem_same 𝒜 he0, sub_self]
    · rw [htop _ (by omega), mul_zero, decompose_of_mem_ne 𝒜 he0 (by omega), sub_zero]
  set n' := e * (u - e)
  have hn' : ∀ k, -1 < k → (decompose 𝒜 n' k : R) = 0 := by
    intro k hk
    have := coe_decompose_mul_add_of_left_mem 𝒜 (b := u - e) (j := k) he0
    rw [zero_add] at this
    rw [this, hu k hk, mul_zero]
  have hnil : IsNilpotent n' := isNilpotent_of_decompose_eq_zero hbdd hn'
  have hn'e : n' * e = n' := by
    rw [mul_assoc, sub_mul, hue, heI.eq]
  have heu : e * u = e + n' := by
    change e * u = e + e * (u - e)
    rw [mul_sub, heI.eq, add_sub_cancel]
  obtain ⟨U, hU⟩ := hnil.isUnit_one_add
  have hmem : e ∈ N := by
    have : e = (↑U⁻¹ : R) * (e * u) := by
      rw [heu, ← hn'e, ← one_add_mul, ← hU, ← mul_assoc, Units.inv_mul, one_mul]
    rw [this]
    exact N.smul_mem _ (N.smul_mem e huN)
  exact hN.2 ((Ideal.span_singleton_le_iff_mem _).mpr hmem)

/-- A graded semisimple ring whose grading is bounded below is semisimple. -/
theorem isSemisimpleRing_of_isGradedSemisimpleRing (h : IsGradedSemisimpleRing 𝒜)
    (hbdd : ∃ N : ℤ, ∀ k < N, ∀ x ∈ 𝒜 k, x = 0) : IsSemisimpleRing R := by
  obtain ⟨l, hl, -, hsum⟩ := h.exists_list_sum_eq_one
  refine isSemisimpleModule_of_isSemisimpleModule_submodule (s := {x | x ∈ l})
    (p := fun x => Ideal.span {x}) ?_ ?_
  · intro x hx
    obtain ⟨hx0, hxI, hxs⟩ := hl x hx
    have := isSimpleModule_of_isGradedSimpleIdempotent hbdd hx0 hxI hxs
    infer_instance
  · rw [eq_top_iff, ← Ideal.span_singleton_one, Ideal.span, Submodule.span_singleton_le_iff_mem,
      ← hsum]
    refine list_sum_mem fun x hx => ?_
    exact Submodule.mem_iSup_of_mem x (Submodule.mem_iSup_of_mem hx (Ideal.subset_span rfl))

/-- The grading of a finite-dimensional graded algebra over a field is bounded below. -/
theorem exists_forall_lt_eq_zero_of_finiteDimensional (K : Type*) [Field K] [Algebra K R]
    [FiniteDimensional K R] (h𝒜 : ∀ k (c : K) {x : R}, x ∈ 𝒜 k → c • x ∈ 𝒜 k) :
    ∃ N : ℤ, ∀ k < N, ∀ x ∈ 𝒜 k, x = 0 := by
  classical
  let S : Set ℤ := {k | ∃ x ∈ 𝒜 k, x ≠ 0}
  choose v hv hv0 using fun k : S => k.2
  have hli : LinearIndependent K v := by
    rw [linearIndependent_iff']
    intro t c hc i hi
    have := congrArg (GradedRing.proj 𝒜 i.1) hc
    rw [map_sum, map_zero, Finset.sum_eq_single i (fun j _ hji => by
        rw [GradedRing.proj_apply, decompose_of_mem_ne 𝒜 (h𝒜 j.1 (c j) (hv j))
          (fun h => hji (Subtype.ext h))])
      (fun hi' => absurd hi hi'), GradedRing.proj_apply,
      decompose_of_mem_same 𝒜 (h𝒜 i.1 (c i) (hv i))] at this
    exact (smul_eq_zero.mp this).resolve_right (hv0 i)
  have hfin : S.Finite := Set.finite_coe_iff.mp hli.finite_of_isNoetherian
  obtain ⟨b, hb⟩ := hfin.bddBelow
  refine ⟨b, fun k hk x hx => ?_⟩
  by_contra hx0
  exact absurd (hb ⟨x, hx, hx0⟩) (not_le.mpr hk)

/-- For a finite-dimensional graded algebra over a field, graded semisimplicity and
semisimplicity coincide. -/
theorem isGradedSemisimpleRing_iff_isSemisimpleRing (K : Type*) [Field K] [Algebra K R]
    [FiniteDimensional K R] (h𝒜 : ∀ k (c : K) {x : R}, x ∈ 𝒜 k → c • x ∈ 𝒜 k) :
    IsGradedSemisimpleRing 𝒜 ↔ IsSemisimpleRing R :=
  ⟨fun h => isSemisimpleRing_of_isGradedSemisimpleRing h
    (exists_forall_lt_eq_zero_of_finiteDimensional K h𝒜),
    fun _ => isGradedSemisimpleRing_of_isSemisimpleRing 𝒜⟩

end Bounded

end DG
