import DG.Algebra.Cohomology
import DG.Category.Derived.Keller
import DG.Derived.KProjective

/-!
# Formal dg rings

A dg ring `A` is *formal* if it is connected to its cohomology ring `H(A)` (with zero
differential, `DG.Cohomology A`) by a zigzag of quasi-isomorphisms of dg rings (Roadmap 6.4).

## Main definitions and results

* `DG.BundledDGRing`: dg rings as bundled objects, and `DG.BundledDGRing.QuasiIsoRel`: the
  relation "there is a quasi-isomorphism `A → B`".
* `DG.QuasiIsomorphic A B`: `A` and `B` are connected by a zigzag of quasi-isomorphisms (the
  equivalence relation generated by `QuasiIsoRel`); `DG.IsFormal A := QuasiIsomorphic A H(A)`.
* `DG.QuasiIsomorphic.nonempty_derivedEquivalence`: quasi-isomorphic dg rings have equivalent
  derived categories, by Keller's theorem (`DG.DGRingHom.derivedEquivalence`) along each step
  of the zigzag; in particular `D(A) ≌ D(H(A))` for `A` formal
  (`DG.IsFormal.nonempty_derivedEquivalence`).
* `DG.DGRingHom.IsCohomologySection`: a morphism of dg rings `s : H(A) → A` (that is, a graded
  ring map sending classes to cocycles) which sends every class to a cocycle representing it;
  `DG.DGRingHom.IsCohomologySection.isQuasiIso`: such an `s` is a quasi-isomorphism, and
  `DG.isFormal_of_isCohomologySection`: then `A` is formal (the formality criterion of
  Roadmap 6.4).

## Universes

The zigzag consists of dg rings in one universe `u`. Derived categories are taken for dg modules
in `Type (max u w)`, with arbitrary chosen localizations; two choices of the derived category of
the same dg ring are equivalent (`DG.DerivedCategory.nonempty_equivalence_of_instances`).
-/

open CategoryTheory DirectSum

universe w w₁ w₂ u

namespace DG

/-- A dg ring as a bundled object: a type with `Ring`, `DGAddCommGroup` and `DGRing`
instances. -/
structure BundledDGRing where
  /-- The underlying type. -/
  carrier : Type u
  [ring : Ring carrier]
  [dgAddCommGroup : DGAddCommGroup carrier]
  [dgRing : DGRing carrier]

attribute [instance] BundledDGRing.ring BundledDGRing.dgAddCommGroup BundledDGRing.dgRing

namespace BundledDGRing

instance : CoeSort BundledDGRing.{u} (Type u) := ⟨carrier⟩

/-- The bundled dg ring attached to a dg ring. -/
abbrev of (A : Type u) [Ring A] [DGAddCommGroup A] [DGRing A] : BundledDGRing.{u} := ⟨A⟩

/-- The relation "there is a quasi-isomorphism of dg rings `A → B`". -/
def QuasiIsoRel (A B : BundledDGRing.{u}) : Prop :=
  ∃ f : A →ᵈᵍ+* B, f.IsQuasiIso

end BundledDGRing

section Formal

variable (A B : Type u) [Ring A] [DGAddCommGroup A] [DGRing A] [Ring B] [DGAddCommGroup B]
  [DGRing B]

/-- Two dg rings are *quasi-isomorphic* if they are connected by a zigzag of quasi-isomorphisms
of dg rings, i.e. related by the equivalence relation generated by the quasi-isomorphisms. -/
def QuasiIsomorphic : Prop :=
  Relation.EqvGen BundledDGRing.QuasiIsoRel (.of A) (.of B)

/-- A dg ring `A` is *formal* if it is quasi-isomorphic to its cohomology ring `H(A)`, with zero
differential. -/
def IsFormal : Prop :=
  QuasiIsomorphic A (Cohomology A)

variable {A B}

theorem DGRingHom.IsQuasiIso.quasiIsomorphic {f : A →ᵈᵍ+* B} (hf : f.IsQuasiIso) :
    QuasiIsomorphic A B :=
  .rel _ _ ⟨f, hf⟩

end Formal

/-! ### Derived equivalences -/

namespace DerivedCategory

/-- Two choices of the derived category of a dg ring (localizations of the homotopy category at
the quasi-isomorphisms) are equivalent. -/
theorem nonempty_equivalence_of_instances (A : Type u) [Ring A] [DGAddCommGroup A] [DGRing A]
    (I₁ : HasDerivedCategory.{w₁, max u w} A)
    (I₂ : HasDerivedCategory.{w₂, max u w} A) :
    Nonempty (@DerivedCategory A _ _ _ I₁ ≌ @DerivedCategory A _ _ _ I₂) :=
  ⟨Localization.uniq (@Qh A _ _ _ I₁) (@Qh A _ _ _ I₂) (HomotopyCategory.quasiIso A)⟩

end DerivedCategory

/-- Along a zigzag of quasi-isomorphisms, the derived categories (small models,
`DG.HasDerivedCategory.small`) are equivalent. -/
theorem nonempty_derivedEquivalence_small {X Y : BundledDGRing.{u}}
    (h : Relation.EqvGen BundledDGRing.QuasiIsoRel X Y) :
    Nonempty (@DerivedCategory X _ _ _ (HasDerivedCategory.small.{w, u} X) ≌
      @DerivedCategory Y _ _ _ (HasDerivedCategory.small.{w, u} Y)) := by
  induction h with
  | rel X Y hXY =>
    obtain ⟨f, hf⟩ := hXY
    let := HasDerivedCategory.small.{w, u} X
    let := HasDerivedCategory.small.{w, u} Y
    exact ⟨(DGRingHom.derivedEquivalence.{max u w} f hf)⟩
  | refl X => exact ⟨CategoryTheory.Equivalence.refl⟩
  | symm X Y _ ih => exact ⟨ih.some.symm⟩
  | trans X Y Z _ _ ih₁ ih₂ => exact ⟨ih₁.some.trans ih₂.some⟩

/-- Quasi-isomorphic dg rings (connected by a zigzag of quasi-isomorphisms) have equivalent
derived categories [Keller, *Deriving DG categories*, Ex. 6.1]. -/
theorem QuasiIsomorphic.nonempty_derivedEquivalence {A B : Type u} [Ring A] [DGAddCommGroup A]
    [DGRing A] [Ring B] [DGAddCommGroup B] [DGRing B] (h : QuasiIsomorphic A B)
    [I₁ : HasDerivedCategory.{w₁, max u w} A] [I₂ : HasDerivedCategory.{w₂, max u w} B] :
    Nonempty (DerivedCategory A ≌ DerivedCategory B) := by
  obtain ⟨E⟩ := nonempty_derivedEquivalence_small.{w} h
  obtain ⟨E₁⟩ := DerivedCategory.nonempty_equivalence_of_instances A I₁
    (HasDerivedCategory.small.{w, u} A)
  obtain ⟨E₂⟩ := DerivedCategory.nonempty_equivalence_of_instances B
    (HasDerivedCategory.small.{w, u} B) I₂
  exact ⟨E₁.trans (E.trans E₂)⟩

/-- For a formal dg ring `A`, `D(A) ≌ D(H(A))`. -/
theorem IsFormal.nonempty_derivedEquivalence {A : Type u} [Ring A] [DGAddCommGroup A]
    [DGRing A] (h : IsFormal A) [HasDerivedCategory.{w₁, max u w} A]
    [HasDerivedCategory.{w₂, max u w} (Cohomology A)] :
    Nonempty (DerivedCategory A ≌ DerivedCategory (Cohomology A)) :=
  QuasiIsomorphic.nonempty_derivedEquivalence.{w} h

/-! ### The formality criterion -/

section Criterion

variable {A B : Type u} [Ring A] [DGAddCommGroup A] [DGRing A] [Ring B] [DGAddCommGroup B]

/-- A morphism of dg rings `s : H(A) → B` sends classes to cocycles (`H(A)` has zero
differential). -/
theorem DGRingHom.mem_cocycles_apply_of (s : Cohomology A →ᵈᵍ+* B) (n : ℤ)
    (x : cohomology A n) : s (DirectSum.of (fun n => cohomology A n) n x) ∈ cocycles B n :=
  mem_cocycles.mpr ⟨s.map_mem (Cohomology.of_mem_grading n x), by
    rw [← s.map_d, Cohomology.d_apply, map_zero]⟩

/-- A morphism of dg rings `s : H(A) → A` is a *cohomology section* if it sends every class to
a cocycle representing it: `[s x] = x` for `x ∈ Hⁿ(A)`. Equivalently, `s` is a morphism of graded
rings `H(A) → A` with values in the cocycles, splitting the projection `Z(A) → H(A)`. -/
def DGRingHom.IsCohomologySection (s : Cohomology A →ᵈᵍ+* A) : Prop :=
  ∀ (n : ℤ) (x : cohomology A n),
    cohomology.mk A n ⟨_, s.mem_cocycles_apply_of n x⟩ = x

/-- A cohomology section `H(A) → A` is a quasi-isomorphism. -/
theorem DGRingHom.IsCohomologySection.isQuasiIso {s : Cohomology A →ᵈᵍ+* A}
    (hs : s.IsCohomologySection) : s.IsQuasiIso := by
  have hs' : ∀ (n : ℤ) (x : cohomology A n),
      cohomology.mk A n ⟨_, s.mem_cocycles_apply_of n x⟩ = x := hs
  intro n
  -- Every class of `Hⁿ(H(A))` is represented by `of n x` for a unique `x ∈ Hⁿ(A)`.
  have hrep : ∀ z : cocycles (Cohomology A) n,
      ∃ x : cohomology A n, (z : Cohomology A) = DirectSum.of (fun n => cohomology A n) n x :=
    fun z => by
      obtain ⟨x, hx⟩ := Cohomology.mem_grading_iff.mp (mem_cocycles.mp z.2).1
      exact ⟨x, hx.symm⟩
  have hmap : ∀ (z : cocycles (Cohomology A) n) (x : cohomology A n),
      (z : Cohomology A) = DirectSum.of (fun n => cohomology A n) n x →
        s.cohomologyMap n (cohomology.mk _ n z) = x := by
    intro z x hzx
    rw [cohomologyMap_mk, ← hs' n x]
    congr 1
    exact Subtype.ext (by rw [coe_cocyclesMap, hzx])
  constructor
  · intro y y' hyy'
    obtain ⟨z, rfl⟩ := cohomology.mk_surjective _ n y
    obtain ⟨z', rfl⟩ := cohomology.mk_surjective _ n y'
    obtain ⟨x, hx⟩ := hrep z
    obtain ⟨x', hx'⟩ := hrep z'
    rw [hmap z x hx, hmap z' x' hx'] at hyy'
    subst hyy'
    congr 1
    exact Subtype.ext (hx.trans hx'.symm)
  · intro x
    refine ⟨cohomology.mk _ n ⟨DirectSum.of (fun n => cohomology A n) n x,
      mem_cocycles.mpr ⟨Cohomology.of_mem_grading n x, rfl⟩⟩, hmap _ x rfl⟩

/-- **Formality criterion** (Roadmap 6.4): if there is a morphism of dg rings `s : H(A) → A`
sending every cohomology class to a cocycle representing it (a graded ring map `H(A) → A`
splitting the cocycles), then `A` is formal, via the single quasi-isomorphism `s`. -/
theorem isFormal_of_isCohomologySection (s : Cohomology A →ᵈᵍ+* A)
    (hs : s.IsCohomologySection) : IsFormal A :=
  .symm _ _ (.rel _ _ ⟨s, hs.isQuasiIso⟩)

end Criterion

end DG
