import DG.Algebra.Commutative
import DG.Module.CohomologyLinear
import DG.Positive.Formality

/-!
# Formality of CDGAs with free graded-commutative cohomology

Let `A` be a commutative dg algebra over a commutative ring `R` (`DG.IsCDGA A`: strictly graded
commutative, `a * a = 0` for homogeneous `a` of odd degree). If its cohomology `H(A)` is a *free*
graded-commutative `R`-algebra on homogeneous classes `xᵢ`, then choosing cocycle representatives
`zᵢ` of the `xᵢ` defines a morphism of dg algebras `H(A) → A` (with `H(A)` carrying the zero
differential) which sends every class to a representing cocycle, so `A` is formal
(Roadmap 6.4, the free graded-commutative criterion).

## Main definitions and results

* `DG.IsFreeGradedCommAlgebra R ℋ deg x`: a graded `R`-algebra `H` (grading `ℋ`) is free
  (strictly) graded-commutative on the homogeneous elements `x i ∈ ℋ (deg i)`: `H` is strictly
  graded commutative, and for every `R`-algebra `B` with a multiplicative grading `ℬ` which is
  strictly graded commutative and every family `y i ∈ ℬ (deg i)` there is a unique morphism of
  `R`-algebras `H → B` preserving the gradings and sending `x i` to `y i`.
* `DG.cocyclesSubmodule_gradedMonoid`, `DG.cocyclesSubmodule_isGradedCommStrict`: the cocycles
  `Zⁿ(A)` form a multiplicative grading of `A` (by `R`-submodules), strictly graded commutative
  if `A` is a CDGA.
* `DG.exists_isCohomologySection_of_isFreeGradedCommAlgebra`: for a CDGA `A` whose cohomology is
  free graded-commutative on homogeneous classes, there is a morphism of dg rings `H(A) → A`
  sending every class to a cocycle representing it (`DG.DGRingHom.IsCohomologySection`).
* `DG.isFormal_of_isFreeGradedCommAlgebra`: such an `A` is formal;
  `DG.isFormal_of_isFreeGradedCommAlgebra_of_isGradedComm`: the same for a graded commutative
  (not necessarily strictly) dg algebra over a ring in which `2` is invertible.

## The hypothesis on odd generators

Freeness is taken in the category of *strictly* graded-commutative algebras, which is the
standard notion (the free object is a polynomial algebra on the even generators tensor an
exterior algebra on the odd ones). The lift `H(A) → A` must send an odd generator `x` (with
`x * x = 0`) to a representative `z` with `z * z = 0`; this holds when `A` is strictly graded
commutative, which is part of `DG.IsCDGA`. Graded commutativity alone only gives `2 • (z * z) = 0`,
which suffices when `2` is invertible in `R` (`DG.IsCDGA.of_isGradedComm`). Without either
hypothesis the argument fails: over `𝔽₂`, the graded-commutative dg algebra
`A = 𝔽₂[z, u] / (z³, z u, u²)` with `z`, `u` of degree `1`, `d z = 0` and `d u = z²` has
cohomology the exterior algebra on the class of `z` (free strictly graded-commutative on one odd
generator), but `z` is the only cocycle representing that class and `z * z ≠ 0`, so no graded
algebra map `H(A) → A` sends the generator to a representative.

## Universes

The universal property is required for targets `B` in the universe of `H`; this is all that is
used (the targets are `A` and `H(A)`).
-/

open DirectSum

universe u

namespace DG

section Definition

variable (R : Type*) {H : Type u} [CommRing R] [Ring H] [Algebra R H]
  (ℋ : ℤ → Submodule R H) {ι : Type*} (deg : ι → ℤ) (x : ι → H)

/-- A graded `R`-algebra `H` (with grading `ℋ`) is *free graded-commutative* on the homogeneous
elements `x i ∈ ℋ (deg i)`: it is strictly graded commutative, and for every `R`-algebra `B`
(in the universe of `H`) with a multiplicative grading `ℬ` by `R`-submodules which is strictly
graded commutative, and every family of homogeneous elements `y i ∈ ℬ (deg i)`, there is a unique
morphism of `R`-algebras `f : H → B` with `f (ℋ n) ⊆ ℬ n` for all `n` and `f (x i) = y i`.
The targets need not be graded algebras in the sense of a direct sum decomposition: this makes
the condition apply to the cocycles `Z(A) ⊆ A` of a dg algebra, and the free object
(polynomials on the even generators tensor the exterior algebra on the odd ones) satisfies it,
since its image lies in the subalgebra generated by homogeneous elements. -/
structure IsFreeGradedCommAlgebra : Prop where
  /-- The generators are homogeneous of the given degrees. -/
  mem : ∀ i, x i ∈ ℋ (deg i)
  /-- `H` is strictly graded commutative. -/
  isGradedCommStrict : IsGradedCommStrict ℋ
  /-- The universal property among strictly graded-commutative graded `R`-algebras. -/
  existsUnique_lift : ∀ (B : Type u) [Ring B] [Algebra R B] (ℬ : ℤ → Submodule R B)
    [SetLike.GradedMonoid ℬ] [IsGradedCommStrict ℬ] (y : ι → B), (∀ i, y i ∈ ℬ (deg i)) →
    ∃! f : H →ₐ[R] B, (∀ (n : ℤ) (a : H), a ∈ ℋ n → f a ∈ ℬ n) ∧ ∀ i, f (x i) = y i

end Definition

section Cocycles

variable (R : Type*) (A : Type u) [CommRing R] [Ring A] [Algebra R A] [DGAddCommGroup A]
  [DGRing A] [DGAlgebra R A]

/-- The product of cocycles of degrees `i` and `j` is a cocycle of degree `i + j`. -/
theorem mul_mem_cocycles {i j : ℤ} {a b : A} (ha : a ∈ cocycles A i) (hb : b ∈ cocycles A j) :
    a * b ∈ cocycles A (i + j) := by
  rw [mem_cocycles] at *
  refine ⟨mul_mem_grading ha.1 hb.1, ?_⟩
  rw [d_mul ha.1, ha.2, hb.2, zero_mul, mul_zero, smul_zero, add_zero]

/-- The cocycles `Zⁿ(A)` (as `R`-submodules) form a multiplicative grading of `A`. -/
instance cocyclesSubmodule_gradedMonoid :
    SetLike.GradedMonoid (DGModule.cocyclesSubmodule R A A) where
  one_mem := mem_cocycles.mpr ⟨one_mem_grading, d_one⟩
  mul_mem _ _ _ _ ha hb := mul_mem_cocycles A ha hb

/-- The cocycles of a CDGA are strictly graded commutative. -/
instance cocyclesSubmodule_isGradedCommStrict [IsCDGA A] :
    IsGradedCommStrict (DGModule.cocyclesSubmodule R A A) where
  mul_comm_of_mem ha hb := IsCDGA.mul_comm_of_mem (mem_cocycles.mp ha).1 (mem_cocycles.mp hb).1
  mul_self_of_odd ha hi := IsCDGA.mul_self_of_odd (mem_cocycles.mp ha).1 hi

end Cocycles

section Criterion

variable {R : Type*} {A : Type u} [CommRing R] [Ring A] [Algebra R A] [DGAddCommGroup A]
  [DGRing A] [DGAlgebra R A]

/-- A morphism of `R`-algebras `f : H(A) → A` sending `Hⁿ(A)` into the cocycles of degree `n`,
as a morphism of dg rings. -/
def cocycleValuedDGRingHom (f : Cohomology A →ₐ[R] A)
    (hf : ∀ (n : ℤ) (a : Cohomology A), a ∈ DGAlgebra.gradingSubmodule R (Cohomology A) n →
      f a ∈ DGModule.cocyclesSubmodule R A A n) : Cohomology A →ᵈᵍ+* A where
  toRingHom := f.toRingHom
  map_mem' {n a} ha := (mem_cocycles.mp (hf n a ha)).1
  map_d' a := by
    change f 0 = d (f a)
    rw [map_zero]
    induction a using DirectSum.induction_on with
    | zero => rw [map_zero, d_zero]
    | of n y => exact ((mem_cocycles.mp (hf n _ (Cohomology.of_mem_grading n y))).2).symm
    | add a b ha hb => rw [map_add, d_add, ← ha, ← hb, add_zero]

variable (f : Cohomology A →ₐ[R] A)
  (hf : ∀ (n : ℤ) (a : Cohomology A), a ∈ DGAlgebra.gradingSubmodule R (Cohomology A) n →
      f a ∈ DGModule.cocyclesSubmodule R A A n)

/-- The degree-`n` component of the classes of the values of `f`: `y ↦ [f y]`. -/
def classOfValueAux (n : ℤ) : cohomology A n →+ Cohomology A :=
  (DirectSum.of (fun n => cohomology A n) n).comp ((cohomology.mk A n).comp
    { toFun := fun y => ⟨f (DirectSum.of (fun n => cohomology A n) n y),
        hf n _ (Cohomology.of_mem_grading n y)⟩
      map_zero' := Subtype.ext (by simp)
      map_add' := fun _ _ => Subtype.ext (by simp) })

theorem classOfValueAux_apply (n : ℤ) (y : cohomology A n) :
    classOfValueAux f hf n y = DirectSum.of (fun n => cohomology A n) n
      (cohomology.mk A n ⟨f (DirectSum.of (fun n => cohomology A n) n y),
        hf n _ (Cohomology.of_mem_grading n y)⟩) := rfl

/-- The ring endomorphism `y ↦ [f y]` of `H(A)`, for a ring map `f : H(A) → A` with cocycle
values. -/
def classOfValue : Cohomology A →+* Cohomology A :=
  DirectSum.toSemiring (classOfValueAux f hf) (by
    rw [classOfValueAux_apply]
    have h : (⟨f (DirectSum.of (fun n => cohomology A n) 0 GradedMonoid.GOne.one),
        hf 0 _ (Cohomology.of_mem_grading 0 _)⟩ : cocycles A 0) =
        ⟨1, mem_cocycles.mpr ⟨one_mem_grading, d_one⟩⟩ :=
      Subtype.ext ((congrArg f Cohomology.one_eq.symm).trans (map_one f))
    rw [h]
    rfl) (by
    intro i j y y'
    rw [classOfValueAux_apply, classOfValueAux_apply, classOfValueAux_apply,
      Cohomology.of_mul_of, cohomology.smulHom_mk_mk]
    congr 2
    refine Subtype.ext ?_
    rw [cocycles.coe_smulHom_apply, smul_eq_mul]
    exact (congrArg f (Cohomology.of_mul_of y y')).symm.trans (map_mul f _ _))

theorem classOfValue_of (n : ℤ) (y : cohomology A n) :
    classOfValue f hf (DirectSum.of (fun n => cohomology A n) n y) =
      DirectSum.of (fun n => cohomology A n) n
        (cohomology.mk A n ⟨f (DirectSum.of (fun n => cohomology A n) n y),
          hf n _ (Cohomology.of_mem_grading n y)⟩) :=
  DirectSum.toSemiring_of _ _ _ n y

set_option backward.isDefEq.respectTransparency false in
/-- The `R`-algebra endomorphism `y ↦ [f y]` of `H(A)`. -/
def classOfValueAlgHom : Cohomology A →ₐ[R] Cohomology A :=
  { classOfValue f hf with
    commutes' := fun r => by
      change classOfValue f hf (algebraMap R (Cohomology A) r) = _
      rw [Cohomology.algebraMap_apply, classOfValue_of]
      conv_rhs => rw [Cohomology.algebraMapZero_eq_mk]
      congr 2
      refine Subtype.ext ?_
      change f (algebraMap R (Cohomology A) r) = _
      exact f.commutes r }

theorem classOfValueAlgHom_of (n : ℤ) (y : cohomology A n) :
    classOfValueAlgHom f hf (DirectSum.of (fun n => cohomology A n) n y) =
      DirectSum.of (fun n => cohomology A n) n
        (cohomology.mk A n ⟨f (DirectSum.of (fun n => cohomology A n) n y),
          hf n _ (Cohomology.of_mem_grading n y)⟩) :=
  classOfValue_of f hf n y

/-- **Formality criterion for free graded-commutative cohomology** (Roadmap 6.4). Let `A` be a
commutative dg `R`-algebra (strictly graded commutative) whose cohomology `H(A)` is free
graded-commutative on homogeneous classes `x i ∈ H^{deg i}(A)`. Then there is a morphism of dg
rings `s : H(A) → A` sending every class to a cocycle representing it: `s` is the morphism of
algebras sending `x i` to a chosen representative `z i` (it exists since the cocycles of `A` form
a strictly graded-commutative graded algebra), and `y ↦ [s y]` is the identity of `H(A)` by the
uniqueness in the universal property, since it fixes the generators. -/
theorem exists_isCohomologySection_of_isFreeGradedCommAlgebra [IsCDGA A] {ι : Type*}
    {deg : ι → ℤ}
    {x : ι → Cohomology A}
    (hx : IsFreeGradedCommAlgebra R (DGAlgebra.gradingSubmodule R (Cohomology A)) deg x) :
    ∃ s : Cohomology A →ᵈᵍ+* A, s.IsCohomologySection := by
  have hrep : ∀ i, ∃ z : cocycles A (deg i),
      DirectSum.of (fun n => cohomology A n) (deg i) (cohomology.mk A _ z) = x i := fun i => by
    obtain ⟨y, hy⟩ := Cohomology.mem_grading_iff.mp (hx.mem i)
    obtain ⟨z, rfl⟩ := cohomology.mk_surjective A _ y
    exact ⟨z, hy⟩
  choose z hz using hrep
  obtain ⟨f, ⟨hf, hfx⟩, -⟩ := hx.existsUnique_lift A (DGModule.cocyclesSubmodule R A A)
    (fun i => (z i : A)) (fun i => (z i).2)
  refine ⟨cocycleValuedDGRingHom f hf, ?_⟩
  obtain ⟨g, -, hg⟩ := hx.existsUnique_lift (Cohomology A)
    (DGAlgebra.gradingSubmodule R (Cohomology A)) x hx.mem
  have h₁ : classOfValueAlgHom f hf = g := by
    refine hg _ ⟨fun n a ha => ?_, fun i => ?_⟩
    · obtain ⟨y, rfl⟩ := Cohomology.mem_grading_iff.mp ha
      rw [classOfValueAlgHom_of]
      exact Cohomology.of_mem_grading n _
    · have h := hfx i
      rw [← hz i] at h ⊢
      rw [classOfValueAlgHom_of]
      exact congrArg (DirectSum.of (fun n => cohomology A n) (deg i))
        (congrArg (cohomology.mk A (deg i)) (Subtype.ext h))
  have h₂ : AlgHom.id R (Cohomology A) = g := hg _ ⟨fun _ _ ha => ha, fun _ => rfl⟩
  intro n y
  have h := congrArg (fun φ : Cohomology A →ₐ[R] Cohomology A =>
    φ (DirectSum.of (fun n => cohomology A n) n y)) (h₁.trans h₂.symm)
  simp only [classOfValueAlgHom_of, AlgHom.id_apply] at h
  exact DirectSum.of_injective n h

/-- **Formality of CDGAs with free graded-commutative cohomology** (Roadmap 6.4): a commutative dg
`R`-algebra `A` (strictly graded commutative, `DG.IsCDGA`) whose cohomology `H(A)` is a free
graded-commutative `R`-algebra on homogeneous classes is formal, via the single
quasi-isomorphism `H(A) → A` obtained by choosing cocycle representatives of the generators. -/
theorem isFormal_of_isFreeGradedCommAlgebra [IsCDGA A] {ι : Type*} {deg : ι → ℤ}
    {x : ι → Cohomology A}
    (hx : IsFreeGradedCommAlgebra R (DGAlgebra.gradingSubmodule R (Cohomology A)) deg x) :
    IsFormal A :=
  let ⟨s, hs⟩ := exists_isCohomologySection_of_isFreeGradedCommAlgebra hx
  isFormal_of_isCohomologySection s hs

/-- The formality criterion for a graded-commutative (not necessarily strictly) dg algebra over a
commutative ring in which `2` is invertible: graded commutativity is then strict
(`DG.IsCDGA.of_isGradedComm`). -/
theorem isFormal_of_isFreeGradedCommAlgebra_of_isGradedComm [Invertible (2 : R)]
    [IsGradedComm (DGAlgebra.gradingSubmodule R A)] {ι : Type*} {deg : ι → ℤ}
    {x : ι → Cohomology A}
    (hx : IsFreeGradedCommAlgebra R (DGAlgebra.gradingSubmodule R (Cohomology A)) deg x) :
    IsFormal A :=
  haveI := IsCDGA.of_isGradedComm R (A := A)
  isFormal_of_isFreeGradedCommAlgebra hx

end Criterion

end DG
