import DG.K0.DGRing
import DG.Positive.Schnurer

/-!
# The Grothendieck group of a positive dg ring

Let `A` be a positive dg ring (`DG.IsPositive A`). By Schnürer's theorem every compact object of
`D(A)` has an ordered cell tower with cells `(A e)⟦n⟧`, `e` a simple idempotent of `A⁰`
(`DG.IsPositive.hasOrderedCellTower_of_isCompact`), so its class in `K₀(A) = K₀(D^c(A))` is
`∑ᵢ (-1)^{nᵢ} [A eᵢ]` (Roadmap 6.3, first part).

* `DG.IsPositive.mk_mem_closure_leftCorner`, `DG.IsPositive.closure_leftCorner_eq_top`: `K₀(A)`
  is generated by the classes `[A e]` of the simple idempotents `e` of `A⁰`.

The remaining statements of Roadmap 6.3 (`K₀(A) ≅ K₀(A⁰)`, `[A e] ↦ [A⁰ e]`, and freeness on
the classes of the simple modules) are not formalized here: the first needs the compatibility
of `DG.DGRing.K0.map` with the classes `[A e]` (derived induction of `B e` along `B → A` is
`A φ(e)`), the second an additive invariant separating the simple modules (e.g.
`X ↦ ∑ⱼ (-1)ʲ dim Hom(X, L⟦j⟧)` for the simple modules `L = A⁰ e`, viewed as dg `A`-modules).
-/

open CategoryTheory Limits

universe u

set_option backward.isDefEq.respectTransparency false

namespace DG

namespace IsPositive

variable {A : Type u} [Ring A] [DGAddCommGroup A] [DGRing A] (hA : IsPositive A)
  [HasDerivedCategory.{u, u} A]
include hA

open _root_.DG.DerivedCategory

/-- The class in `K₀(A)` of a compact object of `D(A)` is a `ℤ`-linear combination of the
classes `[A e]` of the simple idempotents `e` of `A⁰` [Sch, Thm. 1]. -/
theorem mk_mem_closure_leftCorner (X : PerfectDerivedCategory.{u, u} A) :
    DG.K0.mk X ∈ AddSubgroup.closure
      (Set.range fun e : SimpleIdempotent A => DGRing.K0.leftCorner (A := A) e.1) := by
  obtain ⟨l, -, hl⟩ := hA.hasOrderedCellTower_of_isCompact (X := X.obj) X.property
  have hc : ∀ (i : SimpleIdempotent A) (n : ℤ), IsCompact.{u} (cell A i.1 n) :=
    fun i n => isCompact_cell i.1 n
  have h := CellTower.mk_eq_sum.{u} hc hl
  change DG.K0.mk (⟨X.obj, X.property⟩ : PerfectDerivedCategory A) ∈ _
  rw [h]
  refine AddSubgroup.list_sum_mem _ fun x hx => ?_
  obtain ⟨c, -, rfl⟩ := List.mem_map.mp hx
  rw [DGRing.K0.mk_cell, Units.smul_def]
  exact AddSubgroup.zsmul_mem _ (AddSubgroup.subset_closure (Set.mem_range_self c.1)) _

/-- `K₀(A)` is generated by the classes `[A e]` of the simple idempotents `e` of `A⁰`
(Roadmap 6.3, generation). -/
theorem closure_leftCorner_eq_top :
    AddSubgroup.closure
      (Set.range fun e : SimpleIdempotent A => DGRing.K0.leftCorner (A := A) e.1) = ⊤ := by
  refine eq_top_iff.mpr fun x _ => ?_
  obtain ⟨X, rfl⟩ := DG.K0.exists_mk_eq x
  exact hA.mk_mem_closure_leftCorner X

end IsPositive

end DG
